import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Animals: cats, dogs, birds, fish, hamsters, the zoo, the neighbourhood strays, wildlife.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const ANIMALS_SKIP: readonly Draft[] = [
  {
    emoji: '🕊️',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Balkona güvercin taşındı. Kira vermiyor.',
      en: 'A pigeon moved onto my balcony. Rent-free.',
      de: 'Eine Taube wohnt jetzt auf dem Balkon. Mietfrei.',
      ar: 'حمامة سكنت شرفتي… ولا تدفع الإيجار',
      fr: 'Un pigeon squatte mon balcon. Zéro loyer.',
      es: 'Una paloma se mudó a mi balcón. No paga alquiler.',
    },
  },
  {
    emoji: '🐜',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Tek kırıntı düşürdüm, 400 misafir geldi',
      en: 'Dropped one crumb. 400 guests showed up.',
      de: 'Ein Krümel gefallen, 400 Gäste gekommen',
      ar: 'أسقطت فتاتة واحدة… فجاء 400 ضيف',
      fr: 'Une miette tombée, 400 invités débarquent',
      es: 'Se me cayó una miga y llegaron 400 invitados',
    },
  },
  {
    emoji: '🦒',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Zürafayla selfie: ben ve iki bacak',
      en: 'Selfie with a giraffe: me and two legs',
      de: 'Selfie mit Giraffe: ich und zwei Beine',
      ar: 'سيلفي مع زرافة: أنا وساقان',
      fr: 'Selfie avec une girafe : moi et deux pattes',
      es: 'Selfie con una jirafa: yo y dos patas',
    },
  },
  {
    emoji: '🐆',
    user: ACCOUNTS.pets,
    body: { format: 'scene' },
    caption: {
      tr: 'Gece 3’te kedi koşusu. Parkur: ben.',
      en: '3 a.m. cat zoomies. The track: me.',
      de: 'Katzenrennen um 3 Uhr nachts. Die Strecke: ich.',
      ar: 'سباق القطة في الثالثة فجرًا… والمضمار أنا',
      fr: 'Sprint du chat à 3 h du mat. La piste : moi.',
      es: 'Carrera gatuna a las 3 de la mañana. La pista: yo.',
    },
  },
  {
    emoji: '🐟',
    user: ACCOUNTS.pets,
    body: { format: 'scene' },
    caption: {
      tr: 'Balığım konuşuyor, ben başımı sallıyorum',
      en: 'My fish talks. I just nod along.',
      de: 'Mein Fisch redet, ich nicke nur.',
      ar: 'سمكتي تتكلم… وأنا أهزّ رأسي فقط',
      fr: 'Mon poisson parle. Moi, je hoche la tête.',
      es: 'Mi pez habla y yo le digo que sí con la cabeza.',
    },
  },
  {
    emoji: '🦗',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Cırcır böceği: sesi her yerde, kendisi yok',
      en: 'Crickets: heard everywhere, seen nowhere',
      de: 'Grille: überall zu hören, nirgends zu sehen',
      ar: 'صرصور الليل: صوته في كل مكان ولا أثر له',
      fr: "Le grillon : on l'entend partout, on le voit nulle part",
      es: 'El grillo: se oye en todas partes y no está en ninguna',
    },
  },
  {
    emoji: '🐄',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'İnekler beni 1 saat izledi. Rekor izlenme.',
      en: 'Cows stared at me for an hour. Record views.',
      de: 'Die Kühe starrten mich eine Stunde an. Rekordquote.',
      ar: 'الأبقار حدّقت بي ساعة كاملة… أعلى مشاهدات لي',
      fr: "Les vaches m'ont fixé une heure. Record d'audience.",
      es: 'Las vacas me miraron una hora. Récord de audiencia.',
    },
  },
  {
    emoji: '🦜',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'senin kuş yine telefon gibi çalıyor',
            en: "your bird's doing the ringtone again",
            de: 'dein Vogel macht wieder den Klingelton',
            ar: 'عصفورك يقلّد رنين الهاتف مجددًا',
            fr: 'ton oiseau refait la sonnerie',
            es: 'tu pájaro imita otra vez el teléfono',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'açmaya koştun mu? 😂',
            en: 'did you run to answer? 😂',
            de: 'bist du hingerannt? 😂',
            ar: 'هل ركضتِ لتردّي؟ 😂',
            fr: "t'as couru répondre ? 😂",
            es: '¿corriste a contestar? 😂',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'koştum. o da “alo” dedi',
            en: 'yep. then it said “hello?”',
            de: 'ja. dann sagte er „Hallo?“',
            ar: 'نعم. ثم قال: «ألو؟»',
            fr: 'oui. et là, il a dit « allô ? »',
            es: 'sí. y luego dijo “¿hola?”',
          },
        },
      ],
    },
    caption: {
      tr: 'Evin en iyi taklitçisi 30 gram',
      en: 'Best impressionist in the house: 30 grams',
      de: 'Bester Imitator im Haus: 30 Gramm',
      ar: 'أفضل مقلّد في البيت وزنه 30 غرامًا',
      fr: 'Meilleur imitateur de la maison : 30 grammes',
      es: 'El mejor imitador de la casa pesa 30 gramos',
    },
  },
  {
    emoji: '😸',
    user: ACCOUNTS.pets,
    body: {
      format: 'chat',
      contact: { tr: 'Komşu', en: 'Neighbor', de: 'Nachbarin', ar: 'الجارة', fr: 'Voisine', es: 'Vecina' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'kediniz yine bizde 🐈',
            en: 'your cat is at our place again 🐈',
            de: 'Ihre Katze ist schon wieder bei uns 🐈',
            ar: 'قطتكم عندنا مرة أخرى 🐈',
            fr: 'votre chat est encore chez nous 🐈',
            es: 'su gato está otra vez en nuestra casa 🐈',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'çok özür dilerim, hemen alıyorum',
            en: 'so sorry, coming to get her',
            de: 'tut mir leid, ich hole sie sofort',
            ar: 'آسف جدًا، سآتي لأخذها حالًا',
            fr: 'désolé, je viens le chercher',
            es: 'perdón, ya voy por él',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'acele etmeyin, yemeğini yedi, uyuyor',
            en: "no rush, she ate and she's napping",
            de: 'keine Eile, sie hat gegessen und schläft',
            ar: 'لا داعي للعجلة، أكلت وهي نائمة',
            fr: 'rien ne presse, il a mangé, il dort',
            es: 'sin prisa, ya comió y está durmiendo',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bu arada adını değiştirdik',
            en: 'also, we renamed her',
            de: 'übrigens haben wir sie umbenannt',
            ar: 'وبالمناسبة، غيّرنا اسمها',
            fr: "au fait, on l'a rebaptisé",
            es: 'por cierto, le cambiamos el nombre',
          },
        },
      ],
    },
    caption: {
      tr: 'Kedimin ikinci bir ailesi var',
      en: 'My cat has a second family',
      de: 'Meine Katze hat eine Zweitfamilie',
      ar: 'لقطتي عائلة ثانية',
      fr: 'Mon chat a une deuxième famille',
      es: 'Mi gato tiene una segunda familia',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kardeşim',
        en: 'Little bro',
        de: 'Brüderchen',
        ar: 'أخي',
        fr: 'Frérot',
        es: 'Hermanito',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'kediye mama verdin mi?',
            en: 'did you feed the cat?',
            de: 'hast du die Katze gefüttert?',
            ar: 'هل أطعمت القطة؟',
            fr: "t'as nourri le chat ?",
            es: '¿le diste de comer al gato?',
          },
        },
        {
          from: 'them',
          text: { tr: 'verdim', en: 'yep', de: 'jep', ar: 'نعم', fr: 'ouais', es: 'sí' },
        },
        {
          from: 'me',
          text: {
            tr: 'ben de verdim 😳',
            en: 'so did I 😳',
            de: 'ich auch 😳',
            ar: 'وأنا أيضًا 😳',
            fr: 'moi aussi 😳',
            es: 'yo también 😳',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'annem de vermiş. babam da.',
            en: 'so did mom. and dad.',
            de: 'Mama auch. und Papa.',
            ar: 'وأمي أيضًا… وأبي كذلك',
            fr: 'maman aussi. et papa.',
            es: 'mamá también. y papá.',
          },
        },
      ],
    },
    caption: {
      tr: 'Her birimize ayrı ayrı aç numarası yapmış',
      en: 'She pulled the hungry act on each of us',
      de: 'Sie hat jedem von uns Hunger vorgespielt',
      ar: 'مثّلت دور الجائعة على كل واحد منا',
      fr: 'Il nous a tous eus avec son air affamé',
      es: 'Se hizo el hambriento con cada uno',
    },
  },
  {
    emoji: '🤳',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'köpekle parka geldik 🥰',
            en: 'at the park with the dog 🥰',
            de: 'mit dem Hund im Park 🥰',
            ar: 'في الحديقة مع الكلب 🥰',
            fr: 'au parc avec le chien 🥰',
            es: 'en el parque con el perro 🥰',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hani bu eve köpek girmezdi?',
            en: 'what happened to “no dogs in this house”?',
            de: 'hieß es nicht „kein Hund in diesem Haus“?',
            ar: 'ألم تقل إن هذا البيت لا يدخله كلب؟',
            fr: "c'était pas « jamais de chien ici » ?",
            es: '¿no decías que aquí no entraban perros?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'o ayrı. o bizim oğlan.',
            en: "that's different. he's our boy.",
            de: 'das ist was anderes. er ist unser Junge.',
            ar: 'هذا مختلف، إنه ولدنا',
            fr: "c'est pas pareil. c'est notre fiston.",
            es: 'eso es distinto. es nuestro niño.',
          },
        },
      ],
    },
    caption: {
      tr: 'Evin en katı kuralı 1 hafta dayandı',
      en: "The house's strictest rule lasted a week",
      de: 'Die strengste Hausregel hielt eine Woche',
      ar: 'أصرم قاعدة في البيت صمدت أسبوعًا',
      fr: "La règle d'or de la maison a tenu une semaine",
      es: 'La regla más estricta de la casa duró una semana',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Evcil hayvanınla konuşurken sesin:',
        en: 'Your voice when you talk to your pet:',
        de: 'Deine Stimme, wenn du mit dem Haustier redest:',
        ar: 'صوتك عندما تتحدث إلى حيوانك الأليف:',
        fr: 'Ta voix quand tu parles à ton animal :',
        es: 'Tu voz cuando le hablas a tu mascota:',
      },
      options: [
        {
          tr: 'Her zamanki sesim',
          en: 'My normal voice',
          de: 'Meine normale Stimme',
          ar: 'صوتي العادي',
          fr: 'Ma voix normale',
          es: 'Mi voz normal',
        },
        {
          tr: '3 oktav daha ince',
          en: 'Three octaves higher',
          de: 'Drei Oktaven höher',
          ar: 'أعلى بثلاث طبقات',
          fr: '3 octaves plus haut',
          es: 'Tres octavas más aguda',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Komşu duydu, artık geri dönüş yok',
      en: 'The neighbor heard. No going back.',
      de: "Der Nachbar hat's gehört. Kein Zurück.",
      ar: 'سمعني الجار… ولا مجال للتراجع',
      fr: 'Le voisin a entendu. Pas de retour en arrière.',
      es: 'El vecino me oyó. Ya no hay vuelta atrás.',
    },
  },
  {
    emoji: '🏘️',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Mahallenin kedisinin adı ne?',
        en: "What's the neighborhood cat's name?",
        de: 'Wie heißt die Katze aus dem Viertel?',
        ar: 'ما اسم قطة الحي؟',
        fr: "Comment s'appelle le chat du quartier ?",
        es: '¿Cómo se llama el gato del barrio?',
      },
      options: [
        { tr: 'Paşa', en: 'Tiger', de: 'Minka', ar: 'مشمش', fr: 'Minou', es: 'Michi' },
        { tr: 'Duman', en: 'Smokey', de: 'Tiger', ar: 'سمسم', fr: 'Caramel', es: 'Pelusa' },
        {
          tr: 'Hepsi',
          en: 'All of the above',
          de: 'Alle drei',
          ar: 'كلها',
          fr: 'Tous ces noms',
          es: 'Todos esos',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: '7 adı var, hiçbirine dönüp bakmıyor',
      en: 'Seven names. Answers to none.',
      de: 'Sieben Namen. Hört auf keinen.',
      ar: 'لها سبعة أسماء ولا تلتفت لأيٍّ منها',
      fr: 'Sept noms. Il ne répond à aucun.',
      es: 'Siete nombres y no responde a ninguno',
    },
  },
  {
    emoji: '🦁',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Hayvanat bahçesinde aslanı gördün mü?',
        en: 'Did you see the lion at the zoo?',
        de: 'Hast du im Zoo den Löwen gesehen?',
        ar: 'هل رأيت الأسد في حديقة الحيوان؟',
        fr: "T'as vu le lion au zoo ?",
        es: '¿Viste al león en el zoológico?',
      },
      options: [
        {
          tr: 'Gördüm, kükredi!',
          en: 'Yes, it roared!',
          de: 'Ja, er hat gebrüllt!',
          ar: 'نعم، وزأر!',
          fr: 'Oui, il a rugi !',
          es: '¡Sí, rugió!',
        },
        {
          tr: 'Uyuyan bir sırt gördüm',
          en: 'Just a snoozing back',
          de: 'Einen dösenden Rücken',
          ar: 'رأيت ظهرًا نائمًا',
          fr: 'Un dos qui dort',
          es: 'Vi una espalda dormida',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: '2 saat bekledim, bir kez kulağını oynattı',
      en: 'Waited 2 hours. One ear twitch.',
      de: '2 Stunden gewartet. Ein Ohr hat gezuckt.',
      ar: 'انتظرت ساعتين… فحرّك أذنه مرة واحدة',
      fr: "2 h d'attente. Une oreille a bougé.",
      es: 'Esperé 2 horas. Movió una oreja.',
    },
  },
  {
    emoji: '🐹',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'HAMSTERIN GECE KOŞUSU',
        en: "MY HAMSTER'S NIGHT RUN",
        de: 'NACHTLAUF DES HAMSTERS',
        ar: 'جري الهامستر ليلًا',
        fr: 'HAMSTER EN ROUE LIBRE',
        es: 'MARATÓN DEL HÁMSTER',
      },
      value: { tr: '9 km', en: '9 km', de: '9 km', ar: '9 كم', fr: '9 km', es: '9 km' },
      shape: 'rise',
      axis: 'hours',
    },
    caption: {
      tr: 'O çarkta, ben akışta. Yerimizde sayıyoruz.',
      en: "He's on his wheel, I'm on my feed. Going nowhere.",
      de: 'Er im Laufrad, ich im Feed. Beide auf der Stelle.',
      ar: 'هو على عجلته وأنا على الخلاصة… ولا نتقدم خطوة',
      fr: 'Lui dans sa roue, moi dans mon fil : du surplace.',
      es: 'Él en su rueda, yo en el feed. Ninguno avanza.',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.pets,
    body: {
      format: 'chart',
      title: {
        tr: 'KÖPEĞİMİN SEVİNCİ',
        en: "MY DOG'S JOY LEVEL",
        de: 'FREUDE MEINES HUNDES',
        ar: 'فرحة كلبي',
        fr: 'LA JOIE DE MON CHIEN',
        es: 'LA ALEGRÍA DE MI PERRO',
      },
      value: null,
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Çöpü atıp döndüm, 10 yıl olmuş sanki',
      en: "Took out the trash. He acted like it'd been years.",
      de: 'Müll rausgebracht. Empfang wie nach 10 Jahren.',
      ar: 'أخرجت القمامة وعدت… فاستقبلني كأنني غبت 10 سنوات',
      fr: "Poubelle sortie. Accueil digne de 10 ans d'absence.",
      es: 'Saqué la basura y me recibió como tras 10 años',
    },
  },
  {
    emoji: '🧶',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'PET SHOP',
        en: 'PET STORE',
        de: 'ZOOHANDLUNG',
        ar: 'متجر الحيوانات',
        fr: 'ANIMALERIE',
        es: 'TIENDA DE MASCOTAS',
      },
      items: [
        {
          tr: 'TÜY RULOSU (12 ADET)',
          en: 'LINT ROLLERS (12)',
          de: 'FUSSELROLLEN ×12',
          ar: 'بكرات إزالة الوبر (12)',
          fr: 'ROULEAUX ADHÉSIFS ×12',
          es: 'QUITAPELUSAS (12)',
        },
      ],
    },
    caption: {
      tr: 'Siyah kazak aldım, kedi desenli çıktı',
      en: "Bought a black sweater. It's cat print now.",
      de: 'Schwarzer Pulli gekauft. Jetzt mit Katzenmuster.',
      ar: 'اشتريت كنزة سوداء… فصارت بنقشة قطط',
      fr: 'Pull noir acheté. Il est à motif chat, maintenant.',
      es: 'Me compré un suéter negro. Ahora es estampado de gato.',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.home,
    body: {
      format: 'receipt',
      store: {
        tr: 'MARKET',
        en: 'GROCERY STORE',
        de: 'SUPERMARKT',
        ar: 'سوبرماركت',
        fr: 'SUPÉRETTE',
        es: 'SUPERMERCADO',
      },
      items: [
        {
          tr: 'KUŞ YEMİ (5 KG)',
          en: 'BIRDSEED (5 KG)',
          de: 'VOGELFUTTER (5 KG)',
          ar: 'حبوب للطيور (5 كغ)',
          fr: 'GRAINES OISEAUX (5 KG)',
          es: 'ALPISTE (5 KG)',
        },
      ],
    },
    caption: {
      tr: 'Balkona 1 serçe geliyordu. Artık 40.',
      en: "One sparrow used to visit my balcony. Now it's 40.",
      de: 'Früher kam ein Spatz auf den Balkon. Jetzt 40.',
      ar: 'كان عصفور واحد يزور شرفتي… صاروا 40',
      fr: 'Avant, un moineau au balcon. Maintenant, 40.',
      es: 'Antes venía un gorrión al balcón. Ahora vienen 40.',
    },
  },
  {
    emoji: '🐠',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'AKVARYUMCU',
        en: 'AQUARIUM SHOP',
        de: 'AQUARISTIK',
        ar: 'متجر الأحياء المائية',
        fr: "MAGASIN D'AQUARIUMS",
        es: 'TIENDA DE ACUARIOS',
      },
      items: [
        {
          tr: 'AKVARYUM KALESİ',
          en: 'AQUARIUM CASTLE',
          de: 'AQUARIUM-BURG',
          ar: 'قلعة لحوض السمك',
          fr: "CHÂTEAU D'AQUARIUM",
          es: 'CASTILLO PARA PECERA',
        },
        {
          tr: 'MİNİ BATIK GEMİ',
          en: 'MINI SHIPWRECK',
          de: 'MINI-SCHIFFSWRACK',
          ar: 'سفينة غارقة صغيرة',
          fr: 'MINI ÉPAVE',
          es: 'MINI BARCO HUNDIDO',
        },
      ],
    },
    caption: {
      tr: 'Balığımın evi benimkinden şık',
      en: "My fish's place is nicer than mine",
      de: 'Mein Fisch wohnt schicker als ich',
      ar: 'بيت سمكتي أفخم من بيتي',
      fr: 'Mon poisson est mieux logé que moi',
      es: 'Mi pez vive mejor que yo',
    },
  },
  {
    emoji: '😻',
    user: ACCOUNTS.pets,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'EVCİL HAYVAN RAPORU',
        en: 'PET REPORT',
        de: 'HAUSTIER-REPORT',
        ar: 'تقرير الحيوان الأليف',
        fr: 'RAPPORT ANIMAL',
        es: 'INFORME DE MASCOTA',
      },
      big: { tr: '23', en: '23', de: '23', ar: '23', fr: '23', es: '23' },
      text: {
        tr: 'farklı lakap taktın kedine. Asıl adını unuttun bile.',
        en: 'different nicknames for your cat. You forgot her real name.',
        de: 'Spitznamen für deine Katze. Den echten Namen hast du vergessen.',
        ar: 'لقبًا أطلقته على قطتك… ونسيت اسمها الحقيقي',
        fr: 'surnoms pour ton chat. Tu as oublié son vrai nom.',
        es: 'apodos para tu gata. Ya olvidaste su nombre real.',
      },
    },
    caption: {
      tr: 'Pamuk, Pamukçuk, Patates, Minnoş…',
      en: 'Mittens, Mitty, Potato, Sir Fluff…',
      de: 'Mimi, Mimilein, Kartoffel, Flauschi…',
      ar: 'مشمش، مشمشة، بطاطا، يا قمر…',
      fr: 'Minou, Minouche, Patate, Boule de poils…',
      es: 'Michi, Michita, Papita, Bolita…',
    },
  },
  {
    emoji: '🧀',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'KÖPEĞİNİN SÜPER GÜCÜ',
        en: "YOUR DOG'S SUPERPOWER",
        de: 'SUPERKRAFT DEINES HUNDES',
        ar: 'قوة كلبك الخارقة',
        fr: 'SUPERPOUVOIR CANIN',
        es: 'SUPERPODER CANINO',
      },
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'oda öteden peynir paketinin sesini duydu. Adını duymadı.',
        en: 'rooms away, he heard the cheese wrapper. Not his name, though.',
        de: 'Zimmer weiter hört er die Käsepackung. Seinen Namen nicht.',
        ar: 'غرف تفصله عن كيس الجبن وقد سمعه… أما اسمه فلا',
        fr: 'pièces plus loin, il entend le sachet de fromage. Pas son nom.',
        es: 'habitaciones más allá oye el paquete de queso. Su nombre, no.',
      },
    },
    caption: {
      tr: 'Seçici işitme, ileri seviye',
      en: 'Selective hearing, expert level',
      de: 'Selektives Hören, Profi-Level',
      ar: 'سمع انتقائي، مستوى متقدم',
      fr: 'Audition sélective, niveau expert',
      es: 'Oído selectivo, nivel experto',
    },
  },
  {
    emoji: '👣',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BUGÜNKÜ YÜRÜYÜŞ',
        en: "TODAY'S WALK",
        de: 'HEUTIGER SPAZIERGANG',
        ar: 'نزهة اليوم',
        fr: 'LA BALADE DU JOUR',
        es: 'EL PASEO DE HOY',
      },
      big: { tr: '6.214', en: '6,214', de: '6.214', ar: '6,214', fr: '6 214', es: '6214' },
      text: {
        tr: 'adım attın. Rotayı köpeğin çizdi, sen sadece tasmayı tuttun.',
        en: 'steps today. Your dog picked the route; you held the leash.',
        de: 'Schritte. Die Route wählte dein Hund, du hieltst nur die Leine.',
        ar: 'خطوة اليوم. كلبك اختار الطريق وأنت أمسكت المقود فقط',
        fr: "pas aujourd'hui. Ton chien a choisi la route, toi la laisse.",
        es: 'pasos hoy. La ruta la eligió tu perro; tú, la correa.',
      },
    },
    caption: {
      tr: 'Kim kimi gezdiriyor, belli değil',
      en: "Who's walking who, exactly?",
      de: 'Wer führt hier eigentlich wen aus?',
      ar: 'من يأخذ من في نزهة؟',
      fr: 'Qui promène qui, au juste ?',
      es: '¿Quién pasea a quién?',
    },
  },
  {
    emoji: '🐌',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'HAFTANIN DİZİSİ',
        en: 'SHOW OF THE WEEK',
        de: 'SERIE DER WOCHE',
        ar: 'مسلسل الأسبوع',
        fr: 'LA SÉRIE DE LA SEMAINE',
        es: 'LA SERIE DE LA SEMANA',
      },
      big: { tr: '40', en: '40', de: '40', ar: '40', fr: '40', es: '40' },
      text: {
        tr: 'dakika balkondaki salyangozu izledin. Hiç kaydırmadın.',
        en: 'minutes watching a snail cross the balcony. Zero scrolling.',
        de: 'Minuten einer Balkonschnecke zugesehen. Null gescrollt.',
        ar: 'دقيقة تتابع حلزونًا يعبر الشرفة… دون أي تمرير',
        fr: 'minutes à regarder un escargot sur le balcon. Zéro scroll.',
        es: 'minutos viendo un caracol cruzar el balcón. Cero scroll.',
      },
    },
    caption: {
      tr: 'Yılın en sürükleyici yapımı',
      en: "Most gripping thing I've seen all year",
      de: 'Spannendste Produktion des Jahres',
      ar: 'أكثر عمل مشوّق هذا العام',
      fr: "La production la plus haletante de l'année",
      es: 'La producción más emocionante del año',
    },
  },
  {
    emoji: '🦟',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'BALKON MİSAFİRLERİ TIER LIST',
        en: 'BALCONY GUESTS TIER LIST',
        de: 'BALKONBESUCH-TIER-LIST',
        ar: 'تصنيف ضيوف الشرفة',
        fr: 'TIER LIST DU BALCON',
        es: 'TIER LIST DEL BALCÓN',
      },
      rows: [['🐝', '🦋'], ['🐞', '🐦'], ['🐛', '🐜'], ['🦟', '🪰']],
    },
    caption: {
      tr: 'Sivrisinek C: ışık sönünce gelen misafir',
      en: "Mosquito's C: only visits once the lights are off",
      de: 'Mücke: C. Kommt erst, wenn das Licht aus ist.',
      ar: 'البعوضة في الأخير: لا تزور إلا بعد إطفاء النور',
      fr: "Moustique en C : il attend que la lumière s'éteigne",
      es: 'Mosquito en C: solo viene con la luz apagada',
    },
  },
  {
    emoji: '🐓',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ÇİFTLİK TIER LIST',
        en: 'FARM ANIMAL TIER LIST',
        de: 'BAUERNHOF-TIER-LIST',
        ar: 'تصنيف حيوانات المزرعة',
        fr: 'TIER LIST DE LA FERME',
        es: 'TIER LIST DE LA GRANJA',
      },
      rows: [['🐐', '🐑'], ['🐄', '🐴'], ['🦆', '🐔'], ['🐓']],
    },
    caption: {
      tr: 'Horoz C: saati bozuk, öğlen 2’de ötüyor',
      en: "Rooster's C: his clock's off, crows at 2 p.m.",
      de: 'Hahn: C. Innere Uhr kaputt, kräht um 14 Uhr.',
      ar: 'الديك في الأخير: ساعته معطّلة ويصيح ظهرًا',
      fr: 'Le coq en C : il chante à 14 h',
      es: 'Gallo en C: canta a las 2 de la tarde',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '📹',
        app: {
          tr: 'Pati kamerası',
          en: 'Pet cam',
          de: 'Haustier-Kamera',
          ar: 'كاميرا الحيوان',
          fr: 'Caméra animaux',
          es: 'Cámara mascota',
        },
        text: {
          tr: 'Hareket algılandı: köpek yine kanepede',
          en: 'Motion detected: dog on couch, again',
          de: 'Bewegung: Hund wieder auf dem Sofa',
          ar: 'رُصدت حركة: الكلب على الأريكة مجددًا',
          fr: 'Mouvement : chien sur le canapé (encore)',
          es: 'Movimiento: el perro otra vez en el sofá',
        },
      },
    },
    caption: {
      tr: 'Kameraya baktı. İnmedi.',
      en: 'He looked right at the camera. Stayed put.',
      de: 'Er sah in die Kamera. Und blieb liegen.',
      ar: 'نظر إلى الكاميرا… ولم ينزل',
      fr: 'Il a regardé la caméra. Il est resté.',
      es: 'Miró a la cámara. No se bajó.',
    },
  },
  {
    emoji: '🐩',
    user: ACCOUNTS.pets,
    body: {
      format: 'notifications',
      first: {
        icon: '✂️',
        app: {
          tr: 'Pati kuaförü',
          en: 'Pet groomer',
          de: 'Hundesalon',
          ar: 'صالون الحيوانات',
          fr: 'Toiletteur',
          es: 'Peluquería canina',
        },
        text: {
          tr: 'Köpeğiniz hazır. Tanımayabilirsiniz.',
          en: "He's ready. You may not recognize him.",
          de: 'Abholbereit – kaum wiederzuerkennen!',
          ar: 'كلبك جاهز… وقد لا تتعرّف عليه',
          fr: 'Il est prêt. Méconnaissable !',
          es: 'Tu perro está listo. ¿Lo reconocerás?',
        },
      },
    },
    caption: {
      tr: 'Bıraktığım köpek bu değildi',
      en: "That's not the dog I dropped off",
      de: 'Das ist nicht der Hund, den ich abgegeben hab',
      ar: 'هذا ليس الكلب الذي تركته عندهم',
      fr: "C'est pas le chien que j'ai déposé",
      es: 'Ese no es el perro que dejé',
    },
  },
  {
    emoji: '🔴',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kedim kırmızı noktayı hiç yakalayamadı. Bir gün bile vazgeçmedi.',
        en: 'My cat never caught the red dot. Not once did she give up.',
        de: 'Meine Katze hat den roten Punkt nie erwischt. Aufgegeben hat sie nie.',
        ar: 'قطتي لم تمسك النقطة الحمراء يومًا… ولم تستسلم يومًا.',
        fr: "Mon chat n'a jamais attrapé le point rouge. Il n'a jamais abandonné.",
        es: 'Mi gata nunca atrapó el punto rojo. Nunca se rindió.',
      },
    },
    caption: {
      tr: 'Ben ilk denemede bırakırdım',
      en: "I'd have quit on the first try",
      de: 'Ich hätte nach einem Versuch aufgehört',
      ar: 'أنا كنت سأستسلم من أول محاولة',
      fr: "Moi, j'aurais lâché au premier essai",
      es: 'Yo me habría rendido al primer intento',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her gün aynı sokağı ilk kez görüyormuş gibi yürü.',
        en: "Walk the same street every day like it's brand new.",
        de: 'Lauf jeden Tag dieselbe Straße, als wäre sie neu.',
        ar: 'امشِ في الشارع نفسه كل يوم كأنك تراه لأول مرة.',
        fr: 'Parcours la même rue chaque jour comme si elle était neuve.',
        es: 'Recorre la misma calle cada día como si fuera nueva.',
      },
    },
    caption: {
      tr: 'Köpeğim 5 yıldır aynı sokağı keşfediyor',
      en: "My dog's been discovering the same block for 5 years",
      de: 'Mein Hund entdeckt seit 5 Jahren dieselbe Straße',
      ar: 'كلبي يكتشف الشارع نفسه منذ 5 سنوات',
      fr: 'Mon chien découvre la même rue depuis 5 ans',
      es: 'Mi perro lleva 5 años descubriendo la misma calle',
    },
  },
  {
    emoji: '🌀',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hedefinin peşinden koş. Kendi kuyruğun bile olsa.',
        en: "Chase your dreams. Even if it's your own tail.",
        de: 'Jag deinen Träumen nach. Auch wenn du dich dabei im Kreis drehst.',
        ar: 'طارد أحلامك، حتى لو كانت ذيلك.',
        fr: "Poursuis tes rêves. Même s'ils tournent en rond.",
        es: 'Persigue tus sueños, aunque den vueltas en círculo.',
      },
    },
    caption: {
      tr: 'Köpeğim 10 dakikadır bu hedefin peşinde',
      en: "My dog's been chasing this goal for 10 minutes",
      de: 'Mein Hund verfolgt dieses Ziel seit 10 Minuten',
      ar: 'كلبي يطارد هذا الهدف منذ 10 دقائق',
      fr: 'Mon chien poursuit ce rêve depuis 10 minutes',
      es: 'Mi perro lleva 10 minutos tras esta meta',
    },
  },
  {
    emoji: '💻',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Kedi gibi ol: istediğin yere otur, kimseye açıklama yapma.',
        en: 'Be like a cat: sit wherever you want and explain nothing.',
        de: 'Sei wie eine Katze: Setz dich, wohin du willst. Erklär nichts.',
        ar: 'كن كالقطة: اجلس حيث تشاء ولا تبرّر لأحد.',
        fr: 'Sois comme un chat : assieds-toi où tu veux, sans te justifier.',
        es: 'Sé como un gato: siéntate donde quieras y no expliques nada.',
      },
    },
    caption: {
      tr: 'Laptopun üstü dahil',
      en: 'Laptop included',
      de: 'Auch auf dem Laptop',
      ar: 'حتى فوق الحاسوب',
      fr: 'Clavier compris',
      es: 'Incluido el teclado',
    },
  },
];

export const ANIMALS_LIKE: readonly Draft[] = [
  {
    emoji: '🐱',
    user: ACCOUNTS.defne,
    body: { format: 'scene' },
    caption: {
      tr: 'sokak kedisini sahiplendim, o da yatağımı',
      en: 'adopted a street cat. she adopted my bed',
      de: 'hab eine straßenkatze adoptiert, sie mein bett',
      ar: 'تبنّيت قطة من الشارع… وهي تبنّت سريري',
      fr: "j'ai adopté un chat des rues, il a adopté mon lit",
      es: 'adopté una gata callejera y ella adoptó mi cama',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.tolga,
    body: { format: 'scene' },
    caption: {
      tr: 'köpeğim denizi ilk kez gördü, dalgalarla tartıştı',
      en: "my dog met the sea today. he's arguing with the waves",
      de: 'mein hund kennt jetzt das meer. er streitet mit den wellen',
      ar: 'كلبي رأى البحر لأول مرة… وبدأ يجادل الأمواج',
      fr: '1re fois à la mer : mon chien se dispute avec les vagues',
      es: 'mi perro vio el mar por primera vez y discutió con las olas',
    },
  },
  {
    emoji: '🐣',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'civcivler çıktı, biri beni annesi sandı',
      en: "the chicks hatched and one thinks i'm its mom",
      de: 'die küken sind geschlüpft, eins hält mich für seine mama',
      ar: 'فقست الكتاكيت… وأحدها يظنني أمه',
      fr: "les poussins sont nés, l'un d'eux me prend pour sa mère",
      es: 'nacieron los pollitos y uno cree que soy su mamá',
    },
  },
  {
    emoji: '🐹',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'hamsterıma 3 saatte labirent yaptım, 4 saniyede çözdü',
      en: '3-hour maze for my hamster. solved in 4 seconds',
      de: 'labyrinth für meinen hamster: 3 std. gebaut, 4 sek. gelöst',
      ar: 'بنيت متاهة لهامستري في 3 ساعات… فحلّها في 4 ثوانٍ',
      fr: "j'ai mis 3 h à faire un labyrinthe. mon hamster, 4 s.",
      es: '3 horas de laberinto y mi hámster salió en 4 segundos',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.berk,
    body: {
      format: 'polaroid',
      note: {
        tr: 'favori mekânı',
        en: 'his favorite hangout',
        de: 'sein lieblingsort',
        ar: 'مكانه المفضّل',
        fr: 'son endroit préféré',
        es: 'su lugar favorito',
      },
    },
    caption: {
      tr: 'veterinerde ödül yedi, her gün oraya çekiyor',
      en: 'got a treat at the vet. now he pulls me there every day',
      de: "beim tierarzt gab's ein leckerli. jetzt zieht er täglich hin",
      ar: 'أخذ مكافأة عند البيطري… والآن يجرّني إليه كل يوم',
      fr: 'friandise chez le véto : il veut y aller tous les jours',
      es: 'premio en el veterinario: ahora quiere ir todos los días',
    },
  },
  {
    emoji: '🦩',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ben ve hocalarım',
        en: 'me & my coaches',
        de: 'ich und meine trainer',
        ar: 'أنا ومدرّباتي',
        fr: 'moi et mes profs',
        es: 'yo y mis maestros',
      },
    },
    caption: {
      tr: 'flamingolarla aynı poz (ben 2 saniye dayandım)',
      en: 'same pose as the flamingos (i lasted 2 seconds)',
      de: 'gleiche pose wie die flamingos (ich hielt 2 sekunden)',
      ar: 'نفس وقفة طيور النحام… صمدت ثانيتين فقط',
      fr: "même pose que les flamants roses (j'ai tenu 2 secondes)",
      es: 'misma pose que los flamencos (aguanté 2 segundos)',
    },
  },
  {
    emoji: '🐴',
    user: ACCOUNTS.arda,
    body: {
      format: 'polaroid',
      note: {
        tr: 'direksiyon onda',
        en: "he's driving",
        de: 'er lenkt',
        ar: 'القيادة له',
        fr: "c'est lui qui conduit",
        es: 'él lleva las riendas',
      },
    },
    caption: {
      tr: 'ilk binicilik dersim: at nereye, ben oraya',
      en: 'first riding lesson: wherever the horse goes, i go',
      de: 'erste reitstunde: wohin das pferd will, da will ich auch',
      ar: 'أول درس ركوب خيل: حيث يذهب الحصان أذهب',
      fr: "1er cours d'équitation : là où va le cheval, je vais",
      es: 'primera clase de equitación: voy a donde quiere el caballo',
    },
  },
  {
    emoji: '🐱',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'doğum günü kızı 🎂',
        en: 'birthday girl 🎂',
        de: 'geburtstagskind 🎂',
        ar: 'صاحبة العيد 🎂',
        fr: 'reine du jour 🎂',
        es: 'la cumpleañera 🎂',
      },
    },
    caption: {
      tr: 'kedim şapkayı 1 saniye taktı, o saniyeyi yakaladım',
      en: 'my cat kept the party hat on for 1 second. i got it',
      de: 'meine katze trug den partyhut 1 sekunde. erwischt!',
      ar: 'قطتي لبست قبعة الحفلة ثانية واحدة… والتقطتها!',
      fr: 'ma minette a gardé le chapeau 1 seconde. photo prise !',
      es: 'mi gata aguantó el gorrito 1 segundo y lo capturé',
    },
  },
  {
    emoji: '🐩',
    user: ACCOUNTS.onur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ikiz kombin',
        en: 'matching fit',
        de: 'partnerlook',
        ar: 'إطلالة متطابقة',
        fr: 'tenue assortie',
        es: 'conjunto a juego',
      },
    },
    caption: {
      tr: 'köpeğimle aynı pijamayı aldık, ona daha çok yakıştı',
      en: 'got matching pajamas with my dog. he pulls it off better',
      de: 'partnerlook-pyjama mit meinem hund. ihm steht er besser',
      ar: 'بيجامة مطابقة لي ولكلبي… وهي عليه أجمل',
      fr: 'pyjama assorti avec mon chien. ça lui va mieux',
      es: 'pijama a juego con mi perro. a él le queda mejor',
    },
  },
  {
    emoji: '🕊️',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🕊️', '🦒', '🐘', '🦁'] },
    caption: {
      tr: 'hayvanat bahçesi dump’ı: en çok güvercini çektim',
      en: 'zoo dump: most of my photos are pigeons',
      de: 'zoo-dump: die meisten fotos sind tauben',
      ar: 'رحلة حديقة الحيوان: معظم صوري للحمام',
      fr: "dump du zoo : la plupart de mes photos, c'est des pigeons",
      es: 'día en el zoológico: la mayoría de mis fotos son palomas',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['🐶', '🩴', '🧸', '🛋️'] },
    caption: {
      tr: 'yavrumun ilk haftası: 2 terlik, 1 minder, bol sevgi',
      en: "puppy's first week: 2 slippers, 1 cushion, endless love",
      de: 'welpe, woche 1: 2 hausschuhe, 1 kissen, ganz viel liebe',
      ar: 'أسبوع الجرو الأول: خفّان، ووسادة، وحب لا ينتهي',
      fr: '1re semaine du chiot : 2 chaussons, 1 coussin, amour infini',
      es: 'cachorro, semana 1: 2 pantuflas, 1 cojín, amor infinito',
    },
  },
  {
    emoji: '🔭',
    user: ACCOUNTS.baris,
    body: { format: 'dump', emojis: ['🔭', '🌲', '🐦', '🥪', '🥾'] },
    caption: {
      tr: 'kuş gözlemi: 6 saat, 1 serçe, çok mutluyum',
      en: 'birdwatching: 6 hours, 1 sparrow, so happy',
      de: 'vogelbeobachtung: 6 stunden, 1 spatz, überglücklich',
      ar: 'مراقبة الطيور: 6 ساعات، عصفور واحد، وسعادة كبيرة',
      fr: 'sortie ornitho : 6 h, 1 moineau, trop heureux',
      es: 'observando aves: 6 horas, 1 gorrión y mucha felicidad',
    },
  },
];

export const ANIMALS_HOLD: readonly Draft[] = [
  {
    emoji: '🎾',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir an: köpek topu getirdi ve bıraktı',
      en: 'Rare moment: the dog brought the ball AND let go',
      de: 'Seltener Moment: Der Hund bringt den Ball UND lässt los',
      ar: 'لحظة نادرة: أحضر الكلب الكرة… وتركها!',
      fr: 'Moment rare : le chien rapporte la balle ET la lâche',
      es: 'Momento único: el perro trajo la pelota Y la soltó',
    },
  },
  {
    emoji: '🦚',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tavus kuşu kuyruğunu açtı. Sadece senin için.',
      en: 'The peacock fanned its tail. Just for you.',
      de: 'Der Pfau schlägt ein Rad. Nur für dich.',
      ar: 'الطاووس فرد ذيله… من أجلك وحدك',
      fr: 'Le paon fait la roue. Rien que pour toi.',
      es: 'El pavo real abrió la cola. Solo para ti.',
    },
  },
  {
    emoji: '🐬',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Vapurdan yunus göründü! 3 saniye sonra dalacak',
      en: 'Dolphin by the ferry! It dives again in 3 seconds',
      de: 'Delfin neben der Fähre! In 3 Sekunden taucht er ab',
      ar: 'دلفين بجانب العبّارة! سيغوص بعد 3 ثوانٍ',
      fr: 'Un dauphin près du ferry ! Il replonge dans 3 secondes',
      es: '¡Un delfín junto al barco! Se sumerge en 3 segundos',
    },
  },
  {
    emoji: '🦴',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayıp hazine bulundu: köpeğin gizli kemik zulası',
      en: "Lost treasure found: the dog's secret bone stash",
      de: 'Schatz gefunden: das geheime Knochenlager vom Hund',
      ar: 'عُثر على الكنز المفقود: مخبأ عظام الكلب السري',
      fr: "Trésor retrouvé : la réserve secrète d'os du chien",
      es: 'Tesoro encontrado: el escondite secreto de huesos del perro',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Gündüz uyanık bir baykuş. Milyonda bir.',
      en: 'An owl, wide awake at noon. One in a million.',
      de: 'Eine Eule, mittags hellwach. Eins zu einer Million.',
      ar: 'بومة مستيقظة في عزّ النهار… واحدة في المليون',
      fr: 'Une chouette réveillée à midi. Une sur un million.',
      es: 'Un búho despierto al mediodía. Uno en un millón.',
    },
  },
  {
    emoji: '🐠',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kalesinden hiç çıkmayan balık sonunda göründü',
      en: 'The fish that never leaves its castle came out',
      de: 'Der Fisch, der nie aus seiner Burg kommt, ist draußen',
      ar: 'السمكة التي لا تغادر قلعتها خرجت أخيرًا',
      fr: 'Le poisson qui ne quitte jamais son château est sorti',
      es: 'El pez que nunca sale de su castillo por fin salió',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi kare: 3 patili, 3’ü de kameraya bakıyor',
      en: 'Legendary shot: all 3 pets looking at the camera',
      de: 'Legendäres Foto: Alle 3 Haustiere schauen in die Kamera',
      ar: 'لقطة أسطورية: الحيوانات الثلاثة تنظر إلى الكاميرا',
      fr: "Photo légendaire : les 3 animaux regardent l'objectif",
      es: 'Foto legendaria: las 3 mascotas mirando a la cámara',
    },
  },
];

export const ANIMALS_FREEZE: readonly Draft[] = [
  {
    emoji: '💤',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: { tr: 'MEŞGUL', en: 'OCCUPIED', de: 'BESETZT', ar: 'مشغول', fr: 'OCCUPÉ', es: 'OCUPADO' },
      small: {
        tr: 'KEDİ KUCAKTA UYUYOR',
        en: 'CAT ASLEEP ON LAP',
        de: 'KATZE SCHLÄFT AUF DEM SCHOSS',
        ar: 'القطة نائمة في الحضن',
        fr: 'CHAT ENDORMI SUR LES GENOUX',
        es: 'GATO DORMIDO EN LAS PIERNAS',
      },
    },
    caption: {
      tr: 'Artık burada yaşıyorsun.',
      en: 'You live here now.',
      de: 'Du wohnst jetzt hier.',
      ar: 'أنت تسكن هنا الآن.',
      fr: 'Tu habites ici, maintenant.',
      es: 'Ahora vives aquí.',
    },
    headline: {
      tr: 'Kedi kucağında uyuyakaldı',
      en: 'The cat fell asleep on your lap',
      de: 'Die Katze schläft auf deinem Schoß',
      ar: 'القطة نامت في حضنك',
      fr: "Le chat s'est endormi sur toi",
      es: 'El gato se durmió en tus piernas',
    },
  },
  {
    emoji: '🦌',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: { tr: 'DİKKAT', en: 'CAUTION', de: 'ACHTUNG', ar: 'انتبه', fr: 'ATTENTION', es: 'PRECAUCIÓN' },
      small: {
        tr: 'GEYİK ÇIKABİLİR',
        en: 'DEER CROSSING',
        de: 'WILDWECHSEL',
        ar: 'منطقة عبور غزلان',
        fr: 'PASSAGE DE CERFS',
        es: 'CRUCE DE CIERVOS',
      },
    },
    caption: {
      tr: 'İlk kıpırdayan kaybeder.',
      en: 'First one to move loses.',
      de: 'Wer sich zuerst bewegt, verliert.',
      ar: 'أول من يتحرك يخسر.',
      fr: 'Le premier qui bouge a perdu.',
      es: 'El primero que se mueva pierde.',
    },
    headline: {
      tr: 'Bir geyikle göz göze geldin',
      en: 'You and a deer just locked eyes',
      de: 'Du und ein Reh: Blickkontakt',
      ar: 'التقت عيناك بعيني غزال',
      fr: 'Toi et un cerf, les yeux dans les yeux',
      es: 'Un ciervo te mira fijo a los ojos',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'FLAŞ YASAK',
        en: 'NO FLASH',
        de: 'KEIN BLITZ',
        ar: 'ممنوع الفلاش',
        fr: 'PAS DE FLASH',
        es: 'SIN FLASH',
      },
      small: {
        tr: 'BAYKUŞLAR UYUYOR',
        en: 'OWLS SLEEPING',
        de: 'EULEN SCHLAFEN',
        ar: 'البوم نائم',
        fr: 'CHOUETTES ENDORMIES',
        es: 'BÚHOS DURMIENDO',
      },
    },
    caption: {
      tr: 'Seni gördü. Kıpırdama.',
      en: "It saw you. Don't move.",
      de: 'Sie hat dich gesehen. Keine Bewegung.',
      ar: 'لقد رأتك. لا تتحرك.',
      fr: "Elle t'a vu. Bouge pas.",
      es: 'Te vio. No te muevas.',
    },
    headline: {
      tr: 'Baykuş tek gözünü açtı',
      en: 'The owl just opened one eye',
      de: 'Die Eule hat ein Auge geöffnet',
      ar: 'البومة فتحت عينًا واحدة',
      fr: 'La chouette a ouvert un œil',
      es: 'El búho abrió un ojo',
    },
  },
  {
    emoji: '🐒',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYARI',
        en: 'WARNING',
        de: 'WARNUNG',
        ar: 'تحذير',
        fr: 'AVERTISSEMENT',
        es: 'ADVERTENCIA',
      },
      small: {
        tr: 'MAYMUNLAR TAKLİT EDER',
        en: 'MONKEYS COPY EVERYTHING',
        de: 'AFFEN MACHEN ALLES NACH',
        ar: 'القرود تقلّد كل شيء',
        fr: 'LES SINGES IMITENT TOUT',
        es: 'LOS MONOS IMITAN TODO',
      },
    },
    caption: {
      tr: 'Sen durursan o da durur.',
      en: 'Freeze, and so will it.',
      de: 'Halt still, dann hält er auch still.',
      ar: 'توقّف كي يتوقف هو أيضًا.',
      fr: "Arrête-toi, il s'arrêtera aussi.",
      es: 'Quédate quieto y él también.',
    },
    headline: {
      tr: 'Maymun her hareketini taklit ediyor',
      en: 'A monkey is copying your every move',
      de: 'Ein Affe macht dir alles nach',
      ar: 'قرد يقلّد كل حركة تقوم بها',
      fr: 'Un singe imite tous tes gestes',
      es: 'Un mono imita cada movimiento tuyo',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'KORİDOR', en: 'HALLWAY', de: 'FLUR', ar: 'الممر', fr: 'COULOIR', es: 'PASILLO' },
    },
    caption: {
      tr: 'Bir adım at, ayaklarına atlar.',
      en: 'Take one step and it pounces.',
      de: 'Ein Schritt, und sie springt.',
      ar: 'خطوة واحدة وتنقضّ على قدميك.',
      fr: 'Un pas, et il bondit.',
      es: 'Da un paso y se lanza.',
    },
    headline: {
      tr: 'Kedi pusuda, ayaklarını izliyor',
      en: 'Cat in ambush mode. Target: your feet',
      de: 'Die Katze lauert. Ziel: deine Füße',
      ar: 'القطة تكمن لك… وهدفها قدماك',
      fr: "Le chat est à l'affût. Cible : tes pieds",
      es: 'El gato acecha. Objetivo: tus pies',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAPI ÖNÜ',
        en: 'DOORSTEP',
        de: 'HAUSEINGANG',
        ar: 'عتبة الباب',
        fr: 'PAS DE LA PORTE',
        es: 'ENTRADA',
      },
    },
    caption: {
      tr: 'Az kaldı. Nefesini tut.',
      en: 'Almost there. Hold your breath.',
      de: 'Fast geschafft. Luft anhalten.',
      ar: 'اقتربت… احبس أنفاسك.',
      fr: 'Presque. Retiens ton souffle.',
      es: 'Ya casi. Aguanta la respiración.',
    },
    headline: {
      tr: 'Ürkek sokak kedisi ilk kez yaklaşıyor',
      en: 'The shy stray is finally coming closer',
      de: 'Die scheue Streunerkatze kommt näher',
      ar: 'قطة الشارع الخجولة تقترب لأول مرة',
      fr: "Le chat errant timide s'approche enfin",
      es: 'La gata callejera tímida se acerca',
    },
  },
  {
    emoji: '🦔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'BAHÇE', en: 'BACKYARD', de: 'GARTEN', ar: 'الحديقة', fr: 'JARDIN', es: 'JARDÍN' },
    },
    caption: {
      tr: 'Ses çıkarma, top olur.',
      en: "One sound and it's a ball.",
      de: 'Ein Mucks, und er rollt sich ein.',
      ar: 'صوت واحد ويتكوّر.',
      fr: 'Un bruit, et il se roule en boule.',
      es: 'Un ruido y se hace bolita.',
    },
    headline: {
      tr: 'Kirpi bahçeye çıktı, seni fark etmedi',
      en: "A hedgehog's out. It hasn't seen you.",
      de: 'Ein Igel im Garten – er sieht dich nicht',
      ar: 'قنفذ في الحديقة ولم يلاحظك بعد',
      fr: "Un hérisson sort. Il ne t'a pas vu.",
      es: 'Salió un erizo y no te ha visto',
    },
  },
  {
    emoji: '🛁',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'BANYO',
        en: 'BATHROOM',
        de: 'BADEZIMMER',
        ar: 'الحمّام',
        fr: 'SALLE DE BAIN',
        es: 'BAÑO',
      },
    },
    caption: {
      tr: 'Tek hareket ve yatağın altına kaçar.',
      en: "One move and he's under the bed.",
      de: 'Eine Bewegung, und er ist unterm Bett.',
      ar: 'حركة واحدة ويختبئ تحت السرير.',
      fr: 'Un geste, et il file sous le lit.',
      es: 'Un movimiento y se esconde bajo la cama.',
    },
    headline: {
      tr: 'Köpek banyo suyunu duydu, seni izliyor',
      en: 'The dog heard the bath. Eyes on you.',
      de: 'Der Hund hat das Badewasser gehört',
      ar: 'الكلب سمع ماء الحمّام… وهو يراقبك',
      fr: 'Le chien a entendu le bain couler',
      es: 'El perro oyó el agua del baño',
    },
  },
];
