import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Animals: cats, dogs, birds, fish, hamsters, the zoo, the neighbourhood strays, wildlife.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const ANIMALS_SKIP: readonly Draft[] = [
  {
    emoji: '🕊️',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Balkona güvercin taşındı. Kira vermiyor.',
      en: 'A pigeon moved onto my balcony. Rent-free.',
      de: 'Eine Taube wohnt jetzt auf dem Balkon. Mietfrei.',
      ar: 'حمامة سكنت شرفتي… ولا تدفع الإيجار',
      fr: 'Un pigeon squatte mon balcon. Zéro loyer.',
      es: 'Una paloma se mudó a mi balcón. No paga alquiler.',
      ja: 'ベランダにハトが住みついた。家賃は払わない。',
      ko: '베란다에 비둘기가 이사 왔다. 월세는 안 낸다.',
    },
  },
  {
    emoji: '🐜',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Tek kırıntı düşürdüm, 400 misafir geldi',
      en: 'Dropped one crumb. 400 guests showed up.',
      de: 'Ein Krümel gefallen, 400 Gäste gekommen',
      ar: 'أسقطت فتاتة واحدة… فجاء 400 ضيف',
      fr: 'Une miette tombée, 400 invités débarquent',
      es: 'Se me cayó una miga y llegaron 400 invitados',
      ja: 'パンくず1つ落としたら400名様ご来店',
      ko: '빵부스러기 하나 흘렸더니 손님 400명 입장',
    },
  },
  {
    emoji: '🦒',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Zürafayla selfie: ben ve iki bacak',
      en: 'Selfie with a giraffe: me and two legs',
      de: 'Selfie mit Giraffe: ich und zwei Beine',
      ar: 'سيلفي مع زرافة: أنا وساقان',
      fr: 'Selfie avec une girafe : moi et deux pattes',
      es: 'Selfie con una jirafa: yo y dos patas',
      ja: 'キリンと自撮り。写ったのは私と脚2本',
      ko: '기린이랑 셀카: 나랑 다리 두 개',
    },
  },
  {
    emoji: '🐆',
    user: ACCOUNTS.pets,
    body: { format: 'scene' },
    caption: {
      tr: 'Gece 3’te kedi koşusu. Parkur: ben.',
      en: '3 a.m. cat zoomies. The track: me.',
      de: 'Katzenrennen um 3 Uhr nachts. Die Strecke: ich.',
      ar: 'سباق القطة في الثالثة فجرًا… والمضمار أنا',
      fr: 'Sprint du chat à 3 h du mat. La piste : moi.',
      es: 'Carrera gatuna a las 3 de la mañana. La pista: yo.',
      ja: '深夜3時、猫の大運動会。コースは私。',
      ko: '새벽 3시 고양이 우다다. 트랙은 나.',
    },
  },
  {
    emoji: '🐟',
    user: ACCOUNTS.pets,
    body: { format: 'scene' },
    caption: {
      tr: 'Balığım konuşuyor, ben başımı sallıyorum',
      en: 'My fish talks. I just nod along.',
      de: 'Mein Fisch redet, ich nicke nur.',
      ar: 'سمكتي تتكلم… وأنا أهزّ رأسي فقط',
      fr: 'Mon poisson parle. Moi, je hoche la tête.',
      es: 'Mi pez habla y yo le digo que sí con la cabeza.',
      ja: '金魚が何か話してる。とりあえずうなずいてる。',
      ko: '물고기가 말을 건다. 난 고개만 끄덕인다.',
    },
  },
  {
    emoji: '🦗',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Cırcır böceği: sesi her yerde, kendisi yok',
      en: 'Crickets: heard everywhere, seen nowhere',
      de: 'Grille: überall zu hören, nirgends zu sehen',
      ar: 'صرصور الليل: صوته في كل مكان ولا أثر له',
      fr: "Le grillon : on l'entend partout, on le voit nulle part",
      es: 'El grillo: se oye en todas partes y no está en ninguna',
      ja: 'コオロギ：声はすれども姿は見えず',
      ko: '귀뚜라미: 소리는 사방에, 모습은 어디에도 없음',
    },
  },
  {
    emoji: '🐄',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'İnekler beni 1 saat izledi. Rekor izlenme.',
      en: 'Cows stared at me for an hour. Record views.',
      de: 'Die Kühe starrten mich eine Stunde an. Rekordquote.',
      ar: 'الأبقار حدّقت بي ساعة كاملة… أعلى مشاهدات لي',
      fr: "Les vaches m'ont fixé une heure. Record d'audience.",
      es: 'Las vacas me miraron una hora. Récord de audiencia.',
      ja: '牛に1時間ガン見された。過去最高の視聴数。',
      ko: '소들이 1시간 동안 날 쳐다봤다. 역대 최고 조회수.',
    },
  },
  {
    emoji: '🦜',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'senin kuş yine telefon gibi çalıyor',
            en: "your bird's doing the ringtone again",
            de: 'dein Vogel macht wieder den Klingelton',
            ar: 'عصفورك يقلّد رنين الهاتف مجددًا',
            fr: 'ton oiseau refait la sonnerie',
            es: 'tu pájaro imita otra vez el teléfono',
            ja: 'またあんたの鳥が着信音のマネしてる',
            ko: '네 새가 또 전화벨 소리 흉내 내',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'açmaya koştun mu? 😂',
            en: 'did you run to answer? 😂',
            de: 'bist du hingerannt? 😂',
            ar: 'هل ركضتِ لتردّي؟ 😂',
            fr: "t'as couru répondre ? 😂",
            es: '¿corriste a contestar? 😂',
            ja: '電話に出ようと走った？ 😂',
            ko: '받으러 뛰어갔어? 😂',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'koştum. o da “alo” dedi',
            en: 'yep. then it said “hello?”',
            de: 'ja. dann sagte er „Hallo?“',
            ar: 'نعم. ثم قال: «ألو؟»',
            fr: 'oui. et là, il a dit « allô ? »',
            es: 'sí. y luego dijo “¿hola?”',
            ja: '走った。そしたら「もしもし？」だって',
            ko: '뛰어갔지. 그랬더니 “여보세요?” 하더라',
          },
        },
      ],
    },
    caption: {
      tr: 'Evin en iyi taklitçisi 30 gram',
      en: 'Best impressionist in the house: 30 grams',
      de: 'Bester Imitator im Haus: 30 Gramm',
      ar: 'أفضل مقلّد في البيت وزنه 30 غرامًا',
      fr: 'Meilleur imitateur de la maison : 30 grammes',
      es: 'El mejor imitador de la casa pesa 30 gramos',
      ja: '我が家いちばんのモノマネ芸人、体重30グラム',
      ko: '우리 집 최고의 성대모사 달인, 30그램',
    },
  },
  {
    emoji: '😸',
    user: ACCOUNTS.pets,
    body: {
      format: 'chat',
      contact: {
        tr: 'Komşu',
        en: 'Neighbor',
        de: 'Nachbarin',
        ar: 'الجارة',
        fr: 'Voisine',
        es: 'Vecina',
        ja: 'お隣さん',
        ko: '옆집',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'kediniz yine bizde 🐈',
            en: 'your cat is at our place again 🐈',
            de: 'Ihre Katze ist schon wieder bei uns 🐈',
            ar: 'قطتكم عندنا مرة أخرى 🐈',
            fr: 'votre chat est encore chez nous 🐈',
            es: 'su gato está otra vez en nuestra casa 🐈',
            ja: 'お宅の猫ちゃん、またうちに来てますよ 🐈',
            ko: '댁의 고양이가 또 저희 집에 왔어요 🐈',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'çok özür dilerim, hemen alıyorum',
            en: 'so sorry, coming to get her',
            de: 'tut mir leid, ich hole sie sofort',
            ar: 'آسف جدًا، سآتي لأخذها حالًا',
            fr: 'désolé, je viens le chercher',
            es: 'perdón, ya voy por él',
            ja: 'すみません、すぐ迎えに行きます',
            ko: '정말 죄송해요, 바로 데리러 갈게요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'acele etmeyin, yemeğini yedi, uyuyor',
            en: "no rush, she ate and she's napping",
            de: 'keine Eile, sie hat gegessen und schläft',
            ar: 'لا داعي للعجلة، أكلت وهي نائمة',
            fr: 'rien ne presse, il a mangé, il dort',
            es: 'sin prisa, ya comió y está durmiendo',
            ja: 'ごゆっくり。ごはん食べて寝てますから',
            ko: '천천히 오세요, 밥 먹고 자고 있어요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bu arada adını değiştirdik',
            en: 'also, we renamed her',
            de: 'übrigens haben wir sie umbenannt',
            ar: 'وبالمناسبة، غيّرنا اسمها',
            fr: "au fait, on l'a rebaptisé",
            es: 'por cierto, le cambiamos el nombre',
            ja: 'ちなみに名前、変えちゃいました',
            ko: '참, 이름도 새로 지어 줬어요',
          },
        },
      ],
    },
    caption: {
      tr: 'Kedimin ikinci bir ailesi var',
      en: 'My cat has a second family',
      de: 'Meine Katze hat eine Zweitfamilie',
      ar: 'لقطتي عائلة ثانية',
      fr: 'Mon chat a une deuxième famille',
      es: 'Mi gato tiene una segunda familia',
      ja: 'うちの猫、もうひとつ家族がいた',
      ko: '우리 고양이에게 두 번째 가족이 있었다',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kardeşim',
        en: 'Little bro',
        de: 'Brüderchen',
        ar: 'أخي',
        fr: 'Frérot',
        es: 'Hermanito',
        ja: '弟',
        ko: '남동생',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'kediye mama verdin mi?',
            en: 'did you feed the cat?',
            de: 'hast du die Katze gefüttert?',
            ar: 'هل أطعمت القطة؟',
            fr: "t'as nourri le chat ?",
            es: '¿le diste de comer al gato?',
            ja: '猫にごはんあげた？',
            ko: '고양이 밥 줬어?',
          },
        },
        {
          from: 'them',
          text: { tr: 'verdim', en: 'yep', de: 'jep', ar: 'نعم', fr: 'ouais', es: 'sí', ja: 'あげた', ko: '줬어' },
        },
        {
          from: 'me',
          text: {
            tr: 'ben de verdim 😳',
            en: 'so did I 😳',
            de: 'ich auch 😳',
            ar: 'وأنا أيضًا 😳',
            fr: 'moi aussi 😳',
            es: 'yo también 😳',
            ja: '私もあげた 😳',
            ko: '나도 줬는데 😳',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'annem de vermiş. babam da.',
            en: 'so did mom. and dad.',
            de: 'Mama auch. und Papa.',
            ar: 'وأمي أيضًا… وأبي كذلك',
            fr: 'maman aussi. et papa.',
            es: 'mamá también. y papá.',
            ja: 'お母さんもあげたって。お父さんも。',
            ko: '엄마도 줬대. 아빠도.',
          },
        },
      ],
    },
    caption: {
      tr: 'Her birimize ayrı ayrı aç numarası yapmış',
      en: 'She pulled the hungry act on each of us',
      de: 'Sie hat jedem von uns Hunger vorgespielt',
      ar: 'مثّلت دور الجائعة على كل واحد منا',
      fr: 'Il nous a tous eus avec son air affamé',
      es: 'Se hizo el hambriento con cada uno',
      ja: '全員に「おなかすいた」の演技をしてた',
      ko: '한 명씩 돌아가며 배고픈 척을 했다',
    },
  },
  {
    emoji: '🤳',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá', ja: 'お父さん', ko: '아빠' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'köpekle parka geldik 🥰',
            en: 'at the park with the dog 🥰',
            de: 'mit dem Hund im Park 🥰',
            ar: 'في الحديقة مع الكلب 🥰',
            fr: 'au parc avec le chien 🥰',
            es: 'en el parque con el perro 🥰',
            ja: '犬と公園に来たよ 🥰',
            ko: '강아지랑 공원 왔어 🥰',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hani bu eve köpek girmezdi?',
            en: 'what happened to “no dogs in this house”?',
            de: 'hieß es nicht „kein Hund in diesem Haus“?',
            ar: 'ألم تقل إن هذا البيت لا يدخله كلب؟',
            fr: "c'était pas « jamais de chien ici » ?",
            es: '¿no decías que aquí no entraban perros?',
            ja: '「うちに犬は入れない」んじゃなかった？',
            ko: '우리 집엔 개 안 들인다며?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'o ayrı. o bizim oğlan.',
            en: "that's different. he's our boy.",
            de: 'das ist was anderes. er ist unser Junge.',
            ar: 'هذا مختلف، إنه ولدنا',
            fr: "c'est pas pareil. c'est notre fiston.",
            es: 'eso es distinto. es nuestro niño.',
            ja: 'それとこれとは別。うちの息子だから。',
            ko: '그건 다르지. 얘는 우리 아들이야.',
          },
        },
      ],
    },
    caption: {
      tr: 'Evin en katı kuralı 1 hafta dayandı',
      en: "The house's strictest rule lasted a week",
      de: 'Die strengste Hausregel hielt eine Woche',
      ar: 'أصرم قاعدة في البيت صمدت أسبوعًا',
      fr: "La règle d'or de la maison a tenu une semaine",
      es: 'La regla más estricta de la casa duró una semana',
      ja: '我が家いちばん厳しいルール、1週間で崩壊',
      ko: '우리 집 제일 엄격한 규칙, 일주일 만에 무너짐',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Evcil hayvanınla konuşurken sesin:',
        en: 'Your voice when you talk to your pet:',
        de: 'Deine Stimme, wenn du mit dem Haustier redest:',
        ar: 'صوتك عندما تتحدث إلى حيوانك الأليف:',
        fr: 'Ta voix quand tu parles à ton animal :',
        es: 'Tu voz cuando le hablas a tu mascota:',
        ja: 'ペットに話しかけるときの声：',
        ko: '반려동물한테 말할 때 내 목소리:',
      },
      options: [
        {
          tr: 'Her zamanki sesim',
          en: 'My normal voice',
          de: 'Meine normale Stimme',
          ar: 'صوتي العادي',
          fr: 'Ma voix normale',
          es: 'Mi voz normal',
          ja: 'いつもの声',
          ko: '평소 목소리',
        },
        {
          tr: '3 oktav daha ince',
          en: 'Three octaves higher',
          de: 'Drei Oktaven höher',
          ar: 'أعلى بثلاث طبقات',
          fr: '3 octaves plus haut',
          es: 'Tres octavas más aguda',
          ja: '3オクターブ高い',
          ko: '3옥타브 위',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Komşu duydu, artık geri dönüş yok',
      en: 'The neighbor heard. No going back.',
      de: "Der Nachbar hat's gehört. Kein Zurück.",
      ar: 'سمعني الجار… ولا مجال للتراجع',
      fr: 'Le voisin a entendu. Pas de retour en arrière.',
      es: 'El vecino me oyó. Ya no hay vuelta atrás.',
      ja: 'お隣さんに聞かれた。もう後戻りできない。',
      ko: '옆집에서 들었다. 이제 돌이킬 수 없다.',
    },
  },
  {
    emoji: '🏘️',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Mahallenin kedisinin adı ne?',
        en: "What's the neighborhood cat's name?",
        de: 'Wie heißt die Katze aus dem Viertel?',
        ar: 'ما اسم قطة الحي؟',
        fr: "Comment s'appelle le chat du quartier ?",
        es: '¿Cómo se llama el gato del barrio?',
        ja: '近所の野良猫の名前は？',
        ko: '동네 고양이 이름은?',
      },
      options: [
        { tr: 'Paşa', en: 'Tiger', de: 'Minka', ar: 'مشمش', fr: 'Minou', es: 'Michi', ja: 'タマ', ko: '나비' },
        { tr: 'Duman', en: 'Smokey', de: 'Tiger', ar: 'سمسم', fr: 'Caramel', es: 'Pelusa', ja: 'ミケ', ko: '치즈' },
        {
          tr: 'Hepsi',
          en: 'All of the above',
          de: 'Alle drei',
          ar: 'كلها',
          fr: 'Tous ces noms',
          es: 'Todos esos',
          ja: '全部',
          ko: '전부 다',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: '7 adı var, hiçbirine dönüp bakmıyor',
      en: 'Seven names. Answers to none.',
      de: 'Sieben Namen. Hört auf keinen.',
      ar: 'لها سبعة أسماء ولا تلتفت لأيٍّ منها',
      fr: 'Sept noms. Il ne répond à aucun.',
      es: 'Siete nombres y no responde a ninguno',
      ja: '名前が7つある。どれにも振り向かない。',
      ko: '이름이 7개인데 어느 이름에도 안 돌아본다',
    },
  },
  {
    emoji: '🦁',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Hayvanat bahçesinde aslanı gördün mü?',
        en: 'Did you see the lion at the zoo?',
        de: 'Hast du im Zoo den Löwen gesehen?',
        ar: 'هل رأيت الأسد في حديقة الحيوان؟',
        fr: "T'as vu le lion au zoo ?",
        es: '¿Viste al león en el zoológico?',
        ja: '動物園でライオン見た？',
        ko: '동물원에서 사자 봤어?',
      },
      options: [
        {
          tr: 'Gördüm, kükredi!',
          en: 'Yes, it roared!',
          de: 'Ja, er hat gebrüllt!',
          ar: 'نعم، وزأر!',
          fr: 'Oui, il a rugi !',
          es: '¡Sí, rugió!',
          ja: '見た！吠えた！',
          ko: '봤어, 포효했어!',
        },
        {
          tr: 'Uyuyan bir sırt gördüm',
          en: 'Just a snoozing back',
          de: 'Einen dösenden Rücken',
          ar: 'رأيت ظهرًا نائمًا',
          fr: 'Un dos qui dort',
          es: 'Vi una espalda dormida',
          ja: '寝てる背中だけ',
          ko: '자는 등만 봤어',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: '2 saat bekledim, bir kez kulağını oynattı',
      en: 'Waited 2 hours. One ear twitch.',
      de: '2 Stunden gewartet. Ein Ohr hat gezuckt.',
      ar: 'انتظرت ساعتين… فحرّك أذنه مرة واحدة',
      fr: "2 h d'attente. Une oreille a bougé.",
      es: 'Esperé 2 horas. Movió una oreja.',
      ja: '2時間待って、耳が1回ピクッとしただけ',
      ko: '2시간 기다렸는데 귀 한 번 움찔했다',
    },
  },
  {
    emoji: '🐹',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'HAMSTERIN GECE KOŞUSU',
        en: "MY HAMSTER'S NIGHT RUN",
        de: 'NACHTLAUF DES HAMSTERS',
        ar: 'جري الهامستر ليلًا',
        fr: 'HAMSTER EN ROUE LIBRE',
        es: 'MARATÓN DEL HÁMSTER',
        ja: 'ハムスターの夜ラン',
        ko: '햄스터의 야간 러닝',
      },
      value: { tr: '9 km', en: '9 km', de: '9 km', ar: '9 كم', fr: '9 km', es: '9 km', ja: '9 km', ko: '9 km' },
      shape: 'rise',
      axis: 'hours',
    },
    caption: {
      tr: 'O çarkta, ben akışta. Yerimizde sayıyoruz.',
      en: "He's on his wheel, I'm on my feed. Going nowhere.",
      de: 'Er im Laufrad, ich im Feed. Beide auf der Stelle.',
      ar: 'هو على عجلته وأنا على الخلاصة… ولا نتقدم خطوة',
      fr: 'Lui dans sa roue, moi dans mon fil : du surplace.',
      es: 'Él en su rueda, yo en el feed. Ninguno avanza.',
      ja: 'あいつは回し車、私はフィード。どっちも前に進まない。',
      ko: '걔는 쳇바퀴, 나는 피드. 둘 다 제자리걸음.',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.pets,
    body: {
      format: 'chart',
      title: {
        tr: 'KÖPEĞİMİN SEVİNCİ',
        en: "MY DOG'S JOY LEVEL",
        de: 'FREUDE MEINES HUNDES',
        ar: 'فرحة كلبي',
        fr: 'LA JOIE DE MON CHIEN',
        es: 'LA ALEGRÍA DE MI PERRO',
        ja: 'うちの犬のよろこび度',
        ko: '우리 개 기쁨 지수',
      },
      value: null,
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Çöpü atıp döndüm, 10 yıl olmuş sanki',
      en: "Took out the trash. He acted like it'd been years.",
      de: 'Müll rausgebracht. Empfang wie nach 10 Jahren.',
      ar: 'أخرجت القمامة وعدت… فاستقبلني كأنني غبت 10 سنوات',
      fr: "Poubelle sortie. Accueil digne de 10 ans d'absence.",
      es: 'Saqué la basura y me recibió como tras 10 años',
      ja: 'ゴミ出しから戻ったら、10年ぶりの再会みたいな歓迎',
      ko: '쓰레기 버리고 왔더니 10년 만에 만난 듯 반김',
    },
  },
  {
    emoji: '🧶',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'PET SHOP',
        en: 'PET STORE',
        de: 'ZOOHANDLUNG',
        ar: 'متجر الحيوانات',
        fr: 'ANIMALERIE',
        es: 'TIENDA DE MASCOTAS',
        ja: 'ペットショップ',
        ko: '펫숍',
      },
      items: [
        {
          tr: 'TÜY RULOSU (12 ADET)',
          en: 'LINT ROLLERS (12)',
          de: 'FUSSELROLLEN ×12',
          ar: 'بكرات إزالة الوبر (12)',
          fr: 'ROULEAUX ADHÉSIFS ×12',
          es: 'QUITAPELUSAS (12)',
          ja: 'コロコロ 12個',
          ko: '돌돌이 (12개)',
        },
      ],
    },
    caption: {
      tr: 'Siyah kazak aldım, kedi desenli çıktı',
      en: "Bought a black sweater. It's cat print now.",
      de: 'Schwarzer Pulli gekauft. Jetzt mit Katzenmuster.',
      ar: 'اشتريت كنزة سوداء… فصارت بنقشة قطط',
      fr: 'Pull noir acheté. Il est à motif chat, maintenant.',
      es: 'Me compré un suéter negro. Ahora es estampado de gato.',
      ja: '黒いセーターを買ったら、猫柄になった',
      ko: '검은 스웨터를 샀는데 고양이 무늬가 됐다',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.home,
    body: {
      format: 'receipt',
      store: {
        tr: 'MARKET',
        en: 'GROCERY STORE',
        de: 'SUPERMARKT',
        ar: 'سوبرماركت',
        fr: 'SUPÉRETTE',
        es: 'SUPERMERCADO',
        ja: 'スーパー',
        ko: '마트',
      },
      items: [
        {
          tr: 'KUŞ YEMİ (5 KG)',
          en: 'BIRDSEED (5 KG)',
          de: 'VOGELFUTTER (5 KG)',
          ar: 'حبوب للطيور (5 كغ)',
          fr: 'GRAINES OISEAUX (5 KG)',
          es: 'ALPISTE (5 KG)',
          ja: '鳥のエサ 5kg',
          ko: '새 모이 (5kg)',
        },
      ],
    },
    caption: {
      tr: 'Balkona 1 serçe geliyordu. Artık 40.',
      en: "One sparrow used to visit my balcony. Now it's 40.",
      de: 'Früher kam ein Spatz auf den Balkon. Jetzt 40.',
      ar: 'كان عصفور واحد يزور شرفتي… صاروا 40',
      fr: 'Avant, un moineau au balcon. Maintenant, 40.',
      es: 'Antes venía un gorrión al balcón. Ahora vienen 40.',
      ja: 'ベランダに来るスズメは1羽だった。今は40羽。',
      ko: '베란다에 참새 1마리가 오곤 했다. 이제는 40마리.',
    },
  },
  {
    emoji: '🐠',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'AKVARYUMCU',
        en: 'AQUARIUM SHOP',
        de: 'AQUARISTIK',
        ar: 'متجر الأحياء المائية',
        fr: "MAGASIN D'AQUARIUMS",
        es: 'TIENDA DE ACUARIOS',
        ja: '熱帯魚ショップ',
        ko: '수족관 용품점',
      },
      items: [
        {
          tr: 'AKVARYUM KALESİ',
          en: 'AQUARIUM CASTLE',
          de: 'AQUARIUM-BURG',
          ar: 'قلعة لحوض السمك',
          fr: "CHÂTEAU D'AQUARIUM",
          es: 'CASTILLO PARA PECERA',
          ja: '水槽用のお城',
          ko: '어항용 성',
        },
        {
          tr: 'MİNİ BATIK GEMİ',
          en: 'MINI SHIPWRECK',
          de: 'MINI-SCHIFFSWRACK',
          ar: 'سفينة غارقة صغيرة',
          fr: 'MINI ÉPAVE',
          es: 'MINI BARCO HUNDIDO',
          ja: 'ミニ沈没船',
          ko: '미니 난파선',
        },
      ],
    },
    caption: {
      tr: 'Balığımın evi benimkinden şık',
      en: "My fish's place is nicer than mine",
      de: 'Mein Fisch wohnt schicker als ich',
      ar: 'بيت سمكتي أفخم من بيتي',
      fr: 'Mon poisson est mieux logé que moi',
      es: 'Mi pez vive mejor que yo',
      ja: '金魚の家のほうが私の部屋よりおしゃれ',
      ko: '내 집보다 물고기 집이 더 멋지다',
    },
  },
  {
    emoji: '😻',
    user: ACCOUNTS.pets,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'EVCİL HAYVAN RAPORU',
        en: 'PET REPORT',
        de: 'HAUSTIER-REPORT',
        ar: 'تقرير الحيوان الأليف',
        fr: 'RAPPORT ANIMAL',
        es: 'INFORME DE MASCOTA',
        ja: 'ペットレポート',
        ko: '반려동물 리포트',
      },
      big: { tr: '23', en: '23', de: '23', ar: '23', fr: '23', es: '23', ja: '23', ko: '23' },
      text: {
        tr: 'farklı lakap taktın kedine. Asıl adını unuttun bile.',
        en: 'different nicknames for your cat. You forgot her real name.',
        de: 'Spitznamen für deine Katze. Den echten Namen hast du vergessen.',
        ar: 'لقبًا أطلقته على قطتك… ونسيت اسمها الحقيقي',
        fr: 'surnoms pour ton chat. Tu as oublié son vrai nom.',
        es: 'apodos para tu gata. Ya olvidaste su nombre real.',
        ja: '種類のあだ名を猫につけた。本名はもう忘れてる。',
        ko: '가지 별명을 고양이에게 지어 줬어요. 진짜 이름은 잊었고요.',
      },
    },
    caption: {
      tr: 'Pamuk, Pamukçuk, Patates, Minnoş…',
      en: 'Mittens, Mitty, Potato, Sir Fluff…',
      de: 'Mimi, Mimilein, Kartoffel, Flauschi…',
      ar: 'مشمش، مشمشة، بطاطا، يا قمر…',
      fr: 'Minou, Minouche, Patate, Boule de poils…',
      es: 'Michi, Michita, Papita, Bolita…',
      ja: 'ミケ、ミケちゃん、おいも、もふ様…',
      ko: '나비, 나비야, 감자, 털뭉치 님…',
    },
  },
  {
    emoji: '🧀',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'KÖPEĞİNİN SÜPER GÜCÜ',
        en: "YOUR DOG'S SUPERPOWER",
        de: 'SUPERKRAFT DEINES HUNDES',
        ar: 'قوة كلبك الخارقة',
        fr: 'SUPERPOUVOIR CANIN',
        es: 'SUPERPODER CANINO',
        ja: '犬の超能力',
        ko: '강아지의 초능력',
      },
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3', ja: '3', ko: '3' },
      text: {
        tr: 'oda öteden peynir paketinin sesini duydu. Adını duymadı.',
        en: 'rooms away, he heard the cheese wrapper. Not his name, though.',
        de: 'Zimmer weiter hört er die Käsepackung. Seinen Namen nicht.',
        ar: 'غرف تفصله عن كيس الجبن وقد سمعه… أما اسمه فلا',
        fr: 'pièces plus loin, il entend le sachet de fromage. Pas son nom.',
        es: 'habitaciones más allá oye el paquete de queso. Su nombre, no.',
        ja: '部屋先のチーズの袋の音は聞こえる。名前は聞こえない。',
        ko: '방 너머 치즈 봉지 소리는 들었다. 자기 이름은 못 들었다.',
      },
    },
    caption: {
      tr: 'Seçici işitme, ileri seviye',
      en: 'Selective hearing, expert level',
      de: 'Selektives Hören, Profi-Level',
      ar: 'سمع انتقائي، مستوى متقدم',
      fr: 'Audition sélective, niveau expert',
      es: 'Oído selectivo, nivel experto',
      ja: '都合のいい耳、上級者レベル',
      ko: '선택적 청각, 고수 레벨',
    },
  },
  {
    emoji: '👣',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BUGÜNKÜ YÜRÜYÜŞ',
        en: "TODAY'S WALK",
        de: 'HEUTIGER SPAZIERGANG',
        ar: 'نزهة اليوم',
        fr: 'LA BALADE DU JOUR',
        es: 'EL PASEO DE HOY',
        ja: '今日のお散歩',
        ko: '오늘의 산책',
      },
      big: { tr: '6.214', en: '6,214', de: '6.214', ar: '6,214', fr: '6 214', es: '6214', ja: '6,214', ko: '6,214' },
      text: {
        tr: 'adım attın. Rotayı köpeğin çizdi, sen sadece tasmayı tuttun.',
        en: 'steps today. Your dog picked the route; you held the leash.',
        de: 'Schritte. Die Route wählte dein Hund, du hieltst nur die Leine.',
        ar: 'خطوة اليوم. كلبك اختار الطريق وأنت أمسكت المقود فقط',
        fr: "pas aujourd'hui. Ton chien a choisi la route, toi la laisse.",
        es: 'pasos hoy. La ruta la eligió tu perro; tú, la correa.',
        ja: '歩。ルートは犬が決めて、きみはリードを持っただけ。',
        ko: '걸음 걸었어요. 코스는 강아지가 정하고, 목줄만 잡았죠.',
      },
    },
    caption: {
      tr: 'Kim kimi gezdiriyor, belli değil',
      en: "Who's walking who, exactly?",
      de: 'Wer führt hier eigentlich wen aus?',
      ar: 'من يأخذ من في نزهة؟',
      fr: 'Qui promène qui, au juste ?',
      es: '¿Quién pasea a quién?',
      ja: '散歩されてるのはどっち？',
      ko: '누가 누구를 산책시키는 걸까',
    },
  },
  {
    emoji: '🐌',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'HAFTANIN DİZİSİ',
        en: 'SHOW OF THE WEEK',
        de: 'SERIE DER WOCHE',
        ar: 'مسلسل الأسبوع',
        fr: 'LA SÉRIE DE LA SEMAINE',
        es: 'LA SERIE DE LA SEMANA',
        ja: '今週のドラマ',
        ko: '이번 주 드라마',
      },
      big: { tr: '40', en: '40', de: '40', ar: '40', fr: '40', es: '40', ja: '40', ko: '40' },
      text: {
        tr: 'dakika balkondaki salyangozu izledin. Hiç kaydırmadın.',
        en: 'minutes watching a snail cross the balcony. Zero scrolling.',
        de: 'Minuten einer Balkonschnecke zugesehen. Null gescrollt.',
        ar: 'دقيقة تتابع حلزونًا يعبر الشرفة… دون أي تمرير',
        fr: 'minutes à regarder un escargot sur le balcon. Zéro scroll.',
        es: 'minutos viendo un caracol cruzar el balcón. Cero scroll.',
        ja: '分、ベランダのカタツムリを見てた。スクロールは一度もなし。',
        ko: '분 동안 베란다 달팽이를 봤어요. 스크롤은 한 번도 안 했어요.',
      },
    },
    caption: {
      tr: 'Yılın en sürükleyici yapımı',
      en: "Most gripping thing I've seen all year",
      de: 'Spannendste Produktion des Jahres',
      ar: 'أكثر عمل مشوّق هذا العام',
      fr: "La production la plus haletante de l'année",
      es: 'La producción más emocionante del año',
      ja: '今年いちばん目が離せない作品',
      ko: '올해 가장 몰입감 있는 작품',
    },
  },
  {
    emoji: '🦟',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'BALKON MİSAFİRLERİ TIER LIST',
        en: 'BALCONY GUESTS TIER LIST',
        de: 'BALKONBESUCH-TIER-LIST',
        ar: 'تصنيف ضيوف الشرفة',
        fr: 'TIER LIST DU BALCON',
        es: 'TIER LIST DEL BALCÓN',
        ja: 'ベランダ来客Tier表',
        ko: '베란다 손님 티어표',
      },
      rows: [['🐝', '🦋'], ['🐞', '🐦'], ['🐛', '🐜'], ['🦟', '🪰']],
    },
    caption: {
      tr: 'Sivrisinek C: ışık sönünce gelen misafir',
      en: "Mosquito's C: only visits once the lights are off",
      de: 'Mücke: C. Kommt erst, wenn das Licht aus ist.',
      ar: 'البعوضة في الأخير: لا تزور إلا بعد إطفاء النور',
      fr: "Moustique en C : il attend que la lumière s'éteigne",
      es: 'Mosquito en C: solo viene con la luz apagada',
      ja: '蚊はC。電気を消した瞬間に来る客。',
      ko: '모기는 C: 불 끄면 찾아오는 손님',
    },
  },
  {
    emoji: '🐓',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ÇİFTLİK TIER LIST',
        en: 'FARM ANIMAL TIER LIST',
        de: 'BAUERNHOF-TIER-LIST',
        ar: 'تصنيف حيوانات المزرعة',
        fr: 'TIER LIST DE LA FERME',
        es: 'TIER LIST DE LA GRANJA',
        ja: '牧場の動物Tier表',
        ko: '농장 동물 티어표',
      },
      rows: [['🐐', '🐑'], ['🐄', '🐴'], ['🦆', '🐔'], ['🐓']],
    },
    caption: {
      tr: 'Horoz C: saati bozuk, öğlen 2’de ötüyor',
      en: "Rooster's C: his clock's off, crows at 2 p.m.",
      de: 'Hahn: C. Innere Uhr kaputt, kräht um 14 Uhr.',
      ar: 'الديك في الأخير: ساعته معطّلة ويصيح ظهرًا',
      fr: 'Le coq en C : il chante à 14 h',
      es: 'Gallo en C: canta a las 2 de la tarde',
      ja: 'オンドリはC：体内時計が狂って昼2時に鳴く',
      ko: '수탉은 C: 시계 고장 나서 오후 2시에 운다',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '📹',
        app: {
          tr: 'Pati kamerası',
          en: 'Pet cam',
          de: 'Haustier-Kamera',
          ar: 'كاميرا الحيوان',
          fr: 'Caméra animaux',
          es: 'Cámara mascota',
          ja: 'ペットカメラ',
          ko: '펫캠',
        },
        text: {
          tr: 'Hareket algılandı: köpek yine kanepede',
          en: 'Motion detected: dog on couch, again',
          de: 'Bewegung: Hund wieder auf dem Sofa',
          ar: 'رُصدت حركة: الكلب على الأريكة مجددًا',
          fr: 'Mouvement : chien sur le canapé (encore)',
          es: 'Movimiento: el perro otra vez en el sofá',
          ja: '動きを検知：犬がまたソファにいます',
          ko: '움직임 감지: 강아지가 또 소파에',
        },
      },
    },
    caption: {
      tr: 'Kameraya baktı. İnmedi.',
      en: 'He looked right at the camera. Stayed put.',
      de: 'Er sah in die Kamera. Und blieb liegen.',
      ar: 'نظر إلى الكاميرا… ولم ينزل',
      fr: 'Il a regardé la caméra. Il est resté.',
      es: 'Miró a la cámara. No se bajó.',
      ja: 'カメラをじっと見た。降りなかった。',
      ko: '카메라를 똑바로 봤다. 안 내려왔다.',
    },
  },
  {
    emoji: '🐩',
    user: ACCOUNTS.pets,
    body: {
      format: 'notifications',
      first: {
        icon: '✂️',
        app: {
          tr: 'Pati kuaförü',
          en: 'Pet groomer',
          de: 'Hundesalon',
          ar: 'صالون الحيوانات',
          fr: 'Toiletteur',
          es: 'Peluquería canina',
          ja: 'ペットサロン',
          ko: '애견 미용실',
        },
        text: {
          tr: 'Köpeğiniz hazır. Tanımayabilirsiniz.',
          en: "He's ready. You may not recognize him.",
          de: 'Abholbereit – kaum wiederzuerkennen!',
          ar: 'كلبك جاهز… وقد لا تتعرّف عليه',
          fr: 'Il est prêt. Méconnaissable !',
          es: 'Tu perro está listo. ¿Lo reconocerás?',
          ja: 'お迎えどうぞ。見違えるかもしれません',
          ko: '준비됐어요. 못 알아보실 수도 있어요.',
        },
      },
    },
    caption: {
      tr: 'Bıraktığım köpek bu değildi',
      en: "That's not the dog I dropped off",
      de: 'Das ist nicht der Hund, den ich abgegeben hab',
      ar: 'هذا ليس الكلب الذي تركته عندهم',
      fr: "C'est pas le chien que j'ai déposé",
      es: 'Ese no es el perro que dejé',
      ja: '預けたのはこの犬じゃない',
      ko: '내가 맡긴 개는 이 개가 아닌데',
    },
  },
  {
    emoji: '🔴',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kedim kırmızı noktayı hiç yakalayamadı. Bir gün bile vazgeçmedi.',
        en: 'My cat never caught the red dot. Not once did she give up.',
        de: 'Meine Katze hat den roten Punkt nie erwischt. Aufgegeben hat sie nie.',
        ar: 'قطتي لم تمسك النقطة الحمراء يومًا… ولم تستسلم يومًا.',
        fr: "Mon chat n'a jamais attrapé le point rouge. Il n'a jamais abandonné.",
        es: 'Mi gata nunca atrapó el punto rojo. Nunca se rindió.',
        ja: '猫は赤い点を一度も捕まえられなかった。一日もあきらめなかった。',
        ko: '고양이는 빨간 점을 한 번도 못 잡았다. 그래도 하루도 포기하지 않았다.',
      },
    },
    caption: {
      tr: 'Ben ilk denemede bırakırdım',
      en: "I'd have quit on the first try",
      de: 'Ich hätte nach einem Versuch aufgehört',
      ar: 'أنا كنت سأستسلم من أول محاولة',
      fr: "Moi, j'aurais lâché au premier essai",
      es: 'Yo me habría rendido al primer intento',
      ja: '私なら1回目でやめてた',
      ko: '나였으면 첫 시도에 포기했다',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her gün aynı sokağı ilk kez görüyormuş gibi yürü.',
        en: "Walk the same street every day like it's brand new.",
        de: 'Lauf jeden Tag dieselbe Straße, als wäre sie neu.',
        ar: 'امشِ في الشارع نفسه كل يوم كأنك تراه لأول مرة.',
        fr: 'Parcours la même rue chaque jour comme si elle était neuve.',
        es: 'Recorre la misma calle cada día como si fuera nueva.',
        ja: '毎日同じ道を、初めて見るように歩こう。',
        ko: '매일 같은 길을 처음 보는 것처럼 걸어라.',
      },
    },
    caption: {
      tr: 'Köpeğim 5 yıldır aynı sokağı keşfediyor',
      en: "My dog's been discovering the same block for 5 years",
      de: 'Mein Hund entdeckt seit 5 Jahren dieselbe Straße',
      ar: 'كلبي يكتشف الشارع نفسه منذ 5 سنوات',
      fr: 'Mon chien découvre la même rue depuis 5 ans',
      es: 'Mi perro lleva 5 años descubriendo la misma calle',
      ja: 'うちの犬、5年間同じ道を新発見し続けてる',
      ko: '우리 개는 5년째 같은 골목을 탐험 중이다',
    },
  },
  {
    emoji: '🌀',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hedefinin peşinden koş. Kendi kuyruğun bile olsa.',
        en: "Chase your dreams. Even if it's your own tail.",
        de: 'Jag deinen Träumen nach. Auch wenn du dich dabei im Kreis drehst.',
        ar: 'طارد أحلامك، حتى لو كانت ذيلك.',
        fr: "Poursuis tes rêves. Même s'ils tournent en rond.",
        es: 'Persigue tus sueños, aunque den vueltas en círculo.',
        ja: '夢を追いかけよう。それが自分のしっぽでも。',
        ko: '꿈을 쫓아라. 그게 자기 꼬리일지라도.',
      },
    },
    caption: {
      tr: 'Köpeğim 10 dakikadır bu hedefin peşinde',
      en: "My dog's been chasing this goal for 10 minutes",
      de: 'Mein Hund verfolgt dieses Ziel seit 10 Minuten',
      ar: 'كلبي يطارد هذا الهدف منذ 10 دقائق',
      fr: 'Mon chien poursuit ce rêve depuis 10 minutes',
      es: 'Mi perro lleva 10 minutos tras esta meta',
      ja: 'うちの犬、この夢を10分間追いかけてる',
      ko: '우리 개가 10분째 이 꿈을 쫓는 중',
    },
  },
  {
    emoji: '💻',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Kedi gibi ol: istediğin yere otur, kimseye açıklama yapma.',
        en: 'Be like a cat: sit wherever you want and explain nothing.',
        de: 'Sei wie eine Katze: Setz dich, wohin du willst. Erklär nichts.',
        ar: 'كن كالقطة: اجلس حيث تشاء ولا تبرّر لأحد.',
        fr: 'Sois comme un chat : assieds-toi où tu veux, sans te justifier.',
        es: 'Sé como un gato: siéntate donde quieras y no expliques nada.',
        ja: '猫のように生きよう。好きな所に座り、言い訳はしない。',
        ko: '고양이처럼 살아라: 앉고 싶은 곳에 앉고, 설명하지 마라.',
      },
    },
    caption: {
      tr: 'Laptopun üstü dahil',
      en: 'Laptop included',
      de: 'Auch auf dem Laptop',
      ar: 'حتى فوق الحاسوب',
      fr: 'Clavier compris',
      es: 'Incluido el teclado',
      ja: 'ノートパソコンの上も含めて',
      ko: '노트북 위도 포함',
    },
  },
];

export const ANIMALS_LIKE: readonly Draft[] = [
  {
    emoji: '🐱',
    user: ACCOUNTS.defne,
    body: { format: 'scene' },
    caption: {
      tr: 'sokak kedisini sahiplendim, o da yatağımı',
      en: 'adopted a street cat. she adopted my bed',
      de: 'hab eine straßenkatze adoptiert, sie mein bett',
      ar: 'تبنّيت قطة من الشارع… وهي تبنّت سريري',
      fr: "j'ai adopté un chat des rues, il a adopté mon lit",
      es: 'adopté una gata callejera y ella adoptó mi cama',
      ja: '野良猫を引き取ったら、ベッドを引き取られた',
      ko: '길냥이 입양함. 걔는 내 침대를 입양함',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.tolga,
    body: { format: 'scene' },
    caption: {
      tr: 'köpeğim denizi ilk kez gördü, dalgalarla tartıştı',
      en: "my dog met the sea today. he's arguing with the waves",
      de: 'mein hund kennt jetzt das meer. er streitet mit den wellen',
      ar: 'كلبي رأى البحر لأول مرة… وبدأ يجادل الأمواج',
      fr: '1re fois à la mer : mon chien se dispute avec les vagues',
      es: 'mi perro vio el mar por primera vez y discutió con las olas',
      ja: 'うちの犬、初めての海で波とケンカしてる',
      ko: '우리 개 바다 처음 봄. 파도랑 싸우는 중',
    },
  },
  {
    emoji: '🐣',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'civcivler çıktı, biri beni annesi sandı',
      en: "the chicks hatched and one thinks i'm its mom",
      de: 'die küken sind geschlüpft, eins hält mich für seine mama',
      ar: 'فقست الكتاكيت… وأحدها يظنني أمه',
      fr: "les poussins sont nés, l'un d'eux me prend pour sa mère",
      es: 'nacieron los pollitos y uno cree que soy su mamá',
      ja: 'ひよこが生まれて、1羽が私をママだと思ってる',
      ko: '병아리 부화함. 한 마리가 날 엄마인 줄 앎',
    },
  },
  {
    emoji: '🐹',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'hamsterıma 3 saatte labirent yaptım, 4 saniyede çözdü',
      en: '3-hour maze for my hamster. solved in 4 seconds',
      de: 'labyrinth für meinen hamster: 3 std. gebaut, 4 sek. gelöst',
      ar: 'بنيت متاهة لهامستري في 3 ساعات… فحلّها في 4 ثوانٍ',
      fr: "j'ai mis 3 h à faire un labyrinthe. mon hamster, 4 s.",
      es: '3 horas de laberinto y mi hámster salió en 4 segundos',
      ja: 'ハムスターに3時間かけて迷路を作った。4秒で解かれた',
      ko: '햄스터 미로 3시간 걸려 만듦. 4초 만에 탈출함',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.berk,
    body: {
      format: 'polaroid',
      note: {
        tr: 'favori mekânı',
        en: 'his favorite hangout',
        de: 'sein lieblingsort',
        ar: 'مكانه المفضّل',
        fr: 'son endroit préféré',
        es: 'su lugar favorito',
        ja: 'お気に入りスポット',
        ko: '최애 장소',
      },
    },
    caption: {
      tr: 'veterinerde ödül yedi, her gün oraya çekiyor',
      en: 'got a treat at the vet. now he pulls me there every day',
      de: "beim tierarzt gab's ein leckerli. jetzt zieht er täglich hin",
      ar: 'أخذ مكافأة عند البيطري… والآن يجرّني إليه كل يوم',
      fr: 'friandise chez le véto : il veut y aller tous les jours',
      es: 'premio en el veterinario: ahora quiere ir todos los días',
      ja: '動物病院でおやつをもらって以来、毎日そっちに引っぱられる',
      ko: '동물병원에서 간식 받더니 매일 그쪽으로 끌고 감',
    },
  },
  {
    emoji: '🦩',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ben ve hocalarım',
        en: 'me & my coaches',
        de: 'ich und meine trainer',
        ar: 'أنا ومدرّباتي',
        fr: 'moi et mes profs',
        es: 'yo y mis maestros',
        ja: '私と師匠たち',
        ko: '나와 스승님들',
      },
    },
    caption: {
      tr: 'flamingolarla aynı poz (ben 2 saniye dayandım)',
      en: 'same pose as the flamingos (i lasted 2 seconds)',
      de: 'gleiche pose wie die flamingos (ich hielt 2 sekunden)',
      ar: 'نفس وقفة طيور النحام… صمدت ثانيتين فقط',
      fr: "même pose que les flamants roses (j'ai tenu 2 secondes)",
      es: 'misma pose que los flamencos (aguanté 2 segundos)',
      ja: 'フラミンゴと同じポーズ（私は2秒でギブ）',
      ko: '플라밍고랑 같은 포즈 (난 2초 버팀)',
    },
  },
  {
    emoji: '🐴',
    user: ACCOUNTS.arda,
    body: {
      format: 'polaroid',
      note: {
        tr: 'direksiyon onda',
        en: "he's driving",
        de: 'er lenkt',
        ar: 'القيادة له',
        fr: "c'est lui qui conduit",
        es: 'él lleva las riendas',
        ja: '運転は彼',
        ko: '운전은 얘가',
      },
    },
    caption: {
      tr: 'ilk binicilik dersim: at nereye, ben oraya',
      en: 'first riding lesson: wherever the horse goes, i go',
      de: 'erste reitstunde: wohin das pferd will, da will ich auch',
      ar: 'أول درس ركوب خيل: حيث يذهب الحصان أذهب',
      fr: "1er cours d'équitation : là où va le cheval, je vais",
      es: 'primera clase de equitación: voy a donde quiere el caballo',
      ja: '初めての乗馬レッスン：馬が行く方へ私も行く',
      ko: '첫 승마 수업: 말 가는 대로 나도 감',
    },
  },
  {
    emoji: '🐱',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'doğum günü kızı 🎂',
        en: 'birthday girl 🎂',
        de: 'geburtstagskind 🎂',
        ar: 'صاحبة العيد 🎂',
        fr: 'reine du jour 🎂',
        es: 'la cumpleañera 🎂',
        ja: '今日の主役 🎂',
        ko: '생일 주인공 🎂',
      },
    },
    caption: {
      tr: 'kedim şapkayı 1 saniye taktı, o saniyeyi yakaladım',
      en: 'my cat kept the party hat on for 1 second. i got it',
      de: 'meine katze trug den partyhut 1 sekunde. erwischt!',
      ar: 'قطتي لبست قبعة الحفلة ثانية واحدة… والتقطتها!',
      fr: 'ma minette a gardé le chapeau 1 seconde. photo prise !',
      es: 'mi gata aguantó el gorrito 1 segundo y lo capturé',
      ja: '猫がパーティー帽を被ったのは1秒だけ。その1秒を撮った',
      ko: '고양이가 고깔모자 1초 씀. 그 1초를 찍음',
    },
  },
  {
    emoji: '🐩',
    user: ACCOUNTS.onur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ikiz kombin',
        en: 'matching fit',
        de: 'partnerlook',
        ar: 'إطلالة متطابقة',
        fr: 'tenue assortie',
        es: 'conjunto a juego',
        ja: 'おそろいコーデ',
        ko: '커플룩',
      },
    },
    caption: {
      tr: 'köpeğimle aynı pijamayı aldık, ona daha çok yakıştı',
      en: 'got matching pajamas with my dog. he pulls it off better',
      de: 'partnerlook-pyjama mit meinem hund. ihm steht er besser',
      ar: 'بيجامة مطابقة لي ولكلبي… وهي عليه أجمل',
      fr: 'pyjama assorti avec mon chien. ça lui va mieux',
      es: 'pijama a juego con mi perro. a él le queda mejor',
      ja: '犬とおそろいのパジャマを買った。犬のほうが似合う',
      ko: '강아지랑 커플 잠옷 삼. 걔가 더 잘 어울림',
    },
  },
  {
    emoji: '🕊️',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🕊️', '🦒', '🐘', '🦁'] },
    caption: {
      tr: 'hayvanat bahçesi dump’ı: en çok güvercini çektim',
      en: 'zoo dump: most of my photos are pigeons',
      de: 'zoo-dump: die meisten fotos sind tauben',
      ar: 'رحلة حديقة الحيوان: معظم صوري للحمام',
      fr: "dump du zoo : la plupart de mes photos, c'est des pigeons",
      es: 'día en el zoológico: la mayoría de mis fotos son palomas',
      ja: '動物園の写真まとめ：ほぼハトしか撮ってない',
      ko: '동물원 사진 덤프: 거의 다 비둘기임',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['🐶', '🩴', '🧸', '🛋️'] },
    caption: {
      tr: 'yavrumun ilk haftası: 2 terlik, 1 minder, bol sevgi',
      en: "puppy's first week: 2 slippers, 1 cushion, endless love",
      de: 'welpe, woche 1: 2 hausschuhe, 1 kissen, ganz viel liebe',
      ar: 'أسبوع الجرو الأول: خفّان، ووسادة، وحب لا ينتهي',
      fr: '1re semaine du chiot : 2 chaussons, 1 coussin, amour infini',
      es: 'cachorro, semana 1: 2 pantuflas, 1 cojín, amor infinito',
      ja: '子犬の1週目：スリッパ2足、クッション1個、愛情たっぷり',
      ko: '강아지 첫 주: 슬리퍼 2개, 방석 1개, 사랑 가득',
    },
  },
  {
    emoji: '🔭',
    user: ACCOUNTS.baris,
    body: { format: 'dump', emojis: ['🔭', '🌲', '🐦', '🥪', '🥾'] },
    caption: {
      tr: 'kuş gözlemi: 6 saat, 1 serçe, çok mutluyum',
      en: 'birdwatching: 6 hours, 1 sparrow, so happy',
      de: 'vogelbeobachtung: 6 stunden, 1 spatz, überglücklich',
      ar: 'مراقبة الطيور: 6 ساعات، عصفور واحد، وسعادة كبيرة',
      fr: 'sortie ornitho : 6 h, 1 moineau, trop heureux',
      es: 'observando aves: 6 horas, 1 gorrión y mucha felicidad',
      ja: 'バードウォッチング：6時間でスズメ1羽。大満足',
      ko: '탐조 6시간, 참새 1마리, 너무 행복함',
    },
  },
];

export const ANIMALS_HOLD: readonly Draft[] = [
  {
    emoji: '🎾',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir an: köpek topu getirdi ve bıraktı',
      en: 'Rare moment: the dog brought the ball AND let go',
      de: 'Seltener Moment: Der Hund bringt den Ball UND lässt los',
      ar: 'لحظة نادرة: أحضر الكلب الكرة… وتركها!',
      fr: 'Moment rare : le chien rapporte la balle ET la lâche',
      es: 'Momento único: el perro trajo la pelota Y la soltó',
      ja: 'レアな瞬間：犬がボールを持ってきて、しかも離した',
      ko: '희귀한 순간: 강아지가 공을 가져와서 놓기까지 했다',
    },
  },
  {
    emoji: '🦚',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tavus kuşu kuyruğunu açtı. Sadece senin için.',
      en: 'The peacock fanned its tail. Just for you.',
      de: 'Der Pfau schlägt ein Rad. Nur für dich.',
      ar: 'الطاووس فرد ذيله… من أجلك وحدك',
      fr: 'Le paon fait la roue. Rien que pour toi.',
      es: 'El pavo real abrió la cola. Solo para ti.',
      ja: 'クジャクが羽を広げた。あなただけのために。',
      ko: '공작새가 꼬리를 펼쳤어요. 오직 당신만을 위해.',
    },
  },
  {
    emoji: '🐬',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Vapurdan yunus göründü! 3 saniye sonra dalacak',
      en: 'Dolphin by the ferry! It dives again in 3 seconds',
      de: 'Delfin neben der Fähre! In 3 Sekunden taucht er ab',
      ar: 'دلفين بجانب العبّارة! سيغوص بعد 3 ثوانٍ',
      fr: 'Un dauphin près du ferry ! Il replonge dans 3 secondes',
      es: '¡Un delfín junto al barco! Se sumerge en 3 segundos',
      ja: 'フェリーの横にイルカ！3秒後にまた潜る',
      ko: '여객선 옆에 돌고래! 3초 뒤에 다시 잠수함',
    },
  },
  {
    emoji: '🦴',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayıp hazine bulundu: köpeğin gizli kemik zulası',
      en: "Lost treasure found: the dog's secret bone stash",
      de: 'Schatz gefunden: das geheime Knochenlager vom Hund',
      ar: 'عُثر على الكنز المفقود: مخبأ عظام الكلب السري',
      fr: "Trésor retrouvé : la réserve secrète d'os du chien",
      es: 'Tesoro encontrado: el escondite secreto de huesos del perro',
      ja: '幻の財宝を発見：犬がへそくりしてた骨',
      ko: '잃어버린 보물 발견: 강아지의 비밀 뼈다귀 창고',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Gündüz uyanık bir baykuş. Milyonda bir.',
      en: 'An owl, wide awake at noon. One in a million.',
      de: 'Eine Eule, mittags hellwach. Eins zu einer Million.',
      ar: 'بومة مستيقظة في عزّ النهار… واحدة في المليون',
      fr: 'Une chouette réveillée à midi. Une sur un million.',
      es: 'Un búho despierto al mediodía. Uno en un millón.',
      ja: '真っ昼間に起きてるフクロウ。100万分の1。',
      ko: '대낮에 깨어 있는 부엉이. 백만 분의 일.',
    },
  },
  {
    emoji: '🐠',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kalesinden hiç çıkmayan balık sonunda göründü',
      en: 'The fish that never leaves its castle came out',
      de: 'Der Fisch, der nie aus seiner Burg kommt, ist draußen',
      ar: 'السمكة التي لا تغادر قلعتها خرجت أخيرًا',
      fr: 'Le poisson qui ne quitte jamais son château est sorti',
      es: 'El pez que nunca sale de su castillo por fin salió',
      ja: 'お城から出てこない魚が、ついに出てきた',
      ko: '성 밖으로 절대 안 나오던 물고기가 드디어 나왔다',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi kare: 3 patili, 3’ü de kameraya bakıyor',
      en: 'Legendary shot: all 3 pets looking at the camera',
      de: 'Legendäres Foto: Alle 3 Haustiere schauen in die Kamera',
      ar: 'لقطة أسطورية: الحيوانات الثلاثة تنظر إلى الكاميرا',
      fr: "Photo légendaire : les 3 animaux regardent l'objectif",
      es: 'Foto legendaria: las 3 mascotas mirando a la cámara',
      ja: '伝説の1枚：3匹全員がカメラ目線',
      ko: '전설의 한 컷: 3마리 모두 카메라 정면',
    },
  },
];

export const ANIMALS_FREEZE: readonly Draft[] = [
  {
    emoji: '💤',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'MEŞGUL',
        en: 'OCCUPIED',
        de: 'BESETZT',
        ar: 'مشغول',
        fr: 'OCCUPÉ',
        es: 'OCUPADO',
        ja: '使用中',
        ko: '사용 중',
      },
      small: {
        tr: 'KEDİ KUCAKTA UYUYOR',
        en: 'CAT ASLEEP ON LAP',
        de: 'KATZE SCHLÄFT AUF DEM SCHOSS',
        ar: 'القطة نائمة في الحضن',
        fr: 'CHAT ENDORMI SUR LES GENOUX',
        es: 'GATO DORMIDO EN LAS PIERNAS',
        ja: 'ひざの上で猫が睡眠中',
        ko: '무릎 위 고양이 취침 중',
      },
    },
    caption: {
      tr: 'Artık burada yaşıyorsun.',
      en: 'You live here now.',
      de: 'Du wohnst jetzt hier.',
      ar: 'أنت تسكن هنا الآن.',
      fr: 'Tu habites ici, maintenant.',
      es: 'Ahora vives aquí.',
      ja: 'もう、ここに住むしかない。',
      ko: '이제 여기서 사셔야 해요.',
    },
    headline: {
      tr: 'Kedi kucağında uyuyakaldı',
      en: 'The cat fell asleep on your lap',
      de: 'Die Katze schläft auf deinem Schoß',
      ar: 'القطة نامت في حضنك',
      fr: "Le chat s'est endormi sur toi",
      es: 'El gato se durmió en tus piernas',
      ja: '猫がひざの上で寝ちゃった',
      ko: '고양이가 무릎에서 잠들었어요',
    },
  },
  {
    emoji: '🦌',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'CAUTION',
        de: 'ACHTUNG',
        ar: 'انتبه',
        fr: 'ATTENTION',
        es: 'PRECAUCIÓN',
        ja: '注意',
        ko: '주의',
      },
      small: {
        tr: 'GEYİK ÇIKABİLİR',
        en: 'DEER CROSSING',
        de: 'WILDWECHSEL',
        ar: 'منطقة عبور غزلان',
        fr: 'PASSAGE DE CERFS',
        es: 'CRUCE DE CIERVOS',
        ja: 'シカ飛び出し注意',
        ko: '사슴 출몰 지역',
      },
    },
    caption: {
      tr: 'İlk kıpırdayan kaybeder.',
      en: 'First one to move loses.',
      de: 'Wer sich zuerst bewegt, verliert.',
      ar: 'أول من يتحرك يخسر.',
      fr: 'Le premier qui bouge a perdu.',
      es: 'El primero que se mueva pierde.',
      ja: '先に動いたほうが負け。',
      ko: '먼저 움직이는 쪽이 지는 거예요.',
    },
    headline: {
      tr: 'Bir geyikle göz göze geldin',
      en: 'You and a deer just locked eyes',
      de: 'Du und ein Reh: Blickkontakt',
      ar: 'التقت عيناك بعيني غزال',
      fr: 'Toi et un cerf, les yeux dans les yeux',
      es: 'Un ciervo te mira fijo a los ojos',
      ja: 'シカと目が合った',
      ko: '사슴과 눈이 마주쳤어요',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'FLAŞ YASAK',
        en: 'NO FLASH',
        de: 'KEIN BLITZ',
        ar: 'ممنوع الفلاش',
        fr: 'PAS DE FLASH',
        es: 'SIN FLASH',
        ja: 'フラッシュ禁止',
        ko: '플래시 금지',
      },
      small: {
        tr: 'BAYKUŞLAR UYUYOR',
        en: 'OWLS SLEEPING',
        de: 'EULEN SCHLAFEN',
        ar: 'البوم نائم',
        fr: 'CHOUETTES ENDORMIES',
        es: 'BÚHOS DURMIENDO',
        ja: 'フクロウ睡眠中',
        ko: '부엉이 자는 중',
      },
    },
    caption: {
      tr: 'Seni gördü. Kıpırdama.',
      en: "It saw you. Don't move.",
      de: 'Sie hat dich gesehen. Keine Bewegung.',
      ar: 'لقد رأتك. لا تتحرك.',
      fr: "Elle t'a vu. Bouge pas.",
      es: 'Te vio. No te muevas.',
      ja: '見られてる。動かないで。',
      ko: '들켰어요. 움직이지 마세요.',
    },
    headline: {
      tr: 'Baykuş tek gözünü açtı',
      en: 'The owl just opened one eye',
      de: 'Die Eule hat ein Auge geöffnet',
      ar: 'البومة فتحت عينًا واحدة',
      fr: 'La chouette a ouvert un œil',
      es: 'El búho abrió un ojo',
      ja: 'フクロウが片目を開けた',
      ko: '부엉이가 한쪽 눈을 떴어요',
    },
  },
  {
    emoji: '🐒',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYARI',
        en: 'WARNING',
        de: 'WARNUNG',
        ar: 'تحذير',
        fr: 'AVERTISSEMENT',
        es: 'ADVERTENCIA',
        ja: '警告',
        ko: '경고',
      },
      small: {
        tr: 'MAYMUNLAR TAKLİT EDER',
        en: 'MONKEYS COPY EVERYTHING',
        de: 'AFFEN MACHEN ALLES NACH',
        ar: 'القرود تقلّد كل شيء',
        fr: 'LES SINGES IMITENT TOUT',
        es: 'LOS MONOS IMITAN TODO',
        ja: 'サルが動きをマネします',
        ko: '원숭이가 행동을 따라 합니다',
      },
    },
    caption: {
      tr: 'Sen durursan o da durur.',
      en: 'Freeze, and so will it.',
      de: 'Halt still, dann hält er auch still.',
      ar: 'توقّف كي يتوقف هو أيضًا.',
      fr: "Arrête-toi, il s'arrêtera aussi.",
      es: 'Quédate quieto y él también.',
      ja: 'あなたが止まれば、サルも止まる。',
      ko: '멈추면 원숭이도 멈춰요.',
    },
    headline: {
      tr: 'Maymun her hareketini taklit ediyor',
      en: 'A monkey is copying your every move',
      de: 'Ein Affe macht dir alles nach',
      ar: 'قرد يقلّد كل حركة تقوم بها',
      fr: 'Un singe imite tous tes gestes',
      es: 'Un mono imita cada movimiento tuyo',
      ja: 'サルがあなたの動きを全部マネしてる',
      ko: '원숭이가 모든 동작을 따라 해요',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'KORİDOR', en: 'HALLWAY', de: 'FLUR', ar: 'الممر', fr: 'COULOIR', es: 'PASILLO', ja: '廊下', ko: '복도' },
    },
    caption: {
      tr: 'Bir adım at, ayaklarına atlar.',
      en: 'Take one step and it pounces.',
      de: 'Ein Schritt, und sie springt.',
      ar: 'خطوة واحدة وتنقضّ على قدميك.',
      fr: 'Un pas, et il bondit.',
      es: 'Da un paso y se lanza.',
      ja: '一歩でも動けば飛びかかってくる。',
      ko: '한 발짝만 떼면 달려들어요.',
    },
    headline: {
      tr: 'Kedi pusuda, ayaklarını izliyor',
      en: 'Cat in ambush mode. Target: your feet',
      de: 'Die Katze lauert. Ziel: deine Füße',
      ar: 'القطة تكمن لك… وهدفها قدماك',
      fr: "Le chat est à l'affût. Cible : tes pieds",
      es: 'El gato acecha. Objetivo: tus pies',
      ja: '猫が待ち伏せ中。狙いはあなたの足',
      ko: '고양이 매복 중. 목표물은 발이에요.',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAPI ÖNÜ',
        en: 'DOORSTEP',
        de: 'HAUSEINGANG',
        ar: 'عتبة الباب',
        fr: 'PAS DE LA PORTE',
        es: 'ENTRADA',
        ja: '玄関前',
        ko: '현관 앞',
      },
    },
    caption: {
      tr: 'Az kaldı. Nefesini tut.',
      en: 'Almost there. Hold your breath.',
      de: 'Fast geschafft. Luft anhalten.',
      ar: 'اقتربت… احبس أنفاسك.',
      fr: 'Presque. Retiens ton souffle.',
      es: 'Ya casi. Aguanta la respiración.',
      ja: 'あと少し。息を止めて。',
      ko: '조금만 더. 숨 참으세요.',
    },
    headline: {
      tr: 'Ürkek sokak kedisi ilk kez yaklaşıyor',
      en: 'The shy stray is finally coming closer',
      de: 'Die scheue Streunerkatze kommt näher',
      ar: 'قطة الشارع الخجولة تقترب لأول مرة',
      fr: "Le chat errant timide s'approche enfin",
      es: 'La gata callejera tímida se acerca',
      ja: '人見知りの野良猫が初めて近づいてきた',
      ko: '겁 많은 길고양이가 처음으로 다가와요',
    },
  },
  {
    emoji: '🦔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'BAHÇE', en: 'BACKYARD', de: 'GARTEN', ar: 'الحديقة', fr: 'JARDIN', es: 'JARDÍN', ja: '庭', ko: '뒷마당' },
    },
    caption: {
      tr: 'Ses çıkarma, top olur.',
      en: "One sound and it's a ball.",
      de: 'Ein Mucks, und er rollt sich ein.',
      ar: 'صوت واحد ويتكوّر.',
      fr: 'Un bruit, et il se roule en boule.',
      es: 'Un ruido y se hace bolita.',
      ja: '音を立てたら、丸まっちゃう。',
      ko: '소리 한 번이면 공처럼 말려요.',
    },
    headline: {
      tr: 'Kirpi bahçeye çıktı, seni fark etmedi',
      en: "A hedgehog's out. It hasn't seen you.",
      de: 'Ein Igel im Garten – er sieht dich nicht',
      ar: 'قنفذ في الحديقة ولم يلاحظك بعد',
      fr: "Un hérisson sort. Il ne t'a pas vu.",
      es: 'Salió un erizo y no te ha visto',
      ja: 'ハリネズミ登場。まだ気づかれてない',
      ko: '고슴도치가 나왔어요. 아직 안 들켰어요',
    },
  },
  {
    emoji: '🛁',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'BANYO',
        en: 'BATHROOM',
        de: 'BADEZIMMER',
        ar: 'الحمّام',
        fr: 'SALLE DE BAIN',
        es: 'BAÑO',
        ja: '浴室',
        ko: '욕실',
      },
    },
    caption: {
      tr: 'Tek hareket ve yatağın altına kaçar.',
      en: "One move and he's under the bed.",
      de: 'Eine Bewegung, und er ist unterm Bett.',
      ar: 'حركة واحدة ويختبئ تحت السرير.',
      fr: 'Un geste, et il file sous le lit.',
      es: 'Un movimiento y se esconde bajo la cama.',
      ja: 'ちょっとでも動けば、ベッドの下に逃げる。',
      ko: '움직이는 순간 침대 밑으로 도망가요.',
    },
    headline: {
      tr: 'Köpek banyo suyunu duydu, seni izliyor',
      en: 'The dog heard the bath. Eyes on you.',
      de: 'Der Hund hat das Badewasser gehört',
      ar: 'الكلب سمع ماء الحمّام… وهو يراقبك',
      fr: 'Le chien a entendu le bain couler',
      es: 'El perro oyó el agua del baño',
      ja: '犬がお風呂の音を聞いた。見られてる',
      ko: '강아지가 목욕물 소리를 들었어요',
    },
  },
];
