import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Family: parents, grandparents, siblings, cousins, the family group chat, holidays and visits.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const FAMILY_SKIP: readonly Draft[] = [
  {
    emoji: '🗣️',
    user: ACCOUNTS.family,
    body: { format: 'scene' },
    caption: {
      tr: 'Aile yemeği: 6 sohbet birden. Babaannem hepsinde.',
      en: "Family dinner: 6 chats at once. Grandma's in all of them.",
      de: '6 Gespräche beim Familienessen. Oma redet überall mit.',
      ar: 'عشاء العائلة: 6 أحاديث معًا… وجدتي في كلها',
      fr: 'Repas de famille : 6 conversations. Mamie est dans toutes.',
      es: 'Cena familiar: 6 charlas a la vez. La abuela, en todas.',
    },
  },
  {
    emoji: '👴',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Dedem görüntülü aradı. 20 dakika alnını izledim.',
      en: 'Video call with Grandpa: 20 minutes of forehead.',
      de: 'Videoanruf mit Opa: 20 Minuten Stirn.',
      ar: 'اتصل جدي بالفيديو… وشاهدت جبينه 20 دقيقة',
      fr: 'Appel vidéo avec papi : 20 minutes de front.',
      es: 'Videollamada con el abuelo: 20 minutos de su frente.',
    },
  },
  {
    emoji: '🚙',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Babam bagajı kapattı. Çantam hâlâ elimde.',
      en: "Dad just shut the trunk. My bag's still in my hand.",
      de: 'Papa macht den Kofferraum zu. Meine Tasche hab ich noch.',
      ar: 'أغلق أبي صندوق السيارة… وحقيبتي ما زالت في يدي',
      fr: "Papa vient de fermer le coffre. J'ai encore mon sac.",
      es: 'Papá cerró el maletero. Mi bolso sigue en mi mano.',
    },
  },
  {
    emoji: '📏',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: '“Ne kadar büyümüşsün!” Teyze, 26 yaşındayım.',
      en: "“Look how big you've gotten!” Auntie, I'm 26.",
      de: '„Bist du groß geworden!“ Tante, ich bin 26.',
      ar: '«كم كبرت!»… يا خالتي، عمري 26 سنة',
      fr: "« Comme t'as grandi ! » Tata, j'ai 26 ans.",
      es: '“¡Cómo has crecido!” Tía, tengo 26 años.',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.screens,
    body: { format: 'scene' },
    caption: {
      tr: 'Babam ss attı. Annemin telefonuyla çekmiş.',
      en: "Dad sent a screenshot. He took it with Mom's phone.",
      de: 'Papas Screenshot: mit Mamas Handy abfotografiert',
      ar: 'أرسل أبي لقطة شاشة… صوّرها بهاتف أمي',
      fr: "La capture d'écran de papa : prise avec le tel de maman",
      es: 'La captura de papá: una foto con el teléfono de mamá',
    },
  },
  {
    emoji: '🧒',
    user: ACCOUNTS.family,
    body: { format: 'scene' },
    caption: {
      tr: 'Kuzenime 5 dakika telefonumu verdim. Dili değişmiş.',
      en: 'My little cousin had my phone for 5 minutes. New language.',
      de: 'Mein Cousin hatte 5 Minuten mein Handy. Neue Sprache.',
      ar: 'أعرت ابن عمي الصغير هاتفي 5 دقائق… فتغيّرت لغته',
      fr: 'Mon petit cousin a eu mon tel 5 minutes. Nouvelle langue.',
      es: '5 minutos con mi primito y mi teléfono cambió de idioma',
    },
  },
  {
    emoji: '⌛',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba cumartesi müsait misin?',
            en: 'dad, are you free saturday?',
            de: 'Papa, hast du Samstag Zeit?',
            ar: 'أبي، هل أنت متفرغ يوم السبت؟',
            fr: "papa, t'es dispo samedi ?",
            es: 'papá, ¿estás libre el sábado?',
          },
        },
        {
          from: 'them',
          text: { tr: 'Evet.', en: 'Yes.', de: 'Ja.', ar: 'نعم.', fr: 'Oui.', es: 'Sí.' },
        },
        {
          from: 'me',
          text: {
            tr: 'baba cumartesi geçti 😅',
            en: 'dad, saturday was last week 😅',
            de: 'Papa, Samstag war letzte Woche 😅',
            ar: 'أبي، السبت مضى 😅',
            fr: "papa, samedi c'était la semaine dernière 😅",
            es: 'papá, el sábado ya pasó 😅',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'O zaman öbür cumartesi.',
            en: 'Then next Saturday.',
            de: 'Dann nächsten Samstag.',
            ar: 'إذن السبت الذي يليه.',
            fr: 'Alors samedi prochain.',
            es: 'Entonces el próximo sábado.',
          },
        },
      ],
    },
    caption: {
      tr: 'Babamın cevap süresi: 5 iş günü',
      en: "Dad's reply time: 5 business days",
      de: 'Papas Antwortzeit: 5 Werktage',
      ar: 'مدة ردّ أبي: 5 أيام عمل',
      fr: 'Délai de réponse de papa : 5 jours ouvrés',
      es: 'Tiempo de respuesta de papá: 5 días hábiles',
    },
  },
  {
    emoji: '🍖',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Dayım', en: 'Uncle', de: 'Onkel', ar: 'خالي', fr: 'Tonton', es: 'Tío' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'Pazar mangal var, herkes davetli! 🔥',
            en: "BBQ on Sunday, everyone's invited! 🔥",
            de: 'Sonntag Grillen, alle eingeladen! 🔥',
            ar: 'شواء يوم العطلة، والجميع مدعو! 🔥',
            fr: 'Barbecue dimanche, tous invités ! 🔥',
            es: '¡Asado el domingo, todos invitados! 🔥',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'süper! ne getirelim?',
            en: 'awesome! what should we bring?',
            de: 'super! was sollen wir mitbringen?',
            ar: 'رائع! ماذا نُحضر؟',
            fr: 'trop bien ! on apporte quoi ?',
            es: '¡genial! ¿qué llevamos?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Eti, kömürü, bir de mangalı',
            en: 'The meat, the charcoal and the grill',
            de: 'Fleisch, Kohle und den Grill',
            ar: 'اللحم والفحم… والشوّاية',
            fr: 'La viande, le charbon et le barbecue',
            es: 'La carne, el carbón y la parrilla',
          },
        },
      ],
    },
    caption: {
      tr: 'Davet dayımdan, gerisi bizden',
      en: 'He brings the invite. We bring the rest.',
      de: 'Er lädt ein. Wir bringen den Rest.',
      ar: 'الدعوة من خالي… والباقي علينا',
      fr: 'Il invite. On apporte tout le reste.',
      es: 'Él invita. Nosotros ponemos el resto.',
    },
  },
  {
    emoji: '♻️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'Şu videoyu izle, çok komik 😂',
            en: 'Watch this video, so funny 😂',
            de: 'Guck mal, voll lustig 😂',
            ar: 'شاهد هذا الفيديو، مضحك جدًا 😂',
            fr: 'Regarde cette vidéo, trop drôle 😂',
            es: 'Mira este video, qué risa 😂',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'anne onu sana ben attım',
            en: 'mom, I sent you that',
            de: 'Mama, das hab ich dir geschickt',
            ar: 'أمي، أنا من أرسله إليك',
            fr: "maman, c'est moi qui te l'ai envoyée",
            es: 'mamá, yo te lo mandé',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'O zaman bir daha izle',
            en: 'Then watch it again',
            de: "Dann guck's nochmal",
            ar: 'إذن شاهده مرة أخرى',
            fr: 'Alors regarde-la encore',
            es: 'Entonces míralo otra vez',
          },
        },
      ],
    },
    caption: {
      tr: 'Aile içi geri dönüşüm',
      en: 'Family recycling program',
      de: 'Familien-Recycling',
      ar: 'إعادة تدوير عائلية',
      fr: 'Le recyclage familial',
      es: 'Reciclaje familiar',
    },
  },
  {
    emoji: '🥘',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Babaannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'Hafta sonu geliyor musun?',
            en: 'Coming this weekend?',
            de: 'Kommst du am Wochenende?',
            ar: 'هل ستأتي في عطلة نهاية الأسبوع؟',
            fr: 'Tu viens ce week-end ?',
            es: '¿Vienes este fin de semana?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'belki, bakacağım',
            en: "maybe, I'll see",
            de: 'vielleicht, mal sehen',
            ar: 'ربما، سأرى',
            fr: 'peut-être, je verrai',
            es: 'tal vez, ya veré',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Tamam, sarmaları sardım bile 😊',
            en: 'Great, I already made your favorite 😊',
            de: 'Gut, dein Lieblingsessen ist fertig 😊',
            ar: 'حسنًا، طبخت أكلتك المفضلة 😊',
            fr: "Super, j'ai déjà fait ton plat préféré 😊",
            es: 'Perfecto, ya hice tu comida favorita 😊',
          },
        },
      ],
    },
    caption: {
      tr: 'Gidiyorum galiba',
      en: "Guess I'm going",
      de: 'Ich fahre dann wohl hin',
      ar: 'يبدو أنني ذاهب',
      fr: "Bon, j'y vais, apparemment",
      es: 'Parece que voy',
    },
  },
  {
    emoji: '📛',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Annen seni kaçıncı denemede doğru isimle çağırır?',
        en: 'How many tries until Mom gets your name right?',
        de: 'Wie oft braucht Mama, bis dein Name stimmt?',
        ar: 'كم محاولة تحتاج أمك لتناديك باسمك الصحيح؟',
        fr: "En combien d'essais ta mère trouve ton prénom ?",
        es: '¿Cuántos intentos para que mamá diga tu nombre?',
      },
      options: [
        {
          tr: 'İlkinde',
          en: 'First try',
          de: 'Beim ersten Mal',
          ar: 'من أول مرة',
          fr: 'Du premier coup',
          es: 'Al primero',
        },
        {
          tr: 'Kardeşimden sonra',
          en: "After my brother's",
          de: 'Nach meinem Bruder',
          ar: 'بعد اسم أخي',
          fr: 'Après mon frère',
          es: 'Después de mi hermano',
        },
        {
          tr: 'Kediden bile sonra',
          en: "After the cat's",
          de: 'Sogar nach der Katze',
          ar: 'حتى بعد اسم القطة',
          fr: 'Même après le chat',
          es: 'Hasta después del gato',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Kardeşim, kedi, dayım… sonra ben',
      en: 'My brother, the cat, my uncle… then me',
      de: 'Mein Bruder, die Katze, mein Onkel… dann ich',
      ar: 'أخي، القطة، خالي… ثم أنا',
      fr: 'Mon frère, le chat, mon oncle… puis moi',
      es: 'Mi hermano, el gato, mi tío… y luego yo',
    },
  },
  {
    emoji: '🛣️',
    user: ACCOUNTS.family,
    body: {
      format: 'poll',
      question: {
        tr: 'Babam “bu yolu bilirim” dedi. Sonuç:',
        en: 'Dad said “I know a shortcut.” Result:',
        de: 'Papa: „Ich kenne eine Abkürzung.“ Ergebnis:',
        ar: 'قال أبي: «أعرف طريقًا مختصرًا». النتيجة؟',
        fr: 'Papa : « Je connais un raccourci. » Résultat ?',
        es: 'Papá dijo: “conozco un atajo”. ¿Resultado?',
      },
      options: [
        {
          tr: '10 dakika kazandık',
          en: 'Saved 10 minutes',
          de: '10 Minuten gespart',
          ar: 'وفّرنا 10 دقائق',
          fr: '10 minutes gagnées',
          es: 'Ahorramos 10 minutos',
        },
        {
          tr: 'Aynı köprü, 3. kez',
          en: 'Same bridge, 3rd time',
          de: '3. Mal dieselbe Brücke',
          ar: 'الجسر نفسه 3 مرات',
          fr: 'Même pont, 3e fois',
          es: 'Mismo puente, 3 veces',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Haritayı açmak gururuna dokunuyor',
      en: 'Opening the map would hurt his pride',
      de: 'Die Karte öffnen? Unter seiner Würde.',
      ar: 'فتح الخريطة يجرح كبرياءه',
      fr: 'Ouvrir la carte ? Son orgueil dit non.',
      es: 'Abrir el mapa hiere su orgullo',
    },
  },
  {
    emoji: '🔦',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Annen “dolapta, bak” dedi. Buldun mu?',
        en: "Mom said “it's in the closet.” Found it?",
        de: 'Mama: „Liegt im Schrank.“ Gefunden?',
        ar: 'قالت أمك: «في الخزانة». هل وجدته؟',
        fr: 'Maman : « Dans le placard. » Trouvé ?',
        es: 'Mamá dijo: “está en el armario”. ¿Lo encontraste?',
      },
      options: [
        { tr: 'Buldum', en: 'Found it', de: 'Gefunden', ar: 'وجدته', fr: 'Trouvé', es: 'Lo encontré' },
        {
          tr: 'O gelince bulundu',
          en: 'She found it instantly',
          de: 'Sie fand es sofort',
          ar: 'وجدته هي فورًا',
          fr: "Elle l'a trouvé direct",
          es: 'Ella, en un segundo',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Aynı rafa bakmıştım, gerçekten',
      en: 'I looked on that exact shelf. I swear.',
      de: 'Ich hab genau da geguckt. Ehrlich.',
      ar: 'بحثت في الرف نفسه، صدقًا',
      fr: "J'avais regardé pile là. Promis.",
      es: 'Busqué en ese mismo estante. Lo juro.',
    },
  },
  {
    emoji: '🎒',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'DEDEMİN OKUL YOLU',
        en: "GRANDPA'S WALK TO SCHOOL",
        de: 'OPAS SCHULWEG',
        ar: 'طريق جدي إلى المدرسة',
        fr: 'TRAJET ÉCOLE DE PAPI',
        es: 'RUTA ESCOLAR DEL ABUELO',
      },
      value: { tr: '12 km', en: '12 mi', de: '12 km', ar: '12 كم', fr: '12 km', es: '12 km' },
      shape: 'rise',
      axis: 'months',
    },
    caption: {
      tr: 'Her anlatışında 1 km uzuyor',
      en: 'Gets a mile longer every time he tells it',
      de: 'Wird mit jeder Erzählung 1 km länger',
      ar: 'يطول كيلومترًا مع كل مرة يرويها',
      fr: "S'allonge d'1 km à chaque récit",
      es: 'Crece 1 km cada vez que lo cuenta',
    },
  },
  {
    emoji: '🔇',
    user: ACCOUNTS.family,
    body: {
      format: 'chart',
      title: {
        tr: 'EVDEKİ GÜRÜLTÜ',
        en: 'NOISE AT HOME',
        de: 'LÄRM ZU HAUSE',
        ar: 'الضجيج في البيت',
        fr: 'LE BRUIT À LA MAISON',
        es: 'RUIDO EN CASA',
      },
      value: null,
      shape: 'crash',
      axis: 'days',
    },
    caption: {
      tr: 'Kardeşlerim kampa gitti. 3. gün: özledim.',
      en: 'My siblings left for camp. Day 3: I miss them.',
      de: 'Geschwister im Ferienlager. Tag 3: Ich vermisse sie.',
      ar: 'سافر إخوتي إلى المخيّم… وفي اليوم الثالث اشتقت إليهم',
      fr: 'Frères et sœurs en colo. Jour 3 : ils me manquent.',
      es: 'Mis hermanos se fueron de campamento. Día 3: los extraño.',
    },
  },
  {
    emoji: '🧥',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'ÇOCUK GİYİM',
        en: "KIDS' CLOTHING",
        de: 'KINDERMODE',
        ar: 'ملابس أطفال',
        fr: 'MODE ENFANT',
        es: 'ROPA INFANTIL',
      },
      items: [
        {
          tr: 'MONT (2 BEDEN BÜYÜK)',
          en: 'COAT (2 SIZES UP)',
          de: 'JACKE (2 GRÖSSEN MEHR)',
          ar: 'معطف (أكبر بمقاسين)',
          fr: 'MANTEAU (TAILLE +2)',
          es: 'ABRIGO (2 TALLAS MÁS)',
        },
      ],
    },
    caption: {
      tr: 'Annem: “Büyürsün.” 3 yıldır bekliyorum.',
      en: "Mom: “You'll grow into it.” Still waiting.",
      de: 'Mama: „Da wächst du rein.“ Ich warte noch.',
      ar: 'أمي: «ستكبر عليه». وما زلت أنتظر منذ 3 سنوات',
      fr: "Maman : « Tu vas grandir. » J'attends toujours.",
      es: 'Mamá: “Ya crecerás”. Sigo esperando.',
    },
  },
  {
    emoji: '🧽',
    user: ACCOUNTS.shopping,
    body: {
      format: 'receipt',
      store: {
        tr: 'KIRTASİYE',
        en: 'STATIONERY STORE',
        de: 'SCHREIBWAREN',
        ar: 'مكتبة وقرطاسية',
        fr: 'PAPETERIE',
        es: 'PAPELERÍA',
      },
      items: [
        {
          tr: 'YIKANABİLİR BOYA',
          en: 'WASHABLE CRAYONS',
          de: 'ABWASCHBARE MALSTIFTE',
          ar: 'ألوان قابلة للغسل',
          fr: 'CRAYONS LAVABLES',
          es: 'CRAYONES LAVABLES',
        },
        {
          tr: 'SÜNGER (3 ADET)',
          en: 'SPONGES (3)',
          de: 'SCHWÄMME (3 STÜCK)',
          ar: 'إسفنج (3 قطع)',
          fr: 'ÉPONGES (LOT DE 3)',
          es: 'ESPONJAS (3 UNIDADES)',
        },
      ],
    },
    caption: {
      tr: 'Kuzenim hafta sonu bizde. Duvarlar tedirgin.',
      en: "Little cousin's here all weekend. The walls are nervous.",
      de: 'Mein Cousin ist übers Wochenende da. Die Wände zittern.',
      ar: 'ابن عمي الصغير عندنا طوال العطلة… والجدران قلقة',
      fr: 'Mon petit cousin vient ce week-end. Les murs tremblent.',
      es: 'Mi primito viene el fin de semana. Las paredes tiemblan.',
    },
  },
  {
    emoji: '❓',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BAKICILIK GÜNLÜĞÜ',
        en: 'BABYSITTING LOG',
        de: 'BABYSITTER-TAGEBUCH',
        ar: 'يوميات مجالسة الأطفال',
        fr: 'JOURNAL DE BABY-SITTING',
        es: 'CUIDANDO AL PRIMITO',
      },
      big: { tr: '47', en: '47', de: '47', ar: '47', fr: '47', es: '47' },
      text: {
        tr: 'kez “neden?” diye sordu küçük kuzenin; daha öğlen olmadı',
        en: "times your little cousin asked “but why?” It's not even noon.",
        de: 'Mal „aber warum?“ von deinem kleinen Cousin – noch vor Mittag',
        ar: 'مرة سألك ابن عمك الصغير «لماذا؟»… ولم يحن الظهر بعد',
        fr: 'fois « pourquoi ? » de ton petit cousin. Même pas midi.',
        es: 'veces tu primito preguntó “¿por qué?”. Y aún no es mediodía.',
      },
    },
    caption: {
      tr: 'Cevapların bitti, soruları bitmedi',
      en: "You're out of answers. He's not out of questions.",
      de: 'Dir gehen die Antworten aus, ihm nie die Fragen.',
      ar: 'نفدت إجاباتك، ولم تنفد أسئلته',
      fr: "Tu n'as plus de réponses. Lui a encore des questions.",
      es: 'Tú ya no tienes respuestas. Él sigue con preguntas.',
    },
  },
  {
    emoji: '🥁',
    user: ACCOUNTS.family,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '20', en: '20', de: '20', ar: '20', fr: '20', es: '20' },
      text: {
        tr: 'dakika sürdü dayının fıkrası; sonunu unuttu',
        en: "minutes of your uncle's joke. He forgot the punchline.",
        de: 'Minuten dauerte der Witz deines Onkels. Pointe vergessen.',
        ar: 'دقيقة استغرقتها نكتة خالك… ثم نسي نهايتها',
        fr: "minutes de blague de ton oncle. Il a oublié la chute.",
        es: 'minutos duró el chiste de tu tío. Olvidó el final.',
      },
    },
    caption: {
      tr: 'Yine de gecenin en komik fıkrasıydı',
      en: 'Still the funniest joke of the night',
      de: 'Trotzdem der beste Witz des Abends',
      ar: 'ومع ذلك كانت أطرف نكتة في السهرة',
      fr: 'Quand même la meilleure blague de la soirée',
      es: 'Igual fue el mejor chiste de la noche',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'AİLE GRUBU RAPORU',
        en: 'FAMILY GROUP REPORT',
        de: 'FAMILIENCHAT-BERICHT',
        ar: 'تقرير مجموعة العائلة',
        fr: 'BILAN DU GROUPE FAMILLE',
        es: 'CHAT FAMILIAR: INFORME',
      },
      big: { tr: '174', en: '174', de: '174', ar: '174', fr: '174', es: '174' },
      text: {
        tr: 'mesaj aile grubunda; konu: pazar kahvaltısı saat kaçta',
        en: 'messages in the family group. Topic: Sunday breakfast time.',
        de: 'Nachrichten im Familienchat. Thema: Wann ist Sonntagsfrühstück?',
        ar: 'رسالة في مجموعة العائلة، والموضوع: موعد فطور يوم العطلة',
        fr: "messages au groupe famille pour fixer l'heure du brunch",
        es: 'mensajes en el grupo familiar para decidir la hora del desayuno',
      },
    },
    caption: {
      tr: 'Karar: her zamanki saat',
      en: 'Verdict: the usual time',
      de: 'Ergebnis: wie immer',
      ar: 'القرار: الموعد المعتاد',
      fr: "Verdict : l'heure habituelle",
      es: 'Decisión: la hora de siempre',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'BABAANNE EVİ TIER LIST',
        en: "GRANDMA'S HOUSE TIER LIST",
        de: 'OMAS HAUS: TIER-LIST',
        ar: 'تصنيف بيت الجدة',
        fr: 'TIER LIST CHEZ MAMIE',
        es: 'TIER LIST: CASA DE LA ABUELA',
      },
      rows: [['🍪', '🥧'], ['🫖', '🧶'], ['📺', '🕰️'], ['📶']],
    },
    caption: {
      tr: 'Wi-Fi yok ama kurabiye sınırsız. Adil.',
      en: 'No Wi-Fi, unlimited cookies. Fair trade.',
      de: 'Kein WLAN, dafür endlos Kekse. Fair.',
      ar: 'لا إنترنت، لكن البسكويت بلا حدود. صفقة عادلة.',
      fr: 'Pas de Wi-Fi, mais biscuits à volonté. Ça se vaut.',
      es: 'Sin wifi, pero galletas infinitas. Trato justo.',
    },
  },
  {
    emoji: '👪',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'AİLE GRUBU TIER LIST',
        en: 'FAMILY GROUP CHAT TIER LIST',
        de: 'FAMILIENCHAT-RANKING',
        ar: 'تصنيف رسائل مجموعة العائلة',
        fr: 'TIER LIST DU GROUPE FAMILLE',
        es: 'TIER LIST DEL GRUPO FAMILIAR',
      },
      rows: [['👶', '🎉'], ['🐈', '🍲'], ['🌅', '🌹'], ['🔗']],
    },
    caption: {
      tr: 'Zincir mesajlar C. İtirazı olan 10 kişiye iletsin.',
      en: 'Chain messages: C. Disagree? Forward to 10 people.',
      de: 'Kettenbriefe: C. Wer widerspricht, leitet an 10 weiter.',
      ar: 'الرسائل المتسلسلة في القاع… ومن يعترض فليرسلها إلى 10',
      fr: "Les chaînes : C. Pas d'accord ? Transfère à 10 personnes.",
      es: 'Cadenas: nivel C. ¿Objeciones? Reenvía a 10 personas.',
    },
  },
  {
    emoji: '🔠',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '👨',
        app: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
        text: {
          tr: 'YARIN 8’DE YOLA ÇIKIYORUZ. HAZIR OL.',
          en: 'WE LEAVE AT 8 TOMORROW. BE READY.',
          de: 'MORGEN UM 8 GEHT ES LOS. SEI BEREIT.',
          ar: 'سنخرج غدًا الساعة 8!!!! كن جاهزًا!!!!',
          fr: 'ON PART DEMAIN À 8 HEURES. SOIS PRÊT.',
          es: 'SALIMOS MAÑANA A LAS 8. PREPÁRATE.',
        },
      },
    },
    caption: {
      tr: 'Kızgın değilmiş. Büyük harf açık kalmış.',
      en: "He's not mad. Caps lock is just on.",
      de: 'Er ist nicht sauer. Die Feststelltaste klemmt.',
      ar: 'ليس غاضبًا… إنه يحب علامات التعجب فقط',
      fr: "Il n'est pas fâché. Juste les majuscules.",
      es: 'No está enojado. Solo dejó las mayúsculas.',
    },
  },
  {
    emoji: '👶',
    user: ACCOUNTS.family,
    body: {
      format: 'notifications',
      first: {
        icon: '🏷️',
        app: {
          tr: 'Etiketler',
          en: 'Tags',
          de: 'Markierungen',
          ar: 'الإشارات',
          fr: 'Identifications',
          es: 'Etiquetas',
        },
        text: {
          tr: 'Annen seni etiketledi: “bebekken 🥰”',
          en: 'Mom tagged you: “baby you 🥰”',
          de: 'Mama hat dich markiert: „als Baby 🥰“',
          ar: 'أشارت إليك أمك: «وأنت رضيع 🥰»',
          fr: "Maman t'a identifié : « bébé 🥰 »",
          es: 'Mamá te etiquetó: “de bebé 🥰”',
        },
      },
    },
    caption: {
      tr: 'Arkadaşlarım gördü. Hepsi.',
      en: 'All my friends saw it. All of them.',
      de: 'Alle meine Freunde haben es gesehen. Alle.',
      ar: 'رآها أصدقائي… جميعهم',
      fr: "Tous mes amis l'ont vue. Tous.",
      es: 'La vieron mis amigos. Todos.',
    },
  },
  {
    emoji: '🛁',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '👵',
        app: { tr: 'Babaannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela' },
        text: {
          tr: '7 cevapsız arama',
          en: '7 missed calls',
          de: '7 verpasste Anrufe',
          ar: '7 مكالمات فائتة',
          fr: '7 appels manqués',
          es: '7 llamadas perdidas',
        },
      },
    },
    caption: {
      tr: 'Sadece 3 dakika banyodaydım',
      en: 'I was in the shower for 3 minutes',
      de: 'Ich war nur 3 Minuten duschen',
      ar: 'كنت أستحمّ 3 دقائق فقط',
      fr: "J'étais sous la douche 3 minutes",
      es: 'Estuve 3 minutos en la ducha',
    },
  },
  {
    emoji: '⏰',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat kısa. Annemin beş dakikası değil.',
        en: "Life is short. Mom's five minutes are not.",
        de: 'Das Leben ist kurz. Mamas fünf Minuten nicht.',
        ar: 'الحياة قصيرة… أما دقائق أمي الخمس فلا.',
        fr: 'La vie est courte. Les cinq minutes de maman, non.',
        es: 'La vida es corta. Los cinco minutos de mamá, no.',
      },
    },
    caption: {
      tr: 'Ayakkabılarımı giydim. 1 saat önce.',
      en: 'Shoes on. That was an hour ago.',
      de: 'Schuhe an. Seit einer Stunde.',
      ar: 'لبست حذائي… قبل ساعة',
      fr: 'Chaussures aux pieds. Depuis une heure.',
      es: 'Zapatos puestos. Hace una hora.',
    },
  },
  {
    emoji: '💡',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Büyümek, ışığı açık bırakana söylendiğin gündür.',
        en: 'Growing up is the day you nag someone about leaving the lights on.',
        de: 'Erwachsen bist du, wenn du wegen brennendem Licht meckerst.',
        ar: 'أن تكبر يعني أن توبّخ من ترك الضوء مضاءً.',
        fr: "Grandir, c'est râler contre ceux qui laissent la lumière allumée.",
        es: 'Madurar es regañar a alguien por dejar la luz encendida.',
      },
    },
    caption: {
      tr: 'Babam gurur duyuyor',
      en: 'Dad is so proud',
      de: 'Papa ist so stolz',
      ar: 'أبي فخور جدًا',
      fr: 'Papa est si fier',
      es: 'Papá está orgulloso',
    },
  },
  {
    emoji: '🦸',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bazıları kahraman doğar. Bazıları da kuzenlerin en büyüğü.',
        en: 'Some are born heroes. Others are born the oldest cousin.',
        de: 'Manche werden als Helden geboren. Andere als ältester Cousin.',
        ar: 'بعض الناس يولدون أبطالًا… وبعضهم يولد أكبر أبناء العم.',
        fr: "Certains naissent héros. D'autres naissent l'aîné des cousins.",
        es: 'Algunos nacen héroes. Otros nacen siendo el primo mayor.',
      },
    },
    caption: {
      tr: 'Küçükleri yine bana bıraktılar',
      en: 'They left the little ones with me again',
      de: 'Die Kleinen sind wieder bei mir gelandet',
      ar: 'تركوا الصغار عندي مجددًا',
      fr: "On m'a encore confié les petits",
      es: 'Otra vez me dejaron a los pequeños',
    },
  },
  {
    emoji: '🧸',
    user: ACCOUNTS.family,
    body: {
      format: 'quote',
      text: {
        tr: 'Kardeşler aynı çocukluğu yaşar. Ama asla aynı şekilde anlatmaz.',
        en: 'Siblings share one childhood. They never tell it the same way.',
        de: 'Geschwister teilen eine Kindheit. Erzählen sie aber nie gleich.',
        ar: 'الإخوة يعيشون طفولة واحدة… ولا يروونها بالطريقة نفسها أبدًا.',
        fr: 'Frères et sœurs vivent la même enfance. Jamais la même version.',
        es: 'Los hermanos comparten infancia. Nunca la cuentan igual.',
      },
    },
    caption: {
      tr: 'Lambayı kimin kırdığı hâlâ tartışmalı',
      en: 'Who broke the lamp is still up for debate',
      de: 'Wer die Lampe kaputt gemacht hat, ist bis heute offen',
      ar: 'من كسر المصباح؟ ما زال الأمر محل خلاف',
      fr: "Qui a cassé la lampe ? Le débat reste ouvert.",
      es: '¿Quién rompió la lámpara? Sigue en debate.',
    },
  },
];

export const FAMILY_LIKE: readonly Draft[] = [
  {
    emoji: '🍼',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'yeğenimin ilk kelimesi benim adım!! ağlıyorum',
      en: "my niece's first word was my name!! crying",
      de: 'das erste wort meiner nichte: mein name!! ich heule',
      ar: 'أول كلمة نطقتها ابنة أختي كانت اسمي!! أبكي',
      fr: 'le premier mot de ma nièce, mon prénom !! je pleure',
      es: '¡¡la primera palabra de mi sobrina fue mi nombre!! lloro',
    },
  },
  {
    emoji: '🎊',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'babam 35 yıl sonra emekli!! bugün yine 6’da kalktı',
      en: 'dad retired after 35 years!! still up at 6 today',
      de: 'papa ist nach 35 jahren in rente!! heute trotzdem um 6 wach',
      ar: 'تقاعد أبي بعد 35 سنة!! واستيقظ اليوم الساعة 6 كعادته',
      fr: 'papa à la retraite après 35 ans de boulot !! debout à 6 h',
      es: '¡¡papá se jubiló tras 35 años!! igual se levantó a las 6',
    },
  },
  {
    emoji: '🫖',
    user: ACCOUNTS.irem,
    body: { format: 'scene' },
    caption: {
      tr: 'kuzenime bakıcılık yaptım, 14 bardak hayali çay içtim',
      en: 'babysat my little cousin, drank 14 cups of pretend tea',
      de: 'babysitten bei meiner cousine: 14 tassen fantasie-tee',
      ar: 'جالست ابنة خالتي الصغيرة… وشربت 14 كوب شاي وهمي',
      fr: 'baby-sitting de ma cousine : 14 tasses de thé imaginaire',
      es: 'cuidé a mi primita: me tomé 14 tazas de té imaginario',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.baris,
    body: { format: 'scene' },
    caption: {
      tr: 'dedemle diktiğimiz fidan bugün benden uzun',
      en: 'the tree grandpa and i planted is taller than me now',
      de: 'der baum von opa und mir ist jetzt größer als ich',
      ar: 'الشجرة التي زرعتها مع جدي صارت أطول مني',
      fr: "l'arbre planté avec papi est plus grand que moi",
      es: 'el árbol que plantamos con el abuelo ya es más alto que yo',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ailemiz (kardeşim çizdi)',
        en: 'our family, by my sister',
        de: 'schwester hat uns gemalt',
        ar: 'عائلتنا (رسمتها أختي)',
        fr: 'notre famille, par ma sœur',
        es: 'la familia, por mi hermana',
      },
    },
    caption: {
      tr: 'köpeği benden büyük çizmiş, not aldım',
      en: 'she drew the dog bigger than me. noted.',
      de: 'den hund hat sie größer gemalt als mich. notiert.',
      ar: 'رسمت الكلب أكبر مني… سجّلت ذلك',
      fr: 'elle a dessiné le chien plus grand que moi. noté.',
      es: 'dibujó al perro más grande que a mí. anotado.',
    },
  },
  {
    emoji: '👵',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: { tr: '50. yıl', en: '50 years', de: '50 jahre', ar: '50 عامًا', fr: '50 ans', es: '50 años' },
    },
    caption: {
      tr: 'dedemle babaannem, hâlâ el ele',
      en: 'grandma and grandpa, still holding hands',
      de: 'oma und opa, immer noch hand in hand',
      ar: 'جدي وجدتي… يدًا بيد حتى اليوم',
      fr: 'papi et mamie, toujours main dans la main',
      es: 'mis abuelos, todavía de la mano',
    },
  },
  {
    emoji: '📷',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'annem çekti',
        en: 'mom took this',
        de: 'foto: mama',
        ar: 'صوّرتها أمي',
        fr: 'photo de maman',
        es: 'foto de mamá',
      },
    },
    caption: {
      tr: 'yarısı parmak ama en sevdiğim bu',
      en: 'half of it is her finger. still my favorite',
      de: 'halb finger, trotzdem mein lieblingsfoto',
      ar: 'نصفها إصبع… لكنها صورتي المفضلة',
      fr: "moitié doigt, mais c'est ma préférée",
      es: 'la mitad es su dedo, pero es mi favorita',
    },
  },
  {
    emoji: '☕',
    user: ACCOUNTS.ali,
    body: {
      format: 'polaroid',
      note: {
        tr: 'babamın kahvesi',
        en: "dad's coffee",
        de: 'papas kaffee',
        ar: 'قهوة أبي',
        fr: 'le café de papa',
        es: 'el café de papá',
      },
    },
    caption: {
      tr: 'babama kahve yaptım. “olmuş” dedi. rekor övgü',
      en: 'made dad coffee. he said “not bad.” record praise',
      de: 'papa kaffee gemacht. er sagte „passt“. rekordlob',
      ar: 'صنعت لأبي قهوة، فقال: «لا بأس». أعلى مديح',
      fr: "café pour papa. il a dit « pas mal ». record d'éloges",
      es: 'le hice café a papá. dijo “no está mal”. récord de elogios',
    },
  },
  {
    emoji: '🏡',
    user: ACCOUNTS.kaan,
    body: { format: 'dump', emojis: ['🏡', '🍉', '⚽️', '🎲', '🤳'] },
    caption: {
      tr: 'kuzenler buluşması: 11 kişi, tek banyo, sıfır uyku',
      en: 'cousins weekend: 11 of us, one bathroom, zero sleep',
      de: 'cousin-treffen: 11 leute, ein bad, null schlaf',
      ar: 'لقاء أبناء العم: 11 شخصًا، حمّام واحد، ولا نوم',
      fr: 'week-end cousins : 11 personnes, 1 salle de bain, 0 dodo',
      es: 'fin de semana de primos: 11, un baño, cero sueño',
    },
  },
  {
    emoji: '🍅',
    user: ACCOUNTS.melis,
    body: { format: 'dump', emojis: ['🍅', '🥒', '🌻', '🐓', '🧺'] },
    caption: {
      tr: 'dayımın köyünde hafta sonu: 40 domates, 1 inatçı horoz',
      en: "weekend at my uncle's farm: 40 tomatoes, 1 stubborn rooster",
      de: 'beim onkel auf dem land: 40 tomaten, 1 sturer hahn',
      ar: 'عطلة في مزرعة خالي: 40 حبة طماطم وديك عنيد',
      fr: 'chez mon oncle à la campagne : 40 tomates, 1 coq têtu',
      es: 'en el campo con mi tío: 40 tomates, 1 gallo terco',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.tolga,
    body: { format: 'dump', emojis: ['🖼️', '👪', '👕', '😂', '📷'] },
    caption: {
      tr: 'eski aile fotoğrafını canlandırdık, babamın gömleği aynı',
      en: 'recreated an old family photo. dad kept the same shirt',
      de: 'familienfoto nachgestellt: papa hat noch dasselbe hemd',
      ar: 'أعدنا صورة عائلية قديمة… وقميص أبي هو نفسه',
      fr: 'photo de famille refaite. papa a gardé la même chemise',
      es: 'foto familiar recreada: papá aún tiene la misma camisa',
    },
  },
  {
    emoji: '🎂',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['🎂', '👴', '🎈', '💐', '📸'] },
    caption: {
      tr: 'dedemin 80. yaş günü: 4 kuşak aynı karede',
      en: "grandpa's 80th: 4 generations in one photo",
      de: 'opas 80.: 4 generationen auf einem foto',
      ar: 'عيد ميلاد جدي الثمانين: 4 أجيال في صورة واحدة',
      fr: 'les 80 ans de papi : 4 générations sur une photo',
      es: 'los 80 del abuelo: 4 generaciones en una foto',
    },
  },
];

export const FAMILY_HOLD: readonly Draft[] = [
  {
    emoji: '💵',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Babaanne harçlığı. “Annene söyleme.”',
      en: "Grandma's secret cash. “Don't tell your mom.”",
      de: "Omas Geheimgeld. „Sag's nicht deiner Mama.“",
      ar: 'مصروف سري من جدتك… «لا تخبر أمك»',
      fr: "L'argent de poche de mamie. « Le dis pas à ta mère. »",
      es: 'El dinerito de la abuela. “No le digas a tu mamá.”',
    },
  },
  {
    emoji: '🍬',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir eşya: dedenin cebindeki son şeker',
      en: "Rare item: the last candy in Grandpa's pocket",
      de: 'Seltenes Item: das letzte Bonbon aus Opas Tasche',
      ar: 'غرض نادر: آخر حلوى في جيب جدك',
      fr: 'Objet rare : le dernier bonbon de la poche de papi',
      es: 'Objeto raro: el último caramelo del bolsillo del abuelo',
    },
  },
  {
    emoji: '📜',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Babaannenin gizli tarifi. Sadece sana verdi.',
      en: "Grandma's secret recipe. She gave it only to you.",
      de: 'Omas Geheimrezept. Nur du hast es bekommen.',
      ar: 'وصفة جدتك السرية… أعطتها لك وحدك',
      fr: 'La recette secrète de mamie. Rien que pour toi.',
      es: 'La receta secreta de la abuela. Solo para ti.',
    },
  },
  {
    emoji: '💺',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ön koltuk senin! Kardeşin “ön benim” demeyi unuttu.',
      en: "Front seat's yours! Your sister forgot to call shotgun.",
      de: "Beifahrersitz gehört dir! Deine Schwester hat's verpennt.",
      ar: 'المقعد الأمامي لك! نسيت أختك أن تحجزه',
      fr: 'Place avant pour toi ! Ta sœur a oublié de la réclamer.',
      es: '¡El asiento de adelante es tuyo! Tu hermana se olvidó.',
    },
  },
  {
    emoji: '✅',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Baban “tamam, git” dedi. Fikri değişmeden bırak!',
      en: "Dad said “okay, go.” Let go before he changes his mind!",
      de: "Papa sagt ja. Loslassen, bevor er's sich anders überlegt!",
      ar: 'قال أبوك «حسنًا، اذهب»… اترك قبل أن يغيّر رأيه!',
      fr: "Papa a dit oui. Lâche avant qu'il change d'avis !",
      es: 'Papá dijo “sí, ve”. ¡Suelta antes de que cambie de idea!',
    },
  },
  {
    emoji: '🍱',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Annenin verdiği 6 kap yemek. Bir hafta yeter.',
      en: "6 containers of Mom's cooking. Good for a whole week.",
      de: '6 Dosen von Mamas Essen. Reicht für eine Woche.',
      ar: '6 علب من طبخ أمك… تكفي أسبوعًا كاملًا',
      fr: '6 boîtes de petits plats de maman. Une semaine de festin.',
      es: '6 recipientes con comida de mamá. Para toda la semana.',
    },
  },
  {
    emoji: '🎮',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kardeşin oyun kolunu sana verdi. Kendi isteğiyle.',
      en: 'Your brother handed you the controller. Voluntarily.',
      de: 'Dein Bruder gibt dir freiwillig den Controller.',
      ar: 'أعطاك أخوك يد التحكم… بإرادته!',
      fr: 'Ton frère te passe la manette. De lui-même.',
      es: 'Tu hermano te pasó el control. Por voluntad propia.',
    },
  },
];

export const FAMILY_FREEZE: readonly Draft[] = [
  {
    emoji: '🧰',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'YASAK BÖLGE',
        en: 'OFF LIMITS',
        de: 'SPERRZONE',
        ar: 'منطقة محظورة',
        fr: 'ZONE INTERDITE',
        es: 'ZONA PROHIBIDA',
      },
      small: {
        tr: 'BABAMIN ALETLERİ',
        en: "DAD'S TOOLS",
        de: 'PAPAS WERKZEUG',
        ar: 'أدوات أبي',
        fr: 'LES OUTILS DE PAPA',
        es: 'HERRAMIENTAS DE PAPÁ',
      },
    },
    caption: {
      tr: 'Biri sende. Kıpırdama.',
      en: "One's in your room. Freeze.",
      de: 'Einer liegt bei dir. Keine Bewegung.',
      ar: 'واحد منها عندك. لا تتحرك.',
      fr: 'Il y en a un chez toi. Bouge pas.',
      es: 'Uno lo tienes tú. No te muevas.',
    },
    headline: {
      tr: 'Baban tornavidalarını sayıyor',
      en: "Dad's counting his screwdrivers",
      de: 'Papa zählt seine Schraubenzieher',
      ar: 'أبوك يعدّ مفكّاته',
      fr: 'Papa compte ses tournevis',
      es: 'Papá está contando sus destornilladores',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'REZERVE',
        en: 'RESERVED',
        de: 'RESERVIERT',
        ar: 'محجوز',
        fr: 'RÉSERVÉ',
        es: 'RESERVADO',
      },
      small: {
        tr: 'BABAMIN KOLTUĞU',
        en: "DAD'S CHAIR",
        de: 'PAPAS SESSEL',
        ar: 'كرسي أبي',
        fr: 'LE FAUTEUIL DE PAPA',
        es: 'EL SILLÓN DE PAPÁ',
      },
    },
    caption: {
      tr: 'Belki fark etmez. Kıpırdama.',
      en: "Maybe he won't notice. Don't move.",
      de: "Vielleicht merkt er's nicht. Nicht bewegen.",
      ar: 'ربما لا يلاحظ. لا تتحرك.',
      fr: 'Il le verra peut-être pas. Bouge pas.',
      es: 'Quizás no se dé cuenta. No te muevas.',
    },
    headline: {
      tr: 'Baban geldi, sen onun koltuğundasın',
      en: "Dad's home and you're in his chair",
      de: 'Papa ist da. Du sitzt in seinem Sessel.',
      ar: 'وصل أبوك وأنت على كرسيه',
      fr: "Papa rentre et t'es dans son fauteuil",
      es: 'Llegó papá y estás en su sillón',
    },
  },
  {
    emoji: '🪡',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'EL SÜRMEYİN',
        en: 'HANDS OFF',
        de: 'NICHT ANFASSEN',
        ar: 'لا تلمس',
        fr: 'NE TOUCHEZ PAS',
        es: 'NO TOCAR',
      },
      small: {
        tr: 'BABAANNEMİN DANTELLERİ',
        en: "GRANDMA'S DOILIES",
        de: 'OMAS HÄKELDECKCHEN',
        ar: 'مفارش جدتي',
        fr: 'LES NAPPERONS DE MAMIE',
        es: 'LOS TAPETES DE LA ABUELA',
      },
    },
    caption: {
      tr: 'Sen yapmadın. Kıpırdama.',
      en: "You didn't do it. Don't move.",
      de: 'Du warst es nicht. Keine Bewegung.',
      ar: 'لست أنت الفاعل. لا تتحرك.',
      fr: "C'est pas toi. Bouge pas.",
      es: 'No fuiste tú. No te muevas.',
    },
    headline: {
      tr: 'Dantel yamuk, babaannen geliyor',
      en: "The doily's crooked. Grandma's coming.",
      de: 'Deckchen schief. Oma kommt.',
      ar: 'المفرش مائل… وجدتك قادمة',
      fr: 'Napperon de travers. Mamie arrive.',
      es: 'Tapete torcido. Viene la abuela.',
    },
  },
  {
    emoji: '🤏',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'ANTRE',
        en: 'ENTRYWAY',
        de: 'FLUR',
        ar: 'المدخل',
        fr: 'ENTRÉE',
        es: 'RECIBIDOR',
      },
    },
    caption: {
      tr: 'Kıpırdamazsan seni göremez.',
      en: "She can't see you if you don't move.",
      de: 'Wenn du still hältst, sieht sie dich nicht.',
      ar: 'إن لم تتحرك فلن تراك.',
      fr: 'Si tu bouges pas, elle te voit pas.',
      es: 'Si no te mueves, no te ve.',
    },
    headline: {
      tr: 'Teyzen yanağını sıkmaya geliyor',
      en: "Your aunt's coming to pinch your cheeks",
      de: 'Tante will dir in die Wange kneifen',
      ar: 'خالتك قادمة لتقرص خدّك',
      fr: 'Tata arrive pour te pincer la joue',
      es: 'Tu tía viene a pellizcarte las mejillas',
    },
  },
  {
    emoji: '🤨',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'BABAANNEMİN SALONU',
        en: "GRANDMA'S HOUSE",
        de: 'BEI OMA',
        ar: 'صالون جدتي',
        fr: 'CHEZ MAMIE',
        es: 'CASA DE LA ABUELA',
      },
    },
    caption: {
      tr: 'Dik otur. Gülümse. Kıpırdama.',
      en: "Sit up straight. Smile. Don't move.",
      de: 'Gerade sitzen. Lächeln. Nicht bewegen.',
      ar: 'اجلس معتدلًا. ابتسم. لا تتحرك.',
      fr: 'Tiens-toi droit. Souris. Bouge pas.',
      es: 'Siéntate derecho. Sonríe. No te muevas.',
    },
    headline: {
      tr: 'Annen o bakışı attı',
      en: 'Mom just gave you the look',
      de: 'Mama wirft dir diesen Blick zu',
      ar: 'أمك رمقتك بتلك النظرة',
      fr: "Maman t'a lancé son regard noir",
      es: 'Mamá te echó esa mirada',
    },
  },
  {
    emoji: '🍰',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK',
        en: 'KITCHEN',
        de: 'KÜCHE',
        ar: 'المطبخ',
        fr: 'CUISINE',
        es: 'COCINA',
      },
    },
    caption: {
      tr: 'Dudağında krema var. Kıpırdama.',
      en: "There's frosting on your lip. Don't move.",
      de: 'Du hast Sahne an der Lippe. Nicht bewegen.',
      ar: 'على شفتك كريمة. لا تتحرك.',
      fr: "T'as de la crème sur la lèvre. Bouge pas.",
      es: 'Tienes crema en el labio. No te muevas.',
    },
    headline: {
      tr: 'Annen pastayı kimin yediğini soruyor',
      en: "Mom's asking who ate the cake",
      de: 'Mama fragt, wer den Kuchen gegessen hat',
      ar: 'أمك تسأل: من أكل الكعكة؟',
      fr: 'Maman demande qui a mangé le gâteau',
      es: 'Mamá pregunta quién se comió el pastel',
    },
  },
  {
    emoji: '👣',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'OTURMA ODASI',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة الجلوس',
        fr: 'SALON',
        es: 'SALA DE ESTAR',
      },
    },
    caption: {
      tr: 'Nefesini tut. Kıpırdama.',
      en: "Hold your breath. Don't move.",
      de: 'Luft anhalten. Nicht bewegen.',
      ar: 'احبس أنفاسك. لا تتحرك.',
      fr: 'Retiens ton souffle. Bouge pas.',
      es: 'Aguanta la respiración. No te muevas.',
    },
    headline: {
      tr: 'Minik kuzenin yürümek üzere',
      en: "Your baby cousin's about to walk",
      de: 'Dein kleiner Cousin läuft gleich los',
      ar: 'ابن عمك الصغير على وشك أن يمشي',
      fr: 'Ton petit cousin va se mettre à marcher',
      es: 'Tu primito está a punto de caminar',
    },
  },
];
