import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';
import { HANDS_OFF } from '../classic';

/**
 * Food, groceries and shopping: cooking, snacks, diets, restaurants, the market, carts and deals.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const FOOD_SKIP: readonly Draft[] = [
  {
    emoji: '🥖',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Ana yemek geldi. Ben ekmekle doydum.',
      en: "Main course is here. I'm full from the bread.",
      de: 'Hauptgang kommt. Ich bin schon satt vom Brot.',
      ar: 'وصل الطبق الرئيسي… وأنا شبعت من الخبز',
      fr: "Le plat arrive. J'ai déjà calé sur le pain.",
      es: 'Llegó el plato principal. Ya me llené de pan.',
    },
  },
  {
    emoji: '🧅',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Soğan beni dizi finalinden çok ağlattı',
      en: 'This onion hit harder than any season finale',
      de: 'Zwiebel geschnitten. Trauriger als jedes Finale.',
      ar: 'بصلة واحدة أبكتني أكثر من أي حلقة أخيرة',
      fr: "Cet oignon m'a plus fait pleurer qu'un final de saison",
      es: 'Esta cebolla me hizo llorar más que un final de serie',
    },
  },
  {
    emoji: '🍌',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Muzlar karardı. Kaderleri artık kek.',
      en: 'Bananas went brown. Banana bread it is.',
      de: 'Bananen braun. Ihr Schicksal: Bananenbrot.',
      ar: 'اسودّ الموز… ومصيره الآن كعكة',
      fr: 'Bananes noires. Leur destin : finir en gâteau.',
      es: 'Plátanos negros. Su destino: pan de plátano.',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.shopping,
    body: { format: 'scene' },
    caption: {
      tr: 'Kabinde 9 parça. Kazanan: kendi tişörtüm.',
      en: 'Fitting room: 9 tries. Winner: my own T-shirt.',
      de: 'Umkleide: 9 Teile. Sieger: mein eigenes Shirt.',
      ar: 'جرّبت 9 قطع في غرفة القياس… والفائز: قميصي',
      fr: "Cabine d'essayage : 9 tenues. Gagnant : mon t-shirt.",
      es: 'Probador: 9 prendas. Ganó mi propia camiseta.',
    },
  },
  {
    emoji: '🥚',
    user: ACCOUNTS.kitchen,
    body: { format: 'scene' },
    caption: {
      tr: 'Yumurta kırdım. Kabuk avı: 10. dakika.',
      en: 'Cracked one egg. Shell hunt: minute 10.',
      de: 'Ein Ei aufgeschlagen. Schalenjagd: Minute 10.',
      ar: 'كسرت بيضة… ومطاردة القشرة مستمرة منذ 10 دقائق',
      fr: 'Un œuf cassé. Chasse à la coquille : 10e minute.',
      es: 'Rompí un huevo. Cazando cáscaras: minuto 10.',
    },
  },
  {
    emoji: '🏷️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Fiyatına baktım. Usulca rafa geri koydum.',
      en: 'Saw the price tag. Gently put it back.',
      de: 'Preis gesehen. Ganz leise zurück ins Regal.',
      ar: 'رأيت السعر… فأعدته إلى الرف بهدوء',
      fr: 'Vu le prix. Reposé tout doucement en rayon.',
      es: 'Vi el precio. Lo devolví al estante despacito.',
    },
  },
  {
    emoji: '🌶️',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: '“Az acılı” dedim. Şefin azı başkaymış.',
      en: "Ordered it mild. The chef's mild is lava.",
      de: 'Ich sagte „mild“. Die Küche hörte „Lava“.',
      ar: 'طلبته «حارًا قليلًا»… وقليل الطاهي بركان',
      fr: "J'ai dit « doux ». Le chef a compris « lave ».",
      es: 'Pedí “poco picante”. El chef entendió “lava”.',
    },
  },
  {
    emoji: '🥣',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Anneannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'anneanne, kek için ne kadar un?',
            en: 'grandma, how much flour for the cake?',
            de: 'Oma, wie viel Mehl für den Kuchen?',
            ar: 'جدتي، كم من الطحين للكعكة؟',
            fr: 'mamie, combien de farine pour le gâteau ?',
            es: 'abuela, ¿cuánta harina lleva el pastel?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'alabildiği kadar',
            en: 'as much as it takes',
            de: 'so viel, wie er braucht',
            ar: 'بقدر ما يحتاج',
            fr: "ce qu'il faut",
            es: 'la que pida la masa',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yani kaç bardak?',
            en: 'so… how many cups?',
            de: 'also wie viele Tassen?',
            ar: 'يعني كم كوبًا؟',
            fr: 'donc… combien de verres ?',
            es: '¿o sea, cuántas tazas?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'kıvamını görünce anlarsın',
            en: "you'll know it when you see it",
            de: 'das siehst du dann schon',
            ar: 'ستعرف حين ترى القوام',
            fr: 'tu verras bien à la texture',
            es: 'lo sabrás cuando lo veas',
          },
        },
      ],
    },
    caption: {
      tr: 'Ölçü birimi: göz kararı',
      en: 'Unit of measure: vibes',
      de: 'Maßeinheit: Gefühl',
      ar: 'وحدة القياس: الإحساس',
      fr: "Unité de mesure : à l'œil",
      es: 'Unidad de medida: a ojo',
    },
  },
  {
    emoji: '🥖',
    user: ACCOUNTS.food,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'ekmek aldın mı?',
            en: 'did you get bread?',
            de: 'hast du Brot geholt?',
            ar: 'هل اشتريت الخبز؟',
            fr: "t'as pris du pain ?",
            es: '¿compraste pan?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'aldım, sıcacık 😋',
            en: 'yep, still warm 😋',
            de: 'ja, noch ganz warm 😋',
            ar: 'نعم، وما زال ساخنًا 😋',
            fr: 'oui, encore tout chaud 😋',
            es: 'sí, calentito 😋',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'iki ucu nerede?',
            en: 'where are the ends?',
            de: 'wo sind die Enden?',
            ar: 'وأين طرفاه؟',
            fr: 'ils sont où, les bouts ?',
            es: '¿y las puntas?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'fırın artık uçsuz satıyor',
            en: 'they sell it without ends now',
            de: "das gibt's jetzt ohne Enden",
            ar: 'المخبز صار يبيعه بلا أطراف',
            fr: 'ils le vendent sans bouts maintenant',
            es: 'ahora lo venden sin puntas',
          },
        },
      ],
    },
    caption: {
      tr: 'Sıcak ekmek eve hiç sağlam gelmez',
      en: 'Warm bread never makes it home whole',
      de: 'Warmes Brot kommt nie heil zu Hause an',
      ar: 'الخبز الساخن لا يصل إلى البيت كاملًا أبدًا',
      fr: "Une baguette chaude n'arrive jamais entière",
      es: 'El pan caliente nunca llega entero a casa',
    },
  },
  {
    emoji: '🏷️',
    user: ACCOUNTS.shopping,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'fotoğraftaki ceket yeni mi?',
            en: 'is that jacket in the photo new?',
            de: 'ist die Jacke auf dem Foto neu?',
            ar: 'هل السترة التي في الصورة جديدة؟',
            fr: 'la veste sur la photo, elle est neuve ?',
            es: '¿la chaqueta de la foto es nueva?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yok ya, çoktandır var',
            en: "nah, I've had it forever",
            de: 'nee, die hab ich schon ewig',
            ar: 'لا، عندي منذ زمن',
            fr: "non, je l'ai depuis des siècles",
            es: 'no, la tengo desde hace siglos',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'etiketi sallanıyor ama',
            en: "the tag's still hanging off it",
            de: 'da hängt noch das Etikett dran',
            ar: 'لكن البطاقة ما زالت معلّقة بها',
            fr: "l'étiquette pend encore",
            es: 'todavía le cuelga la etiqueta',
          },
        },
      ],
    },
    caption: {
      tr: 'Etiket her şeyi itiraf etti',
      en: 'The tag told on me',
      de: 'Das Etikett hat mich verpetzt',
      ar: 'البطاقة فضحتني',
      fr: "L'étiquette a tout balancé",
      es: 'La etiqueta me delató',
    },
  },
  {
    emoji: '🥘',
    user: ACCOUNTS.kitchen,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'mutfaktan bir koku geliyor',
            en: "what's that smell in the kitchen?",
            de: 'was riecht denn da in der Küche?',
            ar: 'ما هذه الرائحة في المطبخ؟',
            fr: 'ça sent quoi dans la cuisine ?',
            es: '¿qué es ese olor en la cocina?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yemek yaptım!',
            en: 'I cooked!',
            de: 'ich hab gekocht!',
            ar: 'طبخت!',
            fr: "j'ai cuisiné !",
            es: '¡cociné!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ne yaptın?',
            en: 'cooked what?',
            de: 'was denn?',
            ar: 'ماذا طبخت؟',
            fr: "c'est quoi ?",
            es: '¿qué cosa?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'başta makarnaydı',
            en: 'it started out as pasta',
            de: 'am Anfang waren es Nudeln',
            ar: 'في البداية كانت معكرونة',
            fr: "au début, c'étaient des pâtes",
            es: 'al principio era pasta',
          },
        },
      ],
    },
    caption: {
      tr: 'Şefin önerisi: sorma, ye',
      en: "Chef's recommendation: don't ask",
      de: 'Empfehlung des Hauses: nicht fragen',
      ar: 'توصية الطاهي: لا تسأل',
      fr: 'Conseil du chef : ne demande pas',
      es: 'Sugerencia del chef: no preguntes',
    },
  },
  {
    emoji: '👍',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Ağzın dolu. Garson: “Her şey yolunda mı?” Sen:',
        en: 'Mouth full. Server: “How is everything?” You:',
        de: 'Mund voll. Kellner: „Schmeckt es?“ Du:',
        ar: 'فمك ممتلئ، والنادل يسأل: «هل كل شيء بخير؟»',
        fr: 'Le serveur demande si ça va. Bouche pleine. Toi :',
        es: 'Boca llena. Te preguntan: “¿Todo bien?” Tú:',
      },
      options: [
        {
          tr: 'Cevap veririm',
          en: 'Answer out loud',
          de: 'Antworten',
          ar: 'أجيب بالكلام',
          fr: 'Je réponds',
          es: 'Respondo',
        },
        {
          tr: 'Başparmak 👍',
          en: 'Thumbs up 👍',
          de: 'Daumen hoch 👍',
          ar: 'أرفع إبهامي 👍',
          fr: 'Pouce levé 👍',
          es: 'Pulgar arriba 👍',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Başparmak her dili konuşur',
      en: 'The thumb speaks every language',
      de: 'Der Daumen spricht jede Sprache',
      ar: 'الإبهام يتكلم كل اللغات',
      fr: 'Le pouce parle toutes les langues',
      es: 'El pulgar habla todos los idiomas',
    },
  },
  {
    emoji: '🛒',
    user: ACCOUNTS.plain,
    body: {
      format: 'poll',
      question: {
        tr: 'Kasada üç sıra var. Hangisi hızlı gider?',
        en: 'Three checkout lines. Which one moves fastest?',
        de: 'Drei Kassen offen. Welche geht am schnellsten?',
        ar: 'ثلاثة طوابير عند الصناديق. أيها أسرع؟',
        fr: 'Trois caisses ouvertes. Laquelle avance vite ?',
        es: 'Tres cajas abiertas. ¿Cuál avanza más rápido?',
      },
      options: [
        {
          tr: 'Benim seçtiğim',
          en: 'The one I pick',
          de: 'Die, die ich nehme',
          ar: 'الطابور الذي أختاره',
          fr: 'Celle que je choisis',
          es: 'La que yo elija',
        },
        {
          tr: 'Diğer ikisi',
          en: 'The other two',
          de: 'Die anderen zwei',
          ar: 'الطابوران الآخران',
          fr: 'Les deux autres',
          es: 'Las otras dos',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Sıra değiştirdim, o da durdu',
      en: 'Switched lines. That one stopped too.',
      de: 'Kasse gewechselt. Die stand dann auch.',
      ar: 'غيّرت الطابور… فتوقف هو أيضًا',
      fr: "J'ai changé de file. Elle s'est arrêtée aussi.",
      es: 'Me cambié de fila. También se detuvo.',
    },
  },
  {
    emoji: '🚚',
    user: ACCOUNTS.shopping,
    body: {
      format: 'poll',
      question: {
        tr: 'Ücretsiz kargoya az kaldı. Ne yaparsın?',
        en: "You're just short of free shipping. You:",
        de: 'Bis zum Gratisversand fehlt nur wenig. Du:',
        ar: 'ينقصك القليل للشحن المجاني. ماذا تفعل؟',
        fr: 'Presque la livraison gratuite. Toi :',
        es: 'Te falta poco para el envío gratis. Tú:',
      },
      options: [
        {
          tr: 'Kargoyu öderim',
          en: 'Pay for shipping',
          de: 'Versand zahlen',
          ar: 'أدفع ثمن الشحن',
          fr: 'Je paie la livraison',
          es: 'Pago el envío',
        },
        {
          tr: 'Bir şey daha eklerim',
          en: 'Add one more thing',
          de: 'Noch was dazupacken',
          ar: 'أضيف شيئًا آخر',
          fr: "J'ajoute un truc",
          es: 'Agrego algo más',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kargo bedava oldu. Sepet üç katı.',
      en: 'Free shipping! Cart tripled.',
      de: 'Versand gespart. Warenkorb verdreifacht.',
      ar: 'وفّرت الشحن… وتضاعفت السلة ثلاث مرات',
      fr: 'Livraison offerte. Panier triplé.',
      es: 'Envío gratis. Carrito triplicado.',
    },
  },
  {
    emoji: '🛵',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'KURYENİN ROTASI',
        en: "MY DRIVER'S ROUTE",
        de: 'ROUTE DES KURIERS',
        ar: 'مسار المندوب',
        fr: 'TRAJET DU LIVREUR',
        es: 'RUTA DEL REPARTIDOR',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Kurye evimin etrafında 3 tur attı',
      en: 'The driver circled my block 3 times',
      de: 'Der Kurier drehte 3 Runden um mein Haus',
      ar: 'دار المندوب حول بيتي 3 مرات',
      fr: 'Le livreur a fait 3 fois le tour de chez moi',
      es: 'El repartidor dio 3 vueltas a mi casa',
    },
  },
  {
    emoji: '🥬',
    user: ACCOUNTS.kitchen,
    body: {
      format: 'chart',
      title: {
        tr: 'ISPANAĞIN TAZELİĞİ',
        en: 'SPINACH FRESHNESS',
        de: 'SPINAT-FRISCHE',
        ar: 'نضارة السبانخ',
        fr: 'FRAÎCHEUR DES ÉPINARDS',
        es: 'FRESCURA DE LA ESPINACA',
      },
      value: null,
      shape: 'fall',
      axis: 'days',
    },
    caption: {
      tr: 'Pazartesi: smoothie planı. Cuma: veda.',
      en: 'Monday: smoothie plans. Friday: goodbye.',
      de: 'Montag: Smoothie-Plan. Freitag: Abschied.',
      ar: 'الاثنين: خطة عصير أخضر. الجمعة: وداعًا.',
      fr: 'Lundi : projet smoothie. Vendredi : adieu.',
      es: 'Lunes: plan de batido. Viernes: adiós.',
    },
  },
  {
    emoji: '🍰',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'TOKLUK SEVİYEM',
        en: 'HOW FULL I AM',
        de: 'MEIN SÄTTIGUNGSGRAD',
        ar: 'مستوى شبعي',
        fr: 'MON NIVEAU DE SATIÉTÉ',
        es: 'MI NIVEL DE LLENURA',
      },
      value: null,
      shape: 'crash',
      axis: 'hours',
    },
    caption: {
      tr: 'Tatlıya her zaman yer vardır',
      en: "There's always room for dessert",
      de: 'Für Nachtisch ist immer Platz',
      ar: 'هناك دائمًا مكان للحلوى',
      fr: 'Il y a toujours de la place pour le dessert',
      es: 'Para el postre siempre hay espacio',
    },
  },
  {
    emoji: '🥨',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'SÜPERMARKET',
        en: 'SUPERMARKET',
        de: 'SUPERMARKT',
        ar: 'سوبرماركت',
        fr: 'SUPERMARCHÉ',
        es: 'SUPERMERCADO',
      },
      items: [
        {
          tr: '11 ÇEŞİT ATIŞTIRMALIK',
          en: 'SNACKS (11 KINDS)',
          de: 'SNACKS (11 SORTEN)',
          ar: 'وجبات خفيفة (11 نوعًا)',
          fr: 'EN-CAS (11 SORTES)',
          es: 'SNACKS (11 TIPOS)',
        },
      ],
    },
    caption: {
      tr: 'Markete aç karnına gitmenin bedeli',
      en: 'This is what shopping hungry looks like',
      de: 'So sieht hungrig einkaufen aus',
      ar: 'هذا ما يحدث حين تتسوق جائعًا',
      fr: 'Les courses le ventre vide, voilà le résultat',
      es: 'Así se ve ir al súper con hambre',
    },
  },
  {
    emoji: '👜',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'BAKKAL',
        en: 'CORNER STORE',
        de: 'TANTE-EMMA-LADEN',
        ar: 'البقالة',
        fr: 'ÉPICERIE',
        es: 'TIENDA DE LA ESQUINA',
      },
      items: [
        {
          tr: 'BEZ ÇANTA',
          en: 'REUSABLE BAG',
          de: 'STOFFBEUTEL',
          ar: 'حقيبة قماشية',
          fr: 'SAC EN TISSU',
          es: 'BOLSA DE TELA',
        },
      ],
    },
    caption: {
      tr: 'Yine unuttum. Koleksiyon 28 oldu.',
      en: 'Forgot my bags again. Collection: 28.',
      de: 'Wieder vergessen. Sammlung: 28 Stück.',
      ar: 'نسيتها مجددًا… وصارت المجموعة 28',
      fr: 'Encore oublié. La collection en est à 28.',
      es: 'Otra vez la olvidé. Ya van 28.',
    },
  },
  {
    emoji: '🖤',
    user: ACCOUNTS.shopping,
    body: {
      format: 'receipt',
      store: {
        tr: 'GİYİM MAĞAZASI',
        en: 'CLOTHING STORE',
        de: 'MODEGESCHÄFT',
        ar: 'متجر ملابس',
        fr: 'PRÊT-À-PORTER',
        es: 'TIENDA DE ROPA',
      },
      items: [
        {
          tr: 'SİYAH TİŞÖRT (3 ADET)',
          en: 'BLACK T-SHIRT (3)',
          de: 'SCHWARZES T-SHIRT (3)',
          ar: 'قميص أسود (3 قطع)',
          fr: 'T-SHIRT NOIR (3)',
          es: 'CAMISETA NEGRA (3)',
        },
      ],
    },
    caption: {
      tr: 'Bu sefer renkli bir şey alacaktım',
      en: 'I was going to try color this time',
      de: 'Diesmal wollte ich was Buntes',
      ar: 'كنت أنوي شراء شيء ملوّن هذه المرة',
      fr: 'Cette fois, je voulais de la couleur',
      es: 'Esta vez iba a comprar algo de color',
    },
  },
  {
    emoji: '🧁',
    user: ACCOUNTS.food,
    body: {
      format: 'receipt',
      store: {
        tr: 'PASTANE',
        en: 'PASTRY SHOP',
        de: 'KONDITOREI',
        ar: 'محل حلويات',
        fr: 'PÂTISSERIE',
        es: 'PASTELERÍA',
      },
      items: [
        {
          tr: 'EKLER (12 ADET)',
          en: 'ECLAIRS (12)',
          de: 'ECLAIRS (12 STÜCK)',
          ar: 'إكلير (12 قطعة)',
          fr: 'ÉCLAIRS (12)',
          es: 'ÉCLAIRS (12)',
        },
      ],
    },
    caption: {
      tr: 'Misafir için aldım. Misafir iptal etti.',
      en: 'Bought them for guests. Guests canceled.',
      de: 'Für die Gäste gekauft. Die haben abgesagt.',
      ar: 'اشتريتها للضيوف… والضيوف اعتذروا',
      fr: 'Pour les invités. Qui ont annulé.',
      es: 'Los compré para las visitas. Cancelaron.',
    },
  },
  {
    emoji: '📜',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'TARİF ARARKEN',
        en: 'RECIPE HUNTING',
        de: 'AUF REZEPTSUCHE',
        ar: 'أثناء البحث عن وصفة',
        fr: 'EN QUÊTE DE RECETTE',
        es: 'BUSCANDO UNA RECETA',
      },
      big: { tr: '14', en: '14', de: '14', ar: '14', fr: '14', es: '14' },
      text: {
        tr: 'paragraf hikâye okudun; tarif en alttaydı',
        en: 'paragraphs of life story. The recipe was at the very bottom.',
        de: 'Absätze Lebensgeschichte. Das Rezept stand ganz unten.',
        ar: 'فقرة من قصة حياة الكاتب… والوصفة في آخر الصفحة',
        fr: 'paragraphes de blabla. La recette était tout en bas.',
        es: 'párrafos de historia personal. La receta, al final.',
      },
    },
    caption: {
      tr: 'Yazarın tatilini de öğrendin',
      en: "And all about the author's summer vacation",
      de: 'Und alles über den Urlaub der Autorin',
      ar: 'وعرفت أيضًا كل شيء عن إجازة الكاتب',
      fr: "Et tout sur les vacances de l'autrice",
      es: 'Y todo sobre las vacaciones de la autora',
    },
  },
  {
    emoji: '🍱',
    user: ACCOUNTS.kitchen,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '23', en: '23', de: '23', ar: '23', fr: '23', es: '23' },
      text: {
        tr: 'saklama kabın var; kapağı uyan sadece 2',
        en: 'food containers in your cupboard. Lids that fit: 2',
        de: 'Frischhaltedosen im Schrank. Passende Deckel: 2',
        ar: 'علبة حفظ في خزانتك… والأغطية المناسبة: 2',
        fr: 'boîtes alimentaires au placard. Couvercles qui vont : 2',
        es: 'recipientes en tu cocina. Tapas que les quedan: 2',
      },
    },
    caption: {
      tr: 'Kapaklar başka bir boyutta yaşıyor',
      en: 'The lids live in another dimension',
      de: 'Die Deckel leben in einer anderen Dimension',
      ar: 'الأغطية تعيش في بُعد آخر',
      fr: 'Les couvercles vivent dans une autre dimension',
      es: 'Las tapas viven en otra dimensión',
    },
  },
  {
    emoji: '🍏',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'MANAV REYONU',
        en: 'PRODUCE AISLE',
        de: 'OBST UND GEMÜSE',
        ar: 'قسم الخضار والفواكه',
        fr: 'RAYON FRUITS ET LÉGUMES',
        es: 'SECCIÓN DE FRUTAS',
      },
      big: { tr: '4', en: '4', de: '4', ar: '4', fr: '4', es: '4' },
      text: {
        tr: 'dakika poşetin ağzını açmaya uğraştın',
        en: 'minutes trying to open one produce bag',
        de: 'Minuten, um einen Obstbeutel aufzukriegen',
        ar: 'دقائق وأنت تحاول فتح كيس الخضار',
        fr: "minutes à essayer d'ouvrir un sachet",
        es: 'minutos intentando abrir una bolsita',
      },
    },
    caption: {
      tr: 'Sonunda açtım. Meğer ters tutuyormuşum.',
      en: 'Turns out I was holding it upside down',
      de: 'Ich hielt ihn die ganze Zeit falsch herum',
      ar: 'اتضح أنني كنت أمسكه مقلوبًا',
      fr: "Je le tenais à l'envers depuis le début",
      es: 'Resulta que lo tenía al revés',
    },
  },
  {
    emoji: '🏬',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ALIŞVERİŞ GÜNÜ TIER LIST',
        en: 'SHOPPING DAY TIER LIST',
        de: 'EINKAUFSTAG-RANKING',
        ar: 'تصنيف يوم التسوق',
        fr: 'TIER LIST DU SHOPPING',
        es: 'TIER LIST DE COMPRAS',
      },
      rows: [['🍦', '🥨'], ['👟', '👕'], ['🕶️', '🧴'], ['🅿️']],
    },
    caption: {
      tr: 'Alışveriş 1 saat, otoparktan çıkış 2 saat',
      en: 'Shopping: 1 hour. Leaving the parking lot: 2.',
      de: 'Shoppen: 1 Stunde. Parkhaus verlassen: 2.',
      ar: 'التسوق ساعة… والخروج من الموقف ساعتان',
      fr: 'Shopping : 1 h. Sortir du parking : 2 h.',
      es: 'Compras: 1 hora. Salir del estacionamiento: 2.',
    },
  },
  {
    emoji: '🐜',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'PİKNİK SEPETİ TIER LIST',
        en: 'PICNIC BASKET TIER LIST',
        de: 'PICKNICKKORB-RANKING',
        ar: 'تصنيف سلة النزهة',
        fr: 'TIER LIST DU PIQUE-NIQUE',
        es: 'TIER LIST DEL PÍCNIC',
      },
      rows: [['🍉', '🥪'], ['🍇', '🧃', '🍓'], ['🥗', '🥒'], ['🐜']],
    },
    caption: {
      tr: 'Karıncalar kendini hep S sanıyor',
      en: "The ants always think they're S tier",
      de: 'Die Ameisen halten sich immer für S',
      ar: 'النمل يظن نفسه دائمًا في القمة',
      fr: 'Les fourmis se croient toujours en S',
      es: 'Las hormigas siempre se creen de la S',
    },
  },
  {
    emoji: '🥚',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⏲️',
        app: {
          tr: 'Zamanlayıcı',
          en: 'Timer',
          de: 'Timer',
          ar: 'المؤقت',
          fr: 'Minuteur',
          es: 'Temporizador',
        },
        text: {
          tr: 'Yumurtalar hazır! (18 dakika önce)',
          en: 'Eggs are ready! (18 minutes ago)',
          de: 'Eier sind fertig! (vor 18 Minuten)',
          ar: 'البيض جاهز! (قبل 18 دقيقة)',
          fr: 'Les œufs sont prêts ! (il y a 18 min)',
          es: '¡Los huevos están listos! (hace 18 min)',
        },
      },
    },
    caption: {
      tr: 'Rafadan planı suya düştü',
      en: 'So much for soft-boiled',
      de: 'Weich gekocht? Das war einmal.',
      ar: 'وداعًا للبيض نصف المسلوق',
      fr: "Adieu l'œuf à la coque",
      es: 'Iban a quedar blanditos. Ya no.',
    },
  },
  {
    emoji: '📦',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⏳',
        app: {
          tr: 'İadeler',
          en: 'Returns',
          de: 'Rücksendungen',
          ar: 'المرتجعات',
          fr: 'Retours',
          es: 'Devoluciones',
        },
        text: {
          tr: 'İade için son gün: bugün',
          en: 'Last day to return: today',
          de: 'Letzter Tag für die Rücksendung: heute',
          ar: 'آخر يوم للإرجاع: اليوم',
          fr: "Dernier jour de retour : aujourd'hui",
          es: 'Último día para devolverlo: hoy',
        },
      },
    },
    caption: {
      tr: 'İade paketi 30 gündür kapının yanında',
      en: 'The return box has been by the door for 30 days',
      de: 'Das Retourenpaket steht seit 30 Tagen an der Tür',
      ar: 'طرد الإرجاع بجانب الباب منذ 30 يومًا',
      fr: 'Le colis de retour attend à la porte depuis 30 jours',
      es: 'La devolución lleva 30 días junto a la puerta',
    },
  },
  {
    emoji: '💸',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Tasarruf önemlidir. — %50 indirimle ihtiyacı olmayan 4 şey alan biri',
        en: "Always save money. — Me, buying 4 things I don't need at 50% off",
        de: 'Sparen ist wichtig. — Ich, mit 4 unnötigen Schnäppchen',
        ar: 'التوفير مهم. — شخص اشترى 4 أشياء لا يحتاجها بخصم 50%',
        fr: 'Il faut savoir économiser. — Moi, avec 4 trucs inutiles à -50 %',
        es: 'Ahorrar es importante. — Yo, con 4 cosas que no necesitaba al 50 %',
      },
    },
    caption: {
      tr: 'İndirim kaçmadı, param kaçtı',
      en: 'Caught the sale. Lost my savings.',
      de: 'Schnäppchen gemacht. Geld weg.',
      ar: 'لحقت بالتخفيضات… وطارت النقود',
      fr: "La promo n'a pas filé. Mon argent, si.",
      es: 'No se me escapó la oferta. Mi dinero, sí.',
    },
  },
  {
    emoji: '🥄',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Hazırlık her şeydir. — Tarifin yarısında un olmadığını gören ben',
        en: 'Preparation is everything. — Me, out of flour halfway through',
        de: 'Vorbereitung ist alles. — Ich, mitten im Rezept, ohne Mehl',
        ar: 'الاستعداد هو كل شيء. — أنا في منتصف الوصفة بلا طحين',
        fr: 'Tout est dans la préparation. — Moi, à mi-recette, sans farine',
        es: 'La preparación lo es todo. — Yo, a mitad de receta y sin harina',
      },
    },
    caption: {
      tr: 'Plan B: kek yerine meyve salatası',
      en: 'Plan B: fruit salad instead of cake',
      de: 'Plan B: Obstsalat statt Kuchen',
      ar: 'الخطة البديلة: سلطة فواكه بدل الكعكة',
      fr: 'Plan B : salade de fruits au lieu du gâteau',
      es: 'Plan B: ensalada de frutas en vez de pastel',
    },
  },
  {
    emoji: '🔍',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Az olsun, öz olsun. — Şık restoranda üç bezelyelik tabağa bakan ben',
        en: 'Less is more. — Me, staring at three peas on a fancy plate',
        de: 'Weniger ist mehr. — Ich, vor drei Erbsen auf einem edlen Teller',
        ar: 'خير الطعام ما قلّ ودلّ. — أنا أمام ثلاث حبات بازلاء في مطعم فاخر',
        fr: "Moins, c'est plus. — Moi, devant trois petits pois dans un resto chic",
        es: 'Menos es más. — Yo, ante un plato enorme con un bocado diminuto',
      },
    },
    caption: {
      tr: 'Çıkışta bir tost yedim',
      en: 'Grabbed a burger on the way home',
      de: "Auf dem Heimweg gab's noch Pizza",
      ar: 'وفي طريق العودة اشتريت شطيرة',
      fr: 'Au retour, sandwich obligatoire',
      es: 'De regreso, me comí un sándwich',
    },
  },
  {
    emoji: '📋',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Cesur ol, yeni şeyler dene. — Her zamankini söyleyen ben',
        en: 'Be brave. Try new things. — Me, ordering the usual',
        de: 'Sei mutig, probier Neues. — Ich, beim Bestellen: „wie immer“',
        ar: 'كن جريئًا وجرّب الجديد. — أنا وأنا أطلب الطبق المعتاد',
        fr: "Ose essayer du nouveau. — Moi, qui commande comme d'habitude",
        es: 'Atrévete a probar cosas nuevas. — Yo, pidiendo lo de siempre',
      },
    },
    caption: {
      tr: 'Menüyü 20 dakika okudum. Neden?',
      en: 'Read the menu for 20 minutes. Why?',
      de: '20 Minuten Speisekarte gelesen. Wozu?',
      ar: 'قرأت القائمة 20 دقيقة… لماذا؟',
      fr: "J'ai lu la carte pendant 20 minutes. Pourquoi ?",
      es: 'Leí el menú 20 minutos. ¿Para qué?',
    },
  },
];

export const FOOD_LIKE: readonly Draft[] = [
  {
    emoji: '🍞',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk ekmeğim kabardı!! kendimi alkışladım',
      en: 'my first loaf actually rose!! applauded myself',
      de: 'mein erstes brot ist aufgegangen!! hab mir applaudiert',
      ar: 'خبزي الأول انتفخ!! صفّقت لنفسي',
      fr: 'mon premier pain a levé !! je me suis applaudie',
      es: '¡¡mi primer pan subió!! me aplaudí sola',
    },
  },
  {
    emoji: '🥞',
    user: ACCOUNTS.mert,
    body: { format: 'scene' },
    caption: {
      tr: 'krebi havada çevirdim, tavaya geri düştü!!',
      en: 'flipped my crepe midair. it landed in the pan!!',
      de: 'crêpe in der luft gewendet. landung in der pfanne!!',
      ar: 'قلبت الكريب في الهواء… وعاد إلى المقلاة!!',
      fr: "j'ai fait sauter ma crêpe, retombée dans la poêle !!",
      es: '¡¡lancé el crepe al aire y cayó en la sartén!!',
    },
  },
  {
    emoji: '🥟',
    user: ACCOUNTS.tolga,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk mantım: 312 tane, tek tek saydım',
      en: 'made dumplings from scratch: 312, yes I counted',
      de: 'erste selbstgemachte teigtaschen: 312, alle gezählt',
      ar: 'أول مرة أصنع المانتي: 312 حبة، عددتها واحدة واحدة',
      fr: 'premiers raviolis maison : 312, je les ai comptés',
      es: 'mis primeros raviolis caseros: 312, los conté',
    },
  },
  {
    emoji: '🍋',
    user: ACCOUNTS.yagmur,
    body: { format: 'scene' },
    caption: {
      tr: 'limonata tezgâhım 12 bardak sattı (9’u annem)',
      en: 'my lemonade stand sold 12 cups (9 to my mom)',
      de: 'mein limo-stand: 12 becher verkauft (9 an mama)',
      ar: 'كشك الليموناضة باع 12 كوبًا (9 منها لأمي)',
      fr: 'mon stand de citronnade : 12 verres (dont 9 à maman)',
      es: 'mi puesto de limonada vendió 12 vasos (9 a mi mamá)',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk maaşımla',
        en: 'first paycheck dinner',
        de: 'erstes gehalt',
        ar: 'من أول راتب',
        fr: 'premier salaire',
        es: 'primer sueldo',
      },
    },
    caption: {
      tr: 'ailemi yemeğe çıkardım, hesap benden!!',
      en: 'took my family out to dinner, my treat!!',
      de: 'familie zum essen eingeladen, geht auf mich!!',
      ar: 'دعوت عائلتي إلى العشاء… والحساب عليّ!!',
      fr: "j'ai invité ma famille au resto, c'est moi qui paie !!",
      es: '¡¡invité a cenar a mi familia, pago yo!!',
    },
  },
  {
    emoji: '🦢',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'kuğu (ördek oldu)',
        en: "swan (it's a duck)",
        de: 'schwan (eher ente)',
        ar: 'بجعة (صارت بطة)',
        fr: 'cygne (plutôt canard)',
        es: 'cisne (salió pato)',
      },
    },
    caption: {
      tr: 'ilk misafir sofram!! peçeteler bile katlı',
      en: 'hosted my first dinner!! even folded the napkins',
      de: 'erstes dinner für gäste!! sogar servietten gefaltet',
      ar: 'أول مائدة أعدّها للضيوف!! حتى المناديل مطوية',
      fr: 'mon premier dîner !! serviettes pliées et tout',
      es: '¡¡primera cena con invitados!! hasta doblé servilletas',
    },
  },
  {
    emoji: '🧥',
    user: ACCOUNTS.irem,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ikinci el hazinesi',
        en: 'thrift store treasure',
        de: 'second-hand-schatz',
        ar: 'كنز من سوق المستعمل',
        fr: 'trésor de friperie',
        es: 'tesoro de segunda mano',
      },
    },
    caption: {
      tr: 'hayatımın ceketini ikinci elde buldum',
      en: 'found the jacket of my life at a thrift store',
      de: 'die jacke meines lebens im second-hand-laden gefunden',
      ar: 'وجدت سترة العمر في متجر للملابس المستعملة',
      fr: 'trouvé la veste de ma vie en friperie',
      es: 'la chaqueta de mi vida, y de segunda mano',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.arda,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bu bir kalp',
        en: "that's a heart",
        de: 'das ist ein herz',
        ar: 'هذا قلب',
        fr: "c'est un cœur",
        es: 'es un corazón',
      },
    },
    caption: {
      tr: 'ilk latte art kalbim!! biraz bulut gibi',
      en: 'my first latte art heart!! kinda looks like a cloud',
      de: 'mein erstes latte-art-herz!! sieht eher nach wolke aus',
      ar: 'أول قلب أرسمه على القهوة!! يشبه غيمة قليلًا',
      fr: 'mon premier cœur en latte art !! un peu nuage',
      es: '¡¡mi primer corazón de latte art!! parece una nube',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.ayse,
    body: { format: 'dump', emojis: ['🧺', '🍅', '🍑', '🥬', '🌽'] },
    caption: {
      tr: 'pazar dump’ı: pazarcılar artık adımı biliyor',
      en: 'farmers market dump: the vendors know my name now',
      de: 'wochenmarkt-dump: die händler kennen meinen namen',
      ar: 'جولة السوق: الباعة صاروا يعرفون اسمي',
      fr: 'dump du marché : les vendeurs savent mon prénom',
      es: 'día de mercado: los vendedores ya saben mi nombre',
    },
  },
  {
    emoji: '🛍️',
    user: ACCOUNTS.defne,
    body: { format: 'dump', emojis: ['🛍️', '👟', '👗', '🧦', '🥤'] },
    caption: {
      tr: 'avm dump’ı: 5 mağaza, 3 saat, 1 çift çorap',
      en: 'mall dump: 5 stores, 3 hours, 1 pair of socks',
      de: 'shopping-dump: 5 läden, 3 stunden, 1 paar socken',
      ar: 'جولة المول: 5 متاجر، 3 ساعات، زوج جوارب واحد',
      fr: 'journée shopping : 5 boutiques, 3 h, 1 paire de chaussettes',
      es: 'día de compras: 5 tiendas, 3 horas, 1 par de calcetines',
    },
  },
  {
    emoji: '🧑‍🍳',
    user: ACCOUNTS.baris,
    body: { format: 'dump', emojis: ['🧑‍🍳', '🥘', '🧂', '🧄', '🥕'] },
    caption: {
      tr: 'yemek kursu dump’ı: şef “harika” dedi (yanımdakine)',
      en: 'cooking class dump: chef said “perfect” (not to me)',
      de: 'kochkurs-dump: der koch sagte „perfekt“ (nicht zu mir)',
      ar: 'دورة الطبخ: قال الشيف «ممتاز» (لكن ليس لي)',
      fr: 'cours de cuisine : le chef a dit « parfait » (pas à moi)',
      es: 'clase de cocina: el chef dijo “perfecto” (no a mí)',
    },
  },
];

export const FOOD_HOLD: readonly Draft[] = [
  {
    emoji: '🍯',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kavanoz kapağı ilk denemede açıldı!',
      en: 'The jar lid opened on the first try!',
      de: 'Das Glas ging beim ersten Versuch auf!',
      ar: 'غطاء المرطبان انفتح من المحاولة الأولى!',
      fr: "Le bocal s'est ouvert du premier coup !",
      es: '¡El frasco se abrió al primer intento!',
    },
  },
  {
    emoji: '🛒',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Dört tekerleği de düzgün market arabası!',
      en: 'A shopping cart with four working wheels!',
      de: 'Ein Einkaufswagen, der geradeaus fährt!',
      ar: 'عربة تسوّق عجلاتها الأربع سليمة!',
      fr: 'Un chariot qui roule droit !',
      es: '¡Un carrito con las cuatro ruedas buenas!',
    },
  },
  {
    emoji: '🍝',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Makarna tam kıvamında. Şimdi süz!',
      en: "Pasta's perfectly al dente. Drain it now!",
      de: 'Nudeln perfekt al dente. Jetzt abgießen!',
      ar: 'المعكرونة على القوام المثالي. صفّها الآن!',
      fr: 'Pâtes parfaitement al dente. Égoutte maintenant !',
      es: 'Pasta al dente perfecta. ¡Escúrrela ya!',
    },
  },
  {
    emoji: '🍿',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Mısırlar patladı, hiçbiri yanmadı. Şimdi çıkar!',
      en: 'Every kernel popped. None burned. Take it out now!',
      de: 'Alles gepoppt, nichts verbrannt. Jetzt raus damit!',
      ar: 'انفجرت كل الحبات ولم تحترق واحدة. أخرجها الآن!',
      fr: "Tout a éclaté, rien n'a brûlé. Sors-le maintenant !",
      es: 'Todas reventaron, ninguna se quemó. ¡Sácalas ya!',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kurabiye kutusundan gerçekten kurabiye çıktı!',
      en: 'The cookie tin actually has cookies in it!',
      de: 'In der Keksdose sind wirklich Kekse!',
      ar: 'علبة البسكويت فيها بسكويت فعلًا!',
      fr: 'La boîte à biscuits contient vraiment des biscuits !',
      es: '¡La lata de galletas tiene galletas de verdad!',
    },
  },
  {
    emoji: '🧾',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kasada etiketteki fiyattan ucuz çıktı!',
      en: 'It rang up cheaper than the shelf price!',
      de: 'An der Kasse billiger als ausgeschildert!',
      ar: 'سعره عند الصندوق أقل من سعر الرف!',
      fr: "Moins cher en caisse qu'en rayon !",
      es: '¡En la caja salió más barato que en la etiqueta!',
    },
  },
  {
    emoji: '🍨',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Garson: “Tatlı bizden.”',
      en: 'The waiter says: “Dessert’s on the house.”',
      de: 'Der Kellner: „Der Nachtisch geht aufs Haus.“',
      ar: 'النادل: «الحلوى على حساب المحل»',
      fr: 'Le serveur : « Le dessert est offert. »',
      es: '“El postre, cortesía de la casa.”',
    },
  },
  {
    emoji: '👖',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'İnternetten aldın ve ilk seferde tam oldu!',
      en: 'Ordered online and it fit the first time!',
      de: 'Online bestellt und passt auf Anhieb!',
      ar: 'اشتريته من الإنترنت وجاء على مقاسك من أول مرة!',
      fr: 'Commandé en ligne, et à ta taille du premier coup !',
      es: '¡Lo pediste en línea y te quedó a la primera!',
    },
  },
];

export const FOOD_FREEZE: readonly Draft[] = [
  {
    emoji: '🎂',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'FIRINI AÇMAYIN',
        en: "DON'T OPEN",
        de: 'NICHT ÖFFNEN',
        ar: 'لا تفتح الفرن',
        fr: 'NE PAS OUVRIR',
        es: 'NO ABRIR',
      },
      small: {
        tr: 'KEK KABARIYOR',
        en: 'CAKE RISING INSIDE',
        de: 'KUCHEN GEHT GERADE AUF',
        ar: 'الكعكة تنتفخ',
        fr: 'GÂTEAU EN TRAIN DE MONTER',
        es: 'PASTEL SUBIENDO',
      },
    },
    caption: {
      tr: 'Bir kıpırtı, kek söner.',
      en: 'One wobble and it sinks.',
      de: 'Ein Wackler, und er fällt zusammen.',
      ar: 'حركة واحدة وتهبط.',
      fr: 'Un geste et il retombe.',
      es: 'Un movimiento y se baja.',
    },
    headline: {
      tr: 'Kek tam kabarıyor',
      en: 'The cake is rising',
      de: 'Der Kuchen geht gerade auf',
      ar: 'الكعكة تنتفخ الآن',
      fr: 'Le gâteau est en train de monter',
      es: 'El pastel está subiendo',
    },
  },
  {
    emoji: '🍮',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SALLAMAYIN',
        en: "DON'T SHAKE",
        de: 'NICHT WACKELN',
        ar: 'لا تهزّ',
        fr: 'NE PAS SECOUER',
        es: 'NO MOVER',
      },
      small: {
        tr: 'MUHALLEBİ DONUYOR',
        en: 'PUDDING IS SETTING',
        de: 'PUDDING WIRD FEST',
        ar: 'المهلبية تتماسك',
        fr: 'LE FLAN PREND',
        es: 'EL FLAN ESTÁ CUAJANDO',
      },
    },
    caption: {
      tr: 'Masayı bile sallama.',
      en: "Don't even bump the table.",
      de: 'Nicht mal den Tisch anstoßen.',
      ar: 'لا تهزّ الطاولة حتى.',
      fr: 'Ne touche même pas la table.',
      es: 'Ni siquiera toques la mesa.',
    },
    headline: {
      tr: 'Muhallebi donmak üzere',
      en: "The pudding's almost set",
      de: 'Der Pudding ist fast fest',
      ar: 'المهلبية على وشك أن تتماسك',
      fr: 'Le flan a presque pris',
      es: 'El flan está por cuajar',
    },
  },
  {
    emoji: '🍊',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'CAUTION',
        de: 'ACHTUNG',
        ar: 'تنبيه',
        fr: 'ATTENTION',
        es: 'CUIDADO',
      },
      small: {
        tr: 'ALTTAN ALMAYINIZ',
        en: 'DO NOT TAKE FROM THE BOTTOM',
        de: 'NICHT VON UNTEN NEHMEN',
        ar: 'لا تأخذ من الأسفل',
        fr: 'NE PAS PRENDRE PAR-DESSOUS',
        es: 'NO TOMAR DE ABAJO',
      },
    },
    caption: {
      tr: 'Hiç düşünme bile.',
      en: "Don't even think about it.",
      de: 'Denk nicht mal dran.',
      ar: 'لا تفكر في الأمر حتى.',
      fr: "N'y pense même pas.",
      es: 'Ni lo pienses.',
    },
    headline: {
      tr: 'En güzel portakal en altta',
      en: 'The best orange is at the very bottom',
      de: 'Die schönste Orange liegt ganz unten',
      ar: 'أجمل برتقالة في أسفل الهرم',
      fr: 'La plus belle orange est tout en bas',
      es: 'La mejor naranja está en la base',
    },
  },
  {
    emoji: '🧤',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'SICAK',
        en: 'HOT',
        de: 'HEISS',
        ar: 'ساخن',
        fr: 'CHAUD',
        es: 'CALIENTE',
      },
      small: {
        tr: 'TEPSİYE DOKUNMAYIN',
        en: 'DO NOT TOUCH THE TRAY',
        de: 'BLECH NICHT ANFASSEN',
        ar: 'لا تلمس الصينية',
        fr: 'NE PAS TOUCHER LA PLAQUE',
        es: 'NO TOCAR LA BANDEJA',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Tepsi fırından yeni çıktı',
      en: 'The tray just came out of the oven',
      de: 'Das Blech kommt gerade aus dem Ofen',
      ar: 'الصينية خرجت من الفرن للتو',
      fr: 'La plaque sort à peine du four',
      es: 'La bandeja acaba de salir del horno',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'RESTORAN',
        en: 'RESTAURANT',
        de: 'RESTAURANT',
        ar: 'المطعم',
        fr: 'RESTAURANT',
        es: 'RESTAURANTE',
      },
    },
    caption: {
      tr: 'Herkes dondu. Sen de kıpırdama.',
      en: "Everyone froze. Don't you move either.",
      de: 'Alle erstarrt. Du auch.',
      ar: 'الجميع تجمّد. لا تتحرك أنت أيضًا.',
      fr: 'Tout le monde est figé. Toi aussi.',
      es: 'Todos se congelaron. Tú tampoco te muevas.',
    },
    headline: {
      tr: 'Hesap masaya geldi',
      en: 'The check just hit the table',
      de: 'Die Rechnung liegt auf dem Tisch',
      ar: 'وصلت الفاتورة إلى الطاولة',
      fr: "L'addition arrive sur la table",
      es: 'Llegó la cuenta a la mesa',
    },
  },
  {
    emoji: '👗',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'GİYİM MAĞAZASI',
        en: 'CLOTHING STORE',
        de: 'MODEGESCHÄFT',
        ar: 'متجر الملابس',
        fr: 'BOUTIQUE',
        es: 'TIENDA DE ROPA',
      },
    },
    caption: {
      tr: 'Sadece bakıyorsun. Kıpırdama.',
      en: "You're just looking. Don't move.",
      de: 'Du schaust nur. Keine Bewegung.',
      ar: 'أنت تتفرّج فقط. لا تتحرك.',
      fr: 'Tu regardes juste. Bouge pas.',
      es: 'Solo estás mirando. No te muevas.',
    },
    headline: {
      tr: 'Satış danışmanı sana doğru geliyor',
      en: 'A sales associate is heading your way',
      de: 'Eine Verkäuferin kommt auf dich zu',
      ar: 'موظف المبيعات قادم نحوك',
      fr: 'Un vendeur arrive droit sur toi',
      es: 'Un vendedor viene hacia ti',
    },
  },
  {
    emoji: '🍢',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MARKET',
        en: 'SUPERMARKET',
        de: 'SUPERMARKT',
        ar: 'السوبرماركت',
        fr: 'SUPERMARCHÉ',
        es: 'SUPERMERCADO',
      },
    },
    caption: {
      tr: 'Kıpırdama. Belki hatırlamaz.',
      en: "Don't move. Maybe they won't remember.",
      de: "Nicht bewegen. Vielleicht vergisst er's.",
      ar: 'لا تتحرك. ربما لا يتذكرك.',
      fr: "Bouge pas. Peut-être qu'il a oublié.",
      es: 'No te muevas. Quizá no se acuerde.',
    },
    headline: {
      tr: 'Tadım standı seni 4. kez görüyor',
      en: 'The sample stand has seen you 4 times',
      de: 'Der Probierstand sieht dich zum 4. Mal',
      ar: 'موظف التذوق يراك للمرة الرابعة',
      fr: "Le stand dégustation t'a vu 4 fois",
      es: 'En la degustación ya te vieron 4 veces',
    },
  },
];
