import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Friends and social life: plans, birthdays, parties, texting, inside jokes, the group chat.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const FRIENDS_SKIP: readonly Draft[] = [
  // scene
  {
    emoji: '🎂',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Doğum günü şarkısı: 8 kişi, 8 farklı ton',
      en: 'Happy birthday song: 8 people, 8 different keys',
      de: 'Geburtstagsständchen: 8 Leute, 8 Tonarten',
      ar: 'أغنية عيد الميلاد: 8 أشخاص و8 نغمات مختلفة',
      fr: 'Joyeux anniversaire : 8 voix, 8 tonalités',
      es: 'Cumpleaños feliz: 8 personas, 8 tonos distintos',
    },
  },
  {
    emoji: '📕',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Ödünç verdiğim kitap 4. okurunda. Ben okumadım bile.',
      en: "The book I lent out is on reader #4. I haven't even read it.",
      de: 'Mein Buch ist schon beim 4. Leser. Ich hab es nie gelesen.',
      ar: 'الكتاب الذي أعرته وصل إلى قارئه الرابع، وأنا لم أقرأه بعد',
      fr: 'Mon livre prêté en est à son 4e lecteur. Moi, jamais lu.',
      es: 'Mi libro prestado va por su 4.º lector. Yo ni lo he leído.',
    },
  },
  {
    emoji: '😐',
    user: ACCOUNTS.screens,
    body: { format: 'scene' },
    caption: {
      tr: '“HAHAHAHA” yazarken yüzüm',
      en: 'My face while typing “HAHAHAHA”',
      de: 'Mein Gesicht beim Tippen von „HAHAHAHA“',
      ar: 'وجهي وأنا أكتب «هههههه»',
      fr: "Ma tête quand j'écris « MDRRR »",
      es: 'Mi cara mientras escribo “JAJAJAJA”',
    },
  },
  {
    emoji: '🕰️',
    user: ACCOUNTS.city,
    body: { format: 'scene' },
    caption: {
      tr: '10 dk geç kaldım. Yine ilk gelen bendim.',
      en: 'Showed up 10 minutes late. Still the first one there.',
      de: '10 Minuten zu spät. Trotzdem war noch keiner da.',
      ar: 'تأخرت 10 دقائق… وما زلت أول الواصلين',
      fr: "10 min de retard. Et personne n'était encore là.",
      es: 'Llegué 10 minutos tarde. Aún no había nadie.',
    },
  },
  {
    emoji: '🤞',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Herkes “hâlâ geçerli mi?” diye sordu, “hayır” umuduyla',
      en: 'Everyone texted “still on?” Secretly hoping for a no.',
      de: 'Alle fragen „Steht das noch?“ – und hoffen auf Nein.',
      ar: 'سأل الجميع «هل ما زال الموعد قائمًا؟» آملين أن يُلغى',
      fr: 'Chacun demande « ça tient toujours ? » en espérant un non',
      es: 'Todos preguntaron “¿sigue en pie?” esperando un no',
    },
  },
  {
    emoji: '🥔',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Grup adı 47. kez değişti. Şu anki: “patatesler”',
      en: 'Group chat renamed for the 47th time. Now: “the potatoes”',
      de: 'Gruppenname zum 47. Mal geändert. Jetzt: „Die Kartoffeln“',
      ar: 'تغيّر اسم المجموعة للمرة الـ47. الاسم الآن: «البطاطس»',
      fr: 'Nom du groupe changé pour la 47e fois. Là : « les patates »',
      es: 'El grupo cambió de nombre 47 veces. Ahora: “las papas”',
    },
  },
  // chat
  {
    emoji: '🎈',
    user: ACCOUNTS.trends,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sürpriz parti',
        en: 'Surprise party',
        de: 'Überraschungsparty',
        ar: 'الحفلة المفاجئة',
        fr: 'Fête surprise',
        es: 'Fiesta sorpresa',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'pasta bende, balonları kim alıyor?',
            en: "I've got the cake, who's on balloons?",
            de: 'Torte hab ich, wer holt die Ballons?',
            ar: 'الكعكة عليّ، من سيحضر البالونات؟',
            fr: "j'ai le gâteau, qui s'occupe des ballons ?",
            es: 'yo llevo el pastel, ¿quién trae los globos?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ben! kimse ağzından kaçırmasın ama',
            en: 'me! and nobody spill it',
            de: 'ich! und keiner verplappert sich',
            ar: 'أنا! وإياكم أن يفلت السرّ من أحد',
            fr: 'moi ! et personne ne vend la mèche',
            es: '¡yo! y que nadie diga nada',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ne partisi? 👀',
            en: 'what party? 👀',
            de: 'welche Party? 👀',
            ar: 'أي حفلة؟ 👀',
            fr: 'quelle fête ? 👀',
            es: '¿qué fiesta? 👀',
          },
        },
      ],
    },
    caption: {
      tr: 'Doğum günü olanı da gruba eklemişiz',
      en: 'We added the birthday girl to the group',
      de: 'Das Geburtstagskind war auch in der Gruppe',
      ar: 'أضفنا صاحبة عيد الميلاد إلى المجموعة',
      fr: 'On avait ajouté la principale intéressée au groupe',
      es: 'Agregamos a la cumpleañera al grupo',
    },
  },
  {
    emoji: '📳',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
      },
      lines: [
        { from: 'them', text: { tr: 'kanka', en: 'hey', de: 'hey', ar: 'يا صديقي', fr: 'hé', es: 'oye' } },
        { from: 'them', text: { tr: 'bak', en: 'so', de: 'also', ar: 'اسمع', fr: 'écoute', es: 'mira' } },
        { from: 'them', text: { tr: 'şey', en: 'um', de: 'ähm', ar: 'يعني…', fr: 'euh', es: 'este…' } },
        {
          from: 'them',
          text: {
            tr: 'neyse boşver',
            en: 'nvm',
            de: 'egal, vergiss es',
            ar: 'لا عليك، انسَ الأمر',
            fr: 'laisse tomber',
            es: 'olvídalo',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'BU NEYDİ ŞİMDİ',
            en: 'WHAT WAS THAT',
            de: 'WAS WAR DAS DENN',
            ar: 'ما هذا الآن؟!',
            fr: "C'ÉTAIT QUOI, ÇA ?",
            es: '¿¿QUÉ FUE ESO??',
          },
        },
      ],
    },
    caption: {
      tr: '4 bildirim, 0 bilgi',
      en: '4 notifications, 0 information',
      de: '4 Benachrichtigungen, 0 Inhalt',
      ar: '4 إشعارات، و0 معلومات',
      fr: '4 notifs, 0 info',
      es: '4 notificaciones, 0 información',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.vlog,
    body: {
      format: 'chat',
      contact: {
        tr: 'Piknik grubu',
        en: 'Picnic crew',
        de: 'Picknick-Gruppe',
        ar: 'مجموعة النزهة',
        fr: 'Pique-nique',
        es: 'Grupo del pícnic',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'herkes bir şey getirsin!',
            en: 'everyone bring something!',
            de: 'jeder bringt was mit!',
            ar: 'ليُحضر كل واحد شيئًا!',
            fr: 'chacun apporte un truc !',
            es: '¡que cada uno traiga algo!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ben peçete getiririm',
            en: "I'll bring napkins",
            de: 'ich bring Servietten',
            ar: 'سأحضر المناديل',
            fr: 'moi, les serviettes',
            es: 'yo llevo servilletas',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ben de peçete',
            en: 'napkins for me too',
            de: 'ich auch Servietten',
            ar: 'وأنا سأحضر مناديل',
            fr: 'moi aussi, des serviettes',
            es: 'yo también servilletas',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'peçete bende 🙋',
            en: "I've got napkins 🙋",
            de: 'Servietten kommen von mir 🙋',
            ar: 'المناديل عليّ 🙋',
            fr: 'serviettes pour moi aussi 🙋',
            es: 'las servilletas, yo 🙋',
          },
        },
      ],
    },
    caption: {
      tr: 'Pikniğe 6 paket peçete geldi. Yemek gelmedi.',
      en: '6 packs of napkins showed up. Zero food.',
      de: '6 Packungen Servietten. Null Essen.',
      ar: 'وصلت 6 علب مناديل… ولم يصل أي طعام',
      fr: '6 paquets de serviettes. Zéro nourriture.',
      es: 'Llegaron 6 paquetes de servilletas. Cero comida.',
    },
  },
  {
    emoji: '🤫',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sırdaşım',
        en: 'Secret keeper',
        de: 'Mein Vertrauter',
        ar: 'كاتم أسراري',
        fr: 'Mon confident',
        es: 'Mi confidente',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'sır tutabilir misin?',
            en: 'can you keep a secret?',
            de: 'kannst du ein Geheimnis bewahren?',
            ar: 'هل تستطيع كتمان سر؟',
            fr: 'tu sais garder un secret ?',
            es: '¿sabes guardar un secreto?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tabii ki! 🤐',
            en: 'of course! 🤐',
            de: 'na klar! 🤐',
            ar: 'طبعًا! 🤐',
            fr: 'bien sûr ! 🤐',
            es: '¡claro! 🤐',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'süper, ben tutamıyorum. dinle:',
            en: "great, 'cause I can't. listen:",
            de: 'super, ich nämlich nicht. hör zu:',
            ar: 'رائع، لأنني لا أستطيع. اسمع:',
            fr: 'super, parce que moi, non. écoute :',
            es: 'genial, porque yo no. escucha:',
          },
        },
      ],
    },
    caption: {
      tr: 'Sır sadece el değiştirdi',
      en: 'The secret just changed hands',
      de: 'Das Geheimnis hat nur den Besitzer gewechselt',
      ar: 'السرّ غيّر صاحبه فقط',
      fr: 'Le secret a juste changé de main',
      es: 'El secreto solo cambió de manos',
    },
  },
  // poll
  {
    emoji: '🙈',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Grup fotoğrafını sen paylaşacaksın. Hangisi?',
        en: "You're posting the group photo. Which one?",
        de: 'Du postest das Gruppenfoto. Welches?',
        ar: 'ستنشر أنت صورة المجموعة. أيّها تختار؟',
        fr: 'Tu postes la photo de groupe. Laquelle ?',
        es: 'Tú subes la foto grupal. ¿Cuál eliges?',
      },
      options: [
        {
          tr: 'Herkes güzel çıkmış',
          en: 'Everyone looks good',
          de: 'Alle sehen gut aus',
          ar: 'الجميع يبدون رائعين',
          fr: 'Tout le monde est bien',
          es: 'Todos salen bien',
        },
        {
          tr: 'Ben güzel çıkmışım',
          en: 'I look good',
          de: 'Ich seh gut aus',
          ar: 'أنا أبدو رائعًا',
          fr: 'Moi, je suis bien',
          es: 'Yo salgo bien',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Diğerleri “sil şunu” diyor. Çok geç.',
      en: 'The others say “delete it.” Too late.',
      de: 'Die anderen: „Lösch das!“ Zu spät.',
      ar: 'الباقون يقولون «احذفها». فات الأوان.',
      fr: 'Les autres : « supprime ! » Trop tard.',
      es: 'Los demás dicen “bórrala”. Muy tarde.',
    },
  },
  {
    emoji: '🤭',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Yeni arkadaş, grubun iç şakasını sordu. Sen:',
        en: 'The new friend asks about your inside joke. You:',
        de: 'Die Neue fragt nach eurem Insider. Du:',
        ar: 'صديق جديد سأل عن نكتتكم الخاصة. ماذا تفعل؟',
        fr: 'Le nouveau demande votre private joke. Toi :',
        es: 'El nuevo pregunta por su chiste interno. Tú:',
      },
      options: [
        {
          tr: 'Baştan anlatırım',
          en: 'Explain it all',
          de: 'Alles erklären',
          ar: 'أشرح كل شيء',
          fr: 'Tout expliquer',
          es: 'Lo explico todo',
        },
        {
          tr: '“Orada olacaktın”',
          en: '“You had to be there”',
          de: '„Musstest dabei sein“',
          ar: '«كان يجب أن تكون هناك»',
          fr: '« Fallait être là »',
          es: '“Tenías que estar ahí”',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Bir kez denedik. Sadece biz güldük.',
      en: 'We tried once. Only we laughed.',
      de: 'Einmal versucht. Nur wir haben gelacht.',
      ar: 'حاولنا مرة… ولم يضحك سوانا',
      fr: 'Essayé une fois. On était seuls à rire.',
      es: 'Lo intentamos una vez. Solo nos reímos nosotros.',
    },
  },
  {
    emoji: '🌙',
    user: ACCOUNTS.sleep,
    body: {
      format: 'poll',
      question: {
        tr: 'Pijama partisi, saat 04.00. Konu:',
        en: 'Sleepover, 4 a.m. The topic:',
        de: 'Pyjamaparty, 4 Uhr morgens. Thema:',
        ar: 'حفلة مبيت، الساعة 4 فجرًا. الموضوع:',
        fr: 'Soirée pyjama, 4 h du mat. Le sujet :',
        es: 'Fiesta de pijamas, 4 de la mañana. El tema:',
      },
      options: [
        {
          tr: 'Artık uyuyalım',
          en: "Let's get some sleep",
          de: 'Lass uns schlafen',
          ar: 'لننم الآن',
          fr: 'On dort, là',
          es: 'A dormir ya',
        },
        {
          tr: 'Hayatın anlamı',
          en: 'The meaning of life',
          de: 'Der Sinn des Lebens',
          ar: 'معنى الحياة',
          fr: 'Le sens de la vie',
          es: 'El sentido de la vida',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Sabah kimse cevabı hatırlamıyordu',
      en: 'By morning, nobody remembered the answer',
      de: 'Morgens wusste keiner mehr die Antwort',
      ar: 'في الصباح، لم يتذكر أحد الجواب',
      fr: 'Au réveil, personne se rappelait la réponse',
      es: 'Por la mañana nadie recordaba la respuesta',
    },
  },
  {
    emoji: '🙋',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Grupta “cumartesi kim müsait?” yazıldı. Sen:',
        en: "Group chat: “Who's free Saturday?” You:",
        de: 'Gruppenchat: „Wer hat Samstag Zeit?“ Du:',
        ar: 'في المجموعة: «من متفرغ يوم السبت؟» ماذا تفعل؟',
        fr: 'Le groupe : « Qui est dispo samedi ? » Toi :',
        es: 'En el grupo: “¿Quién puede el sábado?” Tú:',
      },
      options: [
        {
          tr: 'Hemen “ben!” derim',
          en: '“Me!” right away',
          de: 'Sofort „Ich!“',
          ar: '«أنا!» فورًا',
          fr: '« Moi ! » direct',
          es: '“¡Yo!” al instante',
        },
        {
          tr: 'Önce kimler var?',
          en: "Wait to see who's in",
          de: 'Erst mal: Wer kommt?',
          ar: 'أنتظر لأرى من سيأتي',
          fr: 'Je vois qui vient',
          es: 'Veo quién va primero',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Müsaitliğim katılımcı listesine bağlı',
      en: 'My availability depends on the guest list',
      de: 'Meine Zeit hängt von der Gästeliste ab',
      ar: 'تفرّغي يعتمد على قائمة الحضور',
      fr: 'Mes dispos dépendent de la liste des invités',
      es: 'Mi disponibilidad depende de quién vaya',
    },
  },
  // chart
  {
    emoji: '📉',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: '“GELİYORUM” DİYENLER',
        en: "PEOPLE WHO SAID “I'M IN”",
        de: 'ZUSAGEN FÜR SAMSTAG',
        ar: 'من قالوا «سآتي»',
        fr: 'NOMBRE DE « JE VIENS »',
        es: 'LOS QUE DIJERON “VOY”',
      },
      value: {
        tr: '-%92',
        en: '-92%',
        de: '-92 %',
        ar: '-92%',
        fr: '-92 %',
        es: '-92 %',
      },
      shape: 'crash',
      axis: 'days',
    },
    caption: {
      tr: 'Etkinlik günü herkesin bir işi çıktı',
      en: 'On the day, everyone suddenly got busy',
      de: 'Am Tag selbst hatten plötzlich alle was vor',
      ar: 'في يوم الموعد، صار لدى الجميع انشغال مفاجئ',
      fr: 'Le jour J, tout le monde avait un empêchement',
      es: 'El día del plan, a todos les surgió algo',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'LİSE GRUBU MESAJLARI',
        en: 'HIGH SCHOOL GROUP CHAT',
        de: 'ALTER KLASSENCHAT',
        ar: 'رسائل مجموعة الثانوية',
        fr: 'GROUPE DU LYCÉE',
        es: 'CHAT DEL COLEGIO',
      },
      value: {
        tr: '+%4.000',
        en: '+4,000%',
        de: '+4.000 %',
        ar: '+4,000%',
        fr: '+4 000 %',
        es: '+4000 %',
      },
      shape: 'spike',
      axis: 'months',
    },
    caption: {
      tr: 'Biri 12 yıl önceki bir fotoğrafı attı',
      en: 'Someone posted a photo from 12 years ago',
      de: 'Jemand hat ein Foto von vor 12 Jahren geschickt',
      ar: 'أرسل أحدهم صورة تعود إلى 12 عامًا',
      fr: "Quelqu'un a posté une photo d'il y a 12 ans",
      es: 'Alguien mandó una foto de hace 12 años',
    },
  },
  // receipt
  {
    emoji: '🍿',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'SİNEMA BÜFESİ',
        en: 'MOVIE SNACK BAR',
        de: 'KINO-SNACKBAR',
        ar: 'مقصف السينما',
        fr: 'CONFISERIE DU CINÉ',
        es: 'CAFETERÍA DEL CINE',
      },
      items: [
        {
          tr: 'MISIR (PAYLAŞIMLIK)',
          en: 'POPCORN (SHARING SIZE)',
          de: 'POPCORN (ZUM TEILEN)',
          ar: 'فشار (حجم للمشاركة)',
          fr: 'POP-CORN (À PARTAGER)',
          es: 'PALOMITAS PARA 2',
        },
      ],
    },
    caption: {
      tr: 'Paylaşacaktık. Fragmanlar bitmeden bitti.',
      en: 'We were going to share. Gone before the trailers ended.',
      de: 'Wir wollten teilen. Vor der Werbung war es leer.',
      ar: 'كنا سنتقاسمه… فانتهى قبل الإعلانات',
      fr: 'On devait partager. Fini avant les bandes-annonces.',
      es: 'Íbamos a compartir. Se acabó antes de los tráileres.',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.shopping,
    body: {
      format: 'receipt',
      store: {
        tr: 'ÇORAPÇI',
        en: 'SOCK SHOP',
        de: 'STRUMPFLADEN',
        ar: 'متجر الجوارب',
        fr: 'BONNETERIE',
        es: 'CALCETERÍA',
      },
      items: [
        {
          tr: 'ÇORAP (HEDİYE PAKETİ)',
          en: 'SOCKS (GIFT-WRAPPED)',
          de: 'SOCKEN (ALS GESCHENK)',
          ar: 'جوارب (مغلّفة كهدية)',
          fr: 'CHAUSSETTES (CADEAU)',
          es: 'CALCETINES (REGALO)',
        },
      ],
    },
    caption: {
      tr: 'Hediyeyi 3 hafta düşündüm. Sonuç: çorap.',
      en: 'Thought about the gift for 3 weeks. Result: socks.',
      de: '3 Wochen übers Geschenk gegrübelt. Ergebnis: Socken.',
      ar: 'فكرت في الهدية 3 أسابيع… والنتيجة: جوارب',
      fr: '3 semaines à chercher un cadeau. Résultat : chaussettes.',
      es: '3 semanas pensando el regalo. Resultado: calcetines.',
    },
  },
  // fact
  {
    emoji: '📆',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '0', en: '0', de: '0', ar: '0', fr: '0', es: '0' },
      text: {
        tr: 'kez “bir ara buluşalım” dediğin biriyle gerçekten buluştun',
        en: "times you actually met up after “let's catch up sometime”",
        de: 'Mal wurde aus „Lass uns mal treffen“ ein echtes Treffen',
        ar: 'مرة تحوّل فيها «لنلتقِ في وقت ما» إلى لقاء حقيقي',
        fr: 'fois où « on se voit un de ces quatre » a vraiment eu lieu',
        es: 'veces que el “a ver cuándo nos vemos” se cumplió',
      },
    },
    caption: {
      tr: '“Bir ara” takvimde yok',
      en: "“Sometime” isn't on any calendar",
      de: '„Mal“ steht in keinem Kalender',
      ar: '«في وقت ما» ليس موجودًا في أي تقويم',
      fr: '« Un de ces quatre », ça existe pas',
      es: 'El “a ver cuándo” nunca llega',
    },
  },
  {
    emoji: '📍',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'GRUP SOHBETİ RAPORU',
        en: 'GROUP CHAT REPORT',
        de: 'GRUPPENCHAT-BERICHT',
        ar: 'تقرير المجموعة',
        fr: 'RAPPORT DU GROUPE',
        es: 'INFORME DEL GRUPO',
      },
      big: { tr: '112', en: '112', de: '112', ar: '112', fr: '112', es: '112' },
      text: {
        tr: 'mesaj “nereye gidelim?” üstüne. Karar: her zamanki yer',
        en: 'messages about “where should we go?” Verdict: the usual place',
        de: 'Nachrichten zu „Wohin gehen wir?“ Ergebnis: wie immer',
        ar: 'رسالة حول «إلى أين نذهب؟»، والقرار: المكان المعتاد',
        fr: "messages sur « on va où ? » Verdict : comme d'hab",
        es: 'mensajes sobre “¿a dónde vamos?”. Veredicto: al de siempre',
      },
    },
    caption: {
      tr: 'Masamız zaten hazırdı',
      en: 'Our table was already waiting',
      de: 'Unser Tisch war schon gedeckt',
      ar: 'طاولتنا كانت جاهزة أصلًا',
      fr: 'Notre table nous attendait déjà',
      es: 'Nuestra mesa ya nos esperaba',
    },
  },
  {
    emoji: '🐉',
    user: ACCOUNTS.vlog,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'ESKİ DOSTLAR BULUŞTU',
        en: 'THE OLD CREW REUNITES',
        de: 'WIEDERSEHEN DER CLIQUE',
        ar: 'لقاء الأصدقاء القدامى',
        fr: 'LA BANDE SE RETROUVE',
        es: 'REENCUENTRO DE AMIGOS',
      },
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'kez aynı anıyı anlattınız; her seferinde biraz daha büyüdü',
        en: 'times you all told the same story. It got bigger every time.',
        de: 'Mal dieselbe Geschichte erzählt. Jedes Mal wurde sie größer.',
        ar: 'مرات رويتم القصة نفسها، وفي كل مرة كبرت أكثر',
        fr: 'fois la même anecdote ce soir. Elle grossit à chaque fois.',
        es: 'veces contaron la misma anécdota. Cada vez fue más épica.',
      },
    },
    caption: {
      tr: 'Dördüncüde bir ejderha vardı',
      en: 'By round four, there was a dragon',
      de: 'Beim vierten Mal kam ein Drache vor',
      ar: 'في المرة الرابعة ظهر فيها تنين',
      fr: 'À la quatrième, il y avait un dragon',
      es: 'A la cuarta ya había un dragón',
    },
  },
  // tier
  {
    emoji: '🚗',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ARKADAŞ GRUBU TIER LIST',
        en: 'FRIEND GROUP TIER LIST',
        de: 'FREUNDESKREIS-RANKING',
        ar: 'تصنيف الأصدقاء',
        fr: 'TIER LIST DES POTES',
        es: 'TIER LIST DE AMIGOS',
      },
      rows: [['🚗'], ['🔋', '🍕', '📸'], ['🗓️', '🎧'], ['⏰']],
    },
    caption: {
      tr: 'Arabası olan arkadaş tartışmasız S',
      en: 'The friend with a car is S tier. No debate.',
      de: 'Wer ein Auto hat, ist S. Keine Diskussion.',
      ar: 'صاحب السيارة في القمة بلا نقاش',
      fr: "Le pote qui a une voiture, c'est S d'office",
      es: 'El amigo con auto va en la S, sin discusión',
    },
  },
  {
    emoji: '🎬',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'FİLM GECESİ TIER LIST',
        en: 'MOVIE NIGHT TIER LIST',
        de: 'FILMABEND-RANKING',
        ar: 'تصنيف ليلة الأفلام',
        fr: 'TIER LIST SOIRÉE FILM',
        es: 'TIER LIST NOCHE DE PELIS',
      },
      rows: [['🍿', '🤫'], ['😭', '🛋️'], ['😴'], ['🗣️', '📱']],
    },
    caption: {
      tr: 'Filmi durdurup “ne oldu?” diyen: C',
      en: 'The one who pauses to ask “what happened?”: C',
      de: 'Wer pausiert und fragt „Was ist passiert?“: C',
      ar: 'من يوقف الفيلم ليسأل «ماذا حدث؟» في ذيل القائمة',
      fr: "Mettre pause pour demander « il s'est passé quoi ? » : C",
      es: 'Pausar para preguntar “¿qué pasó?”: C',
    },
  },
  // notifications
  {
    emoji: '🤳',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🖼️',
        app: {
          tr: 'Kanka',
          en: 'Bestie',
          de: 'Beste Freundin',
          ar: 'صديقتي',
          fr: 'Ma meilleure amie',
          es: 'Mi mejor amiga',
        },
        text: {
          tr: 'Seninle 147 fotoğraf paylaştı',
          en: 'Shared 147 photos with you',
          de: 'Hat 147 Fotos mit dir geteilt',
          ar: 'شاركت معك 147 صورة',
          fr: 'A partagé 147 photos avec toi',
          es: 'Compartió 147 fotos contigo',
        },
      },
    },
    caption: {
      tr: 'Birinde ben de varım: dirseğim',
      en: "I'm in one of them: my elbow",
      de: 'Auf einem bin ich drauf: mein Ellbogen',
      ar: 'أظهر في واحدة منها: مرفقي',
      fr: 'Je suis sur une : mon coude',
      es: 'Salgo en una: mi codo',
    },
  },
  {
    emoji: '📋',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🎂',
        app: {
          tr: 'Doğum günleri',
          en: 'Birthdays',
          de: 'Geburtstage',
          ar: 'أعياد الميلاد',
          fr: 'Anniversaires',
          es: 'Cumpleaños',
        },
        text: {
          tr: 'Bugün 3 arkadaşının doğum günü',
          en: '3 friends have birthdays today',
          de: 'Heute haben 3 Freunde Geburtstag',
          ar: 'اليوم عيد ميلاد 3 من أصدقائك',
          fr: "C'est l'anniversaire de 3 amis",
          es: 'Hoy cumplen años 3 amigos',
        },
      },
    },
    caption: {
      tr: 'Aynı mesajı attım. İsmi değiştirmeyi unuttum.',
      en: 'Sent all three the same text. Forgot to change the name.',
      de: 'Allen dieselbe Nachricht. Den Namen nicht geändert.',
      ar: 'أرسلت الرسالة نفسها للثلاثة… ونسيت تغيير الاسم',
      fr: 'Même message aux trois. Sans changer le prénom.',
      es: 'Mismo mensaje a los tres. Sin cambiar el nombre.',
    },
  },
  // quote
  {
    emoji: '🛋️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Gerçek dostluk, yan yana sessizce telefona bakabilmektir.',
        en: 'True friendship is scrolling side by side without a word.',
        de: 'Wahre Freundschaft heißt: nebeneinander scrollen, ohne ein Wort.',
        ar: 'الصداقة الحقيقية أن تتصفحا هاتفيكما جنبًا إلى جنب في صمت.',
        fr: "La vraie amitié, c'est scroller côte à côte sans un mot.",
        es: 'La verdadera amistad es ver el teléfono juntos sin decir nada.',
      },
    },
    caption: {
      tr: '3 saat buluştuk, 2 kelime konuştuk',
      en: 'Hung out for 3 hours. Said 2 words.',
      de: '3 Stunden zusammen, 2 Wörter gesagt',
      ar: 'التقينا 3 ساعات وتبادلنا كلمتين',
      fr: '3 heures ensemble, 2 mots échangés',
      es: '3 horas juntos, 2 palabras',
    },
  },
  {
    emoji: '🍟',
    user: ACCOUNTS.food,
    body: {
      format: 'quote',
      text: {
        tr: 'Paylaşmak güzeldir. — Tabağımdan patates alan arkadaşım',
        en: 'Sharing is caring. — My friend, eating fries off my plate',
        de: 'Teilen ist schön. — Meine Freundin, an meinen Pommes',
        ar: 'المشاركة جميلة. — صديقي وهو يأكل من بطاطسي',
        fr: "Partager, c'est beau. — Mon pote, qui pique dans mes frites",
        es: 'Compartir es bonito. — Mi amigo, comiendo de mis papas',
      },
    },
    caption: {
      tr: '“Aç değilim” demişti',
      en: "She said she wasn't hungry",
      de: 'Sie hatte angeblich keinen Hunger',
      ar: 'قال إنه ليس جائعًا',
      fr: "Il avait dit qu'il avait pas faim",
      es: 'Dijo que no tenía hambre',
    },
  },
  {
    emoji: '💚',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Kalbinin sesini dinle. — Her çılgın fikrime evet diyen arkadaşım',
        en: 'Follow your heart. — My friend, who says yes to all my wild ideas',
        de: 'Hör auf dein Herz. — Meine Freundin, die jede verrückte Idee gut findet',
        ar: 'استمع إلى قلبك. — صديقي الذي يوافق على كل أفكاري المجنونة',
        fr: 'Écoute ton cœur. — Mon pote, qui dit oui à toutes mes idées folles',
        es: 'Sigue a tu corazón. — Mi amiga, que dice que sí a todas mis locuras',
      },
    },
    caption: {
      tr: 'Yeşil saçlarım bunun kanıtı',
      en: 'My green hair is proof',
      de: 'Meine grünen Haare beweisen es',
      ar: 'شعري الأخضر خير دليل',
      fr: 'Mes cheveux verts en sont la preuve',
      es: 'Mi pelo verde lo demuestra',
    },
  },
  {
    emoji: '🔁',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Dostluk kaldığı yerden sürer. — 10 yıl sonra aynı tartışmaya dönen biz',
        en: 'Friends pick up where they left off. — Us, same argument, 10 years on',
        de: 'Freunde machen einfach weiter. — Wir, gleicher Streit, 10 Jahre später',
        ar: 'الأصدقاء يكملون من حيث توقفوا. — نحن، والنقاش نفسه بعد 10 سنوات',
        fr: 'Les amis reprennent où ils en étaient. — Nous, même débat, 10 ans après',
        es: 'La amistad sigue donde quedó. — Nosotros, mismo debate tras 10 años',
      },
    },
    caption: {
      tr: 'Konu: kim haklıydı. Hâlâ çözülmedi.',
      en: 'Topic: who was right. Still unresolved.',
      de: 'Thema: Wer hatte recht? Weiter offen.',
      ar: 'الموضوع: من كان محقًا؟ لم يُحسم بعد.',
      fr: 'Sujet : qui avait raison. Toujours pas tranché.',
      es: 'Tema: quién tenía razón. Sigue sin resolverse.',
    },
  },
  {
    emoji: '🙃',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'İletişim her şeydir. — 400 mesajı okumadan ne oldu diye soran ben',
        en: 'Communication is key. — Me, 400 unread: what did I miss?',
        de: 'Kommunikation ist alles. — Ich, 400 ungelesen: Was hab ich verpasst?',
        ar: 'التواصل هو كل شيء. — أنا، ولديّ 400 رسالة غير مقروءة: ماذا فاتني؟',
        fr: "Tout est dans la communication. — Moi, 400 non-lus : j'ai raté quoi ?",
        es: 'La comunicación lo es todo. — Yo, con 400 sin leer: ¿qué me perdí?',
      },
    },
    caption: {
      tr: 'Cevap geldi: “yukarı kaydır”',
      en: 'The reply: “scroll up”',
      de: 'Antwort: „Scroll hoch“',
      ar: 'جاء الرد: «اقرأ في الأعلى»',
      fr: 'Réponse : « remonte »',
      es: 'Respuesta: “lee arriba”',
    },
  },
];

export const FRIENDS_LIKE: readonly Draft[] = [
  // scene
  {
    emoji: '🫂',
    user: ACCOUNTS.zeynep,
    body: { format: 'scene' },
    caption: {
      tr: '20 yıllık kankam. ilk sözü: “kalemin var mı?”',
      en: '20 years of friendship. her first words: “got a pen?”',
      de: '20 jahre freundschaft. ihr erster satz: „hast du nen stift?“',
      ar: '20 عامًا من الصداقة، وأول ما قالته لي: «معك قلم؟»',
      fr: "20 ans d'amitié. ses premiers mots : « t'as un stylo ? »",
      es: '20 años de amigas. su primera frase: “¿tienes lápiz?”',
    },
  },
  {
    emoji: '🥳',
    user: ACCOUNTS.berk,
    body: { format: 'scene' },
    caption: {
      tr: 'sürpriz parti: 12 kişi, 3 hafta, 0 ifşa!!',
      en: 'surprise party: 12 people, 3 weeks, 0 leaks!!',
      de: 'überraschungsparty: 12 leute, 3 wochen, 0 verplappert!!',
      ar: 'حفلة مفاجئة: 12 شخصًا، 3 أسابيع، ولا تسريب واحد!!',
      fr: 'fête surprise : 12 personnes, 3 semaines, 0 fuite !!',
      es: '¡¡fiesta sorpresa: 12 personas, 3 semanas, 0 filtraciones!!',
    },
  },
  {
    emoji: '🤝',
    user: ACCOUNTS.naz,
    body: { format: 'scene' },
    caption: {
      tr: 'yetişkinken arkadaş bulmak zormuş. buldum!!',
      en: 'making friends as an adult is hard. i made one!!',
      de: 'als erwachsene freunde finden ist schwer. geschafft!!',
      ar: 'تكوين الصداقات في الكبر صعب… لكنني وجدت صديقة!!',
      fr: "se faire des amis à l'âge adulte, c'est dur. réussi !!",
      es: 'hacer amigos de adulta es difícil. ¡¡lo logré!!',
    },
  },
  {
    emoji: '👯',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'kankamla aynı gün aynı kazağı almışız, habersiz',
      en: 'my bestie and i bought the same sweater. same day. no plan.',
      de: 'meine beste und ich: gleicher pulli, gleicher tag, zufall',
      ar: 'أنا وصديقتي اشترينا الكنزة نفسها في اليوم نفسه، دون اتفاق',
      fr: 'ma meilleure amie et moi : même pull, même jour, pur hasard',
      es: 'mi mejor amiga y yo: mismo suéter, mismo día, sin avisarnos',
    },
  },
  // polaroid
  {
    emoji: '📷',
    user: ACCOUNTS.deniz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'nadir görüntü: ben',
        en: 'rare footage: me',
        de: 'seltene aufnahme: ich',
        ar: 'لقطة نادرة: أنا',
        fr: 'image rare : moi',
        es: 'imagen rara: yo',
      },
    },
    caption: {
      tr: 'grubun fotoğrafçısıyım, bu yıl ilk kez karedeyim',
      en: 'group photographer here. first photo of me this year',
      de: 'die fotografin der clique, dieses jahr zum ersten mal drauf',
      ar: 'مصوّرة الشلّة… وهذه أول صورة لي هذا العام',
      fr: 'la photographe du groupe, enfin sur une photo cette année',
      es: 'soy la fotógrafa del grupo y por fin salgo en una',
    },
  },
  {
    emoji: '🧵',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'arkadaşlık bilekliği',
        en: 'friendship bracelets',
        de: 'freundschaftsbänder',
        ar: 'أساور الصداقة',
        fr: "bracelets d'amitié",
        es: 'pulseras de la amistad',
      },
    },
    caption: {
      tr: 'bileklik yaptık, benimki yüzük boyunda oldu',
      en: 'we made bracelets. mine came out ring-sized',
      de: 'wir haben armbänder geknüpft, meins passt als ring',
      ar: 'صنعنا أساور… وخرجت أسورتي بحجم خاتم',
      fr: "on a fait des bracelets, le mien a la taille d'une bague",
      es: 'hicimos pulseras y la mía quedó del tamaño de un anillo',
    },
  },
  {
    emoji: '🔏',
    user: ACCOUNTS.ece,
    body: {
      format: 'polaroid',
      note: {
        tr: '8 yaşındaki biz',
        en: 'us, age 8',
        de: 'wir mit 8',
        ar: 'نحن في الثامنة',
        fr: 'nous, à 8 ans',
        es: 'nosotras a los 8',
      },
    },
    caption: {
      tr: 'eski gizli mektuplarımızı bulduk. şifreyi unutmuşuz',
      en: 'found our old secret letters. we forgot the code',
      de: 'unsere alten geheimbriefe gefunden. code vergessen',
      ar: 'وجدنا رسائلنا السرية القديمة… ونسينا الشيفرة',
      fr: 'on a retrouvé nos lettres secrètes. oublié le code',
      es: 'encontramos nuestras cartas secretas. olvidamos la clave',
    },
  },
  {
    emoji: '🕛',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'saat tam 00.00',
        en: 'midnight sharp',
        de: 'punkt mitternacht',
        ar: 'منتصف الليل تمامًا',
        fr: 'minuit pile',
        es: 'medianoche en punto',
      },
    },
    caption: {
      tr: 'kankamı ilk ben kutlayayım diye kapısındaydım',
      en: "was at my buddy's door to be his first happy birthday",
      de: 'vor der tür meines kumpels, um als erster zu gratulieren',
      ar: 'كنت عند باب صديقي لأكون أول من يهنّئه بعيد ميلاده',
      fr: 'devant chez mon pote pour être le premier à le fêter',
      es: 'en la puerta de mi amigo para ser el primero en felicitarlo',
    },
  },
  // dump
  {
    emoji: '🧸',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['🧸', '🛌', '🍫', '🌙', '💅'] },
    caption: {
      tr: 'pijama partisi dump’ı: 30 yaşındayız, kimseye söylemeyin',
      en: "sleepover dump: we're 30, don't tell anyone",
      de: 'pyjamaparty-dump: wir sind 30, nicht weitersagen',
      ar: 'حفلة مبيت: عمرنا 30 عامًا، لا تخبروا أحدًا',
      fr: 'soirée pyjama : on a 30 ans, chut',
      es: 'fiesta de pijamas: tenemos 30 años, no le digan a nadie',
    },
  },
  {
    emoji: '👻',
    user: ACCOUNTS.kaan,
    body: { format: 'dump', emojis: ['👻', '🙈', '📺', '😱', '🧣'] },
    caption: {
      tr: 'film gecesi: korku filmi seçtik, 4 kişi tek battaniyede',
      en: 'movie night: we picked horror. 4 of us, 1 blanket',
      de: 'filmabend: horrorfilm. 4 leute, 1 decke',
      ar: 'ليلة أفلام: اخترنا فيلم رعب… 4 أشخاص تحت بطانية واحدة',
      fr: "soirée film : film d'horreur, 4 sous 1 plaid",
      es: 'noche de pelis: de terror. 4 personas, 1 manta',
    },
  },
  {
    emoji: '🕙',
    user: ACCOUNTS.onur,
    body: { format: 'dump', emojis: ['🫂', '🍰', '😂', '🕙', '🏫'] },
    caption: {
      tr: 'lise tayfası 10 yıl sonra: aynıyız, sadece 22.00’de evdeyiz',
      en: 'high school crew, 10 years on: same us, home by 10 p.m.',
      de: 'schul-clique nach 10 jahren: alles gleich, um 22 uhr daheim',
      ar: 'شلة الثانوية بعد 10 سنوات: كما نحن، لكن في البيت قبل العاشرة',
      fr: 'la bande du lycée 10 ans après : pareil, mais au lit à 22 h',
      es: 'los del colegio 10 años después: iguales, en casa a las 10',
    },
  },
  {
    emoji: '☕',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['☕', '🌳', '🧁', '🚶', '🌆'] },
    caption: {
      tr: 'kankamla buluşma: 3 kafe, 2 park, 9 saat, konu bitmedi',
      en: 'bestie day: 3 cafés, 2 parks, 9 hours, still talking',
      de: 'mit meiner besten: 3 cafés, 2 parks, 9 stunden gequatscht',
      ar: 'يوم مع صديقتي: 3 مقاهٍ، وحديقتان، و9 ساعات… والكلام لم ينتهِ',
      fr: 'journée entre copines : 3 cafés, 2 parcs, 9 h de papotage',
      es: 'con mi mejor amiga: 3 cafés, 2 parques, 9 horas de charla',
    },
  },
];

export const FRIENDS_HOLD: readonly Draft[] = [
  {
    emoji: '🗓️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsane: gruptaki 6 kişi aynı gün müsait',
      en: 'Legendary: all 6 friends free on the same day',
      de: 'Legendär: Alle 6 haben am selben Tag Zeit',
      ar: 'حدث أسطوري: الستة متفرغون في اليوم نفسه',
      fr: 'Légendaire : les 6 potes libres le même jour',
      es: 'Legendario: los 6 del grupo libres el mismo día',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kanka aradı. Sadece “nasılsın” demek için.',
      en: 'Your bestie called. Just to ask how you are.',
      de: 'Dein bester Freund ruft an. Einfach so.',
      ar: 'صديقك اتصل… فقط ليطمئن عليك',
      fr: 'Ton meilleur pote appelle. Juste comme ça.',
      es: 'Tu mejor amigo llamó. Solo para saludar.',
    },
  },
  {
    emoji: '☂️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ödünç şemsiye sahibine döndü. Tarihî an.',
      en: 'A lent umbrella came home. Historic.',
      de: 'Verliehener Schirm ist zurück. Historisch.',
      ar: 'المظلة المُعارة عادت إلى صاحبها. لحظة تاريخية',
      fr: 'Le parapluie prêté est revenu. Historique.',
      es: 'El paraguas prestado volvió. Histórico.',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Grup fotoğrafı: herkesin gözü açık. İlk kez!',
      en: "Group photo: everyone's eyes open. A first!",
      de: 'Gruppenfoto: alle Augen offen. Premiere!',
      ar: 'صورة جماعية والجميع بعيون مفتوحة. لأول مرة!',
      fr: 'Photo de groupe : tous les yeux ouverts. Une première !',
      es: 'Foto grupal: todos con los ojos abiertos. ¡Por fin!',
    },
  },
  {
    emoji: '🎞️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Film gecesi: ilk teklifte herkes anlaştı!',
      en: 'Movie night: everyone agreed on the first pick!',
      de: 'Filmabend: Alle waren sofort einverstanden!',
      ar: 'ليلة أفلام: اتفق الجميع على أول اقتراح!',
      fr: "Soirée film : tout le monde d'accord du premier coup !",
      es: 'Noche de pelis: ¡todos de acuerdo a la primera!',
    },
  },
  {
    emoji: '🤐',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir eşya: gerçekten saklanmış bir sır',
      en: 'Rare item: a secret that actually stayed secret',
      de: 'Seltenes Item: ein Geheimnis, das geheim blieb',
      ar: 'غرض نادر: سرّ بقي سرًّا فعلًا',
      fr: 'Objet rare : un secret vraiment gardé',
      es: 'Objeto raro: un secreto que sí se guardó',
    },
  },
  {
    emoji: '🕯️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Mumlar yanıyor: dilek tut, tam vaktinde üfle!',
      en: 'Candles lit: make a wish, blow right on time!',
      de: 'Kerzen brennen: Wunsch denken, genau jetzt pusten!',
      ar: 'الشموع مضاءة: تمنَّ أمنية وانفخ في اللحظة المناسبة!',
      fr: 'Bougies allumées : un vœu, et souffle pile à temps !',
      es: 'Velas encendidas: ¡pide un deseo y sopla justo a tiempo!',
    },
  },
  {
    emoji: '🎉',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Işıklar kapalı, herkes saklandı… bırak: SÜRPRİZ!',
      en: "Lights off, everyone's hiding… let go: SURPRISE!",
      de: 'Licht aus, alle versteckt… loslassen: ÜBERRASCHUNG!',
      ar: 'الأضواء مطفأة والجميع مختبئ… اترك الآن: مفاجأة!',
      fr: 'Lumières éteintes, tous cachés… lâche : SURPRISE !',
      es: 'Luces apagadas, todos escondidos… suelta: ¡SORPRESA!',
    },
  },
];

export const FRIENDS_FREEZE: readonly Draft[] = [
  // sign
  {
    emoji: '🗿',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'MÜZİK DURDU',
        en: 'MUSIC STOPPED',
        de: 'MUSIK AUS',
        ar: 'توقفت الموسيقى',
        fr: 'MUSIQUE STOP',
        es: '¡ESTATUAS!',
      },
      small: {
        tr: 'HERKES HEYKEL OLSUN',
        en: 'EVERYBODY FREEZE',
        de: 'ALLE WERDEN ZU STATUEN',
        ar: 'كونوا تماثيل',
        fr: 'TOUT LE MONDE EN STATUE',
        es: 'SE ACABÓ LA MÚSICA',
      },
    },
    caption: {
      tr: 'Kıpırdayan elenir.',
      en: "Move and you're out.",
      de: 'Wer wackelt, fliegt raus.',
      ar: 'من يتحرك يخرج من اللعبة.',
      fr: "Un geste et t'es éliminé.",
      es: 'El que se mueve, pierde.',
    },
    headline: {
      tr: 'Doğum günü partisinde heykel oyunu',
      en: 'Musical statues at the birthday party',
      de: 'Stopptanz auf der Geburtstagsparty',
      ar: 'لعبة التماثيل في حفلة عيد الميلاد',
      fr: "Jeu des statues à l'anniversaire",
      es: 'Estatuas musicales en el cumpleaños',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SIRA KİMDE?',
        en: "WHO'S NEXT?",
        de: 'WER IST DRAN?',
        ar: 'من التالي؟',
        fr: 'AU SUIVANT !',
        es: '¿QUIÉN SIGUE?',
      },
      small: {
        tr: 'MİKROFON SAHİPSİZ',
        en: 'THE MIC IS UP FOR GRABS',
        de: 'DAS MIKRO IST FREI',
        ar: 'الميكروفون بلا صاحب',
        fr: 'LE MICRO EST LIBRE',
        es: 'MICRÓFONO LIBRE',
      },
    },
    caption: {
      tr: 'Göz göze gelen söyler.',
      en: "Make eye contact and you're singing.",
      de: 'Wer Blickkontakt hat, singt.',
      ar: 'من تلتقي عيناه بعيونهم يغنّي.',
      fr: 'Croise un regard et tu chantes.',
      es: 'Si cruzas miradas, cantas tú.',
    },
    headline: {
      tr: 'Karaokede mikrofon ortada kaldı',
      en: 'Karaoke night: nobody has the mic',
      de: 'Karaoke: Keiner hat das Mikro',
      ar: 'ليلة كاريوكي: لا أحد يمسك الميكروفون',
      fr: 'Karaoké : personne ne tient le micro',
      es: 'Karaoke: nadie tiene el micrófono',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'KAYDIRMA',
        en: 'NO SWIPING',
        de: 'NICHT WISCHEN',
        ar: 'لا تمرّر',
        fr: 'PAS DE SWIPE',
        es: 'NO DESLICES',
      },
      small: {
        tr: 'BAŞKASININ GALERİSİ',
        en: "SOMEONE ELSE'S GALLERY",
        de: 'FREMDE FOTOGALERIE',
        ar: 'معرض صور شخص آخر',
        fr: "LA GALERIE D'UN AUTRE",
        es: 'GALERÍA AJENA',
      },
    },
    caption: {
      tr: 'Galeriye göz atma bile.',
      en: "Don't even peek at the gallery.",
      de: 'Nicht mal in die Galerie linsen.',
      ar: 'ولا حتى نظرة إلى معرض الصور.',
      fr: "Même pas un coup d'œil à la galerie.",
      es: 'Ni una mirada a la galería.',
    },
    headline: {
      tr: 'Kanka fotoğraf için telefonunu verdi',
      en: 'Your bestie hands you her phone',
      de: 'Freundin gibt dir ihr Handy fürs Foto',
      ar: 'صديقتك أعطتك هاتفها لتلتقط صورة',
      fr: 'Ta pote te passe son tel pour une photo',
      es: 'Tu amiga te da su teléfono para una foto',
    },
  },
  // cctv
  {
    emoji: '😬',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
      },
    },
    caption: {
      tr: 'Nefes bile alma.',
      en: "Don't even breathe.",
      de: 'Nicht mal atmen.',
      ar: 'لا تتنفس حتى.',
      fr: 'Ne respire même pas.',
      es: 'Ni respires.',
    },
    headline: {
      tr: 'Kanka 500 domino dizdi, son taşı koyuyor',
      en: "Your friend's placing domino 500",
      de: 'Dein Kumpel setzt Dominostein Nr. 500',
      ar: 'صديقك يضع قطعة الدومينو رقم 500',
      fr: 'Ton pote pose le 500e domino',
      es: 'Tu amigo coloca la ficha de dominó 500',
    },
  },
  {
    emoji: '🎥',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة الجلوس',
        fr: 'SALON',
        es: 'SALA',
      },
    },
    caption: {
      tr: 'Etkilenmiş görün. Kıpırdama.',
      en: "Look impressed. Don't move.",
      de: 'Beeindruckt gucken. Nicht bewegen.',
      ar: 'تظاهر بالإعجاب. لا تتحرك.',
      fr: "Aie l'air ému. Bouge pas.",
      es: 'Pon cara de impresionado. No te muevas.',
    },
    headline: {
      tr: 'Kankanın en sevdiği film. Seni izliyor.',
      en: "Buddy's fave movie. He's watching you.",
      de: 'Kumpels Lieblingsfilm: Er guckt dich an',
      ar: 'فيلم صديقك المفضل… وهو يراقب وجهك',
      fr: 'Film culte de ton pote. Il te regarde.',
      es: 'La peli favorita de tu amigo. Te mira.',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KANEPE',
        en: 'COUCH',
        de: 'SOFA',
        ar: 'الأريكة',
        fr: 'CANAPÉ',
        es: 'SOFÁ',
      },
    },
    caption: {
      tr: 'Kolun uyuşsa bile kıpırdama.',
      en: "Arm's gone numb? Don't move.",
      de: 'Arm eingeschlafen? Nicht rühren.',
      ar: 'تنمّل ذراعك؟ لا تتحرك.',
      fr: 'Bras engourdi ? Bouge pas.',
      es: '¿Se te durmió el brazo? No te muevas.',
    },
    headline: {
      tr: 'Kanka omzunda uyuyakaldı',
      en: 'Your buddy fell asleep on your shoulder',
      de: 'Dein Kumpel pennt an deiner Schulter',
      ar: 'صديقك نام على كتفك',
      fr: "Ton pote s'est endormi sur ton épaule",
      es: 'Tu amigo se durmió en tu hombro',
    },
  },
];
