import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Sport, hobbies and games: the gym, running, football, board and video games, music, crafts.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const HOBBIES_SKIP: readonly Draft[] = [
  {
    emoji: '🏋️',
    user: ACCOUNTS.sport,
    body: { format: 'scene' },
    caption: {
      tr: 'Üyelik yıllık, motivasyon aylıkmış',
      en: 'Signed up for a year. Motivated for a month.',
      de: 'Ein Jahr Abo, ein Monat Motivation',
      ar: 'اشتركت لمدة سنة، وتحمّست لمدة شهر',
      fr: 'Abonné pour un an, motivé pour un mois',
      es: 'Inscrito por un año, motivado por un mes',
    },
  },
  {
    emoji: '🚲',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Kondisyon bisikletinde 20 km gittim. Hâlâ salondayım.',
      en: 'Rode 20 km on the exercise bike. Still in the living room.',
      de: '20 km auf dem Heimtrainer. Immer noch im Wohnzimmer.',
      ar: 'قطعت 20 كم على دراجة التمارين… وما زلت في الصالة',
      fr: "20 km sur le vélo d'appart. Toujours dans le salon.",
      es: '20 km en la bici estática. Sigo en la sala.',
    },
  },
  {
    emoji: '📺',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Golü önce komşudan duydum, sonra gördüm',
      en: 'Heard the goal next door before I saw it',
      de: 'Erst jubelt der Nachbar, dann seh ich das Tor',
      ar: 'سمعت الهدف من الجيران قبل أن أراه',
      fr: "J'ai entendu le but chez le voisin avant de le voir",
      es: 'Oí el gol en casa del vecino antes de verlo',
    },
  },
  {
    emoji: '🧘',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Yogada en iyi yaptığım poz: sondaki uzanma',
      en: 'My best yoga pose: lying down at the end',
      de: 'Meine beste Yoga-Pose: das Liegen am Schluss',
      ar: 'أفضل وضعية أتقنها في اليوغا: الاستلقاء في النهاية',
      fr: "Ma meilleure posture de yoga : celle où on s'allonge",
      es: 'Mi mejor postura de yoga: acostarme al final',
    },
  },
  {
    emoji: '🏊',
    user: ACCOUNTS.sport,
    body: { format: 'scene' },
    caption: {
      tr: '10 dakika yüzdüm, boneyi takmak 20 sürdü',
      en: 'Swam for 10 minutes. The swim cap took 20.',
      de: '10 Minuten geschwommen. Die Badekappe: 20.',
      ar: 'سبحت 10 دقائق، وارتداء قبعة السباحة استغرق 20',
      fr: "J'ai nagé 10 minutes. Le bonnet m'en a pris 20.",
      es: 'Nadé 10 minutos. Ponerme el gorro me llevó 20.',
    },
  },
  {
    emoji: '✍️',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Çizim hilesi: eller zor mu? Cebe sok.',
      en: "Drawing hack: can't draw hands? Pockets.",
      de: 'Zeichen-Hack: Hände zu schwer? Ab in die Taschen.',
      ar: 'حيلة رسم: الأيدي صعبة؟ ضعها في الجيوب.',
      fr: 'Astuce dessin : les mains, trop dures ? Dans les poches.',
      es: 'Truco de dibujo: ¿las manos, difíciles? Al bolsillo.',
    },
  },
  {
    emoji: '⚽️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Halı saha grubu',
        en: 'Pickup soccer',
        de: 'Kicken am Samstag',
        ar: 'مجموعة الكرة',
        fr: 'Foot du samedi',
        es: 'Fútbol del sábado',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'dünkü 3. gol ofsayttı bu arada',
            en: 'btw that 3rd goal yesterday was offside',
            de: 'übrigens, das 3. Tor gestern war Abseits',
            ar: 'بالمناسبة، الهدف الثالث أمس كان تسللًا',
            fr: "au fait, le 3e but d'hier était hors-jeu",
            es: 'el 3.er gol de ayer fue fuera de juego',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'kanka maç dün bitti',
            en: 'dude, the game was yesterday',
            de: 'Alter, das Spiel war gestern',
            ar: 'يا صديقي، المباراة انتهت أمس',
            fr: "mec, le match, c'était hier",
            es: 'amigo, el partido fue ayer',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'video çektim, izle',
            en: 'I filmed it, look',
            de: "hab's gefilmt, schau",
            ar: 'صوّرت اللقطة، شاهد',
            fr: "j'ai filmé, regarde",
            es: 'lo grabé, mira',
          },
        },
        {
          from: 'them',
          text: {
            tr: '11 dakikalık analiz 📹',
            en: '11-minute breakdown 📹',
            de: '11 Minuten Analyse 📹',
            ar: 'تحليل مدته 11 دقيقة 📹',
            fr: "11 minutes d'analyse 📹",
            es: 'análisis de 11 minutos 📹',
          },
        },
      ],
    },
    caption: {
      tr: 'Maç 1 saat, ofsayt tartışması 3 gün',
      en: 'Game: 1 hour. Offside debate: 3 days.',
      de: 'Spiel: 1 Stunde. Abseits-Debatte: 3 Tage.',
      ar: 'المباراة ساعة، والجدل حول التسلل 3 أيام',
      fr: 'Match : 1 heure. Débat sur le hors-jeu : 3 jours.',
      es: 'Partido: 1 hora. Debate del fuera de juego: 3 días.',
    },
  },
  {
    emoji: '🎮',
    user: ACCOUNTS.games,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yemek hazır!',
            en: "dinner's ready!",
            de: 'Essen ist fertig!',
            ar: 'الطعام جاهز!',
            fr: 'à table !',
            es: '¡la comida está lista!',
          },
        },
        {
          from: 'me',
          text: {
            tr: '5 dk geliyorum',
            en: 'coming in 5',
            de: 'komme in 5 Min.',
            ar: 'قادم بعد 5 دقائق',
            fr: "j'arrive dans 5 min",
            es: 'voy en 5 minutos',
          },
        },
        {
          from: 'them',
          text: {
            tr: '40 dakika önce de öyle dedin',
            en: 'you said that 40 minutes ago',
            de: 'das hast du vor 40 Minuten gesagt',
            ar: 'قلت هذا قبل 40 دقيقة',
            fr: 'tu disais ça il y a 40 minutes',
            es: 'eso dijiste hace 40 minutos',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'anne duraklatamıyorum, online!',
            en: "mom, I can't pause, it's online!",
            de: 'Mama, online kann man nicht pausieren!',
            ar: 'أمي، لا أستطيع الإيقاف، اللعب عبر الإنترنت!',
            fr: "maman, pas de pause, c'est en ligne !",
            es: 'mamá, no puedo pausar, ¡es en línea!',
          },
        },
      ],
    },
    caption: {
      tr: 'Online oyun anneye anlatılamaz',
      en: "You can't explain online games to mom",
      de: 'Online-Spiele kann man Mama nicht erklären',
      ar: 'اللعب عبر الإنترنت لا يُشرح للأمهات',
      fr: "Le jeu en ligne, ça s'explique pas à maman",
      es: 'Los juegos en línea no se le explican a mamá',
    },
  },
  {
    emoji: '🎲',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Oyun gecesi',
        en: 'Game night',
        de: 'Spieleabend',
        ar: 'ليلة الألعاب',
        fr: 'Soirée jeux',
        es: 'Noche de juegos',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yeni kutu oyunu aldım!!',
            en: 'got a new board game!!',
            de: 'hab ein neues Brettspiel!!',
            ar: 'اشتريت لعبة لوحية جديدة!!',
            fr: "j'ai un nouveau jeu de société !!",
            es: '¡¡compré un juego de mesa nuevo!!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'süper! kuralları uzun mu?',
            en: 'nice! are the rules long?',
            de: 'cool! sind die Regeln lang?',
            ar: 'رائع! هل قواعدها طويلة؟',
            fr: 'cool ! les règles sont longues ?',
            es: '¡genial! ¿las reglas son largas?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yok, kısacık',
            en: 'nah, super short',
            de: 'nee, ganz kurz',
            ar: 'لا، قصيرة جدًا',
            fr: 'non, super courtes',
            es: 'no, cortitas',
          },
        },
        {
          from: 'them',
          text: {
            tr: '48 sayfa',
            en: '48 pages',
            de: '48 Seiten',
            ar: '48 صفحة',
            fr: '48 pages',
            es: '48 páginas',
          },
        },
      ],
    },
    caption: {
      tr: 'Oyun gecesi değil, okuma gecesi',
      en: 'Not game night. Reading night.',
      de: 'Kein Spieleabend. Ein Leseabend.',
      ar: 'ليست ليلة ألعاب، بل ليلة قراءة',
      fr: 'Pas une soirée jeux : une soirée lecture',
      es: 'No es noche de juegos, es noche de lectura',
    },
  },
  {
    emoji: '🚴',
    user: ACCOUNTS.vlog,
    body: {
      format: 'chat',
      contact: {
        tr: 'Bisiklet grubu',
        en: 'Bike crew',
        de: 'Radgruppe',
        ar: 'مجموعة الدراجات',
        fr: 'Groupe vélo',
        es: 'Grupo de ciclismo',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'pazar 60 km tur, var mısın?',
            en: '60 km ride on sunday, you in?',
            de: 'Sonntag 60-km-Tour, bist du dabei?',
            ar: 'جولة 60 كم يوم الأحد، هل أنت معنا؟',
            fr: 'sortie de 60 km dimanche, partant ?',
            es: 'vuelta de 60 km el domingo, ¿vienes?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'varım! kaç mola var?',
            en: "I'm in! how many breaks?",
            de: 'dabei! wie viele Pausen?',
            ar: 'أنا معكم! كم استراحة؟',
            fr: 'partant ! combien de pauses ?',
            es: '¡voy! ¿cuántas paradas?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'mola yok',
            en: 'no breaks',
            de: 'keine Pausen',
            ar: 'لا استراحات',
            fr: 'aucune',
            es: 'ninguna',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'o zaman ben arabayla arkanızdan gelirim',
            en: "then I'll follow you in the car",
            de: 'dann fahr ich euch mit dem Auto nach',
            ar: 'إذن سألحق بكم بالسيارة',
            fr: 'alors je vous suis en voiture',
            es: 'entonces los sigo en auto',
          },
        },
      ],
    },
    caption: {
      tr: 'Her ekibin bir destek aracı lazım',
      en: 'Every team needs a support car',
      de: 'Jedes Team braucht ein Begleitfahrzeug',
      ar: 'كل فريق يحتاج إلى سيارة دعم',
      fr: "Toute équipe a besoin d'une voiture-balai",
      es: 'Todo equipo necesita un auto de apoyo',
    },
  },
  {
    emoji: '📶',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Spor salonuna girdin. İlk iş:',
        en: 'You walk into the gym. First thing:',
        de: 'Du kommst ins Fitnessstudio. Zuerst:',
        ar: 'دخلت النادي. ما أول ما تفعله؟',
        fr: "Tu arrives à la salle. D'abord :",
        es: 'Llegas al gimnasio. Lo primero:',
      },
      options: [
        {
          tr: 'Isınırım',
          en: 'Warm up',
          de: 'Aufwärmen',
          ar: 'أقوم بالإحماء',
          fr: "Je m'échauffe",
          es: 'Caliento',
        },
        {
          tr: 'Wi-Fi şifresi sorarım',
          en: 'Ask for the Wi-Fi',
          de: 'Nach dem WLAN fragen',
          ar: 'أسأل عن الواي فاي',
          fr: 'Je demande le wifi',
          es: 'Pido la clave del wifi',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Setler arası 20 dakika kaydırma',
      en: '20 minutes of scrolling between sets',
      de: 'Satzpause: 20 Minuten Scrollen',
      ar: 'بين كل مجموعة وأخرى: 20 دقيقة تمرير',
      fr: 'Entre deux séries : 20 minutes de scroll',
      es: 'Entre series: 20 minutos de scroll',
    },
  },
  {
    emoji: '🥅',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Maç penaltılara kaldı. Sen:',
        en: 'The game goes to a shootout. You:',
        de: 'Es geht ins Elfmeterschießen. Du:',
        ar: 'وصلت المباراة إلى ركلات الترجيح. ماذا تفعل؟',
        fr: 'Séance de tirs au but. Toi :',
        es: 'El partido se va a penales. Tú:',
      },
      options: [
        { tr: 'İzlerim', en: 'Watch', de: 'Hinschauen', ar: 'أشاهد', fr: 'Je regarde', es: 'Miro' },
        {
          tr: 'Odadan çıkarım',
          en: 'Leave the room',
          de: 'Raus aus dem Zimmer',
          ar: 'أخرج من الغرفة',
          fr: 'Je sors de la pièce',
          es: 'Salgo del cuarto',
        },
        {
          tr: 'Gözümü kapatırım',
          en: 'Close my eyes',
          de: 'Augen zu',
          ar: 'أغمض عينيّ',
          fr: 'Je ferme les yeux',
          es: 'Cierro los ojos',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Ben izlersem kaçırıyorlar',
      en: 'If I watch, they miss',
      de: 'Wenn ich hinschaue, verschießen sie',
      ar: 'إن شاهدتُ أضاعوها',
      fr: 'Si je regarde, ils ratent',
      es: 'Si miro, fallan',
    },
  },
  {
    emoji: '🛍️',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Yeni bir hobiye başlıyorsun. İlk adım?',
        en: 'Starting a new hobby. Step one?',
        de: 'Neues Hobby. Erster Schritt?',
        ar: 'ستبدأ هواية جديدة. ما الخطوة الأولى؟',
        fr: 'Nouveau hobby. Première étape ?',
        es: 'Empiezas un pasatiempo. ¿Primer paso?',
      },
      options: [
        {
          tr: 'Öğrenmeye başlarım',
          en: 'Start learning',
          de: 'Einfach anfangen',
          ar: 'أبدأ التعلّم',
          fr: "Je m'y mets",
          es: 'Empiezo a practicar',
        },
        {
          tr: 'Tüm malzemeyi alırım',
          en: 'Buy all the gear',
          de: 'Erst mal alles kaufen',
          ar: 'أشتري كل المعدات',
          fr: "J'achète tout le matos",
          es: 'Compro todo el equipo',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Malzemeler hâlâ kutusunda',
      en: 'The gear is still in the box',
      de: 'Alles liegt noch im Karton',
      ar: 'المعدات ما زالت في علبتها',
      fr: 'Le matos dort encore dans son carton',
      es: 'Todo sigue en la caja',
    },
  },
  {
    emoji: '🏃',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'KOŞU HIZIM',
        en: 'MY RUNNING PACE',
        de: 'MEIN LAUFTEMPO',
        ar: 'سرعتي في الجري',
        fr: 'MA VITESSE DE COURSE',
        es: 'MI RITMO AL CORRER',
      },
      value: null,
      shape: 'fall',
      axis: 'hours',
    },
    caption: {
      tr: 'İlk 200 metre efsaneydim',
      en: 'I was a legend for the first 200 meters',
      de: 'Die ersten 200 Meter war ich eine Legende',
      ar: 'كنت أسطورة في أول 200 متر',
      fr: "J'étais une légende sur les 200 premiers mètres",
      es: 'Fui una leyenda los primeros 200 metros',
    },
  },
  {
    emoji: '🎢',
    user: ACCOUNTS.plain,
    body: {
      format: 'chart',
      title: {
        tr: 'MAÇ BOYUNCA MORALİM',
        en: 'MY MOOD DURING THE GAME',
        de: 'MEINE LAUNE BEIM SPIEL',
        ar: 'مزاجي أثناء المباراة',
        fr: 'MORAL PENDANT LE MATCH',
        es: 'MI ÁNIMO EN EL PARTIDO',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: '90 dakikada 6 kez küstüm, 6 kez barıştım',
      en: 'In 90 minutes: gave up 6 times, came back 6 times',
      de: 'In 90 Minuten: 6-mal aufgegeben, 6-mal zurückgekommen',
      ar: 'في 90 دقيقة يئست 6 مرات، وعدت 6 مرات',
      fr: 'En 90 minutes : 6 fois abandonné, 6 fois revenu',
      es: 'En 90 minutos me rendí 6 veces y volví 6 veces',
    },
  },
  {
    emoji: '🕹️',
    user: ACCOUNTS.games,
    body: {
      format: 'chart',
      title: {
        tr: 'OYUNDAKİ İLERLEMEM',
        en: 'MY GAME PROGRESS',
        de: 'MEIN SPIELFORTSCHRITT',
        ar: 'تقدّمي في اللعبة',
        fr: 'MA PROGRESSION EN JEU',
        es: 'MI PROGRESO EN EL JUEGO',
      },
      value: null,
      shape: 'crash',
      axis: 'hours',
    },
    caption: {
      tr: 'Son kayıt: 3 saat önce',
      en: 'Last save: 3 hours ago',
      de: 'Letzter Spielstand: vor 3 Stunden',
      ar: 'آخر حفظ: قبل 3 ساعات',
      fr: 'Dernière sauvegarde : il y a 3 heures',
      es: 'Último guardado: hace 3 horas',
    },
  },
  {
    emoji: '🏡',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'SPOR MAĞAZASI',
        en: 'SPORTING GOODS',
        de: 'SPORTGESCHÄFT',
        ar: 'متجر الرياضة',
        fr: 'MAGASIN DE SPORT',
        es: 'TIENDA DE DEPORTES',
      },
      items: [
        {
          tr: 'FUTBOL TOPU (4 ADET)',
          en: 'SOCCER BALLS (4)',
          de: 'FUSSBÄLLE (4 STÜCK)',
          ar: 'كرات قدم (4)',
          fr: 'BALLONS DE FOOT (4)',
          es: 'BALONES DE FÚTBOL (4)',
        },
      ],
    },
    caption: {
      tr: 'Üçü komşunun bahçesine, biri bize',
      en: "Three for the neighbor's yard, one for us",
      de: 'Drei für Nachbars Garten, einer für uns',
      ar: 'ثلاث لحديقة الجيران، وواحدة لنا',
      fr: 'Trois pour le jardin du voisin, un pour nous',
      es: 'Tres para el patio del vecino, uno para nosotros',
    },
  },
  {
    emoji: '🎸',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'MÜZİK MARKET',
        en: 'MUSIC STORE',
        de: 'MUSIKGESCHÄFT',
        ar: 'متجر الموسيقى',
        fr: 'MAGASIN DE MUSIQUE',
        es: 'TIENDA DE MÚSICA',
      },
      items: [
        {
          tr: 'GİTAR PENASI (50 ADET)',
          en: 'GUITAR PICKS (50)',
          de: 'PLEKTREN (50 STÜCK)',
          ar: 'ريش غيتار (50 قطعة)',
          fr: 'MÉDIATORS (50)',
          es: 'PÚAS DE GUITARRA (50)',
        },
      ],
    },
    caption: {
      tr: 'Bir haftada 3 tane kaldı. Nereye gidiyorlar?',
      en: 'A week later, 3 are left. Where do they go?',
      de: 'Eine Woche später sind noch 3 da. Wohin nur?',
      ar: 'بعد أسبوع بقيت 3. إلى أين تختفي؟',
      fr: 'Une semaine après, il en reste 3. Ils vont où ?',
      es: 'Una semana después quedan 3. ¿Adónde se van?',
    },
  },
  {
    emoji: '🥽',
    user: ACCOUNTS.shopping,
    body: {
      format: 'receipt',
      store: {
        tr: 'SU SPORLARI',
        en: 'SWIM SHOP',
        de: 'SCHWIMMBEDARF',
        ar: 'مستلزمات السباحة',
        fr: 'ARTICLES DE NATATION',
        es: 'TODO PARA NATACIÓN',
      },
      items: [
        {
          tr: 'GÖZLÜK (BUĞU YAPMAZ)',
          en: 'ANTI-FOG GOGGLES',
          de: 'ANTI-BESCHLAG-BRILLE',
          ar: 'نظارة مضادة للضباب',
          fr: 'LUNETTES ANTIBUÉE',
          es: 'GAFAS ANTIEMPAÑO',
        },
      ],
    },
    caption: {
      tr: 'Buğu yaptı. 10 saniyede.',
      en: 'They fogged up. In 10 seconds.',
      de: 'Beschlagen. Nach 10 Sekunden.',
      ar: 'تكوّن عليها الضباب خلال 10 ثوانٍ.',
      fr: 'Buée au bout de 10 secondes.',
      es: 'Se empañaron en 10 segundos.',
    },
  },
  {
    emoji: '🧶',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU HAFTA',
        en: 'THIS WEEK',
        de: 'DIESE WOCHE',
        ar: 'هذا الأسبوع',
        fr: 'CETTE SEMAINE',
        es: 'ESTA SEMANA',
      },
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'saat ip çözdün; 10 dakika ördün',
        en: 'hours untangling yarn. 10 minutes knitting.',
        de: 'Stunden Wolle entwirrt, 10 Minuten gestrickt',
        ar: 'ساعات في فك تشابك الخيوط، و10 دقائق في الحياكة',
        fr: 'heures à démêler la laine, 10 minutes à tricoter',
        es: 'horas desenredando lana, 10 minutos tejiendo',
      },
    },
    caption: {
      tr: 'Örgüden çok düğüm',
      en: 'Less knitting, more knotting',
      de: 'Mehr Knoten als Maschen',
      ar: 'عُقد أكثر من الحياكة',
      fr: 'Plus de nœuds que de mailles',
      es: 'Más nudos que puntos',
    },
  },
  {
    emoji: '🧩',
    user: ACCOUNTS.home,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '400', en: '400', de: '400', ar: '400', fr: '400', es: '400' },
      text: {
        tr: 'parça gökyüzü; hepsi aynı mavi',
        en: 'pieces of sky. All the exact same blue.',
        de: 'Teile Himmel. Alle im exakt gleichen Blau.',
        ar: 'قطعة من السماء، وكلها بالأزرق نفسه',
        fr: 'pièces de ciel. Toutes exactement du même bleu.',
        es: 'piezas de cielo. Todas del mismo azul.',
      },
    },
    caption: {
      tr: 'Bulutlu olanı alacaktın',
      en: "Should've gotten the one with clouds",
      de: 'Hättest das mit Wolken nehmen sollen',
      ar: 'كان عليك شراء التي فيها غيوم',
      fr: 'Fallait prendre celui avec des nuages',
      es: 'Debiste comprar el que tenía nubes',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU AY',
        en: 'THIS MONTH',
        de: 'DIESEN MONAT',
        ar: 'هذا الشهر',
        fr: 'CE MOIS-CI',
        es: 'ESTE MES',
      },
      big: { tr: '200', en: '200', de: '200', ar: '200', fr: '200', es: '200' },
      text: {
        tr: 'saat oyundaki evini döşedin; gerçek odan hâlâ dağınık',
        en: 'hours decorating your game house. Your real room: still a mess.',
        de: 'Stunden dein Spielhaus eingerichtet. Dein echtes Zimmer: Chaos.',
        ar: 'ساعة في تزيين بيتك داخل اللعبة… وغرفتك الحقيقية ما زالت فوضى',
        fr: 'heures à décorer ta maison dans le jeu. Ta chambre : le bazar.',
        es: 'horas decorando tu casa del juego. Tu cuarto: un desastre.',
      },
    },
    caption: {
      tr: 'Sanal ev: 5 yıldız. Gerçek ev: sorma.',
      en: "Game house: 5 stars. Real one: don't ask.",
      de: 'Spielhaus: 5 Sterne. Das echte: frag nicht.',
      ar: 'البيت الافتراضي: 5 نجوم. الحقيقي: لا تسأل.',
      fr: 'Maison virtuelle : 5 étoiles. La vraie : sans commentaire.',
      es: 'Casa virtual: 5 estrellas. La real: ni preguntes.',
    },
  },
  {
    emoji: '🪕',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'YARIM KALAN HOBİLERİM',
        en: 'MY ABANDONED HOBBIES',
        de: 'MEINE ABGEBROCHENEN HOBBYS',
        ar: 'هواياتي التي لم تكتمل',
        fr: 'MES HOBBIES ABANDONNÉS',
        es: 'MIS PASATIEMPOS A MEDIAS',
      },
      rows: [['🎸', '🎨'], ['🧶', '📷'], ['🎹', '🛼'], ['🪕']],
    },
    caption: {
      tr: 'Hepsi az kullanılmış, satılık',
      en: 'All barely used. All for sale.',
      de: 'Alle kaum benutzt. Alle zu verkaufen.',
      ar: 'كلها شبه جديدة، وكلها للبيع',
      fr: 'Tout est comme neuf. Tout est à vendre.',
      es: 'Todo casi sin usar. Todo a la venta.',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.sport,
    body: {
      format: 'tier',
      title: {
        tr: 'SPOR TIER LIST',
        en: 'SPORTS TIER LIST',
        de: 'SPORT-TIER-LIST',
        ar: 'تصنيف الرياضات',
        fr: 'TIER LIST DES SPORTS',
        es: 'TIER LIST DE DEPORTES',
      },
      rows: [['🎣', '🎯', '🏎️'], ['🎳', '🎱'], ['🏊', '🏐'], ['🏃', '🧗']],
    },
    caption: {
      tr: 'Oturarak yapılabiliyorsa S',
      en: "If you can do it sitting down, it's S",
      de: 'Geht es im Sitzen, ist es S',
      ar: 'ما يُمارَس جلوسًا يأتي في المقدمة',
      fr: "Si ça se fait assis, c'est S",
      es: 'Si se hace sentado, es S',
    },
  },
  {
    emoji: '😩',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⚡',
        app: {
          tr: 'Oyun',
          en: 'Game',
          de: 'Spiel',
          ar: 'اللعبة',
          fr: 'Jeu',
          es: 'Juego',
        },
        text: {
          tr: 'Enerjin doldu! Oynamaya hazırsın',
          en: 'Your energy is full! Ready to play',
          de: "Deine Energie ist voll! Los geht's",
          ar: 'طاقتك ممتلئة! أنت جاهز للعب',
          fr: 'Ton énergie est pleine ! Prêt à jouer',
          es: '¡Tu energía está llena! A jugar',
        },
      },
    },
    caption: {
      tr: 'Onunki doldu. Benimki hâlâ %3.',
      en: "The game's energy, maybe. Mine's at 3%.",
      de: 'Die im Spiel vielleicht. Meine: 3 %.',
      ar: 'طاقة اللعبة ربما، أما طاقتي فعند 3%',
      fr: 'Celle du jeu, peut-être. La mienne : 3 %.',
      es: 'La del juego, quizá. La mía: 3 %.',
    },
  },
  {
    emoji: '⏱️',
    user: ACCOUNTS.sport,
    body: {
      format: 'notifications',
      first: {
        icon: '👟',
        app: {
          tr: 'Koşu takibi',
          en: 'Run tracker',
          de: 'Lauf-App',
          ar: 'متتبّع الجري',
          fr: 'Suivi de course',
          es: 'Mis carreras',
        },
        text: {
          tr: 'Kişisel rekor! 400 m, 65 saniye',
          en: 'Personal best! 400 m in 65 seconds',
          de: 'Neue Bestzeit! 400 m in 65 Sekunden',
          ar: 'رقم شخصي جديد! 400 م في 65 ثانية',
          fr: 'Record perso ! 400 m en 65 secondes',
          es: '¡Récord personal! 400 m en 65 segundos',
        },
      },
    },
    caption: {
      tr: 'Otobüse yetişmeye çalışıyordum',
      en: 'I was chasing the bus',
      de: 'Ich bin nur dem Bus hinterhergerannt',
      ar: 'كنت أركض خلف الحافلة',
      fr: 'Je courais après le bus',
      es: 'Iba corriendo detrás del bus',
    },
  },
  {
    emoji: '📆',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Bir gün değil, gün bir. Ben 3 yıldır gün birdeyim.',
        en: "One day or day one? I've been on day one for 3 years.",
        de: 'Eines Tages oder Tag eins? Bei mir seit 3 Jahren Tag eins.',
        ar: 'يومًا ما أم اليوم الأول؟ أنا في اليوم الأول منذ 3 سنوات.',
        fr: 'Un jour ou jour un ? Moi, je suis au jour un depuis 3 ans.',
        es: '¿Algún día o día uno? Llevo 3 años en el día uno.',
      },
    },
    caption: {
      tr: 'Spora her pazartesi yeniden başlıyorum',
      en: 'Restarting the gym every Monday',
      de: 'Jeden Montag fange ich wieder mit Sport an',
      ar: 'أعود إلى الرياضة كل يوم اثنين من جديد',
      fr: 'Je reprends le sport chaque lundi',
      es: 'Retomo el gimnasio cada lunes',
    },
  },
  {
    emoji: '🧖',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Terliyorsan doğru yoldasın. — Saunada oturan biri',
        en: "Sweating means you're on the right track. — Me, in the sauna",
        de: 'Wer schwitzt, ist auf dem richtigen Weg. — Ich, in der Sauna',
        ar: 'إن كنت تتعرّق فأنت على الطريق الصحيح. — شخص جالس في الساونا',
        fr: "Si tu transpires, t'es sur la bonne voie. — Moi, au sauna",
        es: 'Si sudas, vas por buen camino. — Yo, en la sauna',
      },
    },
    caption: {
      tr: 'Bugünkü antrenman tamamlandı',
      en: "Today's workout: done.",
      de: 'Training für heute: erledigt.',
      ar: 'تمرين اليوم: اكتمل.',
      fr: 'Séance du jour : terminée.',
      es: 'Entrenamiento de hoy: listo.',
    },
  },
  {
    emoji: '⏳',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Her hamleni iyice düşün. — 20 dakika düşünüp rastgele piyon süren ben',
        en: 'Think before you move. — Me, moving a random pawn after 20 minutes',
        de: 'Überlege jeden Zug gut. — Ich, der nach 20 Minuten irgendwas zieht',
        ar: 'فكّر جيدًا قبل كل نقلة. — أنا بعد 20 دقيقة أحرّك أي بيدق',
        fr: 'Réfléchis bien. — Moi, qui joue un pion au hasard après 20 minutes',
        es: 'Piensa bien cada jugada. — Yo, moviendo un peón al azar tras 20 minutos',
      },
    },
    caption: {
      tr: 'Rakip bu arada iki çay içti',
      en: 'Meanwhile my opponent made tea. Twice.',
      de: 'Mein Gegner hat inzwischen zwei Tees getrunken',
      ar: 'خصمي شرب كوبين من الشاي في الأثناء',
      fr: "Pendant ce temps, l'adversaire a bu deux thés",
      es: 'Mientras, mi rival se tomó dos tés',
    },
  },
  {
    emoji: '💪',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Tek rakibin dünkü sensin. Dünkü ben çok tembeldi, kolay yendim.',
        en: "Your only rival is yesterday's you. Yesterday's me was lazy. Easy win.",
        de: 'Dein einziger Gegner: du von gestern. Der war faul. Leichter Sieg.',
        ar: 'منافسك الوحيد هو أنت بالأمس. وأنا بالأمس كنت كسولًا، ففزت بسهولة.',
        fr: "Ton seul rival, c'est toi hier. Et hier, j'étais flemmard : facile.",
        es: 'Tu único rival eres tú ayer. Y ayer yo era perezoso: fácil.',
      },
    },
    caption: {
      tr: 'Bugün 2 şınav: yeni rekor',
      en: '2 push-ups today. New record.',
      de: 'Heute 2 Liegestütze. Neuer Rekord.',
      ar: 'تمرينا ضغط اليوم: رقم قياسي جديد',
      fr: "2 pompes aujourd'hui. Nouveau record.",
      es: 'Hoy 2 flexiones: nuevo récord.',
    },
  },
  {
    emoji: '🙃',
    user: ACCOUNTS.games,
    body: {
      format: 'quote',
      text: {
        tr: 'Önemli olan kazanmak değil, katılmaktır. Bunu hep ben söylüyorum.',
        en: "It's not about winning, it's about taking part. I say that a lot.",
        de: 'Dabei sein ist alles. Das sage ich ziemlich oft.',
        ar: 'المهم ليس الفوز بل المشاركة. أنا من يقول هذا دائمًا.',
        fr: "L'important, c'est de participer. C'est toujours moi qui le dis.",
        es: 'Lo importante no es ganar, sino participar. Siempre lo digo yo.',
      },
    },
    caption: {
      tr: 'Oyun gecesi karnem: 0 galibiyet',
      en: 'My game night record: 0 wins',
      de: 'Meine Spieleabend-Bilanz: 0 Siege',
      ar: 'سجلّي في ليالي الألعاب: 0 انتصارات',
      fr: 'Mon bilan en soirée jeux : 0 victoire',
      es: 'Mi récord en noches de juegos: 0 victorias',
    },
  },
];

export const HOBBIES_LIKE: readonly Draft[] = [
  {
    emoji: '🛹',
    user: ACCOUNTS.tolga,
    body: { format: 'scene' },
    caption: {
      tr: '30 yaşında kaykay öğreniyorum, parktaki çocuklar alkışladı',
      en: 'learning to skateboard at 30, the kids at the park clapped',
      de: 'mit 30 skaten lernen, die kids im park haben geklatscht',
      ar: 'أتعلّم التزلج على اللوح في الثلاثين، وصفّق لي الأطفال',
      fr: 'skate à 30 ans : les enfants du parc ont applaudi',
      es: 'aprendo skate a los 30 y los niños del parque aplaudieron',
    },
  },
  {
    emoji: '🤸',
    user: ACCOUNTS.melis,
    body: { format: 'scene' },
    caption: {
      tr: 'sonunda amuda kalktım! (duvar da yardım etti)',
      en: 'finally did a handstand! (the wall helped a bit)',
      de: 'endlich einen handstand geschafft! (die wand hat geholfen)',
      ar: 'أخيرًا وقفت على يديّ! (بمساعدة صغيرة من الجدار)',
      fr: "enfin réussi l'équilibre sur les mains ! (merci le mur)",
      es: '¡por fin hice una parada de manos! (la pared ayudó)',
    },
  },
  {
    emoji: '🥅',
    user: ACCOUNTS.kaan,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk golümü attım!! (kaleci su içiyordu)',
      en: 'scored my first goal!! (the goalie was getting a drink)',
      de: 'mein erstes tor!! (der torwart hat grad was getrunken)',
      ar: 'سجّلت أول هدف لي!! (كان الحارس يشرب الماء)',
      fr: "mon premier but !! (le gardien buvait de l'eau)",
      es: '¡¡metí mi primer gol!! (el portero estaba tomando agua)',
    },
  },
  {
    emoji: '🕺',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'salsa dersinde ilk kez kimsenin ayağına basmadım!!',
      en: "salsa class: didn't step on a single foot today!!",
      de: 'salsakurs: heute niemandem auf den fuß getreten!!',
      ar: 'في درس السالسا لم أدُس على قدم أحد لأول مرة!!',
      fr: "cours de salsa : j'ai marché sur les pieds de personne !!",
      es: '¡¡en salsa no le pisé el pie a nadie por primera vez!!',
    },
  },
  {
    emoji: '✏️',
    user: ACCOUNTS.ipek,
    body: {
      format: 'polaroid',
      note: {
        tr: 'gün 1 → gün 30',
        en: 'day 1 → day 30',
        de: 'tag 1 → tag 30',
        ar: 'اليوم 1 ← اليوم 30',
        fr: 'jour 1 → jour 30',
        es: 'día 1 → día 30',
      },
    },
    caption: {
      tr: '30 gün boyunca her gün çizdim, farka bakın',
      en: 'drew every day for 30 days, look at the difference',
      de: '30 tage jeden tag gezeichnet, seht den unterschied',
      ar: 'رسمت كل يوم لمدة 30 يومًا، انظروا إلى الفرق',
      fr: '30 jours de dessin, regardez la différence',
      es: 'dibujé 30 días seguidos, miren la diferencia',
    },
  },
  {
    emoji: '🎞️',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'en net kare',
        en: 'the sharpest one',
        de: 'das schärfste',
        ar: 'أوضح لقطة',
        fr: 'la plus nette',
        es: 'la más nítida',
      },
    },
    caption: {
      tr: 'ilk film rulom geldi: 36 karenin 4’ü net',
      en: 'got my first film roll back: 4 of 36 in focus',
      de: 'mein erster film ist entwickelt: 4 von 36 scharf',
      ar: 'طُبع أول فيلم تصوير لي: 4 صور واضحة من 36',
      fr: 'ma première pellicule : 4 photos nettes sur 36',
      es: 'revelé mi primer rollo: 4 de 36 fotos nítidas',
    },
  },
  {
    emoji: '🎹',
    user: ACCOUNTS.onur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk konserim',
        en: 'first concert',
        de: 'erstes konzert',
        ar: 'حفلتي الأولى',
        fr: 'premier concert',
        es: 'mi primer concierto',
      },
    },
    caption: {
      tr: 'anneme ilk şarkımı çaldım, ağladı (umarım güzellikten)',
      en: 'played mom my first song, she cried (from joy, I hope)',
      de: 'erstes lied für mama, sie weinte (vor freude, hoffe ich)',
      ar: 'عزفت لأمي أول أغنية، فبكت (من الفرح، أتمنى)',
      fr: 'premier morceau pour maman, elle a pleuré (de joie ?)',
      es: 'mi primera canción para mamá: lloró (de emoción, espero)',
    },
  },
  {
    emoji: '🥉',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bronz benim',
        en: 'bronze is mine',
        de: 'bronze gehört mir',
        ar: 'البرونزية لي',
        fr: 'le bronze est à moi',
        es: 'el bronce es mío',
      },
    },
    caption: {
      tr: 'tırmanış yarışmasında 3. oldum!! (3 kişiydik)',
      en: 'came 3rd in the climbing contest!! (there were 3 of us)',
      de: '3. platz beim kletterwettbewerb!! (wir waren zu dritt)',
      ar: 'حللتُ في المركز الثالث في مسابقة التسلق!! (كنا 3 فقط)',
      fr: "3e au concours d'escalade !! (on était 3)",
      es: '¡¡quedé en 3.er lugar en el torneo de escalada!! (éramos 3)',
    },
  },
  {
    emoji: '📣',
    user: ACCOUNTS.arda,
    body: { format: 'dump', emojis: ['📣', '📺', '🍿', '🥤', '😭'] },
    caption: {
      tr: 'maç günü dump’ı: kaybettik ama sesim hâlâ yok',
      en: 'game day dump: we lost, and my voice is still gone',
      de: 'spieltag: verloren, und meine stimme ist immer noch weg',
      ar: 'يوم المباراة: خسرنا، وصوتي ما زال مبحوحًا',
      fr: 'jour de match : on a perdu, et moi, ma voix',
      es: 'día de partido: perdimos y sigo sin voz',
    },
  },
  {
    emoji: '🏌️',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['🏌️', '🍦', '💦', '🎯', '🏅'] },
    caption: {
      tr: 'mini golf dump’ı: 18 delik, 94 vuruş, top 2 kez havuzda',
      en: 'mini golf dump: 18 holes, 94 shots, ball in the pond twice',
      de: 'minigolf: 18 bahnen, 94 schläge, ball 2-mal im teich',
      ar: 'الغولف المصغّر: 18 حفرة، 94 ضربة، والكرة في البركة مرتين',
      fr: 'mini-golf : 18 trous, 94 coups, 2 plongeons dans la mare',
      es: 'minigolf: 18 hoyos, 94 golpes, la pelota 2 veces al agua',
    },
  },
  {
    emoji: '🏺',
    user: ACCOUNTS.defne,
    body: { format: 'dump', emojis: ['🏺', '☕', '🎨', '👕', '🧽'] },
    caption: {
      tr: 'seramik atölyesi: 1 kupa yaptım, çamurun yarısı üstümde',
      en: 'pottery class: made 1 mug, wearing half the clay',
      de: 'töpferkurs: 1 tasse gemacht, der halbe ton klebt an mir',
      ar: 'ورشة الفخار: صنعت كوبًا واحدًا، ونصف الطين عليّ',
      fr: "atelier poterie : 1 tasse, et la moitié de l'argile sur moi",
      es: 'cerámica: hice 1 taza y tengo la mitad del barro encima',
    },
  },
  {
    emoji: '💿',
    user: ACCOUNTS.baris,
    body: { format: 'dump', emojis: ['💿', '🎶', '📦', '🎧', '✨'] },
    caption: {
      tr: 'plak koleksiyonum 50 oldu!! pikabım yok daha',
      en: '50 records in my collection!! no record player yet',
      de: '50 platten in der sammlung!! plattenspieler fehlt noch',
      ar: 'مجموعة أسطواناتي وصلت إلى 50!! ولا أملك مشغّلًا بعد',
      fr: '50 vinyles dans ma collection !! pas encore de platine',
      es: '¡¡50 vinilos en mi colección!! aún sin tocadiscos',
    },
  },
];

export const HOBBIES_HOLD: readonly Draft[] = [
  {
    emoji: '🏀',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Top havada, süre doluyor… doğru anı bekle',
      en: 'Ball in the air, clock running down… wait for it',
      de: 'Ball in der Luft, die Uhr tickt… warte auf den Moment',
      ar: 'الكرة في الهواء والوقت ينفد… انتظر اللحظة المناسبة',
      fr: "Ballon en l'air, le chrono tourne… attends le bon moment",
      es: 'Balón en el aire, el reloj corre… espera el momento',
    },
  },
  {
    emoji: '🎲',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Üst üste üçüncü çift altı. Masada sessizlik.',
      en: 'Third double six in a row. Silence at the table.',
      de: 'Dritter Sechserpasch in Folge. Stille am Tisch.',
      ar: 'ستة وستة للمرة الثالثة على التوالي. صمت حول الطاولة.',
      fr: "Troisième double six d'affilée. Silence autour de la table.",
      es: 'Tercer doble seis seguido. Silencio en la mesa.',
    },
  },
  {
    emoji: '♟️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Rakibin veziri açıkta! Bu fırsat bir daha gelmez.',
      en: "Their queen is hanging! This chance won't come again.",
      de: 'Die Dame hängt! So eine Chance kommt nie wieder.',
      ar: 'وزير الخصم مكشوف! فرصة لن تتكرر.',
      fr: "La dame adverse est en prise ! Ça n'arrivera plus jamais.",
      es: '¡Te dejaron la reina servida! Oportunidad única.',
    },
  },
  {
    emoji: '✉️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Hatalı basım pul! Dünyada sadece 3 tane var',
      en: 'A misprinted stamp! Only 3 exist in the world',
      de: 'Fehldruck-Briefmarke! Nur 3 gibt es auf der Welt',
      ar: 'طابع بخطأ طباعي! لا يوجد منه في العالم سوى 3',
      fr: 'Un timbre mal imprimé ! Il en existe 3 au monde',
      es: '¡Un sello con error de impresión! Solo hay 3 en el mundo',
    },
  },
  {
    emoji: '📒',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Albümün son çıkartması! 3 yıllık arayış bitti',
      en: 'The last sticker for the album! A 3-year hunt is over',
      de: 'Das letzte Sammelbild fürs Album! 3 Jahre Suche vorbei',
      ar: 'آخر ملصق في الألبوم! انتهى بحث دام 3 سنوات',
      fr: "La dernière vignette de l'album ! 3 ans de chasse terminés",
      es: '¡El último sticker del álbum! 3 años buscándolo',
    },
  },
  {
    emoji: '🏓',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: '99 vuruşluk ralli! 100. vuruş senin.',
      en: 'A 99-hit rally! Hit number 100 is yours.',
      de: 'Ballwechsel mit 99 Schlägen! Der 100. gehört dir.',
      ar: 'تبادل 99 ضربة! والضربة المئة لك.',
      fr: 'Un échange de 99 coups ! Le 100e est pour toi.',
      es: '¡Un peloteo de 99 golpes! El número 100 es tuyo.',
    },
  },
  {
    emoji: '💖',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ekstra can! Hem de son canındayken',
      en: 'Extra life! Right when you were on your last',
      de: 'Extraleben! Genau beim letzten Leben',
      ar: 'حياة إضافية! وأنت في آخر حياة لديك',
      fr: "Vie bonus ! Pile quand t'étais à ta dernière",
      es: '¡Vida extra! Justo cuando te quedaba la última',
    },
  },
  {
    emoji: '🏋️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi an: biri ağırlıkları yerine koydu',
      en: 'Legendary sighting: someone put the weights back',
      de: 'Legendäre Sichtung: Jemand hat die Hanteln zurückgelegt',
      ar: 'لحظة أسطورية: أحدهم أعاد الأوزان إلى مكانها',
      fr: "Scène légendaire : quelqu'un a rangé les haltères",
      es: 'Momento legendario: alguien devolvió las pesas a su lugar',
    },
  },
];

export const HOBBIES_FREEZE: readonly Draft[] = [
  {
    emoji: '♟️',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DOKUNMA',
        en: "DON'T TOUCH",
        de: 'NICHT BERÜHREN',
        ar: 'لا تلمس',
        fr: 'NE TOUCHE PAS',
        es: 'NO TOQUES',
      },
      small: {
        tr: 'DOKUNULAN TAŞ OYNANIR',
        en: 'TOUCH IT AND YOU MOVE IT',
        de: 'BERÜHRT, GEFÜHRT',
        ar: 'القطعة التي تلمسها تحرّكها',
        fr: 'PIÈCE TOUCHÉE, PIÈCE JOUÉE',
        es: 'PIEZA TOCADA, PIEZA MOVIDA',
      },
    },
    caption: {
      tr: 'Elini tahtadan çek.',
      en: 'Hands off the board.',
      de: 'Hände weg vom Brett.',
      ar: 'أبعد يدك عن الرقعة.',
      fr: "Pas touche à l'échiquier.",
      es: 'Quita la mano del tablero.',
    },
    headline: {
      tr: 'Sıra sende ama henüz emin değilsin',
      en: "Your move. You're not sure yet.",
      de: 'Du bist am Zug. Noch nicht sicher.',
      ar: 'دورك الآن، ولست متأكدًا بعد',
      fr: "À toi de jouer. T'es pas encore sûr.",
      es: 'Te toca mover. Aún no estás seguro.',
    },
  },
  {
    emoji: '🎾',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'MAÇ SAYISI',
        en: 'MATCH POINT',
        de: 'MATCHBALL',
        ar: 'نقطة المباراة',
        fr: 'BALLE DE MATCH',
        es: 'MATCH POINT',
      },
      small: {
        tr: 'SESSİZLİK LÜTFEN',
        en: 'QUIET, PLEASE',
        de: 'BITTE RUHE',
        ar: 'الهدوء من فضلك',
        fr: "SILENCE, S'IL VOUS PLAÎT",
        es: 'SILENCIO, POR FAVOR',
      },
    },
    caption: {
      tr: 'Tribünle birlikte nefesini tut.',
      en: 'Hold your breath with the crowd.',
      de: 'Halt mit der Tribüne den Atem an.',
      ar: 'احبس أنفاسك مع الجمهور.',
      fr: 'Retiens ton souffle avec le public.',
      es: 'Contén el aliento con el público.',
    },
    headline: {
      tr: 'Servis atılmak üzere, tribün sustu',
      en: 'The serve is coming. Total silence.',
      de: 'Gleich kommt der Aufschlag. Alles still.',
      ar: 'الإرسال بعد لحظة، والمدرجات صامتة',
      fr: 'Le service arrive. Silence total.',
      es: 'Viene el saque. Silencio total.',
    },
  },
  {
    emoji: '🖌️',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'MODEL POZDA',
        en: 'MODEL POSING',
        de: 'MODELL SITZT',
        ar: 'جلسة رسم',
        fr: 'SÉANCE DE POSE',
        es: 'MODELO POSANDO',
      },
      small: {
        tr: 'RESİM KURSU DEVAM EDİYOR',
        en: 'ART CLASS IN PROGRESS',
        de: 'PORTRÄTKURS LÄUFT',
        ar: 'درس الرسم مستمر',
        fr: 'ATELIER DE DESSIN EN COURS',
        es: 'CLASE DE DIBUJO EN CURSO',
      },
    },
    caption: {
      tr: 'Burnun kaşınsa bile.',
      en: 'Even if your nose itches.',
      de: 'Auch wenn die Nase juckt.',
      ar: 'حتى لو حكّك أنفك.',
      fr: 'Même si ton nez te gratte.',
      es: 'Aunque te pique la nariz.',
    },
    headline: {
      tr: 'Resim kursunda model sensin',
      en: "You're the model in art class",
      de: 'Du sitzt Modell im Zeichenkurs',
      ar: 'أنت الموديل في درس الرسم',
      fr: "C'est toi le modèle au cours de dessin",
      es: 'Eres el modelo de la clase de dibujo',
    },
  },
  {
    emoji: '🤞',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'UĞURLU YER',
        en: 'LUCKY SPOT',
        de: 'GLÜCKSPLATZ',
        ar: 'المكان المحظوظ',
        fr: 'PLACE FÉTICHE',
        es: 'ZONA DE SUERTE',
      },
      small: {
        tr: 'MAÇ BİTENE KADAR KALKMAYIN',
        en: 'STAY PUT TILL THE WHISTLE',
        de: 'SITZEN BLEIBEN BIS ABPFIFF',
        ar: 'لا تتحرك حتى نهاية المباراة',
        fr: 'PAS BOUGER AVANT LA FIN',
        es: 'NO TE MUEVAS HASTA EL FINAL',
      },
    },
    caption: {
      tr: 'Pozisyonu bozma.',
      en: 'Hold that pose.',
      de: 'Bloß nicht bewegen.',
      ar: 'لا تغيّر جلستك.',
      fr: 'Change surtout pas de position.',
      es: 'No cambies de postura.',
    },
    headline: {
      tr: 'Sen böyle oturunca gol geliyor',
      en: 'Every time you sit like this, they score',
      de: 'Wenn du so sitzt, fällt ein Tor',
      ar: 'كلما جلست هكذا سجّلوا هدفًا',
      fr: "Quand tu t'assois comme ça, ils marquent",
      es: 'Cuando te sientas así, meten gol',
    },
  },
  {
    emoji: '🎣',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'İSKELE',
        en: 'FISHING PIER',
        de: 'ANGELSTEG',
        ar: 'رصيف الصيد',
        fr: 'PONTON DE PÊCHE',
        es: 'MUELLE DE PESCA',
      },
    },
    caption: {
      tr: 'Oltayı oynatma.',
      en: "Don't move the rod.",
      de: 'Angel nicht bewegen.',
      ar: 'لا تحرّك الصنارة.',
      fr: 'Bouge pas la canne.',
      es: 'No muevas la caña.',
    },
    headline: {
      tr: 'Balık yeme yaklaşıyor',
      en: 'A fish is nibbling the bait',
      de: 'Ein Fisch knabbert am Köder',
      ar: 'سمكة تقترب من الطُّعم',
      fr: "Un poisson tourne autour de l'appât",
      es: 'Un pez se acerca al anzuelo',
    },
  },
  {
    emoji: '🧘',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'MEDİTASYON SALONU',
        en: 'MEDITATION ROOM',
        de: 'MEDITATIONSRAUM',
        ar: 'قاعة التأمل',
        fr: 'SALLE ZEN',
        es: 'SALA DE MEDITACIÓN',
      },
    },
    caption: {
      tr: 'Gözlerini kapat. Kıpırdama.',
      en: "Eyes closed. Don't move.",
      de: 'Augen zu. Nicht bewegen.',
      ar: 'أغمض عينيك. لا تتحرك.',
      fr: 'Ferme les yeux. Bouge pas.',
      es: 'Cierra los ojos. No te muevas.',
    },
    headline: {
      tr: 'Hoca, meditasyonda kıpırdayanı arıyor',
      en: "The teacher's checking who's fidgeting",
      de: 'Die Lehrerin schaut, wer herumzappelt',
      ar: 'المدربة تبحث عمّن يتململ',
      fr: 'La prof guette qui gigote',
      es: 'La profe busca quién se mueve',
    },
  },
  {
    emoji: '🎻',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ORKESTRA PROVASI',
        en: 'ORCHESTRA PRACTICE',
        de: 'ORCHESTERPROBE',
        ar: 'بروفة الأوركسترا',
        fr: 'RÉPÉTITION',
        es: 'ENSAYO DE ORQUESTA',
      },
    },
    caption: {
      tr: 'Yay havada kalsın, yüz masum olsun.',
      en: 'Bow still. Face innocent.',
      de: 'Bogen still. Unschuldsmiene.',
      ar: 'القوس ثابت، والوجه بريء.',
      fr: 'Archet immobile, air innocent.',
      es: 'Arco quieto, cara de inocente.',
    },
    headline: {
      tr: 'Şef, yanlış notanın sahibini arıyor',
      en: 'The conductor wants to know who that was',
      de: 'Der Dirigent sucht den falschen Ton',
      ar: 'المايسترو يبحث عن صاحب النغمة الخاطئة',
      fr: 'Le chef traque la fausse note',
      es: 'El director busca al de la nota falsa',
    },
  },
];
