import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Home: chores, roommates, furniture, plants, the fridge, the laundry, fixing things.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const HOME_SKIP: readonly Draft[] = [
  {
    emoji: '🧱',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Komşu hapşırdı, “çok yaşa” dedim. Duvardan.',
      en: 'Neighbor sneezed. I said “bless you.” Through the wall.',
      de: 'Nachbar niest. Ich: „Gesundheit!“ Durch die Wand.',
      ar: 'سأل جاري: «أين المفاتيح؟» فأجبته أنا… من خلف الجدار',
      fr: "Des murs en carton : j'ai dit « à vos souhaits » au voisin.",
      es: 'El vecino estornudó y le dije «salud» a través de la pared.',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Bir tablo astım. Duvarda 7 delik var.',
      en: 'Hung one picture. The wall now has 7 holes.',
      de: 'Ein Bild aufgehängt. Die Wand hat jetzt 7 Löcher.',
      ar: 'علّقت لوحة واحدة… وفي الجدار الآن 7 ثقوب',
      fr: 'Un tableau accroché. 7 trous dans le mur.',
      es: 'Colgué un cuadro. La pared tiene 7 agujeros.',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Tek kırmızı çorap, bütün beyazlar pembe',
      en: 'One red sock. All my whites are pink now.',
      de: 'Eine rote Socke – und die ganze Weißwäsche ist rosa.',
      ar: 'جورب أحمر واحد… وكل ملابسي البيضاء صارت وردية',
      fr: 'Une chaussette rouge. Tout mon linge blanc est rose.',
      es: 'Un calcetín rojo y toda mi ropa blanca quedó rosa.',
    },
  },
  {
    emoji: '🛍️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Poşet poşeti doldu. Yeni poşet lazım.',
      en: 'The bag of bags is full. We need a bag.',
      de: 'Die Tütentüte ist voll. Wir brauchen eine Tüte.',
      ar: 'امتلأ كيس الأكياس… نحتاج كيسًا جديدًا',
      fr: 'Le sac à sacs est plein. Il nous faut un sac.',
      es: 'La bolsa de las bolsas se llenó. Necesito otra bolsa.',
    },
  },
  {
    emoji: '🪟',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Camları sildim. 10 dakika sonra yağmur.',
      en: 'Cleaned the windows. Rain, 10 minutes later.',
      de: 'Fenster geputzt. 10 Minuten später: Regen.',
      ar: 'نظّفت النوافذ… وبعد 10 دقائق أمطرت',
      fr: 'Vitres nettoyées. 10 minutes après : la pluie.',
      es: 'Limpié las ventanas. A los 10 minutos, llovió.',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Sandalyeme kimse oturmaz. O bir dolap.',
      en: "Nobody sits on my bedroom chair. It's a closet.",
      de: 'Auf meinem Zimmerstuhl sitzt keiner. Er ist ein Schrank.',
      ar: 'لا أحد يجلس على كرسي غرفتي… إنه خزانة',
      fr: "Personne ne s'assoit sur ma chaise. C'est une armoire.",
      es: 'Nadie se sienta en mi silla. Es un armario.',
    },
  },
  {
    emoji: '🔧',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Hile: 40 dk tamir videosu izle, usta çağır',
      en: 'Hack: watch a 40-min repair video, then call a pro',
      de: 'Trick: 40 Min. Tutorial schauen, dann Handwerker rufen',
      ar: 'حيلة: شاهد فيديو إصلاح لمدة 40 دقيقة، ثم اتصل بالفني',
      fr: 'Astuce : 40 min de tuto réparation, puis appelle un pro',
      es: 'Truco: mira 40 min de tutorial y luego llama al técnico',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.home,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'makinede çamaşır var, senin mi?',
            en: 'is that your laundry in the washer?',
            de: 'ist das deine Wäsche in der Maschine?',
            ar: 'هل الغسيل الذي في الغسالة لك؟',
            fr: "c'est ton linge dans la machine ?",
            es: '¿es tuya la ropa de la lavadora?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'evet, az önce attım',
            en: 'yeah, just put it in',
            de: 'ja, grad erst angemacht',
            ar: 'نعم، وضعته للتو',
            fr: 'oui, je viens de la lancer',
            es: 'sí, la acabo de poner',
          },
        },
        {
          from: 'them',
          text: {
            tr: '“az önce” dediğin salıydı',
            en: '“just now” was Tuesday',
            de: '„grad erst“ war Dienstag',
            ar: 'كان ذلك يوم الثلاثاء',
            fr: "« à l'instant », c'était mardi",
            es: 'eso fue el martes',
          },
        },
      ],
    },
    caption: {
      tr: 'Bir tur daha yıkarım, taptaze olur',
      en: "I'll run it again. Extra fresh.",
      de: 'Ich wasch sie einfach noch mal. Extra frisch.',
      ar: 'سأغسله مرة أخرى… وسيصير أنظف',
      fr: 'Je relance une machine. Extra frais.',
      es: 'La lavo otra vez y queda más fresca.',
    },
  },
  {
    emoji: '👂',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Üst kat komşu',
        en: 'Upstairs neighbor',
        de: 'Nachbar von oben',
        ar: 'جار الطابق العلوي',
        fr: 'Voisin du dessus',
        es: 'Vecino de arriba',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'gece 3’te o ses neydi?',
            en: 'what was that noise at 3 am?',
            de: 'was war das für ein Geräusch um 3 Uhr?',
            ar: 'ما ذلك الصوت في الثالثة فجرًا؟',
            fr: "c'était quoi ce bruit à 3 h du matin ?",
            es: '¿qué fue ese ruido a las 3 de la mañana?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'hangi ses?',
            en: 'what noise?',
            de: 'welches Geräusch?',
            ar: 'أي صوت؟',
            fr: 'quel bruit ?',
            es: '¿qué ruido?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bilye düşürür gibi, tık tık tık',
            en: 'like someone dropping marbles',
            de: 'als würden Murmeln runterfallen',
            ar: 'كأن أحدًا يُسقط كرات زجاجية',
            fr: 'comme des billes qui tombent',
            es: 'como si alguien tirara canicas',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bizde bilye yok ki 😶',
            en: "we don't own any marbles 😶",
            de: 'wir haben gar keine Murmeln 😶',
            ar: 'لا توجد لدينا كرات زجاجية أصلًا 😶',
            fr: "on n'a pas de billes, nous 😶",
            es: 'nosotros no tenemos canicas 😶',
          },
        },
      ],
    },
    caption: {
      tr: 'Apartmanın en büyük gizemi çözülemedi',
      en: "The building's biggest mystery lives on",
      de: 'Das größte Rätsel im Haus bleibt ungelöst',
      ar: 'أكبر لغز في العمارة ما زال بلا حل',
      fr: "Le plus grand mystère de l'immeuble reste entier",
      es: 'El mayor misterio del edificio sigue sin resolver',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Apartman grubu',
        en: 'Building chat',
        de: 'Hausgemeinschaft',
        ar: 'مجموعة العمارة',
        fr: "Groupe de l'immeuble",
        es: 'Grupo del edificio',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'sabah 6’da duşta şarkı söyleyen komşumuz 🙂',
            en: 'to whoever sings in the shower at 6 am 🙂',
            de: 'an unseren Duschsänger um 6 Uhr früh 🙂',
            ar: 'إلى من يغني تحت الدش في السادسة صباحًا 🙂',
            fr: 'au chanteur de la douche de 6 h 🙂',
            es: 'para quien canta en la ducha a las 6 🙂',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'sesiniz çok güzel ama biraz erken',
            en: "lovely voice, but it's a bit early",
            de: 'schöne Stimme, aber etwas früh',
            ar: 'صوتك جميل، لكن الوقت مبكر قليلًا',
            fr: 'jolie voix, mais un peu tôt',
            es: 'qué buena voz, pero es un poco temprano',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'çok teşekkür ederim 🎤',
            en: 'aw, thank you so much 🎤',
            de: 'oh, vielen Dank 🎤',
            ar: 'شكرًا جزيلًا 🎤',
            fr: 'oh, merci beaucoup 🎤',
            es: '¡muchas gracias! 🎤',
          },
        },
      ],
    },
    caption: {
      tr: 'Sadece iltifat kısmını okudum',
      en: 'I only read the compliment part',
      de: 'Ich hab nur das Kompliment gelesen',
      ar: 'قرأت جزء المديح فقط',
      fr: "J'ai lu que le compliment",
      es: 'Solo leí la parte del cumplido',
    },
  },
  {
    emoji: '🛠️',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Teknik servis',
        en: 'Repair service',
        de: 'Kundendienst',
        ar: 'خدمة الصيانة',
        fr: 'Service technique',
        es: 'Servicio técnico',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'makine su kaçırıyor, ne zaman gelirsiniz?',
            en: "the washer's leaking, when can you come?",
            de: 'die Waschmaschine leckt, wann kommen Sie?',
            ar: 'الغسالة تسرّب الماء، متى تأتون؟',
            fr: 'la machine fuit, vous passez quand ?',
            es: 'la lavadora gotea, ¿cuándo pueden venir?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yarın 09.00 ile 18.00 arası',
            en: 'tomorrow, between 9 am and 6 pm',
            de: 'morgen zwischen 9 und 18 Uhr',
            ar: 'غدًا بين التاسعة صباحًا والسادسة مساءً',
            fr: 'demain entre 9 h et 18 h',
            es: 'mañana entre las 9 y las 18',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'biraz daraltabilir miyiz?',
            en: 'could you narrow it down a bit?',
            de: 'geht es etwas genauer?',
            ar: 'هل يمكن تحديد وقت أدق؟',
            fr: 'vous pouvez être plus précis ?',
            es: '¿pueden ser más precisos?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tabii: yarın',
            en: 'sure: tomorrow',
            de: 'klar: morgen',
            ar: 'طبعًا: غدًا',
            fr: 'bien sûr : demain',
            es: 'claro: mañana',
          },
        },
      ],
    },
    caption: {
      tr: 'Bütün gün kapının dibinde bekledim',
      en: 'Spent the whole day waiting by the door',
      de: 'Den ganzen Tag an der Tür gewartet',
      ar: 'قضيت اليوم كله بجانب الباب',
      fr: 'Journée entière à guetter la sonnette',
      es: 'Pasé todo el día esperando junto a la puerta',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Yeni koltuk kapıdan geçmiyor. Plan ne?',
        en: "The new couch won't fit through the door. Plan?",
        de: 'Das neue Sofa passt nicht durch die Tür. Plan?',
        ar: 'الكنبة الجديدة لا تمرّ من الباب. ما الخطة؟',
        fr: 'Le canapé neuf ne passe pas la porte. Le plan ?',
        es: 'El sofá nuevo no pasa por la puerta. ¿Plan?',
      },
      options: [
        {
          tr: 'Ayaklarını sökeriz',
          en: 'Take the legs off',
          de: 'Füße abschrauben',
          ar: 'نفكّ أرجلها',
          fr: 'On démonte les pieds',
          es: 'Quitarle las patas',
        },
        {
          tr: 'Pencereden alırız',
          en: 'Through the window',
          de: 'Durchs Fenster',
          ar: 'ندخلها من النافذة',
          fr: 'Par la fenêtre',
          es: 'Por la ventana',
        },
        {
          tr: 'Koridorda yaşar',
          en: 'It lives in the hall',
          de: 'Es wohnt im Flur',
          ar: 'ستعيش في الممر',
          fr: "Il vit dans l'entrée",
          es: 'Vive en el pasillo',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Koridor artık oturma odası',
      en: 'The hallway is the living room now',
      de: 'Der Flur ist jetzt das Wohnzimmer',
      ar: 'الممر صار غرفة الجلوس',
      fr: "L'entrée, c'est le salon maintenant",
      es: 'El pasillo ya es la sala de estar',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Nevresimi nasıl takıyorsun?',
        en: 'How do you put on a duvet cover?',
        de: 'Wie beziehst du deine Bettdecke?',
        ar: 'كيف تضع غطاء اللحاف؟',
        fr: 'Comment tu mets une housse de couette ?',
        es: '¿Cómo pones la funda del edredón?',
      },
      options: [
        {
          tr: 'Köşelerden tutarak',
          en: 'Corner by corner',
          de: 'Ecke für Ecke',
          ar: 'زاوية بعد زاوية',
          fr: 'Coin par coin',
          es: 'Esquina por esquina',
        },
        {
          tr: 'İçine girerek',
          en: 'I climb inside it',
          de: 'Ich krieche rein',
          ar: 'أدخل فيه بنفسي',
          fr: 'Je me glisse dedans',
          es: 'Me meto dentro',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Nevresimin içinde 10 dakika kayboldum',
      en: 'Got lost in the duvet cover for 10 minutes',
      de: 'War 10 Minuten im Bettbezug verschollen',
      ar: 'ضعت داخل غطاء اللحاف 10 دقائق',
      fr: '10 minutes à me débattre dans la housse',
      es: 'Diez minutos dentro de la funda y sin salida',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Zil çaldı, pijamalısın. Sen:',
        en: "Doorbell rings. You're in pajamas. You:",
        de: 'Es klingelt, du bist im Pyjama. Du:',
        ar: 'رنّ الجرس وأنت بالبيجامة. ماذا تفعل؟',
        fr: 'Ça sonne, tu es en pyjama. Tu fais quoi ?',
        es: 'Suena el timbre y estás en pijama. Tú:',
      },
      options: [
        {
          tr: 'Üstümü değiştiririm',
          en: 'Change real quick',
          de: 'Schnell umziehen',
          ar: 'أبدّل ملابسي',
          fr: 'Je me change',
          es: 'Me cambio rápido',
        },
        {
          tr: 'Sadece kafamı uzatırım',
          en: 'Just poke my head out',
          de: 'Nur Kopf rausstrecken',
          ar: 'أُخرج رأسي فقط',
          fr: 'Je passe juste la tête',
          es: 'Solo asomo la cabeza',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kurye beni sadece kafa olarak tanıyor',
      en: 'The delivery guy only knows me as a head',
      de: 'Der Paketbote kennt nur meinen Kopf',
      ar: 'عامل التوصيل لا يعرف مني إلا رأسي',
      fr: 'Le livreur ne connaît que ma tête',
      es: 'El repartidor solo conoce mi cabeza',
    },
  },
  {
    emoji: '👟',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'KAPIDAKİ AYAKKABILAR',
        en: 'SHOES BY THE DOOR',
        de: 'SCHUHE AN DER TÜR',
        ar: 'الأحذية عند الباب',
        fr: "CHAUSSURES À L'ENTRÉE",
        es: 'ZAPATOS EN LA ENTRADA',
      },
      value: { tr: '31', en: '31', de: '31', ar: '31', fr: '31', es: '31' },
      shape: 'rise',
      axis: 'months',
    },
    caption: {
      tr: 'Evde sadece 3 kişi yaşıyoruz',
      en: 'Only 3 of us live here',
      de: 'Hier wohnen nur 3 Leute',
      ar: 'نسكن هنا 3 أشخاص فقط',
      fr: "On n'est que 3 à vivre ici",
      es: 'Aquí solo vivimos 3',
    },
  },
  {
    emoji: '🔄',
    user: ACCOUNTS.plain,
    body: {
      format: 'chart',
      title: {
        tr: 'MOBİLYALARIN YERİ',
        en: 'WHERE MY FURNITURE IS',
        de: 'WO MEINE MÖBEL STEHEN',
        ar: 'أماكن الأثاث',
        fr: 'PLACE DE MES MEUBLES',
        es: 'LUGAR DE MIS MUEBLES',
      },
      value: null,
      shape: 'zigzag',
      axis: 'months',
    },
    caption: {
      tr: 'Ayda bir, gece 2’de, tek başıma',
      en: 'Once a month. At 2 a.m. By myself.',
      de: 'Einmal im Monat. Um 2 Uhr nachts. Allein.',
      ar: 'مرة في الشهر، في الثانية ليلًا، وحدي',
      fr: 'Une fois par mois. À 2 h du matin. Sans aide.',
      es: 'Una vez al mes. A las 2 a. m. Sin ayuda.',
    },
  },
  {
    emoji: '🪴',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: { tr: 'ÇİÇEKÇİ', en: 'FLOWER SHOP', de: 'BLUMENLADEN', ar: 'محل الزهور', fr: 'FLEURISTE', es: 'VIVERO' },
      items: [
        {
          tr: 'BAKIM İSTEMEZ BİTKİ',
          en: 'LOW-MAINTENANCE PLANT',
          de: 'PFLEGELEICHTE PFLANZE',
          ar: 'نبتة لا تحتاج عناية',
          fr: 'PLANTE SANS ENTRETIEN',
          es: 'PLANTA SIN CUIDADOS',
        },
      ],
    },
    caption: {
      tr: 'Meydan okuma kabul edildi.',
      en: 'Challenge accepted.',
      de: 'Herausforderung angenommen.',
      ar: 'التحدي مقبول.',
      fr: 'Défi accepté.',
      es: 'Reto aceptado.',
    },
  },
  {
    emoji: '📚',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'MOBİLYA MAĞAZASI',
        en: 'FURNITURE STORE',
        de: 'MÖBELHAUS',
        ar: 'متجر الأثاث',
        fr: 'MAGASIN DE MEUBLES',
        es: 'MUEBLERÍA',
      },
      items: [
        {
          tr: 'KİTAPLIK (KENDİN KUR)',
          en: 'FLAT-PACK BOOKCASE',
          de: 'REGAL ZUM SELBSTBAU',
          ar: 'مكتبة (تركيب ذاتي)',
          fr: 'BIBLIOTHÈQUE À MONTER',
          es: 'ESTANTERÍA PARA ARMAR',
        },
        {
          tr: 'SABIR (STOKTA YOK)',
          en: 'PATIENCE (SOLD OUT)',
          de: 'GEDULD (AUSVERKAUFT)',
          ar: 'الصبر (نفد من المخزون)',
          fr: 'PATIENCE (ÉPUISÉE)',
          es: 'PACIENCIA (AGOTADA)',
        },
      ],
    },
    caption: {
      tr: 'Kutu 30 dakika diyor. 4. saatteyim.',
      en: "The box says 30 minutes. I'm on hour 4.",
      de: 'Laut Karton 30 Minuten. Ich bin bei Stunde 4.',
      ar: 'العلبة تقول 30 دقيقة… وأنا في الساعة الرابعة',
      fr: "Le carton dit 30 min. J'en suis à 4 h.",
      es: 'La caja dice 30 minutos. Voy por la hora 4.',
    },
  },
  {
    emoji: '🧴',
    user: ACCOUNTS.hacks,
    body: {
      format: 'receipt',
      store: {
        tr: 'TEMİZLİK MALZEMESİ',
        en: 'CLEANING SUPPLIES',
        de: 'DROGERIE',
        ar: 'أدوات التنظيف',
        fr: 'DROGUERIE',
        es: 'TIENDA DE LIMPIEZA',
      },
      items: [
        {
          tr: 'ODA SPREYİ (LAVANTA)',
          en: 'ROOM SPRAY (LAVENDER)',
          de: 'RAUMSPRAY (LAVENDEL)',
          ar: 'معطّر جو (خزامى)',
          fr: 'DÉSODORISANT LAVANDE',
          es: 'AROMATIZANTE LAVANDA',
        },
      ],
    },
    caption: {
      tr: 'Temizlemedim ama ev lavanta kokuyor',
      en: "Didn't clean. But it smells like lavender.",
      de: 'Nicht geputzt. Riecht aber nach Lavendel.',
      ar: 'لم أنظّف… لكن البيت يفوح بالخزامى',
      fr: 'Pas fait le ménage. Mais ça sent la lavande.',
      es: 'No limpié, pero huele a lavanda.',
    },
  },
  {
    emoji: '🏢',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'APARTMAN TOPLANTISI',
        en: 'BUILDING MEETING',
        de: 'HAUSVERSAMMLUNG',
        ar: 'اجتماع سكان العمارة',
        fr: 'RÉUNION DE COPROPRIÉTÉ',
        es: 'JUNTA DE VECINOS',
      },
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'saat boyunca kapı önündeki paspasın rengi konuşuldu',
        en: 'hours spent debating the color of the doormat.',
        de: 'Stunden Diskussion über die Farbe der Fußmatte.',
        ar: 'ساعات من النقاش حول لون ممسحة الباب',
        fr: 'heures à débattre de la couleur du paillasson.',
        es: 'horas debatiendo el color de la alfombra de la entrada.',
      },
    },
    caption: {
      tr: 'Çatı akıyor ama öncelik paspas',
      en: 'The roof leaks, but the doormat comes first',
      de: 'Das Dach ist undicht, aber erst die Fußmatte',
      ar: 'السقف يسرّب الماء… لكن الأولوية للممسحة',
      fr: "Le toit fuit, mais le paillasson d'abord",
      es: 'El techo gotea, pero primero la alfombra',
    },
  },
  {
    emoji: '📔',
    user: ACCOUNTS.home,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '4', en: '4', de: '4', ar: '4', fr: '4', es: '4' },
      text: {
        tr: 'saat dolabı toplayacaktın; eski fotoğraflara baktın',
        en: 'hours meant for tidying the closet. Spent on old photos.',
        de: 'Stunden zum Schrankaufräumen. Verbracht mit alten Fotos.',
        ar: 'ساعات لترتيب الخزانة… قضيتها مع الصور القديمة',
        fr: "heures pour ranger l'armoire. Passées sur de vieilles photos.",
        es: 'horas para ordenar el armario. Las pasaste viendo fotos viejas.',
      },
    },
    caption: {
      tr: 'Dolap hâlâ dağınık ama çok duygulandım',
      en: 'Closet still a mess. Heart very full.',
      de: 'Schrank noch chaotisch. Herz ganz voll.',
      ar: 'الخزانة ما زالت فوضى… لكن قلبي ممتلئ',
      fr: "Toujours le bazar, mais que d'émotions.",
      es: 'El armario sigue igual. Pero qué nostalgia.',
    },
  },
  {
    emoji: '📋',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'TEMİZLİK ÇİZELGESİ',
        en: 'CHORE CHART',
        de: 'PUTZPLAN',
        ar: 'جدول التنظيف',
        fr: 'PLANNING DU MÉNAGE',
        es: 'TURNOS DE LIMPIEZA',
      },
      big: { tr: '0', en: '0', de: '0', ar: '0', fr: '0', es: '0' },
      text: {
        tr: 'kez uyuldu; 8 aydır buzdolabında asılı duruyor',
        en: 'times followed. On the fridge for 8 months.',
        de: 'Mal eingehalten. Hängt seit 8 Monaten am Kühlschrank.',
        ar: 'مرة التُزم به… وهو معلّق على الثلاجة منذ 8 أشهر',
        fr: 'fois respecté. Sur le frigo depuis 8 mois.',
        es: 'veces se cumplió. Lleva 8 meses en el refrigerador.',
      },
    },
    caption: {
      tr: 'Evin en düzenli şeyi o çizelge',
      en: 'The tidiest thing in the house is that chart',
      de: 'Das Ordentlichste in der Wohnung: der Plan',
      ar: 'أكثر شيء مرتّب في البيت هو ذلك الجدول',
      fr: "Le truc le plus rangé de l'appart : le planning",
      es: 'Lo más ordenado de la casa es esa tabla',
    },
  },
  {
    emoji: '🧹',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'EV İŞLERİ TIER LIST',
        en: 'CHORES TIER LIST',
        de: 'HAUSHALTS-TIER-LIST',
        ar: 'تصنيف أعمال البيت',
        fr: 'TIER LIST DES CORVÉES',
        es: 'TIER LIST DE QUEHACERES',
      },
      rows: [['🌿', '🛋️'], ['👕', '🧦'], ['🍽️', '🗑️'], ['👔', '🧊']],
    },
    caption: {
      tr: 'Ütü C’de, çünkü buruşuk da bir tarz',
      en: 'Ironing is C. Wrinkled is a look.',
      de: 'Bügeln ist C. Knitter-Look ist auch ein Stil.',
      ar: 'الكيّ في آخر القائمة… فالتجاعيد موضة أيضًا',
      fr: "Repassage en C. Le froissé, c'est un style.",
      es: 'Planchar va en la C. Lo arrugado también es estilo.',
    },
  },
  {
    emoji: '🪶',
    user: ACCOUNTS.asmr,
    body: {
      format: 'tier',
      title: {
        tr: 'TEMİZLİK ALETLERİ TIER LIST',
        en: 'CLEANING TOOLS TIER LIST',
        de: 'PUTZZEUG-TIER-LIST',
        ar: 'تصنيف أدوات التنظيف',
        fr: 'TIER LIST DU MATOS MÉNAGE',
        es: 'TIER LIST DE LIMPIEZA',
      },
      rows: [['🧽', '🧴'], ['🧹', '🪣'], ['🧤'], ['🪶']],
    },
    caption: {
      tr: 'Tüylü toz alıcı: tozu sadece taşıyor',
      en: 'Feather dusters just move the dust around',
      de: 'Staubwedel verteilen den Staub nur um',
      ar: 'منفضة الريش تنقل الغبار من مكان لآخر فقط',
      fr: 'Le plumeau déplace juste la poussière',
      es: 'El plumero solo cambia el polvo de lugar',
    },
  },
  {
    emoji: '🌬️',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🏡',
        app: {
          tr: 'Alt kat komşu',
          en: 'Neighbor below',
          de: 'Nachbarin unten',
          ar: 'جارة الطابق السفلي',
          fr: 'Voisine du dessous',
          es: 'Vecina de abajo',
        },
        text: {
          tr: 'Pijamanız bizim balkona düştü 🙂',
          en: 'Your pajamas landed on our balcony 🙂',
          de: 'Ihr Pyjama ist auf unserem Balkon 🙂',
          ar: 'سقطت بيجامتك على شرفتنا 🙂',
          fr: 'Votre pyjama est sur notre balcon 🙂',
          es: 'Su pijama cayó en nuestro balcón 🙂',
        },
      },
    },
    caption: {
      tr: 'O pijama artık onların',
      en: 'Those pajamas are theirs now',
      de: 'Der Pyjama gehört jetzt ihnen',
      ar: 'البيجامة صارت لهم الآن',
      fr: 'Ce pyjama est à eux maintenant',
      es: 'Ese pijama ya es de ellos',
    },
  },
  {
    emoji: '🚰',
    user: ACCOUNTS.home,
    body: {
      format: 'notifications',
      first: {
        icon: '📢',
        app: {
          tr: 'Apartman yönetimi',
          en: 'Building manager',
          de: 'Hausverwaltung',
          ar: 'إدارة العمارة',
          fr: 'Syndic',
          es: 'Administración',
        },
        text: {
          tr: 'Yarın 09.00–17.00 arası sular kesik',
          en: 'Water off tomorrow, 9 am to 5 pm',
          de: 'Morgen 9–17 Uhr kein Wasser',
          ar: 'المياه مقطوعة غدًا من 9 إلى 5',
          fr: "Coupure d'eau demain de 9 h à 17 h",
          es: 'Mañana no habrá agua de 9 a 17 h',
        },
      },
    },
    caption: {
      tr: 'Evdeki bütün tencereleri doldurdum',
      en: 'Filled every pot in the house',
      de: 'Hab jeden Topf im Haus gefüllt',
      ar: 'ملأت كل القدور في البيت',
      fr: "J'ai rempli toutes les casseroles",
      es: 'Llené todas las ollas de la casa',
    },
  },
  {
    emoji: '🩹',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hiçbir şey sonsuza dek sürmez. Bantla yaptığım tamirler hariç.',
        en: 'Nothing lasts forever. Except the stuff I fixed with tape.',
        de: 'Nichts hält ewig. Außer dem, was ich mit Klebeband repariert habe.',
        ar: 'لا شيء يدوم… إلا ما أصلحته بالشريط اللاصق.',
        fr: "Rien n'est éternel. Sauf mes réparations au ruban adhésif.",
        es: 'Nada es para siempre. Excepto lo que arreglé con cinta.',
      },
    },
    caption: {
      tr: 'Dört yıldır sapasağlam',
      en: 'Still holding strong after 4 years',
      de: 'Hält seit vier Jahren',
      ar: 'صامد منذ 4 سنوات',
      fr: 'Ça tient depuis quatre ans',
      es: 'Aguanta desde hace cuatro años',
    },
  },
  {
    emoji: '🗃️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Buna dağınıklık deme. Sadece benim anladığım bir düzen.',
        en: "Don't call it a mess. It's a system only I understand.",
        de: 'Das ist kein Chaos. Das ist ein System, das nur ich verstehe.',
        ar: 'لا تسمّها فوضى… إنه نظام لا يفهمه أحد غيري.',
        fr: "Ce n'est pas le bazar. C'est un ordre que personne d'autre ne comprend.",
        es: 'No es desorden. Es un sistema que solo yo entiendo.',
      },
    },
    caption: {
      tr: 'Makasın yerini bir tek ben biliyorum',
      en: 'Only I know where the scissors are',
      de: 'Nur ich weiß, wo die Schere ist',
      ar: 'أنا وحدي أعرف مكان المقص',
      fr: "Il n'y a que moi qui sais où sont les ciseaux",
      es: 'Solo yo sé dónde están las tijeras',
    },
  },
  {
    emoji: '🔌',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Az eşya, huzurlu zihin. — Bir kutu kabloyu 3 evdir taşıyan biri',
        en: 'Less stuff, more peace. — Me, moving a box of cables for the 3rd time',
        de: 'Weniger Zeug, mehr Ruhe. — Ich, mit meiner Kabelkiste im 3. Umzug',
        ar: 'أشياء أقل، راحة أكثر. — أنا، أنقل صندوق الأسلاك للمرة الثالثة',
        fr: 'Vivre léger. — Moi, 3e déménagement avec ma boîte de câbles',
        es: 'Menos cosas, más paz. — Yo, en mi 3.ª mudanza con la caja de cables',
      },
    },
    caption: {
      tr: 'Hangisi neyin kablosu, kimse bilmiyor',
      en: 'Nobody knows what any of them are for',
      de: 'Keiner weiß, wofür die sind',
      ar: 'لا أحد يعرف لأي جهاز هذه الأسلاك',
      fr: 'Personne ne sait à quoi ils servent',
      es: 'Nadie sabe de qué son',
    },
  },
  {
    emoji: '🚪',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Bir kapı kapanınca başka bir kapı açılır. Cereyan yapıyor çünkü.',
        en: "When one door closes, another opens. It's the draft.",
        de: 'Wenn sich eine Tür schließt, geht eine andere auf. Es zieht halt.',
        ar: 'إذا أُغلق باب فُتح آخر… إنه تيار الهواء.',
        fr: "Quand une porte se ferme, une autre s'ouvre. C'est le courant d'air.",
        es: 'Cuando una puerta se cierra, otra se abre. Es la corriente de aire.',
      },
    },
    caption: {
      tr: 'Bütün evin kapıları aynı anda çarptı',
      en: 'Every door in the house just slammed at once',
      de: 'Gerade sind alle Türen gleichzeitig zugeknallt',
      ar: 'أُغلقت كل أبواب البيت دفعة واحدة',
      fr: 'Toutes les portes ont claqué en même temps',
      es: 'Todas las puertas se cerraron de golpe',
    },
  },
];

export const HOME_LIKE: readonly Draft[] = [
  {
    emoji: '🧂',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'baharatları alfabetik dizdim. huzur.',
      en: 'alphabetized my spice rack. inner peace.',
      de: 'gewürze alphabetisch sortiert. innerer frieden.',
      ar: 'رتّبت البهارات أبجديًا… سلام داخلي',
      fr: 'épices rangées par ordre alphabétique. la paix.',
      es: 'ordené mis especias alfabéticamente. paz interior.',
    },
  },
  {
    emoji: '🌷',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'komşularla bahçeye 40 lale diktik!!',
      en: 'planted 40 tulips out front with the neighbors!!',
      de: 'mit den nachbarn 40 tulpen vorm haus gepflanzt!!',
      ar: 'زرعنا 40 زهرة توليب مع الجيران أمام العمارة!!',
      fr: '40 tulipes plantées avec les voisins !!',
      es: '¡¡sembramos 40 tulipanes con los vecinos!!',
    },
  },
  {
    emoji: '🪟',
    user: ACCOUNTS.onur,
    body: { format: 'scene' },
    caption: {
      tr: 'perdeleri sonunda taktım!! (8 ay sürdü)',
      en: 'finally hung the curtains!! (took 8 months)',
      de: 'endlich vorhänge aufgehängt!! (hat 8 monate gedauert)',
      ar: 'علّقت الستائر أخيرًا!! (استغرق الأمر 8 أشهر)',
      fr: 'rideaux enfin posés !! (ça a pris 8 mois)',
      es: '¡¡por fin colgué las cortinas!! (tardé 8 meses)',
    },
  },
  {
    emoji: '🏠',
    user: ACCOUNTS.berk,
    body: { format: 'scene' },
    caption: {
      tr: 'ev arkadaşımla 1 yıl!! tek tartışma: çöp',
      en: 'one year with my roommate!! only argument: the trash',
      de: 'ein jahr WG!! einziger streit: der müll',
      ar: 'سنة كاملة مع زميل السكن!! خلافنا الوحيد: القمامة',
      fr: 'un an de coloc !! seule dispute : les poubelles',
      es: '¡¡un año de convivencia!! única discusión: la basura',
    },
  },
  {
    emoji: '🔑',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'benim kapım',
        en: 'my own door',
        de: 'meine eigene tür',
        ar: 'بابي أنا',
        fr: 'ma porte à moi',
        es: 'mi propia puerta',
      },
    },
    caption: {
      tr: 'ilk kez kendi evimin kapısını açtım',
      en: 'unlocked the door to my own place for the first time',
      de: 'zum ersten mal meine eigene wohnungstür aufgeschlossen',
      ar: 'فتحت باب بيتي الخاص لأول مرة',
      fr: "j'ai ouvert la porte de chez moi pour la première fois",
      es: 'abrí la puerta de mi propia casa por primera vez',
    },
  },
  {
    emoji: '🌺',
    user: ACCOUNTS.deniz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sabrın çiçeği',
        en: 'patience, in bloom',
        de: 'geduld in blüte',
        ar: 'زهرة الصبر',
        fr: 'la fleur de la patience',
        es: 'la flor de la paciencia',
      },
    },
    caption: {
      tr: 'çiçeğim 3 yıl sonra ilk kez açtı!!',
      en: 'my plant bloomed for the first time in 3 years!!',
      de: 'meine pflanze blüht zum ersten mal seit 3 jahren!!',
      ar: 'نبتتي أزهرت لأول مرة منذ 3 سنوات!!',
      fr: 'ma plante a fleuri pour la première fois en 3 ans !!',
      es: '¡¡mi planta floreció por primera vez en 3 años!!',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'hoş geldin komşu',
        en: 'welcome, neighbor',
        de: 'willkommen, nachbarin',
        ar: 'أهلًا بك يا جارتنا',
        fr: 'bienvenue, voisine',
        es: 'bienvenida, vecina',
      },
    },
    caption: {
      tr: 'üst kat komşum kapıya kurabiye bırakmış!!',
      en: 'the upstairs neighbor left cookies at my door!!',
      de: 'die nachbarin von oben hat kekse vor die tür gestellt!!',
      ar: 'جارة الطابق العلوي تركت لي بسكويتًا أمام الباب!!',
      fr: "la voisine du dessus m'a laissé des biscuits !!",
      es: '¡¡la vecina de arriba me dejó galletas en la puerta!!',
    },
  },
  {
    emoji: '✨',
    user: ACCOUNTS.baris,
    body: {
      format: 'polaroid',
      note: {
        tr: 'zemin bulundu',
        en: 'floor: found',
        de: 'boden gefunden',
        ar: 'عُثر على الأرضية',
        fr: 'sol retrouvé',
        es: 'suelo encontrado',
      },
    },
    caption: {
      tr: 'odamı topladım, altından parke çıktı',
      en: "cleaned my room. turns out there's a floor",
      de: 'zimmer aufgeräumt. da ist ja ein boden!',
      ar: 'رتّبت غرفتي… واكتشفت أن فيها أرضية',
      fr: 'chambre rangée : en fait, il y a un sol',
      es: 'ordené mi habitación y apareció el suelo',
    },
  },
  {
    emoji: '🧽',
    user: ACCOUNTS.zeynep,
    body: { format: 'dump', emojis: ['🧽', '🪣', '🧤', '🌼', '🎶'] },
    caption: {
      tr: 'bahar temizliği: ev parlıyor, ben bittim',
      en: 'spring cleaning dump: house sparkling, me exhausted',
      de: 'frühjahrsputz-dump: wohnung glänzt, ich bin fertig',
      ar: 'تنظيف الربيع: البيت يلمع… وأنا منهكة',
      fr: 'dump grand ménage : la maison brille, moi je suis KO',
      es: 'limpieza de primavera: la casa brilla y yo estoy agotada',
    },
  },
  {
    emoji: '🪴',
    user: ACCOUNTS.ipek,
    body: { format: 'dump', emojis: ['🪴', '🌿', '🪑', '☕️', '💡', '🌙'] },
    caption: {
      tr: 'balkonu yeniledim, artık orada yaşıyorum',
      en: 'redid the balcony. living out there now',
      de: 'balkon neu gemacht, ich wohn jetzt quasi draußen',
      ar: 'جدّدت شرفتي… وصرت أعيش فيها',
      fr: 'balcon refait, maintenant je vis dehors',
      es: 'renové el balcón y ahora prácticamente vivo ahí',
    },
  },
  {
    emoji: '🔨',
    user: ACCOUNTS.kaan,
    body: { format: 'dump', emojis: ['🔨', '🪛', '🧰', '💡', '📏'] },
    caption: {
      tr: 'tamir günü: 3’ünü onardım, 1’ini kırdım',
      en: 'fix-it day: fixed 3 things, broke 1',
      de: 'reparaturtag: 3 sachen repariert, 1 kaputt gemacht',
      ar: 'يوم التصليح: أصلحت 3 أشياء وكسرت واحدًا',
      fr: 'journée bricolage : 3 trucs réparés, 1 cassé',
      es: 'día de arreglos: arreglé 3 cosas y rompí 1',
    },
  },
];

export const HOME_HOLD: readonly Draft[] = [
  {
    emoji: '🚿',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsane duş: sıcak su hiç bitmedi',
      en: 'Legendary shower: the hot water never ran out',
      de: 'Legendäre Dusche: Das heiße Wasser ging nie aus',
      ar: 'دشّ أسطوري: الماء الساخن لم ينفد أبدًا',
      fr: "Douche légendaire : l'eau chaude n'a jamais manqué",
      es: 'Ducha legendaria: el agua caliente nunca se acabó',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ev arkadaşı bulaşığı yıkamış. Sormadan.',
      en: 'Your roommate did the dishes. Unasked.',
      de: 'Dein Mitbewohner hat gespült. Ungefragt.',
      ar: 'زميلك في السكن غسل الأطباق… دون أن تطلب',
      fr: "Ton coloc a fait la vaisselle. Sans qu'on lui demande.",
      es: 'Tu compañero lavó los platos. Sin que le pidieras.',
    },
  },
  {
    emoji: '🔩',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Montaj bitti. Tek bir vida bile artmadı.',
      en: 'Assembly done. Not a single screw left over.',
      de: 'Aufgebaut. Keine einzige Schraube übrig.',
      ar: 'انتهى التركيب… ولم يتبقَّ برغي واحد',
      fr: 'Montage terminé. Pas une seule vis en trop.',
      es: 'Armado terminado. No sobró ni un tornillo.',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Makinede son 1 dakika… bip sesinde bırak',
      en: 'Washer says 1 min left… let go when it beeps',
      de: 'Waschmaschine: noch 1 Minute… beim Piepen loslassen',
      ar: 'بقيت دقيقة في الغسالة… اترك عند الصافرة',
      fr: "Plus qu'une minute de lessive… lâche au bip",
      es: 'Queda 1 min de lavado… suelta con el pitido',
    },
  },
  {
    emoji: '📦',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Taşınma kolisi: aradığın şey en üstte!',
      en: 'Moving box: what you need is right on top!',
      de: 'Umzugskarton: Das Gesuchte liegt ganz oben!',
      ar: 'صندوق الانتقال: ما تبحث عنه في الأعلى تمامًا!',
      fr: 'Carton de déménagement : ce que tu cherches est en haut !',
      es: 'Caja de mudanza: ¡lo que buscas está arriba!',
    },
  },
  {
    emoji: '🤫',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsane komşu: 2 yıldır tek bir ses yok',
      en: 'Legendary neighbor: not one sound in 2 years',
      de: 'Legendärer Nachbar: seit 2 Jahren kein Mucks',
      ar: 'جار أسطوري: لا صوت واحد منذ سنتين',
      fr: 'Voisin légendaire : pas un bruit en 2 ans',
      es: 'Vecino legendario: ni un ruido en 2 años',
    },
  },
  {
    emoji: '🚛',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Çöpü çıkardın, çöpçüler tam o an geldi',
      en: 'Took the trash out right as the truck pulled up',
      de: 'Müll rausgebracht – genau als die Müllabfuhr kam',
      ar: 'أخرجت القمامة… ووصلت شاحنة النظافة في اللحظة نفسها',
      fr: 'Poubelle sortie pile quand le camion passe',
      es: 'Sacaste la basura justo cuando pasó el camión',
    },
  },
];

export const HOME_FREEZE: readonly Draft[] = [
  {
    emoji: '⚡',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: { tr: 'AŞIRI YÜK', en: 'OVERLOAD', de: 'ÜBERLASTUNG', ar: 'حمل زائد', fr: 'SURCHARGE', es: 'SOBRECARGA' },
      small: {
        tr: 'SİGORTA ATMAK ÜZERE',
        en: 'BREAKER ABOUT TO TRIP',
        de: 'SICHERUNG FLIEGT GLEICH',
        ar: 'القاطع على وشك الفصل',
        fr: 'LES PLOMBS VONT SAUTER',
        es: 'SE VA A CORTAR LA LUZ',
      },
    },
    caption: {
      tr: 'Bir fiş daha takma.',
      en: "Don't plug in one more thing.",
      de: 'Keinen Stecker mehr einstecken.',
      ar: 'لا تصل أي جهاز آخر.',
      fr: 'Ne branche plus rien.',
      es: 'No conectes nada más.',
    },
    headline: {
      tr: 'Fırın, ütü ve çamaşır makinesi çalışıyor',
      en: 'Oven, iron and washer: all on at once',
      de: 'Ofen, Bügeleisen und Waschmaschine an',
      ar: 'الفرن والمكواة والغسالة تعمل معًا',
      fr: 'Four, fer et machine à laver en marche',
      es: 'Horno, plancha y lavadora a la vez',
    },
  },
  {
    emoji: '🏺',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: { tr: 'KIRILACAK EŞYA', en: 'FRAGILE', de: 'ZERBRECHLICH', ar: 'قابل للكسر', fr: 'FRAGILE', es: 'FRÁGIL' },
      small: {
        tr: 'BU TARAF YUKARI',
        en: 'THIS SIDE UP',
        de: 'DIESE SEITE OBEN',
        ar: 'هذا الجانب للأعلى',
        fr: 'CE CÔTÉ EN HAUT',
        es: 'ESTE LADO ARRIBA',
      },
    },
    caption: {
      tr: 'Nefesini tut. Kıpırdama.',
      en: 'Hold your breath. Freeze.',
      de: 'Luft anhalten. Nicht bewegen.',
      ar: 'احبس أنفاسك. لا تتحرك.',
      fr: 'Retiens ton souffle. Bouge pas.',
      es: 'Aguanta la respiración. No te muevas.',
    },
    headline: {
      tr: 'Nakliyeci koliyi ters tutuyor',
      en: 'The mover is holding the box upside down',
      de: 'Der Möbelpacker hält den Karton verkehrt',
      ar: 'عامل النقل يحمل الصندوق مقلوبًا',
      fr: "Le déménageur tient le carton à l'envers",
      es: 'El de la mudanza carga la caja al revés',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'MİSAFİR YATAĞI',
        en: 'GUEST BED',
        de: 'GÄSTEBETT',
        ar: 'سرير الضيوف',
        fr: "LIT D'APPOINT",
        es: 'CAMA INFLABLE',
      },
      small: {
        tr: 'HAVA KAÇIRIYOR · DÖNMEYİN',
        en: 'LEAKING AIR · DO NOT ROLL',
        de: 'VERLIERT LUFT · NICHT DREHEN',
        ar: 'يفقد الهواء · لا تتقلّب',
        fr: 'SE DÉGONFLE · NE BOUGEZ PAS',
        es: 'SE DESINFLA · NO TE GIRES',
      },
    },
    caption: {
      tr: 'Dönme. Sabaha 4 saat var.',
      en: "Don't roll over. 4 hours till morning.",
      de: 'Nicht umdrehen. Noch 4 Stunden bis morgens.',
      ar: 'لا تتقلّب. بقيت 4 ساعات حتى الصباح.',
      fr: 'Te retourne pas. Encore 4 h avant le matin.',
      es: 'No te gires. Faltan 4 horas para el amanecer.',
    },
    headline: {
      tr: 'Hava yatağı yavaş yavaş sönüyor',
      en: 'The air mattress is slowly deflating',
      de: 'Die Luftmatratze verliert langsam Luft',
      ar: 'المرتبة الهوائية تفرغ ببطء',
      fr: 'Le matelas gonflable se dégonfle',
      es: 'El colchón inflable se está desinflando',
    },
  },
  {
    emoji: '🧫',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: { tr: 'AÇMAYIN', en: 'DO NOT OPEN', de: 'NICHT ÖFFNEN', ar: 'لا تفتحه', fr: 'NE PAS OUVRIR', es: 'NO ABRIR' },
      small: {
        tr: 'NE OLDUĞUNU KİMSE BİLMİYOR',
        en: 'NOBODY KNOWS WHAT IT IS',
        de: 'KEINER WEISS, WAS DAS IST',
        ar: 'لا أحد يعرف ما بداخله',
        fr: "PERSONNE NE SAIT CE QUE C'EST",
        es: 'NADIE SABE QUÉ ES',
      },
    },
    caption: {
      tr: 'Kapak kapalı kalsın.',
      en: 'The lid stays on.',
      de: 'Der Deckel bleibt zu.',
      ar: 'ليبقَ الغطاء مغلقًا.',
      fr: 'Le couvercle reste fermé.',
      es: 'La tapa se queda cerrada.',
    },
    headline: {
      tr: 'Buzdolabının dibinde gizemli bir kap var',
      en: 'A mystery box at the back of the fridge',
      de: 'Mysteriöse Dose hinten im Kühlschrank',
      ar: 'علبة غامضة في آخر الثلاجة',
      fr: 'Une boîte mystère au fond du frigo',
      es: 'Un misterio al fondo del refrigerador',
    },
  },
  {
    emoji: '🤖',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة الجلوس',
        fr: 'SALON',
        es: 'SALA DE ESTAR',
      },
    },
    caption: {
      tr: 'Rolünü bozma.',
      en: 'Stay in character.',
      de: 'Bleib in deiner Rolle.',
      ar: 'لا تخرج عن الدور.',
      fr: 'Reste dans ton rôle.',
      es: 'No salgas del personaje.',
    },
    headline: {
      tr: 'Robot süpürge seni mobilya sandı',
      en: "The robot vacuum thinks you're furniture",
      de: 'Der Saugroboter hält dich für ein Möbel',
      ar: 'المكنسة الآلية تظنك قطعة أثاث',
      fr: "L'aspi robot te prend pour un meuble",
      es: 'La aspiradora robot te cree un mueble',
    },
  },
  {
    emoji: '👁️',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'DAİRE KAPISI',
        en: 'FRONT DOOR',
        de: 'WOHNUNGSTÜR',
        ar: 'باب الشقة',
        fr: "PORTE D'ENTRÉE",
        es: 'PUERTA DE ENTRADA',
      },
    },
    caption: {
      tr: 'İkiniz de nefesinizi tutuyorsunuz.',
      en: "You're both holding your breath.",
      de: 'Ihr haltet beide die Luft an.',
      ar: 'كلاكما يحبس أنفاسه.',
      fr: 'Vous retenez tous les deux votre souffle.',
      es: 'Los dos contienen la respiración.',
    },
    headline: {
      tr: 'Kapı deliğinden baktın, o da bakıyor',
      en: 'Peephole check: someone is looking back',
      de: 'Durch den Spion schaut jemand zurück',
      ar: 'نظرت من عين الباب… وأحدهم ينظر إليك',
      fr: "Quelqu'un te fixe à travers le judas",
      es: 'Miraste por la mirilla y alguien te mira',
    },
  },
  {
    emoji: '🧐',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KARŞI APARTMAN',
        en: 'ACROSS THE STREET',
        de: 'GEGENÜBER',
        ar: 'العمارة المقابلة',
        fr: 'EN FACE',
        es: 'ENFRENTE',
      },
    },
    caption: {
      tr: 'El sallama. Kıpırdama.',
      en: "Don't wave. Don't move.",
      de: 'Nicht winken. Nicht bewegen.',
      ar: 'لا تلوّح. لا تتحرك.',
      fr: 'Fais pas coucou. Bouge pas.',
      es: 'No saludes. No te muevas.',
    },
    headline: {
      tr: 'Karşı komşu perdenin arkasından izliyor',
      en: 'The neighbor across is peeking out',
      de: 'Nachbarin von gegenüber schaut zu',
      ar: 'الجارة المقابلة تراقب من خلف الستارة',
      fr: "La voisine d'en face t'observe",
      es: 'La vecina de enfrente te está mirando',
    },
  },
  {
    emoji: '🪠',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: { tr: 'BANYO', en: 'BATHROOM', de: 'BADEZIMMER', ar: 'الحمّام', fr: 'SALLE DE BAIN', es: 'BAÑO' },
    },
    caption: {
      tr: 'Hiçbir şey bilmiyorsun. Kıpırdama.',
      en: "You know nothing. Don't move.",
      de: 'Du weißt von nichts. Nicht bewegen.',
      ar: 'أنت لا تعرف شيئًا. لا تتحرك.',
      fr: 'Tu ne sais rien. Bouge pas.',
      es: 'No sabes nada. No te muevas.',
    },
    headline: {
      tr: 'Tesisatçı senin bantlı tamirini buldu',
      en: 'The plumber just found your tape fix',
      de: 'Der Klempner entdeckt dein Klebeband',
      ar: 'السبّاك اكتشف إصلاحك بالشريط اللاصق',
      fr: 'Le plombier a trouvé ton rafistolage',
      es: 'El técnico encontró tu arreglo con cinta',
    },
  },
];
