import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';
import { HANDS_OFF } from '../classic';

/**
 * Weather, seasons and the outdoors: rain, snow, heat, the park, the beach, picnics, sunsets.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const OUTDOORS_SKIP: readonly Draft[] = [
  {
    emoji: '🌬️',
    user: ACCOUNTS.weather,
    body: { format: 'scene' },
    caption: {
      tr: 'Rüzgâr şemsiyemi çanak antene çevirdi',
      en: 'The wind turned my umbrella into a satellite dish',
      de: 'Der Wind hat meinen Schirm zur Satellitenschüssel gemacht',
      ar: 'حوّلت الريح مظلتي إلى طبق استقبال فضائي',
      fr: 'Le vent a changé mon parapluie en antenne parabolique',
      es: 'El viento convirtió mi paraguas en antena parabólica',
    },
  },
  {
    emoji: '🍂',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Yaprakları süpürdüm, ağaç rövanş istedi',
      en: 'Raked the leaves. The tree wants a rematch.',
      de: 'Laub geharkt. Der Baum will Revanche.',
      ar: 'جمعت الأوراق المتساقطة… فطلبت الشجرة جولة إعادة',
      fr: "Feuilles ratissées. L'arbre veut sa revanche.",
      es: 'Barrí las hojas. El árbol pide la revancha.',
    },
  },
  {
    emoji: '🌃',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Yıldız izledim. En parlak üçü uçaktı.',
      en: 'Went stargazing. The three brightest were planes.',
      de: 'Sterne geguckt. Die drei hellsten waren Flugzeuge.',
      ar: 'راقبت النجوم… وأسطع ثلاثة منها كانت طائرات',
      fr: 'Les trois étoiles les plus brillantes ? Des avions.',
      es: 'Miré las estrellas. Las tres más brillantes eran aviones.',
    },
  },
  {
    emoji: '🧴',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Önce güneş kremi, sonra kum. Pane oldum.',
      en: "Sunscreen first, then sand. I'm breaded now.",
      de: 'Erst Sonnencreme, dann Sand. Jetzt bin ich paniert.',
      ar: 'واقي الشمس أولًا ثم الرمل… صرت جاهزًا للقلي',
      fr: 'Crème solaire, puis sable. Me voilà pané.',
      es: 'Protector solar y luego arena. Listo para freír.',
    },
  },
  {
    emoji: '🌊',
    user: ACCOUNTS.weather,
    body: { format: 'scene' },
    caption: {
      tr: 'Denize serinlemeye girdim, çorba olmuş',
      en: 'Went in the sea to cool off. The sea is soup.',
      de: 'Ab ins Meer zum Abkühlen. Das Wasser: Suppe.',
      ar: 'نزلت إلى البحر لأتبرّد… فوجدته حساءً ساخنًا',
      fr: 'Un plongeon pour me rafraîchir. La mer ? Une soupe.',
      es: 'Entré al mar a refrescarme. El agua parecía caldo.',
    },
  },
  {
    emoji: '💦',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Parkta çimlere uzandım. Fıskiyeler açıldı.',
      en: 'Lay down on the park lawn. The sprinklers came on.',
      de: 'Kaum lag ich im Park im Gras, ging der Rasensprenger an.',
      ar: 'استلقيت على عشب الحديقة… فانطلقت مرشّات الري',
      fr: 'Sieste sur la pelouse du parc. Arrosage automatique.',
      es: 'Siesta en el césped del parque. Riego automático.',
    },
  },
  {
    emoji: '⛅',
    user: ACCOUNTS.weather,
    body: { format: 'scene' },
    caption: {
      tr: 'Parçalı bulutlu: bulutlu parça hep bende',
      en: 'Partly cloudy. I always get the cloudy part.',
      de: 'Teils bewölkt. Ich krieg immer den bewölkten Teil.',
      ar: 'غائم جزئيًا… والجزء الغائم من نصيبي دائمًا',
      fr: "Partiellement nuageux. Le nuage, c'est pour moi.",
      es: 'Parcialmente nublado. La parte nublada siempre es la mía.',
    },
  },
  {
    emoji: '⛰️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yürüyüş nasıldı? manzara güzel miydi?',
            en: 'how was the hike? nice views?',
            de: 'wie war die Wanderung? schöne Aussicht?',
            ar: 'كيف كانت رحلة المشي؟ هل المنظر جميل؟',
            fr: "c'était bien, la rando ? belle vue ?",
            es: '¿qué tal la caminata? ¿buena vista?',
          },
        },
        {
          from: 'me',
          text: { tr: 'bilmiyorum', en: 'no idea', de: 'keine Ahnung', ar: 'لا أعرف', fr: 'aucune idée', es: 'ni idea' },
        },
        {
          from: 'me',
          text: {
            tr: '5 saat boyunca önümdekinin çantasına baktım',
            en: '5 hours staring at the backpack ahead of me',
            de: '5 Stunden auf den Rucksack vor mir gestarrt',
            ar: '5 ساعات وأنا أحدّق في حقيبة من أمامي',
            fr: '5 heures à fixer le sac à dos devant moi',
            es: 'pasé 5 horas mirando una mochila',
          },
        },
      ],
    },
    caption: {
      tr: 'Manzara: kırmızı bir sırt çantası',
      en: 'The view: one red backpack',
      de: 'Die Aussicht: ein roter Rucksack',
      ar: 'المنظر: حقيبة ظهر حمراء',
      fr: 'La vue : un sac à dos rouge',
      es: 'La vista: una mochila roja',
    },
  },
  {
    emoji: '🌦️',
    user: ACCOUNTS.weather,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba yarın yağmur yağacak mı?',
            en: 'dad, is it gonna rain tomorrow?',
            de: 'Papa, regnet es morgen?',
            ar: 'أبي، هل ستمطر غدًا؟',
            fr: 'papa, il va pleuvoir demain ?',
            es: 'papá, ¿va a llover mañana?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'uygulama %50 diyor',
            en: 'the app says 50%',
            de: 'die App sagt 50 %',
            ar: 'التطبيق يقول 50%',
            fr: "l'appli dit 50 %",
            es: 'la app dice 50 %',
          },
        },
        {
          from: 'me',
          text: { tr: 'yani?', en: 'meaning?', de: 'heißt?', ar: 'يعني؟', fr: "c'est-à-dire ?", es: '¿o sea?' },
        },
        {
          from: 'them',
          text: {
            tr: 'ya yağar ya yağmaz',
            en: "either it rains or it doesn't",
            de: 'entweder es regnet oder nicht',
            ar: 'إما أن تمطر أو لا تمطر',
            fr: 'soit il pleut, soit il pleut pas',
            es: 'o llueve o no llueve',
          },
        },
      ],
    },
    caption: {
      tr: 'Babam meteorolojiyi çözdü',
      en: 'Dad cracked the weather code',
      de: 'Papa hat das Wetter durchschaut',
      ar: 'أبي فكّ لغز الأرصاد الجوية',
      fr: 'Papa a percé le secret de la météo',
      es: 'Papá descifró la meteorología',
    },
  },
  {
    emoji: '🌨️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Kardeşim', en: 'Sis', de: 'Schwesterherz', ar: 'أختي', fr: 'Sœurette', es: 'Hermanita' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'kar yağıyor!! ❄️',
            en: "it's snowing!! ❄️",
            de: 'es schneit!! ❄️',
            ar: 'إنها تثلج!! ❄️',
            fr: 'il neige !! ❄️',
            es: '¡¡está nevando!! ❄️',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'havucu kaptım, kardan adam geliyor ⛄',
            en: 'got the carrot, snowman time ⛄',
            de: 'Möhre geholt, jetzt kommt der Schneemann ⛄',
            ar: 'جهّزت الجزرة لرجل الثلج ⛄',
            fr: 'carotte prête pour le bonhomme ⛄',
            es: 'ya tengo la zanahoria para el muñeco ⛄',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'kar ancak kardan fareye yeter',
            en: "there's only enough for a snow mouse",
            de: 'reicht höchstens für eine Schneemaus',
            ar: 'الثلج بالكاد يكفي لفأر ثلج',
            fr: 'y a de quoi faire une souris de neige',
            es: 'solo alcanza para un ratón de nieve',
          },
        },
      ],
    },
    caption: {
      tr: 'Kardan fare de bir başlangıç',
      en: 'A snow mouse is still a start',
      de: 'Eine Schneemaus ist auch ein Anfang',
      ar: 'فأر الثلج بداية أيضًا',
      fr: "Une souris de neige, c'est un début",
      es: 'Un ratón de nieve también es un comienzo',
    },
  },
  {
    emoji: '🧅',
    user: ACCOUNTS.vlog,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'bugün hava nasıl?',
            en: "what's the weather like today?",
            de: 'wie wird das Wetter heute?',
            ar: 'كيف الطقس اليوم؟',
            fr: "il fait quel temps aujourd'hui ?",
            es: '¿cómo está el clima hoy?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'sabah 8 derece, öğlen 24',
            en: '46 this morning, 75 by noon',
            de: 'morgens 8 Grad, mittags 24',
            ar: '8 درجات في الصباح و24 عند الظهر',
            fr: '8 degrés le matin, 24 à midi',
            es: '8 grados temprano, 24 al mediodía',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tamam, hepsini giyiyorum',
            en: "ok, I'm wearing everything I own",
            de: 'ok, ich zieh einfach alles an',
            ar: 'حسنًا، سألبس كل ما عندي',
            fr: 'ok, je mets tout sur moi',
            es: 'ok, me pongo todo lo que tengo',
          },
        },
      ],
    },
    caption: {
      tr: 'Sonbahar modası: soğan gibi kat kat',
      en: 'Fall fashion: dress like an onion',
      de: 'Herbstmode: der Zwiebellook',
      ar: 'موضة الخريف: طبقات مثل البصلة',
      fr: "Mode d'automne : s'habiller en oignon",
      es: 'Moda de otoño: capas como una cebolla',
    },
  },
  {
    emoji: '🩳',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Hava ilk kez 18 derece oldu. Sen:',
        en: 'First 65-degree day of the year. You:',
        de: 'Zum ersten Mal 18 Grad. Du:',
        ar: 'لأول مرة هذا العام 18 درجة. ماذا تفعل؟',
        fr: 'Premier jour à 18 degrés. Toi :',
        es: 'Primer día de 18 grados del año. Tú:',
      },
      options: [
        {
          tr: 'Mont giyerim',
          en: 'Keep my coat on',
          de: 'Jacke bleibt an',
          ar: 'أبقى بالمعطف',
          fr: 'Je garde mon manteau',
          es: 'Sigo con abrigo',
        },
        {
          tr: 'Şort ve terlik',
          en: 'Shorts and flip-flops',
          de: 'Shorts und Flip-Flops',
          ar: 'شورت وصندل',
          fr: 'Short et tongs',
          es: 'Short y chanclas',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Akşam 9 derece oldu, pişmanım',
      en: "It's 48 now. Regrets.",
      de: 'Abends 9 Grad. Ich bereue alles.',
      ar: 'في المساء صارت 9 درجات… وندمت',
      fr: 'Le soir, 9 degrés. Je regrette.',
      es: 'Por la noche, 9 grados. Me arrepiento.',
    },
  },
  {
    emoji: '🏊',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Denize nasıl girersin?',
        en: 'How do you get into the sea?',
        de: 'Wie gehst du ins Meer?',
        ar: 'كيف تنزل إلى البحر؟',
        fr: 'Tu entres dans la mer comment ?',
        es: '¿Cómo entras al mar?',
      },
      options: [
        {
          tr: 'Koşup atlarım',
          en: 'Run and dive in',
          de: 'Anlauf und rein',
          ar: 'أركض وأقفز',
          fr: 'Je cours et je plonge',
          es: 'Corro y me lanzo',
        },
        {
          tr: 'Santim santim, 20 dk',
          en: 'Inch by inch, 20 min',
          de: 'Ganz langsam, 20 Min.',
          ar: 'شبرًا شبرًا، 20 دقيقة',
          fr: 'Tout doucement, 20 min',
          es: 'Poco a poco, 20 min',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Su belime geldi, 10 dakika daha mola',
      en: 'Waist-deep. Time for another break.',
      de: 'Bis zur Hüfte. Zeit für die nächste Pause.',
      ar: 'وصل الماء إلى خصري… استراحة أخرى',
      fr: "Jusqu'à la taille. Nouvelle pause.",
      es: 'Me llega a la cintura. Otra pausa.',
    },
  },
  {
    emoji: '🍁',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Yolda kuru yaprak yığını var. Sen:',
        en: 'Pile of dry leaves on the sidewalk. You:',
        de: 'Ein Haufen Laub auf dem Weg. Du:',
        ar: 'كومة أوراق جافة في طريقك. ماذا تفعل؟',
        fr: 'Un tas de feuilles mortes sur ta route. Toi :',
        es: 'Hay hojas secas en el camino. Tú:',
      },
      options: [
        {
          tr: 'Kenarından geçerim',
          en: 'Walk around it',
          de: 'Drumherum gehen',
          ar: 'أمشي بجانبها',
          fr: 'Je contourne',
          es: 'Las esquivo',
        },
        {
          tr: 'Hepsine basarım',
          en: 'Crunch every one',
          de: 'Mitten durch, knirsch!',
          ar: 'أدوس عليها كلها',
          fr: 'Je saute dedans',
          es: 'Las piso todas',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Tek bir tanesini bile atlamam',
      en: 'Not skipping a single one',
      de: 'Ich lass kein einziges aus',
      ar: 'لن أفوّت ورقة واحدة',
      fr: "Je n'en rate pas une",
      es: 'No me salto ni una',
    },
  },
  {
    emoji: '🥵',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'VANTİLATÖRE MESAFEM',
        en: 'MY DISTANCE TO THE FAN',
        de: 'ABSTAND ZUM VENTILATOR',
        ar: 'بُعدي عن المروحة',
        fr: 'MA DISTANCE AU VENTILO',
        es: 'DISTANCIA AL VENTILADOR',
      },
      value: { tr: '3 cm', en: '3 cm', de: '3 cm', ar: '3 سم', fr: '3 cm', es: '3 cm' },
      shape: 'fall',
      axis: 'days',
    },
    caption: {
      tr: 'Ağustos’ta vantilatörle tek vücut olduk',
      en: 'By August, the fan and I were one',
      de: 'Im August wurden der Ventilator und ich eins',
      ar: 'في أغسطس صرت أنا والمروحة شيئًا واحدًا',
      fr: "En août, le ventilo et moi, on ne fait qu'un",
      es: 'En agosto, el ventilador y yo éramos uno',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.weather,
    body: {
      format: 'chart',
      title: {
        tr: 'HAVA DURUMUNA BAKIŞIM',
        en: 'WEATHER APP CHECKS',
        de: 'WETTER-APP GECHECKT',
        ar: 'مرات فتح تطبيق الطقس',
        fr: "COUPS D'ŒIL À LA MÉTÉO",
        es: 'CONSULTAS DEL CLIMA',
      },
      value: { tr: '×23', en: '×23', de: '×23', ar: '×23', fr: '×23', es: '×23' },
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Piknikten önceki gece',
      en: 'The night before the picnic',
      de: 'Die Nacht vor dem Picknick',
      ar: 'الليلة التي تسبق النزهة',
      fr: 'La veille du pique-nique',
      es: 'La noche antes del pícnic',
    },
  },
  {
    emoji: '🍅',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: { tr: 'FİDANLIK', en: 'GARDEN CENTER', de: 'GARTENCENTER', ar: 'مشتل', fr: 'JARDINERIE', es: 'VIVERO' },
      items: [
        {
          tr: 'DOMATES FİDESİ (1)',
          en: 'TOMATO SEEDLING (1)',
          de: 'TOMATENPFLANZE (1)',
          ar: 'شتلة طماطم (1)',
          fr: 'PLANT DE TOMATE (1)',
          es: 'PLANTA DE TOMATE (1)',
        },
        {
          tr: 'SAKSI, TOPRAK, GÜBRE',
          en: 'POT, SOIL, FERTILIZER',
          de: 'TOPF, ERDE, DÜNGER',
          ar: 'أصيص وتربة وسماد',
          fr: 'POT, TERREAU, ENGRAIS',
          es: 'MACETA, TIERRA, ABONO',
        },
      ],
    },
    caption: {
      tr: 'Hasat: 1 domates. Maliyeti: sorma.',
      en: "Harvest: 1 tomato. Cost: don't ask.",
      de: 'Ernte: 1 Tomate. Kosten: frag nicht.',
      ar: 'الحصاد: حبة طماطم واحدة. التكلفة: لا تسأل.',
      fr: 'Récolte : 1 tomate. Prix : ne demande pas.',
      es: 'Cosecha: 1 tomate. Precio: ni preguntes.',
    },
  },
  {
    emoji: '🛷',
    user: ACCOUNTS.plain,
    body: {
      format: 'receipt',
      store: {
        tr: 'SPOR MAĞAZASI',
        en: 'SPORTING GOODS',
        de: 'SPORTGESCHÄFT',
        ar: 'متجر رياضي',
        fr: 'MAGASIN DE SPORT',
        es: 'TIENDA DE DEPORTES',
      },
      items: [
        {
          tr: 'KIZAK (2 KİŞİLİK)',
          en: 'SLED (2-SEATER)',
          de: 'SCHLITTEN FÜR 2',
          ar: 'زلاجة لشخصين',
          fr: 'LUGE 2 PLACES',
          es: 'TRINEO PARA 2',
        },
      ],
    },
    caption: {
      tr: 'Kızağı aldım. Kar ertesi sabah eridi.',
      en: 'Bought the sled. The snow melted by morning.',
      de: 'Schlitten gekauft. Am Morgen war der Schnee weg.',
      ar: 'اشتريت الزلاجة… فذاب الثلج في الصباح التالي',
      fr: 'Luge achetée. La neige a fondu le lendemain.',
      es: 'Compré el trineo. La nieve se derritió al día siguiente.',
    },
  },
  {
    emoji: '⛱️',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'PLAJ İSTATİSTİĞİ',
        en: 'BEACH STATS',
        de: 'STRAND-STATISTIK',
        ar: 'إحصائية الشاطئ',
        fr: 'STATS DE PLAGE',
        es: 'DATOS DE PLAYA',
      },
      big: { tr: '6', en: '6', de: '6', ar: '6', fr: '6', es: '6' },
      text: {
        tr: 'kez havlunu gölgeye taşıdın; gölge yine kaçtı',
        en: 'times you moved your towel to the shade. The shade moved too.',
        de: 'Mal mit dem Handtuch in den Schatten. Der Schatten zog weiter.',
        ar: 'مرات نقلت فيها منشفتك إلى الظل… فهرب الظل مجددًا',
        fr: "fois où tu as mis ta serviette à l'ombre. L'ombre a bougé.",
        es: 'veces moviste la toalla a la sombra. La sombra se fue otra vez.',
      },
    },
    caption: {
      tr: 'Dünya döndükçe sen de dönüyorsun',
      en: 'The Earth turns, and so do you',
      de: 'Die Erde dreht sich – und du mit',
      ar: 'الأرض تدور… وأنت تدور معها',
      fr: 'La Terre tourne, et toi avec',
      es: 'La Tierra gira y tú con ella',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.weather,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'SICAK HAVA RAPORU',
        en: 'HEAT WAVE REPORT',
        de: 'HITZEBERICHT',
        ar: 'تقرير موجة الحر',
        fr: 'BULLETIN CANICULE',
        es: 'INFORME DE CALOR',
      },
      big: { tr: '9', en: '9', de: '9', ar: '9', fr: '9', es: '9' },
      text: {
        tr: 'kez buzdolabını sırf serinlemek için açtın',
        en: 'times you opened the fridge just to cool off',
        de: 'Mal den Kühlschrank nur zum Abkühlen geöffnet',
        ar: 'مرات فتحت فيها الثلاجة لتتبرّد فقط',
        fr: 'fois où tu as ouvert le frigo juste pour avoir frais',
        es: 'veces abriste el refrigerador solo para refrescarte',
      },
    },
    caption: {
      tr: 'Bir de kafanı soktun, biliyoruz',
      en: 'You stuck your head in too. We know.',
      de: 'Und den Kopf reingesteckt. Wir wissen es.',
      ar: 'وأدخلت رأسك أيضًا… نحن نعرف',
      fr: 'Et tu as mis la tête dedans. On sait.',
      es: 'Y metiste la cabeza. Lo sabemos.',
    },
  },
  {
    emoji: '🌅',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '47', en: '47', de: '47', ar: '47', fr: '47', es: '47' },
      text: {
        tr: 'kez aynı gün batımını çektin; hiçbirini silemiyorsun',
        en: "photos of the same sunset. You can't delete a single one.",
        de: 'Fotos vom selben Sonnenuntergang. Keins wird gelöscht.',
        ar: 'صورة للغروب نفسه… ولا تستطيع حذف أي منها',
        fr: "photos du même coucher de soleil. Tu n'en supprimes aucune.",
        es: 'fotos del mismo atardecer. No puedes borrar ninguna.',
      },
    },
    caption: {
      tr: '48. kare daha iyi olabilir',
      en: 'Shot 48 might be the one',
      de: 'Foto 48 wird bestimmt das beste',
      ar: 'ربما تكون الصورة 48 هي الأجمل',
      fr: 'La 48e sera peut-être la bonne',
      es: 'Quizá la 48 sea la buena',
    },
  },
  {
    emoji: '🍉',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'PİKNİK TIER LIST',
        en: 'PICNIC TIER LIST',
        de: 'PICKNICK-RANKING',
        ar: 'تصنيف النزهة',
        fr: 'TIER LIST DU PIQUE-NIQUE',
        es: 'TIER LIST DE PÍCNIC',
      },
      rows: [['🍉', '🌽'], ['🥪', '🧃'], ['🥗', '🥚'], ['💨']],
    },
    caption: {
      tr: 'Duman C, çünkü nereye otursam beni buluyor',
      en: 'Smoke is C tier. It finds me wherever I sit.',
      de: 'Rauch ist C: Er findet mich überall.',
      ar: 'الدخان في المرتبة الأخيرة… يلاحقني أينما جلست',
      fr: 'La fumée est en C : elle me suit partout.',
      es: 'El humo va en C: me encuentra donde me siente.',
    },
  },
  {
    emoji: '🏕️',
    user: ACCOUNTS.vlog,
    body: {
      format: 'tier',
      title: {
        tr: 'KAMP TIER LIST',
        en: 'CAMPING TIER LIST',
        de: 'CAMPING-RANKING',
        ar: 'تصنيف التخييم',
        fr: 'TIER LIST DU CAMPING',
        es: 'TIER LIST DE CAMPAMENTO',
      },
      rows: [['🔥', '🌌'], ['⛺', '🍫'], ['🎒', '🌙'], ['🔦']],
    },
    caption: {
      tr: 'Fener C: pili hep ilk gece bitiyor',
      en: 'Flashlight: C tier. Always dies the first night.',
      de: 'Taschenlampe C: Batterie immer in der ersten Nacht leer',
      ar: 'المصباح في المرتبة الأخيرة: بطاريته تنفد في أول ليلة',
      fr: 'Lampe torche en C : à plat dès la 1re nuit',
      es: 'Linterna en C: se queda sin pilas la primera noche',
    },
  },
  {
    emoji: '🤧',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌼',
        app: {
          tr: 'Polen takibi',
          en: 'Pollen tracker',
          de: 'Pollenflug',
          ar: 'مؤشر حبوب اللقاح',
          fr: 'Alerte pollen',
          es: 'Alerta de polen',
        },
        text: {
          tr: 'Bugünkü polen seviyesi: EFSANEVİ',
          en: "Today's pollen level: LEGENDARY",
          de: 'Pollenbelastung heute: LEGENDÄR',
          ar: 'مستوى حبوب اللقاح اليوم: أسطوري',
          fr: 'Niveau de pollen du jour : LÉGENDAIRE',
          es: 'Nivel de polen hoy: LEGENDARIO',
        },
      },
    },
    caption: {
      tr: 'Mendil stoğu: kritik',
      en: 'Tissue supply: critical',
      de: 'Taschentuchvorrat: kritisch',
      ar: 'مخزون المناديل: حرج',
      fr: 'Stock de mouchoirs : critique',
      es: 'Reserva de pañuelos: crítica',
    },
  },
  {
    emoji: '🌷',
    user: ACCOUNTS.weather,
    body: {
      format: 'notifications',
      first: {
        icon: '🌡️',
        app: { tr: 'Hava durumu', en: 'Weather', de: 'Wetter', ar: 'الطقس', fr: 'Météo', es: 'Clima' },
        text: {
          tr: 'Yarın 26°, perşembe kar yağışı',
          en: 'Tomorrow 79°, snow on Thursday',
          de: 'Morgen 26°, Donnerstag Schnee',
          ar: 'غدًا 26°، والخميس ثلوج',
          fr: 'Demain 26°, neige jeudi',
          es: 'Mañana 26°, el jueves nieve',
        },
      },
    },
    caption: {
      tr: 'Mevsim de benim kadar kararsız',
      en: 'Spring is as indecisive as I am',
      de: 'Der Frühling ist so unentschlossen wie ich',
      ar: 'حتى الفصل متردد مثلي',
      fr: 'Le printemps est aussi indécis que moi',
      es: 'La primavera es tan indecisa como yo',
    },
  },
  {
    emoji: '🧣',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hiçbir kar tanesi birbirine benzemez. Hepsi aynı anda yakana kaçar.',
        en: 'No two snowflakes are alike. They all go down your collar at once.',
        de: 'Keine Schneeflocke gleicht der anderen. Alle landen im Kragen.',
        ar: 'لا تتشابه ندفتان من الثلج أبدًا… لكنها كلها تدخل من ياقتك معًا.',
        fr: 'Chaque flocon est unique. Et tous finissent dans ton col.',
        es: 'No hay dos copos de nieve iguales. Todos se meten por tu cuello.',
      },
    },
    caption: {
      tr: 'Atkı da işe yaramıyor',
      en: "Scarves don't help either",
      de: 'Auch der Schal hilft nicht',
      ar: 'ولا ينفع الوشاح أيضًا',
      fr: "Même l'écharpe n'y peut rien",
      es: 'Ni la bufanda ayuda',
    },
  },
  {
    emoji: '⛱️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Güneş herkese doğar. Bizim balkona 15 dakikalığına uğrar.',
        en: 'The sun rises for everyone. It visits my balcony for 15 minutes.',
        de: 'Die Sonne scheint für alle. Auf meinen Balkon 15 Minuten am Tag.',
        ar: 'الشمس تشرق للجميع… لكنها تزور شرفتي 15 دقيقة فقط.',
        fr: 'Le soleil se lève pour tous. Il passe sur mon balcon 15 minutes.',
        es: 'El sol sale para todos. A mi balcón viene 15 minutos.',
      },
    },
    caption: {
      tr: 'Şezlongu kurdum, gitti',
      en: 'Set up the lounge chair. It left.',
      de: 'Liegestuhl aufgebaut. Weg war sie.',
      ar: 'جهّزت الكرسي… فرحلت',
      fr: 'Transat installé. Il était parti.',
      es: 'Armé la tumbona. Ya se había ido.',
    },
  },
  {
    emoji: '🚡',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Zirveye tırmanan manzarayı hak eder. Teleferikle çıkan da.',
        en: 'The climb earns you the view. So does the cable car.',
        de: 'Wer den Berg erklimmt, verdient die Aussicht. Wer Seilbahn fährt, auch.',
        ar: 'من يتسلق الجبل يستحق المنظر… ومن يركب التلفريك أيضًا.',
        fr: 'Qui gravit la montagne mérite la vue. Qui prend le téléphérique aussi.',
        es: 'Quien escala merece la vista. Quien toma el teleférico, también.',
      },
    },
    caption: {
      tr: 'Aynı manzara, sıfır ter',
      en: 'Same view, zero sweat',
      de: 'Gleiche Aussicht, null Schweiß',
      ar: 'المنظر نفسه، بلا قطرة عرق',
      fr: 'Même vue, zéro sueur',
      es: 'Misma vista, cero sudor',
    },
  },
  {
    emoji: '💨',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Rüzgâra karşı yürüyen güçlenir. Saçı da bir daha düzelmez.',
        en: 'Walking against the wind makes you stronger. Your hair never recovers.',
        de: 'Wer gegen den Wind geht, wird stärker. Die Frisur erholt sich nie.',
        ar: 'من يمشي عكس الريح يزداد قوة… أما شعره فلا يعود كما كان.',
        fr: "Marcher face au vent rend fort. Ta coiffure, elle, ne s'en remet pas.",
        es: 'Caminar contra el viento te hace fuerte. Tu peinado no se recupera.',
      },
    },
    caption: {
      tr: 'Güç arttı, fön gitti',
      en: 'More strength, less hairdo',
      de: 'Mehr Kraft, weniger Frisur',
      ar: 'قوة أكثر، وتسريحة أقل',
      fr: 'Plus de force, moins de brushing',
      es: 'Más fuerza, cero peinado',
    },
  },
];
export const OUTDOORS_LIKE: readonly Draft[] = [
  {
    emoji: '🏰',
    user: ACCOUNTS.yagmur,
    body: { format: 'scene' },
    caption: {
      tr: 'kumdan kale kurdum, krallığım 6 dakika sürdü',
      en: 'built a sandcastle. my kingdom lasted 6 minutes',
      de: 'sandburg gebaut, mein königreich hielt 6 minuten',
      ar: 'بنيت قلعة رملية… ودامت مملكتي 6 دقائق',
      fr: 'château de sable terminé, mon royaume a tenu 6 minutes',
      es: 'hice un castillo de arena y mi reino duró 6 minutos',
    },
  },
  {
    emoji: '⛺',
    user: ACCOUNTS.bora,
    body: { format: 'scene' },
    caption: {
      tr: 'çadırı tek başıma kurdum! sadece 2 saat sürdü',
      en: 'pitched the tent all by myself! only took 2 hours',
      de: 'zelt ganz allein aufgebaut! hat nur 2 stunden gedauert',
      ar: 'نصبت الخيمة وحدي! استغرق الأمر ساعتين فقط',
      fr: "j'ai monté la tente tout seul ! ça n'a pris que 2 h",
      es: '¡armé la tienda de campaña yo solo! solo 2 horas',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'yıllar sonra ağaca tırmandım!! inişi sormayın',
      en: "climbed a tree after years!! don't ask how i got down",
      de: 'nach jahren wieder auf nen baum!! runter? fragt nicht',
      ar: 'تسلّقت شجرة بعد سنوات!! لا تسألوا عن النزول',
      fr: "j'ai regrimpé à un arbre !! la descente, on en parle pas",
      es: '¡¡volví a subirme a un árbol!! no pregunten cómo bajé',
    },
  },
  {
    emoji: '❄️',
    user: ACCOUNTS.irem,
    body: { format: 'scene' },
    caption: {
      tr: 'yılın ilk kar tanesini dilimle yakaladım',
      en: 'caught the first snowflake of the year on my tongue',
      de: 'die erste schneeflocke des jahres mit der zunge gefangen',
      ar: 'التقطت أول ندفة ثلج هذا العام بلساني',
      fr: "premier flocon de l'année attrapé avec la langue",
      es: 'atrapé el primer copo de nieve del año con la lengua',
    },
  },
  {
    emoji: '🏖️',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ıslakken çok güzeldi',
        en: 'they were prettier wet',
        de: 'nass waren sie schöner',
        ar: 'كانت أجمل وهي مبللة',
        fr: 'ils brillaient mouillés',
        es: 'mojadas brillaban más',
      },
    },
    caption: {
      tr: 'sahilde renkli taş topladım, kuruyunca hepsi gri',
      en: 'picked colorful stones on the beach, all gray once dry',
      de: 'bunte steine gesammelt, trocken sind alle grau',
      ar: 'جمعت حصى ملونة من الشاطئ… وحين جفّت صارت رمادية',
      fr: "j'ai ramassé des galets colorés, secs ils sont tous gris",
      es: 'recogí piedras de colores en la playa, secas son grises',
    },
  },
  {
    emoji: '🍁',
    user: ACCOUNTS.cemre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sonbahar arşivi',
        en: 'fall archive',
        de: 'herbst-archiv',
        ar: 'أرشيف الخريف',
        fr: "archives d'automne",
        es: 'archivo de otoño',
      },
    },
    caption: {
      tr: 'sonbaharı bir kitabın arasına sakladım',
      en: 'saved a little fall between the pages of a book',
      de: 'ein stück herbst zwischen buchseiten versteckt',
      ar: 'خبّأت شيئًا من الخريف بين صفحات كتاب',
      fr: "j'ai glissé un peu d'automne entre deux pages",
      es: 'guardé un poco de otoño entre las páginas de un libro',
    },
  },
  {
    emoji: '🌌',
    user: ACCOUNTS.efe,
    body: {
      format: 'polaroid',
      note: {
        tr: 'çıplak gözle!!',
        en: 'no telescope!!',
        de: 'mit bloßem auge!!',
        ar: 'بالعين المجردة!!',
        fr: "à l'œil nu !!",
        es: '¡¡a simple vista!!',
      },
    },
    caption: {
      tr: 'ilk kez samanyolunu gördüm, ağzım açık kaldı',
      en: 'saw the milky way for the first time, jaw on the floor',
      de: 'zum ersten mal die milchstraße gesehen. sprachlos.',
      ar: 'رأيت درب التبانة لأول مرة… وبقي فمي مفتوحًا',
      fr: 'première fois que je vois la voie lactée, bouche bée',
      es: 'vi la vía láctea por primera vez y me quedé boquiabierto',
    },
  },
  {
    emoji: '🎐',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'rüzgâr bekleniyor',
        en: 'waiting on the wind',
        de: 'warte auf wind',
        ar: 'بانتظار الريح',
        fr: 'en attente de vent',
        es: 'esperando al viento',
      },
    },
    caption: {
      tr: 'balkona rüzgâr çanı astım, bir haftadır çıt yok',
      en: 'hung a wind chime on the balcony, a week of silence so far',
      de: 'windspiel auf den balkon gehängt, seit einer woche stille',
      ar: 'علّقت جرس ريح في الشرفة… ولا صوت منذ أسبوع',
      fr: 'carillon à vent sur le balcon, une semaine sans un bruit',
      es: 'colgué un carillón en el balcón y lleva una semana mudo',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.melis,
    body: { format: 'dump', emojis: ['📖', '🏖️', '🍦', '🕶️', '🦀'] },
    caption: {
      tr: 'plaj dump’ı: 1 kitap götürdüm, 0 sayfa okudum',
      en: 'beach dump: brought 1 book, read 0 pages',
      de: 'strand-dump: 1 buch dabei, 0 seiten gelesen',
      ar: 'يوم الشاطئ: أخذت كتابًا واحدًا وقرأت 0 صفحة',
      fr: 'dump plage : 1 livre emporté, 0 page lue',
      es: 'día de playa: llevé 1 libro, leí 0 páginas',
    },
  },
  {
    emoji: '🌸',
    user: ACCOUNTS.ece,
    body: { format: 'dump', emojis: ['🌸', '🌷', '🌼', '🦋', '🤧'] },
    caption: {
      tr: 'bahar dump’ı: çiçekler açtı, ben hapşırdım',
      en: 'spring dump: the flowers bloomed, i sneezed',
      de: 'frühlings-dump: die blumen blühen, ich niese',
      ar: 'صور الربيع: تفتّحت الأزهار… وأنا عطست',
      fr: "dump printemps : les fleurs ont éclos, moi j'éternue",
      es: 'resumen de primavera: todo floreció y yo estornudé',
    },
  },
  {
    emoji: '☔',
    user: ACCOUNTS.kaan,
    body: { format: 'dump', emojis: ['☔', '🥾', '🐌', '💧', '🌈'] },
    caption: {
      tr: 'yağmur sonrası: bütün birikintilere bastım, çok mutluyum',
      en: 'after the rain: jumped in every puddle, so happy',
      de: 'nach dem regen: in jede pfütze gesprungen, so glücklich',
      ar: 'بعد المطر: قفزت في كل بركة ماء… وأنا سعيد جدًا',
      fr: 'après la pluie : sauté dans chaque flaque, trop heureux',
      es: 'después de la lluvia: salté en todos los charcos, feliz',
    },
  },
  {
    emoji: '🌻',
    user: ACCOUNTS.tolga,
    body: { format: 'dump', emojis: ['🌻', '🌾', '🐝', '📸', '🌞'] },
    caption: {
      tr: 'ayçiçeği tarlası dump’ı: hepsi güneşe döndü, ben kameraya',
      en: 'sunflower dump: they faced the sun, i faced the camera',
      de: 'sonnenblumen-dump: sie schauen zur sonne, ich in die kamera',
      ar: 'حقل دوّار الشمس: كلها تنظر إلى الشمس… وأنا إلى الكاميرا',
      fr: "dump tournesols : eux vers le soleil, moi vers l'objectif",
      es: 'campo de girasoles: ellos miran al sol, yo a la cámara',
    },
  },
];
export const OUTDOORS_HOLD: readonly Draft[] = [
  {
    emoji: '🌤️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir olay: hafta sonu tahmini tuttu',
      en: 'Rare event: the weekend forecast was right',
      de: 'Seltenes Ereignis: Die Wochenendprognose stimmt',
      ar: 'حدث نادر: صدقت توقعات عطلة نهاية الأسبوع',
      fr: 'Événement rare : la météo du week-end avait raison',
      es: 'Evento raro: el pronóstico del fin de semana acertó',
    },
  },
  {
    emoji: '🍒',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ağaçtaki ilk olgun kiraz. Kuşlar henüz bulmadı.',
      en: "The tree's first ripe cherry. The birds haven't found it.",
      de: 'Die erste reife Kirsche. Noch hat kein Vogel sie entdeckt.',
      ar: 'أول حبة كرز ناضجة على الشجرة… ولم تجدها الطيور بعد',
      fr: "Première cerise mûre de l'arbre. Les oiseaux l'ont ratée.",
      es: 'La primera cereza madura. Los pájaros aún no la encuentran.',
    },
  },
  {
    emoji: '🍃',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yılın o tek günü: ne sıcak ne soğuk',
      en: 'That one day a year: not hot, not cold',
      de: 'Der eine Tag im Jahr: nicht heiß, nicht kalt',
      ar: 'ذلك اليوم الوحيد في السنة: لا حر ولا برد',
      fr: "Le seul jour de l'année ni trop chaud, ni trop froid",
      es: 'Ese único día del año: ni calor ni frío',
    },
  },
  {
    emoji: '🐚',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kırıksız, kusursuz deniz kabuğu. Bin tanede bir.',
      en: 'An unbroken, flawless seashell. One in a thousand.',
      de: 'Eine ganze, makellose Muschel. Eine unter Tausend.',
      ar: 'صدفة سليمة بلا عيب… واحدة من كل ألف',
      fr: 'Un coquillage intact et parfait. Un sur mille.',
      es: 'Una concha entera y perfecta. Una entre mil.',
    },
  },
  {
    emoji: '🪨',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kusursuz sektirme taşı. Eğil, nişan al… şimdi bırak!',
      en: 'The perfect skipping stone. Aim low and… let go now!',
      de: 'Der perfekte Hüpfstein. Flach werfen und… jetzt loslassen!',
      ar: 'حجر مثالي لرميه فوق الماء… اتركه الآن!',
      fr: 'Galet parfait pour les ricochets… lâche maintenant !',
      es: 'La piedra plana perfecta para rebotar… ¡suéltala ya!',
    },
  },
  {
    emoji: '🌧️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Şans seninle: yağmur tam eve girdiğin an başladı',
      en: 'Lucky you: the rain started the second you got home',
      de: 'Glück gehabt: Der Regen kam, als du gerade drin warst',
      ar: 'حظك جميل: بدأ المطر لحظة دخولك البيت',
      fr: 'Coup de chance : la pluie tombe pile à ton arrivée',
      es: 'Qué suerte: empezó a llover justo al llegar a casa',
    },
  },
  {
    emoji: '✨',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bulutsuz, aysız gece: bütün yıldızlar sahnede',
      en: 'No clouds, no moon: every star on stage',
      de: 'Keine Wolken, kein Mond: alle Sterne auf der Bühne',
      ar: 'ليلة بلا غيوم ولا قمر: كل النجوم على المسرح',
      fr: 'Ni nuage ni lune : toutes les étoiles en scène',
      es: 'Sin nubes ni luna: todas las estrellas en escena',
    },
  },
];
export const OUTDOORS_FREEZE: readonly Draft[] = [
  {
    emoji: '🧊',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: { tr: 'BUZLANMA', en: 'ICY', de: 'GLATTEIS', ar: 'جليد', fr: 'VERGLAS', es: 'HIELO' },
      small: {
        tr: 'YAVAŞ VE DİKKATLİ YÜRÜYÜN',
        en: 'WALK SLOWLY, WATCH YOUR STEP',
        de: 'BITTE VORSICHTIG GEHEN',
        ar: 'امشِ ببطء وحذر',
        fr: 'AVANCEZ LENTEMENT',
        es: 'CAMINE CON PRECAUCIÓN',
      },
    },
    caption: {
      tr: 'Tek adım bile atma.',
      en: "Don't take a single step.",
      de: 'Keinen einzigen Schritt.',
      ar: 'لا تخطُ خطوة واحدة.',
      fr: 'Pas un seul pas.',
      es: 'Ni un solo paso.',
    },
    headline: {
      tr: 'Kaldırım buz pisti oldu',
      en: 'The sidewalk turned into an ice rink',
      de: 'Der Gehweg ist eine Eisbahn',
      ar: 'الرصيف صار حلبة تزلج',
      fr: 'Le trottoir est devenu une patinoire',
      es: 'La acera se volvió pista de hielo',
    },
  },
  {
    emoji: '🔭',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'GÖZLEMEVİ',
        en: 'OBSERVATORY',
        de: 'STERNWARTE',
        ar: 'مرصد فلكي',
        fr: 'OBSERVATOIRE',
        es: 'OBSERVATORIO',
      },
      small: {
        tr: 'TELESKOBA DOKUNMAYIN',
        en: 'DO NOT TOUCH THE TELESCOPE',
        de: 'TELESKOP NICHT BERÜHREN',
        ar: 'ممنوع لمس التلسكوب',
        fr: 'NE TOUCHEZ PAS AU TÉLESCOPE',
        es: 'NO TOCAR EL TELESCOPIO',
      },
    },
    caption: {
      tr: 'Bir dokunuş, Satürn gider.',
      en: "One bump and Saturn's gone.",
      de: 'Ein Stupser, und Saturn ist weg.',
      ar: 'لمسة واحدة ويضيع زحل.',
      fr: 'Une pichenette, et adieu Saturne.',
      es: 'Un toque y adiós, Saturno.',
    },
    headline: {
      tr: 'Teleskop tam Satürn’e odaklandı',
      en: 'The telescope is locked on Saturn',
      de: 'Das Teleskop zeigt genau auf Saturn',
      ar: 'التلسكوب مصوَّب نحو زحل تمامًا',
      fr: 'Le télescope vise pile Saturne',
      es: 'El telescopio apunta justo a Saturno',
    },
  },
  {
    emoji: '🐝',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: { tr: 'DİKKAT', en: 'CAUTION', de: 'ACHTUNG', ar: 'تنبيه', fr: 'ATTENTION', es: 'ATENCIÓN' },
      small: {
        tr: 'ARILAR ÇALIŞIYOR',
        en: 'BEES AT WORK',
        de: 'BIENEN BEI DER ARBEIT',
        ar: 'النحل يعمل هنا',
        fr: 'ABEILLES AU TRAVAIL',
        es: 'ABEJAS TRABAJANDO',
      },
    },
    caption: {
      tr: 'O içsin, sen bekle.',
      en: 'Let her sip. You wait.',
      de: 'Lass sie trinken. Du wartest.',
      ar: 'دعها تشرب… وانتظر.',
      fr: 'Laisse-la boire. Toi, attends.',
      es: 'Déjala beber. Tú espera.',
    },
    headline: {
      tr: 'Limonatanın kenarına bir arı kondu',
      en: 'A bee just landed on your lemonade',
      de: 'Eine Biene sitzt auf deiner Limo',
      ar: 'حطّت نحلة على كوب الليموناضة',
      fr: "Une abeille s'est posée sur ta limonade",
      es: 'Una abeja se posó en tu limonada',
    },
  },
  {
    emoji: '🌡️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SICAK YÜZEY',
        en: 'HOT SURFACE',
        de: 'HEISSE FLÄCHE',
        ar: 'سطح ساخن',
        fr: 'SURFACE CHAUDE',
        es: 'MUY CALIENTE',
      },
      small: {
        tr: 'ÖĞLEN SAATLERİNDE KAYMAYIN',
        en: 'NO SLIDING AT NOON',
        de: 'MITTAGS NICHT RUTSCHEN',
        ar: 'ممنوع التزحلق وقت الظهيرة',
        fr: 'PAS DE GLISSADE À MIDI',
        es: 'NO DESLIZARSE AL MEDIODÍA',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Kaydırak öğleden beri güneşte',
      en: "The slide's been in the sun since noon",
      de: 'Die Rutsche glüht seit Mittag',
      ar: 'الزحليقة تحت الشمس منذ الظهر',
      fr: 'Le toboggan cuit au soleil depuis midi',
      es: 'El tobogán lleva todo el día al sol',
    },
  },
  {
    emoji: '☃️',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'BAHÇE', en: 'FRONT YARD', de: 'VORGARTEN', ar: 'الفناء الأمامي', fr: 'JARDIN', es: 'PATIO' },
    },
    caption: {
      tr: 'Görmezse atamaz.',
      en: "If he can't see you, he can't throw.",
      de: 'Was er nicht sieht, trifft er nicht.',
      ar: 'إن لم يرَك فلن يرمي.',
      fr: "S'il te voit pas, il tire pas.",
      es: 'Si no te ve, no te la lanza.',
    },
    headline: {
      tr: 'Kardeşin elinde kartopuyla pusuda',
      en: "Your brother's waiting with a snowball",
      de: 'Dein Bruder lauert mit einem Schneeball',
      ar: 'أخوك يترصّدك بكرة ثلج',
      fr: 'Ton frère cache une boule de neige',
      es: 'Tu hermano acecha con una bola de nieve',
    },
  },
  {
    emoji: '⚽',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: { tr: 'PARK', en: 'CITY PARK', de: 'STADTPARK', ar: 'الحديقة العامة', fr: 'PARC', es: 'PARQUE' },
    },
    caption: {
      tr: 'Belki başkası vurur. Kıpırdama.',
      en: "Maybe someone else will kick it. Don't move.",
      de: 'Vielleicht schießt ein anderer. Nicht bewegen.',
      ar: 'ربما يركلها غيرك… لا تتحرك.',
      fr: "Quelqu'un d'autre va peut-être tirer. Bouge pas.",
      es: 'Quizá la patee otro. No te muevas.',
    },
    headline: {
      tr: 'Top ayağına geldi, bütün park bakıyor',
      en: 'Ball at your feet, every kid watching',
      de: 'Der Ball rollt zu dir. Alle schauen.',
      ar: 'الكرة عند قدميك… والحديقة كلها تنظر',
      fr: 'Ballon à tes pieds, tout le parc regarde',
      es: 'La pelota llegó a ti. Todos miran.',
    },
  },
  {
    emoji: '☁️',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: { tr: 'PLAJ', en: 'BEACH', de: 'STRAND', ar: 'الشاطئ', fr: 'PLAGE', es: 'PLAYA' },
    },
    caption: {
      tr: 'Kıpırdama, gölge senin.',
      en: "Don't move. The shade is yours.",
      de: 'Nicht bewegen. Der Schatten gehört dir.',
      ar: 'لا تتحرك… الظل لك.',
      fr: "Bouge pas, l'ombre est à toi.",
      es: 'No te muevas. La sombra es tuya.',
    },
    headline: {
      tr: 'Tek bulut tam üstüne geliyor',
      en: 'The only cloud is heading your way',
      de: 'Die einzige Wolke zieht genau zu dir',
      ar: 'الغيمة الوحيدة تتجه نحوك تمامًا',
      fr: "L'unique nuage arrive pile sur toi",
      es: 'La única nube va justo hacia ti',
    },
  },
];
