import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * The phone itself: apps, settings, cameras, updates, typing, autocorrect, social media habits.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const PHONE_SKIP: readonly Draft[] = [
  {
    emoji: '🔦',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Telefonumu aradım. Telefonun feneriyle.',
      en: "Looked for my phone. With my phone's flashlight.",
      de: 'Handy gesucht. Mit der Handy-Taschenlampe.',
      ar: 'بحثت عن هاتفي… مستعينًا بمصباح هاتفي',
      fr: "J'ai cherché mon tel. Avec la lampe du tel.",
      es: 'Busqué mi teléfono. Con la linterna del teléfono.',
      ja: 'スマホを探した。スマホのライトで。',
      ko: '폰을 찾았다. 폰 손전등을 켜고.',
    },
  },
  {
    emoji: '⌨️',
    user: ACCOUNTS.office,
    body: { format: 'scene' },
    caption: {
      tr: '“G” yazdım, klavye “geç kalıyorum” önerdi',
      en: 'One letter in, my keyboard suggests “running late”',
      de: '„K“ getippt. Vorschlag: „komme später“',
      ar: 'كتبت حرفًا واحدًا فاقترحت لوحة المفاتيح: «سأتأخر»',
      fr: "Une lettre, et le clavier propose « j'arrive en retard »",
      es: 'Escribo una letra y el teclado sugiere “llego tarde”',
      ja: '「ご」と打っただけで予測変換が「ごめん遅れる」',
      ko: '“ㅈ”만 쳤는데 키보드가 “좀 늦을 듯” 추천',
    },
  },
  {
    emoji: '📳',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Cebim titredi sandım. Telefon elimdeydi.',
      en: 'Felt my pocket buzz. My phone was in my hand.',
      de: 'Tasche vibriert? Das Handy war in meiner Hand.',
      ar: 'شعرت بجيبي يهتز… والهاتف في يدي',
      fr: 'Ma poche a vibré. Mon tel était dans ma main.',
      es: 'Me vibró el bolsillo. El teléfono estaba en mi mano.',
      ja: 'ポケットが震えた気がした。スマホは手に持ってた。',
      ko: '주머니에서 진동이 온 줄 알았다. 폰은 손에 있었다.',
    },
  },
  {
    emoji: '🌚',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Hile: karanlık modu aç, anında gizemli ol',
      en: 'Hack: dark mode = instant air of mystery',
      de: 'Lifehack: Dunkelmodus an, sofort geheimnisvoll',
      ar: 'حيلة: فعّل الوضع الداكن وستصبح غامضًا فورًا',
      fr: 'Astuce : mode sombre = mystère instantané',
      es: 'Truco: activa el modo oscuro y sé un misterio',
      ja: '裏ワザ：ダークモードにすれば一瞬でミステリアス',
      ko: '꿀팁: 다크 모드 켜면 바로 신비로운 사람 됨',
    },
  },
  {
    emoji: '🪞',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Ayna selfiesi: en net çıkan şey telefon',
      en: 'Mirror selfie: the sharpest thing in it is my phone',
      de: 'Spiegelselfie: Nur das Handy ist richtig im Fokus',
      ar: 'سيلفي في المرآة: أوضح شيء فيها هو الهاتف',
      fr: "Selfie miroir : le plus net, c'est le téléphone",
      es: 'Selfie en el espejo: lo más nítido es el teléfono',
      ja: '鏡の自撮り：いちばんピントが合ってるのはスマホ',
      ko: '거울 셀카: 제일 선명하게 나온 건 폰',
    },
  },
  {
    emoji: '🔍',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Ekran koruyucu: 9 kabarcık. Hepsine isim verdim.',
      en: 'Screen protector: 9 bubbles. I named them all.',
      de: 'Schutzfolie: 9 Blasen. Alle haben einen Namen.',
      ar: 'واقي الشاشة: 9 فقاعات، ولكل واحدة اسم',
      fr: "Protection d'écran : 9 bulles. Elles ont toutes un prénom.",
      es: 'Protector de pantalla: 9 burbujas. Todas tienen nombre.',
      ja: '保護フィルムに気泡が9個。全員に名前をつけた。',
      ko: '보호 필름 기포 9개. 전부 이름 지어 줬다.',
    },
  },
  {
    emoji: '🤦',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'keçi aldım, geliyorum',
            en: 'got the snakes, omw',
            de: 'hab Küken dabei, bin gleich da',
            ar: 'أحضرت الديك، أنا قادم',
            fr: "j'ai le bateau, j'arrive",
            es: 'ya tengo el pastor, voy para allá',
            ja: '景気買った、今から行く',
            ko: '군뱀 사서 가는 중',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'KEÇİ Mİ??',
            en: 'SNAKES??',
            de: 'KÜKEN??',
            ar: 'الديك؟؟',
            fr: 'LE BATEAU ??',
            es: '¿¿EL PASTOR??',
            ja: '景気？？',
            ko: '군뱀??',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'KEKİ. otomatik düzeltme 😩',
            en: 'SNACKS. autocorrect 😩',
            de: 'KUCHEN. Autokorrektur 😩',
            ar: 'الكيك! التصحيح التلقائي 😩',
            fr: 'LE GÂTEAU. correcteur 😩',
            es: 'PASTEL. autocorrector 😩',
            ja: 'ケーキ。変換ミス 😩',
            ko: '군밤. 자동 수정 😩',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'keçi daha eğlenceliydi ama',
            en: 'ngl snakes sounded more fun',
            de: 'Küken wär süßer gewesen',
            ar: 'الديك كان أطرف بصراحة',
            fr: "le bateau, c'était plus drôle",
            es: 'el pastor sonaba más divertido',
            ja: '景気が買えるなら買ってきて',
            ko: '솔직히 군뱀이 더 끌렸는데',
          },
        },
      ],
    },
    caption: {
      tr: 'Otomatik düzeltme yine iş başında',
      en: 'Autocorrect is at it again',
      de: 'Die Autokorrektur schon wieder',
      ar: 'التصحيح التلقائي يفعلها مجددًا',
      fr: 'Le correcteur a encore fait des siennes',
      es: 'El autocorrector otra vez haciendo de las suyas',
      ja: '予測変換、今日も絶好調',
      ko: '자동 수정이 또 일했다',
    },
  },
  {
    emoji: '🙊',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'annem yine “kaçta geliyorsun” diye yazdı 🙄',
            en: "mom asked when I'm coming home AGAIN 🙄",
            de: 'Mama fragt schon wieder, wann ich komme 🙄',
            ar: 'أمي تسأل مجددًا متى سأعود 🙄',
            fr: 'maman demande ENCORE quand je rentre 🙄',
            es: 'mamá pregunta OTRA VEZ cuándo vuelvo 🙄',
            ja: '母からまた「何時に帰るの」って 🙄',
            ko: '엄마가 또 몇 시에 오냐고 물어봄 🙄',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Evet. Kaçta geliyorsun?',
            en: 'Yes. When ARE you coming home?',
            de: 'Ja. Wann kommst du?',
            ar: 'نعم. متى ستعود؟',
            fr: 'Oui. Tu rentres quand ?',
            es: 'Sí. ¿Cuándo vuelves?',
            ja: 'そうよ。で、何時に帰るの？',
            ko: '그래. 그래서 몇 시에 오는데?',
          },
        },
      ],
    },
    caption: {
      tr: 'Yanlış sohbet. En yanlış sohbet.',
      en: 'Wrong chat. The wrongest chat.',
      de: 'Falscher Chat. Der falscheste überhaupt.',
      ar: 'محادثة خاطئة… وأيّ محادثة!',
      fr: 'Mauvaise conversation. La pire de toutes.',
      es: 'Chat equivocado. El más equivocado de todos.',
      ja: '誤爆した。最悪の相手に。',
      ko: '톡 잘못 보냄. 하필 엄마한테.',
    },
  },
  {
    emoji: '🥲',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: {
        tr: 'Anneannem',
        en: 'Grandma',
        de: 'Oma',
        ar: 'جدتي',
        fr: 'Mamie',
        es: 'Abuela',
        ja: 'おばあちゃん',
        ko: '할머니',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'reçeli yaktım 😂😂',
            en: 'I burned the jam 😂😂',
            de: 'die Marmelade ist angebrannt 😂😂',
            ar: 'احترق المربى 😂😂',
            fr: "j'ai fait brûler la confiture 😂😂",
            es: 'se me quemó la mermelada 😂😂',
            ja: 'ジャム焦がしちゃった 😂😂',
            ko: '잼 다 태웠다 😂😂',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'neden gülüyorsun anneanne?',
            en: 'why are you laughing, Grandma?',
            de: 'warum lachst du, Oma?',
            ar: 'لماذا تضحكين يا جدتي؟',
            fr: 'pourquoi tu ris, Mamie ?',
            es: '¿por qué te ríes, abuela?',
            ja: 'おばあちゃん、なんで笑ってるの？',
            ko: '할머니 왜 웃어요?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ağlıyorum yavrum 😂😂😂',
            en: "I'm crying, sweetie 😂😂😂",
            de: 'ich weine doch, Schatz 😂😂😂',
            ar: 'أنا أبكي يا حبيبي 😂😂😂',
            fr: 'mais je pleure, mon chéri 😂😂😂',
            es: 'estoy llorando, mi amor 😂😂😂',
            ja: '泣いてるのよ 😂😂😂',
            ko: '우는 거란다 얘야 😂😂😂',
          },
        },
      ],
    },
    caption: {
      tr: 'Anneannemin sözlüğünde 😂 ağlamak demek',
      en: "In Grandma's dictionary, 😂 means crying",
      de: 'In Omas Wörterbuch heißt 😂 weinen',
      ar: 'في قاموس جدتي، 😂 تعني البكاء',
      fr: 'Dans le dico de Mamie, 😂 veut dire pleurer',
      es: 'En el diccionario de la abuela, 😂 es llorar',
      ja: 'おばあちゃんの辞書では😂は「泣く」',
      ko: '할머니 사전에서 😂는 ‘운다’는 뜻',
    },
  },
  {
    emoji: '👖',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Eski komşu',
        en: 'Old neighbor',
        de: 'Alte Nachbarin',
        ar: 'الجارة القديمة',
        fr: 'Ancienne voisine',
        es: 'Vecina de antes',
        ja: '前のお隣さん',
        ko: '예전 옆집',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'beni aradın mı?',
            en: 'did you just call me?',
            de: 'hast du mich angerufen?',
            ar: 'هل اتصلت بي؟',
            fr: "tu m'as appelée ?",
            es: '¿me llamaste?',
            ja: '今電話くれた？',
            ko: '방금 전화했어요?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yok, cebimden aramışım 🙈',
            en: 'oops, pocket call 🙈',
            de: 'oh nein, das war die Hosentasche 🙈',
            ar: 'آسف، اتصل جيبي وحده 🙈',
            fr: 'oups, appel de poche 🙈',
            es: 'uy, fue el bolsillo 🙈',
            ja: 'ううん、ポケットの中で押しちゃった 🙈',
            ko: '아뇨, 주머니에서 눌렸나 봐요 🙈',
          },
        },
        {
          from: 'them',
          text: {
            tr: '10 dakika yürüyüşünü dinledim',
            en: 'I listened to your walk for 10 min',
            de: 'hab 10 Minuten deinen Schritten gelauscht',
            ar: 'استمعت إلى خطواتك 10 دقائق',
            fr: "j'ai écouté ta balade pendant 10 min",
            es: 'escuché tu caminata 10 minutos',
            ja: '10分間、歩く音を聞いてた',
            ko: '10분 동안 걷는 소리 들었어요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'cebin senden daha sık arıyor bu arada',
            en: 'your pocket calls more than you do btw',
            de: 'deine Tasche ruft öfter an als du',
            ar: 'جيبك يتصل بي أكثر منك بالمناسبة',
            fr: 'ta poche appelle plus souvent que toi',
            es: 'tu bolsillo llama más que tú, eh',
            ja: 'ちなみにポケットのほうがよく電話くれるよ',
            ko: '주머니가 본인보다 더 자주 전화하네요',
          },
        },
      ],
    },
    caption: {
      tr: 'Cebim benden daha sosyal',
      en: 'My pocket has a better social life',
      de: 'Meine Hosentasche ist geselliger als ich',
      ar: 'جيبي اجتماعي أكثر مني',
      fr: 'Ma poche est plus sociable que moi',
      es: 'Mi bolsillo es más sociable que yo',
      ja: '私よりポケットのほうが社交的',
      ko: '내 주머니가 나보다 인싸다',
    },
  },
  {
    emoji: '😰',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Telefon yüzüstü düştü. Sen:',
        en: 'Your phone lands face down. You:',
        de: 'Dein Handy fällt aufs Display. Du:',
        ar: 'سقط هاتفك على وجهه. ماذا تفعل؟',
        fr: 'Ton tel tombe côté écran. Tu fais quoi ?',
        es: 'Tu teléfono cae boca abajo. Tú:',
        ja: 'スマホが画面から落ちた。あなたは？',
        ko: '폰이 화면 쪽으로 떨어졌다. 나는?',
      },
      options: [
        {
          tr: 'Hemen çeviririm',
          en: 'Flip it right away',
          de: 'Sofort umdrehen',
          ar: 'أقلبه فورًا',
          fr: 'Je le retourne direct',
          es: 'Le doy la vuelta ya',
          ja: 'すぐ裏返す',
          ko: '바로 뒤집는다',
        },
        {
          tr: 'Gözüm kapalı çeviririm',
          en: 'Flip it with eyes shut',
          de: 'Augen zu und umdrehen',
          ar: 'أغمض عينيّ ثم أقلبه',
          fr: 'Les yeux fermés',
          es: 'Con los ojos cerrados',
          ja: '目を閉じて裏返す',
          ko: '눈 감고 뒤집는다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Bakmadıkça kırık sayılmaz',
      en: "If I don't look, it's not cracked",
      de: 'Solange ich nicht hinschaue, ist es heil',
      ar: 'ما دمت لا أنظر، فهو ليس مكسورًا',
      fr: "Tant que je regarde pas, c'est pas cassé",
      es: 'Si no lo miro, no está roto',
      ja: '見なければ割れてないのと同じ',
      ko: '안 보면 안 깨진 거다',
    },
  },
  {
    emoji: '😱',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Ön kamera yanlışlıkla açıldı. Sen:',
        en: 'The front camera opens by accident. You:',
        de: 'Die Frontkamera geht aus Versehen an. Du:',
        ar: 'انفتحت الكاميرا الأمامية فجأة. ماذا تفعل؟',
        fr: 'Caméra selfie ouverte par erreur. Tu fais quoi ?',
        es: 'Se abre la cámara frontal sin querer. Tú:',
        ja: 'うっかりインカメが起動。あなたは？',
        ko: '전면 카메라가 실수로 켜졌다. 나는?',
      },
      options: [
        {
          tr: 'Sakince kapatırım',
          en: 'Calmly close it',
          de: 'Ruhig schließen',
          ar: 'أغلقها بهدوء',
          fr: 'Je ferme calmement',
          es: 'La cierro con calma',
          ja: '冷静に閉じる',
          ko: '침착하게 끈다',
        },
        {
          tr: 'Çığlık atarım',
          en: 'Scream',
          de: 'Schreien',
          ar: 'أصرخ',
          fr: 'Je hurle',
          es: 'Grito',
          ja: '悲鳴をあげる',
          ko: '비명을 지른다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'İkimiz de çığlık attık: ben ve ben',
      en: 'Both of us screamed. Me and me.',
      de: 'Wir haben beide geschrien. Ich und ich.',
      ar: 'صرخنا كلانا: أنا وأنا',
      fr: 'On a crié tous les deux. Moi et moi.',
      es: 'Gritamos los dos: yo y yo.',
      ja: '2人とも悲鳴をあげた。私と私。',
      ko: '둘 다 소리 질렀다. 나랑 나.',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sessiz bir ortamda telefonun çaldı. Sen:',
        en: 'Your phone rings in a silent room. You:',
        de: 'Dein Handy klingelt in der Stille. Du:',
        ar: 'رنّ هاتفك في مكان هادئ تمامًا. ماذا تفعل؟',
        fr: 'Ton tel sonne en plein silence. Et là ?',
        es: 'Tu teléfono suena en pleno silencio. Tú:',
        ja: '静かな場所でスマホが鳴った。あなたは？',
        ko: '조용한 곳에서 폰이 울렸다. 나는?',
      },
      options: [
        {
          tr: 'Hemen kapatırım',
          en: 'Silence it fast',
          de: 'Sofort wegdrücken',
          ar: 'أُسكته فورًا',
          fr: 'Je coupe vite',
          es: 'Lo silencio rápido',
          ja: 'すぐに止める',
          ko: '바로 끈다',
        },
        {
          tr: 'Etrafa kızgın bakarım',
          en: 'Glare at everyone else',
          de: 'Andere böse anschauen',
          ar: 'أنظر إلى الآخرين بغضب',
          fr: 'Je toise les autres',
          es: 'Miro mal a los demás',
          ja: '周りをにらむ',
          ko: '주변을 째려본다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kimin telefonu bu, çok ayıp',
      en: 'Wow, whose phone is that? So rude.',
      de: 'Wessen Handy ist das? Unmöglich.',
      ar: 'هاتف مَن هذا؟ يا للإزعاج!',
      fr: "C'est le tel de qui ? Quelle honte.",
      es: '¿De quién es ese teléfono? Qué falta de respeto.',
      ja: '誰のスマホ？マナー悪すぎ',
      ko: '누구 폰이야, 매너 없게',
    },
  },
  {
    emoji: '📢',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sesli asistan seni anlamadı. Sen:',
        en: "The voice assistant didn't get it. You:",
        de: 'Der Sprachassistent versteht dich nicht. Du:',
        ar: 'المساعد الصوتي لم يفهمك. ماذا تفعل؟',
        fr: "L'assistant vocal n'a pas compris. Et là ?",
        es: 'El asistente de voz no te entendió. Tú:',
        ja: '音声アシスタントに伝わらない。あなたは？',
        ko: '음성 비서가 못 알아들었다. 나는?',
      },
      options: [
        {
          tr: 'Tekrar söylerim',
          en: 'Say it again',
          de: 'Noch mal sagen',
          ar: 'أعيد الجملة',
          fr: 'Je répète',
          es: 'Lo repito',
          ja: 'もう一度言う',
          ko: '다시 말한다',
        },
        {
          tr: 'Aynısını bağırırım',
          en: 'Say it again, LOUDER',
          de: 'Dasselbe, nur LAUTER',
          ar: 'أعيدها بصوت أعلى',
          fr: 'Pareil, mais plus FORT',
          es: 'Lo mismo, MÁS FUERTE',
          ja: '同じことを叫ぶ',
          ko: '똑같이 소리친다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Sonra hecelerim. Sonra kendim yaparım.',
      en: 'Then I spell it out. Then I do it myself.',
      de: 'Dann buchstabiere ich. Dann mach ich es selbst.',
      ar: 'ثم أتهجّاها. ثم أفعلها بنفسي.',
      fr: "Puis j'épelle. Puis je le fais moi-même.",
      es: 'Luego lo deletreo. Luego lo hago yo.',
      ja: '次は一語ずつ区切る。最後は自分でやる。',
      ko: '그다음엔 또박또박. 결국 내가 한다.',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: '“YAZIYOR…”',
        en: '“TYPING…”',
        de: '„SCHREIBT…“',
        ar: '«يكتب…»',
        fr: "« EN TRAIN D'ÉCRIRE… »",
        es: '“ESCRIBIENDO…”',
        ja: '「入力中…」',
        ko: '“입력 중…”',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Yazdı, sildi, yazdı… çevrimdışı oldu.',
      en: 'Typing, stopped, typing… went offline.',
      de: 'Schreibt, stoppt, schreibt… offline.',
      ar: 'يكتب، يتوقف، يكتب… ثم يختفي.',
      fr: 'Écrit, arrête, écrit… hors ligne.',
      es: 'Escribe, para, escribe… se desconectó.',
      ja: '入力中、止まって、また入力中…オフラインになった。',
      ko: '입력 중, 멈춤, 입력 중… 오프라인.',
    },
  },
  {
    emoji: '🔉',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'TELEFONUMUN SESİ',
        en: 'MY PHONE VOLUME',
        de: 'LAUTSTÄRKE MEINES HANDYS',
        ar: 'مستوى صوت هاتفي',
        fr: 'VOLUME DE MON TEL',
        es: 'VOLUMEN DE MI TELÉFONO',
        ja: 'スマホの音量',
        ko: '내 폰 볼륨',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Ya son ses ya sessiz, arası yok',
      en: "It's either full blast or silent. Nothing in between.",
      de: 'Entweder voll aufgedreht oder lautlos',
      ar: 'إما بأعلى صوت أو صامت، ولا وسط بينهما',
      fr: 'Soit à fond, soit en silencieux. Pas de milieu.',
      es: 'O a todo volumen o en silencio. Sin término medio.',
      ja: '最大か無音か。その間はない。',
      ko: '최대 아니면 무음. 중간은 없다.',
    },
  },
  {
    emoji: '🔆',
    user: ACCOUNTS.sleep,
    body: {
      format: 'chart',
      title: {
        tr: 'EKRAN PARLAKLIĞI',
        en: 'SCREEN BRIGHTNESS',
        de: 'BILDSCHIRMHELLIGKEIT',
        ar: 'سطوع الشاشة',
        fr: "LUMINOSITÉ DE L'ÉCRAN",
        es: 'BRILLO DE PANTALLA',
        ja: '画面の明るさ',
        ko: '화면 밝기',
      },
      value: {
        tr: '%100',
        en: '100%',
        de: '100 %',
        ar: '100%',
        fr: '100 %',
        es: '100 %',
        ja: '100%',
        ko: '100%',
      },
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Karanlıkta telefonu açtım, güneş doğdu',
      en: 'Unlocked my phone in the dark. Sunrise.',
      de: 'Handy im Dunkeln entsperrt. Sonnenaufgang.',
      ar: 'فتحت هاتفي في الظلام… فأشرقت الشمس',
      fr: 'Tel allumé dans le noir. Lever de soleil.',
      es: 'Abrí el teléfono a oscuras. Amaneció.',
      ja: '暗闇でスマホをつけたら、日の出',
      ko: '어둠 속에서 폰 켰더니 해가 떴다',
    },
  },
  {
    emoji: '🔧',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'TELEFON TAMİRCİSİ',
        en: 'PHONE REPAIR SHOP',
        de: 'HANDYREPARATUR',
        ar: 'محل تصليح الهواتف',
        fr: 'RÉPARATION MOBILES',
        es: 'SERVICIO TÉCNICO',
        ja: 'スマホ修理店',
        ko: '휴대폰 수리점',
      },
      items: [
        {
          tr: 'EKRAN DEĞİŞİMİ',
          en: 'SCREEN REPLACEMENT',
          de: 'DISPLAYTAUSCH',
          ar: 'تغيير الشاشة',
          fr: "CHANGEMENT D'ÉCRAN",
          es: 'CAMBIO DE PANTALLA',
          ja: '画面交換',
          ko: '액정 교체',
        },
        {
          tr: 'KILIF (BU SEFER)',
          en: 'PHONE CASE (THIS TIME)',
          de: 'HÜLLE (DIESMAL)',
          ar: 'غطاء (هذه المرة)',
          fr: 'COQUE (CETTE FOIS)',
          es: 'FUNDA (ESTA VEZ)',
          ja: 'ケース（今度こそ）',
          ko: '케이스 (이번엔 꼭)',
        },
      ],
    },
    caption: {
      tr: 'Ders aldım. Ekran parasıyla.',
      en: 'Lesson learned. It cost me a screen.',
      de: 'Lektion gelernt. Hat ein Display gekostet.',
      ar: 'تعلّمت الدرس… وكلّفني شاشة',
      fr: "Leçon apprise. Ça m'a coûté un écran.",
      es: 'Lección aprendida. Me costó una pantalla.',
      ja: '学んだ。授業料は画面1枚。',
      ko: '교훈 얻었다. 수업료는 액정 하나.',
    },
  },
  {
    emoji: '💡',
    user: ACCOUNTS.vlog,
    body: {
      format: 'receipt',
      store: {
        tr: 'AYDINLATMA',
        en: 'LIGHTING STORE',
        de: 'LAMPENLADEN',
        ar: 'محل الإنارة',
        fr: 'LUMINAIRES',
        es: 'ILUMINACIÓN',
        ja: '照明ショップ',
        ko: '조명 가게',
      },
      items: [
        {
          tr: 'HALKA IŞIK',
          en: 'RING LIGHT',
          de: 'RINGLICHT',
          ar: 'إضاءة حلقية',
          fr: 'ANNEAU LUMINEUX',
          es: 'ARO DE LUZ',
          ja: 'リングライト',
          ko: '링 라이트',
        },
      ],
    },
    caption: {
      tr: 'Artık dağınık odam da çok net çıkıyor',
      en: 'Now my messy room looks crystal clear too',
      de: 'Jetzt sieht man mein Chaos in bester Qualität',
      ar: 'الآن تظهر فوضى غرفتي بوضوح تام',
      fr: 'Maintenant, mon bazar est super net aussi',
      es: 'Ahora mi habitación desordenada se ve nítida',
      ja: '散らかった部屋までくっきり映るようになった',
      ko: '이제 어질러진 내 방도 선명하게 나온다',
    },
  },
  {
    emoji: '🏷️',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3', ja: '3', ko: '3' },
      text: {
        tr: 'kez kendi adını yazdın; otomatik düzeltme üçünü de değiştirdi',
        en: 'times you typed your own name. Autocorrect “fixed” all 3.',
        de: 'Mal den eigenen Namen getippt. Dreimal „korrigiert“.',
        ar: 'مرات كتبت اسمك… فغيّره التصحيح التلقائي في كل مرة',
        fr: 'fois où tu as tapé ton prénom. « Corrigé » les 3 fois.',
        es: 'veces escribiste tu nombre. El corrector lo “arregló” las 3.',
        ja: '回、自分の名前を打った。3回とも予測変換に直された。',
        ko: '번 자기 이름을 쳤는데, 자동 수정이 3번 다 바꿨어요.',
      },
    },
    caption: {
      tr: 'Artık adından bile emin değilsin',
      en: "Now you're not even sure of your name",
      de: 'Jetzt zweifelst du an deinem Namen',
      ar: 'صرت تشك في اسمك',
      fr: 'Tu doutes même de ton prénom',
      es: 'Ya dudas hasta de tu nombre',
      ja: 'もう自分の名前にも自信がない',
      ko: '이제 자기 이름도 헷갈려요',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.food,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '5', en: '5', de: '5', ar: '5', fr: '5', es: '5', ja: '5', ko: '5' },
      text: {
        tr: 'kez QR kodun fotoğrafını çektin; menü bir türlü açılmadı',
        en: 'times you took a photo of the QR code. The menu never opened.',
        de: 'Mal den QR-Code fotografiert. Das Menü ging nie auf.',
        ar: 'مرات التقطت صورة لرمز QR… ولم تُفتح القائمة أبدًا',
        fr: 'fois où tu as pris le QR code en photo. Menu toujours fermé.',
        es: 'veces le tomaste una foto al código QR. El menú nunca abrió.',
        ja: '回、QRコードを写真に撮った。メニューは開かなかった。',
        ko: '번 QR 코드를 사진으로 찍었어요. 메뉴는 끝내 안 열렸고요.',
      },
    },
    caption: {
      tr: 'Sonunda kâğıt menü getirdiler',
      en: 'They brought you a paper menu in the end',
      de: 'Am Ende kam doch die Papierkarte',
      ar: 'في النهاية أحضروا لك قائمة ورقية',
      fr: "Au final, on t'a apporté un menu papier",
      es: 'Al final te trajeron el menú de papel',
      ja: '結局、紙のメニューが出てきた',
      ko: '결국 종이 메뉴판을 갖다줬다',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: { tr: 'BUGÜN', en: 'TODAY', de: 'HEUTE', ar: 'اليوم', fr: "AUJOURD'HUI", es: 'HOY', ja: '今日', ko: '오늘' },
      big: { tr: '1', en: '1', de: '1', ar: '1', fr: '1', es: '1', ja: '1', ko: '1' },
      text: {
        tr: 'bilinmeyen numara aradı; kim olduğunu 2 saat düşündün',
        en: 'unknown number called. You spent 2 hours guessing who.',
        de: 'unbekannte Nummer rief an. 2 Stunden lang gerätselt, wer.',
        ar: 'رقم مجهول اتصل بك… وقضيت ساعتين تخمّن من يكون',
        fr: "numéro inconnu a appelé. Tu as cherché qui c'était pendant 2 h.",
        es: 'número desconocido te llamó. Pasaste 2 horas adivinando quién.',
        ja: '件の知らない番号から着信。誰だったのか2時間考えた。',
        ko: '통, 모르는 번호로 전화가 왔어요. 누군지 2시간 고민했죠.',
      },
    },
    caption: {
      tr: 'Kargocuymuş',
      en: 'It was the delivery guy',
      de: 'Es war der Paketbote',
      ar: 'كان عامل التوصيل',
      fr: "C'était le livreur",
      es: 'Era el repartidor',
      ja: '宅配便だった',
      ko: '택배 기사님이었다',
    },
  },
  {
    emoji: '🎵',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ZİL SESİ TIER LIST',
        en: 'RINGTONE TIER LIST',
        de: 'KLINGELTON-RANKING',
        ar: 'تصنيف نغمات الرنين',
        fr: 'TIER LIST DES SONNERIES',
        es: 'TIER LIST DE TONOS',
        ja: '着信音Tier表',
        ko: '벨소리 티어표',
      },
      rows: [['🔕'], ['🐦', '🎹'], ['🔔', '🎺'], ['☎️']],
    },
    caption: {
      tr: 'Klasik zil çalınca 30 kişi cebini yokluyor',
      en: 'Classic ring goes off, 30 people check their pockets',
      de: 'Klassischer Klingelton: 30 Leute greifen in die Tasche',
      ar: 'ترنّ النغمة الكلاسيكية فيتحسّس 30 شخصًا جيوبهم',
      fr: 'Sonnerie classique : 30 personnes fouillent leur poche',
      es: 'Suena el tono clásico y 30 personas revisan su bolsillo',
      ja: '定番の着信音が鳴ると、30人がポケットを確認する',
      ko: '기본 벨소리 울리면 30명이 주머니를 뒤진다',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'TELEFONUMU BULDUĞUM YERLER',
        en: 'WHERE I FIND MY PHONE',
        de: 'WO ICH MEIN HANDY FINDE',
        ar: 'أين أجد هاتفي',
        fr: 'OÙ JE RETROUVE MON TEL',
        es: 'DÓNDE ENCUENTRO MI TELÉFONO',
        ja: 'スマホが見つかる場所',
        ko: '내 폰이 발견되는 곳',
      },
      rows: [['🛋️'], ['🛏️', '🧥'], ['🧺', '🚗'], ['🧊']],
    },
    caption: {
      tr: 'Buzdolabında buldum. Soğuk karşıladı.',
      en: 'Found it in the fridge. It gave me the cold shoulder.',
      de: 'Im Kühlschrank gefunden. Die Begrüßung war frostig.',
      ar: 'وجدته في الثلاجة… وكان استقباله باردًا',
      fr: "Retrouvé dans le frigo. L'accueil a été glacial.",
      es: 'Apareció en la nevera. Me recibió con frialdad.',
      ja: '冷蔵庫で見つけた。対応が冷たかった。',
      ko: '냉장고에서 찾았다. 태도가 싸늘했다.',
    },
  },
  {
    emoji: '🧭',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🆕',
        app: {
          tr: 'Güncelleme',
          en: 'Update',
          de: 'Update',
          ar: 'التحديث',
          fr: 'Mise à jour',
          es: 'Actualización',
          ja: 'アップデート',
          ko: '업데이트',
        },
        text: {
          tr: 'Yeni: her şeyin yeri değişti!',
          en: "What's new: everything moved!",
          de: 'Neu: Alles ist jetzt woanders!',
          ar: 'الجديد: كل شيء تغيّر مكانه!',
          fr: 'Nouveau : tout a changé de place !',
          es: 'Novedad: ¡todo cambió de lugar!',
          ja: '新機能：すべての場所が変わりました！',
          ko: '새 기능: 모든 게 자리를 옮겼어요!',
        },
      },
    },
    caption: {
      tr: 'Ayarlarda kayboldum, harita lazım',
      en: "I'm lost in Settings. Send a map.",
      de: 'Hab mich in den Einstellungen verlaufen',
      ar: 'ضعت في الإعدادات، أحتاج إلى خريطة',
      fr: 'Il me faut une carte pour les réglages',
      es: 'Me perdí en Ajustes. Necesito un mapa.',
      ja: '設定アプリで迷子。地図ください。',
      ko: '설정에서 길 잃음. 지도 좀 보내 줘',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⌨️',
        app: {
          tr: 'Klavye',
          en: 'Keyboard',
          de: 'Tastatur',
          ar: 'لوحة المفاتيح',
          fr: 'Clavier',
          es: 'Teclado',
          ja: 'キーボード',
          ko: '키보드',
        },
        text: {
          tr: 'Sözlüğe eklendi: “tmmmmm”',
          en: 'Added to dictionary: “okkkkk”',
          de: 'Neues Wort gelernt: „okeeee“',
          ar: 'أُضيفت إلى القاموس: «حسنًااا»',
          fr: 'Ajouté au dictionnaire : « okkkk »',
          es: 'Añadido al diccionario: “okiiii”',
          ja: '辞書に登録：「りょ」',
          ko: '사전에 추가됨: “ㅇㅋㅇㅋㅇㅋ”',
        },
      },
    },
    caption: {
      tr: 'Klavyem artık benim gibi konuşuyor',
      en: 'My keyboard talks like me now',
      de: 'Meine Tastatur redet jetzt wie ich',
      ar: 'لوحة مفاتيحي صارت تتكلم مثلي',
      fr: 'Mon clavier parle comme moi maintenant',
      es: 'Mi teclado ya habla como yo',
      ja: 'キーボードが私の口調になってきた',
      ko: '키보드가 이제 나처럼 말한다',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '⚙️',
        app: {
          tr: 'Ayarlar',
          en: 'Settings',
          de: 'Einstellungen',
          ar: 'الإعدادات',
          fr: 'Réglages',
          es: 'Ajustes',
          ja: '設定',
          ko: '설정',
        },
        text: {
          tr: 'Uçak modu 6 saattir açık',
          en: 'Airplane mode on for 6 hours',
          de: 'Flugmodus seit 6 Stunden an',
          ar: 'وضع الطيران مفعّل منذ 6 ساعات',
          fr: 'Mode avion activé depuis 6 h',
          es: 'Modo avión activado hace 6 horas',
          ja: '機内モードが6時間オンになっています',
          ko: '비행기 모드 6시간째 켜짐',
        },
      },
    },
    caption: {
      tr: 'Ben de kimse yazmıyor diye üzülüyordum',
      en: 'And I was sad nobody was texting me',
      de: 'Und ich dachte, keiner schreibt mir',
      ar: 'وأنا حزين لأن لا أحد يراسلني',
      fr: "Et moi qui croyais que personne m'écrivait",
      es: 'Y yo triste porque nadie me escribía',
      ja: '誰からも連絡が来ないって落ち込んでた',
      ko: '아무도 연락 안 한다고 서운해했는데',
    },
  },
  {
    emoji: '🙉',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🎙️',
        app: {
          tr: 'Sesli asistan',
          en: 'Voice assistant',
          de: 'Sprachassistent',
          ar: 'المساعد الصوتي',
          fr: 'Assistant vocal',
          es: 'Asistente de voz',
          ja: '音声アシスタント',
          ko: '음성 비서',
        },
        text: {
          tr: '“Anime” için sonuçlar gösteriliyor',
          en: 'Showing results for “Tex-Mex”',
          de: 'Rufe „Lama“ an…',
          ar: 'نتائج البحث عن «مانجو»',
          fr: 'Résultats pour « pelle à maman »',
          es: 'Buscando llamas cerca de ti…',
          ja: '「パパイヤ」の検索結果を表示中',
          ko: '‘엄마 전’ 레시피를 찾았어요',
        },
      },
    },
    caption: {
      tr: '“Annemi ara” demiştim',
      en: 'I said “Text Mom.”',
      de: 'Ich sagte: „Ruf Mama an“',
      ar: 'قلتُ: «اتصل بماما»',
      fr: "J'avais dit « appelle maman »",
      es: 'Dije “llama a mamá”',
      ja: '「パパに電話」って言ったのに',
      ko: '“엄마 전화”라고 했는데',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kendin ol. Gerisini filtreler hallediyor.',
        en: 'Be yourself. The filters have everyone else covered.',
        de: 'Sei du selbst. Für alles andere gibt es Filter.',
        ar: 'كن نفسك، فالفلاتر تتكفّل بالباقي.',
        fr: "Sois toi-même. Les filtres s'occupent du reste.",
        es: 'Sé tú mismo. Del resto se encargan los filtros.',
        ja: '自分らしくいよう。ほかの誰かはフィルターがやってくれる。',
        ko: '너 자신이 되어라. 나머지는 필터가 알아서 한다.',
      },
    },
    caption: {
      tr: 'Bugünkü tercihim: köpek kulakları',
      en: 'Today I went with dog ears',
      de: 'Heute mit Hundeohren',
      ar: 'اليوم اخترت أذني الكلب',
      fr: "Aujourd'hui : oreilles de chien",
      es: 'Hoy elegí orejas de perro',
      ja: '今日の私は犬耳で',
      ko: '오늘의 선택: 강아지 귀',
    },
  },
  {
    emoji: '🔕',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Sessizlik en güçlü cevaptır. — 3 yıldır sessizde olan telefonum',
        en: 'Silence speaks volumes. — My phone, on silent for 3 years',
        de: 'Schweigen ist auch eine Antwort. — Mein Handy, seit 3 Jahren lautlos',
        ar: 'الصمت أبلغ جواب. — هاتفي الصامت منذ 3 سنوات',
        fr: 'Le silence est une réponse. — Mon tel, en silencieux depuis 3 ans',
        es: 'El silencio lo dice todo. — Mi teléfono, en silencio hace 3 años',
        ja: '沈黙は最強の答えだ。— 3年間マナーモードの私のスマホ',
        ko: '침묵은 가장 강력한 대답이다. — 3년째 무음 모드인 내 폰',
      },
    },
    caption: {
      tr: 'Aradıysan kusura bakma',
      en: 'Sorry if you called',
      de: 'Falls du angerufen hast: sorry',
      ar: 'إن كنت اتصلت بي، فآسف',
      fr: "Si tu m'as appelé, désolé",
      es: 'Si me llamaste, perdón',
      ja: '電話くれてたらごめん',
      ko: '전화했다면 미안',
    },
  },
  {
    emoji: '🌄',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat panoramaya benzer: kıpırdarsan tuhaf çıkarsın.',
        en: 'Life is like a panorama: move and you come out weird.',
        de: 'Das Leben ist wie ein Panorama: Wer wackelt, sieht komisch aus.',
        ar: 'الحياة مثل الصورة البانورامية: إن تحركت ظهرت بشكل غريب.',
        fr: "La vie, c'est comme un panorama : si tu bouges, tu sors bizarre.",
        es: 'La vida es como una panorámica: si te mueves, sales raro.',
        ja: '人生はパノラマ写真。動くと変に写る。',
        ko: '인생은 파노라마 같다. 움직이면 이상하게 나온다.',
      },
    },
    caption: {
      tr: 'Geçen hafta 3 kollu çıktım',
      en: 'Last week I came out with 3 arms',
      de: 'Letzte Woche hatte ich 3 Arme',
      ar: 'الأسبوع الماضي ظهرت بثلاث أذرع',
      fr: "La semaine dernière, j'avais 3 bras",
      es: 'La semana pasada salí con 3 brazos',
      ja: '先週、腕が3本で写った',
      ko: '지난주엔 팔이 3개로 나왔다',
    },
  },
  {
    emoji: '👥',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Zamanlama her şeydir. — Görüntülü aramada aynı anda konuşan iki kişi',
        en: 'Timing is everything. — Two people talking at once on a video call',
        de: 'Timing ist alles. — Zwei, die im Videocall gleichzeitig reden',
        ar: 'التوقيت هو كل شيء. — شخصان يتكلمان معًا في مكالمة فيديو',
        fr: "Le timing, c'est tout. — Deux qui parlent en même temps en visio",
        es: 'El momento justo lo es todo. — Dos hablando a la vez en videollamada',
        ja: 'タイミングがすべて。— ビデオ通話で同時にしゃべる2人',
        ko: '타이밍이 전부다. — 영상 통화에서 동시에 말하는 두 사람',
      },
    },
    caption: {
      tr: '“Sen söyle.” “Yok, sen söyle.”',
      en: '“You go.” “No, you go.”',
      de: '„Du zuerst.“ „Nein, du.“',
      ar: '«تكلّم أنت». «لا، أنت أولًا».',
      fr: '« Vas-y. » « Non, vas-y toi. »',
      es: '“Tú primero.” “No, tú.”',
      ja: '「どうぞ」「いえ、どうぞ」',
      ko: '“먼저 말해.” “아냐, 너 먼저.”',
    },
  },
];

export const PHONE_LIKE: readonly Draft[] = [
  {
    emoji: '📵',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: '1 saat telefona bakmadım!! (öbür odada kalmış)',
      en: 'a whole hour phone-free!! (left it in the other room)',
      de: 'eine stunde ohne handy!! (lag im anderen zimmer)',
      ar: 'ساعة كاملة بلا هاتف!! (نسيته في الغرفة الأخرى)',
      fr: "une heure sans téléphone !! (oublié dans l'autre pièce)",
      es: '¡¡una hora sin teléfono!! (lo dejé en otra habitación)',
      ja: '1時間スマホ見なかった！！（別の部屋に置き忘れてた）',
      ko: '1시간 동안 폰 안 봄!! (다른 방에 두고 옴)',
    },
  },
  {
    emoji: '👵',
    user: ACCOUNTS.arda,
    body: { format: 'scene' },
    caption: {
      tr: 'anneanneme görüntülü aramayı öğrettim, her gün arıyor',
      en: 'taught grandma video calls, now she calls every day',
      de: 'hab oma videoanrufe beigebracht, jetzt ruft sie täglich an',
      ar: 'علّمت جدتي مكالمات الفيديو، وصارت تتصل كل يوم',
      fr: "j'ai appris la visio à mamie, elle appelle tous les jours",
      es: 'le enseñé videollamadas a mi abuela, ahora llama a diario',
      ja: 'おばあちゃんにビデオ通話を教えたら、毎日かかってくる',
      ko: '할머니한테 영상 통화 알려 드림. 이제 매일 전화 오심',
    },
  },
  {
    emoji: '🎹',
    user: ACCOUNTS.can,
    body: { format: 'scene' },
    caption: {
      tr: 'zil sesimi kendim besteledim: 4 nota ama benim',
      en: 'composed my own ringtone: 4 notes, all mine',
      de: 'klingelton selbst komponiert: 4 töne, aber meine',
      ar: 'لحّنت نغمة رنيني بنفسي: 4 نغمات لكنها لي',
      fr: "j'ai composé ma sonnerie : 4 notes, mais à moi",
      es: 'compuse mi propio tono: 4 notas, pero mías',
      ja: '着信音を自分で作曲した。4音だけど私の曲',
      ko: '벨소리 직접 작곡함. 음 4개지만 내 거',
    },
  },
  {
    emoji: '😊',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: '#filtresiz',
        en: '#nofilter',
        de: '#ohnefilter',
        ar: '#بلا_فلتر',
        fr: '#sansfiltre',
        es: '#sinfiltro',
        ja: '#加工なし',
        ko: '#필터없음',
      },
    },
    caption: {
      tr: 'ilk kez filtresiz paylaşıyorum, alkış lütfen',
      en: 'first post with no filter, applause please',
      de: 'zum ersten mal ohne filter gepostet, applaus bitte',
      ar: 'أول مرة أنشر صورة بلا فلتر، صفّقوا لي',
      fr: 'première photo sans filtre, applaudissez',
      es: 'primera foto sin filtro, aplausos por favor',
      ja: '初めて無加工で投稿する。拍手ください',
      ko: '처음으로 필터 없이 올림. 박수 부탁',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'hepsi aynı kedi',
        en: 'all the same cat',
        de: 'alles dieselbe katze',
        ar: 'كلها القطة نفسها',
        fr: 'toujours le même chat',
        es: 'es el mismo gato',
        ja: '全部同じ猫',
        ko: '전부 같은 고양이',
      },
    },
    caption: {
      tr: 'panorama çektim, kedim 3 kere kadraja girdi',
      en: 'took a panorama, my cat made it in 3 times',
      de: 'panorama gemacht, meine katze ist 3-mal drauf',
      ar: 'التقطت صورة بانورامية فظهرت قطتي 3 مرات',
      fr: 'photo panoramique : mon chat y est 3 fois',
      es: 'hice una panorámica y mi gato salió 3 veces',
      ja: 'パノラマ撮ったら、猫が3回写り込んだ',
      ko: '파노라마 찍었더니 고양이가 3번 나옴',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.tolga,
    body: {
      format: 'polaroid',
      note: {
        tr: 'emekli etmiyorum',
        en: 'not retiring it',
        de: 'wird nicht ausgemustert',
        ar: 'لن أستبدله',
        fr: 'pas question de le changer',
        es: 'no pienso jubilarlo',
        ja: '引退させません',
        ko: '은퇴는 없다',
      },
    },
    caption: {
      tr: 'en sadık dostum: 7 yıllık telefonum',
      en: 'my most loyal friend: my 7-year-old phone',
      de: 'mein treuester begleiter: 7 jahre altes handy',
      ar: 'أوفى أصدقائي: هاتفي ذو السبع سنوات',
      fr: 'mon plus fidèle ami : mon tel de 7 ans',
      es: 'mi amigo más fiel: mi teléfono de 7 años',
      ja: 'いちばん忠実な相棒：7年使ってるスマホ',
      ko: '제일 의리 있는 친구: 7년 된 내 폰',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'el yapımı',
        en: 'handmade',
        de: 'handgemacht',
        ar: 'صنع يدوي',
        fr: 'fait main',
        es: 'hecho a mano',
        ja: 'ハンドメイド',
        ko: '핸드메이드',
      },
    },
    caption: {
      tr: 'telefon kılıfımı kendim boyadım, azıcık taştı',
      en: 'painted my own phone case, went outside the lines a bit',
      de: 'handyhülle selbst bemalt, bisschen über den rand',
      ar: 'لوّنت غطاء هاتفي بنفسي… وخرجت عن الخطوط قليلًا',
      fr: "j'ai peint ma coque moi-même, ça déborde un peu",
      es: 'pinté mi propia funda, me salí un poquito',
      ja: 'スマホケースを自分で塗った。ちょっとはみ出た',
      ko: '폰 케이스 직접 칠함. 살짝 삐져나감',
    },
  },
  {
    emoji: '📦',
    user: ACCOUNTS.cemre,
    body: { format: 'dump', emojis: ['📦', '📲', '✨', '🎉', '🙌'] },
    caption: {
      tr: 'yeni telefon dump’ı: kutusunu atamam tabii',
      en: 'new phone dump: obviously keeping the box',
      de: 'neues-handy-dump: den karton behalte ich natürlich',
      ar: 'هاتف جديد! والعلبة سأحتفظ بها طبعًا',
      fr: 'nouveau tel : je garde la boîte, évidemment',
      es: 'teléfono nuevo: la caja me la quedo, obvio',
      ja: '新しいスマホまとめ：箱はもちろん捨てない',
      ko: '새 폰 덤프: 박스는 당연히 안 버림',
    },
  },
  {
    emoji: '😆',
    user: ACCOUNTS.onur,
    body: { format: 'dump', emojis: ['😆', '😮', '🤪', '😝', '🙃'] },
    caption: {
      tr: 'görüntülü arama dump’ı: en güzel donduğumuz anlar',
      en: 'video call dump: our best frozen frames',
      de: 'videocall-dump: unsere schönsten standbilder',
      ar: 'مكالمة الفيديو: أجمل لحظات تجمّدنا',
      fr: 'dump de visio : nos plus beaux arrêts sur image',
      es: 'resumen de videollamada: nuestras mejores caras congeladas',
      ja: 'ビデオ通話まとめ：いちばんきれいに固まった瞬間',
      ko: '영상 통화 덤프: 제일 예쁘게 멈춘 순간들',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🐈', '🌅', '🍝', '👖', '🌸'] },
    caption: {
      tr: 'galeri dump’ı: kedi, gün batımı ve cebimin içi',
      en: 'camera roll dump: cat, sunset, inside of my pocket',
      de: 'galerie-dump: katze, sonnenuntergang, hosentasche von innen',
      ar: 'من معرض صوري: قطة، غروب، وداخل جيبي',
      fr: 'ma galerie : chat, coucher de soleil, fond de poche',
      es: 'mi galería: gato, atardecer y el interior de mi bolsillo',
      ja: 'カメラロールまとめ：猫、夕日、ポケットの中',
      ko: '앨범 덤프: 고양이, 노을, 주머니 속',
    },
  },
];

export const PHONE_HOLD: readonly Draft[] = [
  {
    emoji: '🖼️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Galerideki o fotoğrafı 2 saniyede buldun!',
      en: 'Found that one photo in your camera roll in 2 seconds!',
      de: 'Das gesuchte Foto in 2 Sekunden in der Galerie gefunden!',
      ar: 'وجدت تلك الصورة في المعرض خلال ثانيتين!',
      fr: 'Retrouvé LA photo de ta galerie en 2 secondes !',
      es: '¡Encontraste esa foto de tu galería en 2 segundos!',
      ja: 'カメラロールのあの写真を2秒で発見！',
      ko: '앨범 속 그 사진을 2초 만에 찾았어요!',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir bulunur: 10 saniyelik sesli mesaj',
      en: 'Rare find: a 10-second voice message',
      de: 'Seltener Fund: eine 10-Sekunden-Sprachnachricht',
      ar: 'اكتشاف نادر: رسالة صوتية مدتها 10 ثوانٍ',
      fr: 'Trouvaille rare : un vocal de 10 secondes',
      es: 'Hallazgo raro: un audio de 10 segundos',
      ja: 'レア発見：10秒のボイスメッセージ',
      ko: '희귀템: 10초짜리 음성 메시지',
    },
  },
  {
    emoji: '🍀',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yanlış gruba attın, kimse görmeden sildin!',
      en: 'Wrong group chat, deleted before anyone saw!',
      de: 'Falsche Gruppe, gelöscht, bevor es jemand sah!',
      ar: 'أرسلتها إلى المجموعة الخطأ وحذفتها قبل أن يراها أحد!',
      fr: "Mauvais groupe, supprimé avant que quelqu'un le voie !",
      es: '¡Grupo equivocado, y lo borraste antes de que lo vieran!',
      ja: 'グループを間違えたけど、誰かが見る前に消せた！',
      ko: '단톡방 잘못 보냈는데 아무도 보기 전에 삭제!',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Telefon yüzüstü düştü… ekran tek parça!',
      en: 'Phone landed face down… screen in one piece!',
      de: 'Handy aufs Display gefallen… alles heil!',
      ar: 'سقط الهاتف على وجهه… والشاشة سليمة!',
      fr: 'Tel tombé côté écran… et intact !',
      es: 'El teléfono cayó boca abajo… ¡y la pantalla intacta!',
      ja: 'スマホが画面から落下…でも無傷！',
      ko: '폰이 화면 쪽으로 떨어짐… 액정 멀쩡!',
    },
  },
  {
    emoji: '🎙️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sesli asistan ilk seferde anladı. Nadir kayıt.',
      en: 'The voice assistant got it on the first try. Rare footage.',
      de: 'Der Sprachassistent hat es sofort verstanden. Rarität.',
      ar: 'المساعد الصوتي فهمك من أول مرة. تسجيل نادر.',
      fr: "L'assistant vocal a compris du premier coup. Image rare.",
      es: 'El asistente de voz entendió a la primera. Imágenes únicas.',
      ja: '音声アシスタントが一発で理解した。貴重映像。',
      ko: '음성 비서가 한 번에 알아들었다. 희귀 영상.',
    },
  },
  {
    emoji: '🧠',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Telefonu açtın ve nedenini hatırladın. Efsane!',
      en: 'You unlocked your phone and remembered why. Legendary!',
      de: 'Handy entsperrt und noch gewusst, wieso. Legendär!',
      ar: 'فتحت هاتفك وتذكرت السبب. أسطوري!',
      fr: 'Tel déverrouillé, et tu sais encore pourquoi. Légendaire !',
      es: 'Abriste el teléfono y recordaste para qué. ¡Legendario!',
      ja: 'スマホを開いて、開いた理由を覚えてた。伝説！',
      ko: '폰을 켜고 왜 켰는지 기억났어요. 전설!',
    },
  },
  {
    emoji: '✅',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yazım hatasını son saniyede yakaladın. Şimdi gönder!',
      en: 'Caught the typo at the last second. Now hit send!',
      de: 'Tippfehler in letzter Sekunde entdeckt. Jetzt senden!',
      ar: 'اكتشفت الخطأ الإملائي في آخر ثانية. أرسل الآن!',
      fr: 'Faute repérée à la dernière seconde. Envoie maintenant !',
      es: 'Detectaste el error justo a tiempo. ¡Ahora envía!',
      ja: '誤字にギリギリで気づいた。さあ送信！',
      ko: '마지막 순간에 오타 발견. 이제 전송!',
    },
  },
  {
    emoji: '✨',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tek parmak izi yok: pırıl pırıl bir ekran',
      en: 'Not a single fingerprint: a spotless screen',
      de: 'Kein einziger Fingerabdruck: ein blitzblankes Display',
      ar: 'ولا بصمة إصبع واحدة: شاشة لامعة تمامًا',
      fr: 'Pas une seule trace de doigt : un écran impeccable',
      es: 'Ni una huella: una pantalla impecable',
      ja: '指紋ひとつない、ピカピカの画面',
      ko: '지문 하나 없는 반짝반짝한 화면',
    },
  },
];

export const PHONE_FREEZE: readonly Draft[] = [
  {
    emoji: '📷',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'PORTRE MODU',
        en: 'PORTRAIT MODE',
        de: 'PORTRÄTMODUS',
        ar: 'وضع البورتريه',
        fr: 'MODE PORTRAIT',
        es: 'MODO RETRATO',
        ja: 'ポートレート',
        ko: '인물 모드',
      },
      small: {
        tr: 'ARKA PLAN BULANIKLAŞIYOR',
        en: 'BACKGROUND BLURRING',
        de: 'HINTERGRUND WIRD UNSCHARF',
        ar: 'جارٍ تمويه الخلفية',
        fr: 'ARRIÈRE-PLAN FLOUTÉ',
        es: 'DESENFOCANDO EL FONDO',
        ja: '背景をぼかしています',
        ko: '배경 흐림 처리 중',
      },
    },
    caption: {
      tr: 'Kıpırdarsan sen de bulanıklaşırsın.',
      en: "Move and you'll blur too.",
      de: 'Wer wackelt, wird auch unscharf.',
      ar: 'إن تحركت صرت ضبابيًا أنت أيضًا.',
      fr: 'Si tu bouges, toi aussi tu passes dans le flou.',
      es: 'Si te mueves, también te desenfoca.',
      ja: '動いたら、あなたもぼける。',
      ko: '움직이면 같이 흐려져요.',
    },
    headline: {
      tr: 'Portre modu sonunda seni netledi',
      en: 'Portrait mode finally got you sharp',
      de: 'Porträtmodus: Endlich bist du im Fokus',
      ar: 'وضع البورتريه أظهرك بوضوح أخيرًا',
      fr: 'Enfin la mise au point sur toi',
      es: 'El modo retrato por fin te enfocó',
      ja: 'ポートレートでやっとピントが合った',
      ko: '인물 모드가 드디어 초점을 잡았어요',
    },
  },
  {
    emoji: '🕸️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'KIRIK EKRAN',
        en: 'CRACKED SCREEN',
        de: 'DISPLAY KAPUTT',
        ar: 'شاشة مكسورة',
        fr: 'ÉCRAN FISSURÉ',
        es: 'PANTALLA ROTA',
        ja: '画面割れ',
        ko: '액정 깨짐',
      },
      small: {
        tr: 'ÇATLAK İLERLEYEBİLİR',
        en: 'CRACK MAY SPREAD',
        de: 'RISS KANN SICH AUSBREITEN',
        ar: 'قد يمتدّ الشق',
        fr: "LA FISSURE PEUT S'ÉTENDRE",
        es: 'LA GRIETA PUEDE CRECER',
        ja: 'ヒビが広がるおそれあり',
        ko: '금이 더 갈 수 있음',
      },
    },
    caption: {
      tr: 'Hiç dokunma, yayılır.',
      en: "Don't even breathe on it.",
      de: 'Nicht mal anhauchen.',
      ar: 'لا تلمسها أبدًا، فالشقّ ينتشر.',
      fr: 'Souffle même pas dessus.',
      es: 'Ni le respires encima.',
      ja: '息もかけないで。',
      ko: '숨도 쉬지 마세요.',
    },
    headline: {
      tr: 'Ekrandaki çatlak büyümek üzere',
      en: 'The crack is about to spread',
      de: 'Der Riss wird gleich länger',
      ar: 'الشقّ على وشك أن يكبر',
      fr: "La fissure est sur le point de s'étendre",
      es: 'La grieta está a punto de crecer',
      ja: '画面のヒビが広がりそう',
      ko: '액정 금이 번지기 직전이에요',
    },
  },
  {
    emoji: '🔳',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'QR OKUNUYOR',
        en: 'SCANNING QR',
        de: 'QR-SCAN',
        ar: 'جارٍ مسح الرمز',
        fr: 'SCAN QR',
        es: 'ESCANEANDO QR',
        ja: 'QR読み取り中',
        ko: 'QR 인식 중',
      },
      small: {
        tr: 'KAMERAYI SABİT TUTUN',
        en: 'HOLD YOUR CAMERA STEADY',
        de: 'KAMERA RUHIG HALTEN',
        ar: 'ثبّت الكاميرا',
        fr: "NE BOUGEZ PAS L'APPAREIL",
        es: 'MANTENGA LA CÁMARA QUIETA',
        ja: 'カメラを動かさないで',
        ko: '카메라를 고정하세요',
      },
    },
    caption: {
      tr: 'Kıpırdarsan baştan okutursun.',
      en: 'Move and you start over.',
      de: 'Wackeln heißt: von vorn.',
      ar: 'إن تحركت ستبدأ من جديد.',
      fr: 'Si tu bouges, tu recommences.',
      es: 'Si te mueves, empiezas de nuevo.',
      ja: '動いたら、最初からやり直し。',
      ko: '움직이면 처음부터 다시 해야 해요.',
    },
    headline: {
      tr: 'Menü açılmak üzere, elin titremesin',
      en: "The menu's about to open. Steady hands.",
      de: 'Das Menü lädt gleich. Hände ruhig!',
      ar: 'قائمة الطعام على وشك أن تُفتح، لا ترتجف',
      fr: "Le menu va s'ouvrir. Tremble pas.",
      es: 'El menú está por abrirse. Pulso firme.',
      ja: 'メニューが開く寸前。手を止めて',
      ko: '메뉴가 곧 열려요. 손 떨지 마세요',
    },
  },
  {
    emoji: '🌃',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'GECE MODU',
        en: 'NIGHT MODE',
        de: 'NACHTMODUS',
        ar: 'الوضع الليلي',
        fr: 'MODE NUIT',
        es: 'MODO NOCHE',
        ja: 'ナイトモード',
        ko: '야간 모드',
      },
      small: {
        tr: 'POZLAMA: 8 SANİYE',
        en: 'EXPOSURE: 8 SECONDS',
        de: 'BELICHTUNG: 8 SEKUNDEN',
        ar: 'مدة التعريض: 8 ثوانٍ',
        fr: 'POSE : 8 SECONDES',
        es: 'EXPOSICIÓN: 8 SEGUNDOS',
        ja: '露光：8秒',
        ko: '노출: 8초',
      },
    },
    caption: {
      tr: 'Sekiz saniye mobilya ol.',
      en: 'Be furniture for 8 seconds.',
      de: 'Sei 8 Sekunden lang ein Möbelstück.',
      ar: 'كن قطعة أثاث لثماني ثوانٍ.',
      fr: 'Sois un meuble pendant 8 secondes.',
      es: 'Sé un mueble durante 8 segundos.',
      ja: '8秒間、家具になって。',
      ko: '8초 동안 가구가 되세요.',
    },
    headline: {
      tr: 'Gece fotoğrafı çekiliyor',
      en: 'Night photo in progress',
      de: 'Nachtfoto wird aufgenommen',
      ar: 'جارٍ التقاط صورة ليلية',
      fr: 'Photo de nuit en cours',
      es: 'Foto nocturna en proceso',
      ja: '夜景を撮影中',
      ko: '야간 사진 촬영 중',
    },
  },
  {
    emoji: '📳',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'WARNING',
        de: 'VORSICHT',
        ar: 'تحذير',
        fr: 'ATTENTION',
        es: 'CUIDADO',
        ja: '注意',
        ko: '주의',
      },
      small: {
        tr: 'TELEFON MASANIN KENARINDA',
        en: 'PHONE ON THE EDGE',
        de: 'HANDY AM TISCHRAND',
        ar: 'الهاتف على حافة الطاولة',
        fr: 'TÉLÉPHONE AU BORD DE LA TABLE',
        es: 'TELÉFONO AL BORDE DE LA MESA',
        ja: '机のはしにスマホあり',
        ko: '폰이 책상 끝에 있음',
      },
    },
    caption: {
      tr: 'Kıpırdama. Bir titreşim daha, düşer.',
      en: "Don't move. One more buzz and it drops.",
      de: 'Keine Bewegung. Noch ein Brummen, und es fällt.',
      ar: 'لا تتحرك. اهتزازة أخرى وسيسقط.',
      fr: 'Bouge pas. Encore un bzz et il tombe.',
      es: 'No te muevas. Una vibración más y se cae.',
      ja: '動かないで。あと1回震えたら落ちる。',
      ko: '움직이지 마세요. 한 번 더 울리면 떨어져요.',
    },
    headline: {
      tr: 'Titreşim telefonu kenara getirdi',
      en: 'Vibrate mode walked it to the edge',
      de: 'Der Vibrationsalarm schob es zum Rand',
      ar: 'الاهتزاز دفع الهاتف إلى الحافة',
      fr: "Le vibreur l'a poussé au bord",
      es: 'La vibración lo llevó hasta el borde',
      ja: 'バイブでスマホがはしまで移動した',
      ko: '진동이 폰을 끝까지 밀어냈어요',
    },
  },
  {
    emoji: '🤭',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
        ja: 'リビング',
        ko: '거실',
      },
    },
    caption: {
      tr: 'Gülersen 6. kez baştan kaydeder.',
      en: "Laugh and it's take 6.",
      de: 'Lachst du, kommt Versuch Nr. 6.',
      ar: 'إن ضحكت فسيعيد التسجيل للمرة السادسة.',
      fr: "Si tu ris, c'est la 6e prise.",
      es: 'Si te ríes, va por el sexto intento.',
      ja: '笑ったら6回目の録り直し。',
      ko: '웃으면 6번째 다시 녹음해요.',
    },
    headline: {
      tr: 'Kanka sesli mesajda, gözü sende',
      en: "Bestie's mid voice note, eyes on you",
      de: 'Sprachnachricht läuft, er schaut her',
      ar: 'صديقك يسجّل رسالة صوتية وعيناه عليك',
      fr: 'Ton pote enregistre un vocal et te fixe',
      es: 'Tu amigo graba un audio y te mira',
      ja: '親友がボイス録音中、こっち見てる',
      ko: '절친이 음성 녹음 중, 날 보고 있어요',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAFE',
        en: 'CAFÉ',
        de: 'CAFÉ',
        ar: 'المقهى',
        fr: 'CAFÉ',
        es: 'CAFETERÍA',
        ja: 'カフェ',
        ko: '카페',
      },
    },
    caption: {
      tr: 'Bari güzel çık. Kıpırdama.',
      en: "At least look good. Don't move.",
      de: 'Dann wenigstens hübsch. Stillhalten.',
      ar: 'اظهر بشكل جميل على الأقل. لا تتحرك.',
      fr: 'Soigne ta pose. Bouge pas.',
      es: 'Al menos sal bien. No te muevas.',
      ja: 'せめて盛れてて。動かないで。',
      ko: '기왕이면 잘 나와야죠. 움직이지 마세요.',
    },
    headline: {
      tr: 'Yan masanın selfiesinde sen de varsın',
      en: "Next table's selfie: you're in the back",
      de: 'Selfie am Nebentisch. Du bist drauf.',
      ar: 'سيلفي على الطاولة المجاورة، وأنت خلفهم',
      fr: 'Selfie à la table voisine, tu es dedans',
      es: 'Selfie en la mesa de al lado: sales tú',
      ja: '隣の席の自撮りに写り込んでる',
      ko: '옆 테이블 셀카에 같이 찍혔어요',
    },
  },
  {
    emoji: '🕺',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KORİDOR',
        en: 'HALLWAY',
        de: 'FLUR',
        ar: 'الممر',
        fr: 'COULOIR',
        es: 'PASILLO',
        ja: '廊下',
        ko: '복도',
      },
    },
    caption: {
      tr: 'Kıpırdarsan sen de oynarsın.',
      en: "Move and you're in it.",
      de: 'Wer sich bewegt, tanzt mit.',
      ar: 'إن تحركت فسترقص معها.',
      fr: 'Si tu bouges, tu danses.',
      es: 'Si te mueves, bailas.',
      ja: '動いたら、あなたも出演決定。',
      ko: '움직이면 바로 출연 확정이에요.',
    },
    headline: {
      tr: 'Kardeşin dans videosu için eleman arıyor',
      en: 'Your sibling needs a dance-video partner',
      de: 'Deine Schwester sucht Tänzer fürs Video',
      ar: 'أختك تبحث عن شريك لفيديو رقص',
      fr: 'Ta sœur cherche un danseur pour sa vidéo',
      es: 'Tu hermana busca pareja para su video',
      ja: 'きょうだいがダンス動画の相方を探してる',
      ko: '동생이 댄스 영상 파트너를 찾아요',
    },
  },
];
