import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * The phone itself: apps, settings, cameras, updates, typing, autocorrect, social media habits.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const PHONE_SKIP: readonly Draft[] = [
  {
    emoji: '🔦',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Telefonumu aradım. Telefonun feneriyle.',
      en: "Looked for my phone. With my phone's flashlight.",
      de: 'Handy gesucht. Mit der Handy-Taschenlampe.',
      ar: 'بحثت عن هاتفي… مستعينًا بمصباح هاتفي',
      fr: "J'ai cherché mon tel. Avec la lampe du tel.",
      es: 'Busqué mi teléfono. Con la linterna del teléfono.',
    },
  },
  {
    emoji: '⌨️',
    user: ACCOUNTS.office,
    body: { format: 'scene' },
    caption: {
      tr: '“G” yazdım, klavye “geç kalıyorum” önerdi',
      en: 'One letter in, my keyboard suggests “running late”',
      de: '„K“ getippt. Vorschlag: „komme später“',
      ar: 'كتبت حرفًا واحدًا فاقترحت لوحة المفاتيح: «سأتأخر»',
      fr: "Une lettre, et le clavier propose « j'arrive en retard »",
      es: 'Escribo una letra y el teclado sugiere “llego tarde”',
    },
  },
  {
    emoji: '📳',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Cebim titredi sandım. Telefon elimdeydi.',
      en: 'Felt my pocket buzz. My phone was in my hand.',
      de: 'Tasche vibriert? Das Handy war in meiner Hand.',
      ar: 'شعرت بجيبي يهتز… والهاتف في يدي',
      fr: 'Ma poche a vibré. Mon tel était dans ma main.',
      es: 'Me vibró el bolsillo. El teléfono estaba en mi mano.',
    },
  },
  {
    emoji: '🌚',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Hile: karanlık modu aç, anında gizemli ol',
      en: 'Hack: dark mode = instant air of mystery',
      de: 'Lifehack: Dunkelmodus an, sofort geheimnisvoll',
      ar: 'حيلة: فعّل الوضع الداكن وستصبح غامضًا فورًا',
      fr: 'Astuce : mode sombre = mystère instantané',
      es: 'Truco: activa el modo oscuro y sé un misterio',
    },
  },
  {
    emoji: '🪞',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Ayna selfiesi: en net çıkan şey telefon',
      en: 'Mirror selfie: the sharpest thing in it is my phone',
      de: 'Spiegelselfie: Nur das Handy ist richtig im Fokus',
      ar: 'سيلفي في المرآة: أوضح شيء فيها هو الهاتف',
      fr: "Selfie miroir : le plus net, c'est le téléphone",
      es: 'Selfie en el espejo: lo más nítido es el teléfono',
    },
  },
  {
    emoji: '🔍',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Ekran koruyucu: 9 kabarcık. Hepsine isim verdim.',
      en: 'Screen protector: 9 bubbles. I named them all.',
      de: 'Schutzfolie: 9 Blasen. Alle haben einen Namen.',
      ar: 'واقي الشاشة: 9 فقاعات، ولكل واحدة اسم',
      fr: "Protection d'écran : 9 bulles. Elles ont toutes un prénom.",
      es: 'Protector de pantalla: 9 burbujas. Todas tienen nombre.',
    },
  },
  {
    emoji: '🤦',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'keçi aldım, geliyorum',
            en: 'got the snakes, omw',
            de: 'hab Küken dabei, bin gleich da',
            ar: 'أحضرت الديك، أنا قادم',
            fr: "j'ai le bateau, j'arrive",
            es: 'ya tengo el pastor, voy para allá',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'KEÇİ Mİ??',
            en: 'SNAKES??',
            de: 'KÜKEN??',
            ar: 'الديك؟؟',
            fr: 'LE BATEAU ??',
            es: '¿¿EL PASTOR??',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'KEKİ. otomatik düzeltme 😩',
            en: 'SNACKS. autocorrect 😩',
            de: 'KUCHEN. Autokorrektur 😩',
            ar: 'الكيك! التصحيح التلقائي 😩',
            fr: 'LE GÂTEAU. correcteur 😩',
            es: 'PASTEL. autocorrector 😩',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'keçi daha eğlenceliydi ama',
            en: 'ngl snakes sounded more fun',
            de: 'Küken wär süßer gewesen',
            ar: 'الديك كان أطرف بصراحة',
            fr: "le bateau, c'était plus drôle",
            es: 'el pastor sonaba más divertido',
          },
        },
      ],
    },
    caption: {
      tr: 'Otomatik düzeltme yine iş başında',
      en: 'Autocorrect is at it again',
      de: 'Die Autokorrektur schon wieder',
      ar: 'التصحيح التلقائي يفعلها مجددًا',
      fr: 'Le correcteur a encore fait des siennes',
      es: 'El autocorrector otra vez haciendo de las suyas',
    },
  },
  {
    emoji: '🙊',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'annem yine “kaçta geliyorsun” diye yazdı 🙄',
            en: "mom asked when I'm coming home AGAIN 🙄",
            de: 'Mama fragt schon wieder, wann ich komme 🙄',
            ar: 'أمي تسأل مجددًا متى سأعود 🙄',
            fr: 'maman demande ENCORE quand je rentre 🙄',
            es: 'mamá pregunta OTRA VEZ cuándo vuelvo 🙄',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Evet. Kaçta geliyorsun?',
            en: 'Yes. When ARE you coming home?',
            de: 'Ja. Wann kommst du?',
            ar: 'نعم. متى ستعود؟',
            fr: 'Oui. Tu rentres quand ?',
            es: 'Sí. ¿Cuándo vuelves?',
          },
        },
      ],
    },
    caption: {
      tr: 'Yanlış sohbet. En yanlış sohbet.',
      en: 'Wrong chat. The wrongest chat.',
      de: 'Falscher Chat. Der falscheste überhaupt.',
      ar: 'محادثة خاطئة… وأيّ محادثة!',
      fr: 'Mauvaise conversation. La pire de toutes.',
      es: 'Chat equivocado. El más equivocado de todos.',
    },
  },
  {
    emoji: '🥲',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Anneannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'reçeli yaktım 😂😂',
            en: 'I burned the jam 😂😂',
            de: 'die Marmelade ist angebrannt 😂😂',
            ar: 'احترق المربى 😂😂',
            fr: "j'ai fait brûler la confiture 😂😂",
            es: 'se me quemó la mermelada 😂😂',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'neden gülüyorsun anneanne?',
            en: 'why are you laughing, Grandma?',
            de: 'warum lachst du, Oma?',
            ar: 'لماذا تضحكين يا جدتي؟',
            fr: 'pourquoi tu ris, Mamie ?',
            es: '¿por qué te ríes, abuela?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ağlıyorum yavrum 😂😂😂',
            en: "I'm crying, sweetie 😂😂😂",
            de: 'ich weine doch, Schatz 😂😂😂',
            ar: 'أنا أبكي يا حبيبي 😂😂😂',
            fr: 'mais je pleure, mon chéri 😂😂😂',
            es: 'estoy llorando, mi amor 😂😂😂',
          },
        },
      ],
    },
    caption: {
      tr: 'Anneannemin sözlüğünde 😂 ağlamak demek',
      en: "In Grandma's dictionary, 😂 means crying",
      de: 'In Omas Wörterbuch heißt 😂 weinen',
      ar: 'في قاموس جدتي، 😂 تعني البكاء',
      fr: 'Dans le dico de Mamie, 😂 veut dire pleurer',
      es: 'En el diccionario de la abuela, 😂 es llorar',
    },
  },
  {
    emoji: '👖',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Eski komşu',
        en: 'Old neighbor',
        de: 'Alte Nachbarin',
        ar: 'الجارة القديمة',
        fr: 'Ancienne voisine',
        es: 'Vecina de antes',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'beni aradın mı?',
            en: 'did you just call me?',
            de: 'hast du mich angerufen?',
            ar: 'هل اتصلت بي؟',
            fr: "tu m'as appelée ?",
            es: '¿me llamaste?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yok, cebimden aramışım 🙈',
            en: 'oops, pocket call 🙈',
            de: 'oh nein, das war die Hosentasche 🙈',
            ar: 'آسف، اتصل جيبي وحده 🙈',
            fr: 'oups, appel de poche 🙈',
            es: 'uy, fue el bolsillo 🙈',
          },
        },
        {
          from: 'them',
          text: {
            tr: '10 dakika yürüyüşünü dinledim',
            en: 'I listened to your walk for 10 min',
            de: 'hab 10 Minuten deinen Schritten gelauscht',
            ar: 'استمعت إلى خطواتك 10 دقائق',
            fr: "j'ai écouté ta balade pendant 10 min",
            es: 'escuché tu caminata 10 minutos',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'cebin senden daha sık arıyor bu arada',
            en: 'your pocket calls more than you do btw',
            de: 'deine Tasche ruft öfter an als du',
            ar: 'جيبك يتصل بي أكثر منك بالمناسبة',
            fr: 'ta poche appelle plus souvent que toi',
            es: 'tu bolsillo llama más que tú, eh',
          },
        },
      ],
    },
    caption: {
      tr: 'Cebim benden daha sosyal',
      en: 'My pocket has a better social life',
      de: 'Meine Hosentasche ist geselliger als ich',
      ar: 'جيبي اجتماعي أكثر مني',
      fr: 'Ma poche est plus sociable que moi',
      es: 'Mi bolsillo es más sociable que yo',
    },
  },
  {
    emoji: '😰',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Telefon yüzüstü düştü. Sen:',
        en: 'Your phone lands face down. You:',
        de: 'Dein Handy fällt aufs Display. Du:',
        ar: 'سقط هاتفك على وجهه. ماذا تفعل؟',
        fr: 'Ton tel tombe côté écran. Tu fais quoi ?',
        es: 'Tu teléfono cae boca abajo. Tú:',
      },
      options: [
        {
          tr: 'Hemen çeviririm',
          en: 'Flip it right away',
          de: 'Sofort umdrehen',
          ar: 'أقلبه فورًا',
          fr: 'Je le retourne direct',
          es: 'Le doy la vuelta ya',
        },
        {
          tr: 'Gözüm kapalı çeviririm',
          en: 'Flip it with eyes shut',
          de: 'Augen zu und umdrehen',
          ar: 'أغمض عينيّ ثم أقلبه',
          fr: 'Les yeux fermés',
          es: 'Con los ojos cerrados',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Bakmadıkça kırık sayılmaz',
      en: "If I don't look, it's not cracked",
      de: 'Solange ich nicht hinschaue, ist es heil',
      ar: 'ما دمت لا أنظر، فهو ليس مكسورًا',
      fr: "Tant que je regarde pas, c'est pas cassé",
      es: 'Si no lo miro, no está roto',
    },
  },
  {
    emoji: '😱',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Ön kamera yanlışlıkla açıldı. Sen:',
        en: 'The front camera opens by accident. You:',
        de: 'Die Frontkamera geht aus Versehen an. Du:',
        ar: 'انفتحت الكاميرا الأمامية فجأة. ماذا تفعل؟',
        fr: 'Caméra selfie ouverte par erreur. Tu fais quoi ?',
        es: 'Se abre la cámara frontal sin querer. Tú:',
      },
      options: [
        {
          tr: 'Sakince kapatırım',
          en: 'Calmly close it',
          de: 'Ruhig schließen',
          ar: 'أغلقها بهدوء',
          fr: 'Je ferme calmement',
          es: 'La cierro con calma',
        },
        { tr: 'Çığlık atarım', en: 'Scream', de: 'Schreien', ar: 'أصرخ', fr: 'Je hurle', es: 'Grito' },
      ],
      winner: 1,
    },
    caption: {
      tr: 'İkimiz de çığlık attık: ben ve ben',
      en: 'Both of us screamed. Me and me.',
      de: 'Wir haben beide geschrien. Ich und ich.',
      ar: 'صرخنا كلانا: أنا وأنا',
      fr: 'On a crié tous les deux. Moi et moi.',
      es: 'Gritamos los dos: yo y yo.',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sessiz bir ortamda telefonun çaldı. Sen:',
        en: 'Your phone rings in a silent room. You:',
        de: 'Dein Handy klingelt in der Stille. Du:',
        ar: 'رنّ هاتفك في مكان هادئ تمامًا. ماذا تفعل؟',
        fr: 'Ton tel sonne en plein silence. Et là ?',
        es: 'Tu teléfono suena en pleno silencio. Tú:',
      },
      options: [
        {
          tr: 'Hemen kapatırım',
          en: 'Silence it fast',
          de: 'Sofort wegdrücken',
          ar: 'أُسكته فورًا',
          fr: 'Je coupe vite',
          es: 'Lo silencio rápido',
        },
        {
          tr: 'Etrafa kızgın bakarım',
          en: 'Glare at everyone else',
          de: 'Andere böse anschauen',
          ar: 'أنظر إلى الآخرين بغضب',
          fr: 'Je toise les autres',
          es: 'Miro mal a los demás',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kimin telefonu bu, çok ayıp',
      en: 'Wow, whose phone is that? So rude.',
      de: 'Wessen Handy ist das? Unmöglich.',
      ar: 'هاتف مَن هذا؟ يا للإزعاج!',
      fr: "C'est le tel de qui ? Quelle honte.",
      es: '¿De quién es ese teléfono? Qué falta de respeto.',
    },
  },
  {
    emoji: '📢',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sesli asistan seni anlamadı. Sen:',
        en: "The voice assistant didn't get it. You:",
        de: 'Der Sprachassistent versteht dich nicht. Du:',
        ar: 'المساعد الصوتي لم يفهمك. ماذا تفعل؟',
        fr: "L'assistant vocal n'a pas compris. Et là ?",
        es: 'El asistente de voz no te entendió. Tú:',
      },
      options: [
        {
          tr: 'Tekrar söylerim',
          en: 'Say it again',
          de: 'Noch mal sagen',
          ar: 'أعيد الجملة',
          fr: 'Je répète',
          es: 'Lo repito',
        },
        {
          tr: 'Aynısını bağırırım',
          en: 'Say it again, LOUDER',
          de: 'Dasselbe, nur LAUTER',
          ar: 'أعيدها بصوت أعلى',
          fr: 'Pareil, mais plus FORT',
          es: 'Lo mismo, MÁS FUERTE',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Sonra hecelerim. Sonra kendim yaparım.',
      en: 'Then I spell it out. Then I do it myself.',
      de: 'Dann buchstabiere ich. Dann mach ich es selbst.',
      ar: 'ثم أتهجّاها. ثم أفعلها بنفسي.',
      fr: "Puis j'épelle. Puis je le fais moi-même.",
      es: 'Luego lo deletreo. Luego lo hago yo.',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: '“YAZIYOR…”',
        en: '“TYPING…”',
        de: '„SCHREIBT…“',
        ar: '«يكتب…»',
        fr: "« EN TRAIN D'ÉCRIRE… »",
        es: '“ESCRIBIENDO…”',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Yazdı, sildi, yazdı… çevrimdışı oldu.',
      en: 'Typing, stopped, typing… went offline.',
      de: 'Schreibt, stoppt, schreibt… offline.',
      ar: 'يكتب، يتوقف، يكتب… ثم يختفي.',
      fr: 'Écrit, arrête, écrit… hors ligne.',
      es: 'Escribe, para, escribe… se desconectó.',
    },
  },
  {
    emoji: '🔉',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'TELEFONUMUN SESİ',
        en: 'MY PHONE VOLUME',
        de: 'LAUTSTÄRKE MEINES HANDYS',
        ar: 'مستوى صوت هاتفي',
        fr: 'VOLUME DE MON TEL',
        es: 'VOLUMEN DE MI TELÉFONO',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Ya son ses ya sessiz, arası yok',
      en: "It's either full blast or silent. Nothing in between.",
      de: 'Entweder voll aufgedreht oder lautlos',
      ar: 'إما بأعلى صوت أو صامت، ولا وسط بينهما',
      fr: 'Soit à fond, soit en silencieux. Pas de milieu.',
      es: 'O a todo volumen o en silencio. Sin término medio.',
    },
  },
  {
    emoji: '🔆',
    user: ACCOUNTS.sleep,
    body: {
      format: 'chart',
      title: {
        tr: 'EKRAN PARLAKLIĞI',
        en: 'SCREEN BRIGHTNESS',
        de: 'BILDSCHIRMHELLIGKEIT',
        ar: 'سطوع الشاشة',
        fr: "LUMINOSITÉ DE L'ÉCRAN",
        es: 'BRILLO DE PANTALLA',
      },
      value: {
        tr: '%100',
        en: '100%',
        de: '100 %',
        ar: '100%',
        fr: '100 %',
        es: '100 %',
      },
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Karanlıkta telefonu açtım, güneş doğdu',
      en: 'Unlocked my phone in the dark. Sunrise.',
      de: 'Handy im Dunkeln entsperrt. Sonnenaufgang.',
      ar: 'فتحت هاتفي في الظلام… فأشرقت الشمس',
      fr: 'Tel allumé dans le noir. Lever de soleil.',
      es: 'Abrí el teléfono a oscuras. Amaneció.',
    },
  },
  {
    emoji: '🔧',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'TELEFON TAMİRCİSİ',
        en: 'PHONE REPAIR SHOP',
        de: 'HANDYREPARATUR',
        ar: 'محل تصليح الهواتف',
        fr: 'RÉPARATION MOBILES',
        es: 'SERVICIO TÉCNICO',
      },
      items: [
        {
          tr: 'EKRAN DEĞİŞİMİ',
          en: 'SCREEN REPLACEMENT',
          de: 'DISPLAYTAUSCH',
          ar: 'تغيير الشاشة',
          fr: "CHANGEMENT D'ÉCRAN",
          es: 'CAMBIO DE PANTALLA',
        },
        {
          tr: 'KILIF (BU SEFER)',
          en: 'PHONE CASE (THIS TIME)',
          de: 'HÜLLE (DIESMAL)',
          ar: 'غطاء (هذه المرة)',
          fr: 'COQUE (CETTE FOIS)',
          es: 'FUNDA (ESTA VEZ)',
        },
      ],
    },
    caption: {
      tr: 'Ders aldım. Ekran parasıyla.',
      en: 'Lesson learned. It cost me a screen.',
      de: 'Lektion gelernt. Hat ein Display gekostet.',
      ar: 'تعلّمت الدرس… وكلّفني شاشة',
      fr: "Leçon apprise. Ça m'a coûté un écran.",
      es: 'Lección aprendida. Me costó una pantalla.',
    },
  },
  {
    emoji: '💡',
    user: ACCOUNTS.vlog,
    body: {
      format: 'receipt',
      store: {
        tr: 'AYDINLATMA',
        en: 'LIGHTING STORE',
        de: 'LAMPENLADEN',
        ar: 'محل الإنارة',
        fr: 'LUMINAIRES',
        es: 'ILUMINACIÓN',
      },
      items: [
        {
          tr: 'HALKA IŞIK',
          en: 'RING LIGHT',
          de: 'RINGLICHT',
          ar: 'إضاءة حلقية',
          fr: 'ANNEAU LUMINEUX',
          es: 'ARO DE LUZ',
        },
      ],
    },
    caption: {
      tr: 'Artık dağınık odam da çok net çıkıyor',
      en: 'Now my messy room looks crystal clear too',
      de: 'Jetzt sieht man mein Chaos in bester Qualität',
      ar: 'الآن تظهر فوضى غرفتي بوضوح تام',
      fr: 'Maintenant, mon bazar est super net aussi',
      es: 'Ahora mi habitación desordenada se ve nítida',
    },
  },
  {
    emoji: '🏷️',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'kez kendi adını yazdın; otomatik düzeltme üçünü de değiştirdi',
        en: 'times you typed your own name. Autocorrect “fixed” all 3.',
        de: 'Mal den eigenen Namen getippt. Dreimal „korrigiert“.',
        ar: 'مرات كتبت اسمك… فغيّره التصحيح التلقائي في كل مرة',
        fr: 'fois où tu as tapé ton prénom. « Corrigé » les 3 fois.',
        es: 'veces escribiste tu nombre. El corrector lo “arregló” las 3.',
      },
    },
    caption: {
      tr: 'Artık adından bile emin değilsin',
      en: "Now you're not even sure of your name",
      de: 'Jetzt zweifelst du an deinem Namen',
      ar: 'صرت تشك في اسمك',
      fr: 'Tu doutes même de ton prénom',
      es: 'Ya dudas hasta de tu nombre',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.food,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '5', en: '5', de: '5', ar: '5', fr: '5', es: '5' },
      text: {
        tr: 'kez QR kodun fotoğrafını çektin; menü bir türlü açılmadı',
        en: 'times you took a photo of the QR code. The menu never opened.',
        de: 'Mal den QR-Code fotografiert. Das Menü ging nie auf.',
        ar: 'مرات التقطت صورة لرمز QR… ولم تُفتح القائمة أبدًا',
        fr: 'fois où tu as pris le QR code en photo. Menu toujours fermé.',
        es: 'veces le tomaste una foto al código QR. El menú nunca abrió.',
      },
    },
    caption: {
      tr: 'Sonunda kâğıt menü getirdiler',
      en: 'They brought you a paper menu in the end',
      de: 'Am Ende kam doch die Papierkarte',
      ar: 'في النهاية أحضروا لك قائمة ورقية',
      fr: "Au final, on t'a apporté un menu papier",
      es: 'Al final te trajeron el menú de papel',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: { tr: 'BUGÜN', en: 'TODAY', de: 'HEUTE', ar: 'اليوم', fr: "AUJOURD'HUI", es: 'HOY' },
      big: { tr: '1', en: '1', de: '1', ar: '1', fr: '1', es: '1' },
      text: {
        tr: 'bilinmeyen numara aradı; kim olduğunu 2 saat düşündün',
        en: 'unknown number called. You spent 2 hours guessing who.',
        de: 'unbekannte Nummer rief an. 2 Stunden lang gerätselt, wer.',
        ar: 'رقم مجهول اتصل بك… وقضيت ساعتين تخمّن من يكون',
        fr: "numéro inconnu a appelé. Tu as cherché qui c'était pendant 2 h.",
        es: 'número desconocido te llamó. Pasaste 2 horas adivinando quién.',
      },
    },
    caption: {
      tr: 'Kargocuymuş',
      en: 'It was the delivery guy',
      de: 'Es war der Paketbote',
      ar: 'كان عامل التوصيل',
      fr: "C'était le livreur",
      es: 'Era el repartidor',
    },
  },
  {
    emoji: '🎵',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ZİL SESİ TIER LIST',
        en: 'RINGTONE TIER LIST',
        de: 'KLINGELTON-RANKING',
        ar: 'تصنيف نغمات الرنين',
        fr: 'TIER LIST DES SONNERIES',
        es: 'TIER LIST DE TONOS',
      },
      rows: [['🔕'], ['🐦', '🎹'], ['🔔', '🎺'], ['☎️']],
    },
    caption: {
      tr: 'Klasik zil çalınca 30 kişi cebini yokluyor',
      en: 'Classic ring goes off, 30 people check their pockets',
      de: 'Klassischer Klingelton: 30 Leute greifen in die Tasche',
      ar: 'ترنّ النغمة الكلاسيكية فيتحسّس 30 شخصًا جيوبهم',
      fr: 'Sonnerie classique : 30 personnes fouillent leur poche',
      es: 'Suena el tono clásico y 30 personas revisan su bolsillo',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'TELEFONUMU BULDUĞUM YERLER',
        en: 'WHERE I FIND MY PHONE',
        de: 'WO ICH MEIN HANDY FINDE',
        ar: 'أين أجد هاتفي',
        fr: 'OÙ JE RETROUVE MON TEL',
        es: 'DÓNDE ENCUENTRO MI TELÉFONO',
      },
      rows: [['🛋️'], ['🛏️', '🧥'], ['🧺', '🚗'], ['🧊']],
    },
    caption: {
      tr: 'Buzdolabında buldum. Soğuk karşıladı.',
      en: 'Found it in the fridge. It gave me the cold shoulder.',
      de: 'Im Kühlschrank gefunden. Die Begrüßung war frostig.',
      ar: 'وجدته في الثلاجة… وكان استقباله باردًا',
      fr: "Retrouvé dans le frigo. L'accueil a été glacial.",
      es: 'Apareció en la nevera. Me recibió con frialdad.',
    },
  },
  {
    emoji: '🧭',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🆕',
        app: {
          tr: 'Güncelleme',
          en: 'Update',
          de: 'Update',
          ar: 'التحديث',
          fr: 'Mise à jour',
          es: 'Actualización',
        },
        text: {
          tr: 'Yeni: her şeyin yeri değişti!',
          en: "What's new: everything moved!",
          de: 'Neu: Alles ist jetzt woanders!',
          ar: 'الجديد: كل شيء تغيّر مكانه!',
          fr: 'Nouveau : tout a changé de place !',
          es: 'Novedad: ¡todo cambió de lugar!',
        },
      },
    },
    caption: {
      tr: 'Ayarlarda kayboldum, harita lazım',
      en: "I'm lost in Settings. Send a map.",
      de: 'Hab mich in den Einstellungen verlaufen',
      ar: 'ضعت في الإعدادات، أحتاج إلى خريطة',
      fr: 'Il me faut une carte pour les réglages',
      es: 'Me perdí en Ajustes. Necesito un mapa.',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⌨️',
        app: {
          tr: 'Klavye',
          en: 'Keyboard',
          de: 'Tastatur',
          ar: 'لوحة المفاتيح',
          fr: 'Clavier',
          es: 'Teclado',
        },
        text: {
          tr: 'Sözlüğe eklendi: “tmmmmm”',
          en: 'Added to dictionary: “okkkkk”',
          de: 'Neues Wort gelernt: „okeeee“',
          ar: 'أُضيفت إلى القاموس: «حسنًااا»',
          fr: 'Ajouté au dictionnaire : « okkkk »',
          es: 'Añadido al diccionario: “okiiii”',
        },
      },
    },
    caption: {
      tr: 'Klavyem artık benim gibi konuşuyor',
      en: 'My keyboard talks like me now',
      de: 'Meine Tastatur redet jetzt wie ich',
      ar: 'لوحة مفاتيحي صارت تتكلم مثلي',
      fr: 'Mon clavier parle comme moi maintenant',
      es: 'Mi teclado ya habla como yo',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '⚙️',
        app: {
          tr: 'Ayarlar',
          en: 'Settings',
          de: 'Einstellungen',
          ar: 'الإعدادات',
          fr: 'Réglages',
          es: 'Ajustes',
        },
        text: {
          tr: 'Uçak modu 6 saattir açık',
          en: 'Airplane mode on for 6 hours',
          de: 'Flugmodus seit 6 Stunden an',
          ar: 'وضع الطيران مفعّل منذ 6 ساعات',
          fr: 'Mode avion activé depuis 6 h',
          es: 'Modo avión activado hace 6 horas',
        },
      },
    },
    caption: {
      tr: 'Ben de kimse yazmıyor diye üzülüyordum',
      en: 'And I was sad nobody was texting me',
      de: 'Und ich dachte, keiner schreibt mir',
      ar: 'وأنا حزين لأن لا أحد يراسلني',
      fr: "Et moi qui croyais que personne m'écrivait",
      es: 'Y yo triste porque nadie me escribía',
    },
  },
  {
    emoji: '🙉',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🎙️',
        app: {
          tr: 'Sesli asistan',
          en: 'Voice assistant',
          de: 'Sprachassistent',
          ar: 'المساعد الصوتي',
          fr: 'Assistant vocal',
          es: 'Asistente de voz',
        },
        text: {
          tr: '“Anime” için sonuçlar gösteriliyor',
          en: 'Showing results for “Tex-Mex”',
          de: 'Rufe „Lama“ an…',
          ar: 'نتائج البحث عن «مانجو»',
          fr: 'Résultats pour « pelle à maman »',
          es: 'Buscando llamas cerca de ti…',
        },
      },
    },
    caption: {
      tr: '“Annemi ara” demiştim',
      en: 'I said “Text Mom.”',
      de: 'Ich sagte: „Ruf Mama an“',
      ar: 'قلتُ: «اتصل بماما»',
      fr: "J'avais dit « appelle maman »",
      es: 'Dije “llama a mamá”',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kendin ol. Gerisini filtreler hallediyor.',
        en: 'Be yourself. The filters have everyone else covered.',
        de: 'Sei du selbst. Für alles andere gibt es Filter.',
        ar: 'كن نفسك، فالفلاتر تتكفّل بالباقي.',
        fr: "Sois toi-même. Les filtres s'occupent du reste.",
        es: 'Sé tú mismo. Del resto se encargan los filtros.',
      },
    },
    caption: {
      tr: 'Bugünkü tercihim: köpek kulakları',
      en: 'Today I went with dog ears',
      de: 'Heute mit Hundeohren',
      ar: 'اليوم اخترت أذني الكلب',
      fr: "Aujourd'hui : oreilles de chien",
      es: 'Hoy elegí orejas de perro',
    },
  },
  {
    emoji: '🔕',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Sessizlik en güçlü cevaptır. — 3 yıldır sessizde olan telefonum',
        en: 'Silence speaks volumes. — My phone, on silent for 3 years',
        de: 'Schweigen ist auch eine Antwort. — Mein Handy, seit 3 Jahren lautlos',
        ar: 'الصمت أبلغ جواب. — هاتفي الصامت منذ 3 سنوات',
        fr: 'Le silence est une réponse. — Mon tel, en silencieux depuis 3 ans',
        es: 'El silencio lo dice todo. — Mi teléfono, en silencio hace 3 años',
      },
    },
    caption: {
      tr: 'Aradıysan kusura bakma',
      en: 'Sorry if you called',
      de: 'Falls du angerufen hast: sorry',
      ar: 'إن كنت اتصلت بي، فآسف',
      fr: "Si tu m'as appelé, désolé",
      es: 'Si me llamaste, perdón',
    },
  },
  {
    emoji: '🌄',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat panoramaya benzer: kıpırdarsan tuhaf çıkarsın.',
        en: 'Life is like a panorama: move and you come out weird.',
        de: 'Das Leben ist wie ein Panorama: Wer wackelt, sieht komisch aus.',
        ar: 'الحياة مثل الصورة البانورامية: إن تحركت ظهرت بشكل غريب.',
        fr: "La vie, c'est comme un panorama : si tu bouges, tu sors bizarre.",
        es: 'La vida es como una panorámica: si te mueves, sales raro.',
      },
    },
    caption: {
      tr: 'Geçen hafta 3 kollu çıktım',
      en: 'Last week I came out with 3 arms',
      de: 'Letzte Woche hatte ich 3 Arme',
      ar: 'الأسبوع الماضي ظهرت بثلاث أذرع',
      fr: "La semaine dernière, j'avais 3 bras",
      es: 'La semana pasada salí con 3 brazos',
    },
  },
  {
    emoji: '👥',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Zamanlama her şeydir. — Görüntülü aramada aynı anda konuşan iki kişi',
        en: 'Timing is everything. — Two people talking at once on a video call',
        de: 'Timing ist alles. — Zwei, die im Videocall gleichzeitig reden',
        ar: 'التوقيت هو كل شيء. — شخصان يتكلمان معًا في مكالمة فيديو',
        fr: "Le timing, c'est tout. — Deux qui parlent en même temps en visio",
        es: 'El momento justo lo es todo. — Dos hablando a la vez en videollamada',
      },
    },
    caption: {
      tr: '“Sen söyle.” “Yok, sen söyle.”',
      en: '“You go.” “No, you go.”',
      de: '„Du zuerst.“ „Nein, du.“',
      ar: '«تكلّم أنت». «لا، أنت أولًا».',
      fr: '« Vas-y. » « Non, vas-y toi. »',
      es: '“Tú primero.” “No, tú.”',
    },
  },
];

export const PHONE_LIKE: readonly Draft[] = [
  {
    emoji: '📵',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: '1 saat telefona bakmadım!! (öbür odada kalmış)',
      en: 'a whole hour phone-free!! (left it in the other room)',
      de: 'eine stunde ohne handy!! (lag im anderen zimmer)',
      ar: 'ساعة كاملة بلا هاتف!! (نسيته في الغرفة الأخرى)',
      fr: "une heure sans téléphone !! (oublié dans l'autre pièce)",
      es: '¡¡una hora sin teléfono!! (lo dejé en otra habitación)',
    },
  },
  {
    emoji: '👵',
    user: ACCOUNTS.arda,
    body: { format: 'scene' },
    caption: {
      tr: 'anneanneme görüntülü aramayı öğrettim, her gün arıyor',
      en: 'taught grandma video calls, now she calls every day',
      de: 'hab oma videoanrufe beigebracht, jetzt ruft sie täglich an',
      ar: 'علّمت جدتي مكالمات الفيديو، وصارت تتصل كل يوم',
      fr: "j'ai appris la visio à mamie, elle appelle tous les jours",
      es: 'le enseñé videollamadas a mi abuela, ahora llama a diario',
    },
  },
  {
    emoji: '🎹',
    user: ACCOUNTS.can,
    body: { format: 'scene' },
    caption: {
      tr: 'zil sesimi kendim besteledim: 4 nota ama benim',
      en: 'composed my own ringtone: 4 notes, all mine',
      de: 'klingelton selbst komponiert: 4 töne, aber meine',
      ar: 'لحّنت نغمة رنيني بنفسي: 4 نغمات لكنها لي',
      fr: "j'ai composé ma sonnerie : 4 notes, mais à moi",
      es: 'compuse mi propio tono: 4 notas, pero mías',
    },
  },
  {
    emoji: '😊',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: '#filtresiz',
        en: '#nofilter',
        de: '#ohnefilter',
        ar: '#بلا_فلتر',
        fr: '#sansfiltre',
        es: '#sinfiltro',
      },
    },
    caption: {
      tr: 'ilk kez filtresiz paylaşıyorum, alkış lütfen',
      en: 'first post with no filter, applause please',
      de: 'zum ersten mal ohne filter gepostet, applaus bitte',
      ar: 'أول مرة أنشر صورة بلا فلتر، صفّقوا لي',
      fr: 'première photo sans filtre, applaudissez',
      es: 'primera foto sin filtro, aplausos por favor',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'hepsi aynı kedi',
        en: 'all the same cat',
        de: 'alles dieselbe katze',
        ar: 'كلها القطة نفسها',
        fr: 'toujours le même chat',
        es: 'es el mismo gato',
      },
    },
    caption: {
      tr: 'panorama çektim, kedim 3 kere kadraja girdi',
      en: 'took a panorama, my cat made it in 3 times',
      de: 'panorama gemacht, meine katze ist 3-mal drauf',
      ar: 'التقطت صورة بانورامية فظهرت قطتي 3 مرات',
      fr: 'photo panoramique : mon chat y est 3 fois',
      es: 'hice una panorámica y mi gato salió 3 veces',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.tolga,
    body: {
      format: 'polaroid',
      note: {
        tr: 'emekli etmiyorum',
        en: 'not retiring it',
        de: 'wird nicht ausgemustert',
        ar: 'لن أستبدله',
        fr: 'pas question de le changer',
        es: 'no pienso jubilarlo',
      },
    },
    caption: {
      tr: 'en sadık dostum: 7 yıllık telefonum',
      en: 'my most loyal friend: my 7-year-old phone',
      de: 'mein treuester begleiter: 7 jahre altes handy',
      ar: 'أوفى أصدقائي: هاتفي ذو السبع سنوات',
      fr: 'mon plus fidèle ami : mon tel de 7 ans',
      es: 'mi amigo más fiel: mi teléfono de 7 años',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'el yapımı',
        en: 'handmade',
        de: 'handgemacht',
        ar: 'صنع يدوي',
        fr: 'fait main',
        es: 'hecho a mano',
      },
    },
    caption: {
      tr: 'telefon kılıfımı kendim boyadım, azıcık taştı',
      en: 'painted my own phone case, went outside the lines a bit',
      de: 'handyhülle selbst bemalt, bisschen über den rand',
      ar: 'لوّنت غطاء هاتفي بنفسي… وخرجت عن الخطوط قليلًا',
      fr: "j'ai peint ma coque moi-même, ça déborde un peu",
      es: 'pinté mi propia funda, me salí un poquito',
    },
  },
  {
    emoji: '📦',
    user: ACCOUNTS.cemre,
    body: { format: 'dump', emojis: ['📦', '📲', '✨', '🎉', '🙌'] },
    caption: {
      tr: 'yeni telefon dump’ı: kutusunu atamam tabii',
      en: 'new phone dump: obviously keeping the box',
      de: 'neues-handy-dump: den karton behalte ich natürlich',
      ar: 'هاتف جديد! والعلبة سأحتفظ بها طبعًا',
      fr: 'nouveau tel : je garde la boîte, évidemment',
      es: 'teléfono nuevo: la caja me la quedo, obvio',
    },
  },
  {
    emoji: '😆',
    user: ACCOUNTS.onur,
    body: { format: 'dump', emojis: ['😆', '😮', '🤪', '😝', '🙃'] },
    caption: {
      tr: 'görüntülü arama dump’ı: en güzel donduğumuz anlar',
      en: 'video call dump: our best frozen frames',
      de: 'videocall-dump: unsere schönsten standbilder',
      ar: 'مكالمة الفيديو: أجمل لحظات تجمّدنا',
      fr: 'dump de visio : nos plus beaux arrêts sur image',
      es: 'resumen de videollamada: nuestras mejores caras congeladas',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🐈', '🌅', '🍝', '👖', '🌸'] },
    caption: {
      tr: 'galeri dump’ı: kedi, gün batımı ve cebimin içi',
      en: 'camera roll dump: cat, sunset, inside of my pocket',
      de: 'galerie-dump: katze, sonnenuntergang, hosentasche von innen',
      ar: 'من معرض صوري: قطة، غروب، وداخل جيبي',
      fr: 'ma galerie : chat, coucher de soleil, fond de poche',
      es: 'mi galería: gato, atardecer y el interior de mi bolsillo',
    },
  },
];

export const PHONE_HOLD: readonly Draft[] = [
  {
    emoji: '🖼️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Galerideki o fotoğrafı 2 saniyede buldun!',
      en: 'Found that one photo in your camera roll in 2 seconds!',
      de: 'Das gesuchte Foto in 2 Sekunden in der Galerie gefunden!',
      ar: 'وجدت تلك الصورة في المعرض خلال ثانيتين!',
      fr: 'Retrouvé LA photo de ta galerie en 2 secondes !',
      es: '¡Encontraste esa foto de tu galería en 2 segundos!',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir bulunur: 10 saniyelik sesli mesaj',
      en: 'Rare find: a 10-second voice message',
      de: 'Seltener Fund: eine 10-Sekunden-Sprachnachricht',
      ar: 'اكتشاف نادر: رسالة صوتية مدتها 10 ثوانٍ',
      fr: 'Trouvaille rare : un vocal de 10 secondes',
      es: 'Hallazgo raro: un audio de 10 segundos',
    },
  },
  {
    emoji: '🍀',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yanlış gruba attın, kimse görmeden sildin!',
      en: 'Wrong group chat, deleted before anyone saw!',
      de: 'Falsche Gruppe, gelöscht, bevor es jemand sah!',
      ar: 'أرسلتها إلى المجموعة الخطأ وحذفتها قبل أن يراها أحد!',
      fr: "Mauvais groupe, supprimé avant que quelqu'un le voie !",
      es: '¡Grupo equivocado, y lo borraste antes de que lo vieran!',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Telefon yüzüstü düştü… ekran tek parça!',
      en: 'Phone landed face down… screen in one piece!',
      de: 'Handy aufs Display gefallen… alles heil!',
      ar: 'سقط الهاتف على وجهه… والشاشة سليمة!',
      fr: 'Tel tombé côté écran… et intact !',
      es: 'El teléfono cayó boca abajo… ¡y la pantalla intacta!',
    },
  },
  {
    emoji: '🎙️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sesli asistan ilk seferde anladı. Nadir kayıt.',
      en: 'The voice assistant got it on the first try. Rare footage.',
      de: 'Der Sprachassistent hat es sofort verstanden. Rarität.',
      ar: 'المساعد الصوتي فهمك من أول مرة. تسجيل نادر.',
      fr: "L'assistant vocal a compris du premier coup. Image rare.",
      es: 'El asistente de voz entendió a la primera. Imágenes únicas.',
    },
  },
  {
    emoji: '🧠',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Telefonu açtın ve nedenini hatırladın. Efsane!',
      en: 'You unlocked your phone and remembered why. Legendary!',
      de: 'Handy entsperrt und noch gewusst, wieso. Legendär!',
      ar: 'فتحت هاتفك وتذكرت السبب. أسطوري!',
      fr: 'Tel déverrouillé, et tu sais encore pourquoi. Légendaire !',
      es: 'Abriste el teléfono y recordaste para qué. ¡Legendario!',
    },
  },
  {
    emoji: '✅',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yazım hatasını son saniyede yakaladın. Şimdi gönder!',
      en: 'Caught the typo at the last second. Now hit send!',
      de: 'Tippfehler in letzter Sekunde entdeckt. Jetzt senden!',
      ar: 'اكتشفت الخطأ الإملائي في آخر ثانية. أرسل الآن!',
      fr: 'Faute repérée à la dernière seconde. Envoie maintenant !',
      es: 'Detectaste el error justo a tiempo. ¡Ahora envía!',
    },
  },
  {
    emoji: '✨',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tek parmak izi yok: pırıl pırıl bir ekran',
      en: 'Not a single fingerprint: a spotless screen',
      de: 'Kein einziger Fingerabdruck: ein blitzblankes Display',
      ar: 'ولا بصمة إصبع واحدة: شاشة لامعة تمامًا',
      fr: 'Pas une seule trace de doigt : un écran impeccable',
      es: 'Ni una huella: una pantalla impecable',
    },
  },
];

export const PHONE_FREEZE: readonly Draft[] = [
  {
    emoji: '📷',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'PORTRE MODU',
        en: 'PORTRAIT MODE',
        de: 'PORTRÄTMODUS',
        ar: 'وضع البورتريه',
        fr: 'MODE PORTRAIT',
        es: 'MODO RETRATO',
      },
      small: {
        tr: 'ARKA PLAN BULANIKLAŞIYOR',
        en: 'BACKGROUND BLURRING',
        de: 'HINTERGRUND WIRD UNSCHARF',
        ar: 'جارٍ تمويه الخلفية',
        fr: 'ARRIÈRE-PLAN FLOUTÉ',
        es: 'DESENFOCANDO EL FONDO',
      },
    },
    caption: {
      tr: 'Kıpırdarsan sen de bulanıklaşırsın.',
      en: "Move and you'll blur too.",
      de: 'Wer wackelt, wird auch unscharf.',
      ar: 'إن تحركت صرت ضبابيًا أنت أيضًا.',
      fr: 'Si tu bouges, toi aussi tu passes dans le flou.',
      es: 'Si te mueves, también te desenfoca.',
    },
    headline: {
      tr: 'Portre modu sonunda seni netledi',
      en: 'Portrait mode finally got you sharp',
      de: 'Porträtmodus: Endlich bist du im Fokus',
      ar: 'وضع البورتريه أظهرك بوضوح أخيرًا',
      fr: 'Enfin la mise au point sur toi',
      es: 'El modo retrato por fin te enfocó',
    },
  },
  {
    emoji: '🕸️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'KIRIK EKRAN',
        en: 'CRACKED SCREEN',
        de: 'DISPLAY KAPUTT',
        ar: 'شاشة مكسورة',
        fr: 'ÉCRAN FISSURÉ',
        es: 'PANTALLA ROTA',
      },
      small: {
        tr: 'ÇATLAK İLERLEYEBİLİR',
        en: 'CRACK MAY SPREAD',
        de: 'RISS KANN SICH AUSBREITEN',
        ar: 'قد يمتدّ الشق',
        fr: "LA FISSURE PEUT S'ÉTENDRE",
        es: 'LA GRIETA PUEDE CRECER',
      },
    },
    caption: {
      tr: 'Hiç dokunma, yayılır.',
      en: "Don't even breathe on it.",
      de: 'Nicht mal anhauchen.',
      ar: 'لا تلمسها أبدًا، فالشقّ ينتشر.',
      fr: 'Souffle même pas dessus.',
      es: 'Ni le respires encima.',
    },
    headline: {
      tr: 'Ekrandaki çatlak büyümek üzere',
      en: 'The crack is about to spread',
      de: 'Der Riss wird gleich länger',
      ar: 'الشقّ على وشك أن يكبر',
      fr: "La fissure est sur le point de s'étendre",
      es: 'La grieta está a punto de crecer',
    },
  },
  {
    emoji: '🔳',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'QR OKUNUYOR',
        en: 'SCANNING QR',
        de: 'QR-SCAN',
        ar: 'جارٍ مسح الرمز',
        fr: 'SCAN QR',
        es: 'ESCANEANDO QR',
      },
      small: {
        tr: 'KAMERAYI SABİT TUTUN',
        en: 'HOLD YOUR CAMERA STEADY',
        de: 'KAMERA RUHIG HALTEN',
        ar: 'ثبّت الكاميرا',
        fr: "NE BOUGEZ PAS L'APPAREIL",
        es: 'MANTENGA LA CÁMARA QUIETA',
      },
    },
    caption: {
      tr: 'Kıpırdarsan baştan okutursun.',
      en: 'Move and you start over.',
      de: 'Wackeln heißt: von vorn.',
      ar: 'إن تحركت ستبدأ من جديد.',
      fr: 'Si tu bouges, tu recommences.',
      es: 'Si te mueves, empiezas de nuevo.',
    },
    headline: {
      tr: 'Menü açılmak üzere, elin titremesin',
      en: "The menu's about to open. Steady hands.",
      de: 'Das Menü lädt gleich. Hände ruhig!',
      ar: 'قائمة الطعام على وشك أن تُفتح، لا ترتجف',
      fr: "Le menu va s'ouvrir. Tremble pas.",
      es: 'El menú está por abrirse. Pulso firme.',
    },
  },
  {
    emoji: '🌃',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'GECE MODU',
        en: 'NIGHT MODE',
        de: 'NACHTMODUS',
        ar: 'الوضع الليلي',
        fr: 'MODE NUIT',
        es: 'MODO NOCHE',
      },
      small: {
        tr: 'POZLAMA: 8 SANİYE',
        en: 'EXPOSURE: 8 SECONDS',
        de: 'BELICHTUNG: 8 SEKUNDEN',
        ar: 'مدة التعريض: 8 ثوانٍ',
        fr: 'POSE : 8 SECONDES',
        es: 'EXPOSICIÓN: 8 SEGUNDOS',
      },
    },
    caption: {
      tr: 'Sekiz saniye mobilya ol.',
      en: 'Be furniture for 8 seconds.',
      de: 'Sei 8 Sekunden lang ein Möbelstück.',
      ar: 'كن قطعة أثاث لثماني ثوانٍ.',
      fr: 'Sois un meuble pendant 8 secondes.',
      es: 'Sé un mueble durante 8 segundos.',
    },
    headline: {
      tr: 'Gece fotoğrafı çekiliyor',
      en: 'Night photo in progress',
      de: 'Nachtfoto wird aufgenommen',
      ar: 'جارٍ التقاط صورة ليلية',
      fr: 'Photo de nuit en cours',
      es: 'Foto nocturna en proceso',
    },
  },
  {
    emoji: '📳',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'WARNING',
        de: 'VORSICHT',
        ar: 'تحذير',
        fr: 'ATTENTION',
        es: 'CUIDADO',
      },
      small: {
        tr: 'TELEFON MASANIN KENARINDA',
        en: 'PHONE ON THE EDGE',
        de: 'HANDY AM TISCHRAND',
        ar: 'الهاتف على حافة الطاولة',
        fr: 'TÉLÉPHONE AU BORD DE LA TABLE',
        es: 'TELÉFONO AL BORDE DE LA MESA',
      },
    },
    caption: {
      tr: 'Kıpırdama. Bir titreşim daha, düşer.',
      en: "Don't move. One more buzz and it drops.",
      de: 'Keine Bewegung. Noch ein Brummen, und es fällt.',
      ar: 'لا تتحرك. اهتزازة أخرى وسيسقط.',
      fr: 'Bouge pas. Encore un bzz et il tombe.',
      es: 'No te muevas. Una vibración más y se cae.',
    },
    headline: {
      tr: 'Titreşim telefonu kenara getirdi',
      en: 'Vibrate mode walked it to the edge',
      de: 'Der Vibrationsalarm schob es zum Rand',
      ar: 'الاهتزاز دفع الهاتف إلى الحافة',
      fr: "Le vibreur l'a poussé au bord",
      es: 'La vibración lo llevó hasta el borde',
    },
  },
  {
    emoji: '🤭',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
      },
    },
    caption: {
      tr: 'Gülersen 6. kez baştan kaydeder.',
      en: "Laugh and it's take 6.",
      de: 'Lachst du, kommt Versuch Nr. 6.',
      ar: 'إن ضحكت فسيعيد التسجيل للمرة السادسة.',
      fr: "Si tu ris, c'est la 6e prise.",
      es: 'Si te ríes, va por el sexto intento.',
    },
    headline: {
      tr: 'Kanka sesli mesajda, gözü sende',
      en: "Bestie's mid voice note, eyes on you",
      de: 'Sprachnachricht läuft, er schaut her',
      ar: 'صديقك يسجّل رسالة صوتية وعيناه عليك',
      fr: 'Ton pote enregistre un vocal et te fixe',
      es: 'Tu amigo graba un audio y te mira',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAFE',
        en: 'CAFÉ',
        de: 'CAFÉ',
        ar: 'المقهى',
        fr: 'CAFÉ',
        es: 'CAFETERÍA',
      },
    },
    caption: {
      tr: 'Bari güzel çık. Kıpırdama.',
      en: "At least look good. Don't move.",
      de: 'Dann wenigstens hübsch. Stillhalten.',
      ar: 'اظهر بشكل جميل على الأقل. لا تتحرك.',
      fr: 'Soigne ta pose. Bouge pas.',
      es: 'Al menos sal bien. No te muevas.',
    },
    headline: {
      tr: 'Yan masanın selfiesinde sen de varsın',
      en: "Next table's selfie: you're in the back",
      de: 'Selfie am Nebentisch. Du bist drauf.',
      ar: 'سيلفي على الطاولة المجاورة، وأنت خلفهم',
      fr: 'Selfie à la table voisine, tu es dedans',
      es: 'Selfie en la mesa de al lado: sales tú',
    },
  },
  {
    emoji: '🕺',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KORİDOR',
        en: 'HALLWAY',
        de: 'FLUR',
        ar: 'الممر',
        fr: 'COULOIR',
        es: 'PASILLO',
      },
    },
    caption: {
      tr: 'Kıpırdarsan sen de oynarsın.',
      en: "Move and you're in it.",
      de: 'Wer sich bewegt, tanzt mit.',
      ar: 'إن تحركت فسترقص معها.',
      fr: 'Si tu bouges, tu danses.',
      es: 'Si te mueves, bailas.',
    },
    headline: {
      tr: 'Kardeşin dans videosu için eleman arıyor',
      en: 'Your sibling needs a dance-video partner',
      de: 'Deine Schwester sucht Tänzer fürs Video',
      ar: 'أختك تبحث عن شريك لفيديو رقص',
      fr: 'Ta sœur cherche un danseur pour sa vidéo',
      es: 'Tu hermana busca pareja para su video',
    },
  },
];
