import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';
import { HANDS_OFF } from '../classic';

/**
 * School: classes, exams, homework, teachers, group projects, the school bus, graduation.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const SCHOOL_SKIP: readonly Draft[] = [
  // Scenes
  {
    emoji: '🎒',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Çantada bütün kitaplar var. Bugünkü hariç.',
      en: "Every book's in my backpack. Except today's.",
      de: 'Alle Bücher im Rucksack. Außer dem von heute.',
      ar: 'كل الكتب في حقيبتي… إلا كتاب اليوم',
      fr: "Tous mes livres dans le sac. Sauf celui d'aujourd'hui.",
      es: 'Todos los libros en la mochila. Menos el de hoy.',
      ja: 'カバンに教科書ぜんぶ入ってる。今日の分以外。',
      ko: '가방에 책 다 있음. 오늘 거 빼고.',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Zil çaldı. Hoca: “Zil benim için çalar.”',
      en: "Bell rings. Teacher: “The bell doesn't dismiss you, I do.”",
      de: 'Es klingelt. Lehrer: „Die Klingel ist für mich.“',
      ar: 'رنّ الجرس، فقال المعلم: «الجرس لي، لا لكم»',
      fr: "Ça sonne. Le prof : « La sonnerie, c'est pour moi. »",
      es: 'Suena el timbre. El profe: “El timbre es para mí”.',
      ja: 'チャイム鳴った。先生「終わりは先生が決める」',
      ko: '종이 울렸다. 선생님: “끝은 내가 정한다.”',
    },
  },
  {
    emoji: '🧮',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Okul bitti ama x’i hâlâ bulamadım',
      en: "School's long over. Still haven't found x.",
      de: 'Schule längst vorbei. x immer noch nicht gefunden.',
      ar: 'أنهيت المدرسة منذ زمن، وما زلت أبحث عن س',
      fr: "L'école, c'est fini. Toujours pas trouvé x.",
      es: 'Terminé la escuela y sigo sin encontrar la x.',
      ja: '卒業したのに、まだxが見つからない',
      ko: '졸업했는데 아직도 x를 못 찾음',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Servis beni bekledi. 30 kişi de beni izledi.',
      en: 'The bus waited for me. So did 30 staring kids.',
      de: 'Der Schulbus hat gewartet. 30 Kinder haben gestarrt.',
      ar: 'انتظرتني حافلة المدرسة… و30 طالبًا يحدّقون بي',
      fr: "Le car m'a attendu. 30 élèves m'ont regardé monter.",
      es: 'El bus escolar me esperó. Y 30 chicos me miraron.',
      ja: 'スクールバスが待っててくれた。30人の視線も。',
      ko: '통학 버스가 날 기다려 줌. 30명의 시선도.',
    },
  },
  {
    emoji: '🖍️',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Önemli yerleri işaretledim. Yani hepsini.',
      en: 'Highlighted the important parts. So… all of it.',
      de: 'Nur das Wichtige markiert. Also alles.',
      ar: 'ظلّلت المهم فقط… أي الصفحة كلها',
      fr: "J'ai surligné l'essentiel. Donc tout.",
      es: 'Subrayé solo lo importante. O sea, todo.',
      ja: '大事なところにマーカーを引いた。つまり全部。',
      ko: '중요한 부분에 형광펜 칠함. 그러니까 전부.',
    },
  },
  {
    emoji: '📄',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Biri ek kâğıt istedi. Ben hâlâ 1. sorudayım.',
      en: "Someone asked for extra paper. I'm still on question 1.",
      de: 'Jemand will ein Extrablatt. Ich bin noch bei Aufgabe 1.',
      ar: 'أحدهم طلب ورقة إضافية، وأنا ما زلت عند السؤال الأول',
      fr: "Quelqu'un demande une feuille en plus. Moi : question 1.",
      es: 'Alguien pidió otra hoja. Yo sigo en la pregunta 1.',
      ja: '誰かが追加の用紙をもらってる。私はまだ1問目。',
      ko: '누가 답안지 추가 요청함. 난 아직 1번 문제.',
    },
  },
  {
    emoji: '🎓',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Kepimi havaya attım. Hâlâ arıyorum.',
      en: 'Tossed my grad cap in the air. Still looking for it.',
      de: 'Abschlusshut in die Luft geworfen. Ich suche ihn noch.',
      ar: 'رميت قبعة التخرج في الهواء… وما زلت أبحث عنها',
      fr: 'Chapeau de diplômé lancé en l’air. Introuvable depuis.',
      es: 'Lancé el birrete al aire. Todavía lo busco.',
      ja: '卒業帽を空に投げた。まだ探してる。',
      ko: '학사모 던졌음. 아직도 찾는 중.',
    },
  },
  // Chats
  {
    emoji: '🎉',
    user: ACCOUNTS.school,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sınıf grubu',
        en: 'Class chat',
        de: 'Klassenchat',
        ar: 'مجموعة الصف',
        fr: 'Groupe de la classe',
        es: 'Grupo de la clase',
        ja: 'クラスのグループ',
        ko: '반 단톡방',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'hoca bugün gelmiyormuş!!',
            en: "teacher's not coming today!!",
            de: 'die Lehrerin kommt heute nicht!!',
            ar: 'المعلم لن يأتي اليوم!!',
            fr: "le prof vient pas aujourd'hui !!",
            es: '¡¡el profe no viene hoy!!',
            ja: '先生今日休みだって！！',
            ko: '쌤 오늘 안 오신대!!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'BOŞ DERS!!',
            en: 'FREE PERIOD!!',
            de: 'FREISTUNDE!!',
            ar: 'حصة فراغ!!',
            fr: 'PAS COURS !!',
            es: '¡¡HORA LIBRE!!',
            ja: '自習だ！！',
            ko: '자습이다!!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yerine müdür giriyormuş',
            en: "the principal's subbing instead",
            de: 'der Direktor vertritt sie',
            ar: 'والمدير سيحضر بدلًا منه',
            fr: 'le proviseur le remplace',
            es: 'viene el director a cubrirlo',
            ja: '代わりに校長が来るって',
            ko: '대신 교장 쌤이 들어오신대',
          },
        },
      ],
    },
    caption: {
      tr: 'Sevinç 40 saniye sürdü',
      en: 'The joy lasted 40 seconds',
      de: 'Die Freude hielt 40 Sekunden',
      ar: 'دامت الفرحة 40 ثانية',
      fr: 'La joie a duré 40 secondes',
      es: 'La alegría duró 40 segundos',
      ja: '喜びは40秒で終わった',
      ko: '기쁨은 40초 갔다',
    },
  },
  {
    emoji: '➗',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá', ja: 'お父さん', ko: '아빠' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba ödevde bir soru var, bakar mısın?',
            en: 'dad can you check one math question?',
            de: 'Papa, schaust du dir eine Matheaufgabe an?',
            ar: 'أبي، هل تنظر في مسألة من واجبي؟',
            fr: 'papa, tu peux regarder un exo de maths ?',
            es: 'papá, ¿me ayudas con un problema?',
            ja: 'お父さん、宿題の問題見てくれる？',
            ko: '아빠 숙제 한 문제만 봐 줄래?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'gönder, çocuk oyuncağı',
            en: "send it, that's kid stuff",
            de: 'schick her, Kinderkram',
            ar: 'أرسلها، إنها لعبة أطفال',
            fr: "envoie, c'est un jeu d'enfant",
            es: 'mándalo, es pan comido',
            ja: '送ってみな、楽勝だ',
            ko: '보내 봐, 식은 죽 먹기지',
          },
        },
        {
          from: 'them',
          text: { tr: '…', en: '…', de: '…', ar: '…', fr: '…', es: '…', ja: '…', ko: '…' },
        },
        {
          from: 'them',
          text: {
            tr: 'bu yeni sistem, annene sor',
            en: 'this is new math. ask your mom',
            de: 'das ist neue Mathe. frag Mama',
            ar: 'هذا منهج جديد، اسأل أمك',
            fr: "c'est les nouvelles maths, demande à maman",
            es: 'eso es matemática nueva, pregúntale a mamá',
            ja: 'これは新しいやり方だな。お母さんに聞いて',
            ko: '이건 요즘 방식이네. 엄마한테 물어봐',
          },
        },
      ],
    },
    caption: {
      tr: 'Babam 4. sınıf sorusuna yenildi',
      en: 'Dad lost to 4th-grade math',
      de: 'Papa hat gegen Mathe der 4. Klasse verloren',
      ar: 'أبي هُزم أمام رياضيات الصف الرابع',
      fr: 'Papa, battu par les maths de CM1',
      es: 'Papá perdió contra las matemáticas de 4.º',
      ja: '父、小4の算数に敗れる',
      ko: '아빠, 초4 수학에 패배',
    },
  },
  {
    emoji: '🥳',
    user: ACCOUNTS.school,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ders çalışma grubu',
        en: 'Study group',
        de: 'Lerngruppe',
        ar: 'مجموعة المذاكرة',
        fr: 'Groupe de révisions',
        es: 'Grupo de estudio',
        ja: '勉強会',
        ko: '스터디 모임',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'akşam bizde ders çalışıyoruz, ciddi!',
            en: 'study night at my place. serious!',
            de: 'heute Abend Lernen bei mir. ernsthaft!',
            ar: 'سنذاكر عندي الليلة، وبجدية!',
            fr: 'révisions chez moi ce soir. sérieux !',
            es: 'esta noche estudiamos en mi casa. ¡en serio!',
            ja: '今夜うちで勉強会。ガチで！',
            ko: '오늘 밤 우리 집에서 공부함. 진지하게!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tamam, ben cips getiririm',
            en: "ok, I'll bring chips",
            de: 'ok, ich bring Chips mit',
            ar: 'حسنًا، سأحضر رقائق البطاطس',
            fr: "ok, j'apporte des chips",
            es: 'ok, yo llevo snacks',
            ja: 'OK、ポテチ持ってく',
            ko: '오케이, 난 과자 가져갈게',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ben de masa oyunu getiririm',
            en: "I'll bring a board game",
            de: 'ich bring ein Brettspiel',
            ar: 'وأنا سأحضر لعبة لوحية',
            fr: 'moi, un jeu de société',
            es: 'yo, un juego de mesa',
            ja: 'じゃあボードゲーム持ってく',
            ko: '난 보드게임 가져갈게',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'hoparlör de bende',
            en: "I've got the speaker",
            de: 'ich hab die Musikbox',
            ar: 'والسماعة عليّ',
            fr: "moi, l'enceinte",
            es: 'yo llevo el altavoz',
            ja: 'スピーカーは任せて',
            ko: '스피커는 내가 챙김',
          },
        },
      ],
    },
    caption: {
      tr: 'Kitap getiren yok ama',
      en: "Nobody's bringing a book, though",
      de: 'Ein Buch bringt aber keiner mit',
      ar: 'ولا أحد سيحضر كتابًا',
      fr: "Mais personne n'apporte de livre",
      es: 'Pero nadie lleva un libro',
      ja: '教科書を持ってくる人はゼロ',
      ko: '근데 책 가져오는 사람 없음',
    },
  },
  {
    emoji: '🙃',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: '4. soru nereden çıktı ya?',
            en: 'where did question 4 even come from??',
            de: 'wo kam Aufgabe 4 denn her??',
            ar: 'من أين جاء السؤال الرابع؟؟',
            fr: "la question 4, elle sort d'où ??",
            es: '¿¿de dónde salió la pregunta 4??',
            ja: '4問目どこから出たの？？',
            ko: '4번 문제 대체 어디서 나온 거야??',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hocanın “bu çıkmaz” dediği yerden',
            en: "from the part he said “won't be on it”",
            de: 'aus dem Teil, der „nicht drankommt“',
            ar: 'من الجزء الذي قال عنه «لن يأتي»',
            fr: 'du chapitre qui « tombera pas »',
            es: 'de lo que el profe dijo que “no entraba”',
            ja: '先生が「ここは出ない」って言ったとこ',
            ko: '쌤이 “여긴 안 나와”라고 한 데서',
          },
        },
      ],
    },
    caption: {
      tr: 'Hoca ters psikoloji ustası',
      en: 'Reverse psychology, teacher edition',
      de: 'Umgekehrte Psychologie, Lehrer-Edition',
      ar: 'المعلم أستاذ في علم النفس العكسي',
      fr: 'Psychologie inversée, version prof',
      es: 'Psicología inversa, versión profe',
      ja: '先生の「出ない」は「出る」の意味',
      ko: '선생님의 “안 나와”는 “나온다”는 뜻',
    },
  },
  // Polls
  {
    emoji: '🙋',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Hoca “soru var mı?” dedi. Sen:',
        en: 'Teacher asks, “Any questions?” You:',
        de: 'Lehrer fragt: „Noch Fragen?“ Du:',
        ar: 'سأل المعلم: «هل من أسئلة؟» وأنت:',
        fr: 'Le prof : « Des questions ? » Toi :',
        es: 'El profe: “¿Alguna pregunta?”. Tú:',
        ja: '先生「質問ある人？」あなたは：',
        ko: '선생님: “질문 있어요?” 당신은:',
      },
      options: [
        {
          tr: 'Soru sorarım',
          en: 'Ask one',
          de: 'Ich frage was',
          ar: 'أطرح سؤالًا',
          fr: 'Je pose une question',
          es: 'Pregunto algo',
          ja: '質問する',
          ko: '질문한다',
        },
        {
          tr: 'Zili beklerim',
          en: 'Wait for the bell',
          de: 'Ich warte auf den Gong',
          ar: 'أنتظر الجرس',
          fr: "J'attends la sonnerie",
          es: 'Espero el timbre',
          ja: 'チャイムを待つ',
          ko: '종을 기다린다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Her soru teneffüsten 5 dakika yer',
      en: 'Every question eats 5 minutes of break',
      de: 'Jede Frage kostet 5 Minuten Pause',
      ar: 'كل سؤال يأكل 5 دقائق من الاستراحة',
      fr: 'Chaque question mange 5 minutes de récré',
      es: 'Cada pregunta se come 5 minutos del recreo',
      ja: '質問1つで休み時間が5分減る',
      ko: '질문 하나에 쉬는 시간 5분 삭제',
    },
  },
  {
    emoji: '🖊️',
    user: ACCOUNTS.school,
    body: {
      format: 'poll',
      question: {
        tr: 'Ders çalışmaya oturdun. İlk 30 dakika:',
        en: 'You sit down to study. First 30 minutes:',
        de: 'Du setzt dich zum Lernen. Erste 30 Minuten:',
        ar: 'جلست لتذاكر. أول 30 دقيقة:',
        fr: 'Tu te mets à réviser. Les 30 premières minutes :',
        es: 'Te sientas a estudiar. Primeros 30 minutos:',
        ja: '勉強しようと座った。最初の30分：',
        ko: '공부하려고 앉았다. 처음 30분:',
      },
      options: [
        { tr: 'Çalışırım', en: 'I study', de: 'Ich lerne', ar: 'أذاكر', fr: 'Je révise', es: 'Estudio', ja: '勉強する', ko: '공부한다' },
        {
          tr: 'Masayı düzenlerim',
          en: 'Tidy the desk',
          de: 'Schreibtisch aufräumen',
          ar: 'أرتّب المكتب',
          fr: 'Je range le bureau',
          es: 'Ordeno el escritorio',
          ja: '机を片づける',
          ko: '책상 정리',
        },
        {
          tr: 'Renkli kalem dizerim',
          en: 'Sort pens by color',
          de: 'Stifte nach Farbe',
          ar: 'أرتّب الأقلام بالألوان',
          fr: 'Je trie mes stylos',
          es: 'Ordeno los colores',
          ja: 'ペンを色順に並べる',
          ko: '펜 색깔별 정리',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Masa hazır, kalemler hazır. Ben değilim.',
      en: "Desk's ready. Pens are ready. I'm not.",
      de: 'Tisch bereit. Stifte bereit. Ich nicht.',
      ar: 'المكتب جاهز، والأقلام جاهزة… وأنا لا',
      fr: 'Bureau prêt. Stylos prêts. Moi, non.',
      es: 'Escritorio listo. Lápices listos. Yo, no.',
      ja: '机も準備OK、ペンも準備OK。私はまだ。',
      ko: '책상 준비 끝. 펜 준비 끝. 나는 아직.',
    },
  },
  {
    emoji: '🙉',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sınav bitti, herkes cevapları konuşuyor. Sen:',
        en: "Exam's over. Everyone's comparing answers. You:",
        de: 'Prüfung vorbei, alle vergleichen. Du:',
        ar: 'انتهى الامتحان والجميع يقارن الإجابات. وأنت:',
        fr: "Fin de l'exam, tout le monde compare. Toi :",
        es: 'Acabó el examen y todos comparan respuestas. Tú:',
        ja: 'テスト終了。みんな答え合わせしてる。あなたは：',
        ko: '시험 끝. 다들 답 맞춰 보는 중. 당신은:',
      },
      options: [
        {
          tr: 'Karşılaştırırım',
          en: 'Compare mine',
          de: 'Ich vergleiche mit',
          ar: 'أقارن إجاباتي',
          fr: 'Je compare',
          es: 'Comparo las mías',
          ja: '答え合わせする',
          ko: '나도 맞춰 본다',
        },
        {
          tr: 'Kulaklarımı kapatırım',
          en: 'Cover my ears',
          de: 'Ohren zuhalten',
          ar: 'أسدّ أذنيّ',
          fr: 'Oreilles bouchées',
          es: 'Me tapo los oídos',
          ja: '耳をふさぐ',
          ko: '귀를 막는다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Bilmemek daha huzurlu',
      en: 'Ignorance is bliss',
      de: 'Was ich nicht weiß, macht mich nicht heiß',
      ar: 'في عدم المعرفة راحة',
      fr: "Moins j'en sais, mieux je me porte",
      es: 'Ojos que no ven, corazón que no siente',
      ja: '知らぬが仏',
      ko: '모르는 게 약',
    },
  },
  // Charts
  {
    emoji: '🕯️',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'DERS ÇALIŞMA İSTEĞİM',
        en: 'MY URGE TO STUDY',
        de: 'MEINE LERNLUST',
        ar: 'رغبتي في المذاكرة',
        fr: 'MON ENVIE DE RÉVISER',
        es: 'MIS GANAS DE ESTUDIAR',
        ja: '勉強したい気持ち',
        ko: '공부하고 싶은 마음',
      },
      value: null,
      shape: 'spike',
      axis: 'days',
    },
    caption: {
      tr: 'Sınavdan önceki gece 02.00’de tavan yaptı',
      en: 'Peaked at 2 a.m. the night before the exam',
      de: 'Höhepunkt: 2 Uhr nachts vor der Prüfung',
      ar: 'بلغت ذروتها ليلة الامتحان، الساعة 2 فجرًا',
      fr: "Pic à 2 h du matin, la veille de l'exam",
      es: 'Máximo: 2 de la mañana, la víspera del examen',
      ja: 'ピークはテスト前夜の午前2時',
      ko: '최고점은 시험 전날 새벽 2시',
    },
  },
  {
    emoji: '📔',
    user: ACCOUNTS.school,
    body: {
      format: 'chart',
      title: {
        tr: 'DEFTERİMİN DÜZENİ',
        en: 'MY NOTEBOOK NEATNESS',
        de: 'ORDNUNG IM HEFT',
        ar: 'ترتيب دفتري',
        fr: 'PROPRETÉ DE MON CAHIER',
        es: 'ORDEN DE MI CUADERNO',
        ja: 'ノートのきれいさ',
        ko: '내 노트 정리 상태',
      },
      value: null,
      shape: 'fall',
      axis: 'months',
    },
    caption: {
      tr: '1. sayfa sanat eseri, son sayfa hiyeroglif',
      en: 'Page 1: a masterpiece. Last page: hieroglyphs.',
      de: 'Seite 1: Kunstwerk. Letzte Seite: Hieroglyphen.',
      ar: 'الصفحة الأولى تحفة فنية، والأخيرة نقوش هيروغليفية',
      fr: "Page 1 : chef-d'œuvre. Dernière page : hiéroglyphes.",
      es: 'Página 1: obra de arte. Última: jeroglíficos.',
      ja: '1ページ目は芸術作品、最後のページは象形文字',
      ko: '1쪽은 예술 작품, 마지막 쪽은 상형 문자',
    },
  },
  // Receipts
  {
    emoji: '🖨️',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'FOTOKOPİ MERKEZİ',
        en: 'COPY SHOP',
        de: 'COPYSHOP',
        ar: 'مركز تصوير',
        fr: 'REPROGRAPHIE',
        es: 'CENTRO DE COPIADO',
        ja: 'コピーセンター',
        ko: '복사집',
      },
      items: [
        {
          tr: 'DERS NOTU (240 SAYFA)',
          en: 'CLASS NOTES (240 PG)',
          de: 'SKRIPT (240 SEITEN)',
          ar: 'ملخص المادة (240 صفحة)',
          fr: 'POLY DE COURS (240 P.)',
          es: 'APUNTES (240 PÁGINAS)',
          ja: '講義ノート（240枚）',
          ko: '강의 노트 (240쪽)',
        },
      ],
    },
    caption: {
      tr: 'Fotokopisini aldım, öğrenmiş sayılırım',
      en: 'Copied it. That counts as studying, right?',
      de: 'Kopiert ist halb gelernt.',
      ar: 'صوّرتها، فكأنني ذاكرتها',
      fr: 'Photocopié, donc à moitié révisé.',
      es: 'Fotocopiado, o sea, casi aprendido.',
      ja: 'コピーした。もう覚えたも同然',
      ko: '복사했으니 공부한 걸로 침',
    },
  },
  {
    emoji: '📐',
    user: ACCOUNTS.school,
    body: {
      format: 'receipt',
      store: {
        tr: 'KIRTASİYE',
        en: 'STATIONERY STORE',
        de: 'SCHREIBWAREN',
        ar: 'قرطاسية',
        fr: 'PAPETERIE',
        es: 'PAPELERÍA',
        ja: '文房具店',
        ko: '문구점',
      },
      items: [
        {
          tr: 'PERGEL SETİ (20 PARÇA)',
          en: 'GEOMETRY SET (20 PCS)',
          de: 'ZIRKELSET (20 TEILE)',
          ar: 'طقم هندسة (20 قطعة)',
          fr: 'GÉOMÉTRIE (20 PIÈCES)',
          es: 'SET DE GEOMETRÍA (20)',
          ja: '製図セット（20点）',
          ko: '컴퍼스 세트 (20종)',
        },
      ],
    },
    caption: {
      tr: '4 yılda kullandığım tek parça: cetvel',
      en: '4 years. The only piece I used: the ruler.',
      de: 'In 4 Jahren benutzt: nur das Lineal',
      ar: 'في 4 سنوات لم أستخدم منه إلا المسطرة',
      fr: "En 4 ans, j'ai utilisé la règle. Point.",
      es: 'En 4 años solo usé la regla',
      ja: '4年間で使ったのは定規だけ',
      ko: '4년 동안 쓴 건 자 하나뿐',
    },
  },
  // Facts
  {
    emoji: '💡',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3', ja: '3', ko: '3' },
      text: {
        tr: 'kez doğru cevabı sınavdan çıkar çıkmaz hatırladın',
        en: 'times you remembered the answer right after the exam',
        de: 'Mal fiel dir die Antwort direkt nach der Prüfung ein',
        ar: 'مرات تذكرت فيها الإجابة فور خروجك من الامتحان',
        fr: "fois où la réponse t'est revenue juste après l'exam",
        es: 'veces recordaste la respuesta justo al salir del examen',
        ja: '回、テストが終わった瞬間に正解を思い出した',
        ko: '번, 시험장 나오자마자 정답이 생각남',
      },
    },
    caption: {
      tr: 'Cevaplar koridorda bekliyor',
      en: 'The answers wait in the hallway',
      de: 'Die Antworten warten im Flur',
      ar: 'الإجابات تنتظرك في الممر',
      fr: 'Les réponses attendent dans le couloir',
      es: 'Las respuestas esperan en el pasillo',
      ja: '答えは廊下で待っている',
      ko: '정답은 복도에서 기다림',
    },
  },
  {
    emoji: '⏰',
    user: ACCOUNTS.school,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU DERSTE',
        en: 'IN THIS CLASS',
        de: 'IN DIESER STUNDE',
        ar: 'في هذه الحصة',
        fr: 'PENDANT CE COURS',
        es: 'EN ESTA CLASE',
        ja: 'この授業で',
        ko: '이번 수업에서',
      },
      big: { tr: '12', en: '12', de: '12', ar: '12', fr: '12', es: '12', ja: '12', ko: '12' },
      text: {
        tr: 'kez dersin bitmesine kaç dakika kaldığına baktın',
        en: 'times you checked how many minutes were left',
        de: 'Mal geschaut, wie viele Minuten noch übrig sind',
        ar: 'مرة نظرت فيها كم دقيقة بقيت على نهاية الحصة',
        fr: 'fois où tu as vérifié combien de minutes il restait',
        es: 'veces miraste cuántos minutos faltaban',
        ja: '回、授業の残り時間を確認した',
        ko: '번, 수업 끝나기까지 몇 분 남았는지 확인함',
      },
    },
    caption: {
      tr: 'Saat bakıldıkça yavaşlar',
      en: 'A watched clock never moves',
      de: 'Beobachtete Uhren gehen langsamer',
      ar: 'الساعة تبطئ كلما نظرت إليها',
      fr: "Une horloge qu'on regarde ralentit",
      es: 'El reloj se frena si lo miras',
      ja: '時計は見るほど遅くなる',
      ko: '시계는 볼수록 느려짐',
    },
  },
  {
    emoji: '🧹',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'SINAV HAFTASI',
        en: 'EXAM WEEK',
        de: 'PRÜFUNGSWOCHE',
        ar: 'أسبوع الامتحانات',
        fr: "SEMAINE D'EXAMS",
        es: 'SEMANA DE EXÁMENES',
        ja: 'テスト週間',
        ko: '시험 기간',
      },
      big: { tr: '4', en: '4', de: '4', ar: '4', fr: '4', es: '4', ja: '4', ko: '4' },
      text: {
        tr: 'kez odanı topladın; ders kitabın hâlâ kapalı',
        en: 'times you cleaned your room. Textbook: still closed.',
        de: 'Mal das Zimmer aufgeräumt. Das Lehrbuch ist noch zu.',
        ar: 'مرات رتّبت غرفتك، والكتاب ما زال مغلقًا',
        fr: 'fois où tu as rangé ta chambre. Le manuel : toujours fermé.',
        es: 'veces ordenaste tu cuarto. El libro sigue cerrado.',
        ja: '回、部屋を片づけた。教科書はまだ閉じたまま',
        ko: '번 방 청소함. 교과서는 아직도 덮여 있음',
      },
    },
    caption: {
      tr: 'Odan hiç bu kadar temiz olmamıştı',
      en: 'Your room has never been this clean',
      de: 'So sauber war dein Zimmer noch nie',
      ar: 'لم تكن غرفتك يومًا بهذه النظافة',
      fr: "Ta chambre n'a jamais été aussi propre",
      es: 'Tu cuarto nunca estuvo tan limpio',
      ja: '部屋がこんなにきれいだったことはない',
      ko: '방이 이렇게 깨끗했던 적은 없었음',
    },
  },
  {
    emoji: '⌛',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '15', en: '15', de: '15', ar: '15', fr: '15', es: '15', ja: '15', ko: '15' },
      text: {
        tr: 'dakikadır hoca yok; kimse ilk kalkan olmak istemiyor',
        en: 'minutes, no professor. Nobody wants to leave first.',
        de: 'Minuten kein Prof. Keiner will als Erster gehen.',
        ar: 'دقيقة ولا أستاذ، ولا أحد يريد أن يغادر أولًا',
        fr: "minutes sans prof. Personne n'ose partir en premier.",
        es: 'minutos sin profe. Nadie quiere irse primero.',
        ja: '分、教授が来ない。誰も最初に帰りたくない',
        ko: '분째 교수님 안 오심. 아무도 먼저 나가기 싫음',
      },
    },
    caption: {
      tr: '16. dakikada kapı açıldı',
      en: 'Minute 16: the door opens',
      de: 'Minute 16: Die Tür geht auf',
      ar: 'وفي الدقيقة 16 انفتح الباب',
      fr: "16e minute : la porte s'ouvre",
      es: 'Minuto 16: se abre la puerta',
      ja: '16分目、ドアが開いた',
      ko: '16분째, 문이 열렸다',
    },
  },
  // Tier lists
  {
    emoji: '🐕',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ÖDEV BAHANESİ TIER LIST',
        en: 'HOMEWORK EXCUSE TIER LIST',
        de: 'AUSREDEN-TIER-LIST',
        ar: 'تصنيف أعذار الواجب',
        fr: 'TIER LIST DES EXCUSES',
        es: 'TIER LIST DE EXCUSAS',
        ja: '宿題の言い訳Tier表',
        ko: '숙제 핑계 티어표',
      },
      rows: [['🐕'], ['💻', '🖨️'], ['🐈', '🌬️'], ['🤷']],
    },
    caption: {
      tr: 'Köpeğim yok. Bahanem var.',
      en: 'No dog. Still using the excuse.',
      de: 'Kein Hund. Aber die Ausrede zieht.',
      ar: 'لا أملك كلبًا… لكن العذر جاهز',
      fr: "Pas de chien. L'excuse marche quand même.",
      es: 'No tengo perro. La excusa, sí.',
      ja: '犬は飼ってない。でも「犬が食べた」は使う。',
      ko: '강아지 없음. 근데 핑계엔 강아지 있음.',
    },
  },
  {
    emoji: '🥪',
    user: ACCOUNTS.school,
    body: {
      format: 'tier',
      title: {
        tr: 'KANTİN TIER LIST',
        en: 'CAFETERIA TIER LIST',
        de: 'KANTINEN-TIER-LIST',
        ar: 'تصنيف المقصف',
        fr: 'TIER LIST DE LA CANTINE',
        es: 'TIER LIST DE LA CAFETERÍA',
        ja: '購買Tier表',
        ko: '매점 티어표',
      },
      rows: [['🥪', '🥯'], ['🧃', '🍫'], ['🍌', '🍪'], ['🥗']],
    },
    caption: {
      tr: 'Tost S. Kokusu 3. kata kadar çıkıyor.',
      en: 'Grilled cheese is S. You can smell it from the 3rd floor.',
      de: 'Toast ist S. Man riecht ihn bis in den 3. Stock.',
      ar: 'الشطيرة في القمة، ورائحتها تصل إلى الطابق الثالث',
      fr: "Le croque est S. On le sent jusqu'au 3e.",
      es: 'El sándwich es S. Se huele hasta el 3.er piso.',
      ja: '焼きそばパンはS。3階まで匂いがする',
      ko: '토스트 S. 냄새가 3층까지 올라옴.',
    },
  },
  // Lock screens
  {
    emoji: '😬',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '📝',
        app: {
          tr: 'Okul portalı',
          en: 'School portal',
          de: 'Schulportal',
          ar: 'بوابة المدرسة',
          fr: 'Espace élèves',
          es: 'Portal escolar',
          ja: '学校ポータル',
          ko: '학교 포털',
        },
        text: {
          tr: 'Yeni not girildi: Matematik yazılısı',
          en: 'New grade posted: Math test',
          de: 'Neue Note eingetragen: Mathearbeit',
          ar: 'رُصدت درجة جديدة: اختبار الرياضيات',
          fr: 'Nouvelle note : contrôle de maths',
          es: 'Nueva nota: examen de matemáticas',
          ja: '新しい成績：数学のテスト',
          ko: '새 성적 등록: 수학 시험',
        },
      },
    },
    caption: {
      tr: 'Açmadan önce 10 dakika tavana baktım',
      en: 'Stared at the ceiling 10 minutes first',
      de: 'Erst mal 10 Minuten an die Decke gestarrt',
      ar: 'حدّقت في السقف 10 دقائق قبل أن أفتحها',
      fr: "10 minutes à fixer le plafond avant d'ouvrir",
      es: 'Miré el techo 10 minutos antes de abrirla',
      ja: '開く前に10分、天井を見つめた',
      ko: '열기 전에 10분 동안 천장만 봄',
    },
  },
  {
    emoji: '🖱️',
    user: ACCOUNTS.school,
    body: {
      format: 'notifications',
      first: {
        icon: '🎓',
        app: {
          tr: 'Üniversite',
          en: 'University',
          de: 'Universität',
          ar: 'الجامعة',
          fr: 'Université',
          es: 'Universidad',
          ja: '大学',
          ko: '대학교',
        },
        text: {
          tr: 'Ders kaydı 09.00’da başlıyor',
          en: 'Course registration opens at 9:00',
          de: 'Kurswahl startet um 9:00 Uhr',
          ar: 'يبدأ تسجيل المقررات الساعة 9:00',
          fr: 'Inscriptions aux cours à 9 h',
          es: 'Inscripción de materias: 9:00',
          ja: '履修登録は9:00開始',
          ko: '수강 신청 9:00 시작',
        },
      },
    },
    caption: {
      tr: 'Alarm 08.55’te çaldı, site 09.01’de çöktü',
      en: 'Alarm at 8:55. Site crashed at 9:01.',
      de: 'Wecker um 8:55. Um 9:01 war die Seite down.',
      ar: 'رنّ المنبه 8:55، وتعطّل الموقع 9:01',
      fr: 'Réveil à 8 h 55. Site planté à 9 h 01.',
      es: 'Alarma a las 8:55. La web se cayó a las 9:01.',
      ja: '8:55にアラーム。9:01にサイトが落ちた。',
      ko: '알람 8:55. 사이트 다운 9:01.',
    },
  },
  // Quote cards
  {
    emoji: '🧠',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bilgi güçtür. Benimki sınavdan çıkınca sıfırlanıyor.',
        en: 'Knowledge is power. Mine resets the minute the exam ends.',
        de: 'Wissen ist Macht. Meins löscht sich nach der Prüfung.',
        ar: 'المعرفة قوة. أما معرفتي فتُمحى بعد الامتحان مباشرة.',
        fr: "Le savoir, c'est le pouvoir. Le mien s'efface après l'exam.",
        es: 'El saber es poder. El mío se borra al salir del examen.',
        ja: '知識は力なり。私の知識はテスト終了でリセットされる。',
        ko: '아는 것이 힘이다. 내 힘은 시험 끝나면 초기화된다.',
      },
    },
    caption: {
      tr: 'Bir sonraki sınava yeniden yüklenir',
      en: 'Reinstalling before the next exam',
      de: 'Neustart vor der nächsten Prüfung',
      ar: 'ويُعاد تحميلها قبل الامتحان القادم',
      fr: 'Réinstallation avant le prochain exam',
      es: 'Se reinstala antes del próximo examen',
      ja: '次のテスト前に再インストール',
      ko: '다음 시험 전에 재설치 예정',
    },
  },
  {
    emoji: '📽️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her son yeni bir başlangıçtır. — Hocanın son slaytı',
        en: "Every ending is a new beginning. — The professor's last slide",
        de: 'Jedes Ende ist ein neuer Anfang. — Die letzte Folie vom Prof',
        ar: 'كل نهاية بداية جديدة. — الشريحة الأخيرة للأستاذ',
        fr: 'Chaque fin est un nouveau départ. — La dernière diapo du prof',
        es: 'Cada final es un nuevo comienzo. — La última diapositiva del profe',
        ja: '終わりは新たな始まりである。— 教授の最後のスライド',
        ko: '모든 끝은 새로운 시작이다. — 교수님의 마지막 슬라이드',
      },
    },
    caption: {
      tr: 'Son slayttan sonra 14 slayt daha geldi',
      en: 'After the last slide came 14 more',
      de: 'Nach der letzten Folie kamen noch 14',
      ar: 'وبعد الشريحة الأخيرة جاءت 14 شريحة أخرى',
      fr: 'Après la dernière diapo, 14 autres',
      es: 'Tras la última diapositiva, vinieron 14 más',
      ja: '最後のスライドのあと、さらに14枚',
      ko: '마지막 슬라이드 다음에 14장 더 나옴',
    },
  },
  {
    emoji: '✏️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat bir sınavdır. Ben yine kalemsiz geldim.',
        en: 'Life is a test. And I forgot my pencil again.',
        de: 'Das Leben ist eine Prüfung. Und ich hab wieder keinen Stift.',
        ar: 'الحياة امتحان، وأنا جئت بلا قلم كالعادة.',
        fr: "La vie est un examen. Et j'ai encore oublié mon stylo.",
        es: 'La vida es un examen. Y otra vez vine sin lápiz.',
        ja: '人生はテストだ。そして私はまたペンを忘れた。',
        ko: '인생은 시험이다. 난 또 펜을 안 가져왔다.',
      },
    },
    caption: {
      tr: 'Yan sıradaki 4 yıldır bana kalem veriyor',
      en: "My desk buddy's been lending me pens for 4 years",
      de: 'Mein Banknachbar leiht mir seit 4 Jahren Stifte',
      ar: 'زميلي يعيرني قلمه منذ 4 سنوات',
      fr: 'Mon voisin me prête un stylo depuis 4 ans',
      es: 'Mi compañero me presta lápiz hace 4 años',
      ja: '隣の席の子に4年間ペンを借りてる',
      ko: '옆자리 친구가 4년째 펜 빌려주는 중',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Asla hafife alma. — Açık kitap sınavına giren biri',
        en: 'Never underestimate anything. — Someone after an open-book exam',
        de: 'Unterschätze niemals etwas. — Jemand nach einer Open-Book-Klausur',
        ar: 'لا تستهن بشيء أبدًا. — شخص خاض امتحانًا بكتاب مفتوح',
        fr: "Ne sous-estime jamais rien. — Quelqu'un après un exam à livre ouvert",
        es: 'Nunca subestimes nada. — Alguien tras un examen a libro abierto',
        ja: '何ごとも甘く見るな。— 持ち込み可のテストを受けた人',
        ko: '절대 방심하지 마라. — 오픈북 시험을 본 사람',
      },
    },
    caption: {
      tr: 'Kitap açıktı, zihnim kapalıydı',
      en: "The book was open. My brain wasn't.",
      de: 'Das Buch war offen, mein Kopf nicht',
      ar: 'كان الكتاب مفتوحًا، وعقلي مغلقًا',
      fr: 'Le livre était ouvert. Mon cerveau, non.',
      es: 'El libro estaba abierto. Mi mente, no.',
      ja: '本は開いてた。頭は閉じてた。',
      ko: '책은 열려 있었다. 머리는 닫혀 있었다.',
    },
  },
];

export const SCHOOL_LIKE: readonly Draft[] = [
  // Scenes
  {
    emoji: '🌋',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'yanardağ deneyim çalıştı!! her yer köpük',
      en: 'my volcano project worked!! foam everywhere',
      de: 'mein vulkan-experiment hat geklappt!! überall schaum',
      ar: 'تجربة البركان نجحت!! الرغوة في كل مكان',
      fr: 'mon volcan a marché !! de la mousse partout',
      es: '¡¡mi volcán funcionó!! hay espuma por todos lados',
      ja: '火山の実験成功！！そこらじゅう泡だらけ',
      ko: '화산 실험 성공!! 사방이 거품',
    },
  },
  {
    emoji: '👵',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'anneannem 68’inde üniversiteye başladı!!',
      en: 'my grandma started college at 68!!',
      de: 'meine oma hat mit 68 ihr studium angefangen!!',
      ar: 'جدتي بدأت الجامعة في عمر 68!!',
      fr: 'ma grand-mère a commencé la fac à 68 ans !!',
      es: '¡¡mi abuela empezó la universidad a los 68!!',
      ja: 'おばあちゃんが68歳で大学に入った！！',
      ko: '우리 할머니 68세에 대학 입학!!',
    },
  },
  {
    emoji: '📊',
    user: ACCOUNTS.naz,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk sunumumu yaptım ve kimse uyumadı!!',
      en: 'gave my first presentation and nobody fell asleep!!',
      de: 'mein erstes referat und keiner ist eingeschlafen!!',
      ar: 'قدّمت أول عرض لي ولم ينم أحد!!',
      fr: "mon premier exposé et personne ne s'est endormi !!",
      es: '¡¡mi primera exposición y nadie se durmió!!',
      ja: '初めての発表、誰も寝なかった！！',
      ko: '첫 발표 했는데 아무도 안 졸았다!!',
    },
  },
  // Instant photos
  {
    emoji: '🏫',
    user: ACCOUNTS.arda,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni kampüs, yeni ben',
        en: 'new campus, new me',
        de: 'neuer campus, neues ich',
        ar: 'حرم جديد، أنا جديد',
        fr: 'nouvelle fac, nouveau moi',
        es: 'nuevo campus, nuevo yo',
        ja: '新キャンパス、新しい私',
        ko: '새 캠퍼스, 새로운 나',
      },
    },
    caption: {
      tr: 'üniversitede ilk günüm, 3 kez kayboldum',
      en: 'first day of college, got lost 3 times',
      de: 'erster tag an der uni, 3-mal verlaufen',
      ar: 'أول يوم لي في الجامعة، وتهت 3 مرات',
      fr: 'premier jour à la fac, perdu 3 fois',
      es: 'primer día en la uni, me perdí 3 veces',
      ja: '大学初日、3回迷子になった',
      ko: '대학 첫날, 3번 길 잃음',
    },
  },
  {
    emoji: '📜',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'panoda benim şiirim',
        en: 'my poem, pinned up',
        de: 'mein gedicht hängt',
        ar: 'قصيدتي على اللوحة',
        fr: 'mon poème affiché',
        es: 'mi poema en el mural',
        ja: '掲示板に私の詩',
        ko: '게시판에 내 시',
      },
    },
    caption: {
      tr: 'yazdığım şiiri öğretmen panoya astı!!',
      en: 'my teacher pinned my poem on the class board!!',
      de: 'meine lehrerin hat mein gedicht aufgehängt!!',
      ar: 'المعلمة علّقت قصيدتي على لوحة الصف!!',
      fr: 'la prof a affiché mon poème en classe !!',
      es: '¡¡la profe colgó mi poema en el mural!!',
      ja: '私の詩を先生が掲示板に貼ってくれた！！',
      ko: '내가 쓴 시를 선생님이 게시판에 붙여 줌!!',
    },
  },
  {
    emoji: '🖋️',
    user: ACCOUNTS.irem,
    body: {
      format: 'polaroid',
      note: {
        tr: 'mürekkep her yerde',
        en: 'ink everywhere',
        de: 'tinte überall',
        ar: 'الحبر في كل مكان',
        fr: "de l'encre partout",
        es: 'tinta por todas partes',
        ja: 'インクまみれ',
        ko: '온통 잉크',
      },
    },
    caption: {
      tr: 'dolma kalemle ilk sayfam, parmaklarım masmavi',
      en: 'first page with a fountain pen, fingers very blue',
      de: 'erste seite mit füller, finger jetzt blau',
      ar: 'أول صفحة بقلم الحبر، وأصابعي زرقاء تمامًا',
      fr: 'première page au stylo plume, doigts tout bleus',
      es: 'primera página con estilográfica, dedos azules',
      ja: '万年筆で初めての1ページ、指が真っ青',
      ko: '만년필로 쓴 첫 페이지, 손가락이 새파래짐',
    },
  },
  {
    emoji: '💐',
    user: ACCOUNTS.tolga,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk öğretmenim',
        en: 'my first teacher',
        de: 'meine erste lehrerin',
        ar: 'معلمتي الأولى',
        fr: 'ma maîtresse de cp',
        es: 'mi primera maestra',
        ja: 'はじめての先生',
        ko: '나의 첫 선생님',
      },
    },
    caption: {
      tr: '15 yıl sonra ilk öğretmenimi ziyaret ettim',
      en: 'visited my first-grade teacher, 15 years later',
      de: 'nach 15 jahren meine erste lehrerin besucht',
      ar: 'زرت معلمتي الأولى بعد 15 عامًا',
      fr: 'revu ma maîtresse de cp, 15 ans après',
      es: 'visité a mi primera maestra 15 años después',
      ja: '15年ぶりに小1の担任に会いに行った',
      ko: '15년 만에 1학년 담임 선생님을 찾아감',
    },
  },
  // Photo dumps
  {
    emoji: '📚',
    user: ACCOUNTS.ece,
    body: { format: 'dump', emojis: ['📚', '☕️', '🌙', '🗒️', '🥳'] },
    caption: {
      tr: 'final haftası: 12 kahve, 3 sabahlama, hepsi bitti!!',
      en: 'finals week dump: 12 coffees, 3 all-nighters, done!!',
      de: 'prüfungswoche: 12 kaffee, 3 nächte durch, geschafft!!',
      ar: 'أسبوع الامتحانات: 12 قهوة، 3 ليالٍ بلا نوم، وانتهينا!!',
      fr: "semaine d'exams : 12 cafés, 3 nuits blanches, fini !!",
      es: 'semana de exámenes: 12 cafés, 3 noches en vela, ¡¡terminé!!',
      ja: '期末まとめ：コーヒー12杯、徹夜3回、終わった！！',
      ko: '기말고사 주간: 커피 12잔, 밤샘 3번, 끝!!',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.berk,
    body: { format: 'dump', emojis: ['👕', '🖊️', '🏫', '📸', '🌞'] },
    caption: {
      tr: 'okulun son günü: gömlekler imzalandı, gözler doldu',
      en: 'last day of school: signed shirts, happy tears',
      de: 'letzter schultag: t-shirts signiert, tränen in den augen',
      ar: 'آخر يوم في المدرسة: توقيعات على القمصان، ودموع في العيون',
      fr: 'dernier jour de cours : t-shirts signés, larmes aux yeux',
      es: 'último día de clases: camisetas firmadas, ojos llorosos',
      ja: '最終登校日：シャツに寄せ書き、うれし涙',
      ko: '마지막 등교: 셔츠에 사인, 눈물 글썽',
    },
  },
  {
    emoji: '🎶',
    user: ACCOUNTS.melis,
    body: { format: 'dump', emojis: ['🎶', '🚌', '🗺️', '🧃', '🍎'] },
    caption: {
      tr: 'okul gezisi dump’ı: en güzeli otobüs şarkıları',
      en: 'field trip dump: the bus songs were the best part',
      de: 'klassenfahrt-dump: das beste waren die lieder im bus',
      ar: 'رحلة المدرسة: أجمل ما فيها أغاني الحافلة',
      fr: "sortie scolaire : le mieux, c'était les chansons du car",
      es: 'excursión escolar: lo mejor fueron las canciones en el bus',
      ja: '遠足まとめ：最高だったのはバスカラオケ',
      ko: '현장학습 모음: 최고는 버스에서 떼창',
    },
  },
];

export const SCHOOL_HOLD: readonly Draft[] = [
  {
    emoji: '🔔',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir an: hoca dersi 10 dakika erken bitirdi',
      en: 'Rare moment: class let out 10 minutes early',
      de: 'Seltener Moment: 10 Minuten früher Schluss',
      ar: 'لحظة نادرة: المعلم أنهى الحصة قبل موعدها بعشر دقائق',
      fr: 'Moment rare : le cours finit 10 minutes plus tôt',
      es: 'Momento único: la clase terminó 10 minutos antes',
      ja: 'レアな瞬間：授業が10分早く終わった',
      ko: '희귀한 순간: 수업이 10분 일찍 끝남',
    },
  },
  {
    emoji: '📝',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi cümle: “Bu hafta ödev yok.”',
      en: 'Legendary words: “No homework this week.”',
      de: 'Legendärer Satz: „Diese Woche keine Hausaufgaben.“',
      ar: 'عبارة أسطورية: «لا واجبات هذا الأسبوع»',
      fr: 'Phrase légendaire : « Pas de devoirs cette semaine. »',
      es: 'Frase legendaria: “Esta semana no hay tarea”.',
      ja: '伝説の一言：「今週は宿題なし」',
      ko: '전설의 한마디: “이번 주 숙제 없음.”',
    },
  },
  {
    emoji: '🎯',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'İnanılmaz! Sınavda tam çalıştığın yerler çıktı',
      en: 'Unbelievable! The exam was exactly what you studied',
      de: 'Unglaublich! Genau das kam dran, was du gelernt hast',
      ar: 'لا يُصدَّق! جاء في الامتحان ما ذاكرته بالضبط',
      fr: "Incroyable ! L'exam tombe pile sur tes révisions",
      es: '¡Increíble! En el examen vino justo lo que estudiaste',
      ja: '信じられない！勉強したところだけが出た',
      ko: '대박! 공부한 데서만 시험이 나옴',
    },
  },
  {
    emoji: '❄️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sabah 06.30: kar tatili açıklandı!',
      en: "6:30 a.m.: it's a snow day!",
      de: '6:30 Uhr: schulfrei wegen Schnee!',
      ar: 'السادسة والنصف صباحًا: إجازة بسبب الثلج!',
      fr: "6 h 30 : pas d'école, il a neigé !",
      es: '¡Son las 6:30 y suspenden las clases por nieve!',
      ja: '朝6:30：大雪で休校決定！',
      ko: '오전 6:30: 폭설 휴교 발표!',
    },
  },
  {
    emoji: '🔌',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kütüphanede prizin yanındaki masa boş!',
      en: 'The library table by the outlet is free!',
      de: 'Der Bibliothekstisch an der Steckdose ist frei!',
      ar: 'طاولة المكتبة بجانب المقبس شاغرة!',
      fr: 'À la BU, la table près de la prise est libre !',
      es: '¡La mesa junto al enchufe de la biblioteca está libre!',
      ja: '図書館のコンセント横の席が空いてる！',
      ko: '도서관 콘센트 옆자리가 비었다!',
    },
  },
  {
    emoji: '⭐',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ödevine altın yıldız! Hem de parlayanından',
      en: 'A gold star on your homework. The shiny kind!',
      de: 'Ein Goldstern auf deiner Hausaufgabe. Der glänzende!',
      ar: 'نجمة ذهبية على واجبك… ومن النوع اللامع!',
      fr: 'Une étoile dorée sur ton devoir. La brillante !',
      es: '¡Estrella dorada en tu tarea! De las brillantes.',
      ja: '宿題に金の星シール！しかもキラキラのやつ',
      ko: '숙제에 금별 스티커! 그것도 반짝이는 걸로',
    },
  },
  {
    emoji: '☀️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yılın son zili! Çaldığı an bırak',
      en: "The year's last bell! Let go the moment it rings",
      de: 'Die letzte Klingel des Jahres! Lass los, sobald sie läutet',
      ar: 'آخر جرس في العام! اترك إصبعك لحظة يرنّ',
      fr: "La dernière sonnerie de l'année ! Lâche quand elle sonne",
      es: '¡Último timbre del año! Suelta en cuanto suene',
      ja: '今年最後のチャイム！鳴った瞬間に離して',
      ko: '올해 마지막 종! 울리는 순간 손 떼기',
    },
  },
];

export const SCHOOL_FREEZE: readonly Draft[] = [
  // Signs
  {
    emoji: '🧪',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'LABORATUVAR',
        en: 'LABORATORY',
        de: 'LABOR',
        ar: 'المختبر',
        fr: 'LABORATOIRE',
        es: 'LABORATORIO',
        ja: '実験室',
        ko: '실험실',
      },
      small: {
        tr: 'DENEY SÜRÜYOR · DOKUNMAYIN',
        en: 'EXPERIMENT IN PROGRESS',
        de: 'VERSUCH LÄUFT · NICHT BERÜHREN',
        ar: 'تجربة جارية · لا تلمس',
        fr: 'EXPÉRIENCE EN COURS',
        es: 'EXPERIMENTO EN CURSO',
        ja: '実験中・さわらないで',
        ko: '실험 중 · 만지지 마시오',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Deney köpürmeye başladı',
      en: 'The experiment is starting to foam',
      de: 'Das Experiment fängt an zu schäumen',
      ar: 'بدأت التجربة تفور',
      fr: "L'expérience commence à mousser",
      es: 'El experimento empezó a hacer espuma',
      ja: '実験が泡立ち始めた',
      ko: '실험에서 거품이 나기 시작함',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'KURUYOR',
        en: 'DRYING',
        de: 'TROCKNET',
        ar: 'يجفّ',
        fr: 'ÇA SÈCHE',
        es: 'SECANDO',
        ja: '乾燥中',
        ko: '건조 중',
      },
      small: {
        tr: 'MAKET ÖDEVİ · DOKUNMAYIN',
        en: "SCHOOL PROJECT · DON'T TOUCH",
        de: 'SCHULPROJEKT · NICHT ANFASSEN',
        ar: 'مشروع مدرسي · لا تلمس',
        fr: 'MAQUETTE · NE PAS TOUCHER',
        es: 'MAQUETA · NO TOCAR',
        ja: '工作の宿題・さわらないで',
        ko: '만들기 숙제 · 만지지 마시오',
      },
    },
    caption: {
      tr: 'Yapıştırıcı tutana kadar kıpırdama.',
      en: "Don't move till the glue sets.",
      de: 'Keine Bewegung, bis der Kleber hält.',
      ar: 'لا تتحرك حتى يثبت الغراء.',
      fr: 'Bouge pas tant que la colle a pas pris.',
      es: 'No te muevas hasta que pegue.',
      ja: '接着剤が乾くまで動かないで。',
      ko: '풀이 마를 때까지 움직이지 마세요.',
    },
    headline: {
      tr: 'Maket ödevin hâlâ kuruyor',
      en: 'Your school project is still drying',
      de: 'Dein Schulprojekt trocknet noch',
      ar: 'مشروعك المدرسي ما زال يجف',
      fr: "Ta maquette n'a pas fini de sécher",
      es: 'Tu maqueta todavía se está secando',
      ja: '工作の宿題がまだ乾いてない',
      ko: '만들기 숙제가 아직 마르는 중',
    },
  },
  {
    emoji: '✍️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SÜRE BİTTİ',
        en: "TIME'S UP",
        de: 'ZEIT UM',
        ar: 'انتهى الوقت',
        fr: 'TERMINÉ',
        es: 'SE ACABÓ',
        ja: '時間切れ',
        ko: '시간 종료',
      },
      small: {
        tr: 'KALEMLERİ BIRAKIN',
        en: 'PENCILS DOWN',
        de: 'STIFTE WEG',
        ar: 'ضعوا الأقلام',
        fr: 'POSEZ VOS STYLOS',
        es: 'DEJEN LOS LÁPICES',
        ja: '筆記用具を置いて',
        ko: '펜을 내려놓으시오',
      },
    },
    caption: {
      tr: 'Son harfi bile yazma.',
      en: 'Not one more letter.',
      de: 'Kein Buchstabe mehr.',
      ar: 'ولا حرفًا واحدًا بعد.',
      fr: 'Pas une lettre de plus.',
      es: 'Ni una letra más.',
      ja: 'あと一文字も書かないで。',
      ko: '한 글자도 더 쓰지 마세요.',
    },
    headline: {
      tr: 'Hoca “kalemler masaya” dedi',
      en: 'Teacher: “Pencils down!”',
      de: 'Lehrer: „Stifte weg!“',
      ar: 'المعلم: «ضعوا الأقلام!»',
      fr: 'Le prof : « Posez vos stylos ! »',
      es: 'El profe: “¡Lápices abajo!”',
      ja: '先生「ペンを置いて」',
      ko: '선생님: “펜 내려놓으세요”',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'SAHNE',
        en: 'STAGE',
        de: 'BÜHNE',
        ar: 'المسرح',
        fr: 'SCÈNE',
        es: 'ESCENARIO',
        ja: 'ステージ',
        ko: '무대',
      },
      small: {
        tr: 'GÖSTERİ BAŞLADI',
        en: 'SHOW IN PROGRESS',
        de: 'VORSTELLUNG LÄUFT',
        ar: 'العرض بدأ',
        fr: 'SPECTACLE EN COURS',
        es: 'FUNCIÓN EN CURSO',
        ja: '上演中',
        ko: '공연 중',
      },
    },
    caption: {
      tr: 'Ağaçlar kıpırdamaz.',
      en: "Trees don't move.",
      de: 'Bäume bewegen sich nicht.',
      ar: 'الأشجار لا تتحرك.',
      fr: 'Un arbre, ça bouge pas.',
      es: 'Los árboles no se mueven.',
      ja: '木は動かない。',
      ko: '나무는 움직이지 않아요.',
    },
    headline: {
      tr: 'Okul oyununda ağaç rolündesin',
      en: "You're a tree in the school play",
      de: 'Du spielst im Schultheater einen Baum',
      ar: 'دورك في مسرحية المدرسة: شجرة',
      fr: "Pièce de l'école : tu joues un arbre",
      es: 'Eres un árbol en la obra de la escuela',
      ja: '学芸会で木の役を演じてる',
      ko: '학예회에서 나무 역할 중',
    },
  },
  // Security cameras
  {
    emoji: '📱',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: '9-B SINIFI',
        en: 'ROOM 9B',
        de: 'KLASSE 9B',
        ar: 'الصف 9 ب',
        fr: 'SALLE 9B',
        es: 'AULA 9B',
        ja: '1年B組',
        ko: '1학년 2반',
      },
    },
    caption: {
      tr: 'Seninki elinde. Kıpırdama.',
      en: 'Yours is in your hand. Freeze.',
      de: 'Deins ist in deiner Hand. Stillhalten.',
      ar: 'هاتفك في يدك. لا تتحرك.',
      fr: 'Le tien est dans ta main. Bouge pas.',
      es: 'El tuyo está en tu mano. Quieto.',
      ja: 'あなたのスマホは手の中。動かないで。',
      ko: '폰은 아직 손에 있어요. 움직이지 마세요.',
    },
    headline: {
      tr: 'Hoca telefonları topluyor',
      en: "Teacher's collecting phones",
      de: 'Die Lehrerin sammelt Handys ein',
      ar: 'المعلم يجمع الهواتف',
      fr: 'La prof ramasse les portables',
      es: 'El profe está recogiendo los teléfonos',
      ja: '先生がスマホを回収中',
      ko: '선생님이 휴대폰을 걷는 중',
    },
  },
  {
    emoji: '🧑‍🏫',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'MATEMATİK DERSİ',
        en: 'MATH CLASS',
        de: 'MATHESTUNDE',
        ar: 'حصة الرياضيات',
        fr: 'COURS DE MATHS',
        es: 'MATEMÁTICAS',
        ja: '数学の授業',
        ko: '수학 시간',
      },
    },
    caption: {
      tr: 'Defterini okuyormuş gibi yap.',
      en: 'Look busy. Stare at your notebook.',
      de: 'Tu so, als würdest du ins Heft schauen.',
      ar: 'تظاهر بأنك تقرأ دفترك.',
      fr: 'Fais semblant de lire ton cahier.',
      es: 'Haz como que lees tu cuaderno.',
      ja: 'ノートを読んでるふりをして。',
      ko: '공책 보는 척하세요.',
    },
    headline: {
      tr: 'Hoca tahtaya kaldıracak birini arıyor',
      en: "Teacher's picking someone for the board",
      de: 'Der Lehrer sucht jemanden für die Tafel',
      ar: 'المعلم يبحث عمّن يخرج إلى السبورة',
      fr: 'Le prof cherche qui envoyer au tableau',
      es: 'El profe busca quién pase a la pizarra',
      ja: '先生が黒板に当てる人を探してる',
      ko: '선생님이 발표할 사람을 고르는 중',
    },
  },
  {
    emoji: '🤝',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÖĞRETMENLER ODASI',
        en: "TEACHERS' LOUNGE",
        de: 'LEHRERZIMMER',
        ar: 'غرفة المعلمين',
        fr: 'SALLE DES PROFS',
        es: 'SALA DE PROFESORES',
        ja: '職員室',
        ko: '교무실',
      },
    },
    caption: {
      tr: 'Sadece gülümse. Kıpırdama.',
      en: "Just smile. Don't move.",
      de: 'Nur lächeln. Nicht bewegen.',
      ar: 'ابتسم فقط. لا تتحرك.',
      fr: 'Souris. Et bouge pas.',
      es: 'Solo sonríe. No te muevas.',
      ja: '笑顔で。動かないで。',
      ko: '웃기만 하세요. 움직이지 마세요.',
    },
    headline: {
      tr: 'Öğretmenin annenle konuşuyor',
      en: 'Your teacher is talking to your mom',
      de: 'Deine Lehrerin spricht mit deiner Mutter',
      ar: 'معلمتك تتحدث مع أمك',
      fr: 'Ta prof parle avec ta mère',
      es: 'Tu profe está hablando con tu mamá',
      ja: '担任がお母さんと話してる',
      ko: '선생님이 엄마랑 이야기하는 중',
    },
  },
  {
    emoji: '🕵️',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'SINAV SALONU',
        en: 'EXAM HALL',
        de: 'PRÜFUNGSSAAL',
        ar: 'قاعة الامتحان',
        fr: "SALLE D'EXAMEN",
        es: 'SALA DE EXAMEN',
        ja: '試験会場',
        ko: '시험장',
      },
    },
    caption: {
      tr: 'Bir şey yapmadın. Yine de kıpırdama.',
      en: "You did nothing. Still, don't move.",
      de: 'Du hast nichts getan. Trotzdem: still.',
      ar: 'لم تفعل شيئًا، لكن لا تتحرك.',
      fr: "T'as rien fait. Bouge pas quand même.",
      es: 'No hiciste nada. Igual, no te muevas.',
      ja: '何もしてない。それでも動かないで。',
      ko: '아무것도 안 했어요. 그래도 움직이지 마세요.',
    },
    headline: {
      tr: 'Gözetmen tam arkanda durdu',
      en: 'The proctor stopped right behind you',
      de: 'Die Aufsicht bleibt hinter dir stehen',
      ar: 'المراقب توقّف خلفك تمامًا',
      fr: "Le surveillant s'arrête derrière toi",
      es: 'El vigilante se detuvo detrás de ti',
      ja: '試験監督が真後ろで止まった',
      ko: '감독관이 바로 뒤에 멈췄다',
    },
  },
];
