import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';
import { HANDS_OFF } from '../classic';

/**
 * School: classes, exams, homework, teachers, group projects, the school bus, graduation.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const SCHOOL_SKIP: readonly Draft[] = [
  // Scenes
  {
    emoji: '🎒',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Çantada bütün kitaplar var. Bugünkü hariç.',
      en: "Every book's in my backpack. Except today's.",
      de: 'Alle Bücher im Rucksack. Außer dem von heute.',
      ar: 'كل الكتب في حقيبتي… إلا كتاب اليوم',
      fr: "Tous mes livres dans le sac. Sauf celui d'aujourd'hui.",
      es: 'Todos los libros en la mochila. Menos el de hoy.',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Zil çaldı. Hoca: “Zil benim için çalar.”',
      en: "Bell rings. Teacher: “The bell doesn't dismiss you, I do.”",
      de: 'Es klingelt. Lehrer: „Die Klingel ist für mich.“',
      ar: 'رنّ الجرس، فقال المعلم: «الجرس لي، لا لكم»',
      fr: "Ça sonne. Le prof : « La sonnerie, c'est pour moi. »",
      es: 'Suena el timbre. El profe: “El timbre es para mí”.',
    },
  },
  {
    emoji: '🧮',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Okul bitti ama x’i hâlâ bulamadım',
      en: "School's long over. Still haven't found x.",
      de: 'Schule längst vorbei. x immer noch nicht gefunden.',
      ar: 'أنهيت المدرسة منذ زمن، وما زلت أبحث عن س',
      fr: "L'école, c'est fini. Toujours pas trouvé x.",
      es: 'Terminé la escuela y sigo sin encontrar la x.',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Servis beni bekledi. 30 kişi de beni izledi.',
      en: 'The bus waited for me. So did 30 staring kids.',
      de: 'Der Schulbus hat gewartet. 30 Kinder haben gestarrt.',
      ar: 'انتظرتني حافلة المدرسة… و30 طالبًا يحدّقون بي',
      fr: "Le car m'a attendu. 30 élèves m'ont regardé monter.",
      es: 'El bus escolar me esperó. Y 30 chicos me miraron.',
    },
  },
  {
    emoji: '🖍️',
    user: ACCOUNTS.school,
    body: { format: 'scene' },
    caption: {
      tr: 'Önemli yerleri işaretledim. Yani hepsini.',
      en: 'Highlighted the important parts. So… all of it.',
      de: 'Nur das Wichtige markiert. Also alles.',
      ar: 'ظلّلت المهم فقط… أي الصفحة كلها',
      fr: "J'ai surligné l'essentiel. Donc tout.",
      es: 'Subrayé solo lo importante. O sea, todo.',
    },
  },
  {
    emoji: '📄',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Biri ek kâğıt istedi. Ben hâlâ 1. sorudayım.',
      en: "Someone asked for extra paper. I'm still on question 1.",
      de: 'Jemand will ein Extrablatt. Ich bin noch bei Aufgabe 1.',
      ar: 'أحدهم طلب ورقة إضافية، وأنا ما زلت عند السؤال الأول',
      fr: "Quelqu'un demande une feuille en plus. Moi : question 1.",
      es: 'Alguien pidió otra hoja. Yo sigo en la pregunta 1.',
    },
  },
  {
    emoji: '🎓',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Kepimi havaya attım. Hâlâ arıyorum.',
      en: 'Tossed my grad cap in the air. Still looking for it.',
      de: 'Abschlusshut in die Luft geworfen. Ich suche ihn noch.',
      ar: 'رميت قبعة التخرج في الهواء… وما زلت أبحث عنها',
      fr: 'Chapeau de diplômé lancé en l’air. Introuvable depuis.',
      es: 'Lancé el birrete al aire. Todavía lo busco.',
    },
  },
  // Chats
  {
    emoji: '🎉',
    user: ACCOUNTS.school,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sınıf grubu',
        en: 'Class chat',
        de: 'Klassenchat',
        ar: 'مجموعة الصف',
        fr: 'Groupe de la classe',
        es: 'Grupo de la clase',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'hoca bugün gelmiyormuş!!',
            en: "teacher's not coming today!!",
            de: 'die Lehrerin kommt heute nicht!!',
            ar: 'المعلم لن يأتي اليوم!!',
            fr: "le prof vient pas aujourd'hui !!",
            es: '¡¡el profe no viene hoy!!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'BOŞ DERS!!',
            en: 'FREE PERIOD!!',
            de: 'FREISTUNDE!!',
            ar: 'حصة فراغ!!',
            fr: 'PAS COURS !!',
            es: '¡¡HORA LIBRE!!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yerine müdür giriyormuş',
            en: "the principal's subbing instead",
            de: 'der Direktor vertritt sie',
            ar: 'والمدير سيحضر بدلًا منه',
            fr: 'le proviseur le remplace',
            es: 'viene el director a cubrirlo',
          },
        },
      ],
    },
    caption: {
      tr: 'Sevinç 40 saniye sürdü',
      en: 'The joy lasted 40 seconds',
      de: 'Die Freude hielt 40 Sekunden',
      ar: 'دامت الفرحة 40 ثانية',
      fr: 'La joie a duré 40 secondes',
      es: 'La alegría duró 40 segundos',
    },
  },
  {
    emoji: '➗',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba ödevde bir soru var, bakar mısın?',
            en: 'dad can you check one math question?',
            de: 'Papa, schaust du dir eine Matheaufgabe an?',
            ar: 'أبي، هل تنظر في مسألة من واجبي؟',
            fr: 'papa, tu peux regarder un exo de maths ?',
            es: 'papá, ¿me ayudas con un problema?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'gönder, çocuk oyuncağı',
            en: "send it, that's kid stuff",
            de: 'schick her, Kinderkram',
            ar: 'أرسلها، إنها لعبة أطفال',
            fr: "envoie, c'est un jeu d'enfant",
            es: 'mándalo, es pan comido',
          },
        },
        {
          from: 'them',
          text: { tr: '…', en: '…', de: '…', ar: '…', fr: '…', es: '…' },
        },
        {
          from: 'them',
          text: {
            tr: 'bu yeni sistem, annene sor',
            en: 'this is new math. ask your mom',
            de: 'das ist neue Mathe. frag Mama',
            ar: 'هذا منهج جديد، اسأل أمك',
            fr: "c'est les nouvelles maths, demande à maman",
            es: 'eso es matemática nueva, pregúntale a mamá',
          },
        },
      ],
    },
    caption: {
      tr: 'Babam 4. sınıf sorusuna yenildi',
      en: 'Dad lost to 4th-grade math',
      de: 'Papa hat gegen Mathe der 4. Klasse verloren',
      ar: 'أبي هُزم أمام رياضيات الصف الرابع',
      fr: 'Papa, battu par les maths de CM1',
      es: 'Papá perdió contra las matemáticas de 4.º',
    },
  },
  {
    emoji: '🥳',
    user: ACCOUNTS.school,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ders çalışma grubu',
        en: 'Study group',
        de: 'Lerngruppe',
        ar: 'مجموعة المذاكرة',
        fr: 'Groupe de révisions',
        es: 'Grupo de estudio',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'akşam bizde ders çalışıyoruz, ciddi!',
            en: 'study night at my place. serious!',
            de: 'heute Abend Lernen bei mir. ernsthaft!',
            ar: 'سنذاكر عندي الليلة، وبجدية!',
            fr: 'révisions chez moi ce soir. sérieux !',
            es: 'esta noche estudiamos en mi casa. ¡en serio!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tamam, ben cips getiririm',
            en: "ok, I'll bring chips",
            de: 'ok, ich bring Chips mit',
            ar: 'حسنًا، سأحضر رقائق البطاطس',
            fr: "ok, j'apporte des chips",
            es: 'ok, yo llevo snacks',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ben de masa oyunu getiririm',
            en: "I'll bring a board game",
            de: 'ich bring ein Brettspiel',
            ar: 'وأنا سأحضر لعبة لوحية',
            fr: 'moi, un jeu de société',
            es: 'yo, un juego de mesa',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'hoparlör de bende',
            en: "I've got the speaker",
            de: 'ich hab die Musikbox',
            ar: 'والسماعة عليّ',
            fr: "moi, l'enceinte",
            es: 'yo llevo el altavoz',
          },
        },
      ],
    },
    caption: {
      tr: 'Kitap getiren yok ama',
      en: "Nobody's bringing a book, though",
      de: 'Ein Buch bringt aber keiner mit',
      ar: 'ولا أحد سيحضر كتابًا',
      fr: "Mais personne n'apporte de livre",
      es: 'Pero nadie lleva un libro',
    },
  },
  {
    emoji: '🙃',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: '4. soru nereden çıktı ya?',
            en: 'where did question 4 even come from??',
            de: 'wo kam Aufgabe 4 denn her??',
            ar: 'من أين جاء السؤال الرابع؟؟',
            fr: "la question 4, elle sort d'où ??",
            es: '¿¿de dónde salió la pregunta 4??',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hocanın “bu çıkmaz” dediği yerden',
            en: "from the part he said “won't be on it”",
            de: 'aus dem Teil, der „nicht drankommt“',
            ar: 'من الجزء الذي قال عنه «لن يأتي»',
            fr: 'du chapitre qui « tombera pas »',
            es: 'de lo que el profe dijo que “no entraba”',
          },
        },
      ],
    },
    caption: {
      tr: 'Hoca ters psikoloji ustası',
      en: 'Reverse psychology, teacher edition',
      de: 'Umgekehrte Psychologie, Lehrer-Edition',
      ar: 'المعلم أستاذ في علم النفس العكسي',
      fr: 'Psychologie inversée, version prof',
      es: 'Psicología inversa, versión profe',
    },
  },
  // Polls
  {
    emoji: '🙋',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Hoca “soru var mı?” dedi. Sen:',
        en: 'Teacher asks, “Any questions?” You:',
        de: 'Lehrer fragt: „Noch Fragen?“ Du:',
        ar: 'سأل المعلم: «هل من أسئلة؟» وأنت:',
        fr: 'Le prof : « Des questions ? » Toi :',
        es: 'El profe: “¿Alguna pregunta?”. Tú:',
      },
      options: [
        {
          tr: 'Soru sorarım',
          en: 'Ask one',
          de: 'Ich frage was',
          ar: 'أطرح سؤالًا',
          fr: 'Je pose une question',
          es: 'Pregunto algo',
        },
        {
          tr: 'Zili beklerim',
          en: 'Wait for the bell',
          de: 'Ich warte auf den Gong',
          ar: 'أنتظر الجرس',
          fr: "J'attends la sonnerie",
          es: 'Espero el timbre',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Her soru teneffüsten 5 dakika yer',
      en: 'Every question eats 5 minutes of break',
      de: 'Jede Frage kostet 5 Minuten Pause',
      ar: 'كل سؤال يأكل 5 دقائق من الاستراحة',
      fr: 'Chaque question mange 5 minutes de récré',
      es: 'Cada pregunta se come 5 minutos del recreo',
    },
  },
  {
    emoji: '🖊️',
    user: ACCOUNTS.school,
    body: {
      format: 'poll',
      question: {
        tr: 'Ders çalışmaya oturdun. İlk 30 dakika:',
        en: 'You sit down to study. First 30 minutes:',
        de: 'Du setzt dich zum Lernen. Erste 30 Minuten:',
        ar: 'جلست لتذاكر. أول 30 دقيقة:',
        fr: 'Tu te mets à réviser. Les 30 premières minutes :',
        es: 'Te sientas a estudiar. Primeros 30 minutos:',
      },
      options: [
        { tr: 'Çalışırım', en: 'I study', de: 'Ich lerne', ar: 'أذاكر', fr: 'Je révise', es: 'Estudio' },
        {
          tr: 'Masayı düzenlerim',
          en: 'Tidy the desk',
          de: 'Schreibtisch aufräumen',
          ar: 'أرتّب المكتب',
          fr: 'Je range le bureau',
          es: 'Ordeno el escritorio',
        },
        {
          tr: 'Renkli kalem dizerim',
          en: 'Sort pens by color',
          de: 'Stifte nach Farbe',
          ar: 'أرتّب الأقلام بالألوان',
          fr: 'Je trie mes stylos',
          es: 'Ordeno los colores',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Masa hazır, kalemler hazır. Ben değilim.',
      en: "Desk's ready. Pens are ready. I'm not.",
      de: 'Tisch bereit. Stifte bereit. Ich nicht.',
      ar: 'المكتب جاهز، والأقلام جاهزة… وأنا لا',
      fr: 'Bureau prêt. Stylos prêts. Moi, non.',
      es: 'Escritorio listo. Lápices listos. Yo, no.',
    },
  },
  {
    emoji: '🙉',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sınav bitti, herkes cevapları konuşuyor. Sen:',
        en: "Exam's over. Everyone's comparing answers. You:",
        de: 'Prüfung vorbei, alle vergleichen. Du:',
        ar: 'انتهى الامتحان والجميع يقارن الإجابات. وأنت:',
        fr: "Fin de l'exam, tout le monde compare. Toi :",
        es: 'Acabó el examen y todos comparan respuestas. Tú:',
      },
      options: [
        {
          tr: 'Karşılaştırırım',
          en: 'Compare mine',
          de: 'Ich vergleiche mit',
          ar: 'أقارن إجاباتي',
          fr: 'Je compare',
          es: 'Comparo las mías',
        },
        {
          tr: 'Kulaklarımı kapatırım',
          en: 'Cover my ears',
          de: 'Ohren zuhalten',
          ar: 'أسدّ أذنيّ',
          fr: 'Oreilles bouchées',
          es: 'Me tapo los oídos',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Bilmemek daha huzurlu',
      en: 'Ignorance is bliss',
      de: 'Was ich nicht weiß, macht mich nicht heiß',
      ar: 'في عدم المعرفة راحة',
      fr: "Moins j'en sais, mieux je me porte",
      es: 'Ojos que no ven, corazón que no siente',
    },
  },
  // Charts
  {
    emoji: '🕯️',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'DERS ÇALIŞMA İSTEĞİM',
        en: 'MY URGE TO STUDY',
        de: 'MEINE LERNLUST',
        ar: 'رغبتي في المذاكرة',
        fr: 'MON ENVIE DE RÉVISER',
        es: 'MIS GANAS DE ESTUDIAR',
      },
      value: null,
      shape: 'spike',
      axis: 'days',
    },
    caption: {
      tr: 'Sınavdan önceki gece 02.00’de tavan yaptı',
      en: 'Peaked at 2 a.m. the night before the exam',
      de: 'Höhepunkt: 2 Uhr nachts vor der Prüfung',
      ar: 'بلغت ذروتها ليلة الامتحان، الساعة 2 فجرًا',
      fr: "Pic à 2 h du matin, la veille de l'exam",
      es: 'Máximo: 2 de la mañana, la víspera del examen',
    },
  },
  {
    emoji: '📔',
    user: ACCOUNTS.school,
    body: {
      format: 'chart',
      title: {
        tr: 'DEFTERİMİN DÜZENİ',
        en: 'MY NOTEBOOK NEATNESS',
        de: 'ORDNUNG IM HEFT',
        ar: 'ترتيب دفتري',
        fr: 'PROPRETÉ DE MON CAHIER',
        es: 'ORDEN DE MI CUADERNO',
      },
      value: null,
      shape: 'fall',
      axis: 'months',
    },
    caption: {
      tr: '1. sayfa sanat eseri, son sayfa hiyeroglif',
      en: 'Page 1: a masterpiece. Last page: hieroglyphs.',
      de: 'Seite 1: Kunstwerk. Letzte Seite: Hieroglyphen.',
      ar: 'الصفحة الأولى تحفة فنية، والأخيرة نقوش هيروغليفية',
      fr: "Page 1 : chef-d'œuvre. Dernière page : hiéroglyphes.",
      es: 'Página 1: obra de arte. Última: jeroglíficos.',
    },
  },
  // Receipts
  {
    emoji: '🖨️',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'FOTOKOPİ MERKEZİ',
        en: 'COPY SHOP',
        de: 'COPYSHOP',
        ar: 'مركز تصوير',
        fr: 'REPROGRAPHIE',
        es: 'CENTRO DE COPIADO',
      },
      items: [
        {
          tr: 'DERS NOTU (240 SAYFA)',
          en: 'CLASS NOTES (240 PG)',
          de: 'SKRIPT (240 SEITEN)',
          ar: 'ملخص المادة (240 صفحة)',
          fr: 'POLY DE COURS (240 P.)',
          es: 'APUNTES (240 PÁGINAS)',
        },
      ],
    },
    caption: {
      tr: 'Fotokopisini aldım, öğrenmiş sayılırım',
      en: 'Copied it. That counts as studying, right?',
      de: 'Kopiert ist halb gelernt.',
      ar: 'صوّرتها، فكأنني ذاكرتها',
      fr: 'Photocopié, donc à moitié révisé.',
      es: 'Fotocopiado, o sea, casi aprendido.',
    },
  },
  {
    emoji: '📐',
    user: ACCOUNTS.school,
    body: {
      format: 'receipt',
      store: {
        tr: 'KIRTASİYE',
        en: 'STATIONERY STORE',
        de: 'SCHREIBWAREN',
        ar: 'قرطاسية',
        fr: 'PAPETERIE',
        es: 'PAPELERÍA',
      },
      items: [
        {
          tr: 'PERGEL SETİ (20 PARÇA)',
          en: 'GEOMETRY SET (20 PCS)',
          de: 'ZIRKELSET (20 TEILE)',
          ar: 'طقم هندسة (20 قطعة)',
          fr: 'GÉOMÉTRIE (20 PIÈCES)',
          es: 'SET DE GEOMETRÍA (20)',
        },
      ],
    },
    caption: {
      tr: '4 yılda kullandığım tek parça: cetvel',
      en: '4 years. The only piece I used: the ruler.',
      de: 'In 4 Jahren benutzt: nur das Lineal',
      ar: 'في 4 سنوات لم أستخدم منه إلا المسطرة',
      fr: "En 4 ans, j'ai utilisé la règle. Point.",
      es: 'En 4 años solo usé la regla',
    },
  },
  // Facts
  {
    emoji: '💡',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'kez doğru cevabı sınavdan çıkar çıkmaz hatırladın',
        en: 'times you remembered the answer right after the exam',
        de: 'Mal fiel dir die Antwort direkt nach der Prüfung ein',
        ar: 'مرات تذكرت فيها الإجابة فور خروجك من الامتحان',
        fr: "fois où la réponse t'est revenue juste après l'exam",
        es: 'veces recordaste la respuesta justo al salir del examen',
      },
    },
    caption: {
      tr: 'Cevaplar koridorda bekliyor',
      en: 'The answers wait in the hallway',
      de: 'Die Antworten warten im Flur',
      ar: 'الإجابات تنتظرك في الممر',
      fr: 'Les réponses attendent dans le couloir',
      es: 'Las respuestas esperan en el pasillo',
    },
  },
  {
    emoji: '⏰',
    user: ACCOUNTS.school,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU DERSTE',
        en: 'IN THIS CLASS',
        de: 'IN DIESER STUNDE',
        ar: 'في هذه الحصة',
        fr: 'PENDANT CE COURS',
        es: 'EN ESTA CLASE',
      },
      big: { tr: '12', en: '12', de: '12', ar: '12', fr: '12', es: '12' },
      text: {
        tr: 'kez dersin bitmesine kaç dakika kaldığına baktın',
        en: 'times you checked how many minutes were left',
        de: 'Mal geschaut, wie viele Minuten noch übrig sind',
        ar: 'مرة نظرت فيها كم دقيقة بقيت على نهاية الحصة',
        fr: 'fois où tu as vérifié combien de minutes il restait',
        es: 'veces miraste cuántos minutos faltaban',
      },
    },
    caption: {
      tr: 'Saat bakıldıkça yavaşlar',
      en: 'A watched clock never moves',
      de: 'Beobachtete Uhren gehen langsamer',
      ar: 'الساعة تبطئ كلما نظرت إليها',
      fr: "Une horloge qu'on regarde ralentit",
      es: 'El reloj se frena si lo miras',
    },
  },
  {
    emoji: '🧹',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'SINAV HAFTASI',
        en: 'EXAM WEEK',
        de: 'PRÜFUNGSWOCHE',
        ar: 'أسبوع الامتحانات',
        fr: "SEMAINE D'EXAMS",
        es: 'SEMANA DE EXÁMENES',
      },
      big: { tr: '4', en: '4', de: '4', ar: '4', fr: '4', es: '4' },
      text: {
        tr: 'kez odanı topladın; ders kitabın hâlâ kapalı',
        en: 'times you cleaned your room. Textbook: still closed.',
        de: 'Mal das Zimmer aufgeräumt. Das Lehrbuch ist noch zu.',
        ar: 'مرات رتّبت غرفتك، والكتاب ما زال مغلقًا',
        fr: 'fois où tu as rangé ta chambre. Le manuel : toujours fermé.',
        es: 'veces ordenaste tu cuarto. El libro sigue cerrado.',
      },
    },
    caption: {
      tr: 'Odan hiç bu kadar temiz olmamıştı',
      en: 'Your room has never been this clean',
      de: 'So sauber war dein Zimmer noch nie',
      ar: 'لم تكن غرفتك يومًا بهذه النظافة',
      fr: "Ta chambre n'a jamais été aussi propre",
      es: 'Tu cuarto nunca estuvo tan limpio',
    },
  },
  {
    emoji: '⌛',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '15', en: '15', de: '15', ar: '15', fr: '15', es: '15' },
      text: {
        tr: 'dakikadır hoca yok; kimse ilk kalkan olmak istemiyor',
        en: 'minutes, no professor. Nobody wants to leave first.',
        de: 'Minuten kein Prof. Keiner will als Erster gehen.',
        ar: 'دقيقة ولا أستاذ، ولا أحد يريد أن يغادر أولًا',
        fr: "minutes sans prof. Personne n'ose partir en premier.",
        es: 'minutos sin profe. Nadie quiere irse primero.',
      },
    },
    caption: {
      tr: '16. dakikada kapı açıldı',
      en: 'Minute 16: the door opens',
      de: 'Minute 16: Die Tür geht auf',
      ar: 'وفي الدقيقة 16 انفتح الباب',
      fr: "16e minute : la porte s'ouvre",
      es: 'Minuto 16: se abre la puerta',
    },
  },
  // Tier lists
  {
    emoji: '🐕',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ÖDEV BAHANESİ TIER LIST',
        en: 'HOMEWORK EXCUSE TIER LIST',
        de: 'AUSREDEN-TIER-LIST',
        ar: 'تصنيف أعذار الواجب',
        fr: 'TIER LIST DES EXCUSES',
        es: 'TIER LIST DE EXCUSAS',
      },
      rows: [['🐕'], ['💻', '🖨️'], ['🐈', '🌬️'], ['🤷']],
    },
    caption: {
      tr: 'Köpeğim yok. Bahanem var.',
      en: 'No dog. Still using the excuse.',
      de: 'Kein Hund. Aber die Ausrede zieht.',
      ar: 'لا أملك كلبًا… لكن العذر جاهز',
      fr: "Pas de chien. L'excuse marche quand même.",
      es: 'No tengo perro. La excusa, sí.',
    },
  },
  {
    emoji: '🥪',
    user: ACCOUNTS.school,
    body: {
      format: 'tier',
      title: {
        tr: 'KANTİN TIER LIST',
        en: 'CAFETERIA TIER LIST',
        de: 'KANTINEN-TIER-LIST',
        ar: 'تصنيف المقصف',
        fr: 'TIER LIST DE LA CANTINE',
        es: 'TIER LIST DE LA CAFETERÍA',
      },
      rows: [['🥪', '🥯'], ['🧃', '🍫'], ['🍌', '🍪'], ['🥗']],
    },
    caption: {
      tr: 'Tost S. Kokusu 3. kata kadar çıkıyor.',
      en: 'Grilled cheese is S. You can smell it from the 3rd floor.',
      de: 'Toast ist S. Man riecht ihn bis in den 3. Stock.',
      ar: 'الشطيرة في القمة، ورائحتها تصل إلى الطابق الثالث',
      fr: "Le croque est S. On le sent jusqu'au 3e.",
      es: 'El sándwich es S. Se huele hasta el 3.er piso.',
    },
  },
  // Lock screens
  {
    emoji: '😬',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '📝',
        app: {
          tr: 'Okul portalı',
          en: 'School portal',
          de: 'Schulportal',
          ar: 'بوابة المدرسة',
          fr: 'Espace élèves',
          es: 'Portal escolar',
        },
        text: {
          tr: 'Yeni not girildi: Matematik yazılısı',
          en: 'New grade posted: Math test',
          de: 'Neue Note eingetragen: Mathearbeit',
          ar: 'رُصدت درجة جديدة: اختبار الرياضيات',
          fr: 'Nouvelle note : contrôle de maths',
          es: 'Nueva nota: examen de matemáticas',
        },
      },
    },
    caption: {
      tr: 'Açmadan önce 10 dakika tavana baktım',
      en: 'Stared at the ceiling 10 minutes first',
      de: 'Erst mal 10 Minuten an die Decke gestarrt',
      ar: 'حدّقت في السقف 10 دقائق قبل أن أفتحها',
      fr: "10 minutes à fixer le plafond avant d'ouvrir",
      es: 'Miré el techo 10 minutos antes de abrirla',
    },
  },
  {
    emoji: '🖱️',
    user: ACCOUNTS.school,
    body: {
      format: 'notifications',
      first: {
        icon: '🎓',
        app: {
          tr: 'Üniversite',
          en: 'University',
          de: 'Universität',
          ar: 'الجامعة',
          fr: 'Université',
          es: 'Universidad',
        },
        text: {
          tr: 'Ders kaydı 09.00’da başlıyor',
          en: 'Course registration opens at 9:00',
          de: 'Kurswahl startet um 9:00 Uhr',
          ar: 'يبدأ تسجيل المقررات الساعة 9:00',
          fr: 'Inscriptions aux cours à 9 h',
          es: 'Inscripción de materias: 9:00',
        },
      },
    },
    caption: {
      tr: 'Alarm 08.55’te çaldı, site 09.01’de çöktü',
      en: 'Alarm at 8:55. Site crashed at 9:01.',
      de: 'Wecker um 8:55. Um 9:01 war die Seite down.',
      ar: 'رنّ المنبه 8:55، وتعطّل الموقع 9:01',
      fr: 'Réveil à 8 h 55. Site planté à 9 h 01.',
      es: 'Alarma a las 8:55. La web se cayó a las 9:01.',
    },
  },
  // Quote cards
  {
    emoji: '🧠',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bilgi güçtür. Benimki sınavdan çıkınca sıfırlanıyor.',
        en: 'Knowledge is power. Mine resets the minute the exam ends.',
        de: 'Wissen ist Macht. Meins löscht sich nach der Prüfung.',
        ar: 'المعرفة قوة. أما معرفتي فتُمحى بعد الامتحان مباشرة.',
        fr: "Le savoir, c'est le pouvoir. Le mien s'efface après l'exam.",
        es: 'El saber es poder. El mío se borra al salir del examen.',
      },
    },
    caption: {
      tr: 'Bir sonraki sınava yeniden yüklenir',
      en: 'Reinstalling before the next exam',
      de: 'Neustart vor der nächsten Prüfung',
      ar: 'ويُعاد تحميلها قبل الامتحان القادم',
      fr: 'Réinstallation avant le prochain exam',
      es: 'Se reinstala antes del próximo examen',
    },
  },
  {
    emoji: '📽️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her son yeni bir başlangıçtır. — Hocanın son slaytı',
        en: "Every ending is a new beginning. — The professor's last slide",
        de: 'Jedes Ende ist ein neuer Anfang. — Die letzte Folie vom Prof',
        ar: 'كل نهاية بداية جديدة. — الشريحة الأخيرة للأستاذ',
        fr: 'Chaque fin est un nouveau départ. — La dernière diapo du prof',
        es: 'Cada final es un nuevo comienzo. — La última diapositiva del profe',
      },
    },
    caption: {
      tr: 'Son slayttan sonra 14 slayt daha geldi',
      en: 'After the last slide came 14 more',
      de: 'Nach der letzten Folie kamen noch 14',
      ar: 'وبعد الشريحة الأخيرة جاءت 14 شريحة أخرى',
      fr: 'Après la dernière diapo, 14 autres',
      es: 'Tras la última diapositiva, vinieron 14 más',
    },
  },
  {
    emoji: '✏️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat bir sınavdır. Ben yine kalemsiz geldim.',
        en: 'Life is a test. And I forgot my pencil again.',
        de: 'Das Leben ist eine Prüfung. Und ich hab wieder keinen Stift.',
        ar: 'الحياة امتحان، وأنا جئت بلا قلم كالعادة.',
        fr: "La vie est un examen. Et j'ai encore oublié mon stylo.",
        es: 'La vida es un examen. Y otra vez vine sin lápiz.',
      },
    },
    caption: {
      tr: 'Yan sıradaki 4 yıldır bana kalem veriyor',
      en: "My desk buddy's been lending me pens for 4 years",
      de: 'Mein Banknachbar leiht mir seit 4 Jahren Stifte',
      ar: 'زميلي يعيرني قلمه منذ 4 سنوات',
      fr: 'Mon voisin me prête un stylo depuis 4 ans',
      es: 'Mi compañero me presta lápiz hace 4 años',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Asla hafife alma. — Açık kitap sınavına giren biri',
        en: 'Never underestimate anything. — Someone after an open-book exam',
        de: 'Unterschätze niemals etwas. — Jemand nach einer Open-Book-Klausur',
        ar: 'لا تستهن بشيء أبدًا. — شخص خاض امتحانًا بكتاب مفتوح',
        fr: "Ne sous-estime jamais rien. — Quelqu'un après un exam à livre ouvert",
        es: 'Nunca subestimes nada. — Alguien tras un examen a libro abierto',
      },
    },
    caption: {
      tr: 'Kitap açıktı, zihnim kapalıydı',
      en: "The book was open. My brain wasn't.",
      de: 'Das Buch war offen, mein Kopf nicht',
      ar: 'كان الكتاب مفتوحًا، وعقلي مغلقًا',
      fr: 'Le livre était ouvert. Mon cerveau, non.',
      es: 'El libro estaba abierto. Mi mente, no.',
    },
  },
];

export const SCHOOL_LIKE: readonly Draft[] = [
  // Scenes
  {
    emoji: '🌋',
    user: ACCOUNTS.efe,
    body: { format: 'scene' },
    caption: {
      tr: 'yanardağ deneyim çalıştı!! her yer köpük',
      en: 'my volcano project worked!! foam everywhere',
      de: 'mein vulkan-experiment hat geklappt!! überall schaum',
      ar: 'تجربة البركان نجحت!! الرغوة في كل مكان',
      fr: 'mon volcan a marché !! de la mousse partout',
      es: '¡¡mi volcán funcionó!! hay espuma por todos lados',
    },
  },
  {
    emoji: '👵',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'anneannem 68’inde üniversiteye başladı!!',
      en: 'my grandma started college at 68!!',
      de: 'meine oma hat mit 68 ihr studium angefangen!!',
      ar: 'جدتي بدأت الجامعة في عمر 68!!',
      fr: 'ma grand-mère a commencé la fac à 68 ans !!',
      es: '¡¡mi abuela empezó la universidad a los 68!!',
    },
  },
  {
    emoji: '📊',
    user: ACCOUNTS.naz,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk sunumumu yaptım ve kimse uyumadı!!',
      en: 'gave my first presentation and nobody fell asleep!!',
      de: 'mein erstes referat und keiner ist eingeschlafen!!',
      ar: 'قدّمت أول عرض لي ولم ينم أحد!!',
      fr: "mon premier exposé et personne ne s'est endormi !!",
      es: '¡¡mi primera exposición y nadie se durmió!!',
    },
  },
  // Instant photos
  {
    emoji: '🏫',
    user: ACCOUNTS.arda,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni kampüs, yeni ben',
        en: 'new campus, new me',
        de: 'neuer campus, neues ich',
        ar: 'حرم جديد، أنا جديد',
        fr: 'nouvelle fac, nouveau moi',
        es: 'nuevo campus, nuevo yo',
      },
    },
    caption: {
      tr: 'üniversitede ilk günüm, 3 kez kayboldum',
      en: 'first day of college, got lost 3 times',
      de: 'erster tag an der uni, 3-mal verlaufen',
      ar: 'أول يوم لي في الجامعة، وتهت 3 مرات',
      fr: 'premier jour à la fac, perdu 3 fois',
      es: 'primer día en la uni, me perdí 3 veces',
    },
  },
  {
    emoji: '📜',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'panoda benim şiirim',
        en: 'my poem, pinned up',
        de: 'mein gedicht hängt',
        ar: 'قصيدتي على اللوحة',
        fr: 'mon poème affiché',
        es: 'mi poema en el mural',
      },
    },
    caption: {
      tr: 'yazdığım şiiri öğretmen panoya astı!!',
      en: 'my teacher pinned my poem on the class board!!',
      de: 'meine lehrerin hat mein gedicht aufgehängt!!',
      ar: 'المعلمة علّقت قصيدتي على لوحة الصف!!',
      fr: 'la prof a affiché mon poème en classe !!',
      es: '¡¡la profe colgó mi poema en el mural!!',
    },
  },
  {
    emoji: '🖋️',
    user: ACCOUNTS.irem,
    body: {
      format: 'polaroid',
      note: {
        tr: 'mürekkep her yerde',
        en: 'ink everywhere',
        de: 'tinte überall',
        ar: 'الحبر في كل مكان',
        fr: "de l'encre partout",
        es: 'tinta por todas partes',
      },
    },
    caption: {
      tr: 'dolma kalemle ilk sayfam, parmaklarım masmavi',
      en: 'first page with a fountain pen, fingers very blue',
      de: 'erste seite mit füller, finger jetzt blau',
      ar: 'أول صفحة بقلم الحبر، وأصابعي زرقاء تمامًا',
      fr: 'première page au stylo plume, doigts tout bleus',
      es: 'primera página con estilográfica, dedos azules',
    },
  },
  {
    emoji: '💐',
    user: ACCOUNTS.tolga,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk öğretmenim',
        en: 'my first teacher',
        de: 'meine erste lehrerin',
        ar: 'معلمتي الأولى',
        fr: 'ma maîtresse de cp',
        es: 'mi primera maestra',
      },
    },
    caption: {
      tr: '15 yıl sonra ilk öğretmenimi ziyaret ettim',
      en: 'visited my first-grade teacher, 15 years later',
      de: 'nach 15 jahren meine erste lehrerin besucht',
      ar: 'زرت معلمتي الأولى بعد 15 عامًا',
      fr: 'revu ma maîtresse de cp, 15 ans après',
      es: 'visité a mi primera maestra 15 años después',
    },
  },
  // Photo dumps
  {
    emoji: '📚',
    user: ACCOUNTS.ece,
    body: { format: 'dump', emojis: ['📚', '☕️', '🌙', '🗒️', '🥳'] },
    caption: {
      tr: 'final haftası: 12 kahve, 3 sabahlama, hepsi bitti!!',
      en: 'finals week dump: 12 coffees, 3 all-nighters, done!!',
      de: 'prüfungswoche: 12 kaffee, 3 nächte durch, geschafft!!',
      ar: 'أسبوع الامتحانات: 12 قهوة، 3 ليالٍ بلا نوم، وانتهينا!!',
      fr: "semaine d'exams : 12 cafés, 3 nuits blanches, fini !!",
      es: 'semana de exámenes: 12 cafés, 3 noches en vela, ¡¡terminé!!',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.berk,
    body: { format: 'dump', emojis: ['👕', '🖊️', '🏫', '📸', '🌞'] },
    caption: {
      tr: 'okulun son günü: gömlekler imzalandı, gözler doldu',
      en: 'last day of school: signed shirts, happy tears',
      de: 'letzter schultag: t-shirts signiert, tränen in den augen',
      ar: 'آخر يوم في المدرسة: توقيعات على القمصان، ودموع في العيون',
      fr: 'dernier jour de cours : t-shirts signés, larmes aux yeux',
      es: 'último día de clases: camisetas firmadas, ojos llorosos',
    },
  },
  {
    emoji: '🎶',
    user: ACCOUNTS.melis,
    body: { format: 'dump', emojis: ['🎶', '🚌', '🗺️', '🧃', '🍎'] },
    caption: {
      tr: 'okul gezisi dump’ı: en güzeli otobüs şarkıları',
      en: 'field trip dump: the bus songs were the best part',
      de: 'klassenfahrt-dump: das beste waren die lieder im bus',
      ar: 'رحلة المدرسة: أجمل ما فيها أغاني الحافلة',
      fr: "sortie scolaire : le mieux, c'était les chansons du car",
      es: 'excursión escolar: lo mejor fueron las canciones en el bus',
    },
  },
];

export const SCHOOL_HOLD: readonly Draft[] = [
  {
    emoji: '🔔',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir an: hoca dersi 10 dakika erken bitirdi',
      en: 'Rare moment: class let out 10 minutes early',
      de: 'Seltener Moment: 10 Minuten früher Schluss',
      ar: 'لحظة نادرة: المعلم أنهى الحصة قبل موعدها بعشر دقائق',
      fr: 'Moment rare : le cours finit 10 minutes plus tôt',
      es: 'Momento único: la clase terminó 10 minutos antes',
    },
  },
  {
    emoji: '📝',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi cümle: “Bu hafta ödev yok.”',
      en: 'Legendary words: “No homework this week.”',
      de: 'Legendärer Satz: „Diese Woche keine Hausaufgaben.“',
      ar: 'عبارة أسطورية: «لا واجبات هذا الأسبوع»',
      fr: 'Phrase légendaire : « Pas de devoirs cette semaine. »',
      es: 'Frase legendaria: “Esta semana no hay tarea”.',
    },
  },
  {
    emoji: '🎯',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'İnanılmaz! Sınavda tam çalıştığın yerler çıktı',
      en: 'Unbelievable! The exam was exactly what you studied',
      de: 'Unglaublich! Genau das kam dran, was du gelernt hast',
      ar: 'لا يُصدَّق! جاء في الامتحان ما ذاكرته بالضبط',
      fr: "Incroyable ! L'exam tombe pile sur tes révisions",
      es: '¡Increíble! En el examen vino justo lo que estudiaste',
    },
  },
  {
    emoji: '❄️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sabah 06.30: kar tatili açıklandı!',
      en: "6:30 a.m.: it's a snow day!",
      de: '6:30 Uhr: schulfrei wegen Schnee!',
      ar: 'السادسة والنصف صباحًا: إجازة بسبب الثلج!',
      fr: "6 h 30 : pas d'école, il a neigé !",
      es: '¡Son las 6:30 y suspenden las clases por nieve!',
    },
  },
  {
    emoji: '🔌',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kütüphanede prizin yanındaki masa boş!',
      en: 'The library table by the outlet is free!',
      de: 'Der Bibliothekstisch an der Steckdose ist frei!',
      ar: 'طاولة المكتبة بجانب المقبس شاغرة!',
      fr: 'À la BU, la table près de la prise est libre !',
      es: '¡La mesa junto al enchufe de la biblioteca está libre!',
    },
  },
  {
    emoji: '⭐',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Ödevine altın yıldız! Hem de parlayanından',
      en: 'A gold star on your homework. The shiny kind!',
      de: 'Ein Goldstern auf deiner Hausaufgabe. Der glänzende!',
      ar: 'نجمة ذهبية على واجبك… ومن النوع اللامع!',
      fr: 'Une étoile dorée sur ton devoir. La brillante !',
      es: '¡Estrella dorada en tu tarea! De las brillantes.',
    },
  },
  {
    emoji: '☀️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yılın son zili! Çaldığı an bırak',
      en: "The year's last bell! Let go the moment it rings",
      de: 'Die letzte Klingel des Jahres! Lass los, sobald sie läutet',
      ar: 'آخر جرس في العام! اترك إصبعك لحظة يرنّ',
      fr: "La dernière sonnerie de l'année ! Lâche quand elle sonne",
      es: '¡Último timbre del año! Suelta en cuanto suene',
    },
  },
];

export const SCHOOL_FREEZE: readonly Draft[] = [
  // Signs
  {
    emoji: '🧪',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'LABORATUVAR',
        en: 'LABORATORY',
        de: 'LABOR',
        ar: 'المختبر',
        fr: 'LABORATOIRE',
        es: 'LABORATORIO',
      },
      small: {
        tr: 'DENEY SÜRÜYOR · DOKUNMAYIN',
        en: 'EXPERIMENT IN PROGRESS',
        de: 'VERSUCH LÄUFT · NICHT BERÜHREN',
        ar: 'تجربة جارية · لا تلمس',
        fr: 'EXPÉRIENCE EN COURS',
        es: 'EXPERIMENTO EN CURSO',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Deney köpürmeye başladı',
      en: 'The experiment is starting to foam',
      de: 'Das Experiment fängt an zu schäumen',
      ar: 'بدأت التجربة تفور',
      fr: "L'expérience commence à mousser",
      es: 'El experimento empezó a hacer espuma',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'KURUYOR',
        en: 'DRYING',
        de: 'TROCKNET',
        ar: 'يجفّ',
        fr: 'ÇA SÈCHE',
        es: 'SECANDO',
      },
      small: {
        tr: 'MAKET ÖDEVİ · DOKUNMAYIN',
        en: "SCHOOL PROJECT · DON'T TOUCH",
        de: 'SCHULPROJEKT · NICHT ANFASSEN',
        ar: 'مشروع مدرسي · لا تلمس',
        fr: 'MAQUETTE · NE PAS TOUCHER',
        es: 'MAQUETA · NO TOCAR',
      },
    },
    caption: {
      tr: 'Yapıştırıcı tutana kadar kıpırdama.',
      en: "Don't move till the glue sets.",
      de: 'Keine Bewegung, bis der Kleber hält.',
      ar: 'لا تتحرك حتى يثبت الغراء.',
      fr: 'Bouge pas tant que la colle a pas pris.',
      es: 'No te muevas hasta que pegue.',
    },
    headline: {
      tr: 'Maket ödevin hâlâ kuruyor',
      en: 'Your school project is still drying',
      de: 'Dein Schulprojekt trocknet noch',
      ar: 'مشروعك المدرسي ما زال يجف',
      fr: "Ta maquette n'a pas fini de sécher",
      es: 'Tu maqueta todavía se está secando',
    },
  },
  {
    emoji: '✍️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SÜRE BİTTİ',
        en: "TIME'S UP",
        de: 'ZEIT UM',
        ar: 'انتهى الوقت',
        fr: 'TERMINÉ',
        es: 'SE ACABÓ',
      },
      small: {
        tr: 'KALEMLERİ BIRAKIN',
        en: 'PENCILS DOWN',
        de: 'STIFTE WEG',
        ar: 'ضعوا الأقلام',
        fr: 'POSEZ VOS STYLOS',
        es: 'DEJEN LOS LÁPICES',
      },
    },
    caption: {
      tr: 'Son harfi bile yazma.',
      en: 'Not one more letter.',
      de: 'Kein Buchstabe mehr.',
      ar: 'ولا حرفًا واحدًا بعد.',
      fr: 'Pas une lettre de plus.',
      es: 'Ni una letra más.',
    },
    headline: {
      tr: 'Hoca “kalemler masaya” dedi',
      en: 'Teacher: “Pencils down!”',
      de: 'Lehrer: „Stifte weg!“',
      ar: 'المعلم: «ضعوا الأقلام!»',
      fr: 'Le prof : « Posez vos stylos ! »',
      es: 'El profe: “¡Lápices abajo!”',
    },
  },
  {
    emoji: '🌳',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'SAHNE',
        en: 'STAGE',
        de: 'BÜHNE',
        ar: 'المسرح',
        fr: 'SCÈNE',
        es: 'ESCENARIO',
      },
      small: {
        tr: 'GÖSTERİ BAŞLADI',
        en: 'SHOW IN PROGRESS',
        de: 'VORSTELLUNG LÄUFT',
        ar: 'العرض بدأ',
        fr: 'SPECTACLE EN COURS',
        es: 'FUNCIÓN EN CURSO',
      },
    },
    caption: {
      tr: 'Ağaçlar kıpırdamaz.',
      en: "Trees don't move.",
      de: 'Bäume bewegen sich nicht.',
      ar: 'الأشجار لا تتحرك.',
      fr: 'Un arbre, ça bouge pas.',
      es: 'Los árboles no se mueven.',
    },
    headline: {
      tr: 'Okul oyununda ağaç rolündesin',
      en: "You're a tree in the school play",
      de: 'Du spielst im Schultheater einen Baum',
      ar: 'دورك في مسرحية المدرسة: شجرة',
      fr: "Pièce de l'école : tu joues un arbre",
      es: 'Eres un árbol en la obra de la escuela',
    },
  },
  // Security cameras
  {
    emoji: '📱',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: '9-B SINIFI',
        en: 'ROOM 9B',
        de: 'KLASSE 9B',
        ar: 'الصف 9 ب',
        fr: 'SALLE 9B',
        es: 'AULA 9B',
      },
    },
    caption: {
      tr: 'Seninki elinde. Kıpırdama.',
      en: 'Yours is in your hand. Freeze.',
      de: 'Deins ist in deiner Hand. Stillhalten.',
      ar: 'هاتفك في يدك. لا تتحرك.',
      fr: 'Le tien est dans ta main. Bouge pas.',
      es: 'El tuyo está en tu mano. Quieto.',
    },
    headline: {
      tr: 'Hoca telefonları topluyor',
      en: "Teacher's collecting phones",
      de: 'Die Lehrerin sammelt Handys ein',
      ar: 'المعلم يجمع الهواتف',
      fr: 'La prof ramasse les portables',
      es: 'El profe está recogiendo los teléfonos',
    },
  },
  {
    emoji: '🧑‍🏫',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'MATEMATİK DERSİ',
        en: 'MATH CLASS',
        de: 'MATHESTUNDE',
        ar: 'حصة الرياضيات',
        fr: 'COURS DE MATHS',
        es: 'MATEMÁTICAS',
      },
    },
    caption: {
      tr: 'Defterini okuyormuş gibi yap.',
      en: 'Look busy. Stare at your notebook.',
      de: 'Tu so, als würdest du ins Heft schauen.',
      ar: 'تظاهر بأنك تقرأ دفترك.',
      fr: 'Fais semblant de lire ton cahier.',
      es: 'Haz como que lees tu cuaderno.',
    },
    headline: {
      tr: 'Hoca tahtaya kaldıracak birini arıyor',
      en: "Teacher's picking someone for the board",
      de: 'Der Lehrer sucht jemanden für die Tafel',
      ar: 'المعلم يبحث عمّن يخرج إلى السبورة',
      fr: 'Le prof cherche qui envoyer au tableau',
      es: 'El profe busca quién pase a la pizarra',
    },
  },
  {
    emoji: '🤝',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÖĞRETMENLER ODASI',
        en: "TEACHERS' LOUNGE",
        de: 'LEHRERZIMMER',
        ar: 'غرفة المعلمين',
        fr: 'SALLE DES PROFS',
        es: 'SALA DE PROFESORES',
      },
    },
    caption: {
      tr: 'Sadece gülümse. Kıpırdama.',
      en: "Just smile. Don't move.",
      de: 'Nur lächeln. Nicht bewegen.',
      ar: 'ابتسم فقط. لا تتحرك.',
      fr: 'Souris. Et bouge pas.',
      es: 'Solo sonríe. No te muevas.',
    },
    headline: {
      tr: 'Öğretmenin annenle konuşuyor',
      en: 'Your teacher is talking to your mom',
      de: 'Deine Lehrerin spricht mit deiner Mutter',
      ar: 'معلمتك تتحدث مع أمك',
      fr: 'Ta prof parle avec ta mère',
      es: 'Tu profe está hablando con tu mamá',
    },
  },
  {
    emoji: '🕵️',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'SINAV SALONU',
        en: 'EXAM HALL',
        de: 'PRÜFUNGSSAAL',
        ar: 'قاعة الامتحان',
        fr: "SALLE D'EXAMEN",
        es: 'SALA DE EXAMEN',
      },
    },
    caption: {
      tr: 'Bir şey yapmadın. Yine de kıpırdama.',
      en: "You did nothing. Still, don't move.",
      de: 'Du hast nichts getan. Trotzdem: still.',
      ar: 'لم تفعل شيئًا، لكن لا تتحرك.',
      fr: "T'as rien fait. Bouge pas quand même.",
      es: 'No hiciste nada. Igual, no te muevas.',
    },
    headline: {
      tr: 'Gözetmen tam arkanda durdu',
      en: 'The proctor stopped right behind you',
      de: 'Die Aufsicht bleibt hinter dir stehen',
      ar: 'المراقب توقّف خلفك تمامًا',
      fr: "Le surveillant s'arrête derrière toi",
      es: 'El vigilante se detuvo detrás de ti',
    },
  },
];
