import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Sleep, mornings and routines: bedtime, naps, dreams, weekends, morning people, new habits.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const SLEEP_SKIP: readonly Draft[] = [
  {
    emoji: '🥛',
    user: ACCOUNTS.mornings,
    body: { format: 'scene' },
    caption: {
      tr: 'Gevreği buzdolabına, sütü dolaba koydum',
      en: 'Cereal in the fridge, milk in the pantry. Morning!',
      de: 'Müsli in den Kühlschrank, Milch in den Schrank. Morgen!',
      ar: 'الحبوب في الثلاجة، والحليب في الخزانة. صباح الخير!',
      fr: 'Céréales au frigo, lait dans le placard. Bonjour !',
      es: 'Cereal en la nevera, leche en la alacena. ¡Buenos días!',
      ja: 'シリアルを冷蔵庫に、牛乳を棚にしまった。朝だ。',
      ko: '시리얼은 냉장고에, 우유는 찬장에 넣었다. 아침이다.',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Tişört öğlene kadar tersti, kimse söylemedi',
      en: 'My shirt was inside out till noon. Nobody said a thing.',
      de: 'Shirt bis mittags auf links. Keiner hat was gesagt.',
      ar: 'ارتديت القميص مقلوبًا حتى الظهر، ولم ينبّهني أحد',
      fr: "T-shirt à l'envers jusqu'à midi. Personne n'a rien dit.",
      es: 'Camiseta al revés hasta el mediodía. Nadie dijo nada.',
      ja: '昼までTシャツが裏返し。誰も言ってくれなかった。',
      ko: '점심까지 티셔츠를 뒤집어 입었는데 아무도 말 안 해 줌',
    },
  },
  {
    emoji: '💭',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Rüyaya geri döndüm, kanal değişmiş',
      en: 'Went back to finish my dream. Channel changed.',
      de: 'Wollte weiterträumen. Anderer Sender.',
      ar: 'عدت إلى النوم لأكمل الحلم… فتغيّرت القناة',
      fr: 'Je me rendors pour la suite du rêve. Autre chaîne.',
      es: 'Volví a dormir para seguir el sueño. Otro canal.',
      ja: '夢の続きを見に戻ったら、チャンネルが変わってた',
      ko: '꿈 이어 보려고 다시 잤는데 채널이 바뀌었다',
    },
  },
  {
    emoji: '🎓',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Rüyamda sınav vardı. 12 yıldır mezunum.',
      en: 'Dreamed I had an exam. I graduated 12 years ago.',
      de: 'Im Traum eine Prüfung. Mein Abschluss war vor 12 Jahren.',
      ar: 'حلمت أن لديّ امتحانًا… وقد تخرّجت قبل 12 عامًا',
      fr: "J'ai rêvé d'un exam. J'ai fini l'école il y a 12 ans.",
      es: 'Soñé que tenía un examen. Me gradué hace 12 años.',
      ja: '夢に試験が出てきた。卒業して12年たつのに。',
      ko: '꿈에 시험이 나왔다. 졸업한 지 12년인데.',
    },
  },
  {
    emoji: '🪥',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Diş macunu üstüne portakal suyu. Hata.',
      en: 'Orange juice right after brushing. Big mistake.',
      de: 'Orangensaft direkt nach dem Zähneputzen. Fehler.',
      ar: 'عصير برتقال بعد تنظيف الأسنان مباشرة. خطأ فادح.',
      fr: "Jus d'orange juste après le dentifrice. Erreur.",
      es: 'Jugo de naranja tras cepillarme los dientes. Error.',
      ja: '歯みがきの後にオレンジジュース。失敗。',
      ko: '양치 직후 오렌지 주스. 실수였다.',
    },
  },
  {
    emoji: '🐑',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Koyun sayarken şaşırdım, baştan başladım',
      en: 'Lost count of the sheep. Starting over.',
      de: 'Beim Schäfchenzählen verzählt. Noch mal von vorn.',
      ar: 'أخطأت في عدّ الخراف، فبدأت من جديد',
      fr: 'Perdu le compte des moutons. On recommence.',
      es: 'Perdí la cuenta de las ovejas. Vuelvo a empezar.',
      ja: '羊を数えてたら途中でわからなくなった。最初から。',
      ko: '양 세다가 헷갈려서 처음부터 다시',
    },
  },
  {
    emoji: '🛌',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Kusursuz uyku pozisyonunu buldum. Sabah olmuş.',
      en: 'Found the perfect sleeping position. It was morning.',
      de: 'Die perfekte Schlafposition gefunden. Da war es Morgen.',
      ar: 'وجدت وضعية النوم المثالية… فإذا بالصباح قد حلّ',
      fr: "Trouvé la position parfaite pour dormir. C'était le matin.",
      es: 'Encontré la postura perfecta para dormir. Ya era de día.',
      ja: '完璧な寝る姿勢を見つけた。朝だった。',
      ko: '완벽한 수면 자세를 찾았다. 아침이었다.',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
        ja: 'ルームメイト',
        ko: '룸메이트',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'dün gece uykunda bağırdın',
            en: 'you yelled in your sleep last night',
            de: 'du hast letzte Nacht im Schlaf geschrien',
            ar: 'صرخت وأنت نائم ليلة أمس',
            fr: "t'as crié en dormant cette nuit",
            es: 'anoche gritaste en sueños',
            ja: '昨日の夜、寝言で叫んでたよ',
            ko: '어젯밤에 너 잠꼬대로 소리 질렀어',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ne dedim ki? 😳',
            en: 'what did I say? 😳',
            de: 'was hab ich gesagt? 😳',
            ar: 'ماذا قلت؟ 😳',
            fr: "j'ai dit quoi ? 😳",
            es: '¿qué dije? 😳',
            ja: '何て言った？😳',
            ko: '내가 뭐라고 했는데? 😳',
          },
        },
        {
          from: 'them',
          text: {
            tr: '“O BÖREK BENİM, KİMSE DOKUNMASIN!”',
            en: '“NOBODY TOUCHES MY WAFFLES!”',
            de: '„FINGER WEG VON MEINEN WAFFELN!“',
            ar: '«لا أحد يلمس فطائري!»',
            fr: '« PERSONNE NE TOUCHE À MES CRÊPES ! »',
            es: '“¡NADIE TOCA MIS GALLETAS!”',
            ja: '「そのプリンは私の！さわるな！」',
            ko: '“그 치킨 내 거야, 아무도 손대지 마!”',
          },
        },
      ],
    },
    caption: {
      tr: 'Rüyamda bile yemeğimi koruyorum',
      en: 'Guarding my food even in my sleep',
      de: 'Ich verteidige mein Essen sogar im Schlaf',
      ar: 'أحمي طعامي حتى في أحلامي',
      fr: 'Je défends ma bouffe même en rêve',
      es: 'Defiendo mi comida hasta en sueños',
      ja: '夢の中でも食べ物は守る',
      ko: '꿈속에서도 내 음식은 지킨다',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.motivation,
    body: {
      format: 'chat',
      contact: {
        tr: 'Dün gece ben',
        en: 'Last-night me',
        de: 'Ich, gestern Nacht',
        ar: 'أنا ليلة أمس',
        fr: "Moi d'hier soir",
        es: 'Yo de anoche',
        ja: '昨夜の自分',
        ko: '어젯밤의 나',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yarın 06.00: koşu, yoga, yeşil smoothie ✨',
            en: 'tomorrow 6am: run, yoga, green smoothie ✨',
            de: 'morgen 6 Uhr: Joggen, Yoga, Smoothie ✨',
            ar: 'غدًا في السادسة: جري، يوغا، عصير أخضر ✨',
            fr: 'demain 6 h : footing, yoga, smoothie vert ✨',
            es: 'mañana 6:00: correr, yoga, batido verde ✨',
            ja: '明日は6時起き：ラン、ヨガ、スムージー✨',
            ko: '내일 6시: 러닝, 요가, 그린 스무디 ✨',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bu sefer ciddiyim 💪',
            en: 'I mean it this time 💪',
            de: "diesmal mein ich's ernst 💪",
            ar: 'هذه المرة أنا جاد 💪',
            fr: "cette fois c'est sérieux 💪",
            es: 'esta vez va en serio 💪',
            ja: '今度こそ本気💪',
            ko: '이번엔 진짜야 💪',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'pardon, kimsiniz?',
            en: 'sorry, who is this?',
            de: 'sorry, wer ist da?',
            ar: 'عذرًا، من معي؟',
            fr: "pardon, c'est qui ?",
            es: 'perdón, ¿quién eres?',
            ja: 'すみません、どちら様？',
            ko: '죄송한데 누구세요?',
          },
        },
      ],
    },
    caption: {
      tr: 'Gece ben planlar, sabah ben reddeder',
      en: 'Night me makes plans. Morning me declines.',
      de: 'Nacht-Ich plant. Morgen-Ich lehnt ab.',
      ar: 'أنا ليلًا أخطط، وأنا صباحًا أرفض',
      fr: 'Moi le soir : des plans. Moi le matin : non.',
      es: 'El yo de la noche planea. El de la mañana, no.',
      ja: '夜の私が計画して、朝の私が却下する',
      ko: '밤의 나는 계획하고, 아침의 나는 거절한다',
    },
  },
  {
    emoji: '🤥',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'uyandırdım mı?',
            en: 'did I wake you?',
            de: 'hab ich dich geweckt?',
            ar: 'هل أيقظتك؟',
            fr: 'je te réveille ?',
            es: '¿te desperté?',
            ja: '起こしちゃった？',
            ko: '깨웠니?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yok ane, çoktan klaktım',
            en: 'nope, bene up for hourss',
            de: 'nee, bin shcon lagne wach',
            ar: 'لا يا أمي، استيظقت منذ ساعات',
            fr: 'non, jsuis debout dpuis des heurs',
            es: 'no, mamá, me levnaté hace hroas',
            ja: 'ううん、とっくにおちてるよ',
            ko: '아니 엄먀, 진작 일러낫어',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yazından belli 🙂',
            en: 'I can tell 🙂',
            de: 'merkt man 🙂',
            ar: 'واضح من كتابتك 🙂',
            fr: 'ça se voit 🙂',
            es: 'se nota 🙂',
            ja: '文字でわかるよ🙂',
            ko: '맞춤법 보니 알겠네 🙂',
          },
        },
      ],
    },
    caption: {
      tr: 'Annemden hiçbir şey saklanmıyor',
      en: "You can't fool a mom",
      de: 'Mamas merken einfach alles',
      ar: 'لا شيء يخفى على أمي',
      fr: 'On ne ment pas à une maman',
      es: 'A una mamá no se le escapa nada',
      ja: '母には何も隠せない',
      ko: '엄마한테는 아무것도 못 숨긴다',
    },
  },
  {
    emoji: '🌄',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sabahçı Kanka',
        en: 'Early Bird',
        de: 'Frühaufsteher',
        ar: 'صديقي الصباحي',
        fr: 'Pote lève-tôt',
        es: 'Amigo madrugador',
        ja: '朝型の友だち',
        ko: '아침형 친구',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'günaydııın ☀️ güneş doğuyor, kalk!',
            en: "morninggg ☀️ sun's coming up, get up!",
            de: 'Mooorgen ☀️ Sonnenaufgang, steh auf!',
            ar: 'صباح الخيرررر ☀️ الشمس تشرق، انهض!',
            fr: 'bonjouuur ☀️ le soleil se lève, debout !',
            es: '¡buenos díaaas ☀️ sale el sol, arriba!',
            ja: 'おはよーー☀️ 日の出だよ、起きて！',
            ko: '좋은 아침~ ☀️ 해 뜬다, 일어나!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'saat kaç?',
            en: 'what time is it',
            de: 'wie spät ist es?',
            ar: 'كم الساعة؟',
            fr: 'il est quelle heure ?',
            es: '¿qué hora es?',
            ja: '今何時？',
            ko: '지금 몇 시야?',
          },
        },
        {
          from: 'them',
          text: {
            tr: '05.47 😊',
            en: '5:47 😊',
            de: '5:47 😊',
            ar: '5:47 😊',
            fr: '5 h 47 😊',
            es: '5:47 😊',
            ja: '5時47分😊',
            ko: '5시 47분 😊',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'güneşe selamımı söyle',
            en: 'tell the sun I said hi',
            de: 'grüß die Sonne von mir',
            ar: 'بلّغ الشمس سلامي',
            fr: 'passe le bonjour au soleil',
            es: 'salúdame al sol',
            ja: '太陽によろしく',
            ko: '해한테 안부 전해 줘',
          },
        },
      ],
    },
    caption: {
      tr: 'Her grupta bir sabahçı vardır',
      en: 'Every group has one morning person',
      de: 'Jede Clique hat einen Frühaufsteher',
      ar: 'في كل مجموعة شخص صباحي واحد',
      fr: 'Chaque bande a son lève-tôt',
      es: 'Todo grupo tiene un madrugador',
      ja: 'どのグループにも朝型が一人いる',
      ko: '어느 단톡방에나 아침형 인간 한 명은 있다',
    },
  },
  {
    emoji: '🌗',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah insanı mısın, gece kuşu mu?',
        en: 'Morning person or night owl?',
        de: 'Morgenmensch oder Nachteule?',
        ar: 'هل أنت صباحي أم ليلي؟',
        fr: 'Plutôt du matin ou du soir ?',
        es: '¿Eres más de mañana o de noche?',
        ja: '朝型？夜型？',
        ko: '아침형 인간이에요, 올빼미형이에요?',
      },
      options: [
        {
          tr: 'Sabah insanı ☀️',
          en: 'Morning person ☀️',
          de: 'Morgenmensch ☀️',
          ar: 'صباحي ☀️',
          fr: 'Du matin ☀️',
          es: 'De mañana ☀️',
          ja: '朝型☀️',
          ko: '아침형 ☀️',
        },
        {
          tr: 'Gece kuşu 🦉',
          en: 'Night owl 🦉',
          de: 'Nachteule 🦉',
          ar: 'ليلي 🦉',
          fr: 'Du soir 🦉',
          es: 'De noche 🦉',
          ja: '夜型🦉',
          ko: '올빼미형 🦉',
        },
        {
          tr: 'Hiçbiri, yorgunum',
          en: 'Neither. Just tired.',
          de: 'Keins, nur müde',
          ar: 'لا هذا ولا ذاك، متعب',
          fr: 'Aucun, juste KO',
          es: 'Ninguno, tengo sueño',
          ja: 'どっちでもない、眠い',
          ko: '둘 다 아님, 피곤함',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'En verimli saatim: 14.00 ile 14.15 arası',
      en: 'My productive hours: 2:00 to 2:15 p.m.',
      de: 'Produktiv bin ich von 14:00 bis 14:15 Uhr',
      ar: 'ساعتي المنتجة: من 2:00 إلى 2:15 ظهرًا',
      fr: 'Mon pic de forme : de 14 h à 14 h 15',
      es: 'Mi hora productiva: de 14:00 a 14:15',
      ja: '一番はかどる時間：14時〜14時15分',
      ko: '가장 생산적인 시간: 오후 2시~2시 15분',
    },
  },
  {
    emoji: '🥴',
    user: ACCOUNTS.mornings,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah ilk kelimen genelde ne olur?',
        en: 'Your first word in the morning?',
        de: 'Dein erstes Wort am Morgen?',
        ar: 'ما أول كلمة تقولها في الصباح؟',
        fr: 'Ton premier mot le matin ?',
        es: '¿Tu primera palabra por la mañana?',
        ja: '朝の第一声は？',
        ko: '아침 첫마디는 보통 뭐예요?',
      },
      options: [
        {
          tr: 'Günaydın!',
          en: 'Good morning!',
          de: 'Guten Morgen!',
          ar: 'صباح الخير!',
          fr: 'Bonjour !',
          es: '¡Buenos días!',
          ja: 'おはよう！',
          ko: '좋은 아침!',
        },
        { tr: 'Hıı?', en: 'Huh?', de: 'Hä?', ar: 'هاه؟', fr: 'Hein ?', es: '¿Eh?', ja: 'んあ？', ko: '으응?' },
      ],
      winner: 1,
    },
    caption: {
      tr: 'İlk düzgün cümlem öğlene doğru gelir',
      en: 'First full sentence arrives around noon',
      de: 'Der erste ganze Satz kommt gegen Mittag',
      ar: 'أول جملة كاملة تصل قرب الظهر',
      fr: 'Première phrase complète : vers midi',
      es: 'Mi primera frase completa llega al mediodía',
      ja: 'まともな文が出るのは昼ごろ',
      ko: '제대로 된 첫 문장은 점심쯤 나온다',
    },
  },
  {
    emoji: '🦥',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah yataktan nasıl çıkarsın?',
        en: 'How do you get out of bed?',
        de: 'Wie kommst du morgens aus dem Bett?',
        ar: 'كيف تنهض من السرير صباحًا؟',
        fr: 'Tu sors du lit comment, le matin ?',
        es: '¿Cómo te levantas de la cama?',
        ja: '朝、どうやってベッドから出る？',
        ko: '아침에 침대에서 어떻게 나와요?',
      },
      options: [
        {
          tr: 'Tek zıplayışta',
          en: 'One jump, done',
          de: 'Mit einem Sprung',
          ar: 'بقفزة واحدة',
          fr: "D'un bond",
          es: 'De un salto',
          ja: '一発で飛び起きる',
          ko: '한 번에 벌떡',
        },
        {
          tr: 'Yuvarlanarak, yavaşça',
          en: 'Slow roll, then flop',
          de: 'Rausrollen, langsam',
          ar: 'أتدحرج ببطء',
          fr: 'En roulant, lentement',
          es: 'Rodando, muy despacio',
          ja: 'ゴロゴロ転がって',
          ko: '데굴데굴 굴러서',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Yere kütük gibi iniyorum. Çok zarif.',
      en: 'I land on the floor like a log. Very graceful.',
      de: 'Ich lande wie ein Baumstamm. Sehr elegant.',
      ar: 'أهبط على الأرض كجذع شجرة. بمنتهى الأناقة.',
      fr: "J'atterris comme une bûche. Tout en grâce.",
      es: 'Aterrizo en el suelo como un tronco. Muy elegante.',
      ja: '丸太みたいに床に着地。とても優雅。',
      ko: '통나무처럼 바닥에 착지한다. 아주 우아하다.',
    },
  },
  {
    emoji: '🦒',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'RÜYADAN AKLIMDA KALAN',
        en: 'DREAM RECALL',
        de: 'ERINNERUNG AN DEN TRAUM',
        ar: 'ما بقي من حلمي',
        fr: 'SOUVENIR DU RÊVE',
        es: 'RECUERDO DEL SUEÑO',
        ja: '夢の記憶',
        ko: '꿈 기억률',
      },
      value: {
        tr: '%3',
        en: '3%',
        de: '3 %',
        ar: '3%',
        fr: '3 %',
        es: '3 %',
        ja: '3%',
        ko: '3%',
      },
      shape: 'fall',
      axis: 'hours',
    },
    caption: {
      tr: 'Öğlene kalan tek şey: bir zürafa vardı galiba',
      en: 'By noon: there was a giraffe, I think?',
      de: 'Bis mittags bleibt: Da war eine Giraffe, oder?',
      ar: 'عند الظهر لم يبقَ إلا: كانت هناك زرافة، على ما أظن',
      fr: 'À midi, il reste : il y avait une girafe, je crois',
      es: 'Al mediodía solo queda: había una jirafa, creo',
      ja: '昼に残ってるのは「キリンがいた気がする」だけ',
      ko: '점심때 남은 기억: 기린이 있었던 것 같다',
    },
  },
  {
    emoji: '🌇',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'PAZAR KEYFİM',
        en: 'MY SUNDAY MOOD',
        de: 'MEINE SONNTAGSLAUNE',
        ar: 'مزاجي في آخر العطلة',
        fr: 'MON MORAL DU DIMANCHE',
        es: 'MI HUMOR DEL DOMINGO',
        ja: '日曜の気分',
        ko: '일요일 기분',
      },
      value: null,
      shape: 'crash',
      axis: 'hours',
    },
    caption: {
      tr: 'Saat 18.00’de pazartesi aklıma geldi',
      en: 'Then at 6 p.m. I remembered Monday',
      de: 'Um 18 Uhr fiel mir der Montag ein',
      ar: 'في السادسة مساءً تذكّرت أن غدًا يوم عمل',
      fr: "À 18 h, j'ai pensé à lundi",
      es: 'A las 6 de la tarde me acordé del lunes',
      ja: '18時に月曜日を思い出した',
      ko: '저녁 6시에 월요일이 떠올랐다',
    },
  },
  {
    emoji: '🥯',
    user: ACCOUNTS.mornings,
    body: {
      format: 'chart',
      title: {
        tr: 'KAHVALTI SÜREM',
        en: 'MY BREAKFAST TIME',
        de: 'MEINE FRÜHSTÜCKSZEIT',
        ar: 'مدة فطوري',
        fr: 'DURÉE DE MON PETIT-DÉJ',
        es: 'MI TIEMPO DE DESAYUNO',
        ja: '朝ごはんの時間',
        ko: '아침 식사 시간',
      },
      value: null,
      shape: 'rise',
      axis: 'days',
    },
    caption: {
      tr: 'Hafta içi 40 saniye, hafta sonu 3 saat',
      en: 'Weekdays: 40 seconds. Weekends: 3 hours.',
      de: 'Unter der Woche 40 Sekunden, am Wochenende 3 Stunden',
      ar: 'أيام العمل: 40 ثانية. العطلة: 3 ساعات.',
      fr: 'En semaine : 40 secondes. Le week-end : 3 heures.',
      es: 'Entre semana, 40 segundos. Fin de semana, 3 horas.',
      ja: '平日40秒、週末3時間',
      ko: '평일 40초, 주말 3시간',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'ZÜCCACİYE',
        en: 'HOUSEWARES',
        de: 'HAUSHALTSWAREN',
        ar: 'الأدوات المنزلية',
        fr: 'ARTS DE LA TABLE',
        es: 'TIENDA DE HOGAR',
        ja: '雑貨店',
        ko: '생활용품점',
      },
      items: [
        {
          tr: 'DEV KUPA (1 LİTRE)',
          en: 'GIANT MUG (1 LITER)',
          de: 'RIESENTASSE (1 LITER)',
          ar: 'كوب عملاق (1 لتر)',
          fr: 'MUG GÉANT (1 LITRE)',
          es: 'TAZA GIGANTE (1 LITRO)',
          ja: '特大マグ（1リットル）',
          ko: '대형 머그 (1리터)',
        },
      ],
    },
    caption: {
      tr: 'Günde tek kahve kuralı. Teknik olarak.',
      en: 'One coffee a day. Technically.',
      de: 'Ein Kaffee am Tag. Technisch gesehen.',
      ar: 'قاعدتي: كوب قهوة واحد في اليوم. تقنيًا.',
      fr: 'Un seul café par jour. Techniquement.',
      es: 'Un solo café al día. Técnicamente.',
      ja: 'コーヒーは1日1杯。一応。',
      ko: '커피는 하루 한 잔. 엄밀히 말하면.',
    },
  },
  {
    emoji: '🌅',
    user: ACCOUNTS.sleep,
    body: {
      format: 'receipt',
      store: {
        tr: 'AYDINLATMA',
        en: 'LIGHTING STORE',
        de: 'LAMPENLADEN',
        ar: 'متجر الإنارة',
        fr: 'LUMINAIRES',
        es: 'ILUMINACIÓN',
        ja: '照明店',
        ko: '조명 가게',
      },
      items: [
        {
          tr: 'GÜN DOĞUMU LAMBASI',
          en: 'SUNRISE LAMP',
          de: 'LICHTWECKER',
          ar: 'مصباح شروق الشمس',
          fr: 'LAMPE LEVER DE SOLEIL',
          es: 'LÁMPARA AMANECER',
          ja: '目覚ましライト',
          ko: '일출 램프',
        },
      ],
    },
    caption: {
      tr: 'Lamba doğdu. Ben kalkmadım.',
      en: 'The lamp rose. I did not.',
      de: 'Die Lampe ist aufgegangen. Ich nicht.',
      ar: 'أشرق المصباح. أما أنا فلا.',
      fr: "La lampe s'est levée. Moi, non.",
      es: 'La lámpara amaneció. Yo no.',
      ja: 'ライトは昇った。私は起きなかった。',
      ko: '램프는 떴다. 나는 안 일어났다.',
    },
  },
  {
    emoji: '🚿',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU SABAH',
        en: 'THIS MORNING',
        de: 'HEUTE MORGEN',
        ar: 'هذا الصباح',
        fr: 'CE MATIN',
        es: 'ESTA MAÑANA',
        ja: '今朝',
        ko: '오늘 아침',
      },
      big: { tr: '12', en: '12', de: '12', ar: '12', fr: '12', es: '12', ja: '12', ko: '12' },
      text: {
        tr: 'dakika duşta öylece durdun; uyanmayı bekledin',
        en: 'minutes standing in the shower, waiting to wake up',
        de: 'Minuten reglos unter der Dusche, bis du wach warst',
        ar: 'دقيقة وقفت تحت الدش تنتظر أن تستيقظ',
        fr: 'minutes sous la douche sans bouger, à attendre le réveil',
        es: 'minutos bajo la ducha sin moverte, esperando despertar',
        ja: '分間、シャワーの下で目が覚めるのを待った',
        ko: '분 동안 샤워기 아래 서서 잠이 깨길 기다렸다',
      },
    },
    caption: {
      tr: 'Ayakta şekerleme de şekerlemedir',
      en: 'A standing nap is still a nap',
      de: 'Ein Nickerchen im Stehen zählt auch',
      ar: 'القيلولة واقفًا تبقى قيلولة',
      fr: 'Une sieste debout reste une sieste',
      es: 'Una siesta de pie sigue siendo siesta',
      ja: '立ったままの昼寝も昼寝',
      ko: '서서 자는 것도 낮잠이다',
    },
  },
  {
    emoji: '👗',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'DOLABINDA',
        en: 'IN YOUR CLOSET',
        de: 'IM KLEIDERSCHRANK',
        ar: 'في خزانتك',
        fr: 'DANS TON PLACARD',
        es: 'EN TU ARMARIO',
        ja: 'クローゼットに',
        ko: '옷장 속에',
      },
      big: { tr: '143', en: '143', de: '143', ar: '143', fr: '143', es: '143', ja: '143', ko: '143' },
      text: {
        tr: 'parça kıyafetin var; giyecek hiçbir şeyin yok',
        en: 'pieces of clothing, and nothing to wear',
        de: 'Kleidungsstücke – und nichts zum Anziehen',
        ar: 'قطعة ملابس… ولا شيء ترتديه',
        fr: 'vêtements, et rien à te mettre',
        es: 'prendas de ropa, y nada que ponerte',
        ja: '着の服があるのに、着る服がない',
        ko: '벌의 옷이 있는데 입을 옷이 없다',
      },
    },
    caption: {
      tr: 'Yine o gri kazak',
      en: 'The gray sweater again',
      de: 'Wieder der graue Pulli',
      ar: 'السترة الرمادية نفسها مجددًا',
      fr: 'Encore le pull gris',
      es: 'Otra vez el suéter gris',
      ja: '結局またあのグレーのセーター',
      ko: '오늘도 그 회색 니트',
    },
  },
  {
    emoji: '🥱',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'ŞU AN',
        en: 'RIGHT NOW',
        de: 'GENAU JETZT',
        ar: 'الآن',
        fr: 'EN CE MOMENT',
        es: 'AHORA MISMO',
        ja: '今',
        ko: '지금',
      },
      big: { tr: '1', en: '1', de: '1', ar: '1', fr: '1', es: '1', ja: '1', ko: '1' },
      text: {
        tr: 'kez esnedin; sadece bunu okuduğun için',
        en: 'yawn, just from reading this',
        de: 'Mal gegähnt, nur weil du das liest',
        ar: 'تثاؤب، فقط لأنك تقرأ هذا',
        fr: "bâillement, rien qu'en lisant ça",
        es: 'bostezo, solo por leer esto',
        ja: '回あくびした。これを読んだだけで。',
        ko: '번 하품했다. 이걸 읽었을 뿐인데.',
      },
    },
    caption: {
      tr: 'Yanındaki de esnedi, bak',
      en: 'Look, the person next to you just yawned',
      de: 'Guck, dein Nachbar gähnt auch',
      ar: 'انظر، من بجانبك تثاءب أيضًا',
      fr: 'Regarde, ton voisin bâille aussi',
      es: 'Mira, el de al lado también bostezó',
      ja: 'ほら、隣の人もあくびした',
      ko: '봐, 옆 사람도 하품했다',
    },
  },
  {
    emoji: '🌯',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'UYKU POZİSYONU TIER LIST',
        en: 'SLEEP POSITION TIER LIST',
        de: 'SCHLAFPOSITIONEN-RANKING',
        ar: 'تصنيف وضعيات النوم',
        fr: 'TIER LIST POSITIONS DODO',
        es: 'POSTURAS PARA DORMIR',
        ja: '寝相ティアリスト',
        ko: '수면 자세 티어 리스트',
      },
      rows: [['🌯', '🥐'], ['⭐️'], ['🪵'], ['🦇']],
    },
    caption: {
      tr: 'Yarasa pozisyonunu denedim, önermem',
      en: 'Tried the bat position. Do not recommend.',
      de: 'Fledermaus-Position getestet. Nicht empfehlenswert.',
      ar: 'جرّبت وضعية الخفاش، لا أنصح بها',
      fr: "J'ai testé la chauve-souris. Je déconseille.",
      es: 'Probé la postura murciélago. No la recomiendo.',
      ja: 'コウモリ寝を試した。おすすめしない。',
      ko: '박쥐 자세 해 봤다. 비추.',
    },
  },
  {
    emoji: '🧠',
    user: ACCOUNTS.asmr,
    body: {
      format: 'tier',
      title: {
        tr: 'YATMADAN ÖNCE TIER LIST',
        en: 'BEDTIME TIER LIST',
        de: 'EINSCHLAF-RANKING',
        ar: 'تصنيف ما قبل النوم',
        fr: 'TIER LIST AVANT DODO',
        es: 'TIER LIST ANTES DE DORMIR',
        ja: '寝る前ティアリスト',
        ko: '자기 전 티어 리스트',
      },
      rows: [['🌧️', '📖'], ['🍵', '🕯️'], ['🐑'], ['🧠']],
    },
    caption: {
      tr: 'Beynim her gece 2014’teki o anıyı açıyor',
      en: 'Every night my brain replays that thing from 2014',
      de: 'Mein Hirn spielt jede Nacht die Sache von 2014 ab',
      ar: 'كل ليلة يعيد دماغي ذلك الموقف المحرج من 2014',
      fr: 'Chaque nuit, mon cerveau rejoue ce truc de 2014',
      es: 'Cada noche mi cerebro repite aquello de 2014',
      ja: '毎晩、脳が2014年のあの記憶を再生する',
      ko: '매일 밤 뇌가 2014년의 그 흑역사를 재생한다',
    },
  },
  {
    emoji: '🥙',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⌚',
        app: {
          tr: 'Uyku takibi',
          en: 'Sleep tracker',
          de: 'Schlaftracker',
          ar: 'متتبّع النوم',
          fr: 'Suivi du sommeil',
          es: 'Monitor de sueño',
          ja: '睡眠記録',
          ko: '수면 기록',
        },
        text: {
          tr: 'Dün gece yatakta 47 kez döndün',
          en: 'You flipped over 47 times last night',
          de: 'Letzte Nacht 47-mal umgedreht',
          ar: 'تقلّبت في السرير 47 مرة الليلة الماضية',
          fr: 'Cette nuit : 47 demi-tours dans le lit',
          es: 'Anoche diste 47 vueltas en la cama',
          ja: '昨夜、47回寝返りを打ちました',
          ko: '어젯밤 47번 뒤척였어요',
        },
      },
    },
    caption: {
      tr: 'Resmen döner gibiyim',
      en: 'Basically a rotisserie chicken',
      de: 'Ich bin quasi ein Grillhähnchen',
      ar: 'صرت مثل سيخ الشاورما',
      fr: 'Un vrai poulet rôti',
      es: 'Soy un pollo asado girando',
      ja: 'ほぼケバブの肉',
      ko: '사실상 전기구이 통닭',
    },
  },
  {
    emoji: '🧘',
    user: ACCOUNTS.motivation,
    body: {
      format: 'notifications',
      first: {
        icon: '✅',
        app: {
          tr: 'Alışkanlıklar',
          en: 'Habit tracker',
          de: 'Gewohnheiten',
          ar: 'تتبّع العادات',
          fr: 'Habitudes',
          es: 'Hábitos',
          ja: '習慣アプリ',
          ko: '습관 기록',
        },
        text: {
          tr: 'Bugünkü hedef: 10 dakika meditasyon',
          en: "Today's goal: 10 minutes of meditation",
          de: 'Heutiges Ziel: 10 Minuten Meditation',
          ar: 'هدف اليوم: 10 دقائق من التأمل',
          fr: 'Objectif du jour : 10 min de méditation',
          es: 'Meta de hoy: 10 minutos de meditación',
          ja: '今日の目標：瞑想10分',
          ko: '오늘의 목표: 명상 10분',
        },
      },
    },
    caption: {
      tr: '10 dakikada aklıma 47 yapılacak iş geldi',
      en: 'Remembered 47 things to do in those 10 minutes',
      de: 'In 10 Minuten fielen mir 47 To-dos ein',
      ar: 'في 10 دقائق تذكّرت 47 مهمة',
      fr: 'En 10 minutes, 47 choses à faire me sont revenues',
      es: 'En 10 minutos recordé 47 pendientes',
      ja: '10分で47個のやることを思い出した',
      ko: '10분 동안 할 일이 47개 떠올랐다',
    },
  },
  {
    emoji: '🥺',
    user: ACCOUNTS.sleep,
    body: {
      format: 'notifications',
      first: {
        icon: '🛏️',
        app: { tr: 'Yatağın', en: 'Your bed', de: 'Dein Bett', ar: 'سريرك', fr: 'Ton lit', es: 'Tu cama', ja: 'きみのベッド', ko: '너의 침대' },
        text: {
          tr: 'Neredesin? Seni özledim 🥺',
          en: 'Where are you? I miss you 🥺',
          de: 'Wo bleibst du? Ich vermisse dich 🥺',
          ar: 'أين أنت؟ اشتقت إليك 🥺',
          fr: "T'es où ? Tu me manques 🥺",
          es: '¿Dónde estás? Te extraño 🥺',
          ja: 'どこにいるの？会いたい🥺',
          ko: '어디야? 보고 싶어 🥺',
        },
      },
    },
    caption: {
      tr: 'Saat daha 20.30 ama haklı',
      en: "It's only 8:30 p.m., but it has a point",
      de: 'Es ist erst 20:30 Uhr, aber es hat recht',
      ar: 'الساعة الثامنة والنصف فقط، لكنه محق',
      fr: "Il n'est que 20 h 30, mais il a raison",
      es: 'Son apenas las 20:30, pero tiene razón',
      ja: 'まだ20時半だけど、一理ある',
      ko: '아직 저녁 8시 반이지만 맞는 말이다',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Erken kalkan yol alır. Ben zaten hiçbir yere gitmiyorum.',
        en: "The early bird gets the worm. Good thing I don't want a worm.",
        de: 'Der frühe Vogel fängt den Wurm. Ich will aber gar keinen Wurm.',
        ar: 'الطائر المبكر يلتقط الدودة. ولحسن الحظ، لا أريد دودة.',
        fr: "L'avenir est à ceux qui se lèvent tôt. Je le prendrai à midi.",
        es: 'Pájaro que madruga atrapa el gusano. Por suerte, no quiero gusanos.',
        ja: '早起きは三文の徳。でも三文いらない。',
        ko: '일찍 일어나는 새가 벌레를 잡는다. 난 벌레 싫은데.',
      },
    },
    caption: {
      tr: 'Mantığım sağlam',
      en: 'Airtight logic',
      de: 'Wasserdichte Logik',
      ar: 'منطق لا يُردّ',
      fr: 'Logique imparable',
      es: 'Lógica impecable',
      ja: '完璧な理論',
      ko: '완벽한 논리',
    },
  },
  {
    emoji: '👀',
    user: ACCOUNTS.mornings,
    body: {
      format: 'quote',
      text: {
        tr: 'Sabahları gülümse. Ya da en azından gözlerini aç.',
        en: 'Smile every morning. Or at least open your eyes.',
        de: 'Lächle jeden Morgen. Oder öffne wenigstens die Augen.',
        ar: 'ابتسم كل صباح. أو افتح عينيك على الأقل.',
        fr: 'Souris chaque matin. Ou ouvre au moins les yeux.',
        es: 'Sonríe cada mañana. O al menos abre los ojos.',
        ja: '朝は笑顔で。せめて目は開けて。',
        ko: '아침엔 웃으세요. 아니면 눈이라도 뜨세요.',
      },
    },
    caption: {
      tr: 'Adım adım',
      en: 'Baby steps',
      de: 'Schritt für Schritt',
      ar: 'خطوة خطوة',
      fr: 'Petit à petit',
      es: 'Paso a paso',
      ja: '一歩ずつ',
      ko: '한 걸음씩',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Dinlenmek de üretkenliktir. Bugün çok üretken geçti.',
        en: 'Rest is productive too. Today was extremely productive.',
        de: 'Ausruhen ist auch produktiv. Heute war ich sehr produktiv.',
        ar: 'الراحة إنتاجية أيضًا. وكان يومي منتجًا جدًا.',
        fr: "Se reposer, c'est productif aussi. Journée très productive.",
        es: 'Descansar también es productivo. Hoy rendí muchísimo.',
        ja: '休むのも生産性。今日はとても生産的だった。',
        ko: '쉬는 것도 생산성이다. 오늘은 아주 생산적이었다.',
      },
    },
    caption: {
      tr: 'Kanepeden bildiriyorum',
      en: 'Reporting live from the couch',
      de: 'Live vom Sofa',
      ar: 'أنقل لكم مباشرة من الأريكة',
      fr: 'En direct du canapé',
      es: 'En vivo desde el sofá',
      ja: 'ソファから中継です',
      ko: '소파에서 전해 드립니다',
    },
  },
  {
    emoji: '🪶',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kendine yatırım yap. Mesela iyi bir yastığa.',
        en: 'Invest in yourself. Starting with a good pillow.',
        de: 'Investiere in dich selbst. Zum Beispiel in ein gutes Kissen.',
        ar: 'استثمر في نفسك. في وسادة جيدة مثلًا.',
        fr: 'Investis en toi-même. Par exemple, dans un bon oreiller.',
        es: 'Invierte en ti. Por ejemplo, en una buena almohada.',
        ja: '自分に投資しよう。たとえば良い枕に。',
        ko: '자신에게 투자하라. 예를 들면 좋은 베개에.',
      },
    },
    caption: {
      tr: 'Portföyüm: 7 yastık',
      en: 'My portfolio: 7 pillows',
      de: 'Mein Portfolio: 7 Kissen',
      ar: 'محفظتي الاستثمارية: 7 وسائد',
      fr: 'Mon portefeuille : 7 oreillers',
      es: 'Mi portafolio: 7 almohadas',
      ja: 'ポートフォリオ：枕7個',
      ko: '내 포트폴리오: 베개 7개',
    },
  },
  {
    emoji: '📔',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Günlük tut, dediler. Tuttum. Hâlâ elimde, bomboş.',
        en: 'Keep a journal, they said. So I kept it. Still blank.',
        de: 'Führ ein Tagebuch, sagten sie. Hab eins gekauft. Seite 1: leer.',
        ar: 'قالوا: احتفظ بمذكرات. فاحتفظت بالدفتر… فارغًا.',
        fr: "Tiens un journal, qu'ils disaient. Je le tiens. Toujours vide.",
        es: 'Lleva un diario, me dijeron. Lo llevo a todas partes. Vacío.',
        ja: '日記をつけなさいと言われた。ノートは買った。まだ白紙。',
        ko: '일기를 쓰라길래 일기장을 샀다. 아직 새것이다.',
      },
    },
    caption: {
      tr: 'Kalemlerini de aldım ama',
      en: 'I did buy the fancy pens, though',
      de: 'Die schönen Stifte hab ich aber',
      ar: 'لكنني اشتريت الأقلام الملوّنة',
      fr: "J'ai quand même acheté les jolis stylos",
      es: 'Pero sí compré los bolígrafos bonitos',
      ja: 'ペンもちゃんと買ったのに',
      ko: '펜도 샀는데 말이지',
    },
  },
];

export const SLEEP_LIKE: readonly Draft[] = [
  {
    emoji: '🛋️',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'yastıklardan kale yaptım. giriş şifreyle.',
      en: 'built a pillow fort. password required.',
      de: 'kissenburg gebaut. eintritt nur mit passwort.',
      ar: 'بنيت قلعة من الوسائد، والدخول بكلمة سر',
      fr: 'fort en coussins terminé. entrée sur mot de passe.',
      es: 'hice un fuerte de almohadas. se entra con contraseña.',
      ja: '枕で城を作った。入るには合言葉。',
      ko: '베개로 성을 쌓았다. 입장은 암호로.',
    },
  },
  {
    emoji: '🎶',
    user: ACCOUNTS.melis,
    body: { format: 'scene' },
    caption: {
      tr: 'kardeşime ninni söyledim, önce ben uyudum',
      en: 'sang my little brother a lullaby. i fell asleep first',
      de: 'schlaflied für meinen bruder. ich war zuerst weg',
      ar: 'غنّيت لأخي الصغير تهويدة… فنمت أنا أولًا',
      fr: "berceuse pour mon petit frère. c'est moi qui ai dormi",
      es: 'le canté para que durmiera y me dormí yo',
      ja: '弟に子守唄を歌ったら、先に私が寝た',
      ko: '동생한테 자장가 불러 줬는데 내가 먼저 잠듦',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.ipek,
    body: { format: 'scene' },
    caption: {
      tr: 'rüyamda uçtum, unutmadan çizdim',
      en: 'flew in my dream, drew it before i forgot',
      de: "im traum geflogen, schnell gemalt, bevor ich's vergesse",
      ar: 'طرت في حلمي، ورسمته قبل أن أنساه',
      fr: "j'ai volé en rêve, dessiné avant d'oublier",
      es: 'volé en un sueño y lo dibujé antes de olvidarlo',
      ja: '夢で空を飛んだ。忘れる前に描いた',
      ko: '꿈에서 날았다. 까먹기 전에 그렸다',
    },
  },
  {
    emoji: '🦁',
    user: ACCOUNTS.yagmur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'uyandığım gibi',
        en: 'just woke up',
        de: 'frisch aufgewacht',
        ar: 'كما استيقظت تمامًا',
        fr: 'au saut du lit',
        es: 'al despertar',
        ja: '起きたて',
        ko: '방금 일어남',
      },
    },
    caption: {
      tr: 'saçım bu sabah kendi kararlarını veriyor',
      en: 'my hair is making its own decisions today',
      de: 'meine haare treffen heute eigene entscheidungen',
      ar: 'شعري يتخذ قراراته بنفسه اليوم',
      fr: 'mes cheveux prennent leurs propres décisions',
      es: 'mi pelo hoy toma sus propias decisiones',
      ja: '今朝の髪は自分の意思で動いてる',
      ko: '오늘 아침 머리는 자기 마음대로다',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni uyku maskem',
        en: 'new sleep mask',
        de: 'neue schlafmaske',
        ar: 'قناع نومي الجديد',
        fr: 'nouveau masque de nuit',
        es: 'antifaz nuevo',
        ja: '新しいアイマスク',
        ko: '새 수면 안대',
      },
    },
    caption: {
      tr: 'üstünde kaş var, uyurken bile şaşkınım',
      en: 'it has eyebrows. i look shocked in my sleep',
      de: 'hat augenbrauen drauf. ich schlafe jetzt schockiert',
      ar: 'عليه حاجبان… أبدو مصدومًا حتى وأنا نائم',
      fr: 'il a des sourcils : je dors avec un air étonné',
      es: 'tiene cejas: duermo con cara de sorpresa',
      ja: '眉毛つき。寝てても驚いてる顔。',
      ko: '눈썹이 그려져 있어서 자면서도 놀란 얼굴',
    },
  },
  {
    emoji: '🧶',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'anneannemin eseri',
        en: 'grandma made this',
        de: 'von oma gestrickt',
        ar: 'من صنع جدتي',
        fr: 'tricotée par mamie',
        es: 'tejida por la abuela',
        ja: 'おばあちゃん作',
        ko: '할머니 작품',
      },
    },
    caption: {
      tr: '20 yıllık battaniye, hâlâ en sıcağı',
      en: '20 years old and still the coziest blanket',
      de: '20 jahre alt und immer noch die wärmste decke',
      ar: 'بطانية عمرها 20 عامًا، وما زالت الأدفأ',
      fr: '20 ans et toujours la couverture la plus chaude',
      es: '20 años y sigue siendo la manta más calentita',
      ja: '20年ものの毛布、今も一番あったかい',
      ko: '20년 된 담요, 아직도 제일 따뜻하다',
    },
  },
  {
    emoji: '🍵',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'günün ilk çayı',
        en: 'first cup of the day',
        de: 'erste tasse des tages',
        ar: 'أول كوب في اليوم',
        fr: 'première tasse du jour',
        es: 'primera taza del día',
        ja: '今日最初のお茶',
        ko: '하루의 첫 차',
      },
    },
    caption: {
      tr: 'balkonda 5 dakika huzur, sonra gün başladı',
      en: '5 quiet minutes on the balcony, then the day began',
      de: '5 minuten ruhe auf dem balkon, dann ging der tag los',
      ar: '5 دقائق من الهدوء في الشرفة، ثم بدأ اليوم',
      fr: '5 minutes de calme au balcon, puis la journée a commencé',
      es: '5 minutos de calma en el balcón y luego empezó el día',
      ja: 'ベランダで5分の平和、そして一日が始まった',
      ko: '베란다에서 5분의 평화, 그리고 하루 시작',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.naz,
    body: { format: 'dump', emojis: ['🛌', '🍪', '📺', '🧦', '🍿'] },
    caption: {
      tr: 'pazar özeti: yataktan 3 kez çıktım (ikisi mutfağa)',
      en: 'sunday recap: left the bed 3 times (twice for snacks)',
      de: 'sonntag: 3-mal aufgestanden (2-mal für snacks)',
      ar: 'ملخص العطلة: غادرت السرير 3 مرات (مرتان إلى المطبخ)',
      fr: 'dimanche : 3 sorties du lit (dont 2 vers le frigo)',
      es: 'resumen del domingo: salí de la cama 3 veces (2 a la cocina)',
      ja: '日曜のまとめ：ベッドを出たのは3回（2回は台所）',
      ko: '일요일 요약: 침대 밖으로 3번 나감 (2번은 부엌)',
    },
  },
  {
    emoji: '🥤',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🌅', '🧘', '🥤', '📓', '👟'] },
    caption: {
      tr: '5’te kalkma denemesi: fotolar güzel, ben bitik',
      en: "tried the 5am routine: great pics, i'm wrecked",
      de: '5-uhr-routine getestet: fotos top, ich bin platt',
      ar: 'جرّبت روتين الخامسة فجرًا: الصور رائعة وأنا منهك',
      fr: 'routine de 5 h testée : photos top, moi KO',
      es: 'rutina de las 5 a. m.: fotos geniales, yo sin pilas',
      ja: '朝5時起きに挑戦：写真は映え、私はボロボロ',
      ko: '새벽 5시 기상 도전: 사진은 예쁨, 나는 너덜너덜',
    },
  },
  {
    emoji: '🌟',
    user: ACCOUNTS.defne,
    body: { format: 'dump', emojis: ['🌟', '🛏️', '🌙', '☁️', '🧸'] },
    caption: {
      tr: 'yeni nevresimim yıldızlı, artık gökyüzünde uyuyorum',
      en: 'new sheets have stars on them. i sleep in the sky now',
      de: 'neue bettwäsche mit sternen. ich schlaf jetzt im himmel',
      ar: 'مفرش سريري الجديد مليء بالنجوم… صرت أنام في السماء',
      fr: 'housse de couette étoilée : je dors dans le ciel',
      es: 'sábanas nuevas con estrellas: ahora duermo en el cielo',
      ja: '新しい布団カバーは星柄。もう夜空で寝てる。',
      ko: '새 이불이 별무늬라 이제 밤하늘에서 잔다',
    },
  },
];

export const SLEEP_HOLD: readonly Draft[] = [
  {
    emoji: '🌬️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yastığın serin tarafı. Çabuk, ısınmadan!',
      en: 'The cool side of the pillow. Quick, before it warms up!',
      de: 'Die kühle Seite vom Kissen. Schnell, bevor sie warm wird!',
      ar: 'الجانب البارد من الوسادة. أسرع قبل أن يسخن!',
      fr: "Le côté frais de l'oreiller. Vite, avant qu'il chauffe !",
      es: 'El lado fresco de la almohada. ¡Rápido, que se calienta!',
      ja: '枕のひんやり面。温まる前に早く！',
      ko: '베개의 시원한 쪽. 데워지기 전에 얼른!',
    },
  },
  {
    emoji: '📆',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Pazartesi sandın. Cumartesiymiş!',
      en: "Thought it was Monday. It's Saturday!",
      de: 'Dachtest, es ist Montag. Es ist Samstag!',
      ar: 'ظننته يوم عمل… إنه يوم العطلة!',
      fr: "Tu croyais qu'on était lundi. C'est samedi !",
      es: 'Creías que era lunes. ¡Es sábado!',
      ja: '月曜だと思った。土曜日だった！',
      ko: '월요일인 줄 알았는데 토요일이다!',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sabahın ilk yudumu: günün en değerli 3 saniyesi',
      en: 'First sip of the morning: the best 3 seconds of the day',
      de: 'Erster Schluck am Morgen: die besten 3 Sekunden',
      ar: 'أول رشفة في الصباح: أغلى 3 ثوانٍ في اليوم',
      fr: 'Première gorgée du matin : les 3 meilleures secondes',
      es: 'El primer sorbo del día: los 3 mejores segundos',
      ja: '朝の最初のひと口：一日で最高の3秒',
      ko: '아침 첫 모금: 하루 중 가장 귀한 3초',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayıp çorabın teki 3 ay sonra yorgandan çıktı',
      en: 'The lost sock turned up in the duvet after 3 months',
      de: 'Die verschollene Socke: nach 3 Monaten im Bettbezug',
      ar: 'الجورب المفقود ظهر في اللحاف بعد 3 أشهر',
      fr: 'La chaussette perdue, retrouvée dans la couette après 3 mois',
      es: 'El calcetín perdido apareció en el edredón tras 3 meses',
      ja: 'なくした靴下が3か月ぶりに布団から出てきた',
      ko: '잃어버린 양말 한 짝이 3개월 만에 이불에서 나왔다',
    },
  },
  {
    emoji: '🌡️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yorgan tam kıvamında ısındı. Bırakmak yok!',
      en: "The duvet is perfectly warm. Don't let go!",
      de: 'Die Decke ist perfekt vorgewärmt. Nicht loslassen!',
      ar: 'اللحاف دافئ تمامًا. لا تتركه!',
      fr: 'La couette est pile à la bonne température. Tiens bon !',
      es: 'La manta está en su punto. ¡No la sueltes!',
      ja: '布団がちょうどいい温かさ。離さないで！',
      ko: '이불이 딱 알맞게 따뜻해졌다. 놓지 마세요!',
    },
  },
  {
    emoji: '💤',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi yetenek: başı yastığa değer değmez uyumak',
      en: 'Legendary skill: out the second your head hits the pillow',
      de: 'Legendäre Fähigkeit: sofort einschlafen',
      ar: 'موهبة أسطورية: النوم لحظة ملامسة رأسك للوسادة',
      fr: 'Talent légendaire : dormir dès la tête posée',
      es: 'Talento legendario: dormirte al tocar la almohada',
      ja: '伝説のスキル：枕に頭がついた瞬間に寝る',
      ko: '전설의 기술: 베개에 머리 닿자마자 잠들기',
    },
  },
  {
    emoji: '🔇',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Horlama durdu! Hemen uyu, fırsat bu fırsat',
      en: "The snoring stopped! Fall asleep now, it's your chance",
      de: 'Das Schnarchen hat aufgehört! Schnell einschlafen!',
      ar: 'توقّف الشخير! نَم الآن، إنها فرصتك',
      fr: "Les ronflements ont cessé ! Dors vite, c'est le moment",
      es: '¡Paró el ronquido! Duérmete ya, es tu oportunidad',
      ja: 'いびきが止まった！今のうちに寝て',
      ko: '코골이가 멈췄다! 지금이 기회, 얼른 자요',
    },
  },
];

export const SLEEP_FREEZE: readonly Draft[] = [
  {
    emoji: '🧟',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'TEHLİKE',
        en: 'DANGER',
        de: 'GEFAHR',
        ar: 'خطر',
        fr: 'DANGER',
        es: 'PELIGRO',
        ja: '危険',
        ko: '위험',
      },
      small: {
        tr: 'HENÜZ KAHVESİNİ İÇMEDİ',
        en: 'HAS NOT HAD COFFEE YET',
        de: 'HATTE NOCH KEINEN KAFFEE',
        ar: 'لم يشرب قهوته بعد',
        fr: "N'A PAS ENCORE BU SON CAFÉ",
        es: 'AÚN NO TOMÓ SU CAFÉ',
        ja: 'まだコーヒーを飲んでいない',
        ko: '아직 커피 안 마심',
      },
    },
    caption: {
      tr: 'Günaydın bile deme.',
      en: "Don't even say good morning.",
      de: 'Nicht mal Guten Morgen sagen.',
      ar: 'ولا تقل صباح الخير حتى.',
      fr: 'Même pas un bonjour.',
      es: 'Ni le digas buenos días.',
      ja: 'おはようも言わないで。',
      ko: '좋은 아침이라는 말도 하지 마세요.',
    },
    headline: {
      tr: 'Kahvesiz biri mutfakta dolaşıyor',
      en: 'Someone uncaffeinated is in the kitchen',
      de: 'Jemand ohne Kaffee ist in der Küche',
      ar: 'شخص بلا قهوة يتجوّل في المطبخ',
      fr: "Quelqu'un sans café rôde dans la cuisine",
      es: 'Alguien sin café anda por la cocina',
      ja: 'コーヒー前の人が台所をうろついてる',
      ko: '커피 안 마신 사람이 부엌을 돌아다녀요',
    },
  },
  {
    emoji: '🧖',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'GÜLMEK YASAK',
        en: 'NO LAUGHING',
        de: 'NICHT LACHEN',
        ar: 'ممنوع الضحك',
        fr: 'NE PAS RIRE',
        es: 'PROHIBIDO REÍR',
        ja: '笑い禁止',
        ko: '웃음 금지',
      },
      small: {
        tr: 'YÜZ MASKESİ KURUYOR',
        en: 'FACE MASK DRYING',
        de: 'GESICHTSMASKE TROCKNET',
        ar: 'قناع الوجه يجف',
        fr: 'MASQUE EN TRAIN DE SÉCHER',
        es: 'MASCARILLA SECÁNDOSE',
        ja: 'パック乾燥中',
        ko: '팩 마르는 중',
      },
    },
    caption: {
      tr: 'Gülersen çatlar. Tek mimik bile yapma.',
      en: 'Laugh and it cracks. Keep a straight face.',
      de: 'Lachen, und sie bröckelt. Pokerface!',
      ar: 'إن ضحكت تشقّق. حافظ على ملامحك.',
      fr: 'Un sourire et ça craque. Reste impassible.',
      es: 'Si te ríes, se agrieta. Cara seria.',
      ja: '笑ったらひび割れる。表情ひとつ変えないで。',
      ko: '웃으면 갈라져요. 표정 하나도 바꾸지 마세요.',
    },
    headline: {
      tr: 'Yüz maskesi tam kurumak üzere',
      en: 'Your face mask is almost dry',
      de: 'Deine Gesichtsmaske ist fast trocken',
      ar: 'قناع وجهك على وشك أن يجف',
      fr: 'Ton masque est presque sec',
      es: 'Tu mascarilla está casi seca',
      ja: 'パックがもうすぐ乾く',
      ko: '팩이 거의 다 말랐어요',
    },
  },
  {
    emoji: '🦖',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'PAZARTESİ',
        en: 'MONDAY',
        de: 'MONTAG',
        ar: 'بداية الأسبوع',
        fr: 'LUNDI',
        es: 'LUNES',
        ja: '月曜日',
        ko: '월요일',
      },
      small: {
        tr: 'ANİ HAREKET YAPMAYIN',
        en: 'NO SUDDEN MOVEMENTS',
        de: 'KEINE HEKTISCHEN BEWEGUNGEN',
        ar: 'لا حركات مفاجئة',
        fr: 'PAS DE GESTES BRUSQUES',
        es: 'NADA DE MOVIMIENTOS BRUSCOS',
        ja: '急に動かないこと',
        ko: '갑자기 움직이지 마세요',
      },
    },
    caption: {
      tr: 'Kıpırdamazsan belki görmez.',
      en: "Don't move. Maybe it won't see you.",
      de: 'Keine Bewegung. Vielleicht sieht er dich nicht.',
      ar: 'لا تتحرك، ربما لا يراك.',
      fr: 'Bouge pas, il te verra peut-être pas.',
      es: 'No te muevas. Quizá no te vea.',
      ja: '動かなければ、気づかれないかも。',
      ko: '가만있으면 못 볼지도 몰라요.',
    },
    headline: {
      tr: 'Pazartesi sabahı yaklaşıyor',
      en: 'Monday morning is getting closer',
      de: 'Der Montagmorgen kommt näher',
      ar: 'صباح أول يوم عمل يقترب',
      fr: 'Lundi matin approche',
      es: 'El lunes por la mañana se acerca',
      ja: '月曜の朝が近づいている',
      ko: '월요일 아침이 다가오고 있어요',
    },
  },
  {
    emoji: '🪟',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YATAK ODASI',
        en: 'BEDROOM',
        de: 'SCHLAFZIMMER',
        ar: 'غرفة النوم',
        fr: 'CHAMBRE',
        es: 'DORMITORIO',
        ja: '寝室',
        ko: '침실',
      },
    },
    caption: {
      tr: 'Gözlerini sımsıkı kapa.',
      en: 'Squeeze your eyes shut.',
      de: 'Augen fest zu.',
      ar: 'أغمض عينيك بقوة.',
      fr: 'Ferme les yeux très fort.',
      es: 'Cierra los ojos bien fuerte.',
      ja: '目をぎゅっとつぶって。',
      ko: '눈을 꼭 감으세요.',
    },
    headline: {
      tr: 'Annen perdeleri açmak üzere',
      en: "Mom's about to open the curtains",
      de: 'Mama reißt gleich die Vorhänge auf',
      ar: 'أمك على وشك فتح الستائر',
      fr: 'Maman va ouvrir grand les rideaux',
      es: 'Mamá va a abrir las cortinas',
      ja: 'お母さんがカーテンを開けようとしてる',
      ko: '엄마가 커튼을 걷으려고 해요',
    },
  },
  {
    emoji: '🥞',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SENİN ODAN',
        en: 'YOUR ROOM',
        de: 'DEIN ZIMMER',
        ar: 'غرفتك',
        fr: 'TA CHAMBRE',
        es: 'TU CUARTO',
        ja: 'あなたの部屋',
        ko: '내 방',
      },
    },
    caption: {
      tr: 'Çayı ağzına kadar doldurmuş. Kıpırdama.',
      en: "He filled the mug to the brim. Don't move.",
      de: 'Die Tasse ist randvoll. Keine Bewegung.',
      ar: 'ملأ الكوب حتى الحافة. لا تتحرك.',
      fr: 'Tasse remplie à ras bord. Bouge pas.',
      es: 'Llenó la taza hasta el borde. No te muevas.',
      ja: 'お茶がなみなみ。動かないで。',
      ko: '차를 넘치기 직전까지 채웠다. 움직이지 마세요.',
    },
    headline: {
      tr: 'Kardeşin yatağa kahvaltı getirdi',
      en: 'Little bro made you breakfast in bed',
      de: 'Dein Bruder bringt Frühstück ans Bett',
      ar: 'أخوك الصغير أحضر لك الفطور إلى السرير',
      fr: 'Petit-déj au lit, servi par ton frère',
      es: 'Tu hermanito te trajo desayuno a la cama',
      ja: '弟がベッドに朝ごはんを持ってきた',
      ko: '동생이 침대로 아침을 가져왔어요',
    },
  },
  {
    emoji: '👔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK',
        en: 'KITCHEN',
        de: 'KÜCHE',
        ar: 'المطبخ',
        fr: 'CUISINE',
        es: 'COCINA',
        ja: 'キッチン',
        ko: '부엌',
      },
    },
    caption: {
      tr: 'Elinde reçelli ekmek. Tek damla bile düşmesin.',
      en: "Jam toast in hand. Don't drip. Don't move.",
      de: 'Marmeladenbrot in der Hand. Bloß nicht tropfen.',
      ar: 'في يدك خبز بالمربى. لا تُسقط قطرة واحدة.',
      fr: 'Tartine de confiture en main. Pas une goutte.',
      es: 'Pan con mermelada en la mano. Ni una gota.',
      ja: 'ジャムトーストを手に。一滴も落とさないで。',
      ko: '손에 잼 바른 빵. 한 방울도 떨어뜨리지 마세요.',
    },
    headline: {
      tr: 'Baban ütülediği gömleğine bakıyor',
      en: "Dad's eyeing the shirt he just ironed",
      de: 'Papa mustert das frisch gebügelte Hemd',
      ar: 'أبوك ينظر إلى القميص الذي كواه للتو',
      fr: 'Papa inspecte ta chemise repassée',
      es: 'Papá revisa tu camisa recién planchada',
      ja: 'お父さんがアイロンしたシャツを見てる',
      ko: '아빠가 다린 셔츠를 보고 있어요',
    },
  },
  {
    emoji: '🧸',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇOCUK ODASI',
        en: "KIDS' ROOM",
        de: 'KINDERZIMMER',
        ar: 'غرفة الأطفال',
        fr: "CHAMBRE D'ENFANT",
        es: 'CUARTO DE NIÑOS',
        ja: '子ども部屋',
        ko: '아이 방',
      },
    },
    caption: {
      tr: 'Yorgan kalkandır. Dışarı çıkma.',
      en: 'The blanket is your shield. Stay under.',
      de: 'Die Decke ist dein Schild. Bleib drunter.',
      ar: 'البطانية درعك. ابقَ تحتها.',
      fr: 'La couette est ton bouclier. Reste dessous.',
      es: 'La manta es tu escudo. Quédate debajo.',
      ja: '布団は盾。外に出ないで。',
      ko: '이불은 방패다. 밖으로 나오지 마세요.',
    },
    headline: {
      tr: 'Yatağın altından bir tıkırtı geldi',
      en: 'Something rustled under the bed',
      de: 'Unterm Bett hat was geraschelt',
      ar: 'صدر صوت من تحت السرير',
      fr: 'Un bruit sous le lit',
      es: 'Algo sonó debajo de la cama',
      ja: 'ベッドの下からカタッと音がした',
      ko: '침대 밑에서 달그락 소리가 났어요',
    },
  },
];
