import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Sleep, mornings and routines: bedtime, naps, dreams, weekends, morning people, new habits.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const SLEEP_SKIP: readonly Draft[] = [
  {
    emoji: '🥛',
    user: ACCOUNTS.mornings,
    body: { format: 'scene' },
    caption: {
      tr: 'Gevreği buzdolabına, sütü dolaba koydum',
      en: 'Cereal in the fridge, milk in the pantry. Morning!',
      de: 'Müsli in den Kühlschrank, Milch in den Schrank. Morgen!',
      ar: 'الحبوب في الثلاجة، والحليب في الخزانة. صباح الخير!',
      fr: 'Céréales au frigo, lait dans le placard. Bonjour !',
      es: 'Cereal en la nevera, leche en la alacena. ¡Buenos días!',
    },
  },
  {
    emoji: '👕',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Tişört öğlene kadar tersti, kimse söylemedi',
      en: 'My shirt was inside out till noon. Nobody said a thing.',
      de: 'Shirt bis mittags auf links. Keiner hat was gesagt.',
      ar: 'ارتديت القميص مقلوبًا حتى الظهر، ولم ينبّهني أحد',
      fr: "T-shirt à l'envers jusqu'à midi. Personne n'a rien dit.",
      es: 'Camiseta al revés hasta el mediodía. Nadie dijo nada.',
    },
  },
  {
    emoji: '💭',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Rüyaya geri döndüm, kanal değişmiş',
      en: 'Went back to finish my dream. Channel changed.',
      de: 'Wollte weiterträumen. Anderer Sender.',
      ar: 'عدت إلى النوم لأكمل الحلم… فتغيّرت القناة',
      fr: 'Je me rendors pour la suite du rêve. Autre chaîne.',
      es: 'Volví a dormir para seguir el sueño. Otro canal.',
    },
  },
  {
    emoji: '🎓',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Rüyamda sınav vardı. 12 yıldır mezunum.',
      en: 'Dreamed I had an exam. I graduated 12 years ago.',
      de: 'Im Traum eine Prüfung. Mein Abschluss war vor 12 Jahren.',
      ar: 'حلمت أن لديّ امتحانًا… وقد تخرّجت قبل 12 عامًا',
      fr: "J'ai rêvé d'un exam. J'ai fini l'école il y a 12 ans.",
      es: 'Soñé que tenía un examen. Me gradué hace 12 años.',
    },
  },
  {
    emoji: '🪥',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Diş macunu üstüne portakal suyu. Hata.',
      en: 'Orange juice right after brushing. Big mistake.',
      de: 'Orangensaft direkt nach dem Zähneputzen. Fehler.',
      ar: 'عصير برتقال بعد تنظيف الأسنان مباشرة. خطأ فادح.',
      fr: "Jus d'orange juste après le dentifrice. Erreur.",
      es: 'Jugo de naranja tras cepillarme los dientes. Error.',
    },
  },
  {
    emoji: '🐑',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Koyun sayarken şaşırdım, baştan başladım',
      en: 'Lost count of the sheep. Starting over.',
      de: 'Beim Schäfchenzählen verzählt. Noch mal von vorn.',
      ar: 'أخطأت في عدّ الخراف، فبدأت من جديد',
      fr: 'Perdu le compte des moutons. On recommence.',
      es: 'Perdí la cuenta de las ovejas. Vuelvo a empezar.',
    },
  },
  {
    emoji: '🛌',
    user: ACCOUNTS.sleep,
    body: { format: 'scene' },
    caption: {
      tr: 'Kusursuz uyku pozisyonunu buldum. Sabah olmuş.',
      en: 'Found the perfect sleeping position. It was morning.',
      de: 'Die perfekte Schlafposition gefunden. Da war es Morgen.',
      ar: 'وجدت وضعية النوم المثالية… فإذا بالصباح قد حلّ',
      fr: "Trouvé la position parfaite pour dormir. C'était le matin.",
      es: 'Encontré la postura perfecta para dormir. Ya era de día.',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'dün gece uykunda bağırdın',
            en: 'you yelled in your sleep last night',
            de: 'du hast letzte Nacht im Schlaf geschrien',
            ar: 'صرخت وأنت نائم ليلة أمس',
            fr: "t'as crié en dormant cette nuit",
            es: 'anoche gritaste en sueños',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ne dedim ki? 😳',
            en: 'what did I say? 😳',
            de: 'was hab ich gesagt? 😳',
            ar: 'ماذا قلت؟ 😳',
            fr: "j'ai dit quoi ? 😳",
            es: '¿qué dije? 😳',
          },
        },
        {
          from: 'them',
          text: {
            tr: '“O BÖREK BENİM, KİMSE DOKUNMASIN!”',
            en: '“NOBODY TOUCHES MY WAFFLES!”',
            de: '„FINGER WEG VON MEINEN WAFFELN!“',
            ar: '«لا أحد يلمس فطائري!»',
            fr: '« PERSONNE NE TOUCHE À MES CRÊPES ! »',
            es: '“¡NADIE TOCA MIS GALLETAS!”',
          },
        },
      ],
    },
    caption: {
      tr: 'Rüyamda bile yemeğimi koruyorum',
      en: 'Guarding my food even in my sleep',
      de: 'Ich verteidige mein Essen sogar im Schlaf',
      ar: 'أحمي طعامي حتى في أحلامي',
      fr: 'Je défends ma bouffe même en rêve',
      es: 'Defiendo mi comida hasta en sueños',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.motivation,
    body: {
      format: 'chat',
      contact: {
        tr: 'Dün gece ben',
        en: 'Last-night me',
        de: 'Ich, gestern Nacht',
        ar: 'أنا ليلة أمس',
        fr: "Moi d'hier soir",
        es: 'Yo de anoche',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yarın 06.00: koşu, yoga, yeşil smoothie ✨',
            en: 'tomorrow 6am: run, yoga, green smoothie ✨',
            de: 'morgen 6 Uhr: Joggen, Yoga, Smoothie ✨',
            ar: 'غدًا في السادسة: جري، يوغا، عصير أخضر ✨',
            fr: 'demain 6 h : footing, yoga, smoothie vert ✨',
            es: 'mañana 6:00: correr, yoga, batido verde ✨',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bu sefer ciddiyim 💪',
            en: 'I mean it this time 💪',
            de: "diesmal mein ich's ernst 💪",
            ar: 'هذه المرة أنا جاد 💪',
            fr: "cette fois c'est sérieux 💪",
            es: 'esta vez va en serio 💪',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'pardon, kimsiniz?',
            en: 'sorry, who is this?',
            de: 'sorry, wer ist da?',
            ar: 'عذرًا، من معي؟',
            fr: "pardon, c'est qui ?",
            es: 'perdón, ¿quién eres?',
          },
        },
      ],
    },
    caption: {
      tr: 'Gece ben planlar, sabah ben reddeder',
      en: 'Night me makes plans. Morning me declines.',
      de: 'Nacht-Ich plant. Morgen-Ich lehnt ab.',
      ar: 'أنا ليلًا أخطط، وأنا صباحًا أرفض',
      fr: 'Moi le soir : des plans. Moi le matin : non.',
      es: 'El yo de la noche planea. El de la mañana, no.',
    },
  },
  {
    emoji: '🤥',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'uyandırdım mı?',
            en: 'did I wake you?',
            de: 'hab ich dich geweckt?',
            ar: 'هل أيقظتك؟',
            fr: 'je te réveille ?',
            es: '¿te desperté?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yok ane, çoktan klaktım',
            en: 'nope, bene up for hourss',
            de: 'nee, bin shcon lagne wach',
            ar: 'لا يا أمي، استيظقت منذ ساعات',
            fr: 'non, jsuis debout dpuis des heurs',
            es: 'no, mamá, me levnaté hace hroas',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yazından belli 🙂',
            en: 'I can tell 🙂',
            de: 'merkt man 🙂',
            ar: 'واضح من كتابتك 🙂',
            fr: 'ça se voit 🙂',
            es: 'se nota 🙂',
          },
        },
      ],
    },
    caption: {
      tr: 'Annemden hiçbir şey saklanmıyor',
      en: "You can't fool a mom",
      de: 'Mamas merken einfach alles',
      ar: 'لا شيء يخفى على أمي',
      fr: 'On ne ment pas à une maman',
      es: 'A una mamá no se le escapa nada',
    },
  },
  {
    emoji: '🌄',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sabahçı Kanka',
        en: 'Early Bird',
        de: 'Frühaufsteher',
        ar: 'صديقي الصباحي',
        fr: 'Pote lève-tôt',
        es: 'Amigo madrugador',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'günaydııın ☀️ güneş doğuyor, kalk!',
            en: "morninggg ☀️ sun's coming up, get up!",
            de: 'Mooorgen ☀️ Sonnenaufgang, steh auf!',
            ar: 'صباح الخيرررر ☀️ الشمس تشرق، انهض!',
            fr: 'bonjouuur ☀️ le soleil se lève, debout !',
            es: '¡buenos díaaas ☀️ sale el sol, arriba!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'saat kaç?',
            en: 'what time is it',
            de: 'wie spät ist es?',
            ar: 'كم الساعة؟',
            fr: 'il est quelle heure ?',
            es: '¿qué hora es?',
          },
        },
        {
          from: 'them',
          text: {
            tr: '05.47 😊',
            en: '5:47 😊',
            de: '5:47 😊',
            ar: '5:47 😊',
            fr: '5 h 47 😊',
            es: '5:47 😊',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'güneşe selamımı söyle',
            en: 'tell the sun I said hi',
            de: 'grüß die Sonne von mir',
            ar: 'بلّغ الشمس سلامي',
            fr: 'passe le bonjour au soleil',
            es: 'salúdame al sol',
          },
        },
      ],
    },
    caption: {
      tr: 'Her grupta bir sabahçı vardır',
      en: 'Every group has one morning person',
      de: 'Jede Clique hat einen Frühaufsteher',
      ar: 'في كل مجموعة شخص صباحي واحد',
      fr: 'Chaque bande a son lève-tôt',
      es: 'Todo grupo tiene un madrugador',
    },
  },
  {
    emoji: '🌗',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah insanı mısın, gece kuşu mu?',
        en: 'Morning person or night owl?',
        de: 'Morgenmensch oder Nachteule?',
        ar: 'هل أنت صباحي أم ليلي؟',
        fr: 'Plutôt du matin ou du soir ?',
        es: '¿Eres más de mañana o de noche?',
      },
      options: [
        {
          tr: 'Sabah insanı ☀️',
          en: 'Morning person ☀️',
          de: 'Morgenmensch ☀️',
          ar: 'صباحي ☀️',
          fr: 'Du matin ☀️',
          es: 'De mañana ☀️',
        },
        {
          tr: 'Gece kuşu 🦉',
          en: 'Night owl 🦉',
          de: 'Nachteule 🦉',
          ar: 'ليلي 🦉',
          fr: 'Du soir 🦉',
          es: 'De noche 🦉',
        },
        {
          tr: 'Hiçbiri, yorgunum',
          en: 'Neither. Just tired.',
          de: 'Keins, nur müde',
          ar: 'لا هذا ولا ذاك، متعب',
          fr: 'Aucun, juste KO',
          es: 'Ninguno, tengo sueño',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'En verimli saatim: 14.00 ile 14.15 arası',
      en: 'My productive hours: 2:00 to 2:15 p.m.',
      de: 'Produktiv bin ich von 14:00 bis 14:15 Uhr',
      ar: 'ساعتي المنتجة: من 2:00 إلى 2:15 ظهرًا',
      fr: 'Mon pic de forme : de 14 h à 14 h 15',
      es: 'Mi hora productiva: de 14:00 a 14:15',
    },
  },
  {
    emoji: '🥴',
    user: ACCOUNTS.mornings,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah ilk kelimen genelde ne olur?',
        en: 'Your first word in the morning?',
        de: 'Dein erstes Wort am Morgen?',
        ar: 'ما أول كلمة تقولها في الصباح؟',
        fr: 'Ton premier mot le matin ?',
        es: '¿Tu primera palabra por la mañana?',
      },
      options: [
        {
          tr: 'Günaydın!',
          en: 'Good morning!',
          de: 'Guten Morgen!',
          ar: 'صباح الخير!',
          fr: 'Bonjour !',
          es: '¡Buenos días!',
        },
        { tr: 'Hıı?', en: 'Huh?', de: 'Hä?', ar: 'هاه؟', fr: 'Hein ?', es: '¿Eh?' },
      ],
      winner: 1,
    },
    caption: {
      tr: 'İlk düzgün cümlem öğlene doğru gelir',
      en: 'First full sentence arrives around noon',
      de: 'Der erste ganze Satz kommt gegen Mittag',
      ar: 'أول جملة كاملة تصل قرب الظهر',
      fr: 'Première phrase complète : vers midi',
      es: 'Mi primera frase completa llega al mediodía',
    },
  },
  {
    emoji: '🦥',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Sabah yataktan nasıl çıkarsın?',
        en: 'How do you get out of bed?',
        de: 'Wie kommst du morgens aus dem Bett?',
        ar: 'كيف تنهض من السرير صباحًا؟',
        fr: 'Tu sors du lit comment, le matin ?',
        es: '¿Cómo te levantas de la cama?',
      },
      options: [
        {
          tr: 'Tek zıplayışta',
          en: 'One jump, done',
          de: 'Mit einem Sprung',
          ar: 'بقفزة واحدة',
          fr: "D'un bond",
          es: 'De un salto',
        },
        {
          tr: 'Yuvarlanarak, yavaşça',
          en: 'Slow roll, then flop',
          de: 'Rausrollen, langsam',
          ar: 'أتدحرج ببطء',
          fr: 'En roulant, lentement',
          es: 'Rodando, muy despacio',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Yere kütük gibi iniyorum. Çok zarif.',
      en: 'I land on the floor like a log. Very graceful.',
      de: 'Ich lande wie ein Baumstamm. Sehr elegant.',
      ar: 'أهبط على الأرض كجذع شجرة. بمنتهى الأناقة.',
      fr: "J'atterris comme une bûche. Tout en grâce.",
      es: 'Aterrizo en el suelo como un tronco. Muy elegante.',
    },
  },
  {
    emoji: '🦒',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'RÜYADAN AKLIMDA KALAN',
        en: 'DREAM RECALL',
        de: 'ERINNERUNG AN DEN TRAUM',
        ar: 'ما بقي من حلمي',
        fr: 'SOUVENIR DU RÊVE',
        es: 'RECUERDO DEL SUEÑO',
      },
      value: {
        tr: '%3',
        en: '3%',
        de: '3 %',
        ar: '3%',
        fr: '3 %',
        es: '3 %',
      },
      shape: 'fall',
      axis: 'hours',
    },
    caption: {
      tr: 'Öğlene kalan tek şey: bir zürafa vardı galiba',
      en: 'By noon: there was a giraffe, I think?',
      de: 'Bis mittags bleibt: Da war eine Giraffe, oder?',
      ar: 'عند الظهر لم يبقَ إلا: كانت هناك زرافة، على ما أظن',
      fr: 'À midi, il reste : il y avait une girafe, je crois',
      es: 'Al mediodía solo queda: había una jirafa, creo',
    },
  },
  {
    emoji: '🌇',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'PAZAR KEYFİM',
        en: 'MY SUNDAY MOOD',
        de: 'MEINE SONNTAGSLAUNE',
        ar: 'مزاجي في آخر العطلة',
        fr: 'MON MORAL DU DIMANCHE',
        es: 'MI HUMOR DEL DOMINGO',
      },
      value: null,
      shape: 'crash',
      axis: 'hours',
    },
    caption: {
      tr: 'Saat 18.00’de pazartesi aklıma geldi',
      en: 'Then at 6 p.m. I remembered Monday',
      de: 'Um 18 Uhr fiel mir der Montag ein',
      ar: 'في السادسة مساءً تذكّرت أن غدًا يوم عمل',
      fr: "À 18 h, j'ai pensé à lundi",
      es: 'A las 6 de la tarde me acordé del lunes',
    },
  },
  {
    emoji: '🥯',
    user: ACCOUNTS.mornings,
    body: {
      format: 'chart',
      title: {
        tr: 'KAHVALTI SÜREM',
        en: 'MY BREAKFAST TIME',
        de: 'MEINE FRÜHSTÜCKSZEIT',
        ar: 'مدة فطوري',
        fr: 'DURÉE DE MON PETIT-DÉJ',
        es: 'MI TIEMPO DE DESAYUNO',
      },
      value: null,
      shape: 'rise',
      axis: 'days',
    },
    caption: {
      tr: 'Hafta içi 40 saniye, hafta sonu 3 saat',
      en: 'Weekdays: 40 seconds. Weekends: 3 hours.',
      de: 'Unter der Woche 40 Sekunden, am Wochenende 3 Stunden',
      ar: 'أيام العمل: 40 ثانية. العطلة: 3 ساعات.',
      fr: 'En semaine : 40 secondes. Le week-end : 3 heures.',
      es: 'Entre semana, 40 segundos. Fin de semana, 3 horas.',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'ZÜCCACİYE',
        en: 'HOUSEWARES',
        de: 'HAUSHALTSWAREN',
        ar: 'الأدوات المنزلية',
        fr: 'ARTS DE LA TABLE',
        es: 'TIENDA DE HOGAR',
      },
      items: [
        {
          tr: 'DEV KUPA (1 LİTRE)',
          en: 'GIANT MUG (1 LITER)',
          de: 'RIESENTASSE (1 LITER)',
          ar: 'كوب عملاق (1 لتر)',
          fr: 'MUG GÉANT (1 LITRE)',
          es: 'TAZA GIGANTE (1 LITRO)',
        },
      ],
    },
    caption: {
      tr: 'Günde tek kahve kuralı. Teknik olarak.',
      en: 'One coffee a day. Technically.',
      de: 'Ein Kaffee am Tag. Technisch gesehen.',
      ar: 'قاعدتي: كوب قهوة واحد في اليوم. تقنيًا.',
      fr: 'Un seul café par jour. Techniquement.',
      es: 'Un solo café al día. Técnicamente.',
    },
  },
  {
    emoji: '🌅',
    user: ACCOUNTS.sleep,
    body: {
      format: 'receipt',
      store: {
        tr: 'AYDINLATMA',
        en: 'LIGHTING STORE',
        de: 'LAMPENLADEN',
        ar: 'متجر الإنارة',
        fr: 'LUMINAIRES',
        es: 'ILUMINACIÓN',
      },
      items: [
        {
          tr: 'GÜN DOĞUMU LAMBASI',
          en: 'SUNRISE LAMP',
          de: 'LICHTWECKER',
          ar: 'مصباح شروق الشمس',
          fr: 'LAMPE LEVER DE SOLEIL',
          es: 'LÁMPARA AMANECER',
        },
      ],
    },
    caption: {
      tr: 'Lamba doğdu. Ben kalkmadım.',
      en: 'The lamp rose. I did not.',
      de: 'Die Lampe ist aufgegangen. Ich nicht.',
      ar: 'أشرق المصباح. أما أنا فلا.',
      fr: "La lampe s'est levée. Moi, non.",
      es: 'La lámpara amaneció. Yo no.',
    },
  },
  {
    emoji: '🚿',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU SABAH',
        en: 'THIS MORNING',
        de: 'HEUTE MORGEN',
        ar: 'هذا الصباح',
        fr: 'CE MATIN',
        es: 'ESTA MAÑANA',
      },
      big: { tr: '12', en: '12', de: '12', ar: '12', fr: '12', es: '12' },
      text: {
        tr: 'dakika duşta öylece durdun; uyanmayı bekledin',
        en: 'minutes standing in the shower, waiting to wake up',
        de: 'Minuten reglos unter der Dusche, bis du wach warst',
        ar: 'دقيقة وقفت تحت الدش تنتظر أن تستيقظ',
        fr: 'minutes sous la douche sans bouger, à attendre le réveil',
        es: 'minutos bajo la ducha sin moverte, esperando despertar',
      },
    },
    caption: {
      tr: 'Ayakta şekerleme de şekerlemedir',
      en: 'A standing nap is still a nap',
      de: 'Ein Nickerchen im Stehen zählt auch',
      ar: 'القيلولة واقفًا تبقى قيلولة',
      fr: 'Une sieste debout reste une sieste',
      es: 'Una siesta de pie sigue siendo siesta',
    },
  },
  {
    emoji: '👗',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'DOLABINDA',
        en: 'IN YOUR CLOSET',
        de: 'IM KLEIDERSCHRANK',
        ar: 'في خزانتك',
        fr: 'DANS TON PLACARD',
        es: 'EN TU ARMARIO',
      },
      big: { tr: '143', en: '143', de: '143', ar: '143', fr: '143', es: '143' },
      text: {
        tr: 'parça kıyafetin var; giyecek hiçbir şeyin yok',
        en: 'pieces of clothing, and nothing to wear',
        de: 'Kleidungsstücke – und nichts zum Anziehen',
        ar: 'قطعة ملابس… ولا شيء ترتديه',
        fr: 'vêtements, et rien à te mettre',
        es: 'prendas de ropa, y nada que ponerte',
      },
    },
    caption: {
      tr: 'Yine o gri kazak',
      en: 'The gray sweater again',
      de: 'Wieder der graue Pulli',
      ar: 'السترة الرمادية نفسها مجددًا',
      fr: 'Encore le pull gris',
      es: 'Otra vez el suéter gris',
    },
  },
  {
    emoji: '🥱',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'ŞU AN',
        en: 'RIGHT NOW',
        de: 'GENAU JETZT',
        ar: 'الآن',
        fr: 'EN CE MOMENT',
        es: 'AHORA MISMO',
      },
      big: { tr: '1', en: '1', de: '1', ar: '1', fr: '1', es: '1' },
      text: {
        tr: 'kez esnedin; sadece bunu okuduğun için',
        en: 'yawn, just from reading this',
        de: 'Mal gegähnt, nur weil du das liest',
        ar: 'تثاؤب، فقط لأنك تقرأ هذا',
        fr: "bâillement, rien qu'en lisant ça",
        es: 'bostezo, solo por leer esto',
      },
    },
    caption: {
      tr: 'Yanındaki de esnedi, bak',
      en: 'Look, the person next to you just yawned',
      de: 'Guck, dein Nachbar gähnt auch',
      ar: 'انظر، من بجانبك تثاءب أيضًا',
      fr: 'Regarde, ton voisin bâille aussi',
      es: 'Mira, el de al lado también bostezó',
    },
  },
  {
    emoji: '🌯',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'UYKU POZİSYONU TIER LIST',
        en: 'SLEEP POSITION TIER LIST',
        de: 'SCHLAFPOSITIONEN-RANKING',
        ar: 'تصنيف وضعيات النوم',
        fr: 'TIER LIST POSITIONS DODO',
        es: 'POSTURAS PARA DORMIR',
      },
      rows: [['🌯', '🥐'], ['⭐️'], ['🪵'], ['🦇']],
    },
    caption: {
      tr: 'Yarasa pozisyonunu denedim, önermem',
      en: 'Tried the bat position. Do not recommend.',
      de: 'Fledermaus-Position getestet. Nicht empfehlenswert.',
      ar: 'جرّبت وضعية الخفاش، لا أنصح بها',
      fr: "J'ai testé la chauve-souris. Je déconseille.",
      es: 'Probé la postura murciélago. No la recomiendo.',
    },
  },
  {
    emoji: '🧠',
    user: ACCOUNTS.asmr,
    body: {
      format: 'tier',
      title: {
        tr: 'YATMADAN ÖNCE TIER LIST',
        en: 'BEDTIME TIER LIST',
        de: 'EINSCHLAF-RANKING',
        ar: 'تصنيف ما قبل النوم',
        fr: 'TIER LIST AVANT DODO',
        es: 'TIER LIST ANTES DE DORMIR',
      },
      rows: [['🌧️', '📖'], ['🍵', '🕯️'], ['🐑'], ['🧠']],
    },
    caption: {
      tr: 'Beynim her gece 2014’teki o anıyı açıyor',
      en: 'Every night my brain replays that thing from 2014',
      de: 'Mein Hirn spielt jede Nacht die Sache von 2014 ab',
      ar: 'كل ليلة يعيد دماغي ذلك الموقف المحرج من 2014',
      fr: 'Chaque nuit, mon cerveau rejoue ce truc de 2014',
      es: 'Cada noche mi cerebro repite aquello de 2014',
    },
  },
  {
    emoji: '🥙',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '⌚',
        app: {
          tr: 'Uyku takibi',
          en: 'Sleep tracker',
          de: 'Schlaftracker',
          ar: 'متتبّع النوم',
          fr: 'Suivi du sommeil',
          es: 'Monitor de sueño',
        },
        text: {
          tr: 'Dün gece yatakta 47 kez döndün',
          en: 'You flipped over 47 times last night',
          de: 'Letzte Nacht 47-mal umgedreht',
          ar: 'تقلّبت في السرير 47 مرة الليلة الماضية',
          fr: 'Cette nuit : 47 demi-tours dans le lit',
          es: 'Anoche diste 47 vueltas en la cama',
        },
      },
    },
    caption: {
      tr: 'Resmen döner gibiyim',
      en: 'Basically a rotisserie chicken',
      de: 'Ich bin quasi ein Grillhähnchen',
      ar: 'صرت مثل سيخ الشاورما',
      fr: 'Un vrai poulet rôti',
      es: 'Soy un pollo asado girando',
    },
  },
  {
    emoji: '🧘',
    user: ACCOUNTS.motivation,
    body: {
      format: 'notifications',
      first: {
        icon: '✅',
        app: {
          tr: 'Alışkanlıklar',
          en: 'Habit tracker',
          de: 'Gewohnheiten',
          ar: 'تتبّع العادات',
          fr: 'Habitudes',
          es: 'Hábitos',
        },
        text: {
          tr: 'Bugünkü hedef: 10 dakika meditasyon',
          en: "Today's goal: 10 minutes of meditation",
          de: 'Heutiges Ziel: 10 Minuten Meditation',
          ar: 'هدف اليوم: 10 دقائق من التأمل',
          fr: 'Objectif du jour : 10 min de méditation',
          es: 'Meta de hoy: 10 minutos de meditación',
        },
      },
    },
    caption: {
      tr: '10 dakikada aklıma 47 yapılacak iş geldi',
      en: 'Remembered 47 things to do in those 10 minutes',
      de: 'In 10 Minuten fielen mir 47 To-dos ein',
      ar: 'في 10 دقائق تذكّرت 47 مهمة',
      fr: 'En 10 minutes, 47 choses à faire me sont revenues',
      es: 'En 10 minutos recordé 47 pendientes',
    },
  },
  {
    emoji: '🥺',
    user: ACCOUNTS.sleep,
    body: {
      format: 'notifications',
      first: {
        icon: '🛏️',
        app: { tr: 'Yatağın', en: 'Your bed', de: 'Dein Bett', ar: 'سريرك', fr: 'Ton lit', es: 'Tu cama' },
        text: {
          tr: 'Neredesin? Seni özledim 🥺',
          en: 'Where are you? I miss you 🥺',
          de: 'Wo bleibst du? Ich vermisse dich 🥺',
          ar: 'أين أنت؟ اشتقت إليك 🥺',
          fr: "T'es où ? Tu me manques 🥺",
          es: '¿Dónde estás? Te extraño 🥺',
        },
      },
    },
    caption: {
      tr: 'Saat daha 20.30 ama haklı',
      en: "It's only 8:30 p.m., but it has a point",
      de: 'Es ist erst 20:30 Uhr, aber es hat recht',
      ar: 'الساعة الثامنة والنصف فقط، لكنه محق',
      fr: "Il n'est que 20 h 30, mais il a raison",
      es: 'Son apenas las 20:30, pero tiene razón',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Erken kalkan yol alır. Ben zaten hiçbir yere gitmiyorum.',
        en: "The early bird gets the worm. Good thing I don't want a worm.",
        de: 'Der frühe Vogel fängt den Wurm. Ich will aber gar keinen Wurm.',
        ar: 'الطائر المبكر يلتقط الدودة. ولحسن الحظ، لا أريد دودة.',
        fr: "L'avenir est à ceux qui se lèvent tôt. Je le prendrai à midi.",
        es: 'Pájaro que madruga atrapa el gusano. Por suerte, no quiero gusanos.',
      },
    },
    caption: {
      tr: 'Mantığım sağlam',
      en: 'Airtight logic',
      de: 'Wasserdichte Logik',
      ar: 'منطق لا يُردّ',
      fr: 'Logique imparable',
      es: 'Lógica impecable',
    },
  },
  {
    emoji: '👀',
    user: ACCOUNTS.mornings,
    body: {
      format: 'quote',
      text: {
        tr: 'Sabahları gülümse. Ya da en azından gözlerini aç.',
        en: 'Smile every morning. Or at least open your eyes.',
        de: 'Lächle jeden Morgen. Oder öffne wenigstens die Augen.',
        ar: 'ابتسم كل صباح. أو افتح عينيك على الأقل.',
        fr: 'Souris chaque matin. Ou ouvre au moins les yeux.',
        es: 'Sonríe cada mañana. O al menos abre los ojos.',
      },
    },
    caption: {
      tr: 'Adım adım',
      en: 'Baby steps',
      de: 'Schritt für Schritt',
      ar: 'خطوة خطوة',
      fr: 'Petit à petit',
      es: 'Paso a paso',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Dinlenmek de üretkenliktir. Bugün çok üretken geçti.',
        en: 'Rest is productive too. Today was extremely productive.',
        de: 'Ausruhen ist auch produktiv. Heute war ich sehr produktiv.',
        ar: 'الراحة إنتاجية أيضًا. وكان يومي منتجًا جدًا.',
        fr: "Se reposer, c'est productif aussi. Journée très productive.",
        es: 'Descansar también es productivo. Hoy rendí muchísimo.',
      },
    },
    caption: {
      tr: 'Kanepeden bildiriyorum',
      en: 'Reporting live from the couch',
      de: 'Live vom Sofa',
      ar: 'أنقل لكم مباشرة من الأريكة',
      fr: 'En direct du canapé',
      es: 'En vivo desde el sofá',
    },
  },
  {
    emoji: '🪶',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kendine yatırım yap. Mesela iyi bir yastığa.',
        en: 'Invest in yourself. Starting with a good pillow.',
        de: 'Investiere in dich selbst. Zum Beispiel in ein gutes Kissen.',
        ar: 'استثمر في نفسك. في وسادة جيدة مثلًا.',
        fr: 'Investis en toi-même. Par exemple, dans un bon oreiller.',
        es: 'Invierte en ti. Por ejemplo, en una buena almohada.',
      },
    },
    caption: {
      tr: 'Portföyüm: 7 yastık',
      en: 'My portfolio: 7 pillows',
      de: 'Mein Portfolio: 7 Kissen',
      ar: 'محفظتي الاستثمارية: 7 وسائد',
      fr: 'Mon portefeuille : 7 oreillers',
      es: 'Mi portafolio: 7 almohadas',
    },
  },
  {
    emoji: '📔',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Günlük tut, dediler. Tuttum. Hâlâ elimde, bomboş.',
        en: 'Keep a journal, they said. So I kept it. Still blank.',
        de: 'Führ ein Tagebuch, sagten sie. Hab eins gekauft. Seite 1: leer.',
        ar: 'قالوا: احتفظ بمذكرات. فاحتفظت بالدفتر… فارغًا.',
        fr: "Tiens un journal, qu'ils disaient. Je le tiens. Toujours vide.",
        es: 'Lleva un diario, me dijeron. Lo llevo a todas partes. Vacío.',
      },
    },
    caption: {
      tr: 'Kalemlerini de aldım ama',
      en: 'I did buy the fancy pens, though',
      de: 'Die schönen Stifte hab ich aber',
      ar: 'لكنني اشتريت الأقلام الملوّنة',
      fr: "J'ai quand même acheté les jolis stylos",
      es: 'Pero sí compré los bolígrafos bonitos',
    },
  },
];

export const SLEEP_LIKE: readonly Draft[] = [
  {
    emoji: '🛋️',
    user: ACCOUNTS.cemre,
    body: { format: 'scene' },
    caption: {
      tr: 'yastıklardan kale yaptım. giriş şifreyle.',
      en: 'built a pillow fort. password required.',
      de: 'kissenburg gebaut. eintritt nur mit passwort.',
      ar: 'بنيت قلعة من الوسائد، والدخول بكلمة سر',
      fr: 'fort en coussins terminé. entrée sur mot de passe.',
      es: 'hice un fuerte de almohadas. se entra con contraseña.',
    },
  },
  {
    emoji: '🎶',
    user: ACCOUNTS.melis,
    body: { format: 'scene' },
    caption: {
      tr: 'kardeşime ninni söyledim, önce ben uyudum',
      en: 'sang my little brother a lullaby. i fell asleep first',
      de: 'schlaflied für meinen bruder. ich war zuerst weg',
      ar: 'غنّيت لأخي الصغير تهويدة… فنمت أنا أولًا',
      fr: "berceuse pour mon petit frère. c'est moi qui ai dormi",
      es: 'le canté para que durmiera y me dormí yo',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.ipek,
    body: { format: 'scene' },
    caption: {
      tr: 'rüyamda uçtum, unutmadan çizdim',
      en: 'flew in my dream, drew it before i forgot',
      de: "im traum geflogen, schnell gemalt, bevor ich's vergesse",
      ar: 'طرت في حلمي، ورسمته قبل أن أنساه',
      fr: "j'ai volé en rêve, dessiné avant d'oublier",
      es: 'volé en un sueño y lo dibujé antes de olvidarlo',
    },
  },
  {
    emoji: '🦁',
    user: ACCOUNTS.yagmur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'uyandığım gibi',
        en: 'just woke up',
        de: 'frisch aufgewacht',
        ar: 'كما استيقظت تمامًا',
        fr: 'au saut du lit',
        es: 'al despertar',
      },
    },
    caption: {
      tr: 'saçım bu sabah kendi kararlarını veriyor',
      en: 'my hair is making its own decisions today',
      de: 'meine haare treffen heute eigene entscheidungen',
      ar: 'شعري يتخذ قراراته بنفسه اليوم',
      fr: 'mes cheveux prennent leurs propres décisions',
      es: 'mi pelo hoy toma sus propias decisiones',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni uyku maskem',
        en: 'new sleep mask',
        de: 'neue schlafmaske',
        ar: 'قناع نومي الجديد',
        fr: 'nouveau masque de nuit',
        es: 'antifaz nuevo',
      },
    },
    caption: {
      tr: 'üstünde kaş var, uyurken bile şaşkınım',
      en: 'it has eyebrows. i look shocked in my sleep',
      de: 'hat augenbrauen drauf. ich schlafe jetzt schockiert',
      ar: 'عليه حاجبان… أبدو مصدومًا حتى وأنا نائم',
      fr: 'il a des sourcils : je dors avec un air étonné',
      es: 'tiene cejas: duermo con cara de sorpresa',
    },
  },
  {
    emoji: '🧶',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'anneannemin eseri',
        en: 'grandma made this',
        de: 'von oma gestrickt',
        ar: 'من صنع جدتي',
        fr: 'tricotée par mamie',
        es: 'tejida por la abuela',
      },
    },
    caption: {
      tr: '20 yıllık battaniye, hâlâ en sıcağı',
      en: '20 years old and still the coziest blanket',
      de: '20 jahre alt und immer noch die wärmste decke',
      ar: 'بطانية عمرها 20 عامًا، وما زالت الأدفأ',
      fr: '20 ans et toujours la couverture la plus chaude',
      es: '20 años y sigue siendo la manta más calentita',
    },
  },
  {
    emoji: '🍵',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'günün ilk çayı',
        en: 'first cup of the day',
        de: 'erste tasse des tages',
        ar: 'أول كوب في اليوم',
        fr: 'première tasse du jour',
        es: 'primera taza del día',
      },
    },
    caption: {
      tr: 'balkonda 5 dakika huzur, sonra gün başladı',
      en: '5 quiet minutes on the balcony, then the day began',
      de: '5 minuten ruhe auf dem balkon, dann ging der tag los',
      ar: '5 دقائق من الهدوء في الشرفة، ثم بدأ اليوم',
      fr: '5 minutes de calme au balcon, puis la journée a commencé',
      es: '5 minutos de calma en el balcón y luego empezó el día',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.naz,
    body: { format: 'dump', emojis: ['🛌', '🍪', '📺', '🧦', '🍿'] },
    caption: {
      tr: 'pazar özeti: yataktan 3 kez çıktım (ikisi mutfağa)',
      en: 'sunday recap: left the bed 3 times (twice for snacks)',
      de: 'sonntag: 3-mal aufgestanden (2-mal für snacks)',
      ar: 'ملخص العطلة: غادرت السرير 3 مرات (مرتان إلى المطبخ)',
      fr: 'dimanche : 3 sorties du lit (dont 2 vers le frigo)',
      es: 'resumen del domingo: salí de la cama 3 veces (2 a la cocina)',
    },
  },
  {
    emoji: '🥤',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🌅', '🧘', '🥤', '📓', '👟'] },
    caption: {
      tr: '5’te kalkma denemesi: fotolar güzel, ben bitik',
      en: "tried the 5am routine: great pics, i'm wrecked",
      de: '5-uhr-routine getestet: fotos top, ich bin platt',
      ar: 'جرّبت روتين الخامسة فجرًا: الصور رائعة وأنا منهك',
      fr: 'routine de 5 h testée : photos top, moi KO',
      es: 'rutina de las 5 a. m.: fotos geniales, yo sin pilas',
    },
  },
  {
    emoji: '🌟',
    user: ACCOUNTS.defne,
    body: { format: 'dump', emojis: ['🌟', '🛏️', '🌙', '☁️', '🧸'] },
    caption: {
      tr: 'yeni nevresimim yıldızlı, artık gökyüzünde uyuyorum',
      en: 'new sheets have stars on them. i sleep in the sky now',
      de: 'neue bettwäsche mit sternen. ich schlaf jetzt im himmel',
      ar: 'مفرش سريري الجديد مليء بالنجوم… صرت أنام في السماء',
      fr: 'housse de couette étoilée : je dors dans le ciel',
      es: 'sábanas nuevas con estrellas: ahora duermo en el cielo',
    },
  },
];

export const SLEEP_HOLD: readonly Draft[] = [
  {
    emoji: '🌬️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yastığın serin tarafı. Çabuk, ısınmadan!',
      en: 'The cool side of the pillow. Quick, before it warms up!',
      de: 'Die kühle Seite vom Kissen. Schnell, bevor sie warm wird!',
      ar: 'الجانب البارد من الوسادة. أسرع قبل أن يسخن!',
      fr: "Le côté frais de l'oreiller. Vite, avant qu'il chauffe !",
      es: 'El lado fresco de la almohada. ¡Rápido, que se calienta!',
    },
  },
  {
    emoji: '📆',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Pazartesi sandın. Cumartesiymiş!',
      en: "Thought it was Monday. It's Saturday!",
      de: 'Dachtest, es ist Montag. Es ist Samstag!',
      ar: 'ظننته يوم عمل… إنه يوم العطلة!',
      fr: "Tu croyais qu'on était lundi. C'est samedi !",
      es: 'Creías que era lunes. ¡Es sábado!',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sabahın ilk yudumu: günün en değerli 3 saniyesi',
      en: 'First sip of the morning: the best 3 seconds of the day',
      de: 'Erster Schluck am Morgen: die besten 3 Sekunden',
      ar: 'أول رشفة في الصباح: أغلى 3 ثوانٍ في اليوم',
      fr: 'Première gorgée du matin : les 3 meilleures secondes',
      es: 'El primer sorbo del día: los 3 mejores segundos',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayıp çorabın teki 3 ay sonra yorgandan çıktı',
      en: 'The lost sock turned up in the duvet after 3 months',
      de: 'Die verschollene Socke: nach 3 Monaten im Bettbezug',
      ar: 'الجورب المفقود ظهر في اللحاف بعد 3 أشهر',
      fr: 'La chaussette perdue, retrouvée dans la couette après 3 mois',
      es: 'El calcetín perdido apareció en el edredón tras 3 meses',
    },
  },
  {
    emoji: '🌡️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Yorgan tam kıvamında ısındı. Bırakmak yok!',
      en: "The duvet is perfectly warm. Don't let go!",
      de: 'Die Decke ist perfekt vorgewärmt. Nicht loslassen!',
      ar: 'اللحاف دافئ تمامًا. لا تتركه!',
      fr: 'La couette est pile à la bonne température. Tiens bon !',
      es: 'La manta está en su punto. ¡No la sueltes!',
    },
  },
  {
    emoji: '💤',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi yetenek: başı yastığa değer değmez uyumak',
      en: 'Legendary skill: out the second your head hits the pillow',
      de: 'Legendäre Fähigkeit: sofort einschlafen',
      ar: 'موهبة أسطورية: النوم لحظة ملامسة رأسك للوسادة',
      fr: 'Talent légendaire : dormir dès la tête posée',
      es: 'Talento legendario: dormirte al tocar la almohada',
    },
  },
  {
    emoji: '🔇',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Horlama durdu! Hemen uyu, fırsat bu fırsat',
      en: "The snoring stopped! Fall asleep now, it's your chance",
      de: 'Das Schnarchen hat aufgehört! Schnell einschlafen!',
      ar: 'توقّف الشخير! نَم الآن، إنها فرصتك',
      fr: "Les ronflements ont cessé ! Dors vite, c'est le moment",
      es: '¡Paró el ronquido! Duérmete ya, es tu oportunidad',
    },
  },
];

export const SLEEP_FREEZE: readonly Draft[] = [
  {
    emoji: '🧟',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'TEHLİKE',
        en: 'DANGER',
        de: 'GEFAHR',
        ar: 'خطر',
        fr: 'DANGER',
        es: 'PELIGRO',
      },
      small: {
        tr: 'HENÜZ KAHVESİNİ İÇMEDİ',
        en: 'HAS NOT HAD COFFEE YET',
        de: 'HATTE NOCH KEINEN KAFFEE',
        ar: 'لم يشرب قهوته بعد',
        fr: "N'A PAS ENCORE BU SON CAFÉ",
        es: 'AÚN NO TOMÓ SU CAFÉ',
      },
    },
    caption: {
      tr: 'Günaydın bile deme.',
      en: "Don't even say good morning.",
      de: 'Nicht mal Guten Morgen sagen.',
      ar: 'ولا تقل صباح الخير حتى.',
      fr: 'Même pas un bonjour.',
      es: 'Ni le digas buenos días.',
    },
    headline: {
      tr: 'Kahvesiz biri mutfakta dolaşıyor',
      en: 'Someone uncaffeinated is in the kitchen',
      de: 'Jemand ohne Kaffee ist in der Küche',
      ar: 'شخص بلا قهوة يتجوّل في المطبخ',
      fr: "Quelqu'un sans café rôde dans la cuisine",
      es: 'Alguien sin café anda por la cocina',
    },
  },
  {
    emoji: '🧖',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'GÜLMEK YASAK',
        en: 'NO LAUGHING',
        de: 'NICHT LACHEN',
        ar: 'ممنوع الضحك',
        fr: 'NE PAS RIRE',
        es: 'PROHIBIDO REÍR',
      },
      small: {
        tr: 'YÜZ MASKESİ KURUYOR',
        en: 'FACE MASK DRYING',
        de: 'GESICHTSMASKE TROCKNET',
        ar: 'قناع الوجه يجف',
        fr: 'MASQUE EN TRAIN DE SÉCHER',
        es: 'MASCARILLA SECÁNDOSE',
      },
    },
    caption: {
      tr: 'Gülersen çatlar. Tek mimik bile yapma.',
      en: 'Laugh and it cracks. Keep a straight face.',
      de: 'Lachen, und sie bröckelt. Pokerface!',
      ar: 'إن ضحكت تشقّق. حافظ على ملامحك.',
      fr: 'Un sourire et ça craque. Reste impassible.',
      es: 'Si te ríes, se agrieta. Cara seria.',
    },
    headline: {
      tr: 'Yüz maskesi tam kurumak üzere',
      en: 'Your face mask is almost dry',
      de: 'Deine Gesichtsmaske ist fast trocken',
      ar: 'قناع وجهك على وشك أن يجف',
      fr: 'Ton masque est presque sec',
      es: 'Tu mascarilla está casi seca',
    },
  },
  {
    emoji: '🦖',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'PAZARTESİ',
        en: 'MONDAY',
        de: 'MONTAG',
        ar: 'بداية الأسبوع',
        fr: 'LUNDI',
        es: 'LUNES',
      },
      small: {
        tr: 'ANİ HAREKET YAPMAYIN',
        en: 'NO SUDDEN MOVEMENTS',
        de: 'KEINE HEKTISCHEN BEWEGUNGEN',
        ar: 'لا حركات مفاجئة',
        fr: 'PAS DE GESTES BRUSQUES',
        es: 'NADA DE MOVIMIENTOS BRUSCOS',
      },
    },
    caption: {
      tr: 'Kıpırdamazsan belki görmez.',
      en: "Don't move. Maybe it won't see you.",
      de: 'Keine Bewegung. Vielleicht sieht er dich nicht.',
      ar: 'لا تتحرك، ربما لا يراك.',
      fr: 'Bouge pas, il te verra peut-être pas.',
      es: 'No te muevas. Quizá no te vea.',
    },
    headline: {
      tr: 'Pazartesi sabahı yaklaşıyor',
      en: 'Monday morning is getting closer',
      de: 'Der Montagmorgen kommt näher',
      ar: 'صباح أول يوم عمل يقترب',
      fr: 'Lundi matin approche',
      es: 'El lunes por la mañana se acerca',
    },
  },
  {
    emoji: '🪟',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YATAK ODASI',
        en: 'BEDROOM',
        de: 'SCHLAFZIMMER',
        ar: 'غرفة النوم',
        fr: 'CHAMBRE',
        es: 'DORMITORIO',
      },
    },
    caption: {
      tr: 'Gözlerini sımsıkı kapa.',
      en: 'Squeeze your eyes shut.',
      de: 'Augen fest zu.',
      ar: 'أغمض عينيك بقوة.',
      fr: 'Ferme les yeux très fort.',
      es: 'Cierra los ojos bien fuerte.',
    },
    headline: {
      tr: 'Annen perdeleri açmak üzere',
      en: "Mom's about to open the curtains",
      de: 'Mama reißt gleich die Vorhänge auf',
      ar: 'أمك على وشك فتح الستائر',
      fr: 'Maman va ouvrir grand les rideaux',
      es: 'Mamá va a abrir las cortinas',
    },
  },
  {
    emoji: '🥞',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SENİN ODAN',
        en: 'YOUR ROOM',
        de: 'DEIN ZIMMER',
        ar: 'غرفتك',
        fr: 'TA CHAMBRE',
        es: 'TU CUARTO',
      },
    },
    caption: {
      tr: 'Çayı ağzına kadar doldurmuş. Kıpırdama.',
      en: "He filled the mug to the brim. Don't move.",
      de: 'Die Tasse ist randvoll. Keine Bewegung.',
      ar: 'ملأ الكوب حتى الحافة. لا تتحرك.',
      fr: 'Tasse remplie à ras bord. Bouge pas.',
      es: 'Llenó la taza hasta el borde. No te muevas.',
    },
    headline: {
      tr: 'Kardeşin yatağa kahvaltı getirdi',
      en: 'Little bro made you breakfast in bed',
      de: 'Dein Bruder bringt Frühstück ans Bett',
      ar: 'أخوك الصغير أحضر لك الفطور إلى السرير',
      fr: 'Petit-déj au lit, servi par ton frère',
      es: 'Tu hermanito te trajo desayuno a la cama',
    },
  },
  {
    emoji: '👔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK',
        en: 'KITCHEN',
        de: 'KÜCHE',
        ar: 'المطبخ',
        fr: 'CUISINE',
        es: 'COCINA',
      },
    },
    caption: {
      tr: 'Elinde reçelli ekmek. Tek damla bile düşmesin.',
      en: "Jam toast in hand. Don't drip. Don't move.",
      de: 'Marmeladenbrot in der Hand. Bloß nicht tropfen.',
      ar: 'في يدك خبز بالمربى. لا تُسقط قطرة واحدة.',
      fr: 'Tartine de confiture en main. Pas une goutte.',
      es: 'Pan con mermelada en la mano. Ni una gota.',
    },
    headline: {
      tr: 'Baban ütülediği gömleğine bakıyor',
      en: "Dad's eyeing the shirt he just ironed",
      de: 'Papa mustert das frisch gebügelte Hemd',
      ar: 'أبوك ينظر إلى القميص الذي كواه للتو',
      fr: 'Papa inspecte ta chemise repassée',
      es: 'Papá revisa tu camisa recién planchada',
    },
  },
  {
    emoji: '🧸',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇOCUK ODASI',
        en: "KIDS' ROOM",
        de: 'KINDERZIMMER',
        ar: 'غرفة الأطفال',
        fr: "CHAMBRE D'ENFANT",
        es: 'CUARTO DE NIÑOS',
      },
    },
    caption: {
      tr: 'Yorgan kalkandır. Dışarı çıkma.',
      en: 'The blanket is your shield. Stay under.',
      de: 'Die Decke ist dein Schild. Bleib drunter.',
      ar: 'البطانية درعك. ابقَ تحتها.',
      fr: 'La couette est ton bouclier. Reste dessous.',
      es: 'La manta es tu escudo. Quédate debajo.',
    },
    headline: {
      tr: 'Yatağın altından bir tıkırtı geldi',
      en: 'Something rustled under the bed',
      de: 'Unterm Bett hat was geraschelt',
      ar: 'صدر صوت من تحت السرير',
      fr: 'Un bruit sous le lit',
      es: 'Algo sonó debajo de la cama',
    },
  },
];
