import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * The city, transport and travel: buses, traffic, taxis, trips, airports, hotels, maps, sightseeing.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const TRAVEL_SKIP: readonly Draft[] = [
  {
    emoji: '💡',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Otel odası: 11 düğme. Bir ışık hâlâ sönmüyor.',
      en: 'The hotel room has 11 switches. One light is still on.',
      de: 'Hotelzimmer: 11 Schalter. Ein Licht brennt immer noch.',
      ar: 'في غرفة الفندق 11 زرًا، وما زال أحد الأضواء مضاءً.',
      fr: "À l'hôtel, 11 interrupteurs. Une lampe reste allumée.",
      es: 'Hotel: 11 interruptores. Una luz sigue encendida.',
    },
  },
  {
    emoji: '📍',
    user: ACCOUNTS.city,
    body: { format: 'scene' },
    caption: {
      tr: '“Hedefinize ulaştınız.” Etraf dümdüz tarla.',
      en: "“You have arrived.” I'm in the middle of a field.",
      de: '„Sie haben Ihr Ziel erreicht.“ Ringsum nur Acker.',
      ar: '«لقد وصلت إلى وجهتك». وحولي حقل فقط.',
      fr: "« Vous êtes arrivé. » Je suis au milieu d'un champ.",
      es: '“Ha llegado a su destino.” Estoy en medio de un campo.',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Cam kenarına para verdim. Manzara: kanat.',
      en: 'Paid extra for the window seat. View: wing.',
      de: 'Fensterplatz extra bezahlt. Aussicht: Flügel.',
      ar: 'دفعت أكثر لأجل مقعد النافذة. المنظر: الجناح.',
      fr: "Place hublot payée en plus. Vue : l'aile.",
      es: 'Pagué extra por la ventanilla. Vista: el ala.',
    },
  },
  {
    emoji: '🚲',
    user: ACCOUNTS.city,
    body: { format: 'scene' },
    caption: {
      tr: 'Bisiklet yolu aniden bitti. Şimdi ben neyim?',
      en: 'The bike lane just ended. So what am I now?',
      de: 'Der Radweg hört einfach auf. Was bin ich jetzt?',
      ar: 'انتهى مسار الدراجات فجأة. فماذا أكون الآن؟',
      fr: "La piste cyclable s'arrête net. Je suis quoi, moi ?",
      es: 'El carril para bicis se acabó. ¿Y ahora qué soy?',
    },
  },
  {
    emoji: '🚍',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Yer verdim, “sen otur” dedi. İkimiz de ayaktayız.',
      en: "Offered my seat. She said “you sit.” We're both standing.",
      de: 'Platz angeboten. „Setz du dich.“ Jetzt stehen wir beide.',
      ar: 'عرضت عليها مقعدي فقالت: «اجلس أنت». والآن نقف كلانا.',
      fr: "J'offre ma place, elle me la rend. Personne ne s'assoit.",
      es: 'Ofrecí mi asiento y me dijo “siéntate tú”. Nadie se sentó.',
    },
  },
  {
    emoji: '🗝️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'İsimli anahtarlıklarda yine adım yok.',
      en: 'Every name on the keychain rack but mine. Again.',
      de: 'Namens-Schlüsselanhänger: jeder Name, nur meiner nicht.',
      ar: 'ميداليات المفاتيح بالأسماء… كلها إلا اسمي، كالعادة.',
      fr: 'Porte-clés prénoms : tous sauf le mien. Encore.',
      es: 'Llaveros con nombres: todos menos el mío. Otra vez.',
    },
  },
  {
    emoji: '🕓',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Jet lag: vücudum evde, uykum hâlâ yolda.',
      en: "Jet lag: my body's home. My sleep is still in transit.",
      de: 'Jetlag: Ich bin zu Hause, mein Schlaf noch unterwegs.',
      ar: 'إرهاق السفر: جسدي في البيت، ونومي ما زال في الطريق.',
      fr: 'Décalage horaire : mon corps est rentré, pas mon sommeil.',
      es: 'Jet lag: mi cuerpo llegó, mi sueño sigue de viaje.',
    },
  },
  {
    emoji: '🛫',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'vardın mı?',
            en: 'did you land?',
            de: 'bist du gelandet?',
            ar: 'هل وصلت؟',
            fr: "t'as atterri ?",
            es: '¿ya aterrizaste?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'anne daha kalkmadık',
            en: "mom, we haven't even taken off",
            de: 'Mama, wir sind noch nicht mal gestartet',
            ar: 'أمي، لم نقلع بعد',
            fr: 'maman, on a même pas décollé',
            es: 'mamá, ni siquiera despegamos',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tamam, inince yaz',
            en: 'ok, text me when you land',
            de: 'ok, schreib, wenn du gelandet bist',
            ar: 'حسنًا، اكتب لي حين تهبط',
            fr: "ok, écris-moi quand t'atterris",
            es: 'ok, avísame cuando aterrices',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'indin mi?',
            en: 'landed?',
            de: 'gelandet?',
            ar: 'هل هبطت؟',
            fr: 'atterri ?',
            es: '¿aterrizaste?',
          },
        },
      ],
    },
    caption: {
      tr: 'Uçak hâlâ pistte',
      en: 'The plane is still on the runway',
      de: 'Das Flugzeug steht noch auf der Startbahn',
      ar: 'الطائرة ما زالت على المدرج',
      fr: "L'avion est encore sur la piste",
      es: 'El avión sigue en la pista',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Tatil grubu',
        en: 'Vacation crew',
        de: 'Urlaubsgruppe',
        ar: 'مجموعة الإجازة',
        fr: 'Groupe vacances',
        es: 'Grupo del viaje',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'yarınki plan: 7’de kahvaltı, 8’de müze',
            en: 'tomorrow: breakfast at 7, museum at 8',
            de: 'morgen: 7 Uhr Frühstück, 8 Uhr Museum',
            ar: 'خطة الغد: الفطور في 7، والمتحف في 8',
            fr: 'demain : petit-déj à 7 h, musée à 8 h',
            es: 'mañana: desayuno a las 7, museo a las 8',
          },
        },
        {
          from: 'me',
          text: {
            tr: '9’da kale, 11’de şehir turu…',
            en: 'castle at 9, city tour at 11…',
            de: '9 Uhr Burg, 11 Uhr Stadtführung…',
            ar: 'القلعة في 9، وجولة في المدينة في 11…',
            fr: 'château à 9 h, visite de la ville à 11 h…',
            es: 'castillo a las 9, paseo a las 11…',
          },
        },
        {
          from: 'them',
          text: {
            tr: '7’de mi?',
            en: 'at 7??',
            de: 'um 7??',
            ar: 'في السابعة؟',
            fr: 'à 7 h ??',
            es: '¿¿a las 7??',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tatildeyiz sanıyordum',
            en: 'I thought we were on vacation',
            de: 'ich dachte, wir haben Urlaub',
            ar: 'ظننت أننا في إجازة',
            fr: "je croyais qu'on était en vacances",
            es: 'creí que estábamos de vacaciones',
          },
        },
      ],
    },
    caption: {
      tr: 'Daha planın ilk sayfası bu',
      en: "And that's just page one of the plan",
      de: 'Und das war erst Seite eins des Plans',
      ar: 'وهذه الصفحة الأولى من الخطة فقط',
      fr: "Et ce n'est que la page 1 du programme",
      es: 'Y esa es solo la página uno del plan',
    },
  },
  {
    emoji: '🚇',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'neredesin?',
            en: 'where are you?',
            de: 'wo bist du?',
            ar: 'أين أنت؟',
            fr: "t'es où ?",
            es: '¿dónde estás?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'metrodayım, 2 durak kaldı',
            en: 'on the subway, 2 stops away',
            de: 'in der U-Bahn, noch 2 Stationen',
            ar: 'في المترو، بقيت محطتان',
            fr: 'dans le métro, encore 2 stations',
            es: 'en el metro, faltan 2 estaciones',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'canlı konumun uzaklaşıyor ama',
            en: "your live location's moving away tho",
            de: 'dein Live-Standort entfernt sich aber',
            ar: 'لكن موقعك المباشر يبتعد',
            fr: "ta position en direct s'éloigne, là",
            es: 'pero tu ubicación en vivo se aleja',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tamam, 3 durak kaldı',
            en: 'ok, 3 stops away',
            de: 'ok, noch 3 Stationen',
            ar: 'حسنًا، بقيت 3 محطات',
            fr: 'ok, encore 3 stations',
            es: 'ok, faltan 3 estaciones',
          },
        },
      ],
    },
    caption: {
      tr: 'Ters yöne binmişim',
      en: 'Wrong direction, obviously',
      de: 'Falsche Richtung, natürlich',
      ar: 'ركبت في الاتجاه المعاكس طبعًا',
      fr: 'Mauvaise direction, évidemment',
      es: 'Dirección contraria, obvio',
    },
  },
  {
    emoji: '🚕',
    user: ACCOUNTS.city,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sürücü',
        en: 'Driver',
        de: 'Fahrer',
        ar: 'السائق',
        fr: 'Chauffeur',
        es: 'Conductor',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'geldim, beyaz arabayım',
            en: "I'm here, white car",
            de: 'bin da, weißes Auto',
            ar: 'وصلت، سيارة بيضاء',
            fr: 'je suis là, voiture blanche',
            es: 'ya llegué, auto blanco',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'burada 6 beyaz araba var',
            en: 'there are 6 white cars here',
            de: 'hier stehen 6 weiße Autos',
            ar: 'هنا 6 سيارات بيضاء',
            fr: 'y a 6 voitures blanches ici',
            es: 'aquí hay 6 autos blancos',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'size el sallıyorum',
            en: "I'm waving at you",
            de: 'ich winke Ihnen',
            ar: 'أنا ألوّح لك',
            fr: 'je vous fais signe',
            es: 'le estoy haciendo señas',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hepsi el sallıyor',
            en: "they're all waving",
            de: 'alle winken',
            ar: 'كلهم يلوّحون',
            fr: 'ils font tous signe',
            es: 'todos están haciendo señas',
          },
        },
      ],
    },
    caption: {
      tr: 'Sonunda plakayı sordum',
      en: 'Finally asked for the plate number',
      de: 'Hab dann doch nach dem Kennzeichen gefragt',
      ar: 'في النهاية سألته عن رقم اللوحة',
      fr: "J'ai fini par demander la plaque",
      es: 'Al final le pedí el número de placa',
    },
  },
  {
    emoji: '🛬',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Uçak indi, kemer ışığı hâlâ yanıyor. Sen:',
        en: "Plane's landed, seatbelt sign still on. You:",
        de: 'Gelandet, Anschnallzeichen noch an. Du:',
        ar: 'هبطت الطائرة وإشارة الحزام ما زالت مضاءة. أنت:',
        fr: 'Atterrissage, voyant ceinture allumé. Toi :',
        es: 'Aterrizaste, pero la luz del cinturón sigue. Tú:',
      },
      options: [
        {
          tr: 'Oturup beklerim',
          en: 'Stay seated',
          de: 'Sitzen bleiben',
          ar: 'أبقى جالسًا',
          fr: 'Je reste assis',
          es: 'Me quedo sentado',
        },
        {
          tr: 'Hemen ayağa kalkarım',
          en: 'Stand up right away',
          de: 'Sofort aufstehen',
          ar: 'أقف فورًا',
          fr: 'Je me lève direct',
          es: 'Me levanto ya',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kapı 20 dakika sonra açıldı',
      en: 'The door opened 20 minutes later',
      de: 'Die Tür ging 20 Minuten später auf',
      ar: 'فُتح الباب بعد 20 دقيقة',
      fr: "La porte s'est ouverte 20 minutes après",
      es: 'La puerta se abrió 20 minutos después',
    },
  },
  {
    emoji: '🚙',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Otoparkta arabanı bulamıyorsun. Sen:',
        en: "Your car's lost in the parking garage. You:",
        de: 'Dein Auto ist im Parkhaus verschollen. Du:',
        ar: 'سيارتك ضائعة في المرآب. ماذا تفعل؟',
        fr: 'Ta voiture est perdue dans le parking. Toi :',
        es: 'No encuentras tu auto en el estacionamiento. Tú:',
      },
      options: [
        {
          tr: 'Kat kat gezerim',
          en: 'Walk every floor',
          de: 'Jede Etage ablaufen',
          ar: 'أبحث في كل طابق',
          fr: 'Tous les étages à pied',
          es: 'Recorro cada piso',
        },
        {
          tr: 'Bip bip, dinlerim',
          en: 'Beep the key, listen',
          de: 'Piepen und lauschen',
          ar: 'أضغط المفتاح وأنصت',
          fr: "Bip-bip, et j'écoute",
          es: 'Bip bip y escucho',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Dördüncü kattan cılız bir bip geldi',
      en: 'A faint beep from level 4',
      de: 'Ein leises Piepen aus Ebene 4',
      ar: 'صفّارة خافتة من الطابق الرابع',
      fr: 'Un petit bip venu du niveau 4',
      es: 'Un bip lejano desde el piso 4',
    },
  },
  {
    emoji: '🧱',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Otelde “deniz manzaralı” oda aldın. Pencereden:',
        en: 'You booked a “sea view” room. Out the window:',
        de: 'Zimmer mit „Meerblick“ gebucht. Am Fenster:',
        ar: 'حجزت غرفة «مطلة على البحر». من النافذة ترى:',
        fr: 'Chambre « vue sur mer » réservée. Par la fenêtre :',
        es: 'Reservaste “vista al mar”. Por la ventana ves:',
      },
      options: [
        {
          tr: 'Deniz',
          en: 'The sea',
          de: 'Das Meer',
          ar: 'البحر',
          fr: 'La mer',
          es: 'El mar',
        },
        {
          tr: 'Otopark',
          en: 'A parking lot',
          de: 'Ein Parkplatz',
          ar: 'موقف سيارات',
          fr: 'Un parking',
          es: 'Un estacionamiento',
        },
        {
          tr: 'Karşı otelin duvarı',
          en: "Another hotel's wall",
          de: 'Eine Hotelwand',
          ar: 'جدار فندق آخر',
          fr: "Le mur d'en face",
          es: 'La pared de otro hotel',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Duvarın arkası denizmiş, öyle dediler',
      en: 'Apparently the sea is behind that wall',
      de: 'Hinter der Wand ist das Meer, sagen sie',
      ar: 'قالوا إن البحر خلف ذلك الجدار',
      fr: 'Paraît que la mer est derrière le mur',
      es: 'Dicen que el mar está detrás de la pared',
    },
  },
  {
    emoji: '🚖',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'SÜRÜCÜ 2 DK UZAKTA',
        en: 'DRIVER: 2 MIN AWAY',
        de: 'FAHRER: 2 MIN ENTFERNT',
        ar: 'السائق على بُعد دقيقتين',
        fr: 'CHAUFFEUR À 2 MIN',
        es: 'CONDUCTOR A 2 MIN',
      },
      value: null,
      shape: 'flat',
      axis: 'hours',
    },
    caption: {
      tr: '1 saattir 2 dakika uzakta',
      en: 'Two minutes away for an hour now',
      de: 'Seit einer Stunde 2 Minuten entfernt',
      ar: 'على بُعد دقيقتين منذ ساعة',
      fr: 'À 2 minutes depuis une heure',
      es: 'A 2 minutos desde hace una hora',
    },
  },
  {
    emoji: '⚖️',
    user: ACCOUNTS.trends,
    body: {
      format: 'chart',
      title: {
        tr: 'BAVULUMUN AĞIRLIĞI',
        en: 'SUITCASE WEIGHT',
        de: 'GEWICHT MEINES KOFFERS',
        ar: 'وزن حقيبتي',
        fr: 'POIDS DE MA VALISE',
        es: 'PESO DE MI MALETA',
      },
      value: { tr: '×2', en: '×2', de: '×2', ar: '×2', fr: '×2', es: '×2' },
      shape: 'rise',
      axis: 'days',
    },
    caption: {
      tr: 'Giderken yarısı boştu',
      en: 'It was half empty on the way out',
      de: 'Auf dem Hinweg war er halb leer',
      ar: 'كانت نصف فارغة في طريق الذهاب',
      fr: "À l'aller, elle était à moitié vide",
      es: 'A la ida iba medio vacía',
    },
  },
  {
    emoji: '🧲',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'HEDİYELİK EŞYA',
        en: 'GIFT SHOP',
        de: 'SOUVENIRLADEN',
        ar: 'متجر التذكارات',
        fr: 'BOUTIQUE SOUVENIRS',
        es: 'TIENDA DE RECUERDOS',
      },
      items: [
        {
          tr: 'BUZDOLABI MAGNETİ (12)',
          en: 'FRIDGE MAGNETS (12)',
          de: 'MAGNETE (12 STÜCK)',
          ar: 'مغناطيس ثلاجة (12)',
          fr: 'MAGNETS DE FRIGO (12)',
          es: 'IMANES (12 UNIDADES)',
        },
      ],
    },
    caption: {
      tr: 'Herkese aynısından aldım. Aynı sofrada açtılar.',
      en: 'Same gift for everyone. They opened them together.',
      de: 'Alle kriegen dasselbe. Ausgepackt am selben Tisch.',
      ar: 'الهدية نفسها للجميع… وفتحوها على المائدة نفسها.',
      fr: 'Le même pour tous. Déballés à la même table.',
      es: 'El mismo para todos. Los abrieron en la misma mesa.',
    },
  },
  {
    emoji: '🥜',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'OTEL MİNİBARI',
        en: 'HOTEL MINIBAR',
        de: 'HOTEL-MINIBAR',
        ar: 'ميني بار الفندق',
        fr: "MINIBAR DE L'HÔTEL",
        es: 'MINIBAR DEL HOTEL',
      },
      items: [
        {
          tr: 'FISTIK (MİNİ PAKET)',
          en: 'PEANUTS (TINY BAG)',
          de: 'ERDNÜSSE (MINITÜTE)',
          ar: 'فول سوداني (كيس صغير)',
          fr: 'CACAHUÈTES (MINI)',
          es: 'FRUTOS SECOS (MINI)',
        },
      ],
    },
    caption: {
      tr: 'İkram sanmıştım',
      en: 'I thought it was complimentary',
      de: 'Ich dachte, die sind gratis',
      ar: 'ظننته ضيافة مجانية',
      fr: "Je croyais que c'était offert",
      es: 'Creí que era cortesía',
    },
  },
  {
    emoji: '🧴',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'KOZMETİK MAĞAZASI',
        en: 'DRUGSTORE',
        de: 'DROGERIE',
        ar: 'الصيدلية',
        fr: 'PARAPHARMACIE',
        es: 'FARMACIA',
      },
      items: [
        {
          tr: 'ŞAMPUAN (SEYAHAT BOY)',
          en: 'SHAMPOO (TRAVEL SIZE)',
          de: 'SHAMPOO (REISEGRÖSSE)',
          ar: 'شامبو (حجم السفر)',
          fr: 'SHAMPOING MINI FORMAT',
          es: 'CHAMPÚ (TAMAÑO VIAJE)',
        },
        {
          tr: 'DİŞ MACUNU (MİNİ)',
          en: 'TOOTHPASTE (MINI)',
          de: 'ZAHNPASTA (MINI)',
          ar: 'معجون أسنان (صغير)',
          fr: 'DENTIFRICE (MINI)',
          es: 'PASTA DENTAL (MINI)',
        },
      ],
    },
    caption: {
      tr: 'Her şey mini. Tatil de mini: 2 gün.',
      en: "Everything's mini. So's the trip: 2 days.",
      de: 'Alles in Mini. Der Urlaub auch: 2 Tage.',
      ar: 'كل شيء صغير… حتى الإجازة: يومان.',
      fr: 'Tout est mini. Les vacances aussi : 2 jours.',
      es: 'Todo es mini. Las vacaciones también: 2 días.',
    },
  },
  {
    emoji: '🚉',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3' },
      text: {
        tr: 'durak fazla gittin; bu postu bitireceğim diye',
        en: 'stops past yours. Just to finish this post.',
        de: 'Stationen zu weit gefahren. Nur für diesen Post.',
        ar: 'محطات بعد محطتك… فقط لتُكمل هذا المنشور',
        fr: 'stations de trop. Juste pour finir ce post.',
        es: 'estaciones de más. Solo por terminar este post.',
      },
    },
    caption: {
      tr: 'Dönüş karşı peronda',
      en: 'The way back is on the other platform',
      de: 'Zurück geht es vom Gleis gegenüber',
      ar: 'طريق العودة من الرصيف المقابل',
      fr: "Le retour, c'est le quai d'en face",
      es: 'La vuelta es en el andén de enfrente',
    },
  },
  {
    emoji: '💌',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '10', en: '10', de: '10', ar: '10', fr: '10', es: '10' },
      text: {
        tr: 'kartpostal aldın tatilde; hepsi hâlâ çekmecede, pullarıyla',
        en: 'postcards bought on the trip. Still in a drawer, stamps and all.',
        de: 'Postkarten gekauft. Alle noch in der Schublade – mit Marken.',
        ar: 'بطاقات بريدية اشتريتها في الإجازة… كلها في الدرج مع طوابعها',
        fr: 'cartes postales achetées. Au fond du tiroir, avec les timbres.',
        es: 'postales compradas. Siguen en un cajón, con sus sellos.',
      },
    },
    caption: {
      tr: 'Seneye yollarım, daha nostaljik olur',
      en: "I'll mail them next year. Extra nostalgic.",
      de: 'Nächstes Jahr schick ich sie. Noch nostalgischer.',
      ar: 'سأرسلها العام القادم، ستكون أكثر حنينًا',
      fr: "Je les enverrai l'an prochain, ce sera plus nostalgique.",
      es: 'Las mando el año que viene, más nostálgico aún.',
    },
  },
  {
    emoji: '🏺',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'MÜZE İSTATİSTİĞİ',
        en: 'MUSEUM STATS',
        de: 'MUSEUMSSTATISTIK',
        ar: 'إحصائية المتحف',
        fr: 'STATS DU MUSÉE',
        es: 'DATO DEL MUSEO',
      },
      big: { tr: '41', en: '41', de: '41', ar: '41', fr: '41', es: '41' },
      text: {
        tr: 'numaralı eserin önündesin; sesli rehber 14’ü anlatıyor',
        en: 'is the piece in front of you. The audio guide is on 14.',
        de: 'ist das Werk vor dir. Der Audioguide erklärt Nummer 14.',
        ar: 'هو رقم القطعة أمامك… والدليل الصوتي يشرح رقم 14',
        fr: "est l'œuvre devant toi. L'audioguide parle de la 14.",
        es: 'es la obra frente a ti. La audioguía habla de la 14.',
      },
    },
    caption: {
      tr: 'Rehber “tablo” diyor, önümde vazo var',
      en: "The guide says “painting.” I'm looking at a vase.",
      de: 'Der Guide sagt „Gemälde“. Vor mir steht eine Vase.',
      ar: 'الدليل يقول «لوحة»، وأمامي مزهرية',
      fr: 'Le guide dit « tableau ». Devant moi : un vase.',
      es: 'La guía dice “cuadro”. Frente a mí hay un jarrón.',
    },
  },
  {
    emoji: '💺',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'UÇAK KOLTUĞU TIER LIST',
        en: 'PLANE SEAT TIER LIST',
        de: 'FLUGZEUGSITZ-RANKING',
        ar: 'تصنيف مقاعد الطائرة',
        fr: "TIER LIST DES SIÈGES D'AVION",
        es: 'TIER LIST: ASIENTOS DE AVIÓN',
      },
      rows: [['🪟', '🌅'], ['🚶', '🦵'], ['🚻'], ['🥪']],
    },
    caption: {
      tr: 'Orta koltuk C: iki kolçak da komşuların',
      en: 'Middle seat is C. Both armrests belong to the neighbors.',
      de: 'Mittelplatz ist C. Beide Armlehnen sind vergeben.',
      ar: 'المقعد الأوسط في ذيل القائمة: بلا مسند ذراع',
      fr: 'Siège du milieu en C : zéro accoudoir.',
      es: 'Asiento del medio en C: cero reposabrazos.',
    },
  },
  {
    emoji: '🚋',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ŞEHİR İÇİ ULAŞIM TIER LIST',
        en: 'CITY TRANSIT TIER LIST',
        de: 'STADTVERKEHR-RANKING',
        ar: 'تصنيف المواصلات في المدينة',
        fr: 'TIER LIST DES TRANSPORTS',
        es: 'TIER LIST DEL TRANSPORTE',
      },
      rows: [['🚋', '🚶'], ['🚇', '🚲'], ['🚌', '🛴'], ['🚗']],
    },
    caption: {
      tr: 'Tramvay S. Tek sebebi: zili.',
      en: "Tram's in S. One reason: the bell.",
      de: 'Tram auf S. Einziger Grund: die Klingel.',
      ar: 'الترام في القمة، والسبب الوحيد: جرسه.',
      fr: 'Tram en S. Une seule raison : la cloche.',
      es: 'El tranvía es S. Única razón: la campanita.',
    },
  },
  {
    emoji: '🏃',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '✈️',
        app: {
          tr: 'Havalimanı',
          en: 'Airport',
          de: 'Flughafen',
          ar: 'المطار',
          fr: 'Aéroport',
          es: 'Aeropuerto',
        },
        text: {
          tr: 'Biniş kapın 3’ten 86’ya taşındı',
          en: 'Your gate moved from 3 to 86',
          de: 'Dein Gate wurde von 3 auf 86 verlegt',
          ar: 'نُقلت بوابتك من 3 إلى 86',
          fr: 'Ta porte passe de la 3 à la 86',
          es: 'Tu puerta cambió de la 3 a la 86',
        },
      },
    },
    caption: {
      tr: '86 numara neredeyse başka şehirde',
      en: 'Gate 86 is basically in the next town',
      de: 'Gate 86 liegt quasi in der Nachbarstadt',
      ar: 'البوابة 86 تكاد تكون في مدينة أخرى',
      fr: "La porte 86 est quasi dans la ville d'à côté",
      es: 'La puerta 86 está casi en otra ciudad',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌐',
        app: {
          tr: 'Çevirmen',
          en: 'Translator',
          de: 'Übersetzer',
          ar: 'المترجم',
          fr: 'Traducteur',
          es: 'Traductor',
        },
        text: {
          tr: '14. çeviri: “Tuvalet nerede?”',
          en: "Translation #14: “Where's the restroom?”",
          de: '14. Übersetzung: „Wo ist die Toilette?“',
          ar: 'الترجمة رقم 14: «أين الحمّام؟»',
          fr: '14e traduction : « Les toilettes ? »',
          es: 'Traducción 14: “¿Dónde está el baño?”',
        },
      },
    },
    caption: {
      tr: '14 günlük tatil, hâlâ ezberleyemedim',
      en: "14-day trip. Still haven't memorized it.",
      de: '14 Tage Urlaub, immer noch nicht gemerkt',
      ar: 'إجازة 14 يومًا… وما زلت لم أحفظها',
      fr: '14 jours de vacances, toujours pas retenu',
      es: '14 días de viaje y todavía no me la sé',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayatta ilerlemek istiyorsan önce otobüsün arkasına ilerle.',
        en: 'If you want to move forward in life, first move to the back of the bus.',
        de: 'Wer im Leben vorankommen will, muss im Bus erst mal durchgehen.',
        ar: 'إن أردت أن تتقدّم في الحياة، فتقدّم أولًا إلى آخر الحافلة.',
        fr: 'Pour avancer dans la vie, commence par avancer au fond du bus.',
        es: 'Si quieres avanzar en la vida, avanza primero al fondo del bus.',
      },
    },
    caption: {
      tr: 'Şoför bu sabah 6 kez söyledi',
      en: 'The driver said it 6 times this morning',
      de: 'Der Fahrer hat es heute früh 6-mal gesagt',
      ar: 'قالها السائق 6 مرات هذا الصباح',
      fr: "Le chauffeur l'a dit 6 fois ce matin",
      es: 'El conductor lo dijo 6 veces esta mañana',
    },
  },
  {
    emoji: '🛎️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kaybolmak da bir keşiftir. — Otel koridorunda 20 dakika dolaşan biri',
        en: 'Getting lost is discovery too. — Me, 20 minutes in the hotel hallway',
        de: 'Sich verlaufen ist auch Entdecken. — Ich, 20 Minuten im Hotelflur',
        ar: 'الضياع اكتشاف أيضًا. — شخص تاه 20 دقيقة في ممر الفندق',
        fr: "Se perdre, c'est découvrir. — Moi, 20 minutes dans le couloir de l'hôtel",
        es: 'Perderse también es descubrir. — Yo, 20 minutos en el pasillo del hotel',
      },
    },
    caption: {
      tr: 'Odam 312. Ben 213’ün önündeydim.',
      en: 'My room is 312. I was outside 213.',
      de: 'Mein Zimmer: 312. Ich stand vor der 213.',
      ar: 'غرفتي 312، وكنت أقف أمام 213.',
      fr: "Ma chambre, c'est la 312. J'étais devant la 213.",
      es: 'Mi habitación es la 312. Estaba frente a la 213.',
    },
  },
  {
    emoji: '🗺️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Dünya bir kitaptır. Ben sadece yorumlarını okuyorum.',
        en: 'The world is a book. I just read the reviews.',
        de: 'Die Welt ist ein Buch. Ich lese nur die Bewertungen.',
        ar: 'العالم كتاب، وأنا أكتفي بقراءة التقييمات.',
        fr: 'Le monde est un livre. Moi, je lis juste les avis.',
        es: 'El mundo es un libro. Yo solo leo las reseñas.',
      },
    },
    caption: {
      tr: '1.482 yorum okudum. Evden çıkmadım.',
      en: 'Read 1,482 reviews. Never left the house.',
      de: '1.482 Bewertungen gelesen. Nie rausgegangen.',
      ar: 'قرأت 1,482 تقييمًا، ولم أغادر البيت.',
      fr: 'Lu 1 482 avis. Pas mis un pied dehors.',
      es: 'Leí 1482 reseñas. No salí de casa.',
    },
  },
  {
    emoji: '🔒',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her macera bir adımla başlar. Benimki kapıyı kontrole dönmekle.',
        en: 'Every trip starts with one step. Mine: back to check the door.',
        de: 'Jede Reise beginnt mit einem Schritt. Meiner: zurück zur Tür.',
        ar: 'كل مغامرة تبدأ بخطوة. وخطوتي: العودة لأتفقّد الباب.',
        fr: 'Tout voyage commence par un pas. Le mien : retour à la porte.',
        es: 'Toda aventura empieza con un paso. El mío: volver a revisar la puerta.',
      },
    },
    caption: {
      tr: '3 kez döndüm. Kilitliydi.',
      en: 'Went back 3 times. It was locked.',
      de: '3-mal zurück. Sie war abgeschlossen.',
      ar: 'عدت 3 مرات. كان مقفلًا.',
      fr: '3 allers-retours. Elle était fermée.',
      es: 'Volví 3 veces. Estaba cerrada.',
    },
  },
  {
    emoji: '🤳',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bazı manzaralar fotoğrafa sığmaz. Önünde 40 turist varsa hiç sığmaz.',
        en: "Some views don't fit in a photo. Especially behind 40 tourists.",
        de: 'Manches passt in kein Foto. Vor allem mit 40 Touristen davor.',
        ar: 'بعض المناظر لا تتّسع لها صورة، خاصةً إذا وقف أمامها 40 سائحًا.',
        fr: 'Certaines vues ne tiennent pas en photo. Surtout derrière 40 touristes.',
        es: 'Hay vistas que no caben en una foto. Menos detrás de 40 turistas.',
      },
    },
    caption: {
      tr: 'Ben de o 40 kişiden biriydim, pardon',
      en: 'I was one of the 40. Sorry.',
      de: 'Ich war einer der 40. Sorry.',
      ar: 'وكنت واحدًا من الأربعين، آسف.',
      fr: "J'étais l'un des 40. Pardon.",
      es: 'Yo era uno de los 40. Perdón.',
    },
  },
];

export const TRAVEL_LIKE: readonly Draft[] = [
  {
    emoji: '🚗',
    user: ACCOUNTS.baris,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk seferde paralel park ettim!! tanık yok ama',
      en: 'parallel parked on the first try!! no witnesses tho',
      de: 'beim ersten versuch eingeparkt!! leider ohne zeugen',
      ar: 'ركنت السيارة من أول محاولة!! لكن بلا شهود',
      fr: 'créneau réussi du premier coup !! zéro témoin',
      es: '¡¡me estacioné a la primera!! pero sin testigos',
    },
  },
  {
    emoji: '🚆',
    user: ACCOUNTS.bora,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk kez gece treniyle gittim, ranza >>> otel',
      en: 'first night train ever, bunk bed >>> hotel',
      de: 'erster nachtzug, schlafkoje >>> hotel',
      ar: 'أول رحلة لي في قطار ليلي… والسرير أحلى من الفندق',
      fr: 'mon premier train de nuit, couchette >>> hôtel',
      es: 'mi primer tren nocturno, litera >>> hotel',
    },
  },
  {
    emoji: '🏙️',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'biri bana yol sordu ve biliyordum!! artık buralıyım',
      en: 'someone asked me for directions and i knew!! local now',
      de: 'hab heute jemandem den weg erklärt!! bin jetzt einheimisch',
      ar: 'سألني أحدهم عن الطريق وكنت أعرفه!! صرت من أهل المدينة',
      fr: "on m'a demandé le chemin, je savais !! je suis du coin",
      es: '¡¡me preguntaron una calle y la sabía!! ya soy de aquí',
    },
  },
  {
    emoji: '🎒',
    user: ACCOUNTS.ece,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk solo gezim: kendimle çok iyi anlaştık',
      en: "first solo trip: turns out i'm great company",
      de: 'erste solo-reise: ich bin echt gute gesellschaft',
      ar: 'أول رحلة لي وحدي: اتضح أنني رفيقة رائعة',
      fr: 'premier voyage en solo : je suis de super compagnie',
      es: 'mi primer viaje sola: resulta que soy buena compañía',
    },
  },
  {
    emoji: '📮',
    user: ACCOUNTS.yagmur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'anneanneme',
        en: 'to grandma',
        de: 'an oma',
        ar: 'إلى جدتي',
        fr: 'pour mamie',
        es: 'para la abuela',
      },
    },
    caption: {
      tr: 'kartpostal benden sonra vardı, beraber okuduk',
      en: 'the postcard got there after me, so we read it together',
      de: 'die karte kam nach mir an, wir haben sie zusammen gelesen',
      ar: 'وصلت البطاقة بعدي، فقرأناها معًا',
      fr: "la carte est arrivée après moi, on l'a lue ensemble",
      es: 'la postal llegó después que yo, la leímos juntas',
    },
  },
  {
    emoji: '🎡',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'en tepede',
        en: 'top of the wheel',
        de: 'ganz oben',
        ar: 'في القمة',
        fr: 'tout en haut',
        es: 'en lo más alto',
      },
    },
    caption: {
      tr: 'dönme dolaba bindim!! gözlerim kapalıydı ama sayılır',
      en: 'rode the ferris wheel!! eyes shut, still counts',
      de: 'riesenrad gefahren!! augen zu, zählt trotzdem',
      ar: 'ركبت العجلة الدوّارة!! بعينين مغمضتين، لكنها تُحسب',
      fr: "j'ai fait la grande roue !! les yeux fermés, mais ça compte",
      es: '¡¡me subí a la rueda gigante!! ojos cerrados, pero cuenta',
    },
  },
  {
    emoji: '🦖',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'kankam rex',
        en: 'my buddy rex',
        de: 'mein kumpel rex',
        ar: 'صديقي ريكس',
        fr: 'mon pote rex',
        es: 'mi amigo rex',
      },
    },
    caption: {
      tr: 'dinozorla fotoğraf sırası: 30 çocuk ve ben',
      en: 'line for the dinosaur photo: 30 kids and me',
      de: 'schlange fürs dino-foto: 30 kinder und ich',
      ar: 'طابور التصوير مع الديناصور: 30 طفلًا وأنا',
      fr: 'file pour la photo avec le dino : 30 enfants et moi',
      es: 'fila para la foto con el dinosaurio: 30 niños y yo',
    },
  },
  {
    emoji: '🚋',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'en ön koltuk',
        en: 'front seat',
        de: 'erste reihe',
        ar: 'المقعد الأمامي',
        fr: 'premier rang',
        es: 'primera fila',
      },
    },
    caption: {
      tr: 'tramvayda en öne oturdum, vatman el salladı',
      en: 'sat up front on the tram and the driver waved at me',
      de: 'ganz vorne in der tram, der fahrer hat mir gewinkt',
      ar: 'جلست في مقدمة الترام، ولوّح لي السائق',
      fr: "tout devant dans le tram, le conducteur m'a fait coucou",
      es: 'me senté al frente en el tranvía y el conductor me saludó',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.bora,
    body: { format: 'dump', emojis: ['🏰', '🎒', '🚆', '🗺️', '🥨'] },
    caption: {
      tr: 'sırt çantası dump’ı: 5 şehir, 1 çanta, 0 ütü',
      en: 'backpacking dump: 5 cities, 1 bag, 0 ironing',
      de: 'rucksack-dump: 5 städte, 1 rucksack, 0 bügeln',
      ar: 'رحلة بحقيبة ظهر: 5 مدن، حقيبة واحدة، ولا كيّ أبدًا',
      fr: 'dump sac à dos : 5 villes, 1 sac, 0 repassage',
      es: 'dump mochilero: 5 ciudades, 1 mochila, 0 planchado',
    },
  },
  {
    emoji: '🏡',
    user: ACCOUNTS.deniz,
    body: { format: 'dump', emojis: ['🏡', '🧳', '🧺', '🛏️', '🪴'] },
    caption: {
      tr: 'eve dönüş dump’ı: bavul, çamaşır ve o ev kokusu',
      en: 'back home dump: suitcase, laundry and that smell of home',
      de: 'heimkehr-dump: koffer, wäsche und dieser duft von zuhause',
      ar: 'العودة إلى البيت: حقيبة، وغسيل، ورائحة البيت تلك',
      fr: 'dump du retour : valise, lessive et cette odeur de maison',
      es: 'dump del regreso: maleta, ropa sucia y ese olor a casa',
    },
  },
  {
    emoji: '🌉',
    user: ACCOUNTS.tolga,
    body: { format: 'dump', emojis: ['🌉', '👟', '📸', '🌆', '🌊'] },
    caption: {
      tr: 'köprü turu: şehrin 7 köprüsünü bir günde yürüdük!!',
      en: 'bridge tour: walked all 7 bridges in one day!!',
      de: 'brücken-tour: alle 7 brücken an einem tag!!',
      ar: 'جولة الجسور: عبرنا جسور المدينة السبعة في يوم واحد!!',
      fr: 'tour des ponts : les 7 ponts de la ville en un jour !!',
      es: '¡¡ruta de puentes: los 7 puentes de la ciudad en un día!!',
    },
  },
  {
    emoji: '🌇',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🌇', '⛲', '🚋', '🍦', '🎟️'] },
    caption: {
      tr: 'kendi şehrimde turist oldum, meğer ne güzelmiş',
      en: "played tourist in my own city, turns out it's gorgeous",
      de: 'tourist in der eigenen stadt, sie ist ja wunderschön',
      ar: 'صرت سائحة في مدينتي… واتضح أنها جميلة جدًا',
      fr: 'touriste dans ma propre ville, elle est trop belle en fait',
      es: 'fui turista en mi propia ciudad y resulta que es preciosa',
    },
  },
];

export const TRAVEL_HOLD: readonly Draft[] = [
  {
    emoji: '🅿️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tam kapının önünde boş park yeri. Rüya mı bu?',
      en: 'An open spot right outside the door. Am I dreaming?',
      de: 'Freier Parkplatz direkt vor der Tür. Träum ich?',
      ar: 'موقف فارغ أمام الباب مباشرة. هل أحلم؟',
      fr: 'Une place libre pile devant la porte. Je rêve ?',
      es: 'Un lugar libre justo frente a la puerta. ¿Estoy soñando?',
    },
  },
  {
    emoji: '🚦',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Eve kadar bütün ışıklar yeşil. Sakın bırakma!',
      en: "Green lights all the way home. Don't let go!",
      de: 'Grüne Welle bis nach Hause. Nicht loslassen!',
      ar: 'كل الإشارات خضراء حتى البيت. لا تُفلت!',
      fr: "Que des feux verts jusqu'à la maison. Lâche pas !",
      es: 'Semáforos en verde hasta casa. ¡No sueltes!',
    },
  },
  {
    emoji: '🧳',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bantta ilk çıkan bavul senin. Bu hiç olmaz!',
      en: 'First bag on the carousel is yours. That never happens!',
      de: 'Der erste Koffer auf dem Band ist deiner. Passiert nie!',
      ar: 'أول حقيبة على السير هي حقيبتك. هذا لا يحدث أبدًا!',
      fr: 'Première valise sur le tapis : la tienne. Du jamais vu !',
      es: 'La primera maleta en la cinta es la tuya. ¡Nunca pasa!',
    },
  },
  {
    emoji: '🚕',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sağanak yağmurda boş taksi sana doğru geliyor',
      en: 'Pouring rain, and an empty cab is heading your way',
      de: 'Platzregen, und ein freies Taxi kommt auf dich zu',
      ar: 'مطر غزير، وسيارة أجرة فارغة تتجه نحوك',
      fr: 'Il pleut des cordes et un taxi libre arrive vers toi',
      es: 'Llueve a cántaros y un taxi libre viene hacia ti',
    },
  },
  {
    emoji: '🏝️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tatilin ilk sabahı. Önünde tam 14 gün var.',
      en: 'First morning of vacation. 14 whole days ahead.',
      de: 'Erster Urlaubsmorgen. 14 ganze Tage vor dir.',
      ar: 'أول صباح في الإجازة، وأمامك 14 يومًا كاملة.',
      fr: 'Premier matin de vacances. 14 jours devant toi.',
      es: 'Primera mañana de vacaciones. Quedan 14 días enteros.',
    },
  },
  {
    emoji: '🛬',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Uçak yarım saat erken indi. Kimse inanamıyor!',
      en: 'Landed half an hour early. Nobody can believe it!',
      de: 'Eine halbe Stunde zu früh gelandet. Keiner glaubt es!',
      ar: 'هبطت الطائرة قبل موعدها بنصف ساعة. لا أحد يصدق!',
      fr: "Atterrissage avec une demi-heure d'avance. Incroyable !",
      es: 'Aterrizaste media hora antes. ¡Nadie lo puede creer!',
    },
  },
  {
    emoji: '💺',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi yol arkadaşı: sessiz ve kolçağı paylaşıyor',
      en: 'Legendary seatmate: quiet, and shares the armrest',
      de: 'Legendärer Sitznachbar: leise und teilt die Armlehne',
      ar: 'رفيق سفر أسطوري: هادئ ويتقاسم معك مسند الذراع',
      fr: "Voisin de siège légendaire : discret et partage l'accoudoir",
      es: 'Vecino de asiento ideal: callado y te deja el apoyabrazos',
    },
  },
];

export const TRAVEL_FREEZE: readonly Draft[] = [
  {
    emoji: '🚪',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYUYORUM',
        en: 'DO NOT DISTURB',
        de: 'NICHT STÖREN',
        ar: 'عدم الإزعاج',
        fr: 'DODO EN COURS',
        es: 'NO MOLESTAR',
      },
      small: {
        tr: 'LÜTFEN RAHATSIZ ETMEYİN',
        en: 'GUEST IS SLEEPING',
        de: 'GAST SCHLÄFT',
        ar: 'النزيل نائم',
        fr: 'PRIÈRE DE NE PAS DÉRANGER',
        es: 'HUÉSPED DURMIENDO',
      },
    },
    caption: {
      tr: 'Ses yok. Belki gider.',
      en: "Not a sound. Maybe they'll leave.",
      de: 'Kein Mucks. Vielleicht gehen sie.',
      ar: 'لا صوت. ربما تذهب.',
      fr: 'Pas un bruit. Ils vont peut-être partir.',
      es: 'Ni un ruido. Quizás se vayan.',
    },
    headline: {
      tr: 'Kat görevlisi kapıyı çalıyor',
      en: 'Housekeeping is knocking',
      de: 'Das Housekeeping klopft',
      ar: 'عاملة التنظيف تطرق الباب',
      fr: 'Le ménage frappe à la porte',
      es: 'Limpieza llama a la puerta',
    },
  },
  {
    emoji: '🙌',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'KOLLAR YUKARI',
        en: 'ARMS UP',
        de: 'ARME HOCH',
        ar: 'ارفع ذراعيك',
        fr: "BRAS EN L'AIR",
        es: 'BRAZOS ARRIBA',
      },
      small: {
        tr: 'TARAMA YAPILIYOR',
        en: 'SCAN IN PROGRESS',
        de: 'SCAN LÄUFT',
        ar: 'جارٍ الفحص',
        fr: 'SCAN EN COURS',
        es: 'ESCANEO EN CURSO',
      },
    },
    caption: {
      tr: 'Tarama bitene kadar kıpırdama.',
      en: "Don't move till the scan's done.",
      de: 'Nicht bewegen, bis der Scan fertig ist.',
      ar: 'لا تتحرك حتى ينتهي الفحص.',
      fr: 'Bouge pas avant la fin du scan.',
      es: 'No te muevas hasta que termine el escaneo.',
    },
    headline: {
      tr: 'Havalimanı tarayıcısındasın',
      en: "You're in the airport scanner",
      de: 'Du stehst im Flughafen-Scanner',
      ar: 'أنت داخل جهاز الفحص في المطار',
      fr: "Tu es dans le scanner de l'aéroport",
      es: 'Estás en el escáner del aeropuerto',
    },
  },
  {
    emoji: '🚥',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'BEKLE',
        en: 'WAIT',
        de: 'WARTEN',
        ar: 'انتظر',
        fr: 'ATTENDEZ',
        es: 'ESPERE',
      },
      small: {
        tr: 'YAYA IŞIĞI KIRMIZI',
        en: "DON'T CROSS ON RED",
        de: 'BEI ROT STEHEN',
        ar: 'الإشارة حمراء للمشاة',
        fr: 'FEU ROUGE PIÉTONS',
        es: 'SEMÁFORO EN ROJO',
      },
    },
    caption: {
      tr: 'Işık hâlâ kırmızı. Kıpırdama.',
      en: "It's still red. Don't move.",
      de: 'Noch ist es rot. Nicht bewegen.',
      ar: 'الإشارة ما زالت حمراء. لا تتحرك.',
      fr: "C'est encore rouge. Bouge pas.",
      es: 'Sigue en rojo. No te muevas.',
    },
    headline: {
      tr: 'Kalabalık senin ilk adımını bekliyor',
      en: "The whole crowd's waiting for you to go",
      de: 'Alle warten darauf, dass du losgehst',
      ar: 'الجميع ينتظر خطوتك الأولى',
      fr: 'Toute la foule attend ton premier pas',
      es: 'Toda la gente espera tu primer paso',
    },
  },
  {
    emoji: '🚃',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SESSİZ VAGON',
        en: 'QUIET CAR',
        de: 'RUHEBEREICH',
        ar: 'عربة هادئة',
        fr: 'VOITURE CALME',
        es: 'VAGÓN SILENCIO',
      },
      small: {
        tr: 'ALÇAK SESLE KONUŞUNUZ',
        en: 'PLEASE KEEP IT DOWN',
        de: 'BITTE LEISE SEIN',
        ar: 'يرجى التزام الهدوء',
        fr: 'MERCI DE RESTER DISCRET',
        es: 'POR FAVOR, GUARDE SILENCIO',
      },
    },
    caption: {
      tr: 'Yarısı açık. Sakın kıpırdama.',
      en: "Half open. Don't you dare move.",
      de: 'Halb offen. Bloß nicht bewegen.',
      ar: 'نصفه مفتوح. إياك أن تتحرك.',
      fr: 'À moitié ouvert. Surtout, bouge pas.',
      es: 'Medio abierta. Ni se te ocurra moverte.',
    },
    headline: {
      tr: 'Sessiz vagonda cips paketi açıyorsun',
      en: "You're opening chips in the quiet car",
      de: 'Du öffnest eine Chipstüte im Ruhebereich',
      ar: 'تفتح كيس رقائق في العربة الهادئة',
      fr: 'Tu ouvres des chips en voiture calme',
      es: 'Abres una bolsa crujiente en el vagón',
    },
  },
  {
    emoji: '📢',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'TREN GARI',
        en: 'TRAIN STATION',
        de: 'HAUPTBAHNHOF',
        ar: 'محطة القطار',
        fr: 'GARE',
        es: 'ESTACIÓN DE TREN',
      },
    },
    caption: {
      tr: 'Cızırtılı. Kıpırdarsan kaçırırsın.',
      en: "It's crackly. Move and you'll miss it.",
      de: 'Es rauscht. Wer sich bewegt, verpasst es.',
      ar: 'الصوت مشوّش. إن تحركت فاتك.',
      fr: 'Ça grésille. Si tu bouges, tu rates tout.',
      es: 'Hay ruido. Si te mueves, te lo pierdes.',
    },
    headline: {
      tr: 'Peron anonsu başladı, herkes dondu',
      en: 'Platform announcement. Everyone froze.',
      de: 'Gleisdurchsage. Alle erstarren.',
      ar: 'بدأ إعلان الرصيف، وتجمّد الجميع',
      fr: 'Annonce en gare. Tout le monde se fige.',
      es: 'Anuncio en el andén. Todos se congelan.',
    },
  },
  {
    emoji: '👥',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'TUR OTOBÜSÜ',
        en: 'TOUR BUS',
        de: 'REISEBUS',
        ar: 'حافلة الرحلات',
        fr: 'CAR DE TOURISME',
        es: 'BUS TURÍSTICO',
      },
    },
    caption: {
      tr: 'Kıpırdarsan baştan sayar.',
      en: 'Move and he starts over.',
      de: 'Beweg dich, und sie fängt von vorn an.',
      ar: 'إن تحركت، بدأ العدّ من جديد.',
      fr: 'Si tu bouges, il recommence.',
      es: 'Si te mueves, empieza otra vez.',
    },
    headline: {
      tr: 'Rehber kafa sayıyor: 23, 24…',
      en: "The guide's counting heads: 23, 24…",
      de: 'Die Reiseleiterin zählt: 23, 24…',
      ar: 'المرشد يعدّ الركّاب: 23، 24…',
      fr: 'Le guide compte les têtes : 23, 24…',
      es: 'El guía cuenta cabezas: 23, 24…',
    },
  },
  {
    emoji: '👀',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'METRO VAGONU',
        en: 'SUBWAY CAR',
        de: 'U-BAHN-WAGEN',
        ar: 'عربة المترو',
        fr: 'RAME DE MÉTRO',
        es: 'VAGÓN DE METRO',
      },
    },
    caption: {
      tr: 'Bölümün sonu geliyor. Kıpırdama.',
      en: "The chapter's almost over. Stay still.",
      de: 'Das Kapitel ist fast vorbei. Halt still.',
      ar: 'الفصل على وشك الانتهاء. لا تتحرك.',
      fr: 'Le chapitre se termine. Bouge pas.',
      es: 'El capítulo está por terminar. No te muevas.',
    },
    headline: {
      tr: 'Yanındakinin kitabını gizlice okuyorsun',
      en: "You're reading over someone's shoulder",
      de: 'Du liest heimlich im Buch neben dir',
      ar: 'تقرأ خلسةً كتاب الراكب بجانبك',
      fr: 'Tu lis en douce le livre de ton voisin',
      es: 'Lees a escondidas el libro de tu vecino',
    },
  },
];
