import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * The city, transport and travel: buses, traffic, taxis, trips, airports, hotels, maps, sightseeing.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const TRAVEL_SKIP: readonly Draft[] = [
  {
    emoji: '💡',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Otel odası: 11 düğme. Bir ışık hâlâ sönmüyor.',
      en: 'The hotel room has 11 switches. One light is still on.',
      de: 'Hotelzimmer: 11 Schalter. Ein Licht brennt immer noch.',
      ar: 'في غرفة الفندق 11 زرًا، وما زال أحد الأضواء مضاءً.',
      fr: "À l'hôtel, 11 interrupteurs. Une lampe reste allumée.",
      es: 'Hotel: 11 interruptores. Una luz sigue encendida.',
      ja: 'ホテルのスイッチ11個。1つだけ電気が消えない。',
      ko: '호텔 방 스위치 11개. 불 하나가 아직도 안 꺼진다.',
    },
  },
  {
    emoji: '📍',
    user: ACCOUNTS.city,
    body: { format: 'scene' },
    caption: {
      tr: '“Hedefinize ulaştınız.” Etraf dümdüz tarla.',
      en: "“You have arrived.” I'm in the middle of a field.",
      de: '„Sie haben Ihr Ziel erreicht.“ Ringsum nur Acker.',
      ar: '«لقد وصلت إلى وجهتك». وحولي حقل فقط.',
      fr: "« Vous êtes arrivé. » Je suis au milieu d'un champ.",
      es: '“Ha llegado a su destino.” Estoy en medio de un campo.',
      ja: '「目的地に到着しました」周りは一面の畑。',
      ko: '“목적지에 도착했습니다.” 주변은 온통 밭.',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Cam kenarına para verdim. Manzara: kanat.',
      en: 'Paid extra for the window seat. View: wing.',
      de: 'Fensterplatz extra bezahlt. Aussicht: Flügel.',
      ar: 'دفعت أكثر لأجل مقعد النافذة. المنظر: الجناح.',
      fr: "Place hublot payée en plus. Vue : l'aile.",
      es: 'Pagué extra por la ventanilla. Vista: el ala.',
      ja: '窓側の席に追加料金を払った。景色：翼。',
      ko: '창가 자리에 돈 더 냈다. 풍경: 날개.',
    },
  },
  {
    emoji: '🚲',
    user: ACCOUNTS.city,
    body: { format: 'scene' },
    caption: {
      tr: 'Bisiklet yolu aniden bitti. Şimdi ben neyim?',
      en: 'The bike lane just ended. So what am I now?',
      de: 'Der Radweg hört einfach auf. Was bin ich jetzt?',
      ar: 'انتهى مسار الدراجات فجأة. فماذا أكون الآن؟',
      fr: "La piste cyclable s'arrête net. Je suis quoi, moi ?",
      es: 'El carril para bicis se acabó. ¿Y ahora qué soy?',
      ja: '自転車レーンが急に終わった。じゃあ今の私は何？',
      ko: '자전거 도로가 갑자기 끝났다. 그럼 난 이제 뭐지?',
    },
  },
  {
    emoji: '🚍',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Yer verdim, “sen otur” dedi. İkimiz de ayaktayız.',
      en: "Offered my seat. She said “you sit.” We're both standing.",
      de: 'Platz angeboten. „Setz du dich.“ Jetzt stehen wir beide.',
      ar: 'عرضت عليها مقعدي فقالت: «اجلس أنت». والآن نقف كلانا.',
      fr: "J'offre ma place, elle me la rend. Personne ne s'assoit.",
      es: 'Ofrecí mi asiento y me dijo “siéntate tú”. Nadie se sentó.',
      ja: '席を譲ったら「あなたが座って」と言われ、2人とも立ってる',
      ko: '자리 양보했더니 “앉아요” 하셔서 둘 다 서 있다',
    },
  },
  {
    emoji: '🗝️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'İsimli anahtarlıklarda yine adım yok.',
      en: 'Every name on the keychain rack but mine. Again.',
      de: 'Namens-Schlüsselanhänger: jeder Name, nur meiner nicht.',
      ar: 'ميداليات المفاتيح بالأسماء… كلها إلا اسمي، كالعادة.',
      fr: 'Porte-clés prénoms : tous sauf le mien. Encore.',
      es: 'Llaveros con nombres: todos menos el mío. Otra vez.',
      ja: '名前入りキーホルダー、今回も私の名前だけない。',
      ko: '이름 새긴 열쇠고리에 내 이름만 또 없다.',
    },
  },
  {
    emoji: '🕓',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Jet lag: vücudum evde, uykum hâlâ yolda.',
      en: "Jet lag: my body's home. My sleep is still in transit.",
      de: 'Jetlag: Ich bin zu Hause, mein Schlaf noch unterwegs.',
      ar: 'إرهاق السفر: جسدي في البيت، ونومي ما زال في الطريق.',
      fr: 'Décalage horaire : mon corps est rentré, pas mon sommeil.',
      es: 'Jet lag: mi cuerpo llegó, mi sueño sigue de viaje.',
      ja: '時差ボケ：体は家、眠気はまだ移動中。',
      ko: '시차 적응 중: 몸은 집에, 잠은 아직 이동 중.',
    },
  },
  {
    emoji: '🛫',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'vardın mı?',
            en: 'did you land?',
            de: 'bist du gelandet?',
            ar: 'هل وصلت؟',
            fr: "t'as atterri ?",
            es: '¿ya aterrizaste?',
            ja: '着いた？',
            ko: '도착했어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'anne daha kalkmadık',
            en: "mom, we haven't even taken off",
            de: 'Mama, wir sind noch nicht mal gestartet',
            ar: 'أمي، لم نقلع بعد',
            fr: 'maman, on a même pas décollé',
            es: 'mamá, ni siquiera despegamos',
            ja: 'お母さん、まだ離陸してないよ',
            ko: '엄마 아직 이륙도 안 했어',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tamam, inince yaz',
            en: 'ok, text me when you land',
            de: 'ok, schreib, wenn du gelandet bist',
            ar: 'حسنًا، اكتب لي حين تهبط',
            fr: "ok, écris-moi quand t'atterris",
            es: 'ok, avísame cuando aterrices',
            ja: 'わかった、着いたら連絡してね',
            ko: '알았어, 내리면 연락해',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'indin mi?',
            en: 'landed?',
            de: 'gelandet?',
            ar: 'هل هبطت؟',
            fr: 'atterri ?',
            es: '¿aterrizaste?',
            ja: '着陸した？',
            ko: '내렸어?',
          },
        },
      ],
    },
    caption: {
      tr: 'Uçak hâlâ pistte',
      en: 'The plane is still on the runway',
      de: 'Das Flugzeug steht noch auf der Startbahn',
      ar: 'الطائرة ما زالت على المدرج',
      fr: "L'avion est encore sur la piste",
      es: 'El avión sigue en la pista',
      ja: '飛行機はまだ滑走路の上',
      ko: '비행기는 아직 활주로 위',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Tatil grubu',
        en: 'Vacation crew',
        de: 'Urlaubsgruppe',
        ar: 'مجموعة الإجازة',
        fr: 'Groupe vacances',
        es: 'Grupo del viaje',
        ja: '旅行グループ',
        ko: '여행 단톡방',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'yarınki plan: 7’de kahvaltı, 8’de müze',
            en: 'tomorrow: breakfast at 7, museum at 8',
            de: 'morgen: 7 Uhr Frühstück, 8 Uhr Museum',
            ar: 'خطة الغد: الفطور في 7، والمتحف في 8',
            fr: 'demain : petit-déj à 7 h, musée à 8 h',
            es: 'mañana: desayuno a las 7, museo a las 8',
            ja: '明日の予定：7時朝食、8時美術館',
            ko: '내일 일정: 7시 아침, 8시 박물관',
          },
        },
        {
          from: 'me',
          text: {
            tr: '9’da kale, 11’de şehir turu…',
            en: 'castle at 9, city tour at 11…',
            de: '9 Uhr Burg, 11 Uhr Stadtführung…',
            ar: 'القلعة في 9، وجولة في المدينة في 11…',
            fr: 'château à 9 h, visite de la ville à 11 h…',
            es: 'castillo a las 9, paseo a las 11…',
            ja: '9時お城、11時市内観光…',
            ko: '9시 성, 11시 시내 투어…',
          },
        },
        {
          from: 'them',
          text: {
            tr: '7’de mi?',
            en: 'at 7??',
            de: 'um 7??',
            ar: 'في السابعة؟',
            fr: 'à 7 h ??',
            es: '¿¿a las 7??',
            ja: '7時？？',
            ko: '7시??',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tatildeyiz sanıyordum',
            en: 'I thought we were on vacation',
            de: 'ich dachte, wir haben Urlaub',
            ar: 'ظننت أننا في إجازة',
            fr: "je croyais qu'on était en vacances",
            es: 'creí que estábamos de vacaciones',
            ja: '休暇中だと思ってた',
            ko: '우리 휴가 온 거 아니었어?',
          },
        },
      ],
    },
    caption: {
      tr: 'Daha planın ilk sayfası bu',
      en: "And that's just page one of the plan",
      de: 'Und das war erst Seite eins des Plans',
      ar: 'وهذه الصفحة الأولى من الخطة فقط',
      fr: "Et ce n'est que la page 1 du programme",
      es: 'Y esa es solo la página uno del plan',
      ja: 'これで計画書の1ページ目',
      ko: '이게 겨우 계획표 1페이지',
    },
  },
  {
    emoji: '🚇',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'neredesin?',
            en: 'where are you?',
            de: 'wo bist du?',
            ar: 'أين أنت؟',
            fr: "t'es où ?",
            es: '¿dónde estás?',
            ja: '今どこ？',
            ko: '어디야?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'metrodayım, 2 durak kaldı',
            en: 'on the subway, 2 stops away',
            de: 'in der U-Bahn, noch 2 Stationen',
            ar: 'في المترو، بقيت محطتان',
            fr: 'dans le métro, encore 2 stations',
            es: 'en el metro, faltan 2 estaciones',
            ja: '地下鉄、あと2駅',
            ko: '지하철이야, 2정거장 남았어',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'canlı konumun uzaklaşıyor ama',
            en: "your live location's moving away tho",
            de: 'dein Live-Standort entfernt sich aber',
            ar: 'لكن موقعك المباشر يبتعد',
            fr: "ta position en direct s'éloigne, là",
            es: 'pero tu ubicación en vivo se aleja',
            ja: 'でも位置情報、離れていってるけど',
            ko: '근데 실시간 위치는 멀어지는데',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tamam, 3 durak kaldı',
            en: 'ok, 3 stops away',
            de: 'ok, noch 3 Stationen',
            ar: 'حسنًا، بقيت 3 محطات',
            fr: 'ok, encore 3 stations',
            es: 'ok, faltan 3 estaciones',
            ja: 'わかった、あと3駅',
            ko: '알았어, 3정거장 남았어',
          },
        },
      ],
    },
    caption: {
      tr: 'Ters yöne binmişim',
      en: 'Wrong direction, obviously',
      de: 'Falsche Richtung, natürlich',
      ar: 'ركبت في الاتجاه المعاكس طبعًا',
      fr: 'Mauvaise direction, évidemment',
      es: 'Dirección contraria, obvio',
      ja: '反対方面の電車に乗ってた',
      ko: '반대 방향으로 탔었다',
    },
  },
  {
    emoji: '🚕',
    user: ACCOUNTS.city,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sürücü',
        en: 'Driver',
        de: 'Fahrer',
        ar: 'السائق',
        fr: 'Chauffeur',
        es: 'Conductor',
        ja: 'ドライバー',
        ko: '기사님',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'geldim, beyaz arabayım',
            en: "I'm here, white car",
            de: 'bin da, weißes Auto',
            ar: 'وصلت، سيارة بيضاء',
            fr: 'je suis là, voiture blanche',
            es: 'ya llegué, auto blanco',
            ja: '着きました、白い車です',
            ko: '도착했어요, 흰색 차예요',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'burada 6 beyaz araba var',
            en: 'there are 6 white cars here',
            de: 'hier stehen 6 weiße Autos',
            ar: 'هنا 6 سيارات بيضاء',
            fr: 'y a 6 voitures blanches ici',
            es: 'aquí hay 6 autos blancos',
            ja: '白い車が6台いるんですが',
            ko: '여기 흰색 차가 6대 있는데요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'size el sallıyorum',
            en: "I'm waving at you",
            de: 'ich winke Ihnen',
            ar: 'أنا ألوّح لك',
            fr: 'je vous fais signe',
            es: 'le estoy haciendo señas',
            ja: '手を振ってます',
            ko: '손 흔들고 있어요',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hepsi el sallıyor',
            en: "they're all waving",
            de: 'alle winken',
            ar: 'كلهم يلوّحون',
            fr: 'ils font tous signe',
            es: 'todos están haciendo señas',
            ja: '全員振ってます',
            ko: '다들 흔들고 있어요',
          },
        },
      ],
    },
    caption: {
      tr: 'Sonunda plakayı sordum',
      en: 'Finally asked for the plate number',
      de: 'Hab dann doch nach dem Kennzeichen gefragt',
      ar: 'في النهاية سألته عن رقم اللوحة',
      fr: "J'ai fini par demander la plaque",
      es: 'Al final le pedí el número de placa',
      ja: '最後にナンバーを聞いた',
      ko: '결국 차 번호를 물어봤다',
    },
  },
  {
    emoji: '🛬',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Uçak indi, kemer ışığı hâlâ yanıyor. Sen:',
        en: "Plane's landed, seatbelt sign still on. You:",
        de: 'Gelandet, Anschnallzeichen noch an. Du:',
        ar: 'هبطت الطائرة وإشارة الحزام ما زالت مضاءة. أنت:',
        fr: 'Atterrissage, voyant ceinture allumé. Toi :',
        es: 'Aterrizaste, pero la luz del cinturón sigue. Tú:',
        ja: '着陸。ベルト着用サインはまだ点灯中。あなたは？',
        ko: '착륙했는데 벨트 사인이 아직 켜져 있다. 나는?',
      },
      options: [
        {
          tr: 'Oturup beklerim',
          en: 'Stay seated',
          de: 'Sitzen bleiben',
          ar: 'أبقى جالسًا',
          fr: 'Je reste assis',
          es: 'Me quedo sentado',
          ja: '座って待つ',
          ko: '앉아서 기다린다',
        },
        {
          tr: 'Hemen ayağa kalkarım',
          en: 'Stand up right away',
          de: 'Sofort aufstehen',
          ar: 'أقف فورًا',
          fr: 'Je me lève direct',
          es: 'Me levanto ya',
          ja: 'すぐに立ち上がる',
          ko: '바로 일어선다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kapı 20 dakika sonra açıldı',
      en: 'The door opened 20 minutes later',
      de: 'Die Tür ging 20 Minuten später auf',
      ar: 'فُتح الباب بعد 20 دقيقة',
      fr: "La porte s'est ouverte 20 minutes après",
      es: 'La puerta se abrió 20 minutos después',
      ja: 'ドアが開いたのは20分後',
      ko: '문은 20분 뒤에 열렸다',
    },
  },
  {
    emoji: '🚙',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Otoparkta arabanı bulamıyorsun. Sen:',
        en: "Your car's lost in the parking garage. You:",
        de: 'Dein Auto ist im Parkhaus verschollen. Du:',
        ar: 'سيارتك ضائعة في المرآب. ماذا تفعل؟',
        fr: 'Ta voiture est perdue dans le parking. Toi :',
        es: 'No encuentras tu auto en el estacionamiento. Tú:',
        ja: '駐車場で車が見つからない。あなたは？',
        ko: '주차장에서 차를 못 찾겠다. 나는?',
      },
      options: [
        {
          tr: 'Kat kat gezerim',
          en: 'Walk every floor',
          de: 'Jede Etage ablaufen',
          ar: 'أبحث في كل طابق',
          fr: 'Tous les étages à pied',
          es: 'Recorro cada piso',
          ja: '全フロアを歩く',
          ko: '층마다 돌아본다',
        },
        {
          tr: 'Bip bip, dinlerim',
          en: 'Beep the key, listen',
          de: 'Piepen und lauschen',
          ar: 'أضغط المفتاح وأنصت',
          fr: "Bip-bip, et j'écoute",
          es: 'Bip bip y escucho',
          ja: 'ピッと鳴らして聞く',
          ko: '삑삑 울려서 듣는다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Dördüncü kattan cılız bir bip geldi',
      en: 'A faint beep from level 4',
      de: 'Ein leises Piepen aus Ebene 4',
      ar: 'صفّارة خافتة من الطابق الرابع',
      fr: 'Un petit bip venu du niveau 4',
      es: 'Un bip lejano desde el piso 4',
      ja: '4階からかすかにピッ',
      ko: '4층에서 희미하게 삑',
    },
  },
  {
    emoji: '🧱',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Otelde “deniz manzaralı” oda aldın. Pencereden:',
        en: 'You booked a “sea view” room. Out the window:',
        de: 'Zimmer mit „Meerblick“ gebucht. Am Fenster:',
        ar: 'حجزت غرفة «مطلة على البحر». من النافذة ترى:',
        fr: 'Chambre « vue sur mer » réservée. Par la fenêtre :',
        es: 'Reservaste “vista al mar”. Por la ventana ves:',
        ja: '「オーシャンビュー」の部屋を予約。窓の外は？',
        ko: '“바다 전망” 객실을 예약했다. 창밖에는?',
      },
      options: [
        {
          tr: 'Deniz',
          en: 'The sea',
          de: 'Das Meer',
          ar: 'البحر',
          fr: 'La mer',
          es: 'El mar',
          ja: '海',
          ko: '바다',
        },
        {
          tr: 'Otopark',
          en: 'A parking lot',
          de: 'Ein Parkplatz',
          ar: 'موقف سيارات',
          fr: 'Un parking',
          es: 'Un estacionamiento',
          ja: '駐車場',
          ko: '주차장',
        },
        {
          tr: 'Karşı otelin duvarı',
          en: "Another hotel's wall",
          de: 'Eine Hotelwand',
          ar: 'جدار فندق آخر',
          fr: "Le mur d'en face",
          es: 'La pared de otro hotel',
          ja: '隣のホテルの壁',
          ko: '옆 호텔 벽',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Duvarın arkası denizmiş, öyle dediler',
      en: 'Apparently the sea is behind that wall',
      de: 'Hinter der Wand ist das Meer, sagen sie',
      ar: 'قالوا إن البحر خلف ذلك الجدار',
      fr: 'Paraît que la mer est derrière le mur',
      es: 'Dicen que el mar está detrás de la pared',
      ja: '壁の向こうは海なんだって',
      ko: '벽 너머가 바다라고 한다',
    },
  },
  {
    emoji: '🚖',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'SÜRÜCÜ 2 DK UZAKTA',
        en: 'DRIVER: 2 MIN AWAY',
        de: 'FAHRER: 2 MIN ENTFERNT',
        ar: 'السائق على بُعد دقيقتين',
        fr: 'CHAUFFEUR À 2 MIN',
        es: 'CONDUCTOR A 2 MIN',
        ja: 'ドライバー到着まで2分',
        ko: '기사님 2분 거리',
      },
      value: null,
      shape: 'flat',
      axis: 'hours',
    },
    caption: {
      tr: '1 saattir 2 dakika uzakta',
      en: 'Two minutes away for an hour now',
      de: 'Seit einer Stunde 2 Minuten entfernt',
      ar: 'على بُعد دقيقتين منذ ساعة',
      fr: 'À 2 minutes depuis une heure',
      es: 'A 2 minutos desde hace una hora',
      ja: '1時間ずっと「あと2分」',
      ko: '1시간째 2분 거리',
    },
  },
  {
    emoji: '⚖️',
    user: ACCOUNTS.trends,
    body: {
      format: 'chart',
      title: {
        tr: 'BAVULUMUN AĞIRLIĞI',
        en: 'SUITCASE WEIGHT',
        de: 'GEWICHT MEINES KOFFERS',
        ar: 'وزن حقيبتي',
        fr: 'POIDS DE MA VALISE',
        es: 'PESO DE MI MALETA',
        ja: 'スーツケースの重さ',
        ko: '캐리어 무게',
      },
      value: { tr: '×2', en: '×2', de: '×2', ar: '×2', fr: '×2', es: '×2', ja: '×2', ko: '×2' },
      shape: 'rise',
      axis: 'days',
    },
    caption: {
      tr: 'Giderken yarısı boştu',
      en: 'It was half empty on the way out',
      de: 'Auf dem Hinweg war er halb leer',
      ar: 'كانت نصف فارغة في طريق الذهاب',
      fr: "À l'aller, elle était à moitié vide",
      es: 'A la ida iba medio vacía',
      ja: '行きは半分空っぽだった',
      ko: '갈 때는 반이 비어 있었다',
    },
  },
  {
    emoji: '🧲',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'HEDİYELİK EŞYA',
        en: 'GIFT SHOP',
        de: 'SOUVENIRLADEN',
        ar: 'متجر التذكارات',
        fr: 'BOUTIQUE SOUVENIRS',
        es: 'TIENDA DE RECUERDOS',
        ja: 'おみやげ屋',
        ko: '기념품 가게',
      },
      items: [
        {
          tr: 'BUZDOLABI MAGNETİ (12)',
          en: 'FRIDGE MAGNETS (12)',
          de: 'MAGNETE (12 STÜCK)',
          ar: 'مغناطيس ثلاجة (12)',
          fr: 'MAGNETS DE FRIGO (12)',
          es: 'IMANES (12 UNIDADES)',
          ja: 'マグネット 12個',
          ko: '냉장고 자석 (12개)',
        },
      ],
    },
    caption: {
      tr: 'Herkese aynısından aldım. Aynı sofrada açtılar.',
      en: 'Same gift for everyone. They opened them together.',
      de: 'Alle kriegen dasselbe. Ausgepackt am selben Tisch.',
      ar: 'الهدية نفسها للجميع… وفتحوها على المائدة نفسها.',
      fr: 'Le même pour tous. Déballés à la même table.',
      es: 'El mismo para todos. Los abrieron en la misma mesa.',
      ja: '全員に同じおみやげ。同じ食卓で開けられた。',
      ko: '모두에게 같은 선물. 한자리에서 같이 뜯었다.',
    },
  },
  {
    emoji: '🥜',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'OTEL MİNİBARI',
        en: 'HOTEL MINIBAR',
        de: 'HOTEL-MINIBAR',
        ar: 'ميني بار الفندق',
        fr: "MINIBAR DE L'HÔTEL",
        es: 'MINIBAR DEL HOTEL',
        ja: 'ホテルのミニバー',
        ko: '호텔 미니바',
      },
      items: [
        {
          tr: 'FISTIK (MİNİ PAKET)',
          en: 'PEANUTS (TINY BAG)',
          de: 'ERDNÜSSE (MINITÜTE)',
          ar: 'فول سوداني (كيس صغير)',
          fr: 'CACAHUÈTES (MINI)',
          es: 'FRUTOS SECOS (MINI)',
          ja: 'ピーナッツ（小袋）',
          ko: '땅콩 (미니 봉지)',
        },
      ],
    },
    caption: {
      tr: 'İkram sanmıştım',
      en: 'I thought it was complimentary',
      de: 'Ich dachte, die sind gratis',
      ar: 'ظننته ضيافة مجانية',
      fr: "Je croyais que c'était offert",
      es: 'Creí que era cortesía',
      ja: 'サービスだと思ってた',
      ko: '무료인 줄 알았다',
    },
  },
  {
    emoji: '🧴',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'KOZMETİK MAĞAZASI',
        en: 'DRUGSTORE',
        de: 'DROGERIE',
        ar: 'الصيدلية',
        fr: 'PARAPHARMACIE',
        es: 'FARMACIA',
        ja: 'ドラッグストア',
        ko: '드러그스토어',
      },
      items: [
        {
          tr: 'ŞAMPUAN (SEYAHAT BOY)',
          en: 'SHAMPOO (TRAVEL SIZE)',
          de: 'SHAMPOO (REISEGRÖSSE)',
          ar: 'شامبو (حجم السفر)',
          fr: 'SHAMPOING MINI FORMAT',
          es: 'CHAMPÚ (TAMAÑO VIAJE)',
          ja: 'シャンプー（旅行用）',
          ko: '샴푸 (여행용)',
        },
        {
          tr: 'DİŞ MACUNU (MİNİ)',
          en: 'TOOTHPASTE (MINI)',
          de: 'ZAHNPASTA (MINI)',
          ar: 'معجون أسنان (صغير)',
          fr: 'DENTIFRICE (MINI)',
          es: 'PASTA DENTAL (MINI)',
          ja: '歯みがき粉（ミニ）',
          ko: '치약 (미니)',
        },
      ],
    },
    caption: {
      tr: 'Her şey mini. Tatil de mini: 2 gün.',
      en: "Everything's mini. So's the trip: 2 days.",
      de: 'Alles in Mini. Der Urlaub auch: 2 Tage.',
      ar: 'كل شيء صغير… حتى الإجازة: يومان.',
      fr: 'Tout est mini. Les vacances aussi : 2 jours.',
      es: 'Todo es mini. Las vacaciones también: 2 días.',
      ja: '全部ミニサイズ。旅行もミニ：2日間。',
      ko: '전부 미니. 여행도 미니: 2일.',
    },
  },
  {
    emoji: '🚉',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '3', en: '3', de: '3', ar: '3', fr: '3', es: '3', ja: '3', ko: '3' },
      text: {
        tr: 'durak fazla gittin; bu postu bitireceğim diye',
        en: 'stops past yours. Just to finish this post.',
        de: 'Stationen zu weit gefahren. Nur für diesen Post.',
        ar: 'محطات بعد محطتك… فقط لتُكمل هذا المنشور',
        fr: 'stations de trop. Juste pour finir ce post.',
        es: 'estaciones de más. Solo por terminar este post.',
        ja: '駅乗り過ごした。この投稿を見終わるために。',
        ko: '정거장 더 갔어요. 이 게시물 끝까지 보려고요.',
      },
    },
    caption: {
      tr: 'Dönüş karşı peronda',
      en: 'The way back is on the other platform',
      de: 'Zurück geht es vom Gleis gegenüber',
      ar: 'طريق العودة من الرصيف المقابل',
      fr: "Le retour, c'est le quai d'en face",
      es: 'La vuelta es en el andén de enfrente',
      ja: '帰りは向かいのホームから',
      ko: '돌아가는 건 반대편 승강장',
    },
  },
  {
    emoji: '💌',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '10', en: '10', de: '10', ar: '10', fr: '10', es: '10', ja: '10', ko: '10' },
      text: {
        tr: 'kartpostal aldın tatilde; hepsi hâlâ çekmecede, pullarıyla',
        en: 'postcards bought on the trip. Still in a drawer, stamps and all.',
        de: 'Postkarten gekauft. Alle noch in der Schublade – mit Marken.',
        ar: 'بطاقات بريدية اشتريتها في الإجازة… كلها في الدرج مع طوابعها',
        fr: 'cartes postales achetées. Au fond du tiroir, avec les timbres.',
        es: 'postales compradas. Siguen en un cajón, con sus sellos.',
        ja: '枚のポストカードを旅先で買った。切手付きで今も引き出しの中。',
        ko: '장의 엽서를 여행에서 샀어요. 우표 붙인 채 아직 서랍 속.',
      },
    },
    caption: {
      tr: 'Seneye yollarım, daha nostaljik olur',
      en: "I'll mail them next year. Extra nostalgic.",
      de: 'Nächstes Jahr schick ich sie. Noch nostalgischer.',
      ar: 'سأرسلها العام القادم، ستكون أكثر حنينًا',
      fr: "Je les enverrai l'an prochain, ce sera plus nostalgique.",
      es: 'Las mando el año que viene, más nostálgico aún.',
      ja: '来年送る。そのほうがエモいし。',
      ko: '내년에 보내야지. 더 감성 있게.',
    },
  },
  {
    emoji: '🏺',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'MÜZE İSTATİSTİĞİ',
        en: 'MUSEUM STATS',
        de: 'MUSEUMSSTATISTIK',
        ar: 'إحصائية المتحف',
        fr: 'STATS DU MUSÉE',
        es: 'DATO DEL MUSEO',
        ja: '美術館データ',
        ko: '박물관 통계',
      },
      big: { tr: '41', en: '41', de: '41', ar: '41', fr: '41', es: '41', ja: '41', ko: '41' },
      text: {
        tr: 'numaralı eserin önündesin; sesli rehber 14’ü anlatıyor',
        en: 'is the piece in front of you. The audio guide is on 14.',
        de: 'ist das Werk vor dir. Der Audioguide erklärt Nummer 14.',
        ar: 'هو رقم القطعة أمامك… والدليل الصوتي يشرح رقم 14',
        fr: "est l'œuvre devant toi. L'audioguide parle de la 14.",
        es: 'es la obra frente a ti. La audioguía habla de la 14.',
        ja: '番の作品の前にいる。音声ガイドは14番を解説中。',
        ko: '번 작품 앞에 있어요. 오디오 가이드는 14번 설명 중.',
      },
    },
    caption: {
      tr: 'Rehber “tablo” diyor, önümde vazo var',
      en: "The guide says “painting.” I'm looking at a vase.",
      de: 'Der Guide sagt „Gemälde“. Vor mir steht eine Vase.',
      ar: 'الدليل يقول «لوحة»، وأمامي مزهرية',
      fr: 'Le guide dit « tableau ». Devant moi : un vase.',
      es: 'La guía dice “cuadro”. Frente a mí hay un jarrón.',
      ja: 'ガイドは「絵画」と言うけど、目の前には花瓶',
      ko: '가이드는 “그림”이라는데 내 앞엔 꽃병',
    },
  },
  {
    emoji: '💺',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'UÇAK KOLTUĞU TIER LIST',
        en: 'PLANE SEAT TIER LIST',
        de: 'FLUGZEUGSITZ-RANKING',
        ar: 'تصنيف مقاعد الطائرة',
        fr: "TIER LIST DES SIÈGES D'AVION",
        es: 'TIER LIST: ASIENTOS DE AVIÓN',
        ja: '飛行機の座席Tier表',
        ko: '비행기 좌석 티어표',
      },
      rows: [['🪟', '🌅'], ['🚶', '🦵'], ['🚻'], ['🥪']],
    },
    caption: {
      tr: 'Orta koltuk C: iki kolçak da komşuların',
      en: 'Middle seat is C. Both armrests belong to the neighbors.',
      de: 'Mittelplatz ist C. Beide Armlehnen sind vergeben.',
      ar: 'المقعد الأوسط في ذيل القائمة: بلا مسند ذراع',
      fr: 'Siège du milieu en C : zéro accoudoir.',
      es: 'Asiento del medio en C: cero reposabrazos.',
      ja: '真ん中の席はC。ひじ掛けは両方とも隣の人のもの。',
      ko: '가운데 자리는 C. 팔걸이 둘 다 옆 사람 거.',
    },
  },
  {
    emoji: '🚋',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'ŞEHİR İÇİ ULAŞIM TIER LIST',
        en: 'CITY TRANSIT TIER LIST',
        de: 'STADTVERKEHR-RANKING',
        ar: 'تصنيف المواصلات في المدينة',
        fr: 'TIER LIST DES TRANSPORTS',
        es: 'TIER LIST DEL TRANSPORTE',
        ja: '市内交通Tier表',
        ko: '시내 교통 티어표',
      },
      rows: [['🚋', '🚶'], ['🚇', '🚲'], ['🚌', '🛴'], ['🚗']],
    },
    caption: {
      tr: 'Tramvay S. Tek sebebi: zili.',
      en: "Tram's in S. One reason: the bell.",
      de: 'Tram auf S. Einziger Grund: die Klingel.',
      ar: 'الترام في القمة، والسبب الوحيد: جرسه.',
      fr: 'Tram en S. Une seule raison : la cloche.',
      es: 'El tranvía es S. Única razón: la campanita.',
      ja: '路面電車はS。理由はひとつ：ベル。',
      ko: '트램은 S. 이유는 단 하나: 종소리.',
    },
  },
  {
    emoji: '🏃',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '✈️',
        app: {
          tr: 'Havalimanı',
          en: 'Airport',
          de: 'Flughafen',
          ar: 'المطار',
          fr: 'Aéroport',
          es: 'Aeropuerto',
          ja: '空港',
          ko: '공항',
        },
        text: {
          tr: 'Biniş kapın 3’ten 86’ya taşındı',
          en: 'Your gate moved from 3 to 86',
          de: 'Dein Gate wurde von 3 auf 86 verlegt',
          ar: 'نُقلت بوابتك من 3 إلى 86',
          fr: 'Ta porte passe de la 3 à la 86',
          es: 'Tu puerta cambió de la 3 a la 86',
          ja: '搭乗口が3番から86番に変更されました',
          ko: '탑승구가 3번에서 86번으로 변경됐어요',
        },
      },
    },
    caption: {
      tr: '86 numara neredeyse başka şehirde',
      en: 'Gate 86 is basically in the next town',
      de: 'Gate 86 liegt quasi in der Nachbarstadt',
      ar: 'البوابة 86 تكاد تكون في مدينة أخرى',
      fr: "La porte 86 est quasi dans la ville d'à côté",
      es: 'La puerta 86 está casi en otra ciudad',
      ja: '86番ゲートはほぼ隣町',
      ko: '86번 게이트는 거의 옆 동네',
    },
  },
  {
    emoji: '💬',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌐',
        app: {
          tr: 'Çevirmen',
          en: 'Translator',
          de: 'Übersetzer',
          ar: 'المترجم',
          fr: 'Traducteur',
          es: 'Traductor',
          ja: '翻訳アプリ',
          ko: '번역기',
        },
        text: {
          tr: '14. çeviri: “Tuvalet nerede?”',
          en: "Translation #14: “Where's the restroom?”",
          de: '14. Übersetzung: „Wo ist die Toilette?“',
          ar: 'الترجمة رقم 14: «أين الحمّام؟»',
          fr: '14e traduction : « Les toilettes ? »',
          es: 'Traducción 14: “¿Dónde está el baño?”',
          ja: '14回目の翻訳：「トイレはどこ？」',
          ko: '14번째 번역: “화장실 어디예요?”',
        },
      },
    },
    caption: {
      tr: '14 günlük tatil, hâlâ ezberleyemedim',
      en: "14-day trip. Still haven't memorized it.",
      de: '14 Tage Urlaub, immer noch nicht gemerkt',
      ar: 'إجازة 14 يومًا… وما زلت لم أحفظها',
      fr: '14 jours de vacances, toujours pas retenu',
      es: '14 días de viaje y todavía no me la sé',
      ja: '14日間の旅行。まだ覚えられない。',
      ko: '14일 여행인데 아직도 못 외웠다',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayatta ilerlemek istiyorsan önce otobüsün arkasına ilerle.',
        en: 'If you want to move forward in life, first move to the back of the bus.',
        de: 'Wer im Leben vorankommen will, muss im Bus erst mal durchgehen.',
        ar: 'إن أردت أن تتقدّم في الحياة، فتقدّم أولًا إلى آخر الحافلة.',
        fr: 'Pour avancer dans la vie, commence par avancer au fond du bus.',
        es: 'Si quieres avanzar en la vida, avanza primero al fondo del bus.',
        ja: '人生で前に進みたいなら、まずバスの奥へお進みください。',
        ko: '인생에서 앞으로 나아가고 싶다면, 먼저 버스 안쪽으로 들어가라.',
      },
    },
    caption: {
      tr: 'Şoför bu sabah 6 kez söyledi',
      en: 'The driver said it 6 times this morning',
      de: 'Der Fahrer hat es heute früh 6-mal gesagt',
      ar: 'قالها السائق 6 مرات هذا الصباح',
      fr: "Le chauffeur l'a dit 6 fois ce matin",
      es: 'El conductor lo dijo 6 veces esta mañana',
      ja: '運転手さんが今朝6回言ってた',
      ko: '기사님이 오늘 아침에만 6번 말했다',
    },
  },
  {
    emoji: '🛎️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Kaybolmak da bir keşiftir. — Otel koridorunda 20 dakika dolaşan biri',
        en: 'Getting lost is discovery too. — Me, 20 minutes in the hotel hallway',
        de: 'Sich verlaufen ist auch Entdecken. — Ich, 20 Minuten im Hotelflur',
        ar: 'الضياع اكتشاف أيضًا. — شخص تاه 20 دقيقة في ممر الفندق',
        fr: "Se perdre, c'est découvrir. — Moi, 20 minutes dans le couloir de l'hôtel",
        es: 'Perderse también es descubrir. — Yo, 20 minutos en el pasillo del hotel',
        ja: '迷子もまた発見である。— ホテルの廊下を20分さまよった私',
        ko: '길을 잃는 것도 발견이다. — 호텔 복도를 20분 헤맨 나',
      },
    },
    caption: {
      tr: 'Odam 312. Ben 213’ün önündeydim.',
      en: 'My room is 312. I was outside 213.',
      de: 'Mein Zimmer: 312. Ich stand vor der 213.',
      ar: 'غرفتي 312، وكنت أقف أمام 213.',
      fr: "Ma chambre, c'est la 312. J'étais devant la 213.",
      es: 'Mi habitación es la 312. Estaba frente a la 213.',
      ja: '部屋は312号室。私がいたのは213の前。',
      ko: '내 방은 312호. 난 213호 앞에 있었다.',
    },
  },
  {
    emoji: '🗺️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Dünya bir kitaptır. Ben sadece yorumlarını okuyorum.',
        en: 'The world is a book. I just read the reviews.',
        de: 'Die Welt ist ein Buch. Ich lese nur die Bewertungen.',
        ar: 'العالم كتاب، وأنا أكتفي بقراءة التقييمات.',
        fr: 'Le monde est un livre. Moi, je lis juste les avis.',
        es: 'El mundo es un libro. Yo solo leo las reseñas.',
        ja: '世界は一冊の本だ。私はレビューだけ読んでいる。',
        ko: '세상은 한 권의 책이다. 나는 리뷰만 읽는다.',
      },
    },
    caption: {
      tr: '1.482 yorum okudum. Evden çıkmadım.',
      en: 'Read 1,482 reviews. Never left the house.',
      de: '1.482 Bewertungen gelesen. Nie rausgegangen.',
      ar: 'قرأت 1,482 تقييمًا، ولم أغادر البيت.',
      fr: 'Lu 1 482 avis. Pas mis un pied dehors.',
      es: 'Leí 1482 reseñas. No salí de casa.',
      ja: 'レビューを1,482件読んだ。家からは出てない。',
      ko: '리뷰 1,482개 읽음. 집 밖엔 안 나감.',
    },
  },
  {
    emoji: '🔒',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Her macera bir adımla başlar. Benimki kapıyı kontrole dönmekle.',
        en: 'Every trip starts with one step. Mine: back to check the door.',
        de: 'Jede Reise beginnt mit einem Schritt. Meiner: zurück zur Tür.',
        ar: 'كل مغامرة تبدأ بخطوة. وخطوتي: العودة لأتفقّد الباب.',
        fr: 'Tout voyage commence par un pas. Le mien : retour à la porte.',
        es: 'Toda aventura empieza con un paso. El mío: volver a revisar la puerta.',
        ja: 'どんな冒険も一歩から始まる。私の一歩は、鍵の確認に戻ること。',
        ko: '모든 여행은 한 걸음부터. 내 첫걸음은 문 잠갔나 보러 돌아가기.',
      },
    },
    caption: {
      tr: '3 kez döndüm. Kilitliydi.',
      en: 'Went back 3 times. It was locked.',
      de: '3-mal zurück. Sie war abgeschlossen.',
      ar: 'عدت 3 مرات. كان مقفلًا.',
      fr: '3 allers-retours. Elle était fermée.',
      es: 'Volví 3 veces. Estaba cerrada.',
      ja: '3回戻った。鍵はかかってた。',
      ko: '3번 돌아갔다. 잠겨 있었다.',
    },
  },
  {
    emoji: '🤳',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bazı manzaralar fotoğrafa sığmaz. Önünde 40 turist varsa hiç sığmaz.',
        en: "Some views don't fit in a photo. Especially behind 40 tourists.",
        de: 'Manches passt in kein Foto. Vor allem mit 40 Touristen davor.',
        ar: 'بعض المناظر لا تتّسع لها صورة، خاصةً إذا وقف أمامها 40 سائحًا.',
        fr: 'Certaines vues ne tiennent pas en photo. Surtout derrière 40 touristes.',
        es: 'Hay vistas que no caben en una foto. Menos detrás de 40 turistas.',
        ja: '写真に収まらない景色もある。前に観光客が40人いればなおさらだ。',
        ko: '사진에 다 담기지 않는 풍경이 있다. 앞에 관광객 40명이 있으면 더더욱.',
      },
    },
    caption: {
      tr: 'Ben de o 40 kişiden biriydim, pardon',
      en: 'I was one of the 40. Sorry.',
      de: 'Ich war einer der 40. Sorry.',
      ar: 'وكنت واحدًا من الأربعين، آسف.',
      fr: "J'étais l'un des 40. Pardon.",
      es: 'Yo era uno de los 40. Perdón.',
      ja: '私もその40人のひとりでした。すみません',
      ko: '나도 그 40명 중 하나였다. 죄송.',
    },
  },
];

export const TRAVEL_LIKE: readonly Draft[] = [
  {
    emoji: '🚗',
    user: ACCOUNTS.baris,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk seferde paralel park ettim!! tanık yok ama',
      en: 'parallel parked on the first try!! no witnesses tho',
      de: 'beim ersten versuch eingeparkt!! leider ohne zeugen',
      ar: 'ركنت السيارة من أول محاولة!! لكن بلا شهود',
      fr: 'créneau réussi du premier coup !! zéro témoin',
      es: '¡¡me estacioné a la primera!! pero sin testigos',
      ja: '縦列駐車、一発で成功！！目撃者はいないけど',
      ko: '평행 주차 한 번에 성공!! 목격자는 없지만',
    },
  },
  {
    emoji: '🚆',
    user: ACCOUNTS.bora,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk kez gece treniyle gittim, ranza >>> otel',
      en: 'first night train ever, bunk bed >>> hotel',
      de: 'erster nachtzug, schlafkoje >>> hotel',
      ar: 'أول رحلة لي في قطار ليلي… والسرير أحلى من الفندق',
      fr: 'mon premier train de nuit, couchette >>> hôtel',
      es: 'mi primer tren nocturno, litera >>> hotel',
      ja: '初めての夜行列車、寝台 >>> ホテル',
      ko: '첫 야간열차, 침대칸 >>> 호텔',
    },
  },
  {
    emoji: '🏙️',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'biri bana yol sordu ve biliyordum!! artık buralıyım',
      en: 'someone asked me for directions and i knew!! local now',
      de: 'hab heute jemandem den weg erklärt!! bin jetzt einheimisch',
      ar: 'سألني أحدهم عن الطريق وكنت أعرفه!! صرت من أهل المدينة',
      fr: "on m'a demandé le chemin, je savais !! je suis du coin",
      es: '¡¡me preguntaron una calle y la sabía!! ya soy de aquí',
      ja: '道を聞かれて答えられた！！もう地元民',
      ko: '누가 길 물어봤는데 알았음!! 이제 현지인',
    },
  },
  {
    emoji: '🎒',
    user: ACCOUNTS.ece,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk solo gezim: kendimle çok iyi anlaştık',
      en: "first solo trip: turns out i'm great company",
      de: 'erste solo-reise: ich bin echt gute gesellschaft',
      ar: 'أول رحلة لي وحدي: اتضح أنني رفيقة رائعة',
      fr: 'premier voyage en solo : je suis de super compagnie',
      es: 'mi primer viaje sola: resulta que soy buena compañía',
      ja: '初ひとり旅：自分と気が合うことが判明',
      ko: '첫 혼자 여행: 나랑 나 완전 잘 맞음',
    },
  },
  {
    emoji: '📮',
    user: ACCOUNTS.yagmur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'anneanneme',
        en: 'to grandma',
        de: 'an oma',
        ar: 'إلى جدتي',
        fr: 'pour mamie',
        es: 'para la abuela',
        ja: 'おばあちゃんへ',
        ko: '할머니께',
      },
    },
    caption: {
      tr: 'kartpostal benden sonra vardı, beraber okuduk',
      en: 'the postcard got there after me, so we read it together',
      de: 'die karte kam nach mir an, wir haben sie zusammen gelesen',
      ar: 'وصلت البطاقة بعدي، فقرأناها معًا',
      fr: "la carte est arrivée après moi, on l'a lue ensemble",
      es: 'la postal llegó después que yo, la leímos juntas',
      ja: 'ハガキが私より後に届いたから、一緒に読んだ',
      ko: '엽서가 나보다 늦게 도착해서 같이 읽었음',
    },
  },
  {
    emoji: '🎡',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'en tepede',
        en: 'top of the wheel',
        de: 'ganz oben',
        ar: 'في القمة',
        fr: 'tout en haut',
        es: 'en lo más alto',
        ja: 'てっぺん',
        ko: '꼭대기',
      },
    },
    caption: {
      tr: 'dönme dolaba bindim!! gözlerim kapalıydı ama sayılır',
      en: 'rode the ferris wheel!! eyes shut, still counts',
      de: 'riesenrad gefahren!! augen zu, zählt trotzdem',
      ar: 'ركبت العجلة الدوّارة!! بعينين مغمضتين، لكنها تُحسب',
      fr: "j'ai fait la grande roue !! les yeux fermés, mais ça compte",
      es: '¡¡me subí a la rueda gigante!! ojos cerrados, pero cuenta',
      ja: '観覧車に乗った！！目はつぶってたけどセーフ',
      ko: '관람차 탔다!! 눈은 감았지만 인정',
    },
  },
  {
    emoji: '🦖',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'kankam rex',
        en: 'my buddy rex',
        de: 'mein kumpel rex',
        ar: 'صديقي ريكس',
        fr: 'mon pote rex',
        es: 'mi amigo rex',
        ja: '相棒レックス',
        ko: '내 친구 렉스',
      },
    },
    caption: {
      tr: 'dinozorla fotoğraf sırası: 30 çocuk ve ben',
      en: 'line for the dinosaur photo: 30 kids and me',
      de: 'schlange fürs dino-foto: 30 kinder und ich',
      ar: 'طابور التصوير مع الديناصور: 30 طفلًا وأنا',
      fr: 'file pour la photo avec le dino : 30 enfants et moi',
      es: 'fila para la foto con el dinosaurio: 30 niños y yo',
      ja: '恐竜との写真待ちの列：子ども30人と私',
      ko: '공룡 사진 줄: 어린이 30명과 나',
    },
  },
  {
    emoji: '🚋',
    user: ACCOUNTS.defne,
    body: {
      format: 'polaroid',
      note: {
        tr: 'en ön koltuk',
        en: 'front seat',
        de: 'erste reihe',
        ar: 'المقعد الأمامي',
        fr: 'premier rang',
        es: 'primera fila',
        ja: 'いちばん前の席',
        ko: '맨 앞자리',
      },
    },
    caption: {
      tr: 'tramvayda en öne oturdum, vatman el salladı',
      en: 'sat up front on the tram and the driver waved at me',
      de: 'ganz vorne in der tram, der fahrer hat mir gewinkt',
      ar: 'جلست في مقدمة الترام، ولوّح لي السائق',
      fr: "tout devant dans le tram, le conducteur m'a fait coucou",
      es: 'me senté al frente en el tranvía y el conductor me saludó',
      ja: '路面電車の最前列に座ったら、運転士さんに手を振られた',
      ko: '트램 맨 앞에 앉았더니 기관사님이 손 흔들어 줌',
    },
  },
  {
    emoji: '🏰',
    user: ACCOUNTS.bora,
    body: { format: 'dump', emojis: ['🏰', '🎒', '🚆', '🗺️', '🥨'] },
    caption: {
      tr: 'sırt çantası dump’ı: 5 şehir, 1 çanta, 0 ütü',
      en: 'backpacking dump: 5 cities, 1 bag, 0 ironing',
      de: 'rucksack-dump: 5 städte, 1 rucksack, 0 bügeln',
      ar: 'رحلة بحقيبة ظهر: 5 مدن، حقيبة واحدة، ولا كيّ أبدًا',
      fr: 'dump sac à dos : 5 villes, 1 sac, 0 repassage',
      es: 'dump mochilero: 5 ciudades, 1 mochila, 0 planchado',
      ja: 'バックパック旅まとめ：5都市、バッグ1つ、アイロン0回',
      ko: '배낭여행 덤프: 5개 도시, 가방 1개, 다림질 0번',
    },
  },
  {
    emoji: '🏡',
    user: ACCOUNTS.deniz,
    body: { format: 'dump', emojis: ['🏡', '🧳', '🧺', '🛏️', '🪴'] },
    caption: {
      tr: 'eve dönüş dump’ı: bavul, çamaşır ve o ev kokusu',
      en: 'back home dump: suitcase, laundry and that smell of home',
      de: 'heimkehr-dump: koffer, wäsche und dieser duft von zuhause',
      ar: 'العودة إلى البيت: حقيبة، وغسيل، ورائحة البيت تلك',
      fr: 'dump du retour : valise, lessive et cette odeur de maison',
      es: 'dump del regreso: maleta, ropa sucia y ese olor a casa',
      ja: '帰宅まとめ：スーツケース、洗濯物、そして家のにおい',
      ko: '귀가 덤프: 캐리어, 빨래, 그리고 그 집 냄새',
    },
  },
  {
    emoji: '🌉',
    user: ACCOUNTS.tolga,
    body: { format: 'dump', emojis: ['🌉', '👟', '📸', '🌆', '🌊'] },
    caption: {
      tr: 'köprü turu: şehrin 7 köprüsünü bir günde yürüdük!!',
      en: 'bridge tour: walked all 7 bridges in one day!!',
      de: 'brücken-tour: alle 7 brücken an einem tag!!',
      ar: 'جولة الجسور: عبرنا جسور المدينة السبعة في يوم واحد!!',
      fr: 'tour des ponts : les 7 ponts de la ville en un jour !!',
      es: '¡¡ruta de puentes: los 7 puentes de la ciudad en un día!!',
      ja: '橋めぐり：街の7つの橋を1日で全部歩いた！！',
      ko: '다리 투어: 도시의 다리 7개를 하루에 다 걸었다!!',
    },
  },
  {
    emoji: '🌇',
    user: ACCOUNTS.irem,
    body: { format: 'dump', emojis: ['🌇', '⛲', '🚋', '🍦', '🎟️'] },
    caption: {
      tr: 'kendi şehrimde turist oldum, meğer ne güzelmiş',
      en: "played tourist in my own city, turns out it's gorgeous",
      de: 'tourist in der eigenen stadt, sie ist ja wunderschön',
      ar: 'صرت سائحة في مدينتي… واتضح أنها جميلة جدًا',
      fr: 'touriste dans ma propre ville, elle est trop belle en fait',
      es: 'fui turista en mi propia ciudad y resulta que es preciosa',
      ja: '地元で観光客してみたら、めちゃくちゃきれいな街だった',
      ko: '내 도시에서 관광객 놀이 해 봄, 알고 보니 엄청 예쁨',
    },
  },
];

export const TRAVEL_HOLD: readonly Draft[] = [
  {
    emoji: '🅿️',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tam kapının önünde boş park yeri. Rüya mı bu?',
      en: 'An open spot right outside the door. Am I dreaming?',
      de: 'Freier Parkplatz direkt vor der Tür. Träum ich?',
      ar: 'موقف فارغ أمام الباب مباشرة. هل أحلم؟',
      fr: 'Une place libre pile devant la porte. Je rêve ?',
      es: 'Un lugar libre justo frente a la puerta. ¿Estoy soñando?',
      ja: 'ドアの真ん前に空き駐車スペース。これは夢？',
      ko: '문 바로 앞에 빈 주차 자리. 꿈인가요?',
    },
  },
  {
    emoji: '🚦',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Eve kadar bütün ışıklar yeşil. Sakın bırakma!',
      en: "Green lights all the way home. Don't let go!",
      de: 'Grüne Welle bis nach Hause. Nicht loslassen!',
      ar: 'كل الإشارات خضراء حتى البيت. لا تُفلت!',
      fr: "Que des feux verts jusqu'à la maison. Lâche pas !",
      es: 'Semáforos en verde hasta casa. ¡No sueltes!',
      ja: '家までずっと青信号。離さないで！',
      ko: '집까지 전부 초록불. 절대 놓지 마세요!',
    },
  },
  {
    emoji: '🧳',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bantta ilk çıkan bavul senin. Bu hiç olmaz!',
      en: 'First bag on the carousel is yours. That never happens!',
      de: 'Der erste Koffer auf dem Band ist deiner. Passiert nie!',
      ar: 'أول حقيبة على السير هي حقيبتك. هذا لا يحدث أبدًا!',
      fr: 'Première valise sur le tapis : la tienne. Du jamais vu !',
      es: 'La primera maleta en la cinta es la tuya. ¡Nunca pasa!',
      ja: 'ターンテーブルの最初の荷物があなたのもの。ありえない！',
      ko: '벨트에서 첫 번째로 나온 가방이 내 거! 절대 없는 일!',
    },
  },
  {
    emoji: '🚕',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sağanak yağmurda boş taksi sana doğru geliyor',
      en: 'Pouring rain, and an empty cab is heading your way',
      de: 'Platzregen, und ein freies Taxi kommt auf dich zu',
      ar: 'مطر غزير، وسيارة أجرة فارغة تتجه نحوك',
      fr: 'Il pleut des cordes et un taxi libre arrive vers toi',
      es: 'Llueve a cántaros y un taxi libre viene hacia ti',
      ja: '土砂降りの中、空車のタクシーがこっちに来る',
      ko: '폭우 속에 빈 택시가 이쪽으로 온다',
    },
  },
  {
    emoji: '🏝️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tatilin ilk sabahı. Önünde tam 14 gün var.',
      en: 'First morning of vacation. 14 whole days ahead.',
      de: 'Erster Urlaubsmorgen. 14 ganze Tage vor dir.',
      ar: 'أول صباح في الإجازة، وأمامك 14 يومًا كاملة.',
      fr: 'Premier matin de vacances. 14 jours devant toi.',
      es: 'Primera mañana de vacaciones. Quedan 14 días enteros.',
      ja: '休暇の初日の朝。まるまる14日間ある。',
      ko: '휴가 첫날 아침. 무려 14일이 남았다.',
    },
  },
  {
    emoji: '🛬',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Uçak yarım saat erken indi. Kimse inanamıyor!',
      en: 'Landed half an hour early. Nobody can believe it!',
      de: 'Eine halbe Stunde zu früh gelandet. Keiner glaubt es!',
      ar: 'هبطت الطائرة قبل موعدها بنصف ساعة. لا أحد يصدق!',
      fr: "Atterrissage avec une demi-heure d'avance. Incroyable !",
      es: 'Aterrizaste media hora antes. ¡Nadie lo puede creer!',
      ja: '飛行機が30分早く着陸。誰も信じられない！',
      ko: '비행기가 30분 일찍 착륙. 다들 믿기지 않는 눈치!',
    },
  },
  {
    emoji: '💺',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi yol arkadaşı: sessiz ve kolçağı paylaşıyor',
      en: 'Legendary seatmate: quiet, and shares the armrest',
      de: 'Legendärer Sitznachbar: leise und teilt die Armlehne',
      ar: 'رفيق سفر أسطوري: هادئ ويتقاسم معك مسند الذراع',
      fr: "Voisin de siège légendaire : discret et partage l'accoudoir",
      es: 'Vecino de asiento ideal: callado y te deja el apoyabrazos',
      ja: '伝説の隣人：静かで、ひじ掛けを半分こしてくれる',
      ko: '전설의 옆자리 승객: 조용하고 팔걸이도 나눠 씀',
    },
  },
];

export const TRAVEL_FREEZE: readonly Draft[] = [
  {
    emoji: '🚪',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYUYORUM',
        en: 'DO NOT DISTURB',
        de: 'NICHT STÖREN',
        ar: 'عدم الإزعاج',
        fr: 'DODO EN COURS',
        es: 'NO MOLESTAR',
        ja: '起こさないで',
        ko: '자는 중',
      },
      small: {
        tr: 'LÜTFEN RAHATSIZ ETMEYİN',
        en: 'GUEST IS SLEEPING',
        de: 'GAST SCHLÄFT',
        ar: 'النزيل نائم',
        fr: 'PRIÈRE DE NE PAS DÉRANGER',
        es: 'HUÉSPED DURMIENDO',
        ja: '入室はご遠慮ください',
        ko: '방해하지 마세요',
      },
    },
    caption: {
      tr: 'Ses yok. Belki gider.',
      en: "Not a sound. Maybe they'll leave.",
      de: 'Kein Mucks. Vielleicht gehen sie.',
      ar: 'لا صوت. ربما تذهب.',
      fr: 'Pas un bruit. Ils vont peut-être partir.',
      es: 'Ni un ruido. Quizás se vayan.',
      ja: '音を立てないで。帰るかもしれない。',
      ko: '소리 내지 마세요. 그냥 갈지도 몰라요.',
    },
    headline: {
      tr: 'Kat görevlisi kapıyı çalıyor',
      en: 'Housekeeping is knocking',
      de: 'Das Housekeeping klopft',
      ar: 'عاملة التنظيف تطرق الباب',
      fr: 'Le ménage frappe à la porte',
      es: 'Limpieza llama a la puerta',
      ja: '客室清掃がノックしてる',
      ko: '객실 청소 직원이 노크하고 있어요',
    },
  },
  {
    emoji: '🙌',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'KOLLAR YUKARI',
        en: 'ARMS UP',
        de: 'ARME HOCH',
        ar: 'ارفع ذراعيك',
        fr: "BRAS EN L'AIR",
        es: 'BRAZOS ARRIBA',
        ja: '両手を上に',
        ko: '팔 올리세요',
      },
      small: {
        tr: 'TARAMA YAPILIYOR',
        en: 'SCAN IN PROGRESS',
        de: 'SCAN LÄUFT',
        ar: 'جارٍ الفحص',
        fr: 'SCAN EN COURS',
        es: 'ESCANEO EN CURSO',
        ja: 'スキャン中',
        ko: '스캔 중',
      },
    },
    caption: {
      tr: 'Tarama bitene kadar kıpırdama.',
      en: "Don't move till the scan's done.",
      de: 'Nicht bewegen, bis der Scan fertig ist.',
      ar: 'لا تتحرك حتى ينتهي الفحص.',
      fr: 'Bouge pas avant la fin du scan.',
      es: 'No te muevas hasta que termine el escaneo.',
      ja: 'スキャンが終わるまで動かないで。',
      ko: '스캔이 끝날 때까지 움직이지 마세요.',
    },
    headline: {
      tr: 'Havalimanı tarayıcısındasın',
      en: "You're in the airport scanner",
      de: 'Du stehst im Flughafen-Scanner',
      ar: 'أنت داخل جهاز الفحص في المطار',
      fr: "Tu es dans le scanner de l'aéroport",
      es: 'Estás en el escáner del aeropuerto',
      ja: '空港のボディスキャナーの中',
      ko: '공항 보안 검색대에 서 있어요',
    },
  },
  {
    emoji: '🚥',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'BEKLE',
        en: 'WAIT',
        de: 'WARTEN',
        ar: 'انتظر',
        fr: 'ATTENDEZ',
        es: 'ESPERE',
        ja: '待って',
        ko: '기다리세요',
      },
      small: {
        tr: 'YAYA IŞIĞI KIRMIZI',
        en: "DON'T CROSS ON RED",
        de: 'BEI ROT STEHEN',
        ar: 'الإشارة حمراء للمشاة',
        fr: 'FEU ROUGE PIÉTONS',
        es: 'SEMÁFORO EN ROJO',
        ja: '歩行者信号は赤',
        ko: '보행자 신호 빨간불',
      },
    },
    caption: {
      tr: 'Işık hâlâ kırmızı. Kıpırdama.',
      en: "It's still red. Don't move.",
      de: 'Noch ist es rot. Nicht bewegen.',
      ar: 'الإشارة ما زالت حمراء. لا تتحرك.',
      fr: "C'est encore rouge. Bouge pas.",
      es: 'Sigue en rojo. No te muevas.',
      ja: 'まだ赤。動かないで。',
      ko: '아직 빨간불이에요. 움직이지 마세요.',
    },
    headline: {
      tr: 'Kalabalık senin ilk adımını bekliyor',
      en: "The whole crowd's waiting for you to go",
      de: 'Alle warten darauf, dass du losgehst',
      ar: 'الجميع ينتظر خطوتك الأولى',
      fr: 'Toute la foule attend ton premier pas',
      es: 'Toda la gente espera tu primer paso',
      ja: 'みんながあなたの一歩目を待ってる',
      ko: '다들 당신이 먼저 건너길 기다려요',
    },
  },
  {
    emoji: '🚃',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'SESSİZ VAGON',
        en: 'QUIET CAR',
        de: 'RUHEBEREICH',
        ar: 'عربة هادئة',
        fr: 'VOITURE CALME',
        es: 'VAGÓN SILENCIO',
        ja: '静かな車両',
        ko: '정숙 칸',
      },
      small: {
        tr: 'ALÇAK SESLE KONUŞUNUZ',
        en: 'PLEASE KEEP IT DOWN',
        de: 'BITTE LEISE SEIN',
        ar: 'يرجى التزام الهدوء',
        fr: 'MERCI DE RESTER DISCRET',
        es: 'POR FAVOR, GUARDE SILENCIO',
        ja: '小声でお話しください',
        ko: '조용히 대화해 주세요',
      },
    },
    caption: {
      tr: 'Yarısı açık. Sakın kıpırdama.',
      en: "Half open. Don't you dare move.",
      de: 'Halb offen. Bloß nicht bewegen.',
      ar: 'نصفه مفتوح. إياك أن تتحرك.',
      fr: 'À moitié ouvert. Surtout, bouge pas.',
      es: 'Medio abierta. Ni se te ocurra moverte.',
      ja: '半分開いてる。絶対に動かないで。',
      ko: '반쯤 뜯었어요. 절대 움직이지 마세요.',
    },
    headline: {
      tr: 'Sessiz vagonda cips paketi açıyorsun',
      en: "You're opening chips in the quiet car",
      de: 'Du öffnest eine Chipstüte im Ruhebereich',
      ar: 'تفتح كيس رقائق في العربة الهادئة',
      fr: 'Tu ouvres des chips en voiture calme',
      es: 'Abres una bolsa crujiente en el vagón',
      ja: '静かな車両でポテチの袋を開けてる',
      ko: '정숙 칸에서 과자 봉지를 뜯는 중',
    },
  },
  {
    emoji: '📢',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'TREN GARI',
        en: 'TRAIN STATION',
        de: 'HAUPTBAHNHOF',
        ar: 'محطة القطار',
        fr: 'GARE',
        es: 'ESTACIÓN DE TREN',
        ja: '駅のホーム',
        ko: '기차역',
      },
    },
    caption: {
      tr: 'Cızırtılı. Kıpırdarsan kaçırırsın.',
      en: "It's crackly. Move and you'll miss it.",
      de: 'Es rauscht. Wer sich bewegt, verpasst es.',
      ar: 'الصوت مشوّش. إن تحركت فاتك.',
      fr: 'Ça grésille. Si tu bouges, tu rates tout.',
      es: 'Hay ruido. Si te mueves, te lo pierdes.',
      ja: '音がガサガサ。動いたら聞き逃す。',
      ko: '지직거려요. 움직이면 놓쳐요.',
    },
    headline: {
      tr: 'Peron anonsu başladı, herkes dondu',
      en: 'Platform announcement. Everyone froze.',
      de: 'Gleisdurchsage. Alle erstarren.',
      ar: 'بدأ إعلان الرصيف، وتجمّد الجميع',
      fr: 'Annonce en gare. Tout le monde se fige.',
      es: 'Anuncio en el andén. Todos se congelan.',
      ja: 'ホームのアナウンス開始、全員フリーズ',
      ko: '승강장 안내 방송 시작, 모두 얼음',
    },
  },
  {
    emoji: '👥',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'TUR OTOBÜSÜ',
        en: 'TOUR BUS',
        de: 'REISEBUS',
        ar: 'حافلة الرحلات',
        fr: 'CAR DE TOURISME',
        es: 'BUS TURÍSTICO',
        ja: '観光バス',
        ko: '관광버스',
      },
    },
    caption: {
      tr: 'Kıpırdarsan baştan sayar.',
      en: 'Move and he starts over.',
      de: 'Beweg dich, und sie fängt von vorn an.',
      ar: 'إن تحركت، بدأ العدّ من جديد.',
      fr: 'Si tu bouges, il recommence.',
      es: 'Si te mueves, empieza otra vez.',
      ja: '動いたら最初から数え直し。',
      ko: '움직이면 처음부터 다시 세야 해요.',
    },
    headline: {
      tr: 'Rehber kafa sayıyor: 23, 24…',
      en: "The guide's counting heads: 23, 24…",
      de: 'Die Reiseleiterin zählt: 23, 24…',
      ar: 'المرشد يعدّ الركّاب: 23، 24…',
      fr: 'Le guide compte les têtes : 23, 24…',
      es: 'El guía cuenta cabezas: 23, 24…',
      ja: 'ガイドが人数を数えてる：23、24…',
      ko: '가이드가 인원 체크 중: 23, 24…',
    },
  },
  {
    emoji: '👀',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'METRO VAGONU',
        en: 'SUBWAY CAR',
        de: 'U-BAHN-WAGEN',
        ar: 'عربة المترو',
        fr: 'RAME DE MÉTRO',
        es: 'VAGÓN DE METRO',
        ja: '地下鉄の車内',
        ko: '지하철 안',
      },
    },
    caption: {
      tr: 'Bölümün sonu geliyor. Kıpırdama.',
      en: "The chapter's almost over. Stay still.",
      de: 'Das Kapitel ist fast vorbei. Halt still.',
      ar: 'الفصل على وشك الانتهاء. لا تتحرك.',
      fr: 'Le chapitre se termine. Bouge pas.',
      es: 'El capítulo está por terminar. No te muevas.',
      ja: 'もうすぐ章の終わり。じっとして。',
      ko: '곧 챕터가 끝나요. 가만히 있어요.',
    },
    headline: {
      tr: 'Yanındakinin kitabını gizlice okuyorsun',
      en: "You're reading over someone's shoulder",
      de: 'Du liest heimlich im Buch neben dir',
      ar: 'تقرأ خلسةً كتاب الراكب بجانبك',
      fr: 'Tu lis en douce le livre de ton voisin',
      es: 'Lees a escondidas el libro de tu vecino',
      ja: '隣の人の本をこっそり読んでる',
      ko: '옆 사람 책을 몰래 읽는 중',
    },
  },
];
