import { ACCOUNTS } from '../../accounts';
import type { Draft } from '../../types';

/**
 * Work: the office, meetings, e-mails, coworkers, deadlines, working from home, the first day.
 * One theme's posts of every kind, written by one hand so that the
 * thousand-post catalog never tells the same joke twice. Append only: a
 * published post keeps its place.
 */
export const WORK_SKIP: readonly Draft[] = [
  {
    emoji: '🖨️',
    user: ACCOUNTS.office,
    body: { format: 'scene' },
    caption: {
      tr: 'Yazıcı boş. Yine de kâğıt sıkışmış.',
      en: 'No paper in the printer. Still a paper jam.',
      de: 'Kein Papier im Drucker. Trotzdem Papierstau.',
      ar: 'لا ورق في الطابعة… ومع ذلك الورق عالق',
      fr: 'Imprimante vide. Bourrage papier quand même.',
      es: 'Impresora sin papel. Y aun así, papel atascado.',
      ja: 'プリンターに紙がない。なのに紙詰まり。',
      ko: '프린터에 종이 없음. 근데 종이 걸림.',
    },
  },
  {
    emoji: '🎂',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Kimin doğum günü bilmem, pastaya geldim',
      en: "No idea whose birthday it is. I'm here for cake.",
      de: 'Wessen Geburtstag? Keine Ahnung. Ich will nur Kuchen.',
      ar: 'لا أعرف عيد ميلاد مَن… جئت من أجل الكعكة',
      fr: "Je sais pas c'est l'anniv de qui. Je viens pour le gâteau.",
      es: 'No sé de quién es el cumpleaños. Vine por el pastel.',
      ja: '誰の誕生日か知らない。ケーキ目当てで来た。',
      ko: '누구 생일인지 모름. 케이크 먹으러 옴.',
    },
  },
  {
    emoji: '🍱',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Öğle arası 12.30’da. Açlığım 10.30’da.',
      en: 'Lunch break: 12:30. My hunger: 10:30.',
      de: 'Mittagspause um 12:30. Hunger ab 10:30.',
      ar: 'استراحة الغداء في 12:30، وجوعي في 10:30',
      fr: 'Pause déj à 12 h 30. Ma faim, à 10 h 30.',
      es: 'Almuerzo a las 12:30. Mi hambre, a las 10:30.',
      ja: '昼休みは12:30。空腹は10:30。',
      ko: '점심시간 12:30. 내 배꼽시계 10:30.',
    },
  },
  {
    emoji: '💼',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'İlk iş günü: bütün gün şifremi bekledim',
      en: 'First day at work: waited all day for my login',
      de: 'Erster Arbeitstag: 8 Stunden aufs Passwort gewartet',
      ar: 'أول يوم عمل: انتظرت كلمة المرور طوال اليوم',
      fr: 'Premier jour de boulot : 8 h à attendre mon mot de passe',
      es: 'Primer día: ocho horas esperando mi contraseña',
      ja: '初出勤：一日中パスワード待ちだった',
      ko: '첫 출근: 하루 종일 비밀번호만 기다림',
    },
  },
  {
    emoji: '☎️',
    user: ACCOUNTS.office,
    body: { format: 'scene' },
    caption: {
      tr: 'Telefon çaldı. Herkes birbirine baktı.',
      en: 'The phone rang. We all just stared at each other.',
      de: 'Das Telefon klingelt. Alle schauen sich nur an.',
      ar: 'رنّ الهاتف… فنظر بعضنا إلى بعض',
      fr: 'Le téléphone sonne. Tout le monde se regarde.',
      es: 'Sonó el teléfono. Todos nos miramos.',
      ja: '電話が鳴った。全員で顔を見合わせた。',
      ko: '전화가 울렸다. 다들 서로 눈치만 봄.',
    },
  },
  {
    emoji: '🧢',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Yarı zamanlı iş, tam zamanlı yorgunluk',
      en: 'Part-time job, full-time tired',
      de: 'Teilzeitjob, Vollzeit müde',
      ar: 'عمل بدوام جزئي، وتعب بدوام كامل',
      fr: 'Job à mi-temps, fatigue à plein temps',
      es: 'Trabajo a tiempo parcial, cansancio a tiempo completo',
      ja: '仕事はパート、疲れはフルタイム',
      ko: '일은 파트타임, 피곤함은 풀타임',
    },
  },
  {
    emoji: '🎒',
    user: ACCOUNTS.family,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'ilk iş günün nasıl geçti?',
            en: 'how was your first day at work?',
            de: 'wie war dein erster Arbeitstag?',
            ar: 'كيف كان أول يوم لك في العمل؟',
            fr: 'alors, ce premier jour au boulot ?',
            es: '¿qué tal tu primer día de trabajo?',
            ja: '初出勤どうだった？',
            ko: '첫 출근 어땠어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'iyiydi anne',
            en: 'it was good, mom',
            de: 'gut, Mama',
            ar: 'كان جيدًا يا أمي',
            fr: 'bien, maman',
            es: 'bien, mamá',
            ja: 'よかったよ、お母さん',
            ko: '좋았어, 엄마',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'arkadaş edindin mi? beslenmeni yedin mi?',
            en: 'make any friends? eat your snack?',
            de: 'Freunde gefunden? Pausenbrot gegessen?',
            ar: 'هل صادقت أحدًا؟ هل أكلت سندويشك؟',
            fr: "des copains ? t'as mangé ton goûter ?",
            es: '¿hiciste amigos? ¿te comiste la merienda?',
            ja: 'お友だちできた？お弁当食べた？',
            ko: '친구는 사귀었어? 도시락은 다 먹었어?',
          },
        },
      ],
    },
    caption: {
      tr: 'Anneme göre okula başladım',
      en: 'Mom thinks I just started kindergarten',
      de: 'Für Mama war das meine Einschulung',
      ar: 'أمي تظن أنني بدأت المدرسة للتو',
      fr: "Pour ma mère, c'était ma rentrée des classes",
      es: 'Mi mamá cree que empecé la escuela',
      ja: '母の中では、私は入園したらしい',
      ko: '엄마는 내가 유치원 입학한 줄 앎',
    },
  },
  {
    emoji: '🔌',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Bilgi işlem',
        en: 'IT Help Desk',
        de: 'IT-Support',
        ar: 'الدعم الفني',
        fr: 'Support info',
        es: 'Soporte técnico',
        ja: '情シス',
        ko: '전산팀',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'yazıcı yine çalışmıyor 😩',
            en: "the printer's broken again 😩",
            de: 'der Drucker geht schon wieder nicht 😩',
            ar: 'الطابعة لا تعمل مجددًا 😩',
            fr: "l'imprimante marche plus 😩",
            es: 'la impresora no funciona otra vez 😩',
            ja: 'またプリンターが動かない 😩',
            ko: '프린터 또 고장 났어요 😩',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'fişi takılı mı?',
            en: 'is it plugged in?',
            de: 'ist der Stecker drin?',
            ar: 'هل هي موصولة بالكهرباء؟',
            fr: 'elle est branchée ?',
            es: '¿está enchufada?',
            ja: 'コンセント入ってます？',
            ko: '전원 코드 꽂혀 있나요?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bir bakayım…',
            en: 'hold on, let me check…',
            de: 'Moment, ich schau mal…',
            ar: 'لحظة، سأتحقق…',
            fr: 'attends, je regarde…',
            es: 'espera, voy a ver…',
            ja: 'ちょっと見てみます…',
            ko: '잠깐 확인해 볼게요…',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bu konuşma hiç yaşanmadı',
            en: 'this conversation never happened',
            de: 'dieses Gespräch hat nie stattgefunden',
            ar: 'هذه المحادثة لم تحدث أبدًا',
            fr: "cette conversation n'a jamais eu lieu",
            es: 'esta conversación nunca ocurrió',
            ja: 'この会話はなかったことに',
            ko: '이 대화는 없던 걸로 해요',
          },
        },
      ],
    },
    caption: {
      tr: 'Bilgi işlem hep ilk soruda çözer',
      en: 'IT solves everything with the first question',
      de: 'Der IT-Support löst alles mit Frage eins',
      ar: 'الدعم الفني يحل المشكلة من أول سؤال',
      fr: 'Le support règle tout dès la première question',
      es: 'Soporte lo resuelve todo con la primera pregunta',
      ja: '情シスはいつも最初の質問で解決する',
      ko: '전산팀은 늘 첫 질문에서 해결함',
    },
  },
  {
    emoji: '🚨',
    user: ACCOUNTS.office,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ofis grubu',
        en: 'Office group',
        de: 'Büro-Gruppe',
        ar: 'مجموعة المكتب',
        fr: 'Groupe du bureau',
        es: 'Grupo de la oficina',
        ja: '会社のグループ',
        ko: '회사 단톡방',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'ACİL DURUM!!',
            en: 'EMERGENCY!!',
            de: 'NOTFALL!!',
            ar: 'حالة طوارئ!!',
            fr: 'URGENCE !!',
            es: '¡¡EMERGENCIA!!',
            ja: '緊急事態！！',
            ko: '긴급 상황!!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ne oldu??',
            en: 'what happened??',
            de: 'was ist passiert??',
            ar: 'ماذا حدث؟؟',
            fr: 'quoi ??',
            es: '¿¿qué pasó??',
            ja: 'どうした？？',
            ko: '무슨 일인데??',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'kahve makinesi bozuldu',
            en: "the coffee machine's broken",
            de: 'die Kaffeemaschine ist kaputt',
            ar: 'آلة القهوة تعطّلت',
            fr: 'la machine à café est en panne',
            es: 'se rompió la cafetera',
            ja: 'コーヒーマシンが壊れた',
            ko: '커피 머신 고장 남',
          },
        },
      ],
    },
    caption: {
      tr: 'Ofisteki tek gerçek acil durum',
      en: "The office's only real emergency",
      de: 'Der einzig echte Notfall im Büro',
      ar: 'حالة الطوارئ الحقيقية الوحيدة في المكتب',
      fr: 'La seule vraie urgence au bureau',
      es: 'La única emergencia real de la oficina',
      ja: 'オフィスで唯一の本物の緊急事態',
      ko: '사무실의 유일한 진짜 비상 사태',
    },
  },
  {
    emoji: '🍫',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Patron', en: 'Boss', de: 'Chef', ar: 'المدير', fr: 'Patron', es: 'Jefe', ja: '部長', ko: '부장님' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'odama bir uğrar mısın?',
            en: 'can you stop by my office?',
            de: 'kannst du kurz in mein Büro kommen?',
            ar: 'هل يمكنك المرور على مكتبي؟',
            fr: 'tu peux passer dans mon bureau ?',
            es: '¿puedes pasar por mi oficina?',
            ja: 'ちょっと部屋に来てくれる？',
            ko: '잠깐 내 방으로 와 줄래요?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tabii… bir sorun mu var? 😰',
            en: 'sure… is something wrong? 😰',
            de: 'klar… stimmt was nicht? 😰',
            ar: 'طبعًا… هل هناك مشكلة؟ 😰',
            fr: 'bien sûr… il y a un souci ? 😰',
            es: 'claro… ¿pasa algo? 😰',
            ja: 'はい…何かありましたか？ 😰',
            ko: '네… 무슨 문제라도 있나요? 😰',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yok, tatilden çikolata getirdim 🍫',
            en: 'nope, brought you chocolate from my trip 🍫',
            de: 'nein, Schokolade aus dem Urlaub für dich 🍫',
            ar: 'لا، أحضرت لك شوكولاتة من إجازتي 🍫',
            fr: 'non, du chocolat de mes vacances pour toi 🍫',
            es: 'no, te traje chocolate de mis vacaciones 🍫',
            ja: 'いや、旅行のお土産があるんだ 🍫',
            ko: '아니, 여행 기념 초콜릿 줄게요 🍫',
          },
        },
      ],
    },
    caption: {
      tr: 'Bütün kariyerim gözümün önünden geçti',
      en: 'My whole career flashed before my eyes',
      de: 'Meine ganze Karriere lief vor meinen Augen ab',
      ar: 'مرّت مسيرتي المهنية كلها أمام عيني',
      fr: 'Toute ma carrière a défilé devant mes yeux',
      es: 'Toda mi carrera pasó ante mis ojos',
      ja: 'キャリアが走馬灯のように駆け巡った',
      ko: '내 커리어가 주마등처럼 스쳐 지나감',
    },
  },
  {
    emoji: '📥',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Cuma 16.55’te yeni bir iş geldi. Sen:',
        en: 'New task at 4:55 p.m. on a Friday. You:',
        de: 'Freitag, 16:55 Uhr, neue Aufgabe. Du:',
        ar: 'الجمعة 4:55 مساءً، ووصلتك مهمة جديدة. ماذا تفعل؟',
        fr: 'Vendredi, 16 h 55, nouvelle tâche. Toi :',
        es: 'Viernes, 16:55, llega una tarea nueva. Tú:',
        ja: '金曜16:55に新しい仕事が来た。あなたは：',
        ko: '금요일 16:55, 새 업무가 왔다. 당신은:',
      },
      options: [
        {
          tr: 'Hemen başlarım',
          en: 'Start right away',
          de: 'Sofort anfangen',
          ar: 'أبدأ فورًا',
          fr: "Je m'y mets",
          es: 'Empiezo ya',
          ja: 'すぐ始める',
          ko: '바로 시작한다',
        },
        {
          tr: 'Pazartesinin işi',
          en: "That's Monday's job",
          de: 'Ein Montagsproblem',
          ar: 'هذه مهمة يوم الاثنين',
          fr: "C'est pour lundi",
          es: 'Eso es del lunes',
          ja: '月曜の仕事',
          ko: '월요일의 일',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Pazartesiki ben halleder',
      en: 'Monday me will handle it',
      de: 'Das Montags-Ich regelt das',
      ar: 'نسختي يوم الاثنين ستتولى الأمر',
      fr: "Le moi de lundi s'en chargera",
      es: 'El yo del lunes se encarga',
      ja: '月曜の自分がなんとかする',
      ko: '월요일의 내가 알아서 하겠지',
    },
  },
  {
    emoji: '📹',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Görüntülü toplantı başlıyor. Kameran:',
        en: 'The video meeting starts. Your camera:',
        de: 'Der Videocall startet. Deine Kamera:',
        ar: 'بدأ الاجتماع المرئي. كاميرتك:',
        fr: 'La visio commence. Ta caméra :',
        es: 'Empieza la videollamada. Tu cámara:',
        ja: 'ビデオ会議が始まる。カメラは：',
        ko: '화상 회의가 시작된다. 카메라는:',
      },
      options: [
        {
          tr: 'Açık, gülümsüyorum',
          en: 'On, smiling',
          de: 'An, mit Lächeln',
          ar: 'مفتوحة وأنا أبتسم',
          fr: 'Allumée, je souris',
          es: 'Encendida, sonriendo',
          ja: 'オン、笑顔で',
          ko: '켜고 활짝 웃기',
        },
        {
          tr: '“İnternetim çekmiyor”',
          en: '“Bad connection”',
          de: '„Mein WLAN spinnt“',
          ar: '«الإنترنت ضعيف»',
          fr: '« Ma connexion rame »',
          es: '“Mi internet falla”',
          ja: '「回線が不安定で」',
          ko: '“인터넷이 끊겨서”',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'İnternetim sadece toplantıda bozuluyor',
      en: 'My internet only dies during meetings',
      de: 'Mein WLAN spinnt nur in Meetings',
      ar: 'الإنترنت عندي لا يضعف إلا في الاجتماعات',
      fr: "Ma connexion rame qu'en réunion",
      es: 'Mi internet solo falla en las reuniones',
      ja: 'うちのネット、会議のときだけ落ちる',
      ko: '우리 집 인터넷은 회의 때만 끊김',
    },
  },
  {
    emoji: '🫖',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Ofis demliğinde tek yudum kaldı. Sen:',
        en: 'The office coffee pot has one sip left. You:',
        de: 'Kaffeekanne im Büro: noch ein Schluck drin. Du:',
        ar: 'بقيت رشفة واحدة في إبريق المكتب. ماذا تفعل؟',
        fr: 'Il reste une gorgée dans la cafetière. Toi :',
        es: 'Queda un sorbo en la cafetera de la oficina. Tú:',
        ja: '会社のコーヒーポットに残り一口。あなたは：',
        ko: '사무실 커피포트에 딱 한 모금 남음. 당신은:',
      },
      options: [
        {
          tr: 'Yenisini demlerim',
          en: 'Brew a fresh pot',
          de: 'Neuen Kaffee kochen',
          ar: 'أُعدّ إبريقًا جديدًا',
          fr: "J'en refais",
          es: 'Preparo más',
          ja: '新しく淹れる',
          ko: '새로 내린다',
        },
        {
          tr: 'Yudumu bırakırım',
          en: 'Leave the sip',
          de: 'Den Schluck lassen',
          ar: 'أترك الرشفة',
          fr: 'Je laisse la gorgée',
          es: 'Dejo el sorbo',
          ja: '一口残しておく',
          ko: '한 모금 남겨 둔다',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'O yudum pazartesiden beri orada',
      en: "That sip's been there since Monday",
      de: 'Der Schluck steht da seit Montag',
      ar: 'تلك الرشفة هناك منذ يوم الاثنين',
      fr: 'Cette gorgée est là depuis lundi',
      es: 'Ese sorbo está ahí desde el lunes',
      ja: 'その一口、月曜からそこにある',
      ko: '그 한 모금은 월요일부터 거기 있었음',
    },
  },
  {
    emoji: '🚀',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'VERİMLİLİĞİM',
        en: 'MY PRODUCTIVITY',
        de: 'MEINE PRODUKTIVITÄT',
        ar: 'إنتاجيتي',
        fr: 'MA PRODUCTIVITÉ',
        es: 'MI PRODUCTIVIDAD',
        ja: '私の生産性',
        ko: '나의 생산성',
      },
      value: null,
      shape: 'spike',
      axis: 'days',
    },
    caption: {
      tr: 'Teslim tarihinden önceki gece',
      en: 'The night before the deadline',
      de: 'Die Nacht vor der Abgabe',
      ar: 'الليلة التي تسبق موعد التسليم',
      fr: 'La veille de la date limite',
      es: 'La noche antes de la entrega',
      ja: '締め切り前夜',
      ko: '마감 전날 밤',
    },
  },
  {
    emoji: '🌡️',
    user: ACCOUNTS.plain,
    body: {
      format: 'chart',
      title: {
        tr: 'OFİS SICAKLIĞI',
        en: 'OFFICE TEMPERATURE',
        de: 'BÜROTEMPERATUR',
        ar: 'حرارة المكتب',
        fr: 'TEMPÉRATURE DU BUREAU',
        es: 'CLIMA EN LA OFICINA',
        ja: 'オフィスの室温',
        ko: '사무실 온도',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Klima kumandası 14 kez el değiştirdi',
      en: 'The AC remote changed hands 14 times',
      de: 'Die Klima-Fernbedienung ging durch 14 Hände',
      ar: 'تنقّل جهاز تحكم المكيّف بين 14 يدًا',
      fr: 'La télécommande de la clim a changé 14 fois de main',
      es: 'El control del aire pasó por 14 manos',
      ja: 'エアコンのリモコンが14回持ち主を変えた',
      ko: '에어컨 리모컨 주인이 14번 바뀜',
    },
  },
  {
    emoji: '👥',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'TOPLANTI SAYISI',
        en: 'NUMBER OF MEETINGS',
        de: 'ANZAHL DER MEETINGS',
        ar: 'عدد الاجتماعات',
        fr: 'NOMBRE DE RÉUNIONS',
        es: 'NÚMERO DE REUNIONES',
        ja: '会議の数',
        ko: '회의 횟수',
      },
      value: {
        tr: '+%40',
        en: '+40%',
        de: '+40 %',
        ar: '+40%',
        fr: '+40 %',
        es: '+40 %',
        ja: '+40%',
        ko: '+40%',
      },
      shape: 'rise',
      axis: 'months',
    },
    caption: {
      tr: 'Toplantı azaltma toplantısından beri',
      en: 'Ever since the “fewer meetings” meeting',
      de: 'Seit dem Meeting über weniger Meetings',
      ar: 'منذ اجتماع «لنقلّل الاجتماعات»',
      fr: 'Depuis la réunion « moins de réunions »',
      es: 'Desde la reunión para tener menos reuniones',
      ja: '「会議を減らす会議」以来',
      ko: '“회의 줄이기 회의” 이후로',
    },
  },
  {
    emoji: '🏷️',
    user: ACCOUNTS.receipts,
    body: {
      format: 'receipt',
      store: {
        tr: 'KIRTASİYE',
        en: 'OFFICE SUPPLY STORE',
        de: 'SCHREIBWAREN',
        ar: 'مكتبة وقرطاسية',
        fr: 'PAPETERIE',
        es: 'PAPELERÍA',
        ja: '文房具店',
        ko: '문구점',
      },
      items: [
        { tr: 'ZIMBA', en: 'STAPLER', de: 'HEFTER', ar: 'دبّاسة', fr: 'AGRAFEUSE', es: 'ENGRAPADORA', ja: 'ホッチキス', ko: '스테이플러' },
        {
          tr: 'İSİM ETİKETİ',
          en: 'NAME LABELS',
          de: 'NAMENSAUFKLEBER',
          ar: 'ملصقات بالاسم',
          fr: 'ÉTIQUETTES À MON NOM',
          es: 'ETIQUETAS DE NOMBRE',
          ja: '名前シール',
          ko: '이름 스티커',
        },
      ],
    },
    caption: {
      tr: 'Bu sefer zımbam masamdan çıkmayacak',
      en: 'This stapler is NOT leaving my desk again',
      de: 'Dieser Hefter verlässt nie wieder meinen Tisch',
      ar: 'هذه الدبّاسة لن تغادر مكتبي بعد اليوم',
      fr: 'Cette agrafeuse ne quittera plus mon bureau',
      es: 'Esta engrapadora no sale más de mi escritorio',
      ja: '今度こそホッチキスは机から出さない',
      ko: '이번엔 스테이플러 절대 안 빌려줌',
    },
  },
  {
    emoji: '👔',
    user: ACCOUNTS.home,
    body: {
      format: 'receipt',
      store: {
        tr: 'GİYİM MAĞAZASI',
        en: 'CLOTHING STORE',
        de: 'MODEGESCHÄFT',
        ar: 'متجر ملابس',
        fr: 'PRÊT-À-PORTER',
        es: 'TIENDA DE ROPA',
        ja: 'アパレルショップ',
        ko: '옷 가게',
      },
      items: [
        {
          tr: 'RESMİ GÖMLEK',
          en: 'DRESS SHIRT',
          de: 'BUSINESSHEMD',
          ar: 'قميص رسمي',
          fr: 'CHEMISE HABILLÉE',
          es: 'CAMISA FORMAL',
          ja: 'ワイシャツ',
          ko: '정장 셔츠',
        },
        {
          tr: 'PİJAMA ALTI',
          en: 'PAJAMA PANTS',
          de: 'PYJAMAHOSE',
          ar: 'بنطال بيجامة',
          fr: 'BAS DE PYJAMA',
          es: 'PANTALÓN DE PIJAMA',
          ja: 'パジャマのズボン',
          ko: '잠옷 바지',
        },
      ],
    },
    caption: {
      tr: 'Görüntülü toplantı kombinim tamam',
      en: 'Video call outfit: complete',
      de: 'Mein Videocall-Outfit ist komplett',
      ar: 'إطلالتي للاجتماعات المرئية اكتملت',
      fr: 'Ma tenue de visio est complète',
      es: 'Conjunto para videollamadas: listo',
      ja: 'ビデオ会議コーデ、完成',
      ko: '화상 회의 코디 완성',
    },
  },
  {
    emoji: '📨',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'E-POSTA RAPORU',
        en: 'EMAIL REPORT',
        de: 'E-MAIL-BERICHT',
        ar: 'تقرير البريد',
        fr: 'BILAN DES MAILS',
        es: 'INFORME DE CORREO',
        ja: 'メールレポート',
        ko: '이메일 리포트',
      },
      big: { tr: '4', en: '4', de: '4', ar: '4', fr: '4', es: '4', ja: '4', ko: '4' },
      text: {
        tr: 'kez “bir önceki e-postamda belirttiğim gibi” yazdın',
        en: 'times you wrote “as per my last email”',
        de: 'Mal „wie in meiner letzten Mail erwähnt“ geschrieben',
        ar: 'مرات كتبتَ فيها «كما ذكرتُ في رسالتي السابقة»',
        fr: 'fois où tu as écrit « comme indiqué dans mon dernier mail »',
        es: 'veces escribiste “como mencioné en mi último correo”',
        ja: '回「前回のメールでお伝えした通り」と書いた',
        ko: '번 “지난 메일에서 말씀드렸듯이”라고 씀',
      },
    },
    caption: {
      tr: 'Kibar ama çok sinirli',
      en: 'Polite, but furious',
      de: 'Höflich, aber stinksauer',
      ar: 'مهذّب، لكنك غاضب جدًا',
      fr: 'Poli, mais furieux',
      es: 'Educado, pero furioso',
      ja: '丁寧だけど激怒してる',
      ko: '공손하지만 엄청 화남',
    },
  },
  {
    emoji: '🎧',
    user: ACCOUNTS.office,
    body: {
      format: 'fact',
      eyebrow: null,
      big: { tr: '11', en: '11', de: '11', ar: '11', fr: '11', es: '11', ja: '11', ko: '11' },
      text: {
        tr: 'kez “beni duyabiliyor musunuz?” diye sordun',
        en: 'times you asked “can you hear me?”',
        de: 'Mal „Hört ihr mich?“ gefragt',
        ar: 'مرة سألتَ: «هل تسمعونني؟»',
        fr: "fois où tu as demandé « vous m'entendez ? »",
        es: 'veces preguntaste “¿me escuchan?”',
        ja: '回「聞こえてますか？」と聞いた',
        ko: '번 “제 목소리 들리세요?”라고 물음',
      },
    },
    caption: {
      tr: 'Duyuyorlardı. Hep duyuyorlardı.',
      en: 'They could. They always could.',
      de: 'Sie konnten. Die ganze Zeit.',
      ar: 'كانوا يسمعونك. طوال الوقت.',
      fr: "Ils t'entendaient. Depuis le début.",
      es: 'Te escuchaban. Todo el tiempo.',
      ja: '聞こえてた。ずっと聞こえてた。',
      ko: '다 들렸음. 늘 들렸음.',
    },
  },
  {
    emoji: '🙂',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'PAZARTESİ RAPORU',
        en: 'MONDAY REPORT',
        de: 'MONTAGSBERICHT',
        ar: 'تقرير يوم الاثنين',
        fr: 'RAPPORT DU LUNDI',
        es: 'INFORME DEL LUNES',
        ja: '月曜レポート',
        ko: '월요일 리포트',
      },
      big: { tr: '14', en: '14', de: '14', ar: '14', fr: '14', es: '14', ja: '14', ko: '14' },
      text: {
        tr: 'kez “hafta sonun nasıldı?” sorusuna “iyiydi” dedin',
        en: 'times you answered “how was your weekend?” with “good”',
        de: 'Mal auf „Wie war dein Wochenende?“ mit „gut“ geantwortet',
        ar: 'مرة أجبتَ عن «كيف كانت عطلتك؟» بـ«جيدة»',
        fr: 'fois où tu as répondu « bien » à « ton week-end ? »',
        es: 'veces respondiste “bien” a “¿qué tal tu fin de semana?”',
        ja: '回「週末どうだった？」に「よかった」と答えた',
        ko: '번 “주말 잘 보냈어요?”에 “네”라고 답함',
      },
    },
    caption: {
      tr: 'Kimse detay istemedi zaten',
      en: 'Nobody wanted details anyway',
      de: 'Details wollte eh keiner',
      ar: 'لم يطلب أحد التفاصيل أصلًا',
      fr: 'Personne voulait de détails, de toute façon',
      es: 'Total, nadie quería detalles',
      ja: 'どうせ誰も詳しく聞きたくない',
      ko: '어차피 아무도 자세히 안 궁금해함',
    },
  },
  {
    emoji: '🗄️',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'OFİS EŞYALARI TIER LIST',
        en: 'OFFICE GEAR TIER LIST',
        de: 'BÜRO-RANKING',
        ar: 'تصنيف أدوات المكتب',
        fr: 'TIER LIST DU BUREAU',
        es: 'TIER LIST DE LA OFICINA',
        ja: 'オフィス用品Tier表',
        ko: '사무용품 티어표',
      },
      rows: [['☕️'], ['💻', '🖱️'], ['📎', '📌'], ['🖨️']],
    },
    caption: {
      tr: 'Yazıcı C, çünkü o da beni sevmiyor',
      en: "Printer's C tier. The feeling's mutual.",
      de: 'Drucker: C. Beruht auf Gegenseitigkeit.',
      ar: 'الطابعة في الأخير، والشعور متبادل',
      fr: "L'imprimante en C. C'est réciproque.",
      es: 'La impresora, en la C. Es mutuo.',
      ja: 'プリンターはC。向こうも私を嫌ってるし',
      ko: '프린터는 C. 걔도 나 싫어하니까',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.home,
    body: {
      format: 'tier',
      title: {
        tr: 'EVDEN ÇALIŞMA TIER LIST',
        en: 'WORK-FROM-HOME TIER LIST',
        de: 'HOMEOFFICE-RANKING',
        ar: 'تصنيف أماكن العمل من المنزل',
        fr: 'TIER LIST DU TÉLÉTRAVAIL',
        es: 'TIER LIST DEL TELETRABAJO',
        ja: '在宅勤務Tier表',
        ko: '재택근무 티어표',
      },
      rows: [['🛏️'], ['🛋️'], ['🍽️'], ['🪑']],
    },
    caption: {
      tr: 'Masaya sadece kamera açılınca oturuyorum',
      en: "I only sit at the desk when the camera's on",
      de: 'Am Schreibtisch sitz ich nur, wenn die Kamera an ist',
      ar: 'لا أجلس إلى المكتب إلا حين تُفتح الكاميرا',
      fr: "Je m'assois au bureau que quand la caméra tourne",
      es: 'Uso el escritorio solo con la cámara encendida',
      ja: '机に座るのはカメラをオンにする時だけ',
      ko: '책상엔 카메라 켤 때만 앉음',
    },
  },
  {
    emoji: '🧵',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '📩',
        app: { tr: 'E-posta', en: 'Mail', de: 'E-Mail', ar: 'البريد', fr: 'Mail', es: 'Correo', ja: 'メール', ko: '메일' },
        text: {
          tr: 'Konu: Re: Re: Fwd: Re: Re: Re: Plan',
          en: 'Subject: Re: Re: Fwd: Re: Re: Re: Plan',
          de: 'Betreff: AW: AW: WG: AW: AW: AW: Plan',
          ar: 'الموضوع: رد: رد: توجيه: رد: رد: الخطة',
          fr: 'Objet : RE : RE : TR : RE : Plan',
          es: 'Asunto: RE: RE: RV: RE: RE: RE: Plan',
          ja: '件名：Re: Re: Fwd: Re: Re: Re: 計画',
          ko: '제목: Re: Re: Fwd: Re: Re: Re: 계획',
        },
      },
    },
    caption: {
      tr: 'Plan neydi, artık kimse bilmiyor',
      en: 'Nobody remembers what the plan was',
      de: 'Was der Plan war, weiß keiner mehr',
      ar: 'لم يعد أحد يتذكر ما كانت الخطة',
      fr: 'Plus personne ne sait quel était le plan',
      es: 'Ya nadie recuerda cuál era el plan',
      ja: '何の計画だったか、もう誰も覚えてない',
      ko: '무슨 계획이었는지 이제 아무도 모름',
    },
  },
  {
    emoji: '🏝️',
    user: ACCOUNTS.office,
    body: {
      format: 'notifications',
      first: {
        icon: '🌴',
        app: {
          tr: 'Otomatik yanıt',
          en: 'Auto-reply',
          de: 'Abwesenheitsnotiz',
          ar: 'رد تلقائي',
          fr: 'Réponse auto',
          es: 'Autorespuesta',
          ja: '自動返信',
          ko: '자동 응답',
        },
        text: {
          tr: 'İzindeyim. Dönünce de pek bakmam.',
          en: "I'm away. Won't read this later, either.",
          de: "Im Urlaub. Danach les ich's auch nicht.",
          ar: 'في إجازة. ولن أقرأها بعد عودتي أيضًا.',
          fr: 'En congé. Et je lirai pas au retour.',
          es: 'Estoy fuera. Al volver tampoco lo leeré.',
          ja: '休暇中です。戻っても読みません。',
          ko: '휴가 중이에요. 복귀해도 안 읽어요.',
        },
      },
    },
    caption: {
      tr: 'Yılın en dürüst otomatik yanıtı',
      en: 'The most honest auto-reply of the year',
      de: 'Die ehrlichste Abwesenheitsnotiz des Jahres',
      ar: 'أصدق رد تلقائي هذا العام',
      fr: "La réponse auto la plus honnête de l'année",
      es: 'La autorespuesta más honesta del año',
      ja: '今年いちばん正直な自動返信',
      ko: '올해 가장 솔직한 자동 응답',
    },
  },
  {
    emoji: '🥣',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🎥',
        app: {
          tr: 'Görüntülü toplantı',
          en: 'Video call',
          de: 'Videocall',
          ar: 'اجتماع مرئي',
          fr: 'Visio',
          es: 'Videollamada',
          ja: 'ビデオ会議',
          ko: '화상 회의',
        },
        text: {
          tr: 'Kameran 20 dakikadır açık',
          en: 'Your camera has been on for 20 minutes',
          de: 'Deine Kamera ist seit 20 Minuten an',
          ar: 'كاميرتك مفتوحة منذ 20 دقيقة',
          fr: 'Ta caméra est allumée depuis 20 min',
          es: 'Tu cámara lleva 20 minutos encendida',
          ja: 'カメラが20分前からオンです',
          ko: '카메라가 20분째 켜져 있어요',
        },
      },
    },
    caption: {
      tr: 'Kahvaltımı 12 kişi izledi',
      en: '12 people watched me eat breakfast',
      de: '12 Leute haben mir beim Frühstück zugeschaut',
      ar: 'شاهدني 12 شخصًا وأنا أتناول الفطور',
      fr: "12 personnes m'ont regardé petit-déjeuner",
      es: '12 personas me vieron desayunar',
      ja: '朝ごはんを12人に見られた',
      ko: '12명이 내 아침 식사를 지켜봄',
    },
  },
  {
    emoji: '📅',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bu toplantı bir e-posta olabilirdi. O e-posta da hiç olmayabilirdi.',
        en: "This meeting could've been an email. That email could've been nothing.",
        de: 'Das Meeting hätte eine Mail sein können. Und die Mail? Gar nichts.',
        ar: 'كان يمكن لهذا الاجتماع أن يكون رسالة، وللرسالة ألّا تكون أصلًا.',
        fr: 'Cette réunion aurait pu être un mail. Et ce mail, rien du tout.',
        es: 'Esta reunión pudo ser un correo. Y ese correo, nada.',
        ja: 'この会議はメールで済んだ。そのメールすら要らなかった。',
        ko: '이 회의는 메일로 충분했다. 그 메일조차 필요 없었다.',
      },
    },
    caption: {
      tr: 'Toplantı yine de 1 saat sürdü',
      en: 'The meeting still took an hour',
      de: 'Das Meeting ging trotzdem eine Stunde',
      ar: 'ومع ذلك استمر الاجتماع ساعة كاملة',
      fr: 'La réunion a quand même duré une heure',
      es: 'Aun así, la reunión duró una hora',
      ja: 'それでも会議は1時間続いた',
      ko: '그래도 회의는 1시간 걸림',
    },
  },
  {
    emoji: '😐',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Pazartesiyi sev. — Hiç pazartesi yaşamamış biri',
        en: "Love your Mondays. — Someone who's never had one",
        de: 'Liebe deine Montage. — Jemand, der nie einen hatte',
        ar: 'أحِبّ أيام الاثنين. — شخص لم يعِش يوم اثنين قط',
        fr: "Aime tes lundis. — Quelqu'un qui n'en a jamais eu",
        es: 'Ama tus lunes. — Alguien que nunca tuvo uno',
        ja: '月曜日を愛そう。— 月曜を知らない誰か',
        ko: '월요일을 사랑하라. — 월요일을 겪어 본 적 없는 사람',
      },
    },
    caption: {
      tr: 'Bunu yazan kesin cumartesi yazmış',
      en: 'Pretty sure this was written on a Saturday',
      de: 'Das wurde garantiert an einem Samstag geschrieben',
      ar: 'أنا متأكد أنها كُتبت يوم سبت',
      fr: "C'est sûrement écrit un samedi",
      es: 'Seguro que lo escribieron un sábado',
      ja: 'これ絶対土曜日に書いたでしょ',
      ko: '이거 분명 토요일에 썼을 거임',
    },
  },
  {
    emoji: '💾',
    user: ACCOUNTS.office,
    body: {
      format: 'quote',
      text: {
        tr: 'Hiçbir şey son değildir. — sunum_son_SON_bu_kesin',
        en: 'Nothing is ever final. — presentation_final_FINAL_v3',
        de: 'Nichts ist je endgültig. — Präsentation_final_FINAL_v3',
        ar: 'لا شيء نهائي أبدًا. — العرض_النهائي_النهائي_3',
        fr: "Rien n'est jamais définitif. — présentation_finale_FINALE_v3",
        es: 'Nada es definitivo. — presentación_final_FINAL_v3',
        ja: '最終版なんて存在しない。— 企画書_最終_本当に最終_v3',
        ko: '끝이란 없다. — 발표_최종_진짜최종_진짜진짜최종',
      },
    },
    caption: {
      tr: 'Masaüstünde 14 tane daha var',
      en: 'There are 14 more on my desktop',
      de: 'Auf dem Desktop liegen noch 14 davon',
      ar: 'وعلى سطح المكتب 14 نسخة أخرى',
      fr: 'Il y en a 14 autres sur mon bureau',
      es: 'Hay 14 más en mi escritorio',
      ja: 'デスクトップにあと14個ある',
      ko: '바탕화면에 14개 더 있음',
    },
  },
  {
    emoji: '📋',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayallerinin peşinden koş. Ama önce şu tabloyu doldur.',
        en: 'Follow your dreams. But first, fill in this spreadsheet.',
        de: 'Folge deinen Träumen. Aber erst diese Tabelle ausfüllen.',
        ar: 'اتبع أحلامك. لكن املأ هذا الجدول أولًا.',
        fr: "Suis tes rêves. Mais d'abord, remplis ce tableau.",
        es: 'Persigue tus sueños. Pero primero, completa esta tabla.',
        ja: '夢を追いかけよう。でもまず、この表を埋めて。',
        ko: '꿈을 좇아라. 하지만 먼저 이 엑셀부터 채워라.',
      },
    },
    caption: {
      tr: 'Tablonun bir de ikinci sayfası varmış',
      en: "Turns out there's a second tab",
      de: 'Die Tabelle hat noch ein zweites Blatt',
      ar: 'واتضح أن للجدول صفحة ثانية',
      fr: 'Et le tableau a un deuxième onglet',
      es: 'Y la tabla tiene una segunda hoja',
      ja: '表には2枚目のシートもあった',
      ko: '알고 보니 시트가 하나 더 있었음',
    },
  },
  {
    emoji: '📽️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Her başarılı sunumun arkasında ters takılmış 3 kablo vardır.',
        en: 'Behind every great presentation are 3 cables plugged in wrong.',
        de: 'Hinter jeder guten Präsentation stecken 3 falsch eingesteckte Kabel.',
        ar: 'خلف كل عرض تقديمي ناجح 3 كابلات موصولة بالخطأ.',
        fr: 'Derrière chaque belle présentation, 3 câbles mal branchés.',
        es: 'Detrás de cada gran presentación hay 3 cables mal conectados.',
        ja: '成功したプレゼンの裏には、逆に挿したケーブルが3本ある。',
        ko: '모든 성공한 발표 뒤에는 거꾸로 꽂은 케이블 3개가 있다.',
      },
    },
    caption: {
      tr: 'Sonra bir adaptör daha lazım oldu',
      en: 'Then we needed another adapter',
      de: 'Dann fehlte noch ein Adapter',
      ar: 'ثم احتجنا إلى محوّل آخر',
      fr: 'Puis il a fallu un autre adaptateur',
      es: 'Luego hizo falta otro adaptador',
      ja: 'そのあとアダプターがもう一個必要になった',
      ko: '그다음엔 어댑터가 하나 더 필요했음',
    },
  },
];

export const WORK_LIKE: readonly Draft[] = [
  {
    emoji: '🎉',
    user: ACCOUNTS.tolga,
    body: { format: 'scene' },
    caption: {
      tr: 'terfi aldım!! yeni unvanımı 40 kez okudum',
      en: 'got promoted!! read my new title 40 times',
      de: 'befördert!! hab meinen neuen titel 40-mal gelesen',
      ar: 'حصلت على ترقية!! وقرأت مسمّاي الوظيفي الجديد 40 مرة',
      fr: "promu !! j'ai relu mon nouveau titre 40 fois",
      es: '¡¡me ascendieron!! leí mi nuevo cargo 40 veces',
      ja: '昇進した！！新しい肩書きを40回読んだ',
      ko: '승진했다!! 새 직함 40번 읽음',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.irem,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk sunumum bitti, sesim sadece 2 kez titredi',
      en: 'gave my first presentation, voice only shook twice',
      de: 'meine erste präsentation! stimme hat nur 2-mal gezittert',
      ar: 'قدّمت أول عرض لي، وارتجف صوتي مرتين فقط',
      fr: 'ma première présentation, ma voix a tremblé que 2 fois',
      es: 'primera presentación: la voz solo me tembló 2 veces',
      ja: '初プレゼン終了、声が震えたのは2回だけ',
      ko: '첫 발표 끝, 목소리 떨린 건 2번뿐',
    },
  },
  {
    emoji: '🏁',
    user: ACCOUNTS.kaan,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk projemizi teslim ettik, ekibim harika',
      en: 'we shipped our first project, my team rocks',
      de: 'erstes projekt abgegeben, mein team ist der hammer',
      ar: 'سلّمنا أول مشروع لنا، فريقي رائع',
      fr: 'premier projet livré, mon équipe est géniale',
      es: 'primer proyecto entregado, mi equipo es lo máximo',
      ja: '初プロジェクト納品、うちのチーム最高',
      ko: '첫 프로젝트 납품 완료, 우리 팀 최고',
    },
  },
  {
    emoji: '🪴',
    user: ACCOUNTS.melis,
    body: {
      format: 'polaroid',
      note: {
        tr: 'masamın yeni üyesi',
        en: 'newest team member',
        de: 'neues teammitglied',
        ar: 'العضو الجديد في مكتبي',
        fr: 'nouvelle collègue',
        es: 'nueva compañera',
        ja: 'デスクの新メンバー',
        ko: '내 책상의 새 멤버',
      },
    },
    caption: {
      tr: 'bitkimin adı cuma, ofiste herkes seviyor',
      en: "my desk plant's name is friday. everyone loves her",
      de: 'meine büropflanze heißt freitag. alle lieben sie',
      ar: 'نبتة مكتبي اسمها «الجمعة»، والجميع يحبها',
      fr: "ma plante au bureau s'appelle vendredi, tous l'adorent",
      es: 'mi planta de la oficina se llama viernes. todos la aman',
      ja: '観葉植物の名前は金曜日。社内で大人気',
      ko: '내 화분 이름은 금요일. 사무실 인기 스타',
    },
  },
  {
    emoji: '🏅',
    user: ACCOUNTS.onur,
    body: {
      format: 'polaroid',
      note: {
        tr: 'duvardaki ben',
        en: 'me, on the wall',
        de: 'ich, an der wand',
        ar: 'أنا، على الحائط',
        fr: 'moi, au mur',
        es: 'yo, en la pared',
        ja: '壁に飾られた私',
        ko: '벽에 걸린 나',
      },
    },
    caption: {
      tr: 'ayın çalışanı oldum, annem çerçeveletiyor',
      en: "employee of the month! mom's getting it framed",
      de: 'mitarbeiter des monats! mama lässt es rahmen',
      ar: 'صرت موظف الشهر، وأمي ستؤطّر الصورة',
      fr: 'employé du mois ! ma mère va le faire encadrer',
      es: '¡empleado del mes! mi mamá lo va a enmarcar',
      ja: '今月の社員に選ばれた。母が額に入れるって',
      ko: '이달의 사원 됨, 엄마가 액자 맞추는 중',
    },
  },
  {
    emoji: '☕️',
    user: ACCOUNTS.naz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk kalbim',
        en: 'my first heart',
        de: 'mein erstes herz',
        ar: 'أول قلب أرسمه',
        fr: 'mon premier cœur',
        es: 'mi primer corazón',
        ja: 'はじめてのハート',
        ko: '나의 첫 하트',
      },
    },
    caption: {
      tr: 'kafede 2. haftam, kalp yaptım (sayılır)',
      en: 'week 2 at the café job, made a heart (kind of)',
      de: 'woche 2 im café-job, ein herz geschafft (fast)',
      ar: 'أسبوعي الثاني في المقهى، رسمت قلبًا (تقريبًا)',
      fr: "2e semaine au café, j'ai fait un cœur (presque)",
      es: 'segunda semana en la cafetería, hice un corazón (casi)',
      ja: 'カフェバイト2週目、ハート描けた（たぶん）',
      ko: '카페 알바 2주 차, 하트 성공 (거의)',
    },
  },
  {
    emoji: '👔',
    user: ACCOUNTS.efe,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk iş günü',
        en: 'first day at work',
        de: 'erster arbeitstag',
        ar: 'أول يوم عمل',
        fr: 'premier jour de boulot',
        es: 'primer día de trabajo',
        ja: '初出勤',
        ko: '첫 출근',
      },
    },
    caption: {
      tr: 'kravatı babam bağladı, ben hâlâ bilmiyorum',
      en: "dad tied my tie. i still don't know how",
      de: "papa hat die krawatte gebunden. ich kann's nicht",
      ar: 'أبي ربط لي ربطة العنق، وما زلت لا أعرف كيف',
      fr: "papa m'a fait mon nœud de cravate, je sais toujours pas",
      es: 'mi papá me hizo el nudo de la corbata, sigo sin saber',
      ja: 'ネクタイは父が結んだ。自分はまだ結べない',
      ko: '넥타이는 아빠가 매 줌. 난 아직도 못 맴',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.arda,
    body: { format: 'dump', emojis: ['🧺', '🥪', '🪢', '🏐', '☀️'] },
    caption: {
      tr: 'şirket pikniği dump’ı: halat çekmeyi muhasebe kazandı',
      en: 'company picnic dump: accounting won tug-of-war',
      de: 'firmenpicknick: die buchhaltung hat tauziehen gewonnen',
      ar: 'نزهة الشركة: قسم المحاسبة فاز بشدّ الحبل',
      fr: 'pique-nique du boulot : la compta a gagné au tir à la corde',
      es: 'picnic de la empresa: contabilidad ganó el tira y afloja',
      ja: '社内ピクニックまとめ：綱引きは経理部の勝ち',
      ko: '회사 야유회 모음: 줄다리기 우승은 회계팀',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.yagmur,
    body: { format: 'dump', emojis: ['💻', '🧦', '🍜', '🛋️', '📦'] },
    caption: {
      tr: 'evden çalışma dump’ı: 5 gündür ayakkabı görmedim',
      en: "wfh week dump: haven't seen shoes in 5 days",
      de: 'homeoffice-woche: seit 5 tagen keine schuhe gesehen',
      ar: 'أسبوع العمل من المنزل: 5 أيام لم أرَ فيها حذاءً',
      fr: 'semaine en télétravail : 5 jours sans voir mes chaussures',
      es: 'semana de teletrabajo: 5 días sin ver mis zapatos',
      ja: '在宅勤務まとめ：5日間くつを見てない',
      ko: '재택근무 모음: 5일째 신발 구경도 못 함',
    },
  },
  {
    emoji: '💌',
    user: ACCOUNTS.defne,
    body: { format: 'dump', emojis: ['💌', '🎈', '📸', '🍰', '🤗'] },
    caption: {
      tr: 'stajın son günü: ekip kart yazdı, ağlamadım (ağladım)',
      en: "last day of my internship: team card, didn't cry (i did)",
      de: 'letzter praktikumstag: karte vom team, nicht geweint (doch)',
      ar: 'آخر يوم في التدريب: الفريق كتب لي بطاقة، لم أبكِ (بكيت)',
      fr: "fin de stage : une carte de l'équipe, pas pleuré (si)",
      es: 'fin de las prácticas: tarjeta del equipo, no lloré (sí)',
      ja: 'インターン最終日：寄せ書きもらった。泣いてない（泣いた）',
      ko: '인턴 마지막 날: 팀이 카드 써 줌. 안 울었음 (울었음)',
    },
  },
];

export const WORK_HOLD: readonly Draft[] = [
  {
    emoji: '🗓️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Toplantı iptal! Bütün öğleden sonra senin',
      en: 'Meeting canceled! The whole afternoon is yours',
      de: 'Meeting abgesagt! Der ganze Nachmittag gehört dir',
      ar: 'أُلغي الاجتماع! فترة ما بعد الظهر كلها لك',
      fr: "Réunion annulée ! Tout l'après-midi est à toi",
      es: '¡Reunión cancelada! Toda la tarde es tuya',
      ja: '会議が中止！午後はまるごと自由',
      ko: '회의 취소! 오후는 통째로 자유',
    },
  },
  {
    emoji: '📭',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Gelen kutusu: 0. Kimse buna inanmayacak.',
      en: "Inbox: 0. Nobody's going to believe this.",
      de: 'Posteingang: 0. Das glaubt dir keiner.',
      ar: 'صندوق الوارد: 0. لن يصدّق أحد ذلك.',
      fr: 'Boîte de réception : 0. Personne va te croire.',
      es: 'Bandeja de entrada: 0. Nadie te lo va a creer.',
      ja: '受信トレイ：0件。誰も信じてくれないはず。',
      ko: '받은편지함: 0. 아무도 안 믿을 듯.',
    },
  },
  {
    emoji: '🕔',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Cuma 16.59. Tam 17.00’de bırak.',
      en: 'Friday, 4:59 p.m. Let go at 5 sharp.',
      de: 'Freitag, 16:59 Uhr. Lass um Punkt 17 los.',
      ar: 'الجمعة، 4:59 مساءً. اترك في الخامسة تمامًا.',
      fr: 'Vendredi, 16 h 59. Lâche à 17 h pile.',
      es: 'Viernes, 16:59. Suelta a las 17:00 en punto.',
      ja: '金曜16:59。17:00ちょうどに離して。',
      ko: '금요일 16:59. 17:00 정각에 손 떼기.',
    },
  },
  {
    emoji: '🏖️',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'İzin onaylandı. Üstelik köprü günüyle!',
      en: 'Time off approved. Long weekend unlocked!',
      de: 'Urlaub genehmigt. Mit Brückentag!',
      ar: 'تمت الموافقة على إجازتك، ومعها عطلة طويلة!',
      fr: 'Congé validé. Avec le pont en prime !',
      es: 'Vacaciones aprobadas. ¡Con puente incluido!',
      ja: '休暇が承認された。しかも連休に！',
      ko: '휴가 승인. 게다가 연휴 확정!',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir buluntu: gıcırdamayan ofis sandalyesi',
      en: "Rare find: an office chair that doesn't squeak",
      de: 'Seltener Fund: ein Bürostuhl, der nicht quietscht',
      ar: 'اكتشاف نادر: كرسي مكتب لا يُصدر صريرًا',
      fr: 'Trouvaille rare : une chaise de bureau qui grince pas',
      es: 'Hallazgo raro: una silla de oficina que no rechina',
      ja: 'レア発見：きしまないオフィスチェア',
      ko: '희귀템 발견: 삐걱대지 않는 사무실 의자',
    },
  },
  {
    emoji: '🪟',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Pencere kenarındaki masa boşaldı. Senin!',
      en: "The window desk just opened up. It's yours!",
      de: 'Der Platz am Fenster ist frei. Er gehört dir!',
      ar: 'المكتب بجانب النافذة صار شاغرًا… وهو لك!',
      fr: 'Le bureau près de la fenêtre est libre. Pour toi !',
      es: 'Se liberó el escritorio junto a la ventana. ¡Es tuyo!',
      ja: '窓側の席が空いた。あなたの席だ！',
      ko: '창가 자리가 비었다. 이제 당신 자리!',
    },
  },
  {
    emoji: '🥡',
    user: ACCOUNTS.lucky,
    body: { format: 'treasure' },
    caption: {
      tr: 'Mucize: buzdolabındaki yemeğin hâlâ orada',
      en: 'Miracle: your lunch is still in the office fridge',
      de: 'Wunder: Dein Essen ist noch im Bürokühlschrank',
      ar: 'معجزة: غداؤك ما زال في ثلاجة المكتب',
      fr: 'Miracle : ton déj est encore dans le frigo du bureau',
      es: 'Milagro: tu almuerzo sigue en el refrigerador',
      ja: '奇跡：冷蔵庫のお弁当がまだある',
      ko: '기적: 냉장고에 둔 도시락이 아직 있음',
    },
  },
];

export const WORK_FREEZE: readonly Draft[] = [
  {
    emoji: '🖥️',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'CANLI YAYIN',
        en: 'ON AIR',
        de: 'AUF SENDUNG',
        ar: 'على الهواء',
        fr: 'EN DIRECT',
        es: 'EN VIVO',
        ja: '生配信中',
        ko: '생방송',
      },
      small: {
        tr: 'HER ŞEYİ GÖRÜYORLAR',
        en: 'THEY SEE EVERYTHING',
        de: 'ALLE SEHEN ALLES',
        ar: 'الجميع يرى كل شيء',
        fr: 'ILS VOIENT TOUT',
        es: 'LO VEN TODO',
        ja: '全部見られてる',
        ko: '다 보고 있음',
      },
    },
    caption: {
      tr: 'Hiçbir sekmeye tıklama.',
      en: "Don't click a single tab.",
      de: 'Klick bloß keinen Tab an.',
      ar: 'لا تضغط على أي تبويب.',
      fr: 'Clique sur aucun onglet.',
      es: 'No hagas clic en ninguna pestaña.',
      ja: 'タブは一つもクリックしないで。',
      ko: '탭 하나도 누르지 마세요.',
    },
    headline: {
      tr: 'Ekranını 40 kişiyle paylaşıyorsun',
      en: 'Your screen is shared with 40 people',
      de: '40 Leute sehen deinen Bildschirm',
      ar: 'أنت تشارك شاشتك مع 40 شخصًا',
      fr: 'Ton écran est partagé avec 40 personnes',
      es: 'Compartes pantalla con 40 personas',
      ja: '画面を40人に共有中',
      ko: '40명에게 화면 공유 중',
    },
  },
  {
    emoji: '📄',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'ELLEMEYİN',
        en: 'HANDS OFF',
        de: 'FINGER WEG',
        ar: 'لا تلمسوها',
        fr: 'PAS TOUCHE',
        es: 'NO LA TOQUEN',
        ja: 'さわるな',
        ko: '손대지 마시오',
      },
      small: {
        tr: 'YAZICI SONUNDA ÇALIŞIYOR',
        en: 'THE PRINTER FINALLY WORKS',
        de: 'DER DRUCKER GEHT ENDLICH',
        ar: 'الطابعة تعمل أخيرًا',
        fr: "L'IMPRIMANTE MARCHE ENFIN",
        es: 'LA IMPRESORA POR FIN FUNCIONA',
        ja: 'プリンターがやっと動いた',
        ko: '프린터 드디어 작동 중',
      },
    },
    caption: {
      tr: 'Sakın hapşırma.',
      en: "Don't you dare sneeze.",
      de: 'Bloß nicht niesen.',
      ar: 'إياك أن تعطس.',
      fr: 'Surtout, éternue pas.',
      es: 'Ni se te ocurra estornudar.',
      ja: 'くしゃみ厳禁。',
      ko: '재채기 절대 금지.',
    },
    headline: {
      tr: 'Çıktın geliyor: sayfa 1/40',
      en: 'Printing now: page 1 of 40',
      de: 'Es druckt: Seite 1 von 40',
      ar: 'جارٍ الطباعة: الصفحة 1 من 40',
      fr: 'Impression : page 1 sur 40',
      es: 'Imprimiendo: página 1 de 40',
      ja: '印刷中：1/40ページ',
      ko: '인쇄 중: 1/40쪽',
    },
  },
  {
    emoji: '🗂️',
    user: ACCOUNTS.alert,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'CAUTION',
        de: 'ACHTUNG',
        ar: 'انتبه',
        fr: 'ATTENTION',
        es: 'CUIDADO',
        ja: '注意',
        ko: '주의',
      },
      small: {
        tr: 'EVRAK KULESİ SALLANIYOR',
        en: 'PAPER TOWER WOBBLING',
        de: 'AKTENTURM WACKELT',
        ar: 'برج الأوراق يتمايل',
        fr: 'LA PILE DE DOSSIERS VACILLE',
        es: 'TORRE DE PAPELES INESTABLE',
        ja: '書類の塔がグラグラ',
        ko: '서류 탑 흔들리는 중',
      },
    },
    caption: {
      tr: 'Nefes alırsan devrilir.',
      en: 'Breathe and it falls.',
      de: 'Ein Atemzug, und er kippt.',
      ar: 'إن تنفّست سقطت.',
      fr: 'Respire et tout tombe.',
      es: 'Si respiras, se cae.',
      ja: '息をしたら崩れる。',
      ko: '숨 쉬면 무너져요.',
    },
    headline: {
      tr: 'Masandaki dosya yığını devrilmek üzere',
      en: "Your desk's file pile is about to tip",
      de: 'Der Aktenstapel kippt gleich um',
      ar: 'كومة الملفات على مكتبك على وشك السقوط',
      fr: "La pile de dossiers va s'effondrer",
      es: 'La pila de carpetas está a punto de caer',
      ja: '机の書類の山が崩れそう',
      ko: '책상 위 서류 더미가 무너지기 직전',
    },
  },
  {
    emoji: '🙋',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'TOPLANTI ODASI',
        en: 'MEETING ROOM',
        de: 'BESPRECHUNGSRAUM',
        ar: 'غرفة الاجتماعات',
        fr: 'SALLE DE RÉUNION',
        es: 'SALA DE REUNIONES',
        ja: '会議室',
        ko: '회의실',
      },
    },
    caption: {
      tr: 'Kimse kıpırdamasın, toplantı bitiyor.',
      en: "Nobody move and it's over.",
      de: 'Keiner rührt sich, dann ist Schluss.',
      ar: 'لا يتحرك أحد، وسينتهي الاجتماع.',
      fr: "Personne bouge, et c'est fini.",
      es: 'Que nadie se mueva y se acaba.',
      ja: '誰も動かなければ会議は終わる。',
      ko: '아무도 안 움직이면 회의 끝나요.',
    },
    headline: {
      tr: 'Son slayt: “Soru var mı?”',
      en: 'Last slide: “Any questions?”',
      de: 'Letzte Folie: „Noch Fragen?“',
      ar: 'الشريحة الأخيرة: «هل من أسئلة؟»',
      fr: 'Dernière diapo : « Des questions ? »',
      es: 'Última diapositiva: “¿Alguna pregunta?”',
      ja: '最後のスライド：「質問は？」',
      ko: '마지막 슬라이드: “질문 있나요?”',
    },
  },
  {
    emoji: '🛗',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'ASANSÖR',
        en: 'ELEVATOR',
        de: 'AUFZUG',
        ar: 'المصعد',
        fr: 'ASCENSEUR',
        es: 'ASCENSOR',
        ja: 'エレベーター',
        ko: '엘리베이터',
      },
    },
    caption: {
      tr: 'Sadece kat numaralarına bak.',
      en: 'Just watch the floor numbers.',
      de: 'Schau nur auf die Stockwerksanzeige.',
      ar: 'انظر إلى أرقام الطوابق فقط.',
      fr: "Regarde juste les numéros d'étage.",
      es: 'Mira solo los números de los pisos.',
      ja: '階数表示だけ見つめて。',
      ko: '층수 표시만 보세요.',
    },
    headline: {
      tr: 'Asansöre genel müdür bindi',
      en: 'The CEO just stepped into the elevator',
      de: 'Die Chefin steigt in den Aufzug',
      ar: 'المدير العام دخل المصعد للتو',
      fr: "Le PDG vient d'entrer dans l'ascenseur",
      es: 'La directora acaba de subir al ascensor',
      ja: 'エレベーターに社長が乗ってきた',
      ko: '엘리베이터에 사장님이 탔다',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.alert,
    body: {
      format: 'cctv',
      place: {
        tr: 'EV OFİSİ',
        en: 'HOME OFFICE',
        de: 'HOMEOFFICE',
        ar: 'المكتب المنزلي',
        fr: 'BUREAU À LA MAISON',
        es: 'OFICINA EN CASA',
        ja: '自宅の仕事部屋',
        ko: '홈 오피스',
      },
    },
    caption: {
      tr: 'İnandırıcı ol. Gözünü kırpma.',
      en: "Sell it. Don't blink.",
      de: 'Überzeugend bleiben. Nicht blinzeln.',
      ar: 'كن مقنعًا. لا ترمش.',
      fr: 'Sois crédible. Cligne pas des yeux.',
      es: 'Que sea creíble. No parpadees.',
      ja: '本気で演じて。まばたき禁止。',
      ko: '진짜처럼. 눈도 깜빡이지 마세요.',
    },
    headline: {
      tr: 'Toplantıda donmuş taklidi yapıyorsun',
      en: 'Faking a frozen video in the meeting',
      de: 'Du spielst im Meeting ein Standbild',
      ar: 'تتظاهر بأن صورتك متجمّدة في الاجتماع',
      fr: "Tu fais l'image figée en pleine réunion",
      es: 'Finges estar congelado en la reunión',
      ja: '会議で画面フリーズのふり中',
      ko: '회의 중 화면 멈춘 척하는 중',
    },
  },
  {
    emoji: '🧽',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK · 3. KAT',
        en: 'KITCHEN · FLOOR 3',
        de: 'KÜCHE · 3. OG',
        ar: 'المطبخ · الطابق 3',
        fr: 'CUISINE · 3E ÉTAGE',
        es: 'COCINA · PISO 3',
        ja: '給湯室・3階',
        ko: '탕비실 · 3층',
      },
    },
    caption: {
      tr: 'Masum görün. Kıpırdama.',
      en: "Look innocent. Don't move.",
      de: 'Unschuldig gucken. Nicht bewegen.',
      ar: 'ابدُ بريئًا. لا تتحرك.',
      fr: 'Prends un air innocent. Bouge pas.',
      es: 'Pon cara de inocente. No te muevas.',
      ja: '何食わぬ顔で。動かないで。',
      ko: '모르는 척. 움직이지 마세요.',
    },
    headline: {
      tr: 'Biri “Bu kupalar kimin?” diye soruyor',
      en: "Someone's asking whose mugs these are",
      de: 'Jemand fragt, wem die Tassen gehören',
      ar: 'أحدهم يسأل: «لمن هذه الأكواب؟»',
      fr: 'Quelqu’un demande à qui sont ces tasses',
      es: 'Alguien pregunta de quién son las tazas',
      ja: '「このマグ誰の？」と誰かが聞いてる',
      ko: '누가 “이 컵 누구 거예요?” 묻는 중',
    },
  },
];
