import { ACCOUNTS } from '../accounts';
import type { Draft, Localized } from '../types';

/**
 * The feed's first posts, in their places for good: `skip-001` is the
 * Monday-morning coffee for as long as the catalog lives. Their words may be
 * polished; their order and emoji never change (the fixtures hold them).
 */
export const CLASSIC_SKIP: readonly Draft[] = [
  {
    emoji: '☕️',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'POV: pazartesi sabahı',
      en: 'POV: Monday morning',
      de: 'POV: Montagmorgen',
      ar: 'مزاجي صباح أول يوم دوام',
      fr: 'POV : lundi matin',
      es: 'POV: lunes por la mañana',
      ja: 'POV：月曜の朝',
      ko: 'POV: 월요일 아침',
    },
  },
  {
    emoji: '🍝',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Bugün ne yedim? Makarna. Yine.',
      en: 'What I eat in a day: pasta. Again.',
      de: "Was gab's heute? Nudeln. Mal wieder.",
      ar: 'ماذا أكلت اليوم؟ معكرونة. مجددًا.',
      fr: 'Mon repas du jour ? Des pâtes. Encore.',
      es: '¿Qué comí hoy? Pasta. Otra vez.',
      ja: '今日の食事：パスタ。また。',
      ko: '오늘 뭐 먹었냐면: 파스타. 또.',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Kimse sormadı ama kahvem soğudu',
      en: 'Nobody asked, but my coffee went cold',
      de: 'Hat keiner gefragt, aber mein Kaffee ist kalt',
      ar: 'لم يسأل أحد، لكن قهوتي بردت',
      fr: "Personne n'a demandé, mais mon café a refroidi",
      es: 'Nadie preguntó, pero se me enfrió el café',
      ja: '誰も聞いてないけど、コーヒーが冷めた',
      ko: '아무도 안 물어봤지만 커피가 식었어요',
    },
  },
  {
    emoji: '🔁',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Rutinim: uyan, kaydır, uyu',
      en: 'My routine: wake up, scroll, sleep',
      de: 'Meine Routine: aufwachen, scrollen, schlafen',
      ar: 'روتيني: أستيقظ، أتصفح، أنام',
      fr: 'Ma routine : réveil, scroll, dodo',
      es: 'Mi rutina: despertar, deslizar, dormir',
      ja: 'ルーティン：起きる、スクロール、寝る',
      ko: '내 루틴: 기상, 스크롤, 취침',
    },
  },
  {
    emoji: '⏱️',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: '5 dakikalık hayat hilesi (4 dk reklam)',
      en: '5-minute life hack (4 min of ads)',
      de: '5-Minuten-Lifehack (4 Min. Werbung)',
      ar: 'حيلة في 5 دقائق (4 منها إعلانات)',
      fr: 'Astuce en 5 minutes (dont 4 de pub)',
      es: 'Truco de 5 minutos (4 son anuncios)',
      ja: '5分でできるライフハック（うち広告4分）',
      ko: '5분 생활 꿀팁 (광고 4분)',
    },
  },
  {
    emoji: '📉',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Bunu izleyenlerin %97’si kaydırdı',
      en: '97% of viewers scrolled past this',
      de: '97 % haben hier weitergescrollt',
      ar: '97% ممن شاهدوا هذا تجاوزوه',
      fr: '97 % des gens ont zappé ce post',
      es: 'El 97 % de la gente siguió deslizando',
      ja: 'これを見た人の97%がスクロールした',
      ko: '이 영상 본 사람의 97%가 넘겼어요',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Çorap eşleştirme challenge #3',
      en: 'Sock matching challenge #3',
      de: 'Socken-Sortier-Challenge #3',
      ar: 'تحدي مطابقة الجوارب، الجزء 3',
      fr: 'Challenge chaussettes orphelines #3',
      es: 'Reto: emparejar calcetines #3',
      ja: '靴下ペア探しチャレンジ #3',
      ko: '양말 짝 맞추기 챌린지 #3',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Otobüs yine gelmedi, vlog',
      en: "Bus didn't show up again, vlog",
      de: 'Bus kam wieder nicht, Vlog',
      ar: 'يوميات: الحافلة لم تأتِ مجددًا',
      fr: "Le bus n'est toujours pas là, vlog",
      es: 'El bus no vino otra vez, vlog',
      ja: 'バスがまた来なかったvlog',
      ko: '버스 또 안 옴 브이로그',
    },
  },
  {
    emoji: '🥬',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Buzdolabını açıp kapattım',
      en: 'Opened the fridge. Closed it.',
      de: 'Kühlschrank auf, Kühlschrank zu',
      ar: 'فتحت الثلاجة ثم أغلقتها',
      fr: 'Frigo ouvert. Frigo fermé.',
      es: 'Abrí la nevera. La cerré.',
      ja: '冷蔵庫を開けて、閉めた',
      ko: '냉장고 열었다가 닫음',
    },
  },
  {
    emoji: '📺',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Dizi önerisi: yok',
      en: 'Show recommendation: none',
      de: 'Serientipp: keiner',
      ar: 'ترشيح مسلسل: لا يوجد',
      fr: 'Série à voir : aucune',
      es: 'Serie recomendada: ninguna',
      ja: 'おすすめドラマ：なし',
      ko: '드라마 추천: 없음',
    },
  },
  {
    emoji: '🎵',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Bu ses trend olacak (olmayacak)',
      en: "This sound's gonna trend (it's not)",
      de: 'Dieser Sound geht viral (tut er nicht)',
      ar: 'هذا الصوت سيصبح ترندًا (لن يصبح)',
      fr: 'Ce son va buzzer (ou pas)',
      es: 'Este audio será tendencia (no lo será)',
      ja: 'この音源、流行る（流行らない）',
      ko: '이 음원 뜬다 (안 뜸)',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Motivasyon: yarın başlarım',
      en: "Motivation: I'll start tomorrow",
      de: 'Motivation: ab morgen dann',
      ar: 'التحفيز: سأبدأ غدًا',
      fr: 'Motivation : je commence demain',
      es: 'Motivación: mañana empiezo',
      ja: 'やる気：明日から本気出す',
      ko: '동기부여: 내일부터 시작',
    },
  },
  {
    emoji: '🧾',
    user: ACCOUNTS.asmr,
    body: {
      format: 'receipt',
      store: {
        tr: 'MARKET',
        en: 'GROCERY STORE',
        de: 'SUPERMARKT',
        ar: 'البقالة',
        fr: 'SUPÉRETTE',
        es: 'SUPERMERCADO',
        ja: 'スーパー',
        ko: '마트',
      },
      items: [{ tr: 'POŞET', en: 'BAG', de: 'TÜTE', ar: 'كيس', fr: 'SAC', es: 'BOLSA', ja: 'レジ袋', ko: '봉투' }],
    },
    caption: {
      tr: 'Market fişi ASMR',
      en: 'Grocery receipt ASMR',
      de: 'Kassenbon-ASMR',
      ar: 'أصوات مريحة: فاتورة البقالة',
      fr: 'ASMR ticket de caisse',
      es: 'ASMR con el ticket del súper',
      ja: 'スーパーのレシートASMR',
      ko: '마트 영수증 ASMR',
    },
  },
  {
    emoji: '🌧️',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Yağmur sesi, 10 saat',
      en: 'Rain sounds, 10 hours',
      de: 'Regengeräusche, 10 Stunden',
      ar: 'صوت المطر، 10 ساعات',
      fr: 'Bruit de pluie, 10 heures',
      es: 'Sonido de lluvia, 10 horas',
      ja: '雨の音、10時間',
      ko: '빗소리 10시간',
    },
  },
  {
    emoji: '🥪',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Tost makinesi incelemesi',
      en: 'In-depth panini press review',
      de: 'Sandwichmaker im Test',
      ar: 'مراجعة شاملة لصانعة الساندويتش',
      fr: "Test complet de l'appareil à croque",
      es: 'Reseña a fondo de la sandwichera',
      ja: 'ホットサンドメーカー徹底レビュー',
      ko: '토스트기 심층 리뷰',
    },
  },
  {
    emoji: '🗂️',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Masa düzenleme ama sessiz',
      en: 'Desk organizing, but make it silent',
      de: 'Schreibtisch aufräumen, aber leise',
      ar: 'ترتيب المكتب، لكن بصمت',
      fr: 'Rangement de bureau, mais en silence',
      es: 'Ordenando el escritorio, pero en silencio',
      ja: '無言でデスク整理',
      ko: '말없이 책상 정리',
    },
  },
  {
    emoji: '🥱',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Günaydın ama öğleden sonra',
      en: "Good morning (it's 2 p.m.)",
      de: 'Guten Morgen (es ist 14 Uhr)',
      ar: 'صباح الخير (الساعة 3 عصرًا)',
      fr: 'Réveil en douceur (il est 15 h)',
      es: 'Buenos días (son las 3 de la tarde)',
      ja: 'おはよう（午後2時）',
      ko: '좋은 아침 (오후 2시)',
    },
  },
  {
    emoji: '🪴',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Kedimin kediliği (kedim yok)',
      en: "Cat content (I don't have a cat)",
      de: 'Katzencontent (hab keine Katze)',
      ar: 'لحظات قطتي اللطيفة (ليس لديّ قطة)',
      fr: "Mon chat trop mignon (j'ai pas de chat)",
      es: 'Mi gato siendo muy gato (no tengo gato)',
      ja: '猫動画（猫は飼ってない）',
      ko: '고양이 콘텐츠 (고양이 없음)',
    },
  },
];

/** Friends post in lower case, the way people type to their friends. */
export const CLASSIC_LIKE: readonly Draft[] = [
  {
    emoji: '🐱',
    user: ACCOUNTS.zeynep,
    body: {
      format: 'polaroid',
      note: {
        tr: 'o bakış…',
        en: 'that look…',
        de: 'dieser blick…',
        ar: 'تلك النظرة…',
        fr: 'ce regard…',
        es: 'esa mirada…',
        ja: 'あの目つき…',
        ko: '저 눈빛…',
      },
    },
    caption: {
      tr: 'kedim yine beni yargılıyor',
      en: 'my cat is judging me again',
      de: 'meine katze verurteilt mich schon wieder',
      ar: 'قطتي تنظر إليّ بازدراء مجددًا',
      fr: 'mon chat me juge encore',
      es: 'mi gato me está juzgando otra vez',
      ja: 'うちの猫にまた裁かれてる',
      ko: '우리 고양이가 또 나를 심판 중',
    },
  },
  {
    emoji: '🎂',
    user: ACCOUNTS.ali,
    body: { format: 'scene' },
    caption: {
      tr: 'doğum günümdü, beğenmeyen küs',
      en: "it was my birthday, like it or we're done",
      de: 'hatte geburtstag. wer nicht liked, ist raus',
      ar: 'كان عيد ميلادي… لا إعجاب؟ لا صداقة',
      fr: "c'était mon anniv, pas de like = je boude",
      es: 'fue mi cumple, sin like no hay amistad',
      ja: '誕生日でした、いいねしない人とは絶交',
      ko: '내 생일이었음, 좋아요 안 누르면 절교',
    },
  },
  {
    emoji: '🍳',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk deneme',
        en: 'first try',
        de: 'erster versuch',
        ar: 'المحاولة الأولى',
        fr: 'premier essai',
        es: 'primer intento',
        ja: '初挑戦',
        ko: '첫 도전',
      },
    },
    caption: {
      tr: 'ilk yemeğim, yorum yapmayın',
      en: 'first time cooking, no comments pls',
      de: 'zum ersten mal gekocht, keine kommentare',
      ar: 'أول طبخة لي، بلا تعليقات',
      fr: 'mon premier plat, pas de commentaires',
      es: 'mi primera receta, sin comentarios',
      ja: '初めての手料理、コメント禁止',
      ko: '첫 요리, 댓글 금지',
    },
  },
  {
    emoji: '🏖️',
    user: ACCOUNTS.ece,
    body: { format: 'dump', emojis: ['🏖️', '🌅', '🍉', '🩴', '🕶️'] },
    caption: {
      tr: 'tatil fotoğrafı (sonunda)',
      en: 'vacation pic (finally)',
      de: 'urlaubsfoto (endlich)',
      ar: 'صورة من الإجازة (أخيرًا)',
      fr: 'photo de vacances (enfin)',
      es: 'foto de vacaciones (por fin)',
      ja: '旅行の写真（やっと）',
      ko: '휴가 사진 (드디어)',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'mezun 🎓',
        en: 'graduate 🎓',
        de: 'absolvent 🎓',
        ar: 'خرّيج 🎓',
        fr: 'diplômé 🎓',
        es: 'graduado 🎓',
        ja: '卒業 🎓',
        ko: '졸업 🎓',
      },
    },
    caption: {
      tr: 'köpeğim diploma aldı',
      en: 'my dog graduated',
      de: 'mein hund hat jetzt ein diplom',
      ar: 'كلبي تخرّج',
      fr: 'mon chien a eu son diplôme',
      es: 'mi perro se graduó',
      ja: 'うちの犬が卒業しました',
      ko: '우리 강아지 졸업했어요',
    },
  },
  {
    emoji: '💇',
    user: ACCOUNTS.deniz,
    body: { format: 'scene' },
    caption: {
      tr: 'yeni saç, dürüst olun',
      en: 'new hair, be honest',
      de: 'neue haare, seid ehrlich',
      ar: 'قصة شعر جديدة، كونوا صريحين',
      fr: 'nouvelle coupe, soyez honnêtes',
      es: 'corte nuevo, sean sinceros',
      ja: '髪切った、正直に言って',
      ko: '새 머리, 솔직하게 말해 줘',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.can,
    body: { format: 'dump', emojis: ['🎤', '🎸', '🎶', '🤘', '🎟️'] },
    caption: {
      tr: 'konserdeydim!!!',
      en: 'went to the concert!!!',
      de: 'war auf dem konzert!!!',
      ar: 'حضرت الحفلة!!!',
      fr: "j'étais au concert !!!",
      es: '¡¡¡fui al concierto!!!',
      ja: 'ライブ行ってきた！！！',
      ko: '콘서트 다녀왔다!!!',
    },
  },
  {
    emoji: '🥟',
    user: ACCOUNTS.mert,
    body: { format: 'scene' },
    caption: {
      tr: 'annemin böreği >>>',
      en: "mom's dumplings >>>",
      de: 'mamas maultaschen >>>',
      ar: 'سمبوسة أمي لا يُعلى عليها',
      fr: 'les raviolis de maman >>>',
      es: 'las empanadas de mi mamá >>>',
      ja: '母の手作り餃子 >>>',
      ko: '엄마표 만두 >>>',
    },
  },
  {
    emoji: '🐰',
    user: ACCOUNTS.ece,
    body: {
      format: 'polaroid',
      note: {
        tr: 'Havuç 🥕',
        en: 'Carrot 🥕',
        de: 'Möhre 🥕',
        ar: 'جزرة 🥕',
        fr: 'Carotte 🥕',
        es: 'Zanahoria 🥕',
        ja: 'にんじん 🥕',
        ko: '당근 🥕',
      },
    },
    caption: {
      tr: 'tavşanımın adı Havuç',
      en: "my bunny's name is Carrot",
      de: 'mein hase heißt Möhre',
      ar: 'أرنبي اسمه جزرة',
      fr: "mon lapin s'appelle Carotte",
      es: 'mi conejo se llama Zanahoria',
      ja: 'うちのうさぎの名前は「にんじん」',
      ko: '우리 토끼 이름은 당근',
    },
  },
  {
    emoji: '🦦',
    user: ACCOUNTS.zeynep,
    body: { format: 'scene' },
    caption: {
      tr: 'en sevdiğim hayvan, tartışmaya kapalı',
      en: 'my favorite animal, not up for debate',
      de: 'mein lieblingstier, keine diskussion',
      ar: 'حيواني المفضل، ولا نقاش',
      fr: 'mon animal préféré, point final',
      es: 'mi animal favorito, no se discute',
      ja: '一番好きな動物、異論は認めない',
      ko: '제일 좋아하는 동물, 반박 불가',
    },
  },
];

export const CLASSIC_HOLD: readonly Draft[] = [
  {
    emoji: '💎',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sonuna kadar izleyen kazanır',
      en: 'Watch till the end to win',
      de: 'Wer bis zum Ende schaut, gewinnt',
      ar: 'من يشاهد حتى النهاية يفوز',
      fr: "Regarde jusqu'au bout pour gagner",
      es: 'Míralo hasta el final y gana',
      ja: '最後まで見た人の勝ち',
      ko: '끝까지 보는 사람이 승리',
    },
  },
  {
    emoji: '👑',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir içerik, kaçırma',
      en: "Rare content, don't miss it",
      de: 'Seltener Content, nicht verpassen',
      ar: 'محتوى نادر، لا تفوّته',
      fr: 'Contenu rare, ne le rate pas',
      es: 'Contenido exclusivo, no te lo pierdas',
      ja: 'レアな動画、見逃すな',
      ko: '희귀 영상, 놓치지 마세요',
    },
  },
  {
    emoji: '🍀',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bu reel %1 şanslı kişiye çıkar',
      en: 'Only the luckiest 1% see this post',
      de: 'Glückspilz! Nur 1 % sehen diesen Post',
      ar: 'محظوظ! لا يرى هذا المنشور إلا 1% من الناس',
      fr: 'Post réservé aux 1 % les plus chanceux',
      es: 'Solo el 1 % más afortunado ve este post',
      ja: 'この投稿はラッキーな1%にしか出ない',
      ko: '이 게시물은 운 좋은 1%에게만 보여요',
    },
  },
  {
    emoji: '🏆',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Hazine sandığı açılıyor',
      en: 'The treasure chest is opening',
      de: 'Die Schatztruhe öffnet sich',
      ar: 'صندوق الكنز يُفتح الآن',
      fr: "Le coffre au trésor s'ouvre",
      es: 'Se abre el cofre del tesoro',
      ja: '宝箱が開きます',
      ko: '보물 상자가 열리는 중',
    },
  },
  {
    emoji: '⏳',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tam zamanında bırakan kazanır',
      en: 'Let go right on time to win',
      de: 'Wer im richtigen Moment loslässt, gewinnt',
      ar: 'من يرفع إصبعه في اللحظة المناسبة يفوز',
      fr: 'Relâche au bon moment pour gagner',
      es: 'Gana quien suelta en el momento justo',
      ja: 'ちょうどいいタイミングで離した人の勝ち',
      ko: '딱 맞춰 손 떼는 사람이 승리',
    },
  },
  {
    emoji: '🪙',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Altın an, doğru saniye',
      en: 'Golden moment, perfect timing',
      de: 'Goldener Moment, perfektes Timing',
      ar: 'لحظة ذهبية، في الثانية المناسبة',
      fr: 'Moment en or, seconde parfaite',
      es: 'Momento dorado, segundo exacto',
      ja: '黄金の瞬間、完璧なタイミング',
      ko: '황금의 순간, 완벽한 타이밍',
    },
  },
];

/** What every freeze reel says under its headline. */
export const HANDS_OFF: Localized = {
  tr: 'Kıpırdama. Dokunma.',
  en: "Don't move. Don't touch.",
  de: 'Nicht bewegen. Nicht berühren.',
  ar: 'لا تتحرك. لا تلمس.',
  fr: 'Bouge pas. Touche pas.',
  es: 'No te muevas. No toques.',
  ja: '動かないで。さわらないで。',
  ko: '움직이지 마세요. 건드리지 마세요.',
};

export const CLASSIC_FREEZE: readonly Draft[] = [
  {
    emoji: '👀',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
        ja: 'リビング',
        ko: '거실',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Annen odaya girdi',
      en: 'Mom just walked in',
      de: 'Mama kommt rein',
      ar: 'أمك دخلت الغرفة',
      fr: 'Maman entre dans la pièce',
      es: 'Tu madre acaba de entrar',
      ja: 'お母さんが部屋に入ってきた',
      ko: '엄마가 방에 들어왔다',
    },
  },
  {
    emoji: '🫣',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'OFİS',
        en: 'OFFICE',
        de: 'BÜRO',
        ar: 'المكتب',
        fr: 'BUREAU',
        es: 'OFICINA',
        ja: 'オフィス',
        ko: '사무실',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Patron arkanda',
      en: 'Boss is right behind you',
      de: 'Chef steht hinter dir',
      ar: 'المدير خلفك مباشرة',
      fr: 'Le patron est derrière toi',
      es: 'Tu jefe está detrás de ti',
      ja: '上司が真後ろにいる',
      ko: '팀장님이 바로 뒤에 있다',
    },
  },
  {
    emoji: '👩‍🏫',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SINIF',
        en: 'CLASSROOM',
        de: 'KLASSENZIMMER',
        ar: 'الصف',
        fr: 'CLASSE',
        es: 'AULA',
        ja: '教室',
        ko: '교실',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Hoca bakıyor',
      en: "Teacher's watching",
      de: 'Die Lehrerin schaut her',
      ar: 'المعلمة تنظر إليك',
      fr: 'La prof te regarde',
      es: 'La profe te está mirando',
      ja: '先生が見てる',
      ko: '선생님이 보고 있다',
    },
  },
  {
    emoji: '🧍',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KORİDOR',
        en: 'HALLWAY',
        de: 'FLUR',
        ar: 'الممر',
        fr: 'COULOIR',
        es: 'PASILLO',
        ja: '廊下',
        ko: '복도',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Babanın ayak sesleri',
      en: "Dad's footsteps",
      de: 'Papas Schritte im Flur',
      ar: 'وقع خطوات أبيك',
      fr: "Papa monte l'escalier",
      es: 'Los pasos de tu padre',
      ja: 'お父さんの足音',
      ko: '아빠 발소리',
    },
  },
  {
    emoji: '🚨',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYARI',
        en: 'WARNING',
        de: 'ACHTUNG',
        ar: 'تحذير',
        fr: 'ATTENTION',
        es: 'ATENCIÓN',
        ja: '警告',
        ko: '경고',
      },
      small: {
        tr: 'EKRAN SÜRESİ DOLDU',
        en: "SCREEN TIME'S UP",
        de: 'BILDSCHIRMZEIT VORBEI',
        ar: 'انتهى وقت الشاشة',
        fr: "TEMPS D'ÉCRAN FINI",
        es: 'SE ACABÓ EL TIEMPO',
        ja: 'スクリーンタイム終了',
        ko: '스크린 타임 종료',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Ekran süresi uyarısı',
      en: 'Screen time alert',
      de: 'Bildschirmzeit-Warnung',
      ar: 'تنبيه وقت الشاشة',
      fr: "Alerte temps d'écran",
      es: 'Alerta de tiempo de pantalla',
      ja: 'スクリーンタイムの警告',
      ko: '스크린 타임 경고',
    },
  },
];
