import { ACCOUNTS } from '../accounts';
import type { Draft, Localized } from '../types';

/**
 * The feed's first posts, in their places for good: `skip-001` is the
 * Monday-morning coffee for as long as the catalog lives. Their words may be
 * polished; their order and emoji never change (the fixtures hold them).
 */
export const CLASSIC_SKIP: readonly Draft[] = [
  {
    emoji: '☕️',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'POV: pazartesi sabahı',
      en: 'POV: Monday morning',
      de: 'POV: Montagmorgen',
      ar: 'مزاجي صباح أول يوم دوام',
      fr: 'POV : lundi matin',
      es: 'POV: lunes por la mañana',
    },
  },
  {
    emoji: '🍝',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Bugün ne yedim? Makarna. Yine.',
      en: 'What I eat in a day: pasta. Again.',
      de: "Was gab's heute? Nudeln. Mal wieder.",
      ar: 'ماذا أكلت اليوم؟ معكرونة. مجددًا.',
      fr: 'Mon repas du jour ? Des pâtes. Encore.',
      es: '¿Qué comí hoy? Pasta. Otra vez.',
    },
  },
  {
    emoji: '🧊',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Kimse sormadı ama kahvem soğudu',
      en: 'Nobody asked, but my coffee went cold',
      de: 'Hat keiner gefragt, aber mein Kaffee ist kalt',
      ar: 'لم يسأل أحد، لكن قهوتي بردت',
      fr: "Personne n'a demandé, mais mon café a refroidi",
      es: 'Nadie preguntó, pero se me enfrió el café',
    },
  },
  {
    emoji: '🔁',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Rutinim: uyan, kaydır, uyu',
      en: 'My routine: wake up, scroll, sleep',
      de: 'Meine Routine: aufwachen, scrollen, schlafen',
      ar: 'روتيني: أستيقظ، أتصفح، أنام',
      fr: 'Ma routine : réveil, scroll, dodo',
      es: 'Mi rutina: despertar, deslizar, dormir',
    },
  },
  {
    emoji: '⏱️',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: '5 dakikalık hayat hilesi (4 dk reklam)',
      en: '5-minute life hack (4 min of ads)',
      de: '5-Minuten-Lifehack (4 Min. Werbung)',
      ar: 'حيلة في 5 دقائق (4 منها إعلانات)',
      fr: 'Astuce en 5 minutes (dont 4 de pub)',
      es: 'Truco de 5 minutos (4 son anuncios)',
    },
  },
  {
    emoji: '📉',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Bunu izleyenlerin %97’si kaydırdı',
      en: '97% of viewers scrolled past this',
      de: '97 % haben hier weitergescrollt',
      ar: '97% ممن شاهدوا هذا تجاوزوه',
      fr: '97 % des gens ont zappé ce post',
      es: 'El 97 % de la gente siguió deslizando',
    },
  },
  {
    emoji: '🧦',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Çorap eşleştirme challenge #3',
      en: 'Sock matching challenge #3',
      de: 'Socken-Sortier-Challenge #3',
      ar: 'تحدي مطابقة الجوارب، الجزء 3',
      fr: 'Challenge chaussettes orphelines #3',
      es: 'Reto: emparejar calcetines #3',
    },
  },
  {
    emoji: '🚌',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Otobüs yine gelmedi, vlog',
      en: "Bus didn't show up again, vlog",
      de: 'Bus kam wieder nicht, Vlog',
      ar: 'يوميات: الحافلة لم تأتِ مجددًا',
      fr: "Le bus n'est toujours pas là, vlog",
      es: 'El bus no vino otra vez, vlog',
    },
  },
  {
    emoji: '🥬',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Buzdolabını açıp kapattım',
      en: 'Opened the fridge. Closed it.',
      de: 'Kühlschrank auf, Kühlschrank zu',
      ar: 'فتحت الثلاجة ثم أغلقتها',
      fr: 'Frigo ouvert. Frigo fermé.',
      es: 'Abrí la nevera. La cerré.',
    },
  },
  {
    emoji: '📺',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Dizi önerisi: yok',
      en: 'Show recommendation: none',
      de: 'Serientipp: keiner',
      ar: 'ترشيح مسلسل: لا يوجد',
      fr: 'Série à voir : aucune',
      es: 'Serie recomendada: ninguna',
    },
  },
  {
    emoji: '🎵',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Bu ses trend olacak (olmayacak)',
      en: "This sound's gonna trend (it's not)",
      de: 'Dieser Sound geht viral (tut er nicht)',
      ar: 'هذا الصوت سيصبح ترندًا (لن يصبح)',
      fr: 'Ce son va buzzer (ou pas)',
      es: 'Este audio será tendencia (no lo será)',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Motivasyon: yarın başlarım',
      en: "Motivation: I'll start tomorrow",
      de: 'Motivation: ab morgen dann',
      ar: 'التحفيز: سأبدأ غدًا',
      fr: 'Motivation : je commence demain',
      es: 'Motivación: mañana empiezo',
    },
  },
  {
    emoji: '🧾',
    user: ACCOUNTS.asmr,
    body: {
      format: 'receipt',
      store: {
        tr: 'MARKET',
        en: 'GROCERY STORE',
        de: 'SUPERMARKT',
        ar: 'البقالة',
        fr: 'SUPÉRETTE',
        es: 'SUPERMERCADO',
      },
      items: [{ tr: 'POŞET', en: 'BAG', de: 'TÜTE', ar: 'كيس', fr: 'SAC', es: 'BOLSA' }],
    },
    caption: {
      tr: 'Market fişi ASMR',
      en: 'Grocery receipt ASMR',
      de: 'Kassenbon-ASMR',
      ar: 'أصوات مريحة: فاتورة البقالة',
      fr: 'ASMR ticket de caisse',
      es: 'ASMR con el ticket del súper',
    },
  },
  {
    emoji: '🌧️',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Yağmur sesi, 10 saat',
      en: 'Rain sounds, 10 hours',
      de: 'Regengeräusche, 10 Stunden',
      ar: 'صوت المطر، 10 ساعات',
      fr: 'Bruit de pluie, 10 heures',
      es: 'Sonido de lluvia, 10 horas',
    },
  },
  {
    emoji: '🥪',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Tost makinesi incelemesi',
      en: 'In-depth panini press review',
      de: 'Sandwichmaker im Test',
      ar: 'مراجعة شاملة لصانعة الساندويتش',
      fr: "Test complet de l'appareil à croque",
      es: 'Reseña a fondo de la sandwichera',
    },
  },
  {
    emoji: '🗂️',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Masa düzenleme ama sessiz',
      en: 'Desk organizing, but make it silent',
      de: 'Schreibtisch aufräumen, aber leise',
      ar: 'ترتيب المكتب، لكن بصمت',
      fr: 'Rangement de bureau, mais en silence',
      es: 'Ordenando el escritorio, pero en silencio',
    },
  },
  {
    emoji: '🥱',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Günaydın ama öğleden sonra',
      en: "Good morning (it's 2 p.m.)",
      de: 'Guten Morgen (es ist 14 Uhr)',
      ar: 'صباح الخير (الساعة 3 عصرًا)',
      fr: 'Réveil en douceur (il est 15 h)',
      es: 'Buenos días (son las 3 de la tarde)',
    },
  },
  {
    emoji: '🪴',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Kedimin kediliği (kedim yok)',
      en: "Cat content (I don't have a cat)",
      de: 'Katzencontent (hab keine Katze)',
      ar: 'لحظات قطتي اللطيفة (ليس لديّ قطة)',
      fr: "Mon chat trop mignon (j'ai pas de chat)",
      es: 'Mi gato siendo muy gato (no tengo gato)',
    },
  },
];

/** Friends post in lower case, the way people type to their friends. */
export const CLASSIC_LIKE: readonly Draft[] = [
  {
    emoji: '🐱',
    user: ACCOUNTS.zeynep,
    body: {
      format: 'polaroid',
      note: {
        tr: 'o bakış…',
        en: 'that look…',
        de: 'dieser blick…',
        ar: 'تلك النظرة…',
        fr: 'ce regard…',
        es: 'esa mirada…',
      },
    },
    caption: {
      tr: 'kedim yine beni yargılıyor',
      en: 'my cat is judging me again',
      de: 'meine katze verurteilt mich schon wieder',
      ar: 'قطتي تنظر إليّ بازدراء مجددًا',
      fr: 'mon chat me juge encore',
      es: 'mi gato me está juzgando otra vez',
    },
  },
  {
    emoji: '🎂',
    user: ACCOUNTS.ali,
    body: { format: 'scene' },
    caption: {
      tr: 'doğum günümdü, beğenmeyen küs',
      en: "it was my birthday, like it or we're done",
      de: 'hatte geburtstag. wer nicht liked, ist raus',
      ar: 'كان عيد ميلادي… لا إعجاب؟ لا صداقة',
      fr: "c'était mon anniv, pas de like = je boude",
      es: 'fue mi cumple, sin like no hay amistad',
    },
  },
  {
    emoji: '🍳',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk deneme',
        en: 'first try',
        de: 'erster versuch',
        ar: 'المحاولة الأولى',
        fr: 'premier essai',
        es: 'primer intento',
      },
    },
    caption: {
      tr: 'ilk yemeğim, yorum yapmayın',
      en: 'first time cooking, no comments pls',
      de: 'zum ersten mal gekocht, keine kommentare',
      ar: 'أول طبخة لي، بلا تعليقات',
      fr: 'mon premier plat, pas de commentaires',
      es: 'mi primera receta, sin comentarios',
    },
  },
  {
    emoji: '🏖️',
    user: ACCOUNTS.ece,
    body: { format: 'dump', emojis: ['🏖️', '🌅', '🍉', '🩴', '🕶️'] },
    caption: {
      tr: 'tatil fotoğrafı (sonunda)',
      en: 'vacation pic (finally)',
      de: 'urlaubsfoto (endlich)',
      ar: 'صورة من الإجازة (أخيرًا)',
      fr: 'photo de vacances (enfin)',
      es: 'foto de vacaciones (por fin)',
    },
  },
  {
    emoji: '🐶',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'mezun 🎓',
        en: 'graduate 🎓',
        de: 'absolvent 🎓',
        ar: 'خرّيج 🎓',
        fr: 'diplômé 🎓',
        es: 'graduado 🎓',
      },
    },
    caption: {
      tr: 'köpeğim diploma aldı',
      en: 'my dog graduated',
      de: 'mein hund hat jetzt ein diplom',
      ar: 'كلبي تخرّج',
      fr: 'mon chien a eu son diplôme',
      es: 'mi perro se graduó',
    },
  },
  {
    emoji: '💇',
    user: ACCOUNTS.deniz,
    body: { format: 'scene' },
    caption: {
      tr: 'yeni saç, dürüst olun',
      en: 'new hair, be honest',
      de: 'neue haare, seid ehrlich',
      ar: 'قصة شعر جديدة، كونوا صريحين',
      fr: 'nouvelle coupe, soyez honnêtes',
      es: 'corte nuevo, sean sinceros',
    },
  },
  {
    emoji: '🎤',
    user: ACCOUNTS.can,
    body: { format: 'dump', emojis: ['🎤', '🎸', '🎶', '🤘', '🎟️'] },
    caption: {
      tr: 'konserdeydim!!!',
      en: 'went to the concert!!!',
      de: 'war auf dem konzert!!!',
      ar: 'حضرت الحفلة!!!',
      fr: "j'étais au concert !!!",
      es: '¡¡¡fui al concierto!!!',
    },
  },
  {
    emoji: '🥟',
    user: ACCOUNTS.mert,
    body: { format: 'scene' },
    caption: {
      tr: 'annemin böreği >>>',
      en: "mom's dumplings >>>",
      de: 'mamas maultaschen >>>',
      ar: 'سمبوسة أمي لا يُعلى عليها',
      fr: 'les raviolis de maman >>>',
      es: 'las empanadas de mi mamá >>>',
    },
  },
  {
    emoji: '🐰',
    user: ACCOUNTS.ece,
    body: {
      format: 'polaroid',
      note: {
        tr: 'Havuç 🥕',
        en: 'Carrot 🥕',
        de: 'Möhre 🥕',
        ar: 'جزرة 🥕',
        fr: 'Carotte 🥕',
        es: 'Zanahoria 🥕',
      },
    },
    caption: {
      tr: 'tavşanımın adı Havuç',
      en: "my bunny's name is Carrot",
      de: 'mein hase heißt Möhre',
      ar: 'أرنبي اسمه جزرة',
      fr: "mon lapin s'appelle Carotte",
      es: 'mi conejo se llama Zanahoria',
    },
  },
  {
    emoji: '🦦',
    user: ACCOUNTS.zeynep,
    body: { format: 'scene' },
    caption: {
      tr: 'en sevdiğim hayvan, tartışmaya kapalı',
      en: 'my favorite animal, not up for debate',
      de: 'mein lieblingstier, keine diskussion',
      ar: 'حيواني المفضل، ولا نقاش',
      fr: 'mon animal préféré, point final',
      es: 'mi animal favorito, no se discute',
    },
  },
];

export const CLASSIC_HOLD: readonly Draft[] = [
  {
    emoji: '💎',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sonuna kadar izleyen kazanır',
      en: 'Watch till the end to win',
      de: 'Wer bis zum Ende schaut, gewinnt',
      ar: 'من يشاهد حتى النهاية يفوز',
      fr: "Regarde jusqu'au bout pour gagner",
      es: 'Míralo hasta el final y gana',
    },
  },
  {
    emoji: '👑',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir içerik, kaçırma',
      en: "Rare content, don't miss it",
      de: 'Seltener Content, nicht verpassen',
      ar: 'محتوى نادر، لا تفوّته',
      fr: 'Contenu rare, ne le rate pas',
      es: 'Contenido exclusivo, no te lo pierdas',
    },
  },
  {
    emoji: '🍀',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bu reel %1 şanslı kişiye çıkar',
      en: 'Only the luckiest 1% see this post',
      de: 'Glückspilz! Nur 1 % sehen diesen Post',
      ar: 'محظوظ! لا يرى هذا المنشور إلا 1% من الناس',
      fr: 'Post réservé aux 1 % les plus chanceux',
      es: 'Solo el 1 % más afortunado ve este post',
    },
  },
  {
    emoji: '🏆',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Hazine sandığı açılıyor',
      en: 'The treasure chest is opening',
      de: 'Die Schatztruhe öffnet sich',
      ar: 'صندوق الكنز يُفتح الآن',
      fr: "Le coffre au trésor s'ouvre",
      es: 'Se abre el cofre del tesoro',
    },
  },
  {
    emoji: '⏳',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Tam zamanında bırakan kazanır',
      en: 'Let go right on time to win',
      de: 'Wer im richtigen Moment loslässt, gewinnt',
      ar: 'من يرفع إصبعه في اللحظة المناسبة يفوز',
      fr: 'Relâche au bon moment pour gagner',
      es: 'Gana quien suelta en el momento justo',
    },
  },
  {
    emoji: '🪙',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Altın an, doğru saniye',
      en: 'Golden moment, perfect timing',
      de: 'Goldener Moment, perfektes Timing',
      ar: 'لحظة ذهبية، في الثانية المناسبة',
      fr: 'Moment en or, seconde parfaite',
      es: 'Momento dorado, segundo exacto',
    },
  },
];

/** What every freeze reel says under its headline. */
export const HANDS_OFF: Localized = {
  tr: 'Kıpırdama. Dokunma.',
  en: "Don't move. Don't touch.",
  de: 'Nicht bewegen. Nicht berühren.',
  ar: 'لا تتحرك. لا تلمس.',
  fr: 'Bouge pas. Touche pas.',
  es: 'No te muevas. No toques.',
};

export const CLASSIC_FREEZE: readonly Draft[] = [
  {
    emoji: '👀',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Annen odaya girdi',
      en: 'Mom just walked in',
      de: 'Mama kommt rein',
      ar: 'أمك دخلت الغرفة',
      fr: 'Maman entre dans la pièce',
      es: 'Tu madre acaba de entrar',
    },
  },
  {
    emoji: '🫣',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'OFİS',
        en: 'OFFICE',
        de: 'BÜRO',
        ar: 'المكتب',
        fr: 'BUREAU',
        es: 'OFICINA',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Patron arkanda',
      en: 'Boss is right behind you',
      de: 'Chef steht hinter dir',
      ar: 'المدير خلفك مباشرة',
      fr: 'Le patron est derrière toi',
      es: 'Tu jefe está detrás de ti',
    },
  },
  {
    emoji: '👩‍🏫',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SINIF',
        en: 'CLASSROOM',
        de: 'KLASSENZIMMER',
        ar: 'الصف',
        fr: 'CLASSE',
        es: 'AULA',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Hoca bakıyor',
      en: "Teacher's watching",
      de: 'Die Lehrerin schaut her',
      ar: 'المعلمة تنظر إليك',
      fr: 'La prof te regarde',
      es: 'La profe te está mirando',
    },
  },
  {
    emoji: '🧍',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'KORİDOR',
        en: 'HALLWAY',
        de: 'FLUR',
        ar: 'الممر',
        fr: 'COULOIR',
        es: 'PASILLO',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Babanın ayak sesleri',
      en: "Dad's footsteps",
      de: 'Papas Schritte im Flur',
      ar: 'وقع خطوات أبيك',
      fr: "Papa monte l'escalier",
      es: 'Los pasos de tu padre',
    },
  },
  {
    emoji: '🚨',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'UYARI',
        en: 'WARNING',
        de: 'ACHTUNG',
        ar: 'تحذير',
        fr: 'ATTENTION',
        es: 'ATENCIÓN',
      },
      small: {
        tr: 'EKRAN SÜRESİ DOLDU',
        en: "SCREEN TIME'S UP",
        de: 'BILDSCHIRMZEIT VORBEI',
        ar: 'انتهى وقت الشاشة',
        fr: "TEMPS D'ÉCRAN FINI",
        es: 'SE ACABÓ EL TIEMPO',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Ekran süresi uyarısı',
      en: 'Screen time alert',
      de: 'Bildschirmzeit-Warnung',
      ar: 'تنبيه وقت الشاشة',
      fr: "Alerte temps d'écran",
      es: 'Alerta de tiempo de pantalla',
    },
  },
];
