import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';
import { HANDS_OFF } from './classic';

/** Don't-touch posts that are security camera frames (`cctv`). Append only: a published post keeps its place. */
export const FREEZE_CCTV: readonly Draft[] = [
  {
    emoji: '👦',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YATAK ODASI',
        en: 'BEDROOM',
        de: 'SCHLAFZIMMER',
        ar: 'غرفة النوم',
        fr: 'CHAMBRE',
        es: 'DORMITORIO',
        ja: '寝室',
        ko: '침실',
      },
    },
    caption: {
      tr: 'Şarj aleti sende. Kıpırdama.',
      en: "You have it. Don't move.",
      de: 'Du hast es. Keine Bewegung.',
      ar: 'الشاحن معك. لا تتحرك.',
      fr: "C'est toi qui l'as. Bouge pas.",
      es: 'Lo tienes tú. No te muevas.',
      ja: '充電器は君が持ってる。動くな。',
      ko: '충전기는 네가 갖고 있어. 움직이지 마.',
    },
    headline: {
      tr: 'Kardeşin şarj aletini arıyor',
      en: "Your brother's looking for his charger",
      de: 'Dein Bruder sucht sein Ladekabel',
      ar: 'أخوك يبحث عن شاحنه',
      fr: 'Ton frère cherche son chargeur',
      es: 'Tu hermano busca su cargador',
      ja: '弟が充電器を探してる！',
      ko: '동생이 충전기를 찾고 있어요!',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇALIŞMA ODASI',
        en: 'STUDY',
        de: 'ARBEITSZIMMER',
        ar: 'غرفة المكتب',
        fr: 'BUREAU',
        es: 'ESTUDIO',
        ja: '書斎',
        ko: '서재',
      },
    },
    caption: {
      tr: 'Göz göze gelme.',
      en: "Don't make eye contact.",
      de: 'Kein Blickkontakt.',
      ar: 'لا تنظر في عينيها.',
      fr: 'Évite son regard.',
      es: 'No lo mires a los ojos.',
      ja: '目を合わせるな。',
      ko: '눈 마주치지 마.',
    },
    headline: {
      tr: 'Kedi kupayı masadan itmek üzere',
      en: "The cat's about to push your mug off",
      de: 'Die Katze schubst deine Tasse zum Rand',
      ar: 'القطة على وشك إسقاط كوبك',
      fr: 'Le chat va faire tomber ta tasse',
      es: 'El gato va a tirar tu taza',
      ja: '猫がマグカップを落とす寸前！',
      ko: '고양이가 머그컵을 떨어뜨리기 직전!',
    },
  },
  {
    emoji: '💇',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KUAFÖR',
        en: 'HAIR SALON',
        de: 'FRISEURSALON',
        ar: 'صالون التجميل',
        fr: 'SALON DE COIFFURE',
        es: 'PELUQUERÍA',
        ja: '美容院',
        ko: '미용실',
      },
    },
    caption: {
      tr: 'Kıpırdarsan kâkül yamuk olur.',
      en: "Move and they'll come out crooked.",
      de: 'Eine Bewegung und er wird schief.',
      ar: 'إن تحركت صارت الغرّة مائلة.',
      fr: 'Un geste et elle sera de travers.',
      es: 'Si te mueves, queda torcido.',
      ja: '動いたら前髪がななめになる。',
      ko: '움직이면 앞머리 삐뚤어져.',
    },
    headline: {
      tr: 'Kuaför kâkülünü kesiyor',
      en: "The stylist's cutting your bangs",
      de: 'Die Friseurin schneidet deinen Pony',
      ar: 'المصففة تقص غرّتك',
      fr: 'La coiffeuse coupe ta frange',
      es: 'Te están cortando el flequillo',
      ja: '美容師さんが前髪をカット中！',
      ko: '미용사가 앞머리를 자르는 중!',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ANTRE',
        en: 'ENTRYWAY',
        de: 'DIELE',
        ar: 'المدخل',
        fr: 'ENTRÉE',
        es: 'ENTRADA',
        ja: '玄関',
        ko: '현관',
      },
    },
    caption: {
      tr: 'Uyuyor numarası yap.',
      en: "Pretend you're asleep.",
      de: 'Stell dich schlafend.',
      ar: 'تظاهر بأنك نائم.',
      fr: 'Fais semblant de dormir.',
      es: 'Hazte el dormido.',
      ja: '寝たふりをしろ。',
      ko: '자는 척해.',
    },
    headline: {
      tr: 'Köpek tasmayı getirdi, seni arıyor',
      en: 'The dog brought its leash over',
      de: 'Der Hund hat die Leine im Maul',
      ar: 'الكلب أحضر المقود ويبحث عنك',
      fr: 'Le chien a apporté sa laisse',
      es: 'El perro trajo la correa',
      ja: '犬がリードをくわえて来た！',
      ko: '강아지가 목줄을 물고 왔어요!',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'BAHÇE',
        en: 'BACKYARD',
        de: 'GARTEN',
        ar: 'الحديقة',
        fr: 'JARDIN',
        es: 'JARDÍN',
        ja: '庭',
        ko: '뒷마당',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Saklambaç: ebe tam önünden geçiyor',
      en: "Hide-and-seek: the seeker's right there",
      de: 'Verstecken: Der Sucher steht direkt da',
      ar: 'الغمّيضة: الباحث أمامك تمامًا',
      fr: 'Cache-cache : il passe juste devant toi',
      es: 'Escondite: te buscan justo al lado',
      ja: 'かくれんぼ：鬼がすぐそこに！',
      ko: '숨바꼭질: 술래가 바로 앞에!',
    },
  },
  {
    emoji: '🤫',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KÜTÜPHANE',
        en: 'LIBRARY',
        de: 'BIBLIOTHEK',
        ar: 'المكتبة',
        fr: 'BIBLIOTHÈQUE',
        es: 'BIBLIOTECA',
        ja: '図書館',
        ko: '도서관',
      },
    },
    caption: {
      tr: 'Sayfa çevirmek bile yasak.',
      en: "Don't even turn a page.",
      de: 'Nicht mal umblättern.',
      ar: 'ولا تقلب صفحة حتى.',
      fr: 'Tourne même pas une page.',
      es: 'Ni se te ocurra pasar la página.',
      ja: 'ページもめくるな。',
      ko: '책장도 넘기지 마.',
    },
    headline: {
      tr: 'Kütüphaneci “şşşt” dedi',
      en: 'The librarian just shushed you',
      de: 'Die Bibliothekarin macht „Pssst!“',
      ar: 'أمينة المكتبة طلبت منك الهدوء',
      fr: "La bibliothécaire t'a fait « chut »",
      es: 'La bibliotecaria te pidió silencio',
      ja: '司書さんに「シーッ」された！',
      ko: '사서가 “쉿” 했어요!',
    },
  },
  {
    emoji: '🎉',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
        ja: 'リビング',
        ko: '거실',
      },
    },
    caption: {
      tr: 'Görmedin. Kıpırdama.',
      en: "You saw nothing. Don't move.",
      de: 'Du hast nichts gesehen. Nicht bewegen.',
      ar: 'لم ترَ شيئًا. لا تتحرك.',
      fr: "T'as rien vu. Bouge pas.",
      es: 'No viste nada. No te muevas.',
      ja: '何も見てない。動くな。',
      ko: '넌 아무것도 못 봤어. 움직이지 마.',
    },
    headline: {
      tr: 'Sana sürpriz parti hazırlıyorlar',
      en: "They're planning your surprise party",
      de: 'Sie planen deine Überraschungsparty',
      ar: 'يجهّزون لك حفلة مفاجئة',
      fr: 'Ils préparent ta fête surprise',
      es: 'Te preparan una fiesta sorpresa',
      ja: '君のサプライズパーティーを準備中！',
      ko: '깜짝 파티를 준비하고 있어요!',
    },
  },
  {
    emoji: '🧀',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK',
        en: 'KITCHEN',
        de: 'KÜCHE',
        ar: 'المطبخ',
        fr: 'CUISINE',
        es: 'COCINA',
        ja: 'キッチン',
        ko: '주방',
      },
    },
    caption: {
      tr: 'Belki kimse fark etmez.',
      en: 'Maybe nobody noticed.',
      de: "Vielleicht merkt's keiner.",
      ar: 'ربما لم يلاحظ أحد.',
      fr: "Peut-être que personne n'a vu.",
      es: 'Quizá nadie se dio cuenta.',
      ja: '誰も気づいてない…かも。',
      ko: '아무도 눈치 못 챘을지도.',
    },
    headline: {
      tr: 'Gece 3. Buzdolabı. Işık açık.',
      en: "3 a.m. Fridge. Light's on.",
      de: '3 Uhr nachts. Kühlschrank. Licht an.',
      ar: 'الثالثة فجرًا. الثلاجة. الضوء مضاء.',
      fr: '3 h du mat. Frigo. Lumière allumée.',
      es: '3 de la mañana. Nevera. Luz encendida.',
      ja: '深夜3時。冷蔵庫。明かりがついた。',
      ko: '새벽 3시. 냉장고. 불이 켜졌다.',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'BALKON',
        en: 'BALCONY',
        de: 'BALKON',
        ar: 'الشرفة',
        fr: 'BALCON',
        es: 'BALCÓN',
        ja: 'ベランダ',
        ko: '베란다',
      },
    },
    caption: {
      tr: 'Gönüllü olma. Kıpırdama.',
      en: "Don't volunteer. Don't move.",
      de: 'Nicht melden. Nicht bewegen.',
      ar: 'لا تتطوع. لا تتحرك.',
      fr: 'Te porte pas volontaire. Bouge pas.',
      es: 'No te ofrezcas. No te muevas.',
      ja: '名乗り出るな。動くな。',
      ko: '자원하지 마. 움직이지 마.',
    },
    headline: {
      tr: 'Çamaşır asacak gönüllü aranıyor',
      en: 'Wanted: a volunteer to hang laundry',
      de: 'Wer hilft beim Wäscheaufhängen?',
      ar: 'مطلوب متطوع لنشر الغسيل',
      fr: 'Qui veut étendre le linge ?',
      es: 'Se busca voluntario para tender la ropa',
      ja: '洗濯物を干す人、募集中！',
      ko: '빨래 널 사람 구해요!',
    },
  },
  {
    emoji: '👴',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YEMEK ODASI',
        en: 'DINING ROOM',
        de: 'ESSZIMMER',
        ar: 'غرفة الطعام',
        fr: 'SALLE À MANGER',
        es: 'COMEDOR',
        ja: 'ダイニング',
        ko: '다이닝룸',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Deden “bu telefonlar…” diye başladı',
      en: 'Grandpa just said “these phones…”',
      de: 'Opa fängt an: „Diese Handys…“',
      ar: 'جدّك بدأ يقول: «هذه الهواتف…»',
      fr: 'Papi commence : « ces téléphones… »',
      es: 'El abuelo empezó: «estos teléfonos…»',
      ja: '祖父が「最近のスマホは…」と言い出した',
      ko: '할아버지가 “요즘 폰은…” 하셨어요',
    },
  },
  {
    emoji: '⏱️',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SPOR SALONU',
        en: 'GYM',
        de: 'TURNHALLE',
        ar: 'صالة الرياضة',
        fr: 'GYMNASE',
        es: 'GIMNASIO',
        ja: 'ジム',
        ko: '헬스장',
      },
    },
    caption: {
      tr: 'Görünmez ol.',
      en: 'Be invisible.',
      de: 'Mach dich unsichtbar.',
      ar: 'كن خفيًّا.',
      fr: 'Fais-toi tout petit.',
      es: 'Hazte invisible.',
      ja: '透明人間になれ。',
      ko: '투명 인간이 돼.',
    },
    headline: {
      tr: 'Antrenör “bir tur daha” diyecek',
      en: 'Coach is about to say “one more lap”',
      de: 'Gleich heißt es: „Noch eine Runde!“',
      ar: 'المدرب سيقول: «لفّة أخرى»',
      fr: 'Le coach va dire « encore un tour »',
      es: 'El entrenador va a pedir otra vuelta',
      ja: 'コーチが「あと1周」と言いそう！',
      ko: '코치가 “한 바퀴 더” 할 기세예요!',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAPI ÖNÜ',
        en: 'FRONT DOOR',
        de: 'HAUSTÜR',
        ar: 'الباب الأمامي',
        fr: "PORTE D'ENTRÉE",
        es: 'PUERTA PRINCIPAL',
        ja: '玄関前',
        ko: '현관문 앞',
      },
    },
    caption: {
      tr: 'Evde kimse yok. Sen de yoksun.',
      en: "Nobody's home. Including you.",
      de: 'Keiner da. Du auch nicht.',
      ar: 'لا أحد في البيت… ولا أنت.',
      fr: 'Y a personne. Toi non plus.',
      es: 'No hay nadie. Tú tampoco.',
      ja: '家には誰もいない。君もいない。',
      ko: '집에 아무도 없어. 너도 없어.',
    },
    headline: {
      tr: 'Komşu zile bastı',
      en: "The neighbor's at the door",
      de: 'Die Nachbarin klingelt',
      ar: 'الجار يرنّ الجرس',
      fr: 'La voisine sonne à la porte',
      es: 'La vecina tocó el timbre',
      ja: 'お隣さんがピンポンした！',
      ko: '이웃이 초인종을 눌렀어요!',
    },
  },
  {
    emoji: '📓',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇOCUK ODASI',
        en: "KIDS' ROOM",
        de: 'KINDERZIMMER',
        ar: 'غرفة الأطفال',
        fr: "CHAMBRE D'ENFANT",
        es: 'CUARTO DE NIÑOS',
        ja: '子ども部屋',
        ko: '아이 방',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Ödev kontrolü geliyor',
      en: 'Homework check incoming',
      de: 'Hausaufgaben-Kontrolle im Anmarsch',
      ar: 'تفتيش الواجبات في الطريق',
      fr: 'Contrôle des devoirs en approche',
      es: 'Viene la revisión de la tarea',
      ja: '宿題チェックが来る！',
      ko: '숙제 검사가 다가와요!',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SAHİL',
        en: 'BOARDWALK',
        de: 'STRANDPROMENADE',
        ar: 'الكورنيش',
        fr: 'BORD DE MER',
        es: 'PASEO MARÍTIMO',
        ja: '海辺',
        ko: '해변',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Martı simidine göz dikti',
      en: "A seagull's eyeing your sandwich",
      de: 'Eine Möwe hat dein Brötchen im Visier',
      ar: 'نورس يحدّق في شطيرتك',
      fr: 'Une mouette lorgne ton sandwich',
      es: 'Una gaviota vigila tu sándwich',
      ja: 'カモメがサンドイッチを狙ってる！',
      ko: '갈매기가 샌드위치를 노리고 있어요!',
    },
  },
];
