import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';
import { HANDS_OFF } from './classic';

/** Don't-touch posts that are security camera frames (`cctv`). Append only: a published post keeps its place. */
export const FREEZE_CCTV: readonly Draft[] = [
  {
    emoji: '👦',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YATAK ODASI',
        en: 'BEDROOM',
        de: 'SCHLAFZIMMER',
        ar: 'غرفة النوم',
        fr: 'CHAMBRE',
        es: 'DORMITORIO',
      },
    },
    caption: {
      tr: 'Şarj aleti sende. Kıpırdama.',
      en: "You have it. Don't move.",
      de: 'Du hast es. Keine Bewegung.',
      ar: 'الشاحن معك. لا تتحرك.',
      fr: "C'est toi qui l'as. Bouge pas.",
      es: 'Lo tienes tú. No te muevas.',
    },
    headline: {
      tr: 'Kardeşin şarj aletini arıyor',
      en: "Your brother's looking for his charger",
      de: 'Dein Bruder sucht sein Ladekabel',
      ar: 'أخوك يبحث عن شاحنه',
      fr: 'Ton frère cherche son chargeur',
      es: 'Tu hermano busca su cargador',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇALIŞMA ODASI',
        en: 'STUDY',
        de: 'ARBEITSZIMMER',
        ar: 'غرفة المكتب',
        fr: 'BUREAU',
        es: 'ESTUDIO',
      },
    },
    caption: {
      tr: 'Göz göze gelme.',
      en: "Don't make eye contact.",
      de: 'Kein Blickkontakt.',
      ar: 'لا تنظر في عينيها.',
      fr: 'Évite son regard.',
      es: 'No lo mires a los ojos.',
    },
    headline: {
      tr: 'Kedi kupayı masadan itmek üzere',
      en: "The cat's about to push your mug off",
      de: 'Die Katze schubst deine Tasse zum Rand',
      ar: 'القطة على وشك إسقاط كوبك',
      fr: 'Le chat va faire tomber ta tasse',
      es: 'El gato va a tirar tu taza',
    },
  },
  {
    emoji: '💇',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KUAFÖR',
        en: 'HAIR SALON',
        de: 'FRISEURSALON',
        ar: 'صالون التجميل',
        fr: 'SALON DE COIFFURE',
        es: 'PELUQUERÍA',
      },
    },
    caption: {
      tr: 'Kıpırdarsan kâkül yamuk olur.',
      en: "Move and they'll come out crooked.",
      de: 'Eine Bewegung und er wird schief.',
      ar: 'إن تحركت صارت الغرّة مائلة.',
      fr: 'Un geste et elle sera de travers.',
      es: 'Si te mueves, queda torcido.',
    },
    headline: {
      tr: 'Kuaför kâkülünü kesiyor',
      en: "The stylist's cutting your bangs",
      de: 'Die Friseurin schneidet deinen Pony',
      ar: 'المصففة تقص غرّتك',
      fr: 'La coiffeuse coupe ta frange',
      es: 'Te están cortando el flequillo',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ANTRE',
        en: 'ENTRYWAY',
        de: 'DIELE',
        ar: 'المدخل',
        fr: 'ENTRÉE',
        es: 'ENTRADA',
      },
    },
    caption: {
      tr: 'Uyuyor numarası yap.',
      en: "Pretend you're asleep.",
      de: 'Stell dich schlafend.',
      ar: 'تظاهر بأنك نائم.',
      fr: 'Fais semblant de dormir.',
      es: 'Hazte el dormido.',
    },
    headline: {
      tr: 'Köpek tasmayı getirdi, seni arıyor',
      en: 'The dog brought its leash over',
      de: 'Der Hund hat die Leine im Maul',
      ar: 'الكلب أحضر المقود ويبحث عنك',
      fr: 'Le chien a apporté sa laisse',
      es: 'El perro trajo la correa',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'BAHÇE',
        en: 'BACKYARD',
        de: 'GARTEN',
        ar: 'الحديقة',
        fr: 'JARDIN',
        es: 'JARDÍN',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Saklambaç: ebe tam önünden geçiyor',
      en: "Hide-and-seek: the seeker's right there",
      de: 'Verstecken: Der Sucher steht direkt da',
      ar: 'الغمّيضة: الباحث أمامك تمامًا',
      fr: 'Cache-cache : il passe juste devant toi',
      es: 'Escondite: te buscan justo al lado',
    },
  },
  {
    emoji: '🤫',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KÜTÜPHANE',
        en: 'LIBRARY',
        de: 'BIBLIOTHEK',
        ar: 'المكتبة',
        fr: 'BIBLIOTHÈQUE',
        es: 'BIBLIOTECA',
      },
    },
    caption: {
      tr: 'Sayfa çevirmek bile yasak.',
      en: "Don't even turn a page.",
      de: 'Nicht mal umblättern.',
      ar: 'ولا تقلب صفحة حتى.',
      fr: 'Tourne même pas une page.',
      es: 'Ni se te ocurra pasar la página.',
    },
    headline: {
      tr: 'Kütüphaneci “şşşt” dedi',
      en: 'The librarian just shushed you',
      de: 'Die Bibliothekarin macht „Pssst!“',
      ar: 'أمينة المكتبة طلبت منك الهدوء',
      fr: "La bibliothécaire t'a fait « chut »",
      es: 'La bibliotecaria te pidió silencio',
    },
  },
  {
    emoji: '🎉',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SALON',
        en: 'LIVING ROOM',
        de: 'WOHNZIMMER',
        ar: 'غرفة المعيشة',
        fr: 'SALON',
        es: 'SALA',
      },
    },
    caption: {
      tr: 'Görmedin. Kıpırdama.',
      en: "You saw nothing. Don't move.",
      de: 'Du hast nichts gesehen. Nicht bewegen.',
      ar: 'لم ترَ شيئًا. لا تتحرك.',
      fr: "T'as rien vu. Bouge pas.",
      es: 'No viste nada. No te muevas.',
    },
    headline: {
      tr: 'Sana sürpriz parti hazırlıyorlar',
      en: "They're planning your surprise party",
      de: 'Sie planen deine Überraschungsparty',
      ar: 'يجهّزون لك حفلة مفاجئة',
      fr: 'Ils préparent ta fête surprise',
      es: 'Te preparan una fiesta sorpresa',
    },
  },
  {
    emoji: '🧀',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'MUTFAK',
        en: 'KITCHEN',
        de: 'KÜCHE',
        ar: 'المطبخ',
        fr: 'CUISINE',
        es: 'COCINA',
      },
    },
    caption: {
      tr: 'Belki kimse fark etmez.',
      en: 'Maybe nobody noticed.',
      de: "Vielleicht merkt's keiner.",
      ar: 'ربما لم يلاحظ أحد.',
      fr: "Peut-être que personne n'a vu.",
      es: 'Quizá nadie se dio cuenta.',
    },
    headline: {
      tr: 'Gece 3. Buzdolabı. Işık açık.',
      en: "3 a.m. Fridge. Light's on.",
      de: '3 Uhr nachts. Kühlschrank. Licht an.',
      ar: 'الثالثة فجرًا. الثلاجة. الضوء مضاء.',
      fr: '3 h du mat. Frigo. Lumière allumée.',
      es: '3 de la mañana. Nevera. Luz encendida.',
    },
  },
  {
    emoji: '🧺',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'BALKON',
        en: 'BALCONY',
        de: 'BALKON',
        ar: 'الشرفة',
        fr: 'BALCON',
        es: 'BALCÓN',
      },
    },
    caption: {
      tr: 'Gönüllü olma. Kıpırdama.',
      en: "Don't volunteer. Don't move.",
      de: 'Nicht melden. Nicht bewegen.',
      ar: 'لا تتطوع. لا تتحرك.',
      fr: 'Te porte pas volontaire. Bouge pas.',
      es: 'No te ofrezcas. No te muevas.',
    },
    headline: {
      tr: 'Çamaşır asacak gönüllü aranıyor',
      en: 'Wanted: a volunteer to hang laundry',
      de: 'Wer hilft beim Wäscheaufhängen?',
      ar: 'مطلوب متطوع لنشر الغسيل',
      fr: 'Qui veut étendre le linge ?',
      es: 'Se busca voluntario para tender la ropa',
    },
  },
  {
    emoji: '👴',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'YEMEK ODASI',
        en: 'DINING ROOM',
        de: 'ESSZIMMER',
        ar: 'غرفة الطعام',
        fr: 'SALLE À MANGER',
        es: 'COMEDOR',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Deden “bu telefonlar…” diye başladı',
      en: 'Grandpa just said “these phones…”',
      de: 'Opa fängt an: „Diese Handys…“',
      ar: 'جدّك بدأ يقول: «هذه الهواتف…»',
      fr: 'Papi commence : « ces téléphones… »',
      es: 'El abuelo empezó: «estos teléfonos…»',
    },
  },
  {
    emoji: '⏱️',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SPOR SALONU',
        en: 'GYM',
        de: 'TURNHALLE',
        ar: 'صالة الرياضة',
        fr: 'GYMNASE',
        es: 'GIMNASIO',
      },
    },
    caption: {
      tr: 'Görünmez ol.',
      en: 'Be invisible.',
      de: 'Mach dich unsichtbar.',
      ar: 'كن خفيًّا.',
      fr: 'Fais-toi tout petit.',
      es: 'Hazte invisible.',
    },
    headline: {
      tr: 'Antrenör “bir tur daha” diyecek',
      en: 'Coach is about to say “one more lap”',
      de: 'Gleich heißt es: „Noch eine Runde!“',
      ar: 'المدرب سيقول: «لفّة أخرى»',
      fr: 'Le coach va dire « encore un tour »',
      es: 'El entrenador va a pedir otra vuelta',
    },
  },
  {
    emoji: '🔔',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'KAPI ÖNÜ',
        en: 'FRONT DOOR',
        de: 'HAUSTÜR',
        ar: 'الباب الأمامي',
        fr: "PORTE D'ENTRÉE",
        es: 'PUERTA PRINCIPAL',
      },
    },
    caption: {
      tr: 'Evde kimse yok. Sen de yoksun.',
      en: "Nobody's home. Including you.",
      de: 'Keiner da. Du auch nicht.',
      ar: 'لا أحد في البيت… ولا أنت.',
      fr: 'Y a personne. Toi non plus.',
      es: 'No hay nadie. Tú tampoco.',
    },
    headline: {
      tr: 'Komşu zile bastı',
      en: "The neighbor's at the door",
      de: 'Die Nachbarin klingelt',
      ar: 'الجار يرنّ الجرس',
      fr: 'La voisine sonne à la porte',
      es: 'La vecina tocó el timbre',
    },
  },
  {
    emoji: '📓',
    user: ACCOUNTS.cctv,
    body: {
      format: 'cctv',
      place: {
        tr: 'ÇOCUK ODASI',
        en: "KIDS' ROOM",
        de: 'KINDERZIMMER',
        ar: 'غرفة الأطفال',
        fr: "CHAMBRE D'ENFANT",
        es: 'CUARTO DE NIÑOS',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Ödev kontrolü geliyor',
      en: 'Homework check incoming',
      de: 'Hausaufgaben-Kontrolle im Anmarsch',
      ar: 'تفتيش الواجبات في الطريق',
      fr: 'Contrôle des devoirs en approche',
      es: 'Viene la revisión de la tarea',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.live,
    body: {
      format: 'cctv',
      place: {
        tr: 'SAHİL',
        en: 'BOARDWALK',
        de: 'STRANDPROMENADE',
        ar: 'الكورنيش',
        fr: 'BORD DE MER',
        es: 'PASEO MARÍTIMO',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Martı simidine göz dikti',
      en: "A seagull's eyeing your sandwich",
      de: 'Eine Möwe hat dein Brötchen im Visier',
      ar: 'نورس يحدّق في شطيرتك',
      fr: 'Une mouette lorgne ton sandwich',
      es: 'Una gaviota vigila tu sándwich',
    },
  },
];
