import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';
import { HANDS_OFF } from './classic';

/** Don't-touch posts that are warning signs (`sign`). Append only: a published post keeps its place. */
export const FREEZE_SIGN: readonly Draft[] = [
  {
    emoji: '🎨',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'YAŞ BOYA',
        en: 'WET PAINT',
        de: 'VORSICHT',
        ar: 'دهان جديد',
        fr: 'PEINTURE',
        es: 'RECIÉN PINTADO',
        ja: 'ペンキ塗りたて',
        ko: '페인트 주의',
      },
      small: {
        tr: 'DOKUNMAYINIZ',
        en: "PLEASE DON'T TOUCH",
        de: 'FRISCH GESTRICHEN',
        ar: 'ممنوع اللمس',
        fr: 'FRAÎCHE',
        es: 'NO TOCAR NI APOYARSE',
        ja: 'さわらないでください',
        ko: '손대지 마세요',
      },
    },
    caption: {
      tr: 'Kuruyana kadar bekle.',
      en: 'Wait till it dries.',
      de: 'Warte, bis alles trocken ist.',
      ar: 'انتظر حتى يجف.',
      fr: 'Attends que ça sèche.',
      es: 'Espera a que se seque.',
      ja: '乾くまで待って。',
      ko: '마를 때까지 기다려.',
    },
    headline: {
      tr: 'Ekranın yeni boyandı',
      en: 'Your screen was just painted',
      de: 'Dein Display ist frisch gestrichen',
      ar: 'شاشتك مطلية للتو',
      fr: "Ton écran vient d'être repeint",
      es: 'Tu pantalla está recién pintada',
      ja: '画面、塗りたてです！',
      ko: '화면 방금 칠했어요!',
    },
  },
  {
    emoji: '💤',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'SESSİZ OLUN',
        en: 'QUIET PLEASE',
        de: 'BITTE LEISE',
        ar: 'الهدوء من فضلك',
        fr: 'SILENCE',
        es: 'SILENCIO',
        ja: 'お静かに',
        ko: '조용히',
      },
      small: {
        tr: 'BEBEK UYUYOR',
        en: 'BABY SLEEPING',
        de: 'BABY SCHLÄFT',
        ar: 'الطفل نائم',
        fr: 'BÉBÉ ENDORMI',
        es: 'BEBÉ DURMIENDO',
        ja: '赤ちゃんが寝ています',
        ko: '아기가 자고 있어요',
      },
    },
    caption: {
      tr: 'Çıt yok. Kıpırtı yok.',
      en: 'Not a peep. Not a twitch.',
      de: 'Kein Mucks. Keine Bewegung.',
      ar: 'لا صوت. لا حركة.',
      fr: 'Pas un bruit. Pas un geste.',
      es: 'Ni un ruido. Ni un movimiento.',
      ja: '物音ひとつ立てるな。ピクリとも動くな。',
      ko: '숨소리도 내지 마. 꼼짝도 하지 마.',
    },
    headline: {
      tr: 'Bebek sonunda uyudu',
      en: 'The baby finally fell asleep',
      de: 'Das Baby schläft endlich',
      ar: 'نام الطفل أخيرًا',
      fr: 'Bébé dort enfin',
      es: 'El bebé por fin se durmió',
      ja: 'やっと赤ちゃんが寝た！',
      ko: '아기가 드디어 잠들었어요!',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DOKUNMAYIN',
        en: 'DO NOT TOUCH',
        de: 'HÄNDE WEG',
        ar: 'لا تلمس',
        fr: 'NE PAS TOUCHER',
        es: 'NO TOCAR',
        ja: '手を触れないで',
        ko: '손대지 마시오',
      },
      small: {
        tr: 'MÜZE ESERİ',
        en: 'MUSEUM PIECE',
        de: 'MUSEUMSSTÜCK',
        ar: 'قطعة متحفية',
        fr: "ŒUVRE D'ART",
        es: 'PIEZA DE MUSEO',
        ja: '展示品',
        ko: '전시품',
      },
    },
    caption: {
      tr: 'İlk sen olma.',
      en: "Don't be the first.",
      de: 'Sei nicht der Erste.',
      ar: 'لا تكن الأول.',
      fr: 'Sois pas le premier.',
      es: 'No seas el primero.',
      ja: '最初の一人にならないで。',
      ko: '첫 번째가 되지 마.',
    },
    headline: {
      tr: '400 yıldır kimse dokunmadı',
      en: "Nobody's touched it in 400 years",
      de: 'Seit 400 Jahren unberührt',
      ar: 'لم يلمسها أحد منذ 400 عام',
      fr: "Personne n'y a touché depuis 400 ans",
      es: 'Nadie lo ha tocado en 400 años',
      ja: '400年間、誰もさわってない！',
      ko: '400년 동안 아무도 안 만졌어요!',
    },
  },
  {
    emoji: '🧯',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'ACİL DURUM',
        en: 'EMERGENCY',
        de: 'NOTFALL',
        ar: 'طوارئ',
        fr: 'URGENCE',
        es: 'EMERGENCIA',
        ja: '非常用',
        ko: '비상용',
      },
      small: {
        tr: 'YALNIZCA ACİL DURUMDA',
        en: 'USE ONLY IN AN EMERGENCY',
        de: 'NUR IM NOTFALL BENUTZEN',
        ar: 'في حالات الطوارئ فقط',
        fr: "EN CAS D'URGENCE SEULEMENT",
        es: 'SOLO EN CASO DE EMERGENCIA',
        ja: '非常時以外使用禁止',
        ko: '비상시에만 사용하세요',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Sıkılmak acil durum sayılmaz',
      en: "Boredom isn't an emergency",
      de: 'Langeweile ist kein Notfall',
      ar: 'الملل ليس حالة طارئة',
      fr: "L'ennui n'est pas une urgence",
      es: 'Aburrirse no es una emergencia',
      ja: '退屈は非常事態じゃない！',
      ko: '심심한 건 비상사태가 아니에요!',
    },
  },
  {
    emoji: '🚧',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'ÇALIŞMA VAR',
        en: 'WORK ZONE',
        de: 'BAUSTELLE',
        ar: 'أعمال بناء',
        fr: 'TRAVAUX',
        es: 'OBRAS',
        ja: '工事中',
        ko: '공사 중',
      },
      small: {
        tr: 'YAKLAŞMAYIN',
        en: 'KEEP OUT',
        de: 'ZUTRITT VERBOTEN',
        ar: 'ممنوع الاقتراب',
        fr: 'ACCÈS INTERDIT',
        es: 'PROHIBIDO EL PASO',
        ja: '立入禁止',
        ko: '출입 금지',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Bu post yapım aşamasında',
      en: 'This post is under construction',
      de: 'Dieser Post ist noch im Bau',
      ar: 'هذا المنشور قيد الإنشاء',
      fr: 'Ce post est en travaux',
      es: 'Este post está en construcción',
      ja: 'この投稿は工事中です！',
      ko: '이 게시물은 공사 중이에요!',
    },
  },
  {
    emoji: '🌱',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'ÇİMLERE',
        en: 'KEEP OFF',
        de: 'RASEN',
        ar: 'تنبيه',
        fr: 'PELOUSE',
        es: 'NO PISAR',
        ja: '芝生に',
        ko: '잔디를',
      },
      small: {
        tr: 'BASMAYINIZ',
        en: 'THE GRASS',
        de: 'BETRETEN VERBOTEN',
        ar: 'ممنوع الدوس على العشب',
        fr: 'INTERDITE',
        es: 'EL CÉSPED',
        ja: '入らないでください',
        ko: '밟지 마세요',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Ekrana da basma',
      en: 'That goes for the screen, too',
      de: 'Gilt auch für den Bildschirm',
      ar: 'ولا على الشاشة أيضًا',
      fr: "L'écran aussi, d'ailleurs",
      es: 'Y eso incluye la pantalla',
      ja: '画面にも入らないで！',
      ko: '화면도 밟지 마세요!',
    },
  },
  {
    emoji: '🪣',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DİKKAT',
        en: 'CAUTION',
        de: 'ACHTUNG',
        ar: 'انتبه',
        fr: 'ATTENTION',
        es: 'CUIDADO',
        ja: '注意',
        ko: '주의',
      },
      small: {
        tr: 'ZEMİN ISLAK',
        en: 'WET FLOOR',
        de: 'RUTSCHGEFAHR',
        ar: 'الأرضية مبللة',
        fr: 'SOL GLISSANT',
        es: 'SUELO MOJADO',
        ja: '床がぬれています',
        ko: '바닥 미끄러움',
      },
    },
    caption: {
      tr: 'Tek adım bile atma.',
      en: 'Not one step.',
      de: 'Keinen einzigen Schritt.',
      ar: 'ولا خطوة واحدة.',
      fr: 'Ne fais pas un seul pas.',
      es: 'Ni un paso.',
      ja: '一歩も動くな。',
      ko: '한 발짝도 움직이지 마.',
    },
    headline: {
      tr: 'Yer yeni silindi',
      en: 'The floor was just mopped',
      de: 'Der Boden ist frisch gewischt',
      ar: 'الأرض مُسحت للتو',
      fr: "Le sol vient d'être lavé",
      es: 'Acaban de limpiar el suelo',
      ja: '床、拭いたばかりです！',
      ko: '방금 바닥 닦았어요!',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'DOKUNMA',
        en: 'HANDS OFF',
        de: 'FINGER WEG',
        ar: 'لا تقترب',
        fr: 'PAS TOUCHE',
        es: 'PROHIBIDO',
        ja: '手を出すな',
        ko: '손대지 마',
      },
      small: {
        tr: 'MİSAFİRLER İÇİN',
        en: 'FOR GUESTS ONLY',
        de: 'NUR FÜR GÄSTE',
        ar: 'للضيوف فقط',
        fr: 'RÉSERVÉ AUX INVITÉS',
        es: 'SOLO PARA VISITAS',
        ja: 'お客さん用',
        ko: '손님용',
      },
    },
    caption: {
      tr: 'Bir tane eksilse anlaşılır.',
      en: "One goes missing and they'll know.",
      de: 'Fehlt einer, fällt es auf.',
      ar: 'لو نقصت قطعة واحدة فسيلاحظون.',
      fr: "S'il en manque un, ça se verra.",
      es: 'Si falta una, se van a dar cuenta.',
      ja: '1枚でも減ったらバレる。',
      ko: '하나만 없어져도 다 티 나.',
    },
    headline: {
      tr: 'Kurabiyeler misafir için!',
      en: 'The cookies are for the guests!',
      de: 'Die Kekse sind für die Gäste!',
      ar: 'البسكويت للضيوف!',
      fr: "Les biscuits, c'est pour les invités !",
      es: '¡Las galletas son para las visitas!',
      ja: 'クッキーはお客さん用！',
      ko: '쿠키는 손님용이에요!',
    },
  },
  {
    emoji: '🔋',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'DÜŞÜK PİL',
        en: 'LOW BATTERY',
        de: 'AKKU FAST LEER',
        ar: 'بطارية ضعيفة',
        fr: 'BATTERIE',
        es: 'BATERÍA BAJA',
        ja: '電池残量低下',
        ko: '배터리 부족',
      },
      small: {
        tr: '%1 KALDI',
        en: '1% LEFT',
        de: 'NOCH 1 %',
        ar: 'متبقٍ 1%',
        fr: '1 % RESTANT',
        es: 'QUEDA 1 %',
        ja: '残り1%',
        ko: '1% 남음',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Kıpırdarsan telefon kapanır',
      en: 'Move and your phone dies',
      de: 'Eine Bewegung und der Akku ist leer',
      ar: 'إن تحركت انطفأ الهاتف',
      fr: "Un geste et ton téléphone s'éteint",
      es: 'Si te mueves, se apaga el teléfono',
      ja: '動いたらスマホが切れる！',
      ko: '움직이면 폰 꺼져요!',
    },
  },
  {
    emoji: '🦋',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'KELEBEK EVİ',
        en: 'BUTTERFLIES',
        de: 'SCHMETTERLINGE',
        ar: 'بيت الفراشات',
        fr: 'PAPILLONS',
        es: 'MARIPOSARIO',
        ja: 'チョウの館',
        ko: '나비의 집',
      },
      small: {
        tr: 'YAVAŞ HAREKET EDİN',
        en: 'MOVE SLOWLY',
        de: 'LANGSAM BEWEGEN',
        ar: 'تحرّك ببطء',
        fr: 'EN LIBERTÉ',
        es: 'MOVERSE DESPACIO',
        ja: 'ゆっくり動いてください',
        ko: '천천히 움직이세요',
      },
    },
    caption: {
      tr: 'Heykel ol.',
      en: 'Be a statue.',
      de: 'Sei eine Statue.',
      ar: 'كن تمثالًا.',
      fr: 'Fais la statue.',
      es: 'Sé una estatua.',
      ja: '銅像になれ。',
      ko: '동상처럼 굳어.',
    },
    headline: {
      tr: 'Kelebek eline kondu',
      en: 'A butterfly landed on your hand',
      de: 'Ein Schmetterling sitzt auf deiner Hand',
      ar: 'فراشة حطّت على يدك',
      fr: "Un papillon s'est posé sur ta main",
      es: 'Una mariposa se posó en tu mano',
      ja: 'チョウが手に止まった！',
      ko: '나비가 손에 앉았어요!',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'GÜLÜMSE',
        en: 'SAY CHEESE',
        de: 'LÄCHELN',
        ar: 'ابتسم',
        fr: 'OUISTITI',
        es: 'SONRÍE',
        ja: 'はい、チーズ',
        ko: '김치!',
      },
      small: {
        tr: 'ZAMANLAYICI AÇIK',
        en: 'SELF-TIMER ON',
        de: 'SELBSTAUSLÖSER AN',
        ar: 'المؤقت يعمل',
        fr: 'RETARDATEUR ACTIVÉ',
        es: 'TEMPORIZADOR ACTIVADO',
        ja: 'セルフタイマー作動中',
        ko: '셀프 타이머 작동 중',
      },
    },
    caption: {
      tr: 'Kimse kıpırdamasın!',
      en: 'Nobody move!',
      de: 'Keiner bewegt sich!',
      ar: 'لا أحد يتحرك!',
      fr: 'Personne ne bouge !',
      es: '¡Que nadie se mueva!',
      ja: '誰も動くな！',
      ko: '아무도 움직이지 마!',
    },
    headline: {
      tr: 'Toplu fotoğraf: 3… 2… 1…',
      en: 'Group photo in 3… 2… 1…',
      de: 'Gruppenfoto in 3… 2… 1…',
      ar: 'صورة جماعية بعد 3… 2… 1…',
      fr: 'Photo de groupe dans 3… 2… 1…',
      es: 'Foto grupal en 3… 2… 1…',
      ja: '集合写真まで3…2…1…',
      ko: '단체 사진 3… 2… 1…',
    },
  },
  {
    emoji: '🐢',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'YAVAŞ',
        en: 'SLOW',
        de: 'LANGSAM',
        ar: 'تمهّل',
        fr: 'RALENTIR',
        es: 'DESPACIO',
        ja: '徐行',
        ko: '서행',
      },
      small: {
        tr: 'KAPLUMBAĞA GEÇİDİ',
        en: 'TURTLE CROSSING',
        de: 'SCHILDKRÖTENWECHSEL',
        ar: 'معبر سلاحف',
        fr: 'PASSAGE DE TORTUES',
        es: 'CRUCE DE TORTUGAS',
        ja: 'カメが横断中',
        ko: '거북이 횡단 중',
      },
    },
    caption: {
      tr: 'Bu biraz sürecek.',
      en: 'This might take a while.',
      de: 'Das kann dauern.',
      ar: 'قد يستغرق هذا بعض الوقت.',
      fr: "Ça risque d'être long.",
      es: 'Esto va para largo.',
      ja: 'しばらくかかりそう。',
      ko: '좀 오래 걸릴 듯.',
    },
    headline: {
      tr: 'Kaplumbağa karşıya geçiyor',
      en: "A turtle's crossing the road",
      de: 'Eine Schildkröte überquert die Straße',
      ar: 'سلحفاة تعبر الطريق',
      fr: 'Une tortue traverse la route',
      es: 'Una tortuga cruza la calle',
      ja: 'カメが道を渡っています！',
      ko: '거북이가 길을 건너는 중이에요!',
    },
  },
  {
    emoji: '🍿',
    user: ACCOUNTS.live,
    body: {
      format: 'sign',
      sign: {
        tr: 'FİLM BAŞLADI',
        en: 'NOW SHOWING',
        de: 'FILM LÄUFT',
        ar: 'بدأ العرض',
        fr: 'FILM EN COURS',
        es: 'PROYECCIÓN',
        ja: '上映中',
        ko: '상영 중',
      },
      small: {
        tr: 'TELEFONLARI KAPATIN',
        en: 'PHONES OFF, PLEASE',
        de: 'BITTE HANDYS AUS',
        ar: 'أطفئ هاتفك من فضلك',
        fr: 'TÉLÉPHONES ÉTEINTS',
        es: 'APAGA EL TELÉFONO',
        ja: 'スマホの電源をお切りください',
        ko: '휴대폰 전원을 꺼 주세요',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Karanlıkta tek ışık senin ekranın',
      en: "Your screen's the only light in here",
      de: 'Dein Display ist das einzige Licht',
      ar: 'شاشتك هي الضوء الوحيد هنا',
      fr: 'Ton écran est la seule lumière ici',
      es: 'Tu pantalla es la única luz aquí',
      ja: '暗闇で光ってるのは君の画面だけ',
      ko: '어둠 속에서 화면만 빛나고 있어요',
    },
  },
  {
    emoji: '🐡',
    user: ACCOUNTS.signs,
    body: {
      format: 'sign',
      sign: {
        tr: 'CAMA VURMAYIN',
        en: 'DO NOT TAP',
        de: 'NICHT KLOPFEN',
        ar: 'لا تطرق الزجاج',
        fr: 'NE PAS TAPER',
        es: 'NO GOLPEAR',
        ja: 'ガラスを',
        ko: '유리를',
      },
      small: {
        tr: 'BALIKLAR ÜRKÜYOR',
        en: 'ON THE GLASS',
        de: 'DIE FISCHE ERSCHRECKEN',
        ar: 'الأسماك تخاف',
        fr: 'SUR LA VITRE',
        es: 'EL VIDRIO',
        ja: 'たたかないでください',
        ko: '두드리지 마세요',
      },
    },
    caption: HANDS_OFF,
    headline: {
      tr: 'Balon balığı şişmek üzere',
      en: 'The pufferfish is about to puff up',
      de: 'Der Kugelfisch bläst sich gleich auf',
      ar: 'السمكة المنتفخة على وشك أن تنتفخ',
      fr: 'Le poisson-globe va se gonfler',
      es: 'El pez globo está a punto de inflarse',
      ja: 'フグがふくらみそう！',
      ko: '복어가 부풀기 직전이에요!',
    },
  },
];
