import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Gold posts: a prize on a pedestal (`treasure`). Append only: a published post keeps its place. */
export const HOLD_TREASURE: readonly Draft[] = [
  {
    emoji: '🔌',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Efsanevi eşya: yatağa yetişen şarj kablosu',
      en: 'Legendary item: a charger that reaches the bed',
      de: 'Legendäres Item: ein Ladekabel bis zum Bett',
      ar: 'غرض أسطوري: شاحن يصل سلكه إلى السرير',
      fr: 'Objet légendaire : un chargeur qui atteint le lit',
      es: 'Objeto legendario: un cargador que llega a la cama',
      ja: '伝説のアイテム：ベッドまで届く充電ケーブル',
      ko: '전설의 아이템: 침대까지 닿는 충전 케이블',
    },
  },
  {
    emoji: '🍕',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Son dilim. Senin. Kimse almamış.',
      en: 'The last slice. Yours. Nobody took it.',
      de: "Das letzte Stück. Deins. Keiner hat's genommen.",
      ar: 'آخر قطعة… لك. لم يأخذها أحد.',
      fr: "La dernière part. À toi. Personne l'a prise.",
      es: 'La última porción. Tuya. Nadie la tocó.',
      ja: '最後の1切れ。あなたの分。誰も取らなかった。',
      ko: '마지막 한 조각. 네 거야. 아무도 안 가져갔어.',
    },
  },
  {
    emoji: '🗺️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Hazine haritası: X tam parmağının altında',
      en: 'Treasure map: X marks the spot under your thumb',
      de: 'Schatzkarte: Das X ist genau unter deinem Daumen',
      ar: 'خريطة الكنز: علامة X تحت إصبعك تمامًا',
      fr: 'Carte au trésor : le X est sous ton pouce',
      es: 'Mapa del tesoro: la X está justo bajo tu dedo',
      ja: '宝の地図：Xは親指の真下',
      ko: '보물 지도: X는 바로 네 엄지 아래',
    },
  },
  {
    emoji: '🥚',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Altın yumurta. Günde sadece bir tane.',
      en: 'A golden egg. Only one a day.',
      de: 'Ein goldenes Ei. Nur eins am Tag.',
      ar: 'بيضة ذهبية. واحدة فقط كل يوم.',
      fr: "Un œuf d'or. Un seul par jour.",
      es: 'Un huevo de oro. Solo uno al día.',
      ja: '金の卵。1日1個だけ。',
      ko: '황금알. 하루에 딱 하나.',
    },
  },
  {
    emoji: '🌠',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayan yıldız! Dilek için 1 saniyen var',
      en: "Shooting star! You've got one second to wish",
      de: 'Sternschnuppe! Du hast eine Sekunde für deinen Wunsch',
      ar: 'شهاب! أمامك ثانية واحدة لتتمنى',
      fr: 'Étoile filante ! Une seconde pour faire un vœu',
      es: '¡Estrella fugaz! Tienes un segundo para pedir un deseo',
      ja: '流れ星！願いごとは1秒以内に',
      ko: '별똥별이다! 소원 빌 시간은 1초',
    },
  },
  {
    emoji: '💰',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Geçen kışın montunun cebinden çıktı',
      en: "Found in last winter's coat pocket",
      de: 'Gefunden in der Jackentasche vom letzten Winter',
      ar: 'وجدته في جيب معطف الشتاء الماضي',
      fr: "Trouvé dans la poche du manteau de l'hiver dernier",
      es: 'Apareció en el bolsillo del abrigo del invierno pasado',
      ja: '去年の冬のコートのポケットから出てきた',
      ko: '작년 겨울 코트 주머니에서 나옴',
    },
  },
  {
    emoji: '📶',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Evin tam çeken tek köşesi bulundu',
      en: 'Found: the one corner with full signal',
      de: 'Gefunden: die eine Ecke mit vollem Empfang',
      ar: 'وجدناها: الزاوية الوحيدة ذات الإشارة الكاملة',
      fr: 'Trouvé : le seul coin où ça capte à fond',
      es: 'Encontrado: el único rincón con señal completa',
      ja: '発見：家で唯一電波がフルに立つ場所',
      ko: '발견: 집에서 유일하게 신호 빵빵한 구석',
    },
  },
  {
    emoji: '🥇',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Başparmak şampiyonası: altın madalya senin',
      en: 'Thumb Championship: the gold goes to you',
      de: 'Daumen-Meisterschaft: Gold geht an dich',
      ar: 'بطولة الإبهام: الميدالية الذهبية لك',
      fr: "Championnat du pouce : l'or est pour toi",
      es: 'Campeonato de pulgares: el oro es tuyo',
      ja: '親指選手権：金メダルはあなたに',
      ko: '엄지 챔피언십: 금메달은 너에게',
    },
  },
  {
    emoji: '🦄',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Görenler doğruluyor: gerçek bir tek boynuzlu at',
      en: 'Eyewitnesses confirm: a real unicorn',
      de: 'Augenzeugen bestätigen: ein echtes Einhorn',
      ar: 'شهود عيان يؤكدون: حصان وحيد القرن حقيقي',
      fr: 'Des témoins le confirment : une vraie licorne',
      es: 'Testigos lo confirman: un unicornio de verdad',
      ja: '目撃者多数：本物のユニコーン',
      ko: '목격자들 증언: 진짜 유니콘',
    },
  },
  {
    emoji: '🎁',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kargo geldi ve sen evdeydin!',
      en: 'The package came, and you were home!',
      de: 'Das Paket kam, und du warst zu Hause!',
      ar: 'وصل الطرد وكنت في البيت!',
      fr: 'Le colis est arrivé, et tu étais là !',
      es: '¡Llegó el paquete y estabas en casa!',
      ja: '荷物が届いた、しかも家にいた！',
      ko: '택배 왔는데 마침 집에 있었다!',
    },
  },
  {
    emoji: '🗝️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kayıp anahtar bulundu. Neyi açtığını bilen yok.',
      en: 'Lost key found. Nobody knows what it opens.',
      de: 'Verlorener Schlüssel gefunden. Wofür, weiß keiner.',
      ar: 'عُثر على المفتاح الضائع… ولا أحد يعرف ماذا يفتح',
      fr: "Clé perdue retrouvée. Personne ne sait ce qu'elle ouvre.",
      es: 'Apareció la llave perdida. Nadie sabe qué abre.',
      ja: 'なくした鍵発見。何の鍵かは誰も知らない。',
      ko: '잃어버린 열쇠 찾음. 뭘 여는 건지는 아무도 모름.',
    },
  },
  {
    emoji: '🌈',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Gökkuşağının sonu burası. Altın da burada.',
      en: "End of the rainbow. The gold's right here.",
      de: 'Hier endet der Regenbogen. Das Gold liegt hier.',
      ar: 'هنا ينتهي قوس قزح، والذهب هنا أيضًا',
      fr: "Le bout de l'arc-en-ciel. L'or est juste là.",
      es: 'El final del arcoíris. El oro está aquí.',
      ja: '虹のふもとはここ。金貨もここ。',
      ko: '무지개 끝이 여기야. 금도 여기 있어.',
    },
  },
  {
    emoji: '🔋',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Nadir görüntü: gece yarısı şarj %100',
      en: 'Rare sighting: 100% battery at midnight',
      de: 'Seltener Anblick: 100 % Akku um Mitternacht',
      ar: 'مشهد نادر: البطارية 100% عند منتصف الليل',
      fr: 'Vision rare : 100 % de batterie à minuit',
      es: 'Rareza: batería al 100 % a medianoche',
      ja: '激レア：深夜0時にバッテリー100%',
      ko: '희귀 장면: 자정에 배터리 100%',
    },
  },
  {
    emoji: '🍟',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Poşetin dibinde gizli bir patates daha',
      en: 'A bonus fry at the bottom of the bag',
      de: 'Eine Bonus-Pommes ganz unten in der Tüte',
      ar: 'قطعة بطاطس إضافية مختبئة في قاع الكيس',
      fr: 'Une frite bonus au fond du sachet',
      es: 'Una patata frita extra al fondo de la bolsa',
      ja: '袋の底にボーナスポテト1本',
      ko: '봉투 바닥에 숨은 감자튀김 하나 더',
    },
  },
  {
    emoji: '🎧',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kulaklık kablosu hiç düğümsüz çıktı',
      en: 'Headphone cord came out with zero knots',
      de: 'Kopfhörerkabel ohne einen einzigen Knoten',
      ar: 'خرج سلك السماعات بلا أي عقدة',
      fr: "Câble d'écouteurs sorti sans un seul nœud",
      es: 'El cable de los auriculares salió sin nudos',
      ja: 'イヤホンのコードが一切絡まってなかった',
      ko: '이어폰 줄이 하나도 안 엉킨 채로 나옴',
    },
  },
  {
    emoji: '🌟',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Günün en parlak postu (evet, bu)',
      en: 'Brightest post of the day (yep, this one)',
      de: 'Der hellste Post des Tages (ja, genau der)',
      ar: 'ألمع منشور اليوم (نعم، هذا بالذات)',
      fr: 'Le post le plus brillant du jour (oui, lui)',
      es: 'El post más brillante del día (sí, este)',
      ja: '今日いちばん輝く投稿（そう、これ）',
      ko: '오늘 가장 빛나는 게시물 (응, 이거)',
    },
  },
  {
    emoji: '🔮',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kristal küre diyor ki: daha değil… şimdi!',
      en: 'The crystal ball says: not yet… now!',
      de: 'Die Kristallkugel sagt: noch nicht… jetzt!',
      ar: 'الكرة البلورية تقول: ليس بعد… الآن!',
      fr: 'La boule de cristal dit : pas encore… maintenant !',
      es: 'La bola de cristal dice: todavía no… ¡ahora!',
      ja: '水晶玉のお告げ：まだ…今だ！',
      ko: '수정 구슬이 말하길: 아직… 지금이야!',
    },
  },
  {
    emoji: '🍉',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'İlk seferde tatlı karpuz seçtin',
      en: 'You picked a sweet watermelon on the first try',
      de: 'Beim ersten Versuch eine süße Melone erwischt',
      ar: 'اخترت بطيخة حلوة من أول مرة',
      fr: 'Une pastèque bien sucrée du premier coup',
      es: 'Elegiste una sandía dulce a la primera',
      ja: '一発で甘いスイカを選べた',
      ko: '한 번에 달콤한 수박 골랐다',
    },
  },
  {
    emoji: '🛋️',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Koltuğun en güzel köşesi boş kalmış!',
      en: 'The best spot on the couch is free!',
      de: 'Der beste Platz auf dem Sofa ist frei!',
      ar: 'أفضل مكان على الكنبة ما زال فارغًا!',
      fr: 'La meilleure place du canapé est libre !',
      es: '¡El mejor lugar del sofá está libre!',
      ja: 'ソファの特等席が空いてる！',
      ko: '소파 명당자리가 비어 있다!',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Gizli ödül: +5 dakika uyku',
      en: 'Secret reward: +5 minutes of sleep',
      de: 'Geheime Belohnung: +5 Minuten Schlaf',
      ar: 'مكافأة سرية: 5 دقائق نوم إضافية',
      fr: 'Récompense secrète : +5 minutes de sommeil',
      es: 'Premio secreto: +5 minutos de sueño',
      ja: '隠しごほうび：睡眠+5分',
      ko: '숨은 보상: 잠 +5분',
    },
  },
  {
    emoji: '⭐️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Algoritma bunu sadece sana gösterdi',
      en: 'The algorithm showed this to you alone',
      de: 'Der Algorithmus zeigt das nur dir',
      ar: 'الخوارزمية أظهرت هذا لك وحدك',
      fr: "L'algorithme n'a montré ça qu'à toi",
      es: 'El algoritmo solo te mostró esto a ti',
      ja: 'アルゴリズムがあなただけに見せた投稿',
      ko: '알고리즘이 너한테만 보여준 게시물',
    },
  },
  {
    emoji: '🛒',
    user: ACCOUNTS.jackpot,
    body: { format: 'treasure' },
    caption: {
      tr: 'Kasada sıra yok. Hiç kimse.',
      en: 'No line at the checkout. None.',
      de: 'Keine Schlange an der Kasse. Niemand.',
      ar: 'لا طابور عند الصندوق. ولا شخص واحد.',
      fr: 'Personne à la caisse. Personne.',
      es: 'Nadie en la fila de la caja. Nadie.',
      ja: 'レジに行列ゼロ。誰もいない。',
      ko: '계산대 줄 없음. 한 명도.',
    },
  },
  {
    emoji: '💎',
    user: ACCOUNTS.treasure,
    body: { format: 'treasure' },
    caption: {
      tr: 'Elmas lige giden yol bu posttan geçer',
      en: 'The road to Diamond league runs through here',
      de: 'Der Weg zur Diamant-Liga führt hier entlang',
      ar: 'الطريق إلى دوري الماس يمرّ من هنا',
      fr: 'La route vers la Ligue Diamant passe par ici',
      es: 'El camino a la Liga Diamante pasa por aquí',
      ja: 'ダイヤモンドリーグへの道はこの投稿から',
      ko: '다이아몬드 리그로 가는 길은 이 게시물에서 시작',
    },
  },
  {
    emoji: '🏅',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Katılım madalyası değil. Gerçek madalya.',
      en: 'Not a participation medal. A real one.',
      de: 'Keine Teilnahme-Medaille. Eine echte.',
      ar: 'ليست ميدالية مشاركة… بل ميدالية حقيقية',
      fr: 'Pas une médaille de participation. Une vraie.',
      es: 'No es de participación. Es una medalla de verdad.',
      ja: '参加賞じゃない。本物のメダル。',
      ko: '참가상 아님. 진짜 메달.',
    },
  },
  {
    emoji: '🪄',
    user: ACCOUNTS.gold,
    body: { format: 'treasure' },
    caption: {
      tr: 'Sihirli değnek bu postu altına çevirdi',
      en: 'A magic wand turned this post to gold',
      de: 'Ein Zauberstab hat diesen Post vergoldet',
      ar: 'عصا سحرية حوّلت هذا المنشور إلى ذهب',
      fr: 'Une baguette magique a changé ce post en or',
      es: 'Una varita mágica volvió de oro este post',
      ja: '魔法の杖でこの投稿が金色に',
      ko: '요술봉이 이 게시물을 황금으로 바꿨다',
    },
  },
  {
    emoji: '🏵️',
    user: ACCOUNTS.rare,
    body: { format: 'treasure' },
    caption: {
      tr: 'Bu post bin oyunda bir çıkar',
      en: 'This one drops once in a thousand games',
      de: 'Kommt nur einmal in tausend Spielen',
      ar: 'يظهر مرة واحدة كل ألف مباراة',
      fr: 'Tombe une fois toutes les mille parties',
      es: 'Sale una vez cada mil partidas',
      ja: '1000ゲームに1回しか出ない投稿',
      ko: '1000판에 한 번 나오는 게시물',
    },
  },
];
