import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Friends' posts drawn as a photo of their emoji (`scene`); friends type in lower case. Append only: a published post keeps its place. */
export const LIKE_SCENE: readonly Draft[] = [
  {
    emoji: '🧶',
    user: ACCOUNTS.deniz,
    body: { format: 'scene' },
    caption: {
      tr: 'atkı örecektim, bardak altlığı oldu',
      en: 'was knitting a scarf, made a coaster',
      de: 'sollte ein schal werden, ist ein untersetzer',
      ar: 'كنت أحيك وشاحًا… فصار قاعدة كوب',
      fr: "je tricotais une écharpe, c'est un sous-verre",
      es: 'iba a tejer una bufanda y salió un posavasos',
      ja: 'マフラー編んでたらコースターができた',
      ko: '목도리 뜨다가 컵받침이 됨',
    },
  },
  {
    emoji: '🏅',
    user: ACCOUNTS.kaan,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk 5 km koşumu bitirdim!!',
      en: 'finished my first 5k!!',
      de: 'meine ersten 5 km gelaufen!!',
      ar: 'أنهيت أول جري لي لمسافة 5 كم!!',
      fr: "j'ai couru mes premiers 5 km !!",
      es: '¡¡terminé mis primeros 5 km!!',
      ja: '初めての5km完走！！',
      ko: '첫 5km 완주!!',
    },
  },
  {
    emoji: '🥧',
    user: ACCOUNTS.ayse,
    body: { format: 'scene' },
    caption: {
      tr: 'anneannemin tarifi, benim ellerim',
      en: "grandma's recipe, my hands",
      de: 'omas rezept, meine hände',
      ar: 'وصفة جدتي… بيديّ أنا',
      fr: 'la recette de mamie, faite par moi',
      es: 'receta de la abuela, hecha con mis manos',
      ja: 'おばあちゃんのレシピ、私の手',
      ko: '할머니 레시피, 내 손',
    },
  },
  {
    emoji: '🚲',
    user: ACCOUNTS.emre,
    body: { format: 'scene' },
    caption: {
      tr: 'sonunda bisiklet sürmeyi öğrendim, alkış',
      en: 'finally learned to ride a bike, applause pls',
      de: 'endlich fahrrad fahren gelernt, applaus bitte',
      ar: 'أخيرًا تعلمت ركوب الدراجة، صفّقوا لي',
      fr: "j'ai enfin appris le vélo, applaudissez",
      es: 'por fin aprendí a andar en bici, aplausos',
      ja: 'やっと自転車に乗れた、拍手ください',
      ko: '드디어 자전거 배웠다, 박수 좀',
    },
  },
  {
    emoji: '🏔️',
    user: ACCOUNTS.bora,
    body: { format: 'scene' },
    caption: {
      tr: 'zirvedeyim, manzara her adıma değdi',
      en: 'made it to the top, worth every step',
      de: 'oben angekommen, jeder schritt hat sich gelohnt',
      ar: 'وصلت إلى القمة، والمنظر يستحق كل خطوة',
      fr: 'arrivé au sommet, ça valait chaque pas',
      es: 'llegué a la cima, valió cada paso',
      ja: '山頂到着、一歩一歩の価値あり',
      ko: '정상 도착, 한 걸음 한 걸음이 아깝지 않았다',
    },
  },
  {
    emoji: '🌻',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'balkondaki ilk ayçiçeğim açtı',
      en: 'my first sunflower bloomed on the balcony',
      de: 'meine erste sonnenblume blüht auf dem balkon',
      ar: 'تفتّحت أول زهرة دوّار شمس في شرفتي',
      fr: 'mon premier tournesol a fleuri sur le balcon',
      es: 'floreció mi primer girasol en el balcón',
      ja: 'ベランダで初めてのひまわりが咲いた',
      ko: '베란다에서 첫 해바라기가 피었다',
    },
  },
  {
    emoji: '🎮',
    user: ACCOUNTS.mert,
    body: { format: 'scene' },
    caption: {
      tr: '3 yıldır geçemediğim bölümü geçtim',
      en: "beat the level i've been stuck on for 3 years",
      de: 'das level geschafft, an dem ich 3 jahre hing',
      ar: 'تجاوزت المرحلة التي علقت فيها 3 سنوات',
      fr: 'passé le niveau qui me bloquait depuis 3 ans',
      es: 'pasé el nivel en el que llevaba 3 años atascado',
      ja: '3年間クリアできなかったステージをクリア',
      ko: '3년 동안 못 깬 판을 드디어 깼다',
    },
  },
  {
    emoji: '🐢',
    user: ACCOUNTS.can,
    body: { format: 'scene' },
    caption: {
      tr: 'kaplumbağam bugün 20 yaşında',
      en: 'my turtle turned 20 today',
      de: 'meine schildkröte wird heute 20',
      ar: 'سلحفاتي أتمّت 20 عامًا اليوم',
      fr: "ma tortue a 20 ans aujourd'hui",
      es: 'mi tortuga cumple 20 años hoy',
      ja: 'うちのカメ、今日で20歳',
      ko: '우리 거북이 오늘 20살',
    },
  },
  {
    emoji: '🧩',
    user: ACCOUNTS.elif,
    body: { format: 'scene' },
    caption: {
      tr: '1000 parçalık yapboz bitti. 1 eksik.',
      en: 'finished a 1000-piece puzzle. 1 missing.',
      de: '1000-teile-puzzle fertig. 1 teil fehlt.',
      ar: 'أنهيت أحجية من 1000 قطعة… وتنقصها قطعة',
      fr: 'puzzle de 1000 pièces fini. il en manque 1.',
      es: 'rompecabezas de 1000 piezas listo. falta 1.',
      ja: '1000ピースのパズル完成。1ピース足りない。',
      ko: '1000피스 퍼즐 완성. 1개 없음.',
    },
  },
  {
    emoji: '🚗',
    user: ACCOUNTS.ece,
    body: { format: 'scene' },
    caption: {
      tr: 'ehliyeti aldım! (4. denemede)',
      en: "got my driver's license! (4th try)",
      de: 'führerschein bestanden! (im 4. anlauf)',
      ar: 'حصلت على رخصة القيادة! (من المحاولة الرابعة)',
      fr: 'permis en poche ! (4e tentative)',
      es: '¡aprobé el examen de conducir! (al 4.º intento)',
      ja: '免許取った！（4回目で）',
      ko: '면허 땄다! (4번째 도전)',
    },
  },
  {
    emoji: '🌅',
    user: ACCOUNTS.zeynep,
    body: { format: 'scene' },
    caption: {
      tr: 'sabah 6’da kalktım, sırf bunun için',
      en: 'woke up at 6 a.m. just for this',
      de: 'um 6 uhr aufgestanden, nur dafür',
      ar: 'استيقظت في السادسة صباحًا من أجل هذا فقط',
      fr: 'debout à 6 h rien que pour ça',
      es: 'me levanté a las 6 solo por esto',
      ja: 'これのためだけに朝6時に起きた',
      ko: '이거 보려고 아침 6시에 일어남',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.ipek,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk tablomu sattım!!',
      en: 'sold my first painting!!',
      de: 'mein erstes bild verkauft!!',
      ar: 'بعت أول لوحة لي!!',
      fr: "j'ai vendu mon premier tableau !!",
      es: '¡¡vendí mi primer cuadro!!',
      ja: '初めて絵が売れた！！',
      ko: '처음으로 그림 팔았다!!',
    },
  },
];
