import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Friends' instant photos (`polaroid`); friends type in lower case. Append only: a published post keeps its place. */
export const LIKE_POLAROID: readonly Draft[] = [
  {
    emoji: '🖍️',
    user: ACCOUNTS.ipek,
    body: {
      format: 'polaroid',
      note: {
        tr: 'otoportre',
        en: 'self-portrait',
        de: 'selbstporträt',
        ar: 'بورتريه ذاتي',
        fr: 'autoportrait',
        es: 'autorretrato',
        ja: '自画像',
        ko: '자화상',
      },
    },
    caption: {
      tr: 'kendimi çizdim, hiç benzemedi',
      en: 'drew myself, looks nothing like me',
      de: 'hab mich selbst gemalt, null ähnlichkeit',
      ar: 'رسمت نفسي… ولا تشبهني أبدًا',
      fr: 'je me suis dessinée, aucune ressemblance',
      es: 'me dibujé y no me parezco nada',
      ja: '自分を描いたら別人になった',
      ko: '내 얼굴 그렸는데 하나도 안 닮음',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'aferin oğlum',
        en: 'good boy',
        de: 'braver junge',
        ar: 'أحسنت يا بطل',
        fr: 'bon chien',
        es: 'buen chico',
        ja: 'いい子だね',
        ko: '착하지',
      },
    },
    caption: {
      tr: 'köpeğim otur komutunu öğrendi (bazen)',
      en: 'my dog learned sit (sometimes)',
      de: 'mein hund kann jetzt sitz (manchmal)',
      ar: 'كلبي تعلّم الجلوس (أحيانًا)',
      fr: 'mon chien sait faire assis (parfois)',
      es: 'mi perro ya sabe sentarse (a veces)',
      ja: 'うちの犬がおすわりを覚えた（たまに）',
      ko: '우리 강아지 앉아 배웠음 (가끔)',
    },
  },
  {
    emoji: '🥁',
    user: ACCOUNTS.ali,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni hobi',
        en: 'new hobby',
        de: 'neues hobby',
        ar: 'هواية جديدة',
        fr: 'nouveau hobby',
        es: 'nuevo pasatiempo',
        ja: '新しい趣味',
        ko: '새 취미',
      },
    },
    caption: {
      tr: 'kanka davul aldım, komşular çok mutlu',
      en: 'got a drum kit, the neighbors are thrilled',
      de: 'hab ein schlagzeug, die nachbarn freuen sich',
      ar: 'اشتريت طقم طبول، والجيران في غاية السعادة',
      fr: "j'ai acheté une batterie, les voisins adorent",
      es: 'me compré una batería, los vecinos encantados',
      ja: 'ドラム買った、ご近所さん大喜び',
      ko: '드럼 샀는데 이웃들이 아주 좋아함',
    },
  },
  {
    emoji: '🌵',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni oda arkadaşım',
        en: 'new roommate',
        de: 'neuer mitbewohner',
        ar: 'شريك سكني الجديد',
        fr: 'nouveau coloc',
        es: 'mi nuevo compañero',
        ja: '新しいルームメイト',
        ko: '새 룸메이트',
      },
    },
    caption: {
      tr: 'sarılmayı sevmiyor ama çok iyi biri',
      en: "doesn't like hugs, but he's a sweetheart",
      de: 'mag keine umarmungen, ist aber total lieb',
      ar: 'لا يحب العناق، لكنه طيب جدًا',
      fr: 'il aime pas les câlins, mais il est adorable',
      es: 'no le gustan los abrazos, pero es un amor',
      ja: 'ハグは苦手だけど、根はいいやつ',
      ko: '포옹은 싫어하지만 착한 애야',
    },
  },
  {
    emoji: '🍰',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sürpriz!',
        en: 'surprise!',
        de: 'überraschung!',
        ar: 'مفاجأة!',
        fr: 'surprise !',
        es: '¡sorpresa!',
        ja: 'サプライズ！',
        ko: '서프라이즈!',
      },
    },
    caption: {
      tr: 'anneme pasta yaptım, azıcık yamuk',
      en: "made mom a cake, it's only a little crooked",
      de: 'kuchen für mama, nur ein bisschen schief',
      ar: 'صنعت كعكة لأمي، مائلة قليلًا فقط',
      fr: 'un gâteau pour maman, à peine penché',
      es: 'le hice un pastel a mamá, apenas torcido',
      ja: '母にケーキ作った、ちょっとだけ傾いてる',
      ko: '엄마한테 케이크 만들어 줌, 살짝 기울었음',
    },
  },
  {
    emoji: '🥾',
    user: ACCOUNTS.bora,
    body: {
      format: 'polaroid',
      note: {
        tr: 'emektar botlarım',
        en: 'my trusty boots',
        de: 'meine treuen stiefel',
        ar: 'حذائي الوفي',
        fr: 'mes fidèles chaussures',
        es: 'mis fieles botas',
        ja: '相棒のブーツ',
        ko: '든든한 내 등산화',
      },
    },
    caption: {
      tr: '20 km yürüdük, ayaklarım bana küstü',
      en: "hiked 20 km, my feet aren't speaking to me",
      de: '20 km gewandert, meine füße sind beleidigt',
      ar: 'مشينا 20 كم… وقدماي تخاصمانني',
      fr: '20 km de rando, mes pieds me font la tête',
      es: 'caminamos 20 km y mis pies ya no me hablan',
      ja: '20km歩いたら足が口をきいてくれない',
      ko: '20km 걸었더니 발이 나랑 말을 안 함',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'cam kenarı',
        en: 'window seat',
        de: 'fensterplatz',
        ar: 'مقعد النافذة',
        fr: 'côté hublot',
        es: 'junto a la ventanilla',
        ja: '窓側の席',
        ko: '창가 자리',
      },
    },
    caption: {
      tr: 'ilk uçuşum, bulutlardan gözümü alamadım',
      en: 'first flight ever, just stared at the clouds',
      de: 'mein erster flug, hab nur wolken angestarrt',
      ar: 'أول رحلة طيران لي، لم أرفع عيني عن الغيوم',
      fr: "mon tout premier vol, j'ai fixé les nuages",
      es: 'mi primer vuelo, no dejé de mirar las nubes',
      ja: '初めての飛行機、ずっと雲を見てた',
      ko: '첫 비행, 구름만 계속 봤음',
    },
  },
  {
    emoji: '🎸',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'tek bildiğim akor',
        en: 'the only chord i know',
        de: 'mein einziger akkord',
        ar: 'النغمة الوحيدة التي أعرفها',
        fr: 'mon seul accord',
        es: 'el único acorde que sé',
        ja: '唯一弾けるコード',
        ko: '유일하게 아는 코드',
      },
    },
    caption: {
      tr: 'gitar dersi, 1. hafta',
      en: 'guitar lessons, week 1',
      de: 'gitarrenunterricht, woche 1',
      ar: 'دروس الغيتار، الأسبوع الأول',
      fr: 'cours de guitare, semaine 1',
      es: 'clases de guitarra, semana 1',
      ja: 'ギター教室、1週目',
      ko: '기타 레슨 1주 차',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.mert,
    body: {
      format: 'polaroid',
      note: {
        tr: 'diğerlerini sormayın',
        en: "don't ask about the rest",
        de: 'fragt nicht nach dem rest',
        ar: 'لا تسألوا عن البقية',
        fr: 'on parle pas des autres',
        es: 'no pregunten por el resto',
        ja: '他のは聞かないで',
        ko: '나머진 묻지 마',
      },
    },
    caption: {
      tr: 'kurabiye yaptım, en güzeli bu',
      en: 'baked cookies, this is the best one',
      de: 'plätzchen gebacken, das ist das schönste',
      ar: 'خبزت الكعك، وهذه أجمل واحدة',
      fr: "j'ai fait des biscuits, voici le plus beau",
      es: 'hice galletas, esta es la mejor',
      ja: 'クッキー焼いた、これが一番マシなやつ',
      ko: '쿠키 구웠는데 이게 제일 잘 나온 거',
    },
  },
  {
    emoji: '🪁',
    user: ACCOUNTS.can,
    body: {
      format: 'polaroid',
      note: {
        tr: 'rüzgâr tam',
        en: 'perfect wind',
        de: 'perfekter wind',
        ar: 'الرياح مثالية',
        fr: 'vent parfait',
        es: 'viento perfecto',
        ja: '風、最高',
        ko: '바람 딱 좋음',
      },
    },
    caption: {
      tr: 'uçurtmam 5 dakika havada kaldı, rekor',
      en: 'my kite stayed up 5 whole minutes, a record',
      de: 'mein drachen flog 5 minuten, rekord',
      ar: 'بقيت طائرتي الورقية 5 دقائق في الجو… رقم قياسي',
      fr: 'mon cerf-volant a tenu 5 minutes, record',
      es: 'mi cometa voló 5 minutos, récord',
      ja: '凧が5分も飛んだ、新記録',
      ko: '연이 5분이나 날았음, 신기록',
    },
  },
  {
    emoji: '🌊',
    user: ACCOUNTS.deniz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk kulaç',
        en: 'first stroke',
        de: 'erste bahn',
        ar: 'أول سباحة',
        fr: 'première brasse',
        es: 'primera brazada',
        ja: '初めてのひとかき',
        ko: '첫 헤엄',
      },
    },
    caption: {
      tr: 'yüzmeyi öğrendim, geç olsun güç olmasın',
      en: 'learned to swim. better late than never',
      de: 'schwimmen gelernt. besser spät als nie',
      ar: 'تعلمت السباحة… أن تأتي متأخرًا خير من ألا تأتي',
      fr: "j'ai appris à nager. mieux vaut tard que jamais",
      es: 'aprendí a nadar. más vale tarde que nunca',
      ja: '泳げるようになった。遅くてもゼロよりマシ',
      ko: '수영 배웠다. 늦어도 안 하는 것보단 낫지',
    },
  },
  {
    emoji: '🌈',
    user: ACCOUNTS.ipek,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yağmurdan sonra',
        en: 'after the rain',
        de: 'nach dem regen',
        ar: 'بعد المطر',
        fr: 'après la pluie',
        es: 'después de la lluvia',
        ja: '雨上がり',
        ko: '비 온 뒤',
      },
    },
    caption: {
      tr: 'eve dönerken gördüm, herkes baksın',
      en: 'saw this on my way home, everyone look',
      de: 'auf dem heimweg gesehen, schaut euch das an',
      ar: 'رأيته في طريقي إلى البيت، انظروا جميعًا',
      fr: 'vu en rentrant, regardez-moi ça',
      es: 'lo vi volviendo a casa, miren esto',
      ja: '帰り道に見つけた、みんな見て',
      ko: '집 가는 길에 봤어, 다들 봐봐',
    },
  },
  {
    emoji: '🎳',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bir daha olmaz',
        en: 'never happening again',
        de: 'passiert nie wieder',
        ar: 'لن تتكرر',
        fr: 'ça se reproduira pas',
        es: 'no volverá a pasar',
        ja: '二度とない',
        ko: '두 번은 없음',
      },
    },
    caption: {
      tr: 'hayatımın ilk strike’ı!!',
      en: 'first strike of my life!!',
      de: 'mein allererster strike!!',
      ar: 'أول سترايك في حياتي!!',
      fr: 'mon tout premier strike !!',
      es: '¡¡el primer strike de mi vida!!',
      ja: '人生初のストライク！！',
      ko: '인생 첫 스트라이크!!',
    },
  },
  {
    emoji: '♟️',
    user: ACCOUNTS.ali,
    body: {
      format: 'polaroid',
      note: {
        tr: 'rövanş cumartesi',
        en: 'rematch saturday',
        de: 'revanche am samstag',
        ar: 'مباراة العودة السبت',
        fr: 'revanche samedi',
        es: 'revancha el sábado',
        ja: 'リベンジは土曜',
        ko: '토요일에 재대결',
      },
    },
    caption: {
      tr: 'kanka babamı satrançta ilk kez yendim',
      en: 'beat my dad at chess for the first time',
      de: 'hab papa zum ersten mal im schach besiegt',
      ar: 'هزمت أبي في الشطرنج لأول مرة',
      fr: "j'ai battu mon père aux échecs, une première",
      es: 'le gané a mi papá al ajedrez por primera vez',
      ja: '初めてチェスで父に勝った',
      ko: '처음으로 체스에서 아빠를 이겼다',
    },
  },
  {
    emoji: '🐞',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'minik misafir',
        en: 'tiny visitor',
        de: 'kleiner besuch',
        ar: 'ضيفة صغيرة',
        fr: 'petite visite',
        es: 'pequeña visita',
        ja: '小さなお客さん',
        ko: '작은 손님',
      },
    },
    caption: {
      tr: 'uğur böceği elime kondu, dilek tuttum',
      en: 'a ladybug landed on my hand, made a wish',
      de: 'ein marienkäfer! hab mir was gewünscht',
      ar: 'حطّت دعسوقة على يدي، فتمنيت أمنية',
      fr: "une coccinelle sur ma main, j'ai fait un vœu",
      es: 'una mariquita en mi mano, pedí un deseo',
      ja: 'てんとう虫が手に止まった、願いごとした',
      ko: '무당벌레가 손에 앉아서 소원 빌었음',
    },
  },
  {
    emoji: '🍓',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bahçeden',
        en: 'from the garden',
        de: 'aus dem garten',
        ar: 'من الحديقة',
        fr: 'du jardin',
        es: 'del jardín',
        ja: '庭でとれた',
        ko: '텃밭에서',
      },
    },
    caption: {
      tr: 'kendi çileğimi yetiştirdim (3 tane)',
      en: 'grew my own strawberries (all 3 of them)',
      de: 'eigene erdbeeren gezogen (alle 3)',
      ar: 'زرعت الفراولة بنفسي (3 حبات كاملة)',
      fr: "j'ai fait pousser mes fraises (les 3)",
      es: 'coseché mis propias fresas (las 3)',
      ja: 'いちごを自家栽培した（全部で3個）',
      ko: '딸기 직접 키웠음 (무려 3개)',
    },
  },
  {
    emoji: '🗺️',
    user: ACCOUNTS.bora,
    body: {
      format: 'polaroid',
      note: {
        tr: 'plansız',
        en: 'no plan',
        de: 'ohne plan',
        ar: 'بلا خطة',
        fr: 'sans plan',
        es: 'sin plan',
        ja: 'ノープラン',
        ko: '무계획',
      },
    },
    caption: {
      tr: 'telefonsuz gezdim, en güzel sokağı buldum',
      en: 'no phone, got lost, found the prettiest street',
      de: 'ohne handy verlaufen, schönste straße gefunden',
      ar: 'تهت من دون هاتفي… فوجدت أجمل شارع',
      fr: 'perdu sans téléphone, trouvé la plus belle rue',
      es: 'me perdí sin teléfono y encontré la mejor calle',
      ja: 'スマホなしで迷って、最高の路地を見つけた',
      ko: '폰 없이 헤매다 제일 예쁜 골목 발견',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni komşular',
        en: 'new neighbors',
        de: 'neue nachbarn',
        ar: 'جيران جدد',
        fr: 'nouveaux voisins',
        es: 'vecinos nuevos',
        ja: '新しいご近所さん',
        ko: '새 이웃',
      },
    },
    caption: {
      tr: 'pencereme kuşlar yuva yaptı',
      en: 'birds built a nest on my windowsill',
      de: 'vögel bauen ein nest an meinem fenster',
      ar: 'بنت العصافير عشًّا على نافذتي',
      fr: 'des oiseaux font leur nid à ma fenêtre',
      es: 'unos pájaros hicieron nido en mi ventana',
      ja: '窓辺に鳥が巣を作った',
      ko: '창틀에 새들이 둥지를 틀었다',
    },
  },
  {
    emoji: '🏆',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'şampiyonlar!',
        en: 'champions!',
        de: 'meister!',
        ar: 'أبطال!',
        fr: 'champions !',
        es: '¡campeones!',
        ja: '優勝！',
        ko: '우승!',
      },
    },
    caption: {
      tr: 'mahalle turnuvasını kazandık!!',
      en: 'we won the neighborhood tournament!!',
      de: 'wir haben das turnier im viertel gewonnen!!',
      ar: 'فزنا ببطولة الحي!!',
      fr: 'on a gagné le tournoi du quartier !!',
      es: '¡¡ganamos el torneo del barrio!!',
      ja: '町内大会で優勝した！！',
      ko: '동네 대회 우승했다!!',
    },
  },
  {
    emoji: '🦆',
    user: ACCOUNTS.zeynep,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sabah ekibi',
        en: 'the morning crew',
        de: 'die morgencrew',
        ar: 'فريق الصباح',
        fr: "l'équipe du matin",
        es: 'el equipo de la mañana',
        ja: '朝のメンバー',
        ko: '아침 멤버들',
      },
    },
    caption: {
      tr: 'parktaki ördekler artık beni tanıyor',
      en: 'the ducks at the park know me now',
      de: 'die enten im park kennen mich jetzt',
      ar: 'بطّ الحديقة صار يعرفني',
      fr: 'les canards du parc me reconnaissent',
      es: 'los patos del parque ya me conocen',
      ja: '公園のカモに顔を覚えられた',
      ko: '공원 오리들이 이제 날 알아봄',
    },
  },
  {
    emoji: '🌕',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'dolunay (inanın)',
        en: 'full moon (trust me)',
        de: 'vollmond (ehrlich)',
        ar: 'بدر كامل (صدقوني)',
        fr: 'pleine lune (promis)',
        es: 'luna llena (lo juro)',
        ja: '満月（信じて）',
        ko: '보름달 (믿어줘)',
      },
    },
    caption: {
      tr: 'dolunayı çektim, bir nokta çıktı',
      en: 'took a pic of the full moon, got a tiny dot',
      de: 'vollmond fotografiert, nur ein punkt drauf',
      ar: 'صوّرت البدر… فظهر كنقطة صغيرة',
      fr: "j'ai photographié la pleine lune : un point",
      es: 'foto a la luna llena: salió un puntito',
      ja: '満月を撮ったら小さい点になった',
      ko: '보름달 찍었는데 점 하나 나옴',
    },
  },
  {
    emoji: '📚',
    user: ACCOUNTS.ece,
    body: {
      format: 'polaroid',
      note: {
        tr: 'hedef tamam',
        en: 'goal: done',
        de: 'ziel erreicht',
        ar: 'تحقق الهدف',
        fr: 'objectif atteint',
        es: 'meta cumplida',
        ja: '目標達成',
        ko: '목표 달성',
      },
    },
    caption: {
      tr: 'bu yıl 12 kitap okudum!!',
      en: 'read 12 books this year!!',
      de: 'dieses jahr 12 bücher gelesen!!',
      ar: 'قرأت 12 كتابًا هذا العام!!',
      fr: "j'ai lu 12 livres cette année !!",
      es: '¡¡leí 12 libros este año!!',
      ja: '今年は本を12冊読んだ！！',
      ko: '올해 책 12권 읽었다!!',
    },
  },
];
