import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Friends' posts drawn as a photo of their emoji (`scene`); friends type in lower case. Append only: a published post keeps its place. */
export const LIKE_SCENE: readonly Draft[] = [
  {
    emoji: '🧶',
    user: ACCOUNTS.deniz,
    body: { format: 'scene' },
    caption: {
      tr: 'atkı örecektim, bardak altlığı oldu',
      en: 'was knitting a scarf, made a coaster',
      de: 'sollte ein schal werden, ist ein untersetzer',
      ar: 'كنت أحيك وشاحًا… فصار قاعدة كوب',
      fr: "je tricotais une écharpe, c'est un sous-verre",
      es: 'iba a tejer una bufanda y salió un posavasos',
    },
  },
  {
    emoji: '🏅',
    user: ACCOUNTS.kaan,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk 5 km koşumu bitirdim!!',
      en: 'finished my first 5k!!',
      de: 'meine ersten 5 km gelaufen!!',
      ar: 'أنهيت أول جري لي لمسافة 5 كم!!',
      fr: "j'ai couru mes premiers 5 km !!",
      es: '¡¡terminé mis primeros 5 km!!',
    },
  },
  {
    emoji: '🥧',
    user: ACCOUNTS.ayse,
    body: { format: 'scene' },
    caption: {
      tr: 'anneannemin tarifi, benim ellerim',
      en: "grandma's recipe, my hands",
      de: 'omas rezept, meine hände',
      ar: 'وصفة جدتي… بيديّ أنا',
      fr: 'la recette de mamie, faite par moi',
      es: 'receta de la abuela, hecha con mis manos',
    },
  },
  {
    emoji: '🚲',
    user: ACCOUNTS.emre,
    body: { format: 'scene' },
    caption: {
      tr: 'sonunda bisiklet sürmeyi öğrendim, alkış',
      en: 'finally learned to ride a bike, applause pls',
      de: 'endlich fahrrad fahren gelernt, applaus bitte',
      ar: 'أخيرًا تعلمت ركوب الدراجة، صفّقوا لي',
      fr: "j'ai enfin appris le vélo, applaudissez",
      es: 'por fin aprendí a andar en bici, aplausos',
    },
  },
  {
    emoji: '🏔️',
    user: ACCOUNTS.bora,
    body: { format: 'scene' },
    caption: {
      tr: 'zirvedeyim, manzara her adıma değdi',
      en: 'made it to the top, worth every step',
      de: 'oben angekommen, jeder schritt hat sich gelohnt',
      ar: 'وصلت إلى القمة، والمنظر يستحق كل خطوة',
      fr: 'arrivé au sommet, ça valait chaque pas',
      es: 'llegué a la cima, valió cada paso',
    },
  },
  {
    emoji: '🌻',
    user: ACCOUNTS.selin,
    body: { format: 'scene' },
    caption: {
      tr: 'balkondaki ilk ayçiçeğim açtı',
      en: 'my first sunflower bloomed on the balcony',
      de: 'meine erste sonnenblume blüht auf dem balkon',
      ar: 'تفتّحت أول زهرة دوّار شمس في شرفتي',
      fr: 'mon premier tournesol a fleuri sur le balcon',
      es: 'floreció mi primer girasol en el balcón',
    },
  },
  {
    emoji: '🎮',
    user: ACCOUNTS.mert,
    body: { format: 'scene' },
    caption: {
      tr: '3 yıldır geçemediğim bölümü geçtim',
      en: "beat the level i've been stuck on for 3 years",
      de: 'das level geschafft, an dem ich 3 jahre hing',
      ar: 'تجاوزت المرحلة التي علقت فيها 3 سنوات',
      fr: 'passé le niveau qui me bloquait depuis 3 ans',
      es: 'pasé el nivel en el que llevaba 3 años atascado',
    },
  },
  {
    emoji: '🐢',
    user: ACCOUNTS.can,
    body: { format: 'scene' },
    caption: {
      tr: 'kaplumbağam bugün 20 yaşında',
      en: 'my turtle turned 20 today',
      de: 'meine schildkröte wird heute 20',
      ar: 'سلحفاتي أتمّت 20 عامًا اليوم',
      fr: "ma tortue a 20 ans aujourd'hui",
      es: 'mi tortuga cumple 20 años hoy',
    },
  },
  {
    emoji: '🧩',
    user: ACCOUNTS.elif,
    body: { format: 'scene' },
    caption: {
      tr: '1000 parçalık yapboz bitti. 1 eksik.',
      en: 'finished a 1000-piece puzzle. 1 missing.',
      de: '1000-teile-puzzle fertig. 1 teil fehlt.',
      ar: 'أنهيت أحجية من 1000 قطعة… وتنقصها قطعة',
      fr: 'puzzle de 1000 pièces fini. il en manque 1.',
      es: 'rompecabezas de 1000 piezas listo. falta 1.',
    },
  },
  {
    emoji: '🚗',
    user: ACCOUNTS.ece,
    body: { format: 'scene' },
    caption: {
      tr: 'ehliyeti aldım! (4. denemede)',
      en: "got my driver's license! (4th try)",
      de: 'führerschein bestanden! (im 4. anlauf)',
      ar: 'حصلت على رخصة القيادة! (من المحاولة الرابعة)',
      fr: 'permis en poche ! (4e tentative)',
      es: '¡aprobé el examen de conducir! (al 4.º intento)',
    },
  },
  {
    emoji: '🌅',
    user: ACCOUNTS.zeynep,
    body: { format: 'scene' },
    caption: {
      tr: 'sabah 6’da kalktım, sırf bunun için',
      en: 'woke up at 6 a.m. just for this',
      de: 'um 6 uhr aufgestanden, nur dafür',
      ar: 'استيقظت في السادسة صباحًا من أجل هذا فقط',
      fr: 'debout à 6 h rien que pour ça',
      es: 'me levanté a las 6 solo por esto',
    },
  },
  {
    emoji: '🖼️',
    user: ACCOUNTS.ipek,
    body: { format: 'scene' },
    caption: {
      tr: 'ilk tablomu sattım!!',
      en: 'sold my first painting!!',
      de: 'mein erstes bild verkauft!!',
      ar: 'بعت أول لوحة لي!!',
      fr: "j'ai vendu mon premier tableau !!",
      es: '¡¡vendí mi primer cuadro!!',
    },
  },
];
