import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Friends' instant photos (`polaroid`); friends type in lower case. Append only: a published post keeps its place. */
export const LIKE_POLAROID: readonly Draft[] = [
  {
    emoji: '🖍️',
    user: ACCOUNTS.ipek,
    body: {
      format: 'polaroid',
      note: {
        tr: 'otoportre',
        en: 'self-portrait',
        de: 'selbstporträt',
        ar: 'بورتريه ذاتي',
        fr: 'autoportrait',
        es: 'autorretrato',
      },
    },
    caption: {
      tr: 'kendimi çizdim, hiç benzemedi',
      en: 'drew myself, looks nothing like me',
      de: 'hab mich selbst gemalt, null ähnlichkeit',
      ar: 'رسمت نفسي… ولا تشبهني أبدًا',
      fr: 'je me suis dessinée, aucune ressemblance',
      es: 'me dibujé y no me parezco nada',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'aferin oğlum',
        en: 'good boy',
        de: 'braver junge',
        ar: 'أحسنت يا بطل',
        fr: 'bon chien',
        es: 'buen chico',
      },
    },
    caption: {
      tr: 'köpeğim otur komutunu öğrendi (bazen)',
      en: 'my dog learned sit (sometimes)',
      de: 'mein hund kann jetzt sitz (manchmal)',
      ar: 'كلبي تعلّم الجلوس (أحيانًا)',
      fr: 'mon chien sait faire assis (parfois)',
      es: 'mi perro ya sabe sentarse (a veces)',
    },
  },
  {
    emoji: '🥁',
    user: ACCOUNTS.ali,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni hobi',
        en: 'new hobby',
        de: 'neues hobby',
        ar: 'هواية جديدة',
        fr: 'nouveau hobby',
        es: 'nuevo pasatiempo',
      },
    },
    caption: {
      tr: 'kanka davul aldım, komşular çok mutlu',
      en: 'got a drum kit, the neighbors are thrilled',
      de: 'hab ein schlagzeug, die nachbarn freuen sich',
      ar: 'اشتريت طقم طبول، والجيران في غاية السعادة',
      fr: "j'ai acheté une batterie, les voisins adorent",
      es: 'me compré una batería, los vecinos encantados',
    },
  },
  {
    emoji: '🌵',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni oda arkadaşım',
        en: 'new roommate',
        de: 'neuer mitbewohner',
        ar: 'شريك سكني الجديد',
        fr: 'nouveau coloc',
        es: 'mi nuevo compañero',
      },
    },
    caption: {
      tr: 'sarılmayı sevmiyor ama çok iyi biri',
      en: "doesn't like hugs, but he's a sweetheart",
      de: 'mag keine umarmungen, ist aber total lieb',
      ar: 'لا يحب العناق، لكنه طيب جدًا',
      fr: 'il aime pas les câlins, mais il est adorable',
      es: 'no le gustan los abrazos, pero es un amor',
    },
  },
  {
    emoji: '🍰',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sürpriz!',
        en: 'surprise!',
        de: 'überraschung!',
        ar: 'مفاجأة!',
        fr: 'surprise !',
        es: '¡sorpresa!',
      },
    },
    caption: {
      tr: 'anneme pasta yaptım, azıcık yamuk',
      en: "made mom a cake, it's only a little crooked",
      de: 'kuchen für mama, nur ein bisschen schief',
      ar: 'صنعت كعكة لأمي، مائلة قليلًا فقط',
      fr: 'un gâteau pour maman, à peine penché',
      es: 'le hice un pastel a mamá, apenas torcido',
    },
  },
  {
    emoji: '🥾',
    user: ACCOUNTS.bora,
    body: {
      format: 'polaroid',
      note: {
        tr: 'emektar botlarım',
        en: 'my trusty boots',
        de: 'meine treuen stiefel',
        ar: 'حذائي الوفي',
        fr: 'mes fidèles chaussures',
        es: 'mis fieles botas',
      },
    },
    caption: {
      tr: '20 km yürüdük, ayaklarım bana küstü',
      en: "hiked 20 km, my feet aren't speaking to me",
      de: '20 km gewandert, meine füße sind beleidigt',
      ar: 'مشينا 20 كم… وقدماي تخاصمانني',
      fr: '20 km de rando, mes pieds me font la tête',
      es: 'caminamos 20 km y mis pies ya no me hablan',
    },
  },
  {
    emoji: '✈️',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'cam kenarı',
        en: 'window seat',
        de: 'fensterplatz',
        ar: 'مقعد النافذة',
        fr: 'côté hublot',
        es: 'junto a la ventanilla',
      },
    },
    caption: {
      tr: 'ilk uçuşum, bulutlardan gözümü alamadım',
      en: 'first flight ever, just stared at the clouds',
      de: 'mein erster flug, hab nur wolken angestarrt',
      ar: 'أول رحلة طيران لي، لم أرفع عيني عن الغيوم',
      fr: "mon tout premier vol, j'ai fixé les nuages",
      es: 'mi primer vuelo, no dejé de mirar las nubes',
    },
  },
  {
    emoji: '🎸',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'tek bildiğim akor',
        en: 'the only chord i know',
        de: 'mein einziger akkord',
        ar: 'النغمة الوحيدة التي أعرفها',
        fr: 'mon seul accord',
        es: 'el único acorde que sé',
      },
    },
    caption: {
      tr: 'gitar dersi, 1. hafta',
      en: 'guitar lessons, week 1',
      de: 'gitarrenunterricht, woche 1',
      ar: 'دروس الغيتار، الأسبوع الأول',
      fr: 'cours de guitare, semaine 1',
      es: 'clases de guitarra, semana 1',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.mert,
    body: {
      format: 'polaroid',
      note: {
        tr: 'diğerlerini sormayın',
        en: "don't ask about the rest",
        de: 'fragt nicht nach dem rest',
        ar: 'لا تسألوا عن البقية',
        fr: 'on parle pas des autres',
        es: 'no pregunten por el resto',
      },
    },
    caption: {
      tr: 'kurabiye yaptım, en güzeli bu',
      en: 'baked cookies, this is the best one',
      de: 'plätzchen gebacken, das ist das schönste',
      ar: 'خبزت الكعك، وهذه أجمل واحدة',
      fr: "j'ai fait des biscuits, voici le plus beau",
      es: 'hice galletas, esta es la mejor',
    },
  },
  {
    emoji: '🪁',
    user: ACCOUNTS.can,
    body: {
      format: 'polaroid',
      note: {
        tr: 'rüzgâr tam',
        en: 'perfect wind',
        de: 'perfekter wind',
        ar: 'الرياح مثالية',
        fr: 'vent parfait',
        es: 'viento perfecto',
      },
    },
    caption: {
      tr: 'uçurtmam 5 dakika havada kaldı, rekor',
      en: 'my kite stayed up 5 whole minutes, a record',
      de: 'mein drachen flog 5 minuten, rekord',
      ar: 'بقيت طائرتي الورقية 5 دقائق في الجو… رقم قياسي',
      fr: 'mon cerf-volant a tenu 5 minutes, record',
      es: 'mi cometa voló 5 minutos, récord',
    },
  },
  {
    emoji: '🌊',
    user: ACCOUNTS.deniz,
    body: {
      format: 'polaroid',
      note: {
        tr: 'ilk kulaç',
        en: 'first stroke',
        de: 'erste bahn',
        ar: 'أول سباحة',
        fr: 'première brasse',
        es: 'primera brazada',
      },
    },
    caption: {
      tr: 'yüzmeyi öğrendim, geç olsun güç olmasın',
      en: 'learned to swim. better late than never',
      de: 'schwimmen gelernt. besser spät als nie',
      ar: 'تعلمت السباحة… أن تأتي متأخرًا خير من ألا تأتي',
      fr: "j'ai appris à nager. mieux vaut tard que jamais",
      es: 'aprendí a nadar. más vale tarde que nunca',
    },
  },
  {
    emoji: '🌈',
    user: ACCOUNTS.ipek,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yağmurdan sonra',
        en: 'after the rain',
        de: 'nach dem regen',
        ar: 'بعد المطر',
        fr: 'après la pluie',
        es: 'después de la lluvia',
      },
    },
    caption: {
      tr: 'eve dönerken gördüm, herkes baksın',
      en: 'saw this on my way home, everyone look',
      de: 'auf dem heimweg gesehen, schaut euch das an',
      ar: 'رأيته في طريقي إلى البيت، انظروا جميعًا',
      fr: 'vu en rentrant, regardez-moi ça',
      es: 'lo vi volviendo a casa, miren esto',
    },
  },
  {
    emoji: '🎳',
    user: ACCOUNTS.burak,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bir daha olmaz',
        en: 'never happening again',
        de: 'passiert nie wieder',
        ar: 'لن تتكرر',
        fr: 'ça se reproduira pas',
        es: 'no volverá a pasar',
      },
    },
    caption: {
      tr: 'hayatımın ilk strike’ı!!',
      en: 'first strike of my life!!',
      de: 'mein allererster strike!!',
      ar: 'أول سترايك في حياتي!!',
      fr: 'mon tout premier strike !!',
      es: '¡¡el primer strike de mi vida!!',
    },
  },
  {
    emoji: '♟️',
    user: ACCOUNTS.ali,
    body: {
      format: 'polaroid',
      note: {
        tr: 'rövanş cumartesi',
        en: 'rematch saturday',
        de: 'revanche am samstag',
        ar: 'مباراة العودة السبت',
        fr: 'revanche samedi',
        es: 'revancha el sábado',
      },
    },
    caption: {
      tr: 'kanka babamı satrançta ilk kez yendim',
      en: 'beat my dad at chess for the first time',
      de: 'hab papa zum ersten mal im schach besiegt',
      ar: 'هزمت أبي في الشطرنج لأول مرة',
      fr: "j'ai battu mon père aux échecs, une première",
      es: 'le gané a mi papá al ajedrez por primera vez',
    },
  },
  {
    emoji: '🐞',
    user: ACCOUNTS.selin,
    body: {
      format: 'polaroid',
      note: {
        tr: 'minik misafir',
        en: 'tiny visitor',
        de: 'kleiner besuch',
        ar: 'ضيفة صغيرة',
        fr: 'petite visite',
        es: 'pequeña visita',
      },
    },
    caption: {
      tr: 'uğur böceği elime kondu, dilek tuttum',
      en: 'a ladybug landed on my hand, made a wish',
      de: 'ein marienkäfer! hab mir was gewünscht',
      ar: 'حطّت دعسوقة على يدي، فتمنيت أمنية',
      fr: "une coccinelle sur ma main, j'ai fait un vœu",
      es: 'una mariquita en mi mano, pedí un deseo',
    },
  },
  {
    emoji: '🍓',
    user: ACCOUNTS.ayse,
    body: {
      format: 'polaroid',
      note: {
        tr: 'bahçeden',
        en: 'from the garden',
        de: 'aus dem garten',
        ar: 'من الحديقة',
        fr: 'du jardin',
        es: 'del jardín',
      },
    },
    caption: {
      tr: 'kendi çileğimi yetiştirdim (3 tane)',
      en: 'grew my own strawberries (all 3 of them)',
      de: 'eigene erdbeeren gezogen (alle 3)',
      ar: 'زرعت الفراولة بنفسي (3 حبات كاملة)',
      fr: "j'ai fait pousser mes fraises (les 3)",
      es: 'coseché mis propias fresas (las 3)',
    },
  },
  {
    emoji: '🗺️',
    user: ACCOUNTS.bora,
    body: {
      format: 'polaroid',
      note: {
        tr: 'plansız',
        en: 'no plan',
        de: 'ohne plan',
        ar: 'بلا خطة',
        fr: 'sans plan',
        es: 'sin plan',
      },
    },
    caption: {
      tr: 'telefonsuz gezdim, en güzel sokağı buldum',
      en: 'no phone, got lost, found the prettiest street',
      de: 'ohne handy verlaufen, schönste straße gefunden',
      ar: 'تهت من دون هاتفي… فوجدت أجمل شارع',
      fr: 'perdu sans téléphone, trouvé la plus belle rue',
      es: 'me perdí sin teléfono y encontré la mejor calle',
    },
  },
  {
    emoji: '🐦',
    user: ACCOUNTS.kaan,
    body: {
      format: 'polaroid',
      note: {
        tr: 'yeni komşular',
        en: 'new neighbors',
        de: 'neue nachbarn',
        ar: 'جيران جدد',
        fr: 'nouveaux voisins',
        es: 'vecinos nuevos',
      },
    },
    caption: {
      tr: 'pencereme kuşlar yuva yaptı',
      en: 'birds built a nest on my windowsill',
      de: 'vögel bauen ein nest an meinem fenster',
      ar: 'بنت العصافير عشًّا على نافذتي',
      fr: 'des oiseaux font leur nid à ma fenêtre',
      es: 'unos pájaros hicieron nido en mi ventana',
    },
  },
  {
    emoji: '🏆',
    user: ACCOUNTS.emre,
    body: {
      format: 'polaroid',
      note: {
        tr: 'şampiyonlar!',
        en: 'champions!',
        de: 'meister!',
        ar: 'أبطال!',
        fr: 'champions !',
        es: '¡campeones!',
      },
    },
    caption: {
      tr: 'mahalle turnuvasını kazandık!!',
      en: 'we won the neighborhood tournament!!',
      de: 'wir haben das turnier im viertel gewonnen!!',
      ar: 'فزنا ببطولة الحي!!',
      fr: 'on a gagné le tournoi du quartier !!',
      es: '¡¡ganamos el torneo del barrio!!',
    },
  },
  {
    emoji: '🦆',
    user: ACCOUNTS.zeynep,
    body: {
      format: 'polaroid',
      note: {
        tr: 'sabah ekibi',
        en: 'the morning crew',
        de: 'die morgencrew',
        ar: 'فريق الصباح',
        fr: "l'équipe du matin",
        es: 'el equipo de la mañana',
      },
    },
    caption: {
      tr: 'parktaki ördekler artık beni tanıyor',
      en: 'the ducks at the park know me now',
      de: 'die enten im park kennen mich jetzt',
      ar: 'بطّ الحديقة صار يعرفني',
      fr: 'les canards du parc me reconnaissent',
      es: 'los patos del parque ya me conocen',
    },
  },
  {
    emoji: '🌕',
    user: ACCOUNTS.elif,
    body: {
      format: 'polaroid',
      note: {
        tr: 'dolunay (inanın)',
        en: 'full moon (trust me)',
        de: 'vollmond (ehrlich)',
        ar: 'بدر كامل (صدقوني)',
        fr: 'pleine lune (promis)',
        es: 'luna llena (lo juro)',
      },
    },
    caption: {
      tr: 'dolunayı çektim, bir nokta çıktı',
      en: 'took a pic of the full moon, got a tiny dot',
      de: 'vollmond fotografiert, nur ein punkt drauf',
      ar: 'صوّرت البدر… فظهر كنقطة صغيرة',
      fr: "j'ai photographié la pleine lune : un point",
      es: 'foto a la luna llena: salió un puntito',
    },
  },
  {
    emoji: '📚',
    user: ACCOUNTS.ece,
    body: {
      format: 'polaroid',
      note: {
        tr: 'hedef tamam',
        en: 'goal: done',
        de: 'ziel erreicht',
        ar: 'تحقق الهدف',
        fr: 'objectif atteint',
        es: 'meta cumplida',
      },
    },
    caption: {
      tr: 'bu yıl 12 kitap okudum!!',
      en: 'read 12 books this year!!',
      de: 'dieses jahr 12 bücher gelesen!!',
      ar: 'قرأت 12 كتابًا هذا العام!!',
      fr: "j'ai lu 12 livres cette année !!",
      es: '¡¡leí 12 libros este año!!',
    },
  },
];
