import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are quote cards (`quote`). Append only: a published post keeps its place. */
export const SKIP_QUOTE: readonly Draft[] = [
  {
    emoji: '🎮',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat bir oyun. Ben hâlâ ayarlar menüsündeyim.',
        en: "Life is a game. I'm still in the settings menu.",
        de: 'Das Leben ist ein Spiel. Ich hänge noch im Menü.',
        ar: 'الحياة لعبة، وأنا ما زلت في قائمة الإعدادات.',
        fr: 'La vie est un jeu. Moi, je suis encore dans les réglages.',
        es: 'La vida es un juego. Yo sigo en el menú de ajustes.',
        ja: '人生はゲーム。私はまだ設定画面から出られない。',
        ko: '인생은 게임이다. 난 아직 설정 화면에서 못 나갔다.',
      },
    },
    caption: {
      tr: 'Karakter oluşturma 2 saat sürdü',
      en: 'Character creation took 2 hours',
      de: 'Charaktererstellung: 2 Stunden',
      ar: 'إنشاء الشخصية استغرق ساعتين',
      fr: 'Création du perso : 2 heures',
      es: 'Crear el personaje me llevó 2 horas',
      ja: 'キャラメイクに2時間かかった',
      ko: '캐릭터 커스텀만 2시간 걸림',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.home,
    body: {
      format: 'quote',
      text: {
        tr: 'Kimse mükemmel değildir. Ama kedim çok yakın.',
        en: "Nobody's perfect. But my cat comes close.",
        de: 'Niemand ist perfekt. Aber meine Katze ist nah dran.',
        ar: 'لا أحد كامل. لكن قطتي قريبة جدًا من الكمال.',
        fr: "Personne n'est parfait. Mais mon chat s'en approche.",
        es: 'Nadie es perfecto. Pero mi gato casi.',
        ja: '完璧な人なんていない。でもうちの猫はほぼ完璧。',
        ko: '완벽한 사람은 없다. 하지만 우리 고양이는 거의 완벽하다.',
      },
    },
    caption: {
      tr: 'Tamamen tarafsız bir görüş',
      en: 'A completely unbiased opinion',
      de: 'Völlig objektive Meinung',
      ar: 'رأي محايد تمامًا',
      fr: 'Avis totalement objectif',
      es: 'Opinión totalmente objetiva',
      ja: '完全に中立な意見です',
      ko: '지극히 객관적인 의견임',
    },
  },
  {
    emoji: '🛍️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Hiçbir şey imkânsız değil. — Poşetleri tek seferde taşıyan biri',
        en: 'Nothing is impossible. — Me, carrying all the groceries in one trip',
        de: "Geht nicht, gibt's nicht. — Ich, mit allen Einkaufstüten auf einmal",
        ar: 'لا شيء مستحيل. — شخص يحمل كل أكياس التسوّق دفعة واحدة',
        fr: "Rien n'est impossible. — Moi, toutes les courses en un seul voyage",
        es: 'Nada es imposible. — Yo, cargando todas las bolsas en un solo viaje',
        ja: '不可能なんてない。——買い物袋を一度で全部運ぶ私',
        ko: '불가능은 없다. — 장바구니를 한 번에 다 옮기는 나',
      },
    },
    caption: {
      tr: 'Kollarım uzadı ama değdi',
      en: 'My arms are longer now. Worth it.',
      de: 'Arme 5 cm länger. Hat sich gelohnt.',
      ar: 'ذراعاي طالتا قليلًا، لكنه يستحق',
      fr: 'Mes bras ont rallongé. Ça valait le coup.',
      es: 'Brazos más largos. Valió la pena.',
      ja: '腕が伸びた気がする。後悔はない。',
      ko: '팔이 좀 길어졌지만 후회는 없다',
    },
  },
  {
    emoji: '🦗',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Sessizlik altındır. Esprini gruba attıktan sonra hariç.',
        en: 'Silence is golden. Except after your joke in the group chat.',
        de: 'Schweigen ist Gold. Außer nach deinem Witz im Gruppenchat.',
        ar: 'السكوت من ذهب. إلا بعد نكتتك في المجموعة.',
        fr: "Le silence est d'or. Sauf après ta blague dans le groupe.",
        es: 'El silencio es oro. Menos después de tu chiste en el grupo.',
        ja: '沈黙は金。ただしグループLINEでスベった後は別。',
        ko: '침묵은 금이다. 단톡방에 드립 치고 난 뒤만 빼고.',
      },
    },
    caption: {
      tr: 'Görüldü: 14 kişi',
      en: 'Seen by 14',
      de: 'Gesehen von 14',
      ar: 'شاهدها 14 شخصًا',
      fr: 'Vu par 14 personnes',
      es: 'Visto por 14',
      ja: '既読14',
      ko: '14명 읽음',
    },
  },
  {
    emoji: '🧥',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Görünüşe aldanma. Hele internetten alınan kazağa.',
        en: 'Never trust appearances. Especially a sweater bought online.',
        de: 'Der Schein trügt. Vor allem bei online bestellten Pullis.',
        ar: 'المظاهر خدّاعة. خصوصًا الكنزة التي طلبتها من الإنترنت.',
        fr: "Méfie-toi des apparences. Surtout d'un pull commandé en ligne.",
        es: 'Las apariencias engañan. Sobre todo si compras ropa en línea.',
        ja: '見た目にだまされるな。特にネットで買ったニット。',
        ko: '겉모습에 속지 마라. 특히 인터넷으로 산 니트.',
      },
    },
    caption: {
      tr: 'Fotoğrafta bordoydu',
      en: 'It was burgundy in the photo',
      de: 'Auf dem Foto war er bordeaux',
      ar: 'كان لونها خمريًا في الصورة',
      fr: 'Sur la photo, il était bordeaux',
      es: 'En la foto era color vino',
      ja: '写真ではボルドーだった',
      ko: '사진에선 버건디였음',
    },
  },
  {
    emoji: '⏲️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Sabır acıdır, meyvesi tatlıdır. — Mikrodalgayı bekleyen biri',
        en: 'Good things come to those who wait. — Me, staring at the microwave',
        de: 'Gut Ding will Weile haben. — Ich, vor der Mikrowelle',
        ar: 'الأشياء الجميلة تستحق الانتظار. — شخص ينتظر الميكروويف',
        fr: 'Tout vient à point à qui sait attendre. — Moi, devant le micro-ondes',
        es: 'La paciencia es la madre de la ciencia. — Yo, frente al microondas',
        ja: '待てば海路の日和あり。——電子レンジを見つめる私',
        ko: '기다리면 좋은 날이 온다. — 전자레인지 앞의 나',
      },
    },
    caption: {
      tr: '90 saniye. Bir ömür.',
      en: '90 seconds. Felt like a lifetime.',
      de: '90 Sekunden. Gefühlt ein Leben.',
      ar: '90 ثانية… كأنها عمر كامل',
      fr: '90 secondes. Une éternité.',
      es: '90 segundos. Una eternidad.',
      ja: '90秒。永遠かと思った。',
      ko: '90초. 거의 평생.',
    },
  },
  {
    emoji: '🐌',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Ertelemenin ustasıyım. Bunu sonra kanıtlayacağım.',
        en: "I'm a master of procrastination. I'll prove it later.",
        de: 'Ich bin Meister im Aufschieben. Beweis folgt später.',
        ar: 'أنا خبير في التأجيل. سأثبت ذلك لاحقًا.',
        fr: 'Je suis un maître de la procrastination. Je le prouverai plus tard.',
        es: 'Soy experto en procrastinar. Luego lo demuestro.',
        ja: '先延ばしの達人です。証明はまた今度。',
        ko: '나는 미루기의 달인이다. 증명은 나중에 하겠다.',
      },
    },
    caption: {
      tr: 'Özgeçmişime ekliyorum',
      en: 'Adding this to my resume',
      de: 'Kommt in meinen Lebenslauf',
      ar: 'سأضيفها إلى سيرتي الذاتية',
      fr: "Je l'ajoute à mon CV",
      es: 'Lo pongo en mi currículum',
      ja: '履歴書に書いておく',
      ko: '이력서에 추가함',
    },
  },
  {
    emoji: '🍲',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Teknoloji bizi yakınlaştırdı. — Mutfaktan mesaj atan annem',
        en: 'Technology brings us closer. — Mom, texting me from the kitchen',
        de: 'Technik bringt uns näher. — Mama, die mir aus der Küche schreibt',
        ar: 'التكنولوجيا قرّبت المسافات. — أمي تراسلني من المطبخ',
        fr: "La technologie nous rapproche. — Maman, qui m'écrit depuis la cuisine",
        es: 'La tecnología nos acerca. — Mi mamá, escribiéndome desde la cocina',
        ja: 'テクノロジーは人を近づける。——台所からLINEしてくる母',
        ko: '기술은 우리를 가깝게 한다. — 부엌에서 카톡 보내는 엄마',
      },
    },
    caption: {
      tr: 'Yemek hazırmış',
      en: "Dinner's ready, apparently",
      de: 'Essen ist fertig, heißt es',
      ar: 'يبدو أن الطعام جاهز',
      fr: 'Le dîner est prêt, apparemment',
      es: 'La cena está lista, al parecer',
      ja: 'ごはんできたらしい',
      ko: '밥 다 됐대',
    },
  },
  {
    emoji: '🚗',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayat bir yolculuktur. Benimki trafikte geçiyor.',
        en: 'Life is a journey. Mine is mostly traffic.',
        de: 'Das Leben ist eine Reise. Meine steht im Stau.',
        ar: 'الحياة رحلة. ورحلتي عالقة في الزحام.',
        fr: 'La vie est un voyage. Le mien est dans les bouchons.',
        es: 'La vida es un viaje. El mío está atascado en el tráfico.',
        ja: '人生は旅だ。私の旅はほぼ渋滞。',
        ko: '인생은 여행이다. 내 여행은 대부분 교통체증.',
      },
    },
    caption: {
      tr: 'Sabah 08.30 düşünceleri',
      en: '8:30 a.m. thoughts',
      de: 'Gedanken um 8:30 Uhr',
      ar: 'خواطر الساعة 8:30 صباحًا',
      fr: 'Pensées de 8 h 30',
      es: 'Reflexiones de las 8:30',
      ja: '朝8時半の思考',
      ko: '아침 8시 30분의 생각',
    },
  },
  {
    emoji: '🍅',
    user: ACCOUNTS.food,
    body: {
      format: 'quote',
      text: {
        tr: 'Herkesin bir mücadelesi var. Benimki ketçap şişesiyle.',
        en: 'Everyone has a struggle. Mine is the ketchup bottle.',
        de: 'Jeder hat seinen Kampf. Meiner heißt Ketchupflasche.',
        ar: 'لكلٍّ منا تحدّياته. وتحدّيّ أنا زجاجة الكاتشب.',
        fr: 'Chacun son combat. Le mien : la bouteille de ketchup.',
        es: 'Cada uno tiene su lucha. La mía es con el kétchup.',
        ja: '誰にでも戦いがある。私の相手はケチャップの瓶。',
        ko: '누구에게나 싸움이 있다. 내 상대는 케첩 통이다.',
      },
    },
    caption: {
      tr: 'Ketçap 1, ben 0',
      en: 'Ketchup 1, me 0',
      de: 'Ketchup 1, ich 0',
      ar: 'الكاتشب 1، أنا 0',
      fr: 'Ketchup 1, moi 0',
      es: 'Kétchup 1, yo 0',
      ja: 'ケチャップ1、私0',
      ko: '케첩 1, 나 0',
    },
  },
  {
    emoji: '🛌',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: '7 kez düş, 8 kez kalk. Ya da hiç kalkma, bugün pazar.',
        en: "Fall down seven times, get up eight. Or don't. It's Sunday.",
        de: 'Fall siebenmal hin, steh achtmal auf. Oder bleib liegen: Sonntag.',
        ar: 'اسقط سبع مرات وانهض ثماني. أو لا تنهض، اليوم عطلة.',
        fr: "Tombe sept fois, relève-toi huit. Ou pas : c'est dimanche.",
        es: 'Cáete siete veces, levántate ocho. O no, que es domingo.',
        ja: '七転び八起き。いや、起きなくていい。今日は日曜。',
        ko: '칠전팔기. 아니면 그냥 누워 있자. 오늘은 일요일이다.',
      },
    },
    caption: {
      tr: 'Pazar modu: açık',
      en: 'Sunday mode: on',
      de: 'Sonntagsmodus: an',
      ar: 'وضع العطلة: مُفعّل',
      fr: 'Mode dimanche : activé',
      es: 'Modo domingo: activado',
      ja: '日曜モード：オン',
      ko: '일요일 모드: 켜짐',
    },
  },
  {
    emoji: '🤐',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Bilgi paylaştıkça çoğalır. — Dizinin finalini söyleyen arkadaşım',
        en: 'Knowledge grows when shared. — My friend, who spoiled the finale',
        de: 'Wissen teilen ist schön. — Mein Kumpel, der das Finale verraten hat',
        ar: 'العلم يزداد بالمشاركة. — صديقي الذي حرق نهاية المسلسل',
        fr: "Le savoir se partage. — Mon pote, qui m'a spoilé la fin de la série",
        es: 'El saber se comparte. — Mi amigo, que me contó el final',
        ja: '知識は分け合うほど増える。——ドラマの最終回をネタバレした友だち',
        ko: '지식은 나눌수록 커진다. — 드라마 결말 스포한 친구',
      },
    },
    caption: {
      tr: 'Arkadaşlığımız 2. sezonda bitti',
      en: 'Our friendship got canceled after season 2',
      de: 'Freundschaft nach Staffel 2 abgesetzt',
      ar: 'صداقتنا أُلغيت بعد الموسم الثاني',
      fr: "Notre amitié s'est arrêtée à la saison 2",
      es: 'Nuestra amistad terminó en la temporada 2',
      ja: '友情はシーズン2で打ち切り',
      ko: '우리 우정은 시즌 2에서 조기 종영',
    },
  },
  {
    emoji: '🎨',
    user: ACCOUNTS.food,
    body: {
      format: 'quote',
      text: {
        tr: 'Yemek yapmak bir sanattır. Benimki modern sanat.',
        en: 'Cooking is an art. Mine is modern art.',
        de: 'Kochen ist eine Kunst. Meins ist moderne Kunst.',
        ar: 'الطبخ فن، وطبخي فن تجريدي.',
        fr: "La cuisine est un art. La mienne, c'est de l'art abstrait.",
        es: 'Cocinar es un arte. Lo mío es arte moderno.',
        ja: '料理は芸術だ。私のは現代アート。',
        ko: '요리는 예술이다. 내 요리는 현대미술이다.',
      },
    },
    caption: {
      tr: 'Kimse ne olduğunu anlamadı',
      en: 'Nobody could tell what it was',
      de: 'Keiner wusste, was es sein soll',
      ar: 'لم يعرف أحد ما هو',
      fr: "Personne n'a deviné ce que c'était",
      es: 'Nadie adivinó qué era',
      ja: '何の料理か誰もわからなかった',
      ko: '뭔지 아무도 못 맞힘',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.home,
    body: {
      format: 'quote',
      text: {
        tr: 'Bazı sırlar hiç çözülmez. Mesela lastikli çarşaf nasıl katlanır.',
        en: 'Some mysteries will never be solved. Like folding a fitted sheet.',
        de: 'Manche Rätsel bleiben ungelöst. Zum Beispiel: Spannbettlaken falten.',
        ar: 'بعض الألغاز لا تُحلّ أبدًا. مثل طيّ ملاءة السرير المطاطية.',
        fr: 'Certains mystères restent entiers. Comme plier un drap-housse.',
        es: 'Hay misterios sin resolver. Como doblar una sábana con elástico.',
        ja: '永遠に解けない謎がある。ボックスシーツのたたみ方とか。',
        ko: '풀리지 않는 미스터리도 있다. 매트리스 커버 개는 법처럼.',
      },
    },
    caption: {
      tr: 'Top yapıp dolaba attım',
      en: 'Balled it up and shoved it in the closet',
      de: 'Zusammengeknüllt, ab in den Schrank',
      ar: 'كوّرتها ورميتها في الخزانة',
      fr: 'Roulé en boule, direction le placard',
      es: 'La hice bola y la guardé',
      ja: '丸めて押し入れに突っ込んだ',
      ko: '돌돌 말아서 옷장에 넣어버림',
    },
  },
  {
    emoji: '🦵',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Emek olmadan yemek olmaz. — Bacak gününden sonra merdiven inen biri',
        en: 'No pain, no gain. — Me, taking the stairs after leg day',
        de: 'Ohne Fleiß kein Preis. — Ich, auf der Treppe nach dem Beintag',
        ar: 'لا نجاح بلا ألم. — شخص ينزل الدرج بعد يوم تمارين الساقين',
        fr: "On n'a rien sans rien. — Moi, dans l'escalier après la séance jambes",
        es: 'Sin dolor no hay gloria. — Yo, en la escalera tras el día de pierna',
        ja: '痛みなくして成長なし。——脚トレ翌日に階段を下りる私',
        ko: '고통 없이는 얻는 것도 없다. — 하체 운동 다음 날 계단 내려가는 나',
      },
    },
    caption: {
      tr: 'Asansör de bozukmuş tabii',
      en: "And the elevator's out, of course",
      de: 'Und der Aufzug ist natürlich kaputt',
      ar: 'والمصعد معطّل طبعًا',
      fr: "Et l'ascenseur est en panne, évidemment",
      es: 'Y el ascensor está averiado, claro',
      ja: 'しかもエレベーターは故障中',
      ko: '엘리베이터는 당연히 고장',
    },
  },
  {
    emoji: '☎️',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Gerçek lüks zamandır. — 40 dakikadır bekleme müziği dinleyen ben',
        en: 'Time is the ultimate luxury. — Me, on hold for 40 minutes',
        de: 'Zeit ist der wahre Luxus. — Ich, seit 40 Minuten in der Warteschleife',
        ar: 'الوقت هو الرفاهية الحقيقية. — أنا، أنتظر على الخط منذ 40 دقيقة',
        fr: "Le vrai luxe, c'est le temps. — Moi, en attente depuis 40 minutes",
        es: 'El verdadero lujo es el tiempo. — Yo, en espera desde hace 40 minutos',
        ja: '本当の贅沢は時間だ。——保留音を40分聞いている私',
        ko: '진정한 사치는 시간이다. — 40분째 통화 대기 중인 나',
      },
    },
    caption: {
      tr: 'Müziği ezberledim',
      en: 'I know the hold music by heart',
      de: 'Die Musik kann ich jetzt auswendig',
      ar: 'حفظت الموسيقى عن ظهر قلب',
      fr: 'Je connais la musique par cœur',
      es: 'Ya me sé la música de memoria',
      ja: '保留音、完全に覚えた',
      ko: '대기 음악 다 외웠음',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Asla yorumları okuma. — Yorumları okuyan herkes',
        en: 'Never read the comments. — Everyone who read the comments',
        de: 'Lies niemals die Kommentare. — Alle, die sie gelesen haben',
        ar: 'لا تقرأ التعليقات أبدًا. — كل من قرأ التعليقات',
        fr: 'Ne lis jamais les commentaires. — Tous ceux qui les ont lus',
        es: 'Nunca leas los comentarios. — Todos los que los leyeron',
        ja: 'コメント欄は見るな。——コメント欄を見た全員',
        ko: '댓글은 절대 읽지 마라. — 댓글 읽은 모든 사람',
      },
    },
    caption: {
      tr: 'Tecrübeyle sabit',
      en: 'Learned the hard way',
      de: 'Aus Erfahrung klug',
      ar: 'عن تجربة',
      fr: 'Appris à mes dépens',
      es: 'Lo aprendí por las malas',
      ja: '経験者は語る',
      ko: '경험에서 우러난 조언',
    },
  },
  {
    emoji: '🚏',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayallerinin peşinden koş. Otobüsün peşinden de.',
        en: 'Chase your dreams. And the bus, apparently.',
        de: 'Lauf deinen Träumen hinterher. Und dem Bus.',
        ar: 'اركض خلف أحلامك. وخلف الحافلة أيضًا.',
        fr: 'Cours après tes rêves. Et après le bus.',
        es: 'Persigue tus sueños. Y el bus también.',
        ja: '夢を追いかけろ。ついでにバスも。',
        ko: '꿈을 향해 달려라. 버스를 향해서도.',
      },
    },
    caption: {
      tr: 'İkisini de kaçırdım',
      en: 'Missed both',
      de: 'Beide verpasst',
      ar: 'فاتني الاثنان',
      fr: "J'ai raté les deux",
      es: 'Perdí los dos',
      ja: '両方逃した',
      ko: '둘 다 놓침',
    },
  },
  {
    emoji: '😳',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Tek dokunuş her şeyi değiştirir. — 6 yıllık fotoğrafı beğenen biri',
        en: 'One tap changes everything. — Someone who liked a 6-year-old photo',
        de: 'Ein Tippen ändert alles. — Jemand, der ein altes Foto geliked hat',
        ar: 'لمسة واحدة تغيّر كل شيء. — شخص أعجب بصورة عمرها 6 سنوات',
        fr: "Un tap peut tout changer. — Quelqu'un qui a liké une vieille photo",
        es: 'Un toque lo cambia todo. — Alguien que dio like a una foto vieja',
        ja: 'ワンタップですべてが変わる。——6年前の写真にいいねした人',
        ko: '터치 한 번이 모든 걸 바꾼다. — 6년 전 사진에 좋아요 누른 사람',
      },
    },
    caption: {
      tr: 'Kaza oldu, gerçekten',
      en: 'It was an accident, I promise',
      de: 'War ein Versehen, ehrlich',
      ar: 'كان خطأً، صدقني',
      fr: "C'était un accident, promis",
      es: 'Fue sin querer, lo juro',
      ja: '誤タップです、本当に',
      ko: '손가락이 미끄러졌어요 진짜',
    },
  },
  {
    emoji: '🤔',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Hayatın anlamını düşündüm. Sonra acıktım.',
        en: 'I pondered the meaning of life. Then I got hungry.',
        de: 'Ich dachte über den Sinn des Lebens nach. Dann kam der Hunger.',
        ar: 'فكّرت في معنى الحياة… ثم جعت.',
        fr: "J'ai réfléchi au sens de la vie. Puis j'ai eu faim.",
        es: 'Pensé en el sentido de la vida. Luego me dio hambre.',
        ja: '人生の意味を考えた。そしてお腹がすいた。',
        ko: '인생의 의미를 생각했다. 그리고 배가 고파졌다.',
      },
    },
    caption: {
      tr: 'Derin düşünceler, boş mide',
      en: 'Deep thoughts, empty stomach',
      de: 'Tiefe Gedanken, leerer Magen',
      ar: 'أفكار عميقة ومعدة فارغة',
      fr: 'Pensées profondes, ventre vide',
      es: 'Pensamientos profundos, estómago vacío',
      ja: '深い思考、空っぽの胃',
      ko: '생각은 깊고 배는 비었다',
    },
  },
  {
    emoji: '🚚',
    user: ACCOUNTS.quotes,
    body: {
      format: 'quote',
      text: {
        tr: 'Gerçek dost, taşınma gününde telefonu açandır.',
        en: 'A true friend is the one who picks up on moving day.',
        de: 'Wahre Freunde gehen am Umzugstag ans Telefon.',
        ar: 'الصديق الحقيقي هو من يرد على هاتفه يوم الانتقال.',
        fr: "Le vrai ami, c'est celui qui décroche le jour du déménagement.",
        es: 'Un amigo de verdad contesta el día de la mudanza.',
        ja: '本当の友だちとは、引っ越しの日に電話に出る人のこと。',
        ko: '진짜 친구는 이삿날 전화를 받는 사람이다.',
      },
    },
    caption: {
      tr: 'Telefonu kapalı olanlara selam',
      en: 'Shoutout to everyone whose phone was off',
      de: 'Grüße an alle, deren Handy aus war',
      ar: 'تحية لكل من كان هاتفه مغلقًا',
      fr: 'Coucou aux téléphones éteints',
      es: 'Saludos a los teléfonos apagados',
      ja: '電源オフだったみんな、元気？',
      ko: '그날 폰 꺼놨던 친구들 안부 전함',
    },
  },
  {
    emoji: '🧴',
    user: ACCOUNTS.motivation,
    body: {
      format: 'quote',
      text: {
        tr: 'Bağımsız ol. Sırtına güneş kremi sürmek hariç.',
        en: "Be independent. Except when it's sunscreen on your back.",
        de: 'Sei unabhängig. Außer beim Eincremen deines Rückens.',
        ar: 'كن مستقلًا… إلا عند وضع الكريم على ظهرك.',
        fr: 'Sois indépendant. Sauf pour la crème dans le dos.',
        es: 'Sé independiente. Menos para ponerte crema en la espalda.',
        ja: '自立しよう。背中に日焼け止めを塗るとき以外は。',
        ko: '독립적인 사람이 되자. 등에 선크림 바를 때만 빼고.',
      },
    },
    caption: {
      tr: 'Sırtımda harita çıktı',
      en: "Now there's a map on my back",
      de: 'Auf meinem Rücken: eine Landkarte',
      ar: 'صار على ظهري خريطة',
      fr: "J'ai une carte du monde dans le dos",
      es: 'Ahora tengo un mapa en la espalda',
      ja: '背中に地図ができた',
      ko: '등에 지도가 생김',
    },
  },
];
