import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are lock screens (`notifications`). Append only: a published post keeps its place. */
export const SKIP_NOTIFICATIONS: readonly Draft[] = [
  {
    emoji: '🍋',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🛒',
        app: {
          tr: 'Market siparişi',
          en: 'Grocery order',
          de: 'Supermarkt-App',
          ar: 'طلب البقالة',
          fr: 'Courses en ligne',
          es: 'Súper a domicilio',
          ja: 'ネットスーパー',
          ko: '장보기 주문',
        },
        text: {
          tr: 'Süt kalmamış, yerine 3 limon koyduk',
          en: 'Out of milk, so we added 3 lemons',
          de: 'Milch war aus, dafür 3 Zitronen dabei',
          ar: 'نفد الحليب، فوضعنا 3 ليمونات بدلًا منه',
          fr: 'Plus de lait : on a mis 3 citrons',
          es: 'No había leche, pusimos 3 limones',
          ja: '牛乳が品切れのため、レモン3個にしました',
          ko: '우유가 없어서 레몬 3개를 넣었어요',
        },
      },
    },
    caption: {
      tr: 'Tabii, neredeyse aynı şey',
      en: 'Sure, basically the same thing',
      de: 'Klar, quasi dasselbe',
      ar: 'طبعًا، تقريبًا الشيء نفسه',
      fr: "Bien sûr, c'est presque pareil",
      es: 'Claro, es casi lo mismo',
      ja: 'うん、ほぼ同じだよね',
      ko: '그래, 거의 같은 거지 뭐',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.motivation,
    body: {
      format: 'notifications',
      first: {
        icon: '⌚',
        app: {
          tr: 'Akıllı saat',
          en: 'Smartwatch',
          de: 'Smartwatch',
          ar: 'الساعة الذكية',
          fr: 'Montre connectée',
          es: 'Reloj inteligente',
          ja: 'スマートウォッチ',
          ko: '스마트워치',
        },
        text: {
          tr: 'Kalkma vakti! 5 saattir oturuyorsun',
          en: "Time to stand! You've sat for 5 hours",
          de: 'Zeit aufzustehen! Du sitzt seit 5 Std.',
          ar: 'حان وقت الوقوف! أنت جالس منذ 5 ساعات',
          fr: 'Debout ! Tu es assis depuis 5 h',
          es: '¡Levántate! Llevas 5 horas sentado',
          ja: '立ち上がりましょう！5時間座っています',
          ko: '일어날 시간이에요! 5시간째 앉아 있어요',
        },
      },
    },
    caption: {
      tr: 'Kalktım. Şarj aletini aldım. Oturdum.',
      en: 'Stood up. Grabbed the charger. Sat down.',
      de: 'Aufgestanden. Ladekabel geholt. Hingesetzt.',
      ar: 'وقفت. أخذت الشاحن. جلست.',
      fr: 'Levé. Chargeur récupéré. Rassis.',
      es: 'Me levanté. Tomé el cargador. Me senté.',
      ja: '立った。充電器を取った。座った。',
      ko: '일어났다. 충전기 챙겼다. 앉았다.',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌷',
        app: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
        text: {
          tr: 'Ara beni. Acil değil. Ama hemen.',
          en: 'Call me. Not urgent. But now.',
          de: 'Ruf an. Nicht dringend. Aber sofort.',
          ar: 'اتصل بي. ليس عاجلًا. لكن الآن.',
          fr: 'Appelle-moi. Pas urgent. Mais vite.',
          es: 'Llámame. No es urgente. Pero ya.',
          ja: '電話して。急ぎじゃない。でも今すぐ。',
          ko: '전화해. 급한 건 아니야. 근데 지금.',
        },
      },
    },
    caption: {
      tr: 'Anne dilinde: acil',
      en: 'Translation: urgent',
      de: 'Übersetzt: dringend',
      ar: 'الترجمة: عاجل جدًا',
      fr: 'Traduction : urgent',
      es: 'Traducción: urgente',
      ja: 'お母さん語で「緊急」',
      ko: '엄마 말로 번역하면: 긴급',
    },
  },
  {
    emoji: '🚶',
    user: ACCOUNTS.plain,
    body: {
      format: 'notifications',
      first: {
        icon: '👣',
        app: {
          tr: 'Adım sayar',
          en: 'Step counter',
          de: 'Schrittzähler',
          ar: 'عداد الخطوات',
          fr: 'Podomètre',
          es: 'Podómetro',
          ja: '歩数計',
          ko: '만보기',
        },
        text: {
          tr: 'Tebrikler! Bugün 10.000 adım attın',
          en: 'Congrats! 10,000 steps today',
          de: 'Glückwunsch! Heute 10.000 Schritte',
          ar: 'مبروك! 10,000 خطوة اليوم',
          fr: "Bravo ! 10 000 pas aujourd'hui",
          es: '¡Felicidades! 10.000 pasos hoy',
          ja: 'おめでとう！今日は10,000歩達成',
          ko: '축하해요! 오늘 10,000보 달성',
        },
      },
    },
    caption: {
      tr: 'Tek bir telefon görüşmesi. Volta attım.',
      en: 'One phone call. I paced the whole time.',
      de: 'Ein Telefonat. Ich bin nur hin und her gelaufen.',
      ar: 'مكالمة واحدة… وأنا أذرع البيت',
      fr: "Un seul coup de fil. J'ai fait les cent pas.",
      es: 'Una sola llamada. Caminé de un lado a otro.',
      ja: '電話1本。ずっとウロウロしてた。',
      ko: '통화 한 통. 내내 서성거렸음.',
    },
  },
  {
    emoji: '🗓️',
    user: ACCOUNTS.plain,
    body: {
      format: 'notifications',
      first: {
        icon: '📅',
        app: {
          tr: 'Takvim',
          en: 'Calendar',
          de: 'Kalender',
          ar: 'التقويم',
          fr: 'Agenda',
          es: 'Calendario',
          ja: 'カレンダー',
          ko: '캘린더',
        },
        text: {
          tr: '15 dk sonra: Hiçbir şey yapmama saati',
          en: 'In 15 min: Doing Absolutely Nothing',
          de: 'In 15 Min.: Eine Stunde Nichtstun',
          ar: 'بعد 15 دقيقة: ساعة الكسل الرسمية',
          fr: 'Dans 15 min : ne rien faire (1 h)',
          es: 'En 15 min: una hora de no hacer nada',
          ja: '15分後：何もしない時間',
          ko: '15분 후: 아무것도 안 하기',
        },
      },
    },
    caption: {
      tr: 'Bu toplantıyı hiç kaçırmam',
      en: 'The one meeting I never miss',
      de: 'Der einzige Termin, den ich nie verpasse',
      ar: 'الموعد الوحيد الذي لا أفوّته أبدًا',
      fr: 'Le seul rendez-vous que je rate jamais',
      es: 'La única cita que nunca me pierdo',
      ja: '絶対に欠席しない唯一の会議',
      ko: '절대 빠지지 않는 유일한 회의',
    },
  },
  {
    emoji: '☔',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '☀️',
        app: {
          tr: 'Hava durumu',
          en: 'Weather',
          de: 'Wetter',
          ar: 'الطقس',
          fr: 'Météo',
          es: 'Pronóstico',
          ja: '天気',
          ko: '날씨',
        },
        text: {
          tr: 'Bugün yağış ihtimali %0',
          en: 'Chance of rain today: 0%',
          de: 'Regenwahrscheinlichkeit heute: 0 %',
          ar: 'احتمال المطر اليوم: 0%',
          fr: "Risque de pluie aujourd'hui : 0 %",
          es: 'Probabilidad de lluvia hoy: 0 %',
          ja: '今日の降水確率：0%',
          ko: '오늘 강수 확률 0%',
        },
      },
    },
    caption: {
      tr: 'Bunu sırılsıklam okuyorum',
      en: 'Reading this soaked to the bone',
      de: 'Lese das gerade klatschnass',
      ar: 'أقرأ هذا وأنا مبلل تمامًا',
      fr: "Je lis ça trempé jusqu'aux os",
      es: 'Lo leo empapado de pies a cabeza',
      ja: 'びしょ濡れで読んでます',
      ko: '이걸 흠뻑 젖은 채로 보는 중',
    },
  },
  {
    emoji: '😑',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🕰️',
        app: {
          tr: 'Anılar',
          en: 'Memories',
          de: 'Erinnerungen',
          ar: 'الذكريات',
          fr: 'Souvenirs',
          es: 'Recuerdos',
          ja: '思い出',
          ko: '추억',
        },
        text: {
          tr: '8 yıl önce bugün paylaştın: “sıkıldım”',
          en: '8 years ago today you posted: “bored”',
          de: 'Heute vor 8 Jahren: „mir ist langweilig“',
          ar: 'قبل 8 سنوات نشرت: «أشعر بالملل»',
          fr: "Il y a 8 ans : « je m'ennuie »",
          es: 'Hace 8 años publicaste: “qué aburrido”',
          ja: '8年前の今日の投稿：「ひま」',
          ko: '8년 전 오늘의 게시물: “심심해”',
        },
      },
    },
    caption: {
      tr: 'Güncelleme: hâlâ sıkılıyorum',
      en: 'Update: still bored',
      de: 'Update: Mir ist immer noch langweilig',
      ar: 'تحديث: ما زلت أشعر بالملل',
      fr: "Mise à jour : je m'ennuie toujours",
      es: 'Actualización: sigo aburrido',
      ja: '近況：今もひま',
      ko: '근황: 아직도 심심함',
    },
  },
  {
    emoji: '🔕',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '👪',
        app: {
          tr: 'Aile grubu',
          en: 'Family group',
          de: 'Familiengruppe',
          ar: 'مجموعة العائلة',
          fr: 'Groupe famille',
          es: 'Grupo familiar',
          ja: '家族グループ',
          ko: '가족 단톡방',
        },
        text: {
          tr: 'Babam: Bu grup nasıl sessize alınır?',
          en: 'Dad: How do I mute this group?',
          de: 'Papa: Wie schalte ich die Gruppe stumm?',
          ar: 'أبي: كيف أكتم هذه المجموعة؟',
          fr: 'Papa : comment on coupe les notifs ?',
          es: 'Papá: ¿cómo silencio este grupo?',
          ja: '父：このグループの通知ってどう切るの？',
          ko: '아빠: 이 방 알림 어떻게 끄냐?',
        },
      },
    },
    caption: {
      tr: 'Soruyu nereye sorduğuna bak',
      en: 'And he asked it in the group',
      de: 'Gefragt hat er natürlich in der Gruppe',
      ar: 'وسأل السؤال في المجموعة نفسها',
      fr: 'Question posée… dans le groupe',
      es: 'Y lo preguntó en el grupo',
      ja: 'それをグループで聞く父',
      ko: '그걸 단톡방에 물어보심',
    },
  },
  {
    emoji: '🛵',
    user: ACCOUNTS.food,
    body: {
      format: 'notifications',
      first: {
        icon: '🥡',
        app: {
          tr: 'Yemek siparişi',
          en: 'Food delivery',
          de: 'Essenslieferung',
          ar: 'توصيل الطعام',
          fr: 'Livraison repas',
          es: 'Comida a domicilio',
          ja: 'フードデリバリー',
          ko: '배달 앱',
        },
        text: {
          tr: 'Bu ayki 23. siparişin, afiyet olsun!',
          en: 'Your 23rd order this month. Enjoy!',
          de: 'Deine 23. Bestellung diesen Monat!',
          ar: 'طلبك رقم 23 هذا الشهر، بالهناء والشفاء!',
          fr: 'Ta 23e commande du mois, bon appétit !',
          es: 'Pedido n.º 23 este mes. ¡Buen provecho!',
          ja: '今月23回目のご注文です。ごゆっくり！',
          ko: '이번 달 23번째 주문! 맛있게 드세요',
        },
      },
    },
    caption: {
      tr: 'Mutfağım sadece dekor',
      en: 'My kitchen is just for decoration',
      de: 'Meine Küche ist nur Deko',
      ar: 'مطبخي مجرد ديكور',
      fr: "Ma cuisine, c'est de la déco",
      es: 'Mi cocina es solo decoración',
      ja: 'うちのキッチンはただの飾り',
      ko: '우리 집 주방은 그냥 인테리어',
    },
  },
  {
    emoji: '🧳',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '🛫',
        app: {
          tr: 'Havayolu',
          en: 'Airline',
          de: 'Fluggesellschaft',
          ar: 'شركة الطيران',
          fr: 'Compagnie aérienne',
          es: 'Aerolínea',
          ja: '航空会社',
          ko: '항공사',
        },
        text: {
          tr: 'Uçuşun 7 saat rötarlı',
          en: 'Your flight is delayed 7 hours',
          de: 'Dein Flug hat 7 Stunden Verspätung',
          ar: 'رحلتك متأخرة 7 ساعات',
          fr: 'Ton vol a 7 h de retard',
          es: 'Tu vuelo tiene 7 horas de retraso',
          ja: 'ご搭乗便は7時間遅れています',
          ko: '항공편이 7시간 지연됐어요',
        },
      },
    },
    caption: {
      tr: 'Artık havalimanında yaşıyorum',
      en: 'I live at the airport now',
      de: 'Ich wohne jetzt am Flughafen',
      ar: 'أنا أعيش في المطار الآن',
      fr: "J'habite à l'aéroport maintenant",
      es: 'Ahora vivo en el aeropuerto',
      ja: '空港に住むことにした',
      ko: '이제 공항 주민임',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.home,
    body: {
      format: 'notifications',
      first: {
        icon: '🔖',
        app: {
          tr: 'Okuma takibi',
          en: 'Reading tracker',
          de: 'Lese-Tracker',
          ar: 'متابعة القراءة',
          fr: 'Suivi de lecture',
          es: 'Mis lecturas',
          ja: '読書記録',
          ko: '독서 기록',
        },
        text: {
          tr: 'Aynı sayfada 43. günün',
          en: 'Day 43 on the same page',
          de: 'Tag 43 auf derselben Seite',
          ar: 'اليوم 43 على الصفحة نفسها',
          fr: '43e jour sur la même page',
          es: 'Día 43 en la misma página',
          ja: '同じページで43日目です',
          ko: '같은 페이지 43일째예요',
        },
      },
    },
    caption: {
      tr: 'Çok sürükleyici bir sayfa',
      en: "It's a really gripping page",
      de: 'Ist halt eine spannende Seite',
      ar: 'إنها صفحة مشوّقة جدًا',
      fr: "C'est une page très prenante",
      es: 'Es una página apasionante',
      ja: 'すごく引き込まれるページなんです',
      ko: '엄청 몰입되는 페이지라서',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🔥',
        app: {
          tr: 'Dil dersi',
          en: 'Language app',
          de: 'Sprach-App',
          ar: 'تعلّم اللغات',
          fr: 'Appli de langues',
          es: 'App de idiomas',
          ja: '語学アプリ',
          ko: '외국어 앱',
        },
        text: {
          tr: 'Günlük seri sıfırlandı. Rekor: 1 gün',
          en: 'Streak lost. Your record: 1 day',
          de: 'Serie verloren. Rekord: 1 Tag',
          ar: 'انتهت سلسلتك. رقمك القياسي: يوم واحد',
          fr: 'Série perdue. Ton record : 1 jour',
          es: 'Perdiste tu racha. Récord: 1 día',
          ja: '連続記録が途切れました。最長：1日',
          ko: '연속 기록이 끊겼어요. 최고: 1일',
        },
      },
    },
    caption: {
      tr: 'Kısa ama güzel bir seriydi',
      en: 'It was short, but it was beautiful',
      de: 'Kurz, aber schön war sie',
      ar: 'كانت قصيرة لكنها جميلة',
      fr: "C'était court, mais c'était beau",
      es: 'Fue corta, pero bonita',
      ja: '短いけど美しい記録だった',
      ko: '짧았지만 아름다운 기록이었다',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌙',
        app: { tr: 'Uyku', en: 'Sleep', de: 'Schlaf', ar: 'النوم', fr: 'Sommeil', es: 'Sueño', ja: '睡眠', ko: '수면' },
        text: {
          tr: 'Yatakta 8 saat, uykuda 3 saat',
          en: '8 hours in bed, 3 hours asleep',
          de: '8 Std. im Bett, 3 Std. geschlafen',
          ar: '8 ساعات في السرير، 3 ساعات نوم',
          fr: '8 h au lit, 3 h de sommeil',
          es: '8 h en la cama, 3 h de sueño',
          ja: 'ベッドで8時間、睡眠3時間',
          ko: '침대에서 8시간, 수면 3시간',
        },
      },
    },
    caption: {
      tr: 'Kalan 5 saat: kaydırma',
      en: 'The other 5 hours: scrolling',
      de: 'Die restlichen 5 Stunden: scrollen',
      ar: 'الساعات الخمس الباقية: تصفّح',
      fr: 'Les 5 autres heures : scroll',
      es: 'Las otras 5 horas: deslizando',
      ja: '残りの5時間：スクロール',
      ko: '나머지 5시간: 스크롤',
    },
  },
  {
    emoji: '🤖',
    user: ACCOUNTS.home,
    body: {
      format: 'notifications',
      first: {
        icon: '🧹',
        app: {
          tr: 'Robot süpürge',
          en: 'Robot vacuum',
          de: 'Saugroboter',
          ar: 'المكنسة الذكية',
          fr: 'Robot aspirateur',
          es: 'Robot aspiradora',
          ja: 'ロボット掃除機',
          ko: '로봇청소기',
        },
        text: {
          tr: 'Yine koltuğun altında sıkıştım',
          en: 'Stuck under the couch again',
          de: 'Stecke wieder unterm Sofa fest',
          ar: 'علقت تحت الأريكة مجددًا',
          fr: 'Encore coincé sous le canapé',
          es: 'Otra vez atascado bajo el sofá',
          ja: 'またソファの下で動けなくなりました',
          ko: '또 소파 밑에 끼었어요',
        },
      },
    },
    caption: {
      tr: 'Kurtarma operasyonu, 12. gün',
      en: 'Rescue mission, day 12',
      de: 'Rettungseinsatz, Tag 12',
      ar: 'عملية إنقاذ، اليوم 12',
      fr: 'Mission sauvetage, jour 12',
      es: 'Misión de rescate, día 12',
      ja: '救出作戦、12日目',
      ko: '구조 작전 12일째',
    },
  },
  {
    emoji: '📧',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '✉️',
        app: { tr: 'E-posta', en: 'Mail', de: 'E-Mail', ar: 'البريد', fr: 'E-mail', es: 'Correo', ja: 'メール', ko: '메일' },
        text: {
          tr: '“Herkese yanıtla” ile 38 yeni e-posta',
          en: '38 new emails, all “Reply All”',
          de: '38 neue Mails, alle „Allen antworten“',
          ar: '38 رسالة جديدة، كلها «رد على الكل»',
          fr: '38 mails en « Répondre à tous »',
          es: '38 correos de “Responder a todos”',
          ja: '「全員に返信」で新着メール38件',
          ko: '“전체 답장”으로 새 메일 38개',
        },
      },
    },
    caption: {
      tr: 'Biri şunu durdursun lütfen',
      en: 'Somebody please make it stop',
      de: 'Kann das bitte jemand stoppen?',
      ar: 'أرجوكم، فليوقف أحدٌ هذا',
      fr: "Que quelqu'un arrête ça, pitié",
      es: 'Que alguien lo detenga, por favor',
      ja: '誰か止めてください',
      ko: '제발 누가 좀 멈춰 줘',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.trends,
    body: {
      format: 'notifications',
      first: {
        icon: '👤',
        app: {
          tr: 'Takipçiler',
          en: 'Followers',
          de: 'Follower',
          ar: 'المتابعون',
          fr: 'Abonnés',
          es: 'Seguidores',
          ja: 'フォロワー',
          ko: '팔로워',
        },
        text: {
          tr: 'Annen seni takip etmeye başladı',
          en: 'Your mom started following you',
          de: 'Deine Mama folgt dir jetzt',
          ar: 'والدتك بدأت متابعتك',
          fr: "Ta mère s'est abonnée à ton compte",
          es: 'Tu mamá empezó a seguirte',
          ja: 'お母さんがあなたをフォローしました',
          ko: '엄마가 회원님을 팔로우하기 시작했어요',
        },
      },
    },
    caption: {
      tr: 'Hesabı temizleme vakti',
      en: 'Time to clean up my profile',
      de: 'Zeit, mein Profil aufzuräumen',
      ar: 'حان وقت ترتيب حسابي',
      fr: "L'heure du grand ménage sur mon profil",
      es: 'Hora de limpiar mi perfil',
      ja: 'プロフィールを大掃除する時が来た',
      ko: '계정 대청소할 시간',
    },
  },
];
