import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are lock screens (`notifications`). Append only: a published post keeps its place. */
export const SKIP_NOTIFICATIONS: readonly Draft[] = [
  {
    emoji: '🍋',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🛒',
        app: {
          tr: 'Market siparişi',
          en: 'Grocery order',
          de: 'Supermarkt-App',
          ar: 'طلب البقالة',
          fr: 'Courses en ligne',
          es: 'Súper a domicilio',
        },
        text: {
          tr: 'Süt kalmamış, yerine 3 limon koyduk',
          en: 'Out of milk, so we added 3 lemons',
          de: 'Milch war aus, dafür 3 Zitronen dabei',
          ar: 'نفد الحليب، فوضعنا 3 ليمونات بدلًا منه',
          fr: 'Plus de lait : on a mis 3 citrons',
          es: 'No había leche, pusimos 3 limones',
        },
      },
    },
    caption: {
      tr: 'Tabii, neredeyse aynı şey',
      en: 'Sure, basically the same thing',
      de: 'Klar, quasi dasselbe',
      ar: 'طبعًا، تقريبًا الشيء نفسه',
      fr: "Bien sûr, c'est presque pareil",
      es: 'Claro, es casi lo mismo',
    },
  },
  {
    emoji: '🪑',
    user: ACCOUNTS.motivation,
    body: {
      format: 'notifications',
      first: {
        icon: '⌚',
        app: {
          tr: 'Akıllı saat',
          en: 'Smartwatch',
          de: 'Smartwatch',
          ar: 'الساعة الذكية',
          fr: 'Montre connectée',
          es: 'Reloj inteligente',
        },
        text: {
          tr: 'Kalkma vakti! 5 saattir oturuyorsun',
          en: "Time to stand! You've sat for 5 hours",
          de: 'Zeit aufzustehen! Du sitzt seit 5 Std.',
          ar: 'حان وقت الوقوف! أنت جالس منذ 5 ساعات',
          fr: 'Debout ! Tu es assis depuis 5 h',
          es: '¡Levántate! Llevas 5 horas sentado',
        },
      },
    },
    caption: {
      tr: 'Kalktım. Şarj aletini aldım. Oturdum.',
      en: 'Stood up. Grabbed the charger. Sat down.',
      de: 'Aufgestanden. Ladekabel geholt. Hingesetzt.',
      ar: 'وقفت. أخذت الشاحن. جلست.',
      fr: 'Levé. Chargeur récupéré. Rassis.',
      es: 'Me levanté. Tomé el cargador. Me senté.',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌷',
        app: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
        text: {
          tr: 'Ara beni. Acil değil. Ama hemen.',
          en: 'Call me. Not urgent. But now.',
          de: 'Ruf an. Nicht dringend. Aber sofort.',
          ar: 'اتصل بي. ليس عاجلًا. لكن الآن.',
          fr: 'Appelle-moi. Pas urgent. Mais vite.',
          es: 'Llámame. No es urgente. Pero ya.',
        },
      },
    },
    caption: {
      tr: 'Anne dilinde: acil',
      en: 'Translation: urgent',
      de: 'Übersetzt: dringend',
      ar: 'الترجمة: عاجل جدًا',
      fr: 'Traduction : urgent',
      es: 'Traducción: urgente',
    },
  },
  {
    emoji: '🚶',
    user: ACCOUNTS.plain,
    body: {
      format: 'notifications',
      first: {
        icon: '👣',
        app: {
          tr: 'Adım sayar',
          en: 'Step counter',
          de: 'Schrittzähler',
          ar: 'عداد الخطوات',
          fr: 'Podomètre',
          es: 'Podómetro',
        },
        text: {
          tr: 'Tebrikler! Bugün 10.000 adım attın',
          en: 'Congrats! 10,000 steps today',
          de: 'Glückwunsch! Heute 10.000 Schritte',
          ar: 'مبروك! 10,000 خطوة اليوم',
          fr: "Bravo ! 10 000 pas aujourd'hui",
          es: '¡Felicidades! 10.000 pasos hoy',
        },
      },
    },
    caption: {
      tr: 'Tek bir telefon görüşmesi. Volta attım.',
      en: 'One phone call. I paced the whole time.',
      de: 'Ein Telefonat. Ich bin nur hin und her gelaufen.',
      ar: 'مكالمة واحدة… وأنا أذرع البيت',
      fr: "Un seul coup de fil. J'ai fait les cent pas.",
      es: 'Una sola llamada. Caminé de un lado a otro.',
    },
  },
  {
    emoji: '🗓️',
    user: ACCOUNTS.plain,
    body: {
      format: 'notifications',
      first: {
        icon: '📅',
        app: {
          tr: 'Takvim',
          en: 'Calendar',
          de: 'Kalender',
          ar: 'التقويم',
          fr: 'Agenda',
          es: 'Calendario',
        },
        text: {
          tr: '15 dk sonra: Hiçbir şey yapmama saati',
          en: 'In 15 min: Doing Absolutely Nothing',
          de: 'In 15 Min.: Eine Stunde Nichtstun',
          ar: 'بعد 15 دقيقة: ساعة الكسل الرسمية',
          fr: 'Dans 15 min : ne rien faire (1 h)',
          es: 'En 15 min: una hora de no hacer nada',
        },
      },
    },
    caption: {
      tr: 'Bu toplantıyı hiç kaçırmam',
      en: 'The one meeting I never miss',
      de: 'Der einzige Termin, den ich nie verpasse',
      ar: 'الموعد الوحيد الذي لا أفوّته أبدًا',
      fr: 'Le seul rendez-vous que je rate jamais',
      es: 'La única cita que nunca me pierdo',
    },
  },
  {
    emoji: '☔',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '☀️',
        app: {
          tr: 'Hava durumu',
          en: 'Weather',
          de: 'Wetter',
          ar: 'الطقس',
          fr: 'Météo',
          es: 'Pronóstico',
        },
        text: {
          tr: 'Bugün yağış ihtimali %0',
          en: 'Chance of rain today: 0%',
          de: 'Regenwahrscheinlichkeit heute: 0 %',
          ar: 'احتمال المطر اليوم: 0%',
          fr: "Risque de pluie aujourd'hui : 0 %",
          es: 'Probabilidad de lluvia hoy: 0 %',
        },
      },
    },
    caption: {
      tr: 'Bunu sırılsıklam okuyorum',
      en: 'Reading this soaked to the bone',
      de: 'Lese das gerade klatschnass',
      ar: 'أقرأ هذا وأنا مبلل تمامًا',
      fr: "Je lis ça trempé jusqu'aux os",
      es: 'Lo leo empapado de pies a cabeza',
    },
  },
  {
    emoji: '😑',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🕰️',
        app: {
          tr: 'Anılar',
          en: 'Memories',
          de: 'Erinnerungen',
          ar: 'الذكريات',
          fr: 'Souvenirs',
          es: 'Recuerdos',
        },
        text: {
          tr: '8 yıl önce bugün paylaştın: “sıkıldım”',
          en: '8 years ago today you posted: “bored”',
          de: 'Heute vor 8 Jahren: „mir ist langweilig“',
          ar: 'قبل 8 سنوات نشرت: «أشعر بالملل»',
          fr: "Il y a 8 ans : « je m'ennuie »",
          es: 'Hace 8 años publicaste: “qué aburrido”',
        },
      },
    },
    caption: {
      tr: 'Güncelleme: hâlâ sıkılıyorum',
      en: 'Update: still bored',
      de: 'Update: Mir ist immer noch langweilig',
      ar: 'تحديث: ما زلت أشعر بالملل',
      fr: "Mise à jour : je m'ennuie toujours",
      es: 'Actualización: sigo aburrido',
    },
  },
  {
    emoji: '🔕',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '👪',
        app: {
          tr: 'Aile grubu',
          en: 'Family group',
          de: 'Familiengruppe',
          ar: 'مجموعة العائلة',
          fr: 'Groupe famille',
          es: 'Grupo familiar',
        },
        text: {
          tr: 'Babam: Bu grup nasıl sessize alınır?',
          en: 'Dad: How do I mute this group?',
          de: 'Papa: Wie schalte ich die Gruppe stumm?',
          ar: 'أبي: كيف أكتم هذه المجموعة؟',
          fr: 'Papa : comment on coupe les notifs ?',
          es: 'Papá: ¿cómo silencio este grupo?',
        },
      },
    },
    caption: {
      tr: 'Soruyu nereye sorduğuna bak',
      en: 'And he asked it in the group',
      de: 'Gefragt hat er natürlich in der Gruppe',
      ar: 'وسأل السؤال في المجموعة نفسها',
      fr: 'Question posée… dans le groupe',
      es: 'Y lo preguntó en el grupo',
    },
  },
  {
    emoji: '🛵',
    user: ACCOUNTS.food,
    body: {
      format: 'notifications',
      first: {
        icon: '🥡',
        app: {
          tr: 'Yemek siparişi',
          en: 'Food delivery',
          de: 'Essenslieferung',
          ar: 'توصيل الطعام',
          fr: 'Livraison repas',
          es: 'Comida a domicilio',
        },
        text: {
          tr: 'Bu ayki 23. siparişin, afiyet olsun!',
          en: 'Your 23rd order this month. Enjoy!',
          de: 'Deine 23. Bestellung diesen Monat!',
          ar: 'طلبك رقم 23 هذا الشهر، بالهناء والشفاء!',
          fr: 'Ta 23e commande du mois, bon appétit !',
          es: 'Pedido n.º 23 este mes. ¡Buen provecho!',
        },
      },
    },
    caption: {
      tr: 'Mutfağım sadece dekor',
      en: 'My kitchen is just for decoration',
      de: 'Meine Küche ist nur Deko',
      ar: 'مطبخي مجرد ديكور',
      fr: "Ma cuisine, c'est de la déco",
      es: 'Mi cocina es solo decoración',
    },
  },
  {
    emoji: '🧳',
    user: ACCOUNTS.vlog,
    body: {
      format: 'notifications',
      first: {
        icon: '🛫',
        app: {
          tr: 'Havayolu',
          en: 'Airline',
          de: 'Fluggesellschaft',
          ar: 'شركة الطيران',
          fr: 'Compagnie aérienne',
          es: 'Aerolínea',
        },
        text: {
          tr: 'Uçuşun 7 saat rötarlı',
          en: 'Your flight is delayed 7 hours',
          de: 'Dein Flug hat 7 Stunden Verspätung',
          ar: 'رحلتك متأخرة 7 ساعات',
          fr: 'Ton vol a 7 h de retard',
          es: 'Tu vuelo tiene 7 horas de retraso',
        },
      },
    },
    caption: {
      tr: 'Artık havalimanında yaşıyorum',
      en: 'I live at the airport now',
      de: 'Ich wohne jetzt am Flughafen',
      ar: 'أنا أعيش في المطار الآن',
      fr: "J'habite à l'aéroport maintenant",
      es: 'Ahora vivo en el aeropuerto',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.home,
    body: {
      format: 'notifications',
      first: {
        icon: '🔖',
        app: {
          tr: 'Okuma takibi',
          en: 'Reading tracker',
          de: 'Lese-Tracker',
          ar: 'متابعة القراءة',
          fr: 'Suivi de lecture',
          es: 'Mis lecturas',
        },
        text: {
          tr: 'Aynı sayfada 43. günün',
          en: 'Day 43 on the same page',
          de: 'Tag 43 auf derselben Seite',
          ar: 'اليوم 43 على الصفحة نفسها',
          fr: '43e jour sur la même page',
          es: 'Día 43 en la misma página',
        },
      },
    },
    caption: {
      tr: 'Çok sürükleyici bir sayfa',
      en: "It's a really gripping page",
      de: 'Ist halt eine spannende Seite',
      ar: 'إنها صفحة مشوّقة جدًا',
      fr: "C'est une page très prenante",
      es: 'Es una página apasionante',
    },
  },
  {
    emoji: '🗣️',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🔥',
        app: {
          tr: 'Dil dersi',
          en: 'Language app',
          de: 'Sprach-App',
          ar: 'تعلّم اللغات',
          fr: 'Appli de langues',
          es: 'App de idiomas',
        },
        text: {
          tr: 'Günlük seri sıfırlandı. Rekor: 1 gün',
          en: 'Streak lost. Your record: 1 day',
          de: 'Serie verloren. Rekord: 1 Tag',
          ar: 'انتهت سلسلتك. رقمك القياسي: يوم واحد',
          fr: 'Série perdue. Ton record : 1 jour',
          es: 'Perdiste tu racha. Récord: 1 día',
        },
      },
    },
    caption: {
      tr: 'Kısa ama güzel bir seriydi',
      en: 'It was short, but it was beautiful',
      de: 'Kurz, aber schön war sie',
      ar: 'كانت قصيرة لكنها جميلة',
      fr: "C'était court, mais c'était beau",
      es: 'Fue corta, pero bonita',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '🌙',
        app: { tr: 'Uyku', en: 'Sleep', de: 'Schlaf', ar: 'النوم', fr: 'Sommeil', es: 'Sueño' },
        text: {
          tr: 'Yatakta 8 saat, uykuda 3 saat',
          en: '8 hours in bed, 3 hours asleep',
          de: '8 Std. im Bett, 3 Std. geschlafen',
          ar: '8 ساعات في السرير، 3 ساعات نوم',
          fr: '8 h au lit, 3 h de sommeil',
          es: '8 h en la cama, 3 h de sueño',
        },
      },
    },
    caption: {
      tr: 'Kalan 5 saat: kaydırma',
      en: 'The other 5 hours: scrolling',
      de: 'Die restlichen 5 Stunden: scrollen',
      ar: 'الساعات الخمس الباقية: تصفّح',
      fr: 'Les 5 autres heures : scroll',
      es: 'Las otras 5 horas: deslizando',
    },
  },
  {
    emoji: '🤖',
    user: ACCOUNTS.home,
    body: {
      format: 'notifications',
      first: {
        icon: '🧹',
        app: {
          tr: 'Robot süpürge',
          en: 'Robot vacuum',
          de: 'Saugroboter',
          ar: 'المكنسة الذكية',
          fr: 'Robot aspirateur',
          es: 'Robot aspiradora',
        },
        text: {
          tr: 'Yine koltuğun altında sıkıştım',
          en: 'Stuck under the couch again',
          de: 'Stecke wieder unterm Sofa fest',
          ar: 'علقت تحت الأريكة مجددًا',
          fr: 'Encore coincé sous le canapé',
          es: 'Otra vez atascado bajo el sofá',
        },
      },
    },
    caption: {
      tr: 'Kurtarma operasyonu, 12. gün',
      en: 'Rescue mission, day 12',
      de: 'Rettungseinsatz, Tag 12',
      ar: 'عملية إنقاذ، اليوم 12',
      fr: 'Mission sauvetage, jour 12',
      es: 'Misión de rescate, día 12',
    },
  },
  {
    emoji: '📧',
    user: ACCOUNTS.notifs,
    body: {
      format: 'notifications',
      first: {
        icon: '✉️',
        app: { tr: 'E-posta', en: 'Mail', de: 'E-Mail', ar: 'البريد', fr: 'E-mail', es: 'Correo' },
        text: {
          tr: '“Herkese yanıtla” ile 38 yeni e-posta',
          en: '38 new emails, all “Reply All”',
          de: '38 neue Mails, alle „Allen antworten“',
          ar: '38 رسالة جديدة، كلها «رد على الكل»',
          fr: '38 mails en « Répondre à tous »',
          es: '38 correos de “Responder a todos”',
        },
      },
    },
    caption: {
      tr: 'Biri şunu durdursun lütfen',
      en: 'Somebody please make it stop',
      de: 'Kann das bitte jemand stoppen?',
      ar: 'أرجوكم، فليوقف أحدٌ هذا',
      fr: "Que quelqu'un arrête ça, pitié",
      es: 'Que alguien lo detenga, por favor',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.trends,
    body: {
      format: 'notifications',
      first: {
        icon: '👤',
        app: {
          tr: 'Takipçiler',
          en: 'Followers',
          de: 'Follower',
          ar: 'المتابعون',
          fr: 'Abonnés',
          es: 'Seguidores',
        },
        text: {
          tr: 'Annen seni takip etmeye başladı',
          en: 'Your mom started following you',
          de: 'Deine Mama folgt dir jetzt',
          ar: 'والدتك بدأت متابعتك',
          fr: "Ta mère s'est abonnée à ton compte",
          es: 'Tu mamá empezó a seguirte',
        },
      },
    },
    caption: {
      tr: 'Hesabı temizleme vakti',
      en: 'Time to clean up my profile',
      de: 'Zeit, mein Profil aufzuräumen',
      ar: 'حان وقت ترتيب حسابي',
      fr: "L'heure du grand ménage sur mon profil",
      es: 'Hora de limpiar mi perfil',
    },
  },
];
