import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts drawn as a photo of their emoji (`scene`). Append only: a published post keeps its place. */
export const SKIP_SCENE: readonly Draft[] = [
  {
    emoji: '🔑',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Kapıyı çektim, anahtar içeride kaldı',
      en: 'Closed the door. Keys are inside.',
      de: 'Tür zugezogen, Schlüssel liegt drinnen',
      ar: 'أغلقت الباب… والمفتاح في الداخل',
      fr: "Porte claquée, clés à l'intérieur",
      es: 'Cerré la puerta con las llaves dentro',
      ja: 'ドアを閉めた。鍵は中。',
      ko: '문 닫았다. 열쇠는 안에 있다.',
    },
  },
  {
    emoji: '🥑',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Avokado: dün taş, yarın lapa',
      en: 'Avocado: rock yesterday, mush tomorrow',
      de: 'Avocado: gestern Stein, morgen Matsch',
      ar: 'الأفوكادو: أمس حجر، وغدًا عجينة',
      fr: 'Avocat : hier caillou, demain purée',
      es: 'Aguacate: ayer piedra, mañana puré',
      ja: 'アボカド：昨日は石、明日はドロドロ',
      ko: '아보카도: 어제는 돌, 내일은 죽',
    },
  },
  {
    emoji: '🌷',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Çiçekleri suladım. Sosyal hayatım bu.',
      en: "Watered my plants. That's my social life today.",
      de: 'Blumen gegossen. Das war mein Sozialleben heute.',
      ar: 'سقيت الزهور… وهذه حياتي الاجتماعية اليوم',
      fr: 'Plantes arrosées. Ma vie sociale du jour.',
      es: 'Regué las plantas. Esa fue mi vida social de hoy.',
      ja: '植物に水やりした。今日の社交はこれだけ。',
      ko: '화분에 물 줬다. 오늘 사회생활 끝.',
    },
  },
  {
    emoji: '☁️',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Bulut tavşana benziyordu. Artık değil.',
      en: 'That cloud looked like a bunny. Not anymore.',
      de: 'Die Wolke war ein Hase. Jetzt nicht mehr.',
      ar: 'كانت الغيمة تشبه أرنبًا. لم تعد كذلك.',
      fr: "Ce nuage, c'était un lapin. Plus maintenant.",
      es: 'Esa nube parecía un conejo. Ya no.',
      ja: 'あの雲、ウサギに見えたのに。もう違う。',
      ko: '저 구름 토끼 같았는데. 이제 아님.',
    },
  },
  {
    emoji: '🧹',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Hile: dağınıklığı kadraj dışına it',
      en: 'Life hack: push the mess out of frame',
      de: 'Lifehack: Chaos einfach aus dem Bild schieben',
      ar: 'حيلة: ادفع الفوضى خارج الصورة',
      fr: 'Astuce : pousse le bazar hors du cadre',
      es: 'Truco: empuja el desorden fuera de la foto',
      ja: 'ライフハック：散らかりは画角の外へ',
      ko: '생활 꿀팁: 어질러진 건 화면 밖으로 밀기',
    },
  },
  {
    emoji: '🏄',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Trendi sonunda yakaladım. Bitmiş.',
      en: 'Finally caught the trend. It was over.',
      de: 'Trend endlich erwischt. War schon vorbei.',
      ar: 'لحقت بالترند أخيرًا… وكان قد انتهى',
      fr: 'Tendance enfin rattrapée. Déjà démodée.',
      es: 'Por fin me subí a la moda. Ya pasó.',
      ja: 'やっと流行に追いついた。もう終わってた。',
      ko: '드디어 유행 따라잡음. 이미 끝났더라.',
    },
  },
  {
    emoji: '🐙',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Ahtapotun 3 kalbi var, bende 0 enerji',
      en: 'Octopuses have 3 hearts. I have 0 energy.',
      de: 'Kraken haben 3 Herzen, ich 0 Energie',
      ar: 'للأخطبوط 3 قلوب، ولديّ 0 طاقة',
      fr: 'La pieuvre a 3 cœurs. Moi, 0 énergie.',
      es: 'El pulpo tiene 3 corazones. Yo, 0 energía.',
      ja: 'タコは心臓が3つ。私は元気が0。',
      ko: '문어는 심장이 3개. 나는 에너지가 0.',
    },
  },
  {
    emoji: '🧘',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Dijital detoks: gün 1, dakika 4',
      en: 'Digital detox: day 1, minute 4',
      de: 'Digital Detox: Tag 1, Minute 4',
      ar: 'إجازة من الهاتف: اليوم 1، الدقيقة 4',
      fr: 'Détox numérique : jour 1, minute 4',
      es: 'Desconexión digital: día 1, minuto 4',
      ja: 'デジタルデトックス：1日目、4分経過',
      ko: '디지털 디톡스: 1일 차, 4분째',
    },
  },
  {
    emoji: '✏️',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Kalem açma ASMR, ödev hâlâ boş',
      en: 'Pencil sharpening ASMR, homework still blank',
      de: 'Bleistiftspitzen-ASMR, Hausaufgaben noch leer',
      ar: 'أصوات مريحة: بري القلم… والواجب فارغ',
      fr: 'ASMR taille-crayon, devoirs pas commencés',
      es: 'ASMR de sacapuntas, la tarea sigue en blanco',
      ja: '鉛筆削りASMR、宿題はまだ白紙',
      ko: '연필 깎기 ASMR, 숙제는 아직 백지',
    },
  },
  {
    emoji: '🍦',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Dondurma aldım, eve varmadan eridi',
      en: 'Bought ice cream. Melted on the way home.',
      de: 'Eis gekauft. Auf dem Heimweg geschmolzen.',
      ar: 'اشتريت آيس كريم… فذاب قبل أن أصل إلى البيت',
      fr: "Glace achetée. Fondue avant d'arriver.",
      es: 'Compré helado. Se derritió antes de llegar.',
      ja: 'アイス買った。家に着く前に溶けた。',
      ko: '아이스크림 샀는데 집 오기 전에 녹음.',
    },
  },
  {
    emoji: '🥗',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Salata sadece fotoğraf içindi',
      en: 'The salad was just for the photo',
      de: 'Der Salat war nur fürs Foto',
      ar: 'السلطة كانت من أجل الصورة فقط',
      fr: "La salade, c'était juste pour la photo",
      es: 'La ensalada era solo para la foto',
      ja: 'サラダは写真用でした',
      ko: '샐러드는 사진용이었음',
    },
  },
  {
    emoji: '🛏️',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Yatağı topladım, bugünlük bu kadar',
      en: "Made my bed. That's it for today.",
      de: "Bett gemacht. Das war's für heute.",
      ar: 'رتّبت سريري… وهذا إنجاز اليوم',
      fr: 'Lit fait. Journée terminée.',
      es: 'Hice la cama. Por hoy, suficiente.',
      ja: 'ベッドを整えた。今日はここまで。',
      ko: '이불 개기 완료. 오늘은 여기까지.',
    },
  },
  {
    emoji: '🪨',
    user: ACCOUNTS.plain,
    body: { format: 'scene' },
    caption: {
      tr: 'Bugün bir taş buldum. Güzel taş.',
      en: 'Found a rock today. Nice rock.',
      de: 'Heute einen Stein gefunden. Schöner Stein.',
      ar: 'وجدت حجرًا اليوم. حجر جميل.',
      fr: "Trouvé un caillou aujourd'hui. Joli caillou.",
      es: 'Hoy encontré una piedra. Buena piedra.',
      ja: '今日、石を拾った。いい石。',
      ko: '오늘 돌을 주웠다. 좋은 돌.',
    },
  },
  {
    emoji: '🔌',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Hile: şarj bitmesin, telefonu kullanma',
      en: 'Hack: infinite battery (just never use your phone)',
      de: 'Hack: Akku nie leer? Handy einfach nicht benutzen.',
      ar: 'حيلة: لن تنفد البطارية إن لم تستخدم الهاتف',
      fr: 'Astuce : batterie éternelle, tel éteint',
      es: 'Truco: batería infinita si no usas el teléfono',
      ja: '裏ワザ：電池が減らない（スマホを使わない）',
      ko: '꿀팁: 배터리 무한 (폰을 안 쓰면 됨)',
    },
  },
  {
    emoji: '🥞',
    user: ACCOUNTS.trends,
    body: { format: 'scene' },
    caption: {
      tr: 'Yeni trend: akşam yemeğine kahvaltı',
      en: 'New trend: breakfast for dinner',
      de: 'Neuer Trend: Frühstück zum Abendessen',
      ar: 'ترند جديد: الفطور على العشاء',
      fr: 'Nouvelle tendance : le petit-déj au dîner',
      es: 'Nueva tendencia: desayuno para cenar',
      ja: '新トレンド：夜ごはんに朝ごはん',
      ko: '새 트렌드: 저녁으로 아침 먹기',
    },
  },
  {
    emoji: '🍯',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Bal asla bozulmaz. Planlarım bozulur.',
      en: 'Honey never spoils. My plans do.',
      de: 'Honig wird nie schlecht. Meine Pläne schon.',
      ar: 'العسل لا يفسد أبدًا. أما خططي فتفسد.',
      fr: 'Le miel ne périme jamais. Mes plans, si.',
      es: 'La miel nunca se echa a perder. Mis planes, sí.',
      ja: 'ハチミツは永遠にもつ。私の予定はもたない。',
      ko: '꿀은 절대 상하지 않는다. 내 계획은 늘 틀어진다.',
    },
  },
  {
    emoji: '📈',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Her gün %1 daha iyi. Bugün: %0.',
      en: '1% better every day. Today: 0%.',
      de: 'Jeden Tag 1 % besser. Heute: 0 %.',
      ar: 'كل يوم أفضل بنسبة 1%. اليوم: 0%.',
      fr: "Chaque jour 1 % meilleur. Aujourd'hui : 0 %.",
      es: 'Cada día un 1 % mejor. Hoy: 0 %.',
      ja: '毎日1%成長。今日は0%。',
      ko: '매일 1%씩 성장. 오늘은 0%.',
    },
  },
  {
    emoji: '📖',
    user: ACCOUNTS.asmr,
    body: { format: 'scene' },
    caption: {
      tr: 'Sayfa çevirme ASMR (kitabı okumuyorum)',
      en: 'Page-turning ASMR (not reading the book)',
      de: 'Umblätter-ASMR (das Buch lese ich nicht)',
      ar: 'أصوات مريحة: تقليب الصفحات (دون قراءة)',
      fr: 'ASMR pages qui tournent (je lis pas le livre)',
      es: 'ASMR de pasar páginas (no leo el libro)',
      ja: 'ページめくりASMR（読んではいない）',
      ko: '책장 넘기기 ASMR (읽지는 않음)',
    },
  },
  {
    emoji: '🎥',
    user: ACCOUNTS.vlog,
    body: { format: 'scene' },
    caption: {
      tr: 'Günlük vlog: bugün hiçbir şey olmadı',
      en: 'Daily vlog: nothing happened today',
      de: 'Tagesvlog: heute ist nichts passiert',
      ar: 'يومياتي: لم يحدث شيء اليوم',
      fr: "Vlog du jour : il ne s'est rien passé",
      es: 'Vlog diario: hoy no pasó nada',
      ja: '日常vlog：今日は何も起きなかった',
      ko: '일상 브이로그: 오늘은 아무 일도 없었음',
    },
  },
  {
    emoji: '🍚',
    user: ACCOUNTS.food,
    body: { format: 'scene' },
    caption: {
      tr: 'Az pirinç koydum, bütün tencereler doldu',
      en: 'Made a little rice. Every pot is full now.',
      de: 'Nur ein bisschen Reis gekocht. Alle Töpfe voll.',
      ar: 'طبخت قليلًا من الأرز… فامتلأت كل القدور',
      fr: 'Juste un peu de riz. Trois casseroles pleines.',
      es: 'Un poco de arroz. Todas las ollas llenas.',
      ja: 'ご飯を少しだけ炊いた。鍋が全部埋まった。',
      ko: '쌀 조금 넣었는데 냄비가 전부 꽉 참.',
    },
  },
  {
    emoji: '🧽',
    user: ACCOUNTS.home,
    body: { format: 'scene' },
    caption: {
      tr: 'Bütün evi temizledim, kimse gelmedi',
      en: 'Cleaned the whole place. Nobody came over.',
      de: 'Ganze Wohnung geputzt. Keiner kam vorbei.',
      ar: 'نظّفت البيت كله… ولم يزرني أحد',
      fr: "Appart nickel. Personne n'est passé.",
      es: 'Limpié toda la casa. No vino nadie.',
      ja: '家じゅう掃除した。誰も来なかった。',
      ko: '집 전체를 청소했다. 아무도 안 왔다.',
    },
  },
  {
    emoji: '🍌',
    user: ACCOUNTS.hacks,
    body: { format: 'scene' },
    caption: {
      tr: 'Muzu alttan soy (hiçbir şey değişmez)',
      en: 'Peel bananas from the bottom (changes nothing)',
      de: 'Bananen von unten schälen (bringt nichts)',
      ar: 'قشّر الموزة من الأسفل (لن يتغير شيء)',
      fr: 'Épluche la banane par le bas (ça change rien)',
      es: 'Pela la banana por abajo (no cambia nada)',
      ja: 'バナナは下からむこう（何も変わらない）',
      ko: '바나나는 아래부터 까기 (아무것도 안 바뀜)',
    },
  },
  {
    emoji: '🐨',
    user: ACCOUNTS.facts,
    body: { format: 'scene' },
    caption: {
      tr: 'Koalalar günde 20 saat uyur. Hedef.',
      en: 'Koalas sleep 20 hours a day. Goals.',
      de: 'Koalas schlafen 20 Stunden am Tag. Lebensziel.',
      ar: 'ينام الكوالا 20 ساعة يوميًا. قدوتي.',
      fr: 'Le koala dort 20 h par jour. Objectif.',
      es: 'Los koalas duermen 20 horas al día. Metas.',
      ja: 'コアラは1日20時間寝る。目標。',
      ko: '코알라는 하루 20시간 잔다. 내 목표.',
    },
  },
  {
    emoji: '🥐',
    user: ACCOUNTS.motivation,
    body: { format: 'scene' },
    caption: {
      tr: 'Koşuya çıktım, fırında durdum',
      en: 'Went for a run. Stopped at the bakery.',
      de: 'Joggen gegangen. Beim Bäcker gelandet.',
      ar: 'خرجت للجري… وتوقفت عند المخبز',
      fr: 'Parti courir. Arrêté à la boulangerie.',
      es: 'Salí a correr. Terminé en la panadería.',
      ja: 'ランニングに出た。パン屋で止まった。',
      ko: '달리기하러 나갔다가 빵집에서 멈춤.',
    },
  },
];
