import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are tier lists (`tier`). Append only: a published post keeps its place. */
export const SKIP_TIER: readonly Draft[] = [
  {
    emoji: '🥞',
    user: ACCOUNTS.food,
    body: {
      format: 'tier',
      title: {
        tr: 'KAHVALTI TIER LIST',
        en: 'BREAKFAST TIER LIST',
        de: 'FRÜHSTÜCKS-TIER-LIST',
        ar: 'تصنيف الفطور',
        fr: 'TIER LIST DU PETIT-DÉJ',
        es: 'TIER LIST DEL DESAYUNO',
      },
      rows: [['🍳', '🧀', '🫒', '🍅'], ['🥞', '🧇', '🥐'], ['🥣', '🍌'], ['🥗']],
    },
    caption: {
      tr: 'Çay listede yok çünkü S’nin üstünde',
      en: "No coffee on the list. It's above S.",
      de: 'Kaffee steht außer Konkurrenz',
      ar: 'القهوة ليست في القائمة، فهي فوق الجميع',
      fr: 'Le café est hors catégorie',
      es: 'El café va fuera de concurso',
    },
  },
  {
    emoji: '🍓',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'MEYVE TIER LIST',
        en: 'FRUIT TIER LIST',
        de: 'OBST-TIER-LIST',
        ar: 'ترتيب الفواكه',
        fr: 'TIER LIST DES FRUITS',
        es: 'TIER LIST DE FRUTAS',
      },
      rows: [['🍇', '🍓', '🫐', '🍒'], ['🍎', '🍐', '🍑', '🍌'], ['🍊', '🥝'], ['🍍', '🥥', '🍉']],
    },
    caption: {
      tr: 'Uğraştırıyorsa C, kusura bakmasın',
      en: "If it's work to eat, it's C tier",
      de: 'Macht es Arbeit, landet es in C',
      ar: 'الفاكهة المتعبة إلى آخر القائمة',
      fr: "Si ça demande des efforts, c'est C",
      es: 'Si cuesta comerla, va a la C',
    },
  },
  {
    emoji: '🍰',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'TATLI TIER LIST',
        en: 'DESSERT TIER LIST',
        de: 'NACHTISCH-RANKING',
        ar: 'تصنيف الحلويات',
        fr: 'TIER LIST DES DESSERTS',
        es: 'TIER LIST DE POSTRES',
      },
      rows: [['🍰', '🍫', '🍦'], ['🍩', '🧁', '🍪'], ['🥧', '🍮'], ['🍎']],
    },
    caption: {
      tr: 'Anne, meyve tatlı değildir',
      en: 'Mom, fruit is not dessert',
      de: 'Mama, Obst ist kein Nachtisch',
      ar: 'أمي، الفاكهة ليست حلوى',
      fr: "Maman, un fruit, c'est pas un dessert",
      es: 'Mamá, la fruta no es postre',
    },
  },
  {
    emoji: '🐾',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'EVCİL HAYVAN TIER LIST',
        en: 'PET TIER LIST',
        de: 'HAUSTIER-RANKING',
        ar: 'تصنيف الحيوانات الأليفة',
        fr: 'TIER LIST DES ANIMAUX',
        es: 'TIER LIST DE MASCOTAS',
      },
      rows: [['🪨'], ['🐈', '🐕', '🐰'], ['🐹', '🐢', '🐠'], ['🕷️', '🐍']],
    },
    caption: {
      tr: 'Taş hiç mama istemiyor',
      en: 'The rock never asks for food',
      de: 'Der Stein will nie Futter',
      ar: 'الحجر لا يطلب طعامًا أبدًا',
      fr: 'Le caillou ne réclame jamais à manger',
      es: 'La piedra nunca pide comida',
    },
  },
  {
    emoji: '🍂',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'MEVSİM TIER LIST',
        en: 'SEASON TIER LIST',
        de: 'JAHRESZEITEN-RANKING',
        ar: 'تصنيف فصول السنة',
        fr: 'TIER LIST DES SAISONS',
        es: 'TIER LIST DE ESTACIONES',
      },
      rows: [['🍂'], ['❄️'], ['🌸'], ['☀️']],
    },
    caption: {
      tr: 'Yaz abartılıyor, söyledim gitti',
      en: 'Summer is overrated. I said it.',
      de: "Sommer wird überschätzt. Ich sag's nur.",
      ar: 'الصيف مبالغ في تقديره، وقد قلتها',
      fr: "L'été est surcoté. Voilà, c'est dit.",
      es: 'El verano está sobrevalorado. Lo dije.',
    },
  },
  {
    emoji: '🌂',
    user: ACCOUNTS.home,
    body: {
      format: 'tier',
      title: {
        tr: 'YAĞMURLU GÜN TIER LIST',
        en: 'RAINY DAY TIER LIST',
        de: 'REGENTAG-RANKING',
        ar: 'تصنيف أنشطة يوم ممطر',
        fr: 'TIER LIST JOUR DE PLUIE',
        es: 'TIER LIST DÍA DE LLUVIA',
      },
      rows: [['🛌', '🍵'], ['🎬', '📚', '🧩'], ['🍪', '🧹'], ['☂️', '🚶']],
    },
    caption: {
      tr: 'Yağmurda yürümek romantik değil, ıslak',
      en: "Rain walks aren't romantic. Just wet.",
      de: 'Regenspaziergang? Nicht romantisch, nur nass.',
      ar: 'المشي تحت المطر ليس رومانسيًا، إنه مبلّل فحسب',
      fr: 'Sous la pluie : pas romantique, juste mouillé',
      es: 'Caminar bajo la lluvia no es romántico, moja',
    },
  },
  {
    emoji: '😴',
    user: ACCOUNTS.plain,
    body: {
      format: 'tier',
      title: {
        tr: 'UYANMA YÖNTEMLERİ',
        en: 'WAYS TO WAKE UP, RANKED',
        de: 'AUFWACH-RANKING',
        ar: 'ترتيب طرق الاستيقاظ',
        fr: 'TIER LIST DU RÉVEIL',
        es: 'TIER LIST DEL DESPERTAR',
      },
      rows: [['😴'], ['☀️', '🐦'], ['⏰', '📱'], ['🐈']],
    },
    caption: {
      tr: 'Kedi alarmının erteleme tuşu yok',
      en: 'The cat alarm has no snooze button',
      de: 'Der Katzenwecker hat keine Schlummertaste',
      ar: 'منبّه القطة بلا زر غفوة',
      fr: 'Impossible de snoozer le réveil-chat',
      es: 'La alarma gatuna no se puede posponer',
    },
  },
  {
    emoji: '🧀',
    user: ACCOUNTS.food,
    body: {
      format: 'tier',
      title: {
        tr: 'GECE ATIŞTIRMALIKLARI',
        en: 'MIDNIGHT SNACK TIER LIST',
        de: 'SNACKS UM MITTERNACHT',
        ar: 'تصنيف وجبات منتصف الليل',
        fr: 'GRIGNOTAGE DE MINUIT',
        es: 'SNACKS DE MEDIANOCHE',
      },
      rows: [['🧀', '🍫'], ['🍪', '🥣'], ['🍞', '🥜'], ['🥕']],
    },
    caption: {
      tr: 'Gece 12’den sonra her şey atıştırmalıktır',
      en: 'After midnight, everything counts as a snack',
      de: 'Nach Mitternacht ist alles ein Snack',
      ar: 'بعد منتصف الليل، كل شيء وجبة خفيفة',
      fr: 'Après minuit, tout compte comme grignotage',
      es: 'Después de medianoche, todo cuenta como snack',
    },
  },
  {
    emoji: '🥦',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'SEBZE TIER LIST',
        en: 'VEGGIE TIER LIST',
        de: 'GEMÜSE-RANKING',
        ar: 'تصنيف الخضراوات',
        fr: 'TIER LIST DES LÉGUMES',
        es: 'TIER LIST DE VERDURAS',
      },
      rows: [['🥔', '🌽'], ['🍅', '🥒', '🥕'], ['🧅', '🫑'], ['🥦']],
    },
    caption: {
      tr: 'Brokoli minik bir ağaç, ben ağaç yemem',
      en: "Broccoli is a tiny tree. I don't eat trees.",
      de: 'Brokkoli = Mini-Baum. Bäume ess ich nicht.',
      ar: 'البروكلي شجرة صغيرة، وأنا لا آكل الأشجار',
      fr: "Le brocoli, c'est un mini-arbre. Non merci.",
      es: 'El brócoli es un arbolito. No como árboles.',
    },
  },
  {
    emoji: '📱',
    user: ACCOUNTS.trends,
    body: {
      format: 'tier',
      title: {
        tr: 'KAYDIRMA YERİ TIER LIST',
        en: 'SCROLLING SPOT TIER LIST',
        de: 'SCROLL-SPOT-RANKING',
        ar: 'تصنيف أماكن التصفح',
        fr: 'TIER LIST SPOTS DE SCROLL',
        es: 'LUGARES PARA DESLIZAR',
      },
      rows: [['🛏️'], ['🛋️', '🚌'], ['🍽️', '🛁'], ['🚶']],
    },
    caption: {
      tr: 'Yatakta kaydırmanın rakibi yok',
      en: 'Nothing beats scrolling in bed',
      de: 'Nichts schlägt Scrollen im Bett',
      ar: 'لا شيء يضاهي التصفح في السرير',
      fr: 'Rien ne vaut le scroll au lit',
      es: 'Nada supera deslizar en la cama',
    },
  },
  {
    emoji: '😂',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'EMOJİ TIER LIST',
        en: 'EMOJI TIER LIST',
        de: 'EMOJI-RANKING',
        ar: 'ترتيب الإيموجي',
        fr: 'TIER LIST DES EMOJIS',
        es: 'TIER LIST DE EMOJIS',
      },
      rows: [['😂', '🤣'], ['😭', '🔥'], ['👍', '❤️'], ['🙂']],
    },
    caption: {
      tr: '🙂 atan kişi sana kızgındır',
      en: "If they send 🙂, they're mad at you",
      de: 'Wer 🙂 schickt, ist sauer auf dich',
      ar: 'من يرسل لك 🙂 فهو غاضب منك',
      fr: "Si on t'envoie 🙂, on t'en veut",
      es: 'Si te mandan 🙂, están molestos contigo',
    },
  },
  {
    emoji: '🐕',
    user: ACCOUNTS.trends,
    body: {
      format: 'tier',
      title: {
        tr: 'AKIŞ TIER LIST',
        en: 'FEED TIER LIST',
        de: 'FEED-RANKING',
        ar: 'تصنيف المنشورات',
        fr: "TIER LIST DU FIL D'ACTU",
        es: 'TIER LIST DEL FEED',
      },
      rows: [['🐈', '🐕', '🦦'], ['😂', '🍳'], ['🏖️', '🏋️'], ['📢']],
    },
    caption: {
      tr: 'Hayvan videosu görünce kaydıramıyorum',
      en: "I can't scroll past an animal video",
      de: 'An Tiervideos scrolle ich nie vorbei',
      ar: 'لا أستطيع تجاوز فيديو فيه حيوان',
      fr: "Impossible de zapper une vidéo d'animal",
      es: 'No puedo saltarme un video de animales',
    },
  },
  {
    emoji: '🍿',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'FİLM TÜRÜ TIER LIST',
        en: 'MOVIE GENRE TIER LIST',
        de: 'FILMGENRE-RANKING',
        ar: 'تصنيف أنواع الأفلام',
        fr: 'TIER LIST GENRES DE FILMS',
        es: 'TIER LIST DE PELÍCULAS',
      },
      rows: [['😂', '🚀'], ['🕵️', '🦸'], ['💕', '🐉'], ['👻']],
    },
    caption: {
      tr: 'Korku C, çünkü korkuyorum. Tamam mı?',
      en: "Horror's C because I get scared, OK?",
      de: "Horror ist C, weil ich Angst hab. Okay?",
      ar: 'أفلام الرعب في الأخير لأنني أخاف، مفهوم؟',
      fr: "L'horreur en C, parce que j'ai peur. Voilà.",
      es: 'Terror en la C porque me asusta. ¿Y qué?',
    },
  },
  {
    emoji: '👃',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'KOKU TIER LIST',
        en: 'SMELL TIER LIST',
        de: 'GERUCHS-RANKING',
        ar: 'ترتيب الروائح',
        fr: 'TIER LIST DES ODEURS',
        es: 'TIER LIST DE OLORES',
      },
      rows: [['📚', '🍞', '🌧️'], ['☕️', '🌸', '🍋'], ['🧼', '🍊'], ['🦨']],
    },
    caption: {
      tr: 'Yeni kitap kokusu S, itiraz kabul edilmez',
      en: 'New book smell is S tier. No appeals.',
      de: 'Neue Bücher riechen nach S. Punkt.',
      ar: 'رائحة الكتب الجديدة في القمة، ولا اعتراض',
      fr: "L'odeur des livres neufs, c'est S. Point.",
      es: 'El olor a libro nuevo es S. Sin discusión.',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.tiers,
    body: {
      format: 'tier',
      title: {
        tr: 'MESAJLAŞMA TIER LIST',
        en: 'TEXTING TIER LIST',
        de: 'NACHRICHTEN-RANKING',
        ar: 'تصنيف طرق التواصل',
        fr: 'TIER LIST DES MESSAGES',
        es: 'TIER LIST DE MENSAJES',
      },
      rows: [['💬'], ['📸', '🎵', '📍'], ['🎙️'], ['📞']],
    },
    caption: {
      tr: 'Haber vermeden arayan direkt C',
      en: 'Calling without texting first? C tier.',
      de: 'Anrufen ohne Vorwarnung? Sofort C.',
      ar: 'من يتصل دون رسالة مسبقة؟ في آخر القائمة',
      fr: 'Appeler sans prévenir ? Direct en C.',
      es: '¿Llamar sin avisar? Directo a la C.',
    },
  },
  {
    emoji: '🍍',
    user: ACCOUNTS.food,
    body: {
      format: 'tier',
      title: {
        tr: 'PİZZA MALZEMESİ TIER LIST',
        en: 'PIZZA TOPPING TIER LIST',
        de: 'PIZZABELAG-RANKING',
        ar: 'تصنيف إضافات البيتزا',
        fr: 'TIER LIST GARNITURES PIZZA',
        es: 'TIER LIST DE LA PIZZA',
      },
      rows: [['🧀', '🍅'], ['🍄', '🌽', '🫑'], ['🫒', '🧅'], ['🍍']],
    },
    caption: {
      tr: 'Ananas sevenler, yorumlar sizin',
      en: 'Pineapple fans, the comments are yours',
      de: 'Ananas-Fans, die Kommentare gehören euch',
      ar: 'يا محبي الأناناس، التعليقات لكم',
      fr: "Fans d'ananas, les commentaires sont à vous",
      es: 'Fans de la piña, los leo en comentarios',
    },
  },
];
