import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are chat screenshots (`chat`). Append only: a published post keeps its place. */
export const SKIP_CHAT: readonly Draft[] = [
  {
    emoji: '🍟',
    user: ACCOUNTS.food,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'bugün sebze yedin mi?',
            en: 'did you eat any veggies today?',
            de: 'hast du heute Gemüse gegessen?',
            ar: 'هل أكلت خضارًا اليوم؟',
            fr: "t'as mangé des légumes aujourd'hui ?",
            es: '¿comiste verduras hoy?',
            ja: '今日、野菜食べた？',
            ko: '오늘 채소 먹었어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'yedim tabii',
            en: 'of course',
            de: 'klar',
            ar: 'طبعًا',
            fr: 'bien sûr',
            es: 'claro',
            ja: 'もちろん',
            ko: '당연하지',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ne yedin?',
            en: 'like what?',
            de: 'was denn?',
            ar: 'ماذا أكلت؟',
            fr: 'lesquels ?',
            es: '¿cuáles?',
            ja: '何食べたの？',
            ko: '뭐 먹었는데?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'patates kızartması 🍟',
            en: 'fries 🍟',
            de: 'Pommes 🍟',
            ar: 'بطاطس مقلية 🍟',
            fr: 'des frites 🍟',
            es: 'papas fritas 🍟',
            ja: 'フライドポテト 🍟',
            ko: '감자튀김 🍟',
          },
        },
      ],
    },
    caption: {
      tr: 'Teknik olarak yalan değil',
      en: 'Technically not a lie',
      de: 'Technisch gesehen keine Lüge',
      ar: 'تقنيًا، هذا ليس كذبًا',
      fr: "Techniquement, c'est pas faux",
      es: 'Técnicamente no es mentira',
      ja: '嘘はついてない。厳密には',
      ko: '엄밀히 말하면 거짓말은 아님',
    },
  },
  {
    emoji: '🔑',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá', ja: 'お父さん', ko: '아빠' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba anahtarı unuttum 🙈',
            en: 'dad I forgot my key 🙈',
            de: 'Papa, hab meinen Schlüssel vergessen 🙈',
            ar: 'أبي، نسيت المفتاح 🙈',
            fr: "papa j'ai oublié ma clé 🙈",
            es: 'papá, olvidé la llave 🙈',
            ja: 'お父さん、鍵忘れた 🙈',
            ko: '아빠 나 열쇠 두고 왔어 🙈',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Merhaba evladım.',
            en: 'Good afternoon.',
            de: 'Guten Tag.',
            ar: 'تحية طيبة وبعد،',
            fr: 'Bonjour.',
            es: 'Buenas tardes.',
            ja: '拝啓',
            ko: '안녕하십니까.',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Saksının altında. Saygılarımla, Baban',
            en: "It's under the flowerpot. Love, Dad",
            de: 'Liegt unterm Blumentopf. Viele Grüße, Papa',
            ar: 'تحت أصيص الزرع. مع التحية، والدك',
            fr: 'Sous le pot de fleurs. Cordialement, Papa',
            es: 'Bajo la maceta. Atentamente, Papá',
            ja: '植木鉢の下です。敬具、父より',
            ko: '화분 밑에 있음. 이상. 아빠가',
          },
        },
      ],
    },
    caption: {
      tr: 'Babam mesaj değil dilekçe yazıyor',
      en: "Dad texts like he's writing a letter",
      de: 'Papa schreibt Nachrichten wie Geschäftsbriefe',
      ar: 'أبي يكتب الرسائل كأنها خطابات رسمية',
      fr: 'Papa, roi du SMS administratif',
      es: 'Papá escribe mensajes como cartas formales',
      ja: '父のLINEが毎回ビジネス文書',
      ko: '아빠 카톡은 항상 공문서',
    },
  },
  {
    emoji: '📲',
    user: ACCOUNTS.trends,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'bak bu tam sen 😂',
            en: 'lol this is so you 😂',
            de: 'haha das bist voll du 😂',
            ar: 'هذا أنت تمامًا 😂',
            fr: "mdr c'est trop toi 😂",
            es: 'jaja este eres tú 😂',
            ja: 'これ完全にあんたじゃん 😂',
            ko: 'ㅋㅋ 이거 완전 너잖아 😂',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'asıl bu sensin 😂',
            en: 'no THIS is you 😂',
            de: 'nee, DAS bist du 😂',
            ar: 'بل هذا أنت 😂',
            fr: "non, ça c'est toi 😂",
            es: 'no, este eres tú 😂',
            ja: 'いや、こっちがあんたでしょ 😂',
            ko: '아니 이게 진짜 너야 😂',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bu arada nasılsın?',
            en: 'btw how are you?',
            de: "wie geht's dir eigentlich?",
            ar: 'بالمناسبة، كيف حالك؟',
            fr: 'au fait, ça va ?',
            es: 'por cierto, ¿cómo estás?',
            ja: 'てか元気？',
            ko: '근데 잘 지내?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bak bu da tam sen 😂',
            en: "lol this one's you too 😂",
            de: 'haha das hier bist auch du 😂',
            ar: 'وهذا أيضًا أنت 😂',
            fr: "mdr ça aussi c'est toi 😂",
            es: 'jaja este también eres tú 😂',
            ja: 'これもあんたじゃん 😂',
            ko: 'ㅋㅋ 이것도 완전 너 😂',
          },
        },
      ],
    },
    caption: {
      tr: 'Arkadaşlığımızın %90’ı video atmak',
      en: 'Our friendship is 90% sending videos',
      de: 'Unsere Freundschaft: 90 % Videos schicken',
      ar: '90% من صداقتنا إرسال فيديوهات',
      fr: "Notre amitié, c'est 90 % de vidéos",
      es: 'Nuestra amistad es 90 % mandar videos',
      ja: '友情の90%は動画の送り合い',
      ko: '우리 우정의 90%는 릴스 보내기',
    },
  },
  {
    emoji: '📅',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Patron', en: 'Boss', de: 'Chef', ar: 'المدير', fr: 'Patron', es: 'Jefe', ja: '部長', ko: '팀장님' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'müsait misin? kısa bir sorum var',
            en: 'got a sec? quick question',
            de: 'hast du kurz Zeit? kurze Frage',
            ar: 'هل لديك دقيقة؟ سؤال سريع',
            fr: "t'as deux minutes ? petite question",
            es: '¿tienes un minuto? una pregunta rápida',
            ja: '今ちょっといい？質問1つだけ',
            ko: '잠깐 괜찮아요? 짧게 하나만 물어볼게요',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tabii, sor',
            en: 'sure, go ahead',
            de: 'klar, schieß los',
            ar: 'طبعًا، تفضّل',
            fr: 'oui, vas-y',
            es: 'claro, dime',
            ja: 'はい、どうぞ',
            ko: '네, 말씀하세요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'süper, 2 saatlik toplantı ayarladım',
            en: 'great, I booked us a 2-hour meeting',
            de: 'super, hab ein 2-Stunden-Meeting angesetzt',
            ar: 'رائع، حجزت لنا اجتماعًا لمدة ساعتين',
            fr: "super, j'ai calé une réunion de 2 h",
            es: 'genial, programé una reunión de 2 horas',
            ja: 'よかった、2時間の会議入れといたから',
            ko: '좋아요, 2시간짜리 회의 잡았어요',
          },
        },
      ],
    },
    caption: {
      tr: '“Kısa bir soru” asla kısa sürmez',
      en: '“Quick question” is never quick',
      de: '„Kurze Frage“ ist nie kurz',
      ar: '«سؤال سريع» ليس سريعًا أبدًا',
      fr: "Une « petite question », qu'il disait",
      es: 'La “pregunta rápida” nunca es rápida',
      ja: '「ちょっといい？」がちょっとで済んだことはない',
      ko: '“잠깐이면 돼”는 절대 잠깐이 아님',
    },
  },
  {
    emoji: '🥣',
    user: ACCOUNTS.home,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
        ja: 'ルームメイト',
        ko: '룸메이트',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'buzdolabındaki yoğurdumu kim yedi?',
            en: 'who ate my yogurt?',
            de: 'wer hat meinen Joghurt gegessen?',
            ar: 'من أكل الزبادي الخاص بي؟',
            fr: 'qui a mangé mon yaourt ?',
            es: '¿quién se comió mi yogur?',
            ja: '冷蔵庫の私のヨーグルト食べたの誰？',
            ko: '냉장고에 있던 내 요거트 누가 먹었어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'üstünde isim yoktu ama',
            en: "it didn't have your name on it",
            de: 'da stand doch kein Name drauf',
            ar: 'لم يكن عليه اسم',
            fr: 'y avait pas ton nom dessus',
            es: 'no tenía tu nombre',
            ja: '名前書いてなかったし',
            ko: '이름 안 써 있었는데?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'kapağında SENİN DEĞİL yazıyordu',
            en: 'the lid literally said NOT YOURS',
            de: 'auf dem Deckel stand NICHT DEINER',
            ar: 'كان مكتوبًا على الغطاء: ليس لك',
            fr: "sur le couvercle c'était écrit PAS À TOI",
            es: 'la tapa decía NO ES TUYO',
            ja: 'フタに「あなたのじゃない」って書いてあった',
            ko: '뚜껑에 “네 거 아님”이라고 써 있었거든',
          },
        },
      ],
    },
    caption: {
      tr: 'Ev arkadaşı hukuku: kapak bağlayıcıdır',
      en: 'Roommate law: the lid is legally binding',
      de: 'WG-Recht: Der Deckel ist verbindlich',
      ar: 'قانون السكن المشترك: الغطاء ملزِم',
      fr: 'Droit de la coloc : le couvercle fait foi',
      es: 'Ley de convivencia: la tapa es un contrato',
      ja: 'ルームシェア法：フタの文字は法的拘束力あり',
      ko: '룸메 법: 뚜껑에 쓴 건 법적 효력 있음',
    },
  },
  {
    emoji: '🌐',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Teyzem', en: 'Auntie', de: 'Tante', ar: 'خالتي', fr: 'Tatie', es: 'Tía', ja: 'おばさん', ko: '이모' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'Sen bu telefon işlerinden anlarsın.',
            en: "You're good with phones, right?",
            de: 'Du kennst dich doch mit Handys aus.',
            ar: 'أنت تفهم في أمور الهواتف، صحيح؟',
            fr: "Toi, tu t'y connais en téléphones ?",
            es: 'Tú sabes de teléfonos, ¿verdad?',
            ja: 'あなた、スマホ詳しいわよね？',
            ko: '너 이런 휴대폰 잘 알지?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'biraz, ne oldu teyze?',
            en: "kind of, what's up?",
            de: 'bisschen, was ist los?',
            ar: 'قليلًا، ماذا حدث يا خالتي؟',
            fr: "un peu, qu'est-ce qui se passe ?",
            es: 'un poco, ¿qué pasó, tía?',
            ja: 'まあね、どうしたの？',
            ko: '조금요, 무슨 일이세요?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'İnterneti sildim galiba, geri yükler misin?',
            en: 'I deleted the internet. Can you put it back?',
            de: 'Hab aus Versehen das Internet gelöscht.',
            ar: 'أظنني حذفت الإنترنت، هل تعيده لي؟',
            fr: "J'ai effacé internet, tu peux le remettre ?",
            es: 'Borré el internet. ¿Lo vuelves a poner?',
            ja: 'インターネット消しちゃったみたい。戻せる？',
            ko: '인터넷을 지운 것 같아. 다시 깔아 줄래?',
          },
        },
      ],
    },
    caption: {
      tr: 'Ailenin bilgi işlem departmanı benim',
      en: "I'm the family's IT department",
      de: 'Ich bin die IT-Abteilung der Familie',
      ar: 'أنا قسم الدعم الفني في العائلة',
      fr: 'Je suis le service informatique de la famille',
      es: 'Soy el soporte técnico de la familia',
      ja: '家族の情シスは私です',
      ko: '우리 집 전산팀은 나 혼자임',
    },
  },
  {
    emoji: '👟',
    user: ACCOUNTS.motivation,
    body: {
      format: 'chat',
      contact: {
        tr: 'Spor arkadaşım',
        en: 'Gym buddy',
        de: 'Trainingspartner',
        ar: 'رفيق النادي',
        fr: 'Pote de muscu',
        es: 'Amigo del gimnasio',
        ja: 'ジム仲間',
        ko: '헬스 메이트',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'spora geliyor musun?',
            en: 'you coming to the gym?',
            de: 'kommst du zum Training?',
            ar: 'هل ستأتي إلى النادي؟',
            fr: 'tu viens à la salle ?',
            es: '¿vienes al gimnasio?',
            ja: 'ジム来る？',
            ko: '헬스장 올 거야?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'geliyorum, eşofmanı giydim bile',
            en: 'yep, already in my gym clothes',
            de: 'klar, hab die Sportsachen schon an',
            ar: 'نعم، لبست ملابس الرياضة',
            fr: "ouais, j'ai déjà mis ma tenue",
            es: 'sí, ya me puse la ropa de deporte',
            ja: '行く行く、もうジャージ着てる',
            ko: '가지, 벌써 운동복 입었어',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'süper! neredesin?',
            en: 'nice! where are you?',
            de: 'super! wo bist du?',
            ar: 'رائع! أين أنت؟',
            fr: "top ! t'es où ?",
            es: '¡genial! ¿dónde estás?',
            ja: 'いいね！今どこ？',
            ko: '오 좋아! 어디야?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'kanepede, ısınıyorum',
            en: 'on the couch, warming up',
            de: 'auf dem Sofa, beim Aufwärmen',
            ar: 'على الأريكة، أقوم بالإحماء',
            fr: "sur le canapé, je m'échauffe",
            es: 'en el sofá, calentando',
            ja: 'ソファでウォーミングアップ中',
            ko: '소파에서 몸 푸는 중',
          },
        },
      ],
    },
    caption: {
      tr: 'Isınmanın 3. günü',
      en: 'Day 3 of warming up',
      de: 'Aufwärmen, Tag 3',
      ar: 'اليوم الثالث من الإحماء',
      fr: 'Échauffement, jour 3',
      es: 'Día 3 de calentamiento',
      ja: 'ウォーミングアップ3日目',
      ko: '몸풀기 3일 차',
    },
  },
  {
    emoji: '🤷',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Cumartesi planı',
        en: 'Saturday plans',
        de: 'Samstagsplan',
        ar: 'خطة السبت',
        fr: 'Plan du samedi',
        es: 'Plan del sábado',
        ja: '土曜の予定',
        ko: '토요일 약속',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'bu cumartesi kesin buluşuyoruz!',
            en: "we're 100% hanging out Saturday!",
            de: 'Samstag treffen wir uns, fix!',
            ar: 'سنلتقي يوم السبت بالتأكيد!',
            fr: "samedi on se voit, c'est sûr !",
            es: '¡este sábado nos vemos sí o sí!',
            ja: '今週の土曜は絶対会おうね！',
            ko: '이번 토요일엔 무조건 보는 거다!',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'süper! saat kaçta?',
            en: 'yes! what time?',
            de: 'cool! um wie viel Uhr?',
            ar: 'رائع! في أي ساعة؟',
            fr: 'trop bien ! à quelle heure ?',
            es: '¡genial! ¿a qué hora?',
            ja: 'やった！何時にする？',
            ko: '좋아! 몇 시에?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bakarız',
            en: "we'll see",
            de: 'mal schauen',
            ar: 'سنرى',
            fr: 'on verra',
            es: 'ya veremos',
            ja: 'また決めよ',
            ko: '그때 봐서',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'nerede peki?',
            en: 'where, though?',
            de: 'und wo?',
            ar: 'وأين؟',
            fr: 'et où ?',
            es: '¿y dónde?',
            ja: '場所は？',
            ko: '어디서?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ona da bakarız',
            en: "we'll see about that too",
            de: 'schauen wir auch mal',
            ar: 'سنرى ذلك أيضًا',
            fr: 'on verra aussi',
            es: 'eso también lo vemos',
            ja: 'それもまた決めよ',
            ko: '그것도 그때 봐서',
          },
        },
      ],
    },
    caption: {
      tr: 'Bu plan asla gerçekleşmeyecek',
      en: 'This plan is never happening',
      de: 'Aus dem Treffen wird nie was',
      ar: 'هذه الخطة لن تتحقق أبدًا',
      fr: "Ce plan n'aura jamais lieu",
      es: 'Este plan nunca va a pasar',
      ja: 'この予定、絶対実現しないやつ',
      ko: '이 약속, 절대 성사 안 됨',
    },
  },
  {
    emoji: '🥚',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Üst kat komşu',
        en: 'Upstairs neighbor',
        de: 'Nachbar von oben',
        ar: 'جار الطابق العلوي',
        fr: 'Voisin du dessus',
        es: 'Vecino de arriba',
        ja: '上の階の人',
        ko: '윗집',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'merhaba, 2 yumurta alabilir miyim?',
            en: 'hi, could I borrow 2 eggs?',
            de: 'hallo, kann ich 2 Eier haben?',
            ar: 'مرحبًا، هل يمكنني أخذ بيضتين؟',
            fr: 'salut, tu peux me dépanner de 2 œufs ?',
            es: 'hola, ¿me prestas 2 huevos?',
            ja: 'こんにちは、卵2個もらえますか？',
            ko: '안녕하세요, 달걀 2개만 빌릴 수 있을까요?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tabii, gelin alın',
            en: 'sure, come grab them',
            de: 'klar, komm vorbei',
            ar: 'طبعًا، تعال خذهما',
            fr: 'bien sûr, passe les prendre',
            es: 'claro, ven a buscarlos',
            ja: 'どうぞ、取りに来てください',
            ko: '그럼요, 가지러 오세요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bir de un, şeker, süt… ve fırınınız',
            en: 'also flour, sugar, milk… and your oven',
            de: 'und Mehl, Zucker, Milch… und deinen Ofen',
            ar: 'وأيضًا طحين وسكر وحليب… وفرنك',
            fr: 'et farine, sucre, lait… et ton four',
            es: 'y harina, azúcar, leche… y tu horno',
            ja: 'あと小麦粉と砂糖と牛乳…とオーブンも',
            ko: '밀가루, 설탕, 우유… 그리고 오븐도요',
          },
        },
      ],
    },
    caption: {
      tr: 'Keki bizde yapıyorlar galiba',
      en: "Pretty sure they're baking at my place",
      de: 'Ich glaub, die backen bei mir',
      ar: 'يبدو أنهم سيخبزون الكعكة عندي',
      fr: "Je crois qu'ils font le gâteau chez moi",
      es: 'Creo que van a hornear en mi casa',
      ja: 'うちのキッチンでケーキ焼く気だ',
      ko: '케이크를 우리 집에서 굽겠다는 거네',
    },
  },
  {
    emoji: '🧥',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kardeşim',
        en: 'Little sis',
        de: 'Schwesterherz',
        ar: 'أختي',
        fr: 'Frangine',
        es: 'Hermanita',
        ja: '妹',
        ko: '여동생',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'mavi kapüşonlunu alabilir miyim?',
            en: 'can I borrow your blue hoodie?',
            de: 'darf ich deinen blauen Hoodie haben?',
            ar: 'هل أستطيع استعارة سترتك الزرقاء؟',
            fr: "je peux t'emprunter ton sweat bleu ?",
            es: '¿me prestas tu sudadera azul?',
            ja: '青いパーカー借りていい？',
            ko: '파란 후드티 빌려도 돼?',
          },
        },
        {
          from: 'me',
          text: { tr: 'hayır', en: 'no', de: 'nein', ar: 'لا', fr: 'non', es: 'no', ja: 'ダメ', ko: '안 돼' },
        },
        {
          from: 'them',
          text: { tr: 'tamam', en: 'ok', de: 'okay', ar: 'حسنًا', fr: 'ok', es: 'ok', ja: 'わかった', ko: '알겠어' },
        },
        {
          from: 'them',
          text: {
            tr: 'şu an üstümde bu arada',
            en: "I'm wearing it rn btw",
            de: 'hab ihn übrigens schon an',
            ar: 'بالمناسبة، أنا أرتديها الآن',
            fr: "je l'ai déjà sur moi au fait",
            es: 'por cierto, ya la tengo puesta',
            ja: 'ちなみに今着てる',
            ko: '참고로 지금 입고 있음',
          },
        },
      ],
    },
    caption: {
      tr: 'Kardeşlerde izin sadece formalite',
      en: 'Asking was just a formality',
      de: 'Fragen war nur eine Formalität',
      ar: 'السؤال كان مجرد إجراء شكلي',
      fr: "Demander, c'était juste pour la forme",
      es: 'Preguntar era pura formalidad',
      ja: '妹の「いい？」はただの事後報告',
      ko: '동생의 “빌려도 돼?”는 그냥 통보임',
    },
  },
  {
    emoji: '📝',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Proje grubu',
        en: 'Group project',
        de: 'Gruppenprojekt',
        ar: 'مجموعة المشروع',
        fr: 'Projet de groupe',
        es: 'Trabajo en grupo',
        ja: 'グループ課題',
        ko: '조별 과제',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'sunum yarın, herkes kısmını bitirdi mi?',
            en: "presentation's tomorrow, everyone done?",
            de: 'Präsentation ist morgen, alle fertig?',
            ar: 'العرض غدًا، هل أنهى الجميع أجزاءهم؟',
            fr: 'exposé demain, tout le monde a fini ?',
            es: 'la presentación es mañana, ¿ya terminaron?',
            ja: '発表明日だけど、みんな自分の分終わった？',
            ko: '발표 내일인데 다들 자기 파트 끝냈어?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'hangi sunum?',
            en: 'what presentation?',
            de: 'welche Präsentation?',
            ar: 'أي عرض؟',
            fr: 'quel exposé ?',
            es: '¿qué presentación?',
            ja: '発表って何の？',
            ko: '무슨 발표?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ben bu grupta mıyım ki?',
            en: 'wait, am I in this group?',
            de: 'Moment, bin ich in der Gruppe?',
            ar: 'لحظة، هل أنا في هذه المجموعة أصلًا؟',
            fr: 'attends, je suis dans le groupe ?',
            es: 'espera, ¿estoy en este grupo?',
            ja: 'え、私このグループだったの？',
            ko: '잠깐, 나 이 조였어?',
          },
        },
      ],
    },
    caption: {
      tr: 'Grup ödevi = tek kişilik ödev',
      en: 'Group project = solo project',
      de: 'Gruppenarbeit = Einzelarbeit',
      ar: 'العمل الجماعي = عمل فردي',
      fr: 'Travail de groupe = travail solo',
      es: 'Trabajo en grupo = trabajo individual',
      ja: 'グループ課題＝ひとり課題',
      ko: '조별 과제 = 개인 과제',
    },
  },
  {
    emoji: '🎙️',
    user: ACCOUNTS.vlog,
    body: {
      format: 'chat',
      contact: { tr: 'Anneannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela', ja: 'おばあちゃん', ko: '할머니' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yavrum sesli mesaj nasıl atılıyor?',
            en: 'sweetie how do I send a voice message?',
            de: 'Schatz, wie geht eine Sprachnachricht?',
            ar: 'يا حبيبي، كيف أرسل رسالة صوتية؟',
            fr: 'mon chéri, comment on envoie un vocal ?',
            es: 'mi amor, ¿cómo mando un audio?',
            ja: 'ねえ、音声メッセージってどうやって送るの？',
            ko: '얘야, 음성 메시지는 어떻게 보내니?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'mikrofona basılı tut anneanne',
            en: 'press and hold the mic, Grandma',
            de: 'Mikro-Taste gedrückt halten, Oma',
            ar: 'اضغطي مطولًا على الميكروفون يا جدتي',
            fr: 'reste appuyée sur le micro, Mamie',
            es: 'mantén presionado el micrófono, abuela',
            ja: 'マイクを長押しするんだよ、おばあちゃん',
            ko: '할머니, 마이크 버튼 길게 누르세요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'tamam tutuyorum',
            en: "ok I'm holding it",
            de: 'okay, ich halte',
            ar: 'حسنًا، أنا أضغط',
            fr: "d'accord, j'appuie",
            es: 'listo, lo estoy presionando',
            ja: 'はいはい、押してるよ',
            ko: '그래, 누르고 있다',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'ALO? ALO?? DUYUYOR MUSUN?',
            en: 'HELLO? HELLO?? CAN YOU HEAR ME?',
            de: 'HALLO? HALLO?? HÖRST DU MICH?',
            ar: 'ألو؟ ألو؟؟ هل تسمعني؟',
            fr: "ALLÔ ? ALLÔ ?? TU M'ENTENDS ?",
            es: '¿HOLA? ¿¿HOLA?? ¿ME OYES?',
            ja: 'もしもし？もしもし？？聞こえる？',
            ko: '여보세요? 여보세요?? 들리니?',
          },
        },
      ],
    },
    caption: {
      tr: 'Anneannemin ilk sesli mesajı (sayılır)',
      en: "Grandma's first voice message (almost)",
      de: 'Omas erste Sprachnachricht (fast)',
      ar: 'أول رسالة صوتية لجدتي (تقريبًا)',
      fr: 'Le premier vocal de Mamie (presque)',
      es: 'El primer audio de mi abuela (casi)',
      ja: 'おばあちゃん初の音声メッセージ（未遂）',
      ko: '할머니의 첫 음성 메시지 (반쯤 성공)',
    },
  },
  {
    emoji: '🤐',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kuzenim',
        en: 'Cousin',
        de: 'Cousine',
        ar: 'ابنة عمي',
        fr: 'Cousine',
        es: 'Prima',
        ja: 'いとこ',
        ko: '사촌',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'sana bir şey anlatmam lazım',
            en: 'I need to tell you something',
            de: 'ich muss dir was erzählen',
            ar: 'يجب أن أخبرك بشيء',
            fr: 'faut que je te raconte un truc',
            es: 'tengo que contarte algo',
            ja: 'ちょっと話したいことがある',
            ko: '너한테 할 말 있어',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ne?? anlat!',
            en: 'what?? tell me!',
            de: 'was?? erzähl!',
            ar: 'ماذا؟؟ أخبريني!',
            fr: 'quoi ?? raconte !',
            es: '¿¿qué?? ¡cuéntame!',
            ja: 'なに？？教えて！',
            ko: '뭔데?? 말해 봐!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yarın yüz yüze anlatırım',
            en: "I'll tell you tomorrow, in person",
            de: 'sag ich dir morgen persönlich',
            ar: 'سأخبرك غدًا وجهًا لوجه',
            fr: 'je te dis demain, en vrai',
            es: 'mañana te cuento en persona',
            ja: '明日会って話す',
            ko: '내일 만나서 말해 줄게',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bunu bana yapamazsın 😭',
            en: "you can't do this to me 😭",
            de: 'das kannst du mir nicht antun 😭',
            ar: 'لا يمكنك أن تفعلي هذا بي 😭',
            fr: 'tu peux pas me faire ça 😭',
            es: 'no me puedes hacer esto 😭',
            ja: 'それはないって 😭',
            ko: '이러는 게 어딨어 😭',
          },
        },
      ],
    },
    caption: {
      tr: 'Yarına kadar nasıl bekleyeceğim?',
      en: 'How am I supposed to wait till tomorrow?',
      de: 'Wie soll ich bis morgen warten?',
      ar: 'كيف سأنتظر حتى الغد؟',
      fr: "Comment je tiens jusqu'à demain ?",
      es: '¿Cómo espero hasta mañana?',
      ja: '明日まで待てるわけないでしょ',
      ko: '내일까지 어떻게 기다려?',
    },
  },
  {
    emoji: '🕚',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Sınıf grubu',
        en: 'Class group chat',
        de: 'Klassenchat',
        ar: 'مجموعة الصف',
        fr: 'Groupe de la classe',
        es: 'Grupo de la clase',
        ja: 'クラスのグループ',
        ko: '반 단톡방',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'ödev ne zamana kadardı?',
            en: "when's the homework due?",
            de: 'bis wann war die Hausaufgabe?',
            ar: 'متى موعد تسليم الواجب؟',
            fr: "le devoir, c'est pour quand ?",
            es: '¿para cuándo es la tarea?',
            ja: '宿題の締め切りいつだっけ？',
            ko: '숙제 언제까지였지?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'bu gece 23.59’a kadar',
            en: 'tonight, 11:59 p.m.',
            de: 'heute bis 23:59',
            ar: 'الليلة حتى 23:59',
            fr: 'ce soir, 23 h 59',
            es: 'hoy, hasta las 23:59',
            ja: '今夜23:59まで',
            ko: '오늘 밤 23:59까지',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'saat kaç şu an?',
            en: 'what time is it now?',
            de: 'wie spät ist es jetzt?',
            ar: 'كم الساعة الآن؟',
            fr: 'il est quelle heure, là ?',
            es: '¿qué hora es?',
            ja: '今何時？',
            ko: '지금 몇 시야?',
          },
        },
        {
          from: 'them',
          text: { tr: '23.51', en: '11:51', de: '23:51', ar: '23:51', fr: '23 h 51', es: '23:51', ja: '23:51', ko: '23:51' },
        },
      ],
    },
    caption: {
      tr: '8 dakikada ödev yapılır mı? Yapılır.',
      en: 'Homework in 8 minutes? Watch me.',
      de: 'Hausaufgabe in 8 Minuten? Geht klar.',
      ar: 'واجب في 8 دقائق؟ تحدٍّ مقبول',
      fr: 'Un devoir en 8 minutes ? Facile.',
      es: '¿Tarea en 8 minutos? Claro que sí.',
      ja: '8分で宿題？余裕です。',
      ko: '8분 만에 숙제? 가능합니다.',
    },
  },
  {
    emoji: '🍔',
    user: ACCOUNTS.food,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'akşam ne yiyelim?',
            en: 'what do you want for dinner?',
            de: 'was essen wir heute Abend?',
            ar: 'ماذا نأكل على العشاء؟',
            fr: 'on mange quoi ce soir ?',
            es: '¿qué cenamos hoy?',
            ja: '夜ごはん何にする？',
            ko: '저녁 뭐 먹을래?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'fark etmez, sen seç',
            en: "idk, anything's fine",
            de: 'egal, such du aus',
            ar: 'لا يهم، اختر أنت',
            fr: 'peu importe, choisis',
            es: 'me da igual, tú elige',
            ja: 'なんでもいいよ',
            ko: '아무거나',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'hamburger?',
            en: 'burgers?',
            de: 'Burger?',
            ar: 'برغر؟',
            fr: 'burger ?',
            es: '¿hamburguesas?',
            ja: 'ハンバーガーは？',
            ko: '햄버거?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'yok, hamburger olmaz',
            en: 'nah, not burgers',
            de: 'nee, bloß keine Burger',
            ar: 'لا، ليس برغر',
            fr: 'ah non, pas de burger',
            es: 'no, hamburguesas no',
            ja: 'ハンバーガーはやだ',
            ko: '햄버거는 좀',
          },
        },
      ],
    },
    caption: {
      tr: '“Fark etmez” = o hariç her şey',
      en: "“Anything's fine” = anything but that",
      de: '„Egal“ = alles, nur nicht das',
      ar: '«لا يهم» تعني: أي شيء إلا هذا',
      fr: '« Peu importe » = tout sauf ça',
      es: '“Me da igual” = todo menos eso',
      ja: '「なんでもいい」＝それ以外なら',
      ko: '“아무거나” = 그거 빼고 아무거나',
    },
  },
  {
    emoji: '🍲',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'Aile grubu',
        en: 'Family group',
        de: 'Familiengruppe',
        ar: 'مجموعة العائلة',
        fr: 'Groupe famille',
        es: 'Grupo familiar',
        ja: '家族グループ',
        ko: '가족 단톡방',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'pazar yemeğine kim geliyor?',
            en: "who's coming to Sunday dinner?",
            de: 'wer kommt Sonntag zum Essen?',
            ar: 'من سيحضر غداء الجمعة؟',
            fr: 'qui vient au repas de dimanche ?',
            es: '¿quién viene a comer el domingo?',
            ja: '日曜のごはん、来る人いる？',
            ko: '일요일 저녁 먹으러 올 사람?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'ben geliyorum!',
            en: 'me!',
            de: 'ich!',
            ar: 'أنا!',
            fr: 'moi !',
            es: '¡yo!',
            ja: 'はい！',
            ko: '나!',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'süper, bulaşıklar sende',
            en: "great, you're on dishes",
            de: 'super, dann spülst du',
            ar: 'ممتاز، غسل الصحون عليك',
            fr: "super, c'est toi qui fais la vaisselle",
            es: 'genial, te toca lavar los platos',
            ja: 'よし、皿洗いよろしく',
            ko: '좋아, 설거지는 네 담당',
          },
        },
      ],
    },
    caption: {
      tr: 'İlk cevap veren kaybeder',
      en: 'First to reply loses',
      de: 'Wer zuerst antwortet, verliert',
      ar: 'من يرد أولًا يخسر',
      fr: 'Le premier qui répond a perdu',
      es: 'El primero en responder pierde',
      ja: '最初に返信した人の負け',
      ko: '먼저 답장하는 사람이 지는 거',
    },
  },
  {
    emoji: '🌙',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kanka',
        en: 'Bestie',
        de: 'Bester Kumpel',
        ar: 'صديقي',
        fr: 'Mon pote',
        es: 'Mi mejor amigo',
        ja: '親友',
        ko: '절친',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'uyudun mu?',
            en: 'you asleep?',
            de: 'schläfst du schon?',
            ar: 'هل نمت؟',
            fr: 'tu dors ?',
            es: '¿ya te dormiste?',
            ja: '寝た？',
            ko: '자?',
          },
        },
        {
          from: 'me',
          text: { tr: 'evet', en: 'yes', de: 'ja', ar: 'نعم', fr: 'oui', es: 'sí', ja: '寝た', ko: '응, 자' },
        },
        {
          from: 'them',
          text: {
            tr: 'uyuyan cevap veremez 🤨',
            en: "sleeping people can't text 🤨",
            de: 'Schlafende schreiben nicht zurück 🤨',
            ar: 'النائم لا يرد على الرسائل 🤨',
            fr: "quelqu'un qui dort répond pas 🤨",
            es: 'los que duermen no contestan 🤨',
            ja: '寝てる人は返信できないでしょ 🤨',
            ko: '자는 사람은 답장 못 하거든 🤨',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'uykumda yazıyorum',
            en: "I'm texting in my sleep",
            de: 'ich schreib im Schlaf',
            ar: 'أنا أرد وأنا نائم',
            fr: 'je réponds en dormant',
            es: 'contesto dormido',
            ja: '寝ながら打ってる',
            ko: '자면서 치는 중',
          },
        },
      ],
    },
    caption: {
      tr: 'Saat 03.00, ikimiz de ekranda',
      en: "3 a.m. and we're both still online",
      de: '3 Uhr nachts, beide noch online',
      ar: 'الساعة 3 فجرًا وكلانا متصل',
      fr: "3 h du mat' et on est encore connectés",
      es: 'Son las 3 a. m. y seguimos conectados',
      ja: '深夜3時、ふたりともまだオンライン',
      ko: '새벽 3시, 둘 다 아직 폰 보는 중',
    },
  },
  {
    emoji: '🧣',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'hırkanı aldın mı?',
            en: 'did you bring a sweater?',
            de: 'hast du eine Jacke dabei?',
            ar: 'هل أخذت سترتك؟',
            fr: "t'as pris un gilet ?",
            es: '¿llevas abrigo?',
            ja: 'カーディガン持った？',
            ko: '카디건 챙겼어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'anne hava 30 derece',
            en: "mom it's 86 degrees",
            de: 'Mama, es sind 30 Grad',
            ar: 'أمي، الحرارة 40 درجة',
            fr: 'maman, il fait 30 degrés',
            es: 'mamá, hace 30 grados',
            ja: 'お母さん、今日30度だよ',
            ko: '엄마 오늘 30도야',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'akşam serinler',
            en: 'it gets chilly at night',
            de: "abends wird's kühl",
            ar: 'سيبرد الجو في المساء',
            fr: 'le soir, ça se rafraîchit',
            es: 'por la noche refresca',
            ja: '夜は冷えるから',
            ko: '저녁엔 쌀쌀해져',
          },
        },
      ],
    },
    caption: {
      tr: 'Annemin hava durumunda hep kış',
      en: "In Mom's forecast, it's always winter",
      de: 'In Mamas Wetterbericht ist immer Winter',
      ar: 'في نشرة أمي الجوية، الشتاء دائمًا',
      fr: "Dans la météo de maman, c'est toujours l'hiver",
      es: 'En el pronóstico de mamá siempre es invierno',
      ja: '母の天気予報は一年中冬',
      ko: '엄마 일기예보는 1년 내내 겨울',
    },
  },
  {
    emoji: '🛒',
    user: ACCOUNTS.plain,
    body: {
      format: 'chat',
      contact: {
        tr: 'Ev arkadaşı',
        en: 'Roommate',
        de: 'Mitbewohner',
        ar: 'زميل السكن',
        fr: 'Coloc',
        es: 'Compañero de casa',
        ja: 'ルームメイト',
        ko: '룸메이트',
      },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'marketteyim, bir şey lazım mı?',
            en: 'at the store, need anything?',
            de: 'bin im Supermarkt, brauchst du was?',
            ar: 'أنا في البقالة، هل تحتاج شيئًا؟',
            fr: 'au supermarché, tu veux quelque chose ?',
            es: 'estoy en el súper, ¿necesitas algo?',
            ja: 'スーパーにいるけど、何かいる？',
            ko: '마트인데 뭐 필요한 거 있어?',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'süt, yumurta, ekmek',
            en: 'milk, eggs, bread',
            de: 'Milch, Eier, Brot',
            ar: 'حليب، بيض، خبز',
            fr: 'du lait, des œufs, du pain',
            es: 'leche, huevos y pan',
            ja: '牛乳と卵とパン',
            ko: '우유, 달걀, 빵',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'tamam 👍',
            en: 'got it 👍',
            de: 'okay 👍',
            ar: 'حسنًا 👍',
            fr: 'ok 👍',
            es: 'listo 👍',
            ja: '了解 👍',
            ko: '오케이 👍',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'cips ve dondurma aldım, geliyorum',
            en: 'got chips and ice cream, omw',
            de: 'hab Chips und Eis, bin gleich da',
            ar: 'اشتريت رقائق ومثلجات، أنا قادم',
            fr: "j'ai pris des chips et une glace, j'arrive",
            es: 'compré helado y galletas, ya voy',
            ja: 'ポテチとアイス買った、今帰る',
            ko: '과자랑 아이스크림 샀어, 가는 중',
          },
        },
      ],
    },
    caption: {
      tr: 'Market listesi sadece bir öneri',
      en: 'Grocery lists are just suggestions',
      de: 'Einkaufslisten sind nur Vorschläge',
      ar: 'قائمة المشتريات مجرد اقتراح',
      fr: "La liste de courses, c'est indicatif",
      es: 'La lista del súper es solo una sugerencia',
      ja: '買い物リストはあくまで参考',
      ko: '장보기 목록은 그냥 참고용',
    },
  },
  {
    emoji: '🐌',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: {
        tr: 'İş arkadaşı',
        en: 'Coworker',
        de: 'Kollegin',
        ar: 'زميلتي في العمل',
        fr: 'Collègue',
        es: 'Compañera de trabajo',
        ja: '同僚',
        ko: '회사 동료',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'yarın cuma, değil mi?',
            en: "tomorrow's Friday, right?",
            de: 'morgen ist Freitag, oder?',
            ar: 'غدًا عطلة نهاية الأسبوع، صحيح؟',
            fr: "demain c'est vendredi, non ?",
            es: 'mañana es viernes, ¿verdad?',
            ja: '明日って金曜だよね？',
            ko: '내일 금요일 맞죠?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'bugün salı',
            en: "it's Tuesday",
            de: 'heute ist Dienstag',
            ar: 'الأسبوع بدأ أمس',
            fr: 'on est mardi',
            es: 'hoy es martes',
            ja: '今日、火曜だよ',
            ko: '오늘 화요일이에요',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'nasıl salı? bir haftadır çalışıyoruz',
            en: "what?? we've been here for a week",
            de: 'wie jetzt? wir arbeiten seit einer Woche',
            ar: 'كيف؟ نحن نعمل منذ أسبوع كامل',
            fr: 'comment ça ? on bosse depuis une semaine',
            es: '¿cómo? llevamos una semana trabajando',
            ja: '火曜？もう1週間働いてるんだけど',
            ko: '화요일이요? 일주일째 일하는 중인데요',
          },
        },
      ],
    },
    caption: {
      tr: 'Salı günü bir hafta sürer',
      en: 'Tuesdays last a whole week',
      de: 'Ein Dienstag dauert eine Woche',
      ar: 'اليوم الثاني من الأسبوع يدوم أسبوعًا',
      fr: 'Un mardi, ça dure une semaine',
      es: 'Los martes duran una semana',
      ja: '火曜日だけで1週間ある',
      ko: '화요일 하나가 일주일 같음',
    },
  },
  {
    emoji: '🌵',
    user: ACCOUNTS.home,
    body: {
      format: 'chat',
      contact: {
        tr: 'Kardeşim',
        en: 'Little sis',
        de: 'Schwesterherz',
        ar: 'أختي',
        fr: 'Frangine',
        es: 'Hermanita',
        ja: '妹',
        ko: '여동생',
      },
      lines: [
        {
          from: 'them',
          text: {
            tr: 'hediye ettiğim kaktüs nasıl?',
            en: "how's the cactus I got you?",
            de: "wie geht's dem Kaktus von mir?",
            ar: 'كيف حال الصبّار الذي أهديتك إياه؟',
            fr: "il va bien, le cactus que je t'ai offert ?",
            es: '¿cómo está el cactus que te regalé?',
            ja: 'あげたサボテン元気？',
            ko: '내가 준 선인장 잘 있어?',
          },
        },
        {
          from: 'me',
          text: {
            tr: 'harika! her gün suluyorum 💧',
            en: 'great! I water it every day 💧',
            de: 'super! ich gieß ihn jeden Tag 💧',
            ar: 'رائع! أسقيه كل يوم 💧',
            fr: "super ! je l'arrose tous les jours 💧",
            es: '¡genial! lo riego todos los días 💧',
            ja: '元気！毎日水あげてる 💧',
            ko: '응! 매일 물 주고 있어 💧',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'o yapay ama',
            en: "it's fake tho",
            de: 'der ist aus Plastik',
            ar: 'لكنه صناعي',
            fr: 'il est en plastique',
            es: 'es de plástico',
            ja: 'それ、偽物だよ',
            ko: '그거 가짜인데',
          },
        },
      ],
    },
    caption: {
      tr: '3 aydır plastik suluyorum',
      en: '3 months of watering plastic',
      de: '3 Monate lang Plastik gegossen',
      ar: '3 أشهر وأنا أسقي البلاستيك',
      fr: "3 mois que j'arrose du plastique",
      es: '3 meses regando plástico',
      ja: '3か月、プラスチックに水やってた',
      ko: '3개월째 플라스틱에 물 주는 중',
    },
  },
  {
    emoji: '🙄',
    user: ACCOUNTS.screens,
    body: {
      format: 'chat',
      contact: { tr: 'Babam', en: 'Dad', de: 'Papa', ar: 'أبي', fr: 'Papa', es: 'Papá', ja: 'お父さん', ko: '아빠' },
      lines: [
        {
          from: 'me',
          text: {
            tr: 'baba acıktım',
            en: "dad I'm hungry",
            de: 'Papa, ich hab Hunger',
            ar: 'أبي، أنا جائع',
            fr: "papa, j'ai faim",
            es: 'papá, tengo hambre',
            ja: 'お父さん、お腹すいた',
            ko: '아빠 배고파',
          },
        },
        {
          from: 'them',
          text: {
            tr: 'Merhaba Acıktım, ben de Baban 😎',
            en: "Hi Hungry, I'm Dad 😎",
            de: 'Hallo Hunger, ich bin Papa 😎',
            ar: 'أهلًا يا جائع، أنا أبوك 😎',
            fr: "Enchanté J'ai faim, moi c'est Papa 😎",
            es: 'Hola, Hambre, soy papá 😎',
            ja: '奇遇だね、電車もすいてるよ 😎',
            ko: '배고프면 배 먹어야지 😎',
          },
        },
      ],
    },
    caption: {
      tr: 'Bu şakayı 15 yıldır yapıyor',
      en: "He's been doing this bit for 15 years",
      de: 'Den Witz macht er seit 15 Jahren',
      ar: 'يكرر هذه النكتة منذ 15 عامًا',
      fr: "Ça fait 15 ans qu'il me la fait, celle-là",
      es: 'Lleva 15 años haciendo ese chiste',
      ja: 'このギャグ、15年続いてる',
      ko: '이 개그를 15년째 하는 중',
    },
  },
];
