import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are one big number (`fact`). Append only: a published post keeps its place. */
export const SKIP_FACT: readonly Draft[] = [
  {
    emoji: '📲',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BUGÜNÜN İSTATİSTİĞİ',
        en: 'STAT OF THE DAY',
        de: 'STATISTIK DES TAGES',
        ar: 'إحصائية اليوم',
        fr: 'LA STAT DU JOUR',
        es: 'EL DATO DEL DÍA',
        ja: '今日の統計',
        ko: '오늘의 통계',
      },
      big: {
        tr: '58',
        en: '58',
        de: '58',
        ar: '58',
        fr: '58',
        es: '58',
        ja: '58',
        ko: '58',
      },
      text: {
        tr: 'kez telefonuna baktın; yeni bildirim yoktu',
        en: 'times you checked your phone. No new notifications.',
        de: 'Mal aufs Handy geschaut. Keine neue Benachrichtigung.',
        ar: 'مرة نظرت إلى هاتفك، ولا إشعار جديد',
        fr: 'fois où tu as regardé ton téléphone. Rien de nouveau.',
        es: 'veces miraste tu teléfono. Nada nuevo.',
        ja: '回スマホを確認。新しい通知はゼロ。',
        ko: '번 휴대폰을 확인했어요. 새 알림은 없었어요.',
      },
    },
    caption: {
      tr: 'Bu da 59 oldu',
      en: 'Make that 59',
      de: 'Jetzt sind es 59',
      ar: 'والآن صارت 59',
      fr: 'Et de 59',
      es: 'Y van 59',
      ja: 'これで59回目',
      ko: '방금 59번이 됐어요',
    },
  },
  {
    emoji: '☂️',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BİLİM İNSANLARI ŞAŞKIN',
        en: 'SCIENTISTS ARE BAFFLED',
        de: 'FORSCHER RÄTSELN',
        ar: 'العلماء في حيرة',
        fr: 'LA SCIENCE EST PERPLEXE',
        es: 'CIENTÍFICOS PERPLEJOS',
        ja: '科学者も困惑',
        ko: '과학자들도 당황',
      },
      big: {
        tr: '0',
        en: '0',
        de: '0',
        ar: '0',
        fr: '0',
        es: '0',
        ja: '0',
        ko: '0',
      },
      text: {
        tr: 'kez şemsiyeni aldığın gün yağmur yağdı',
        en: 'times it rained on a day you took your umbrella',
        de: 'Mal hat es geregnet, wenn du einen Schirm dabeihattest',
        ar: 'مرة أمطرت في يوم حملت فيه مظلتك',
        fr: 'fois où il a plu un jour où tu avais ton parapluie',
        es: 'veces llovió un día que llevabas paraguas',
        ja: '回、傘を持って出た日に雨が降った',
        ko: '번, 우산을 챙긴 날 비가 왔어요',
      },
    },
    caption: {
      tr: 'Bulutlar seni izliyor',
      en: 'The clouds are watching you',
      de: 'Die Wolken beobachten dich',
      ar: 'الغيوم تراقبك',
      fr: 'Les nuages te surveillent',
      es: 'Las nubes te vigilan',
      ja: '雲に見張られている',
      ko: '구름이 당신을 지켜보고 있어요',
    },
  },
  {
    emoji: '🎙️',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '7',
        en: '7',
        de: '7',
        ar: '7',
        fr: '7',
        es: '7',
        ja: '7',
        ko: '7',
      },
      text: {
        tr: 'dakikalık sesli mesaj geldi; özeti: “tamam”',
        en: 'minutes of voice messages. The gist: “okay.”',
        de: 'Minuten Sprachnachricht. Kurz gesagt: „okay“',
        ar: 'دقائق من رسالة صوتية… خلاصتها: «حسنًا»',
        fr: 'minutes de vocal. En résumé : « ok »',
        es: 'minutos de audio. En resumen: “ok”',
        ja: '分のボイスメッセージ。要約すると「OK」。',
        ko: '분짜리 음성 메시지. 요약: “알겠어.”',
      },
    },
    caption: {
      tr: 'İki kat hızda bile bitmedi',
      en: 'Even at 2x speed, it never ends',
      de: 'Selbst in doppeltem Tempo endlos',
      ar: 'حتى بالسرعة المضاعفة لم تنتهِ',
      fr: 'Même en accéléré, interminable',
      es: 'Ni al doble de velocidad se acababa',
      ja: '2倍速でも終わらない',
      ko: '2배속으로 들어도 안 끝나요',
    },
  },
  {
    emoji: '🔑',
    user: ACCOUNTS.home,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '14',
        en: '14',
        de: '14',
        ar: '14',
        fr: '14',
        es: '14',
        ja: '14',
        ko: '14',
      },
      text: {
        tr: 'dakika anahtarını aradın; elindeydi',
        en: 'minutes looking for your keys. They were in your hand.',
        de: 'Minuten den Schlüssel gesucht. Er war in deiner Hand.',
        ar: 'دقيقة بحثت عن مفاتيحك… وكانت في يدك',
        fr: 'minutes à chercher tes clés. Elles étaient dans ta main.',
        es: 'minutos buscando tus llaves. Las tenías en la mano.',
        ja: '分、鍵を探した。手に持っていた。',
        ko: '분 동안 열쇠를 찾았어요. 손에 들고 있었어요.',
      },
    },
    caption: {
      tr: 'Yarın cebinde olacak',
      en: "Tomorrow they'll be in your pocket",
      de: 'Morgen steckt er in der Hosentasche',
      ar: 'غدًا ستكون في جيبك',
      fr: 'Demain, elles seront dans ta poche',
      es: 'Mañana estarán en tu bolsillo',
      ja: '明日はポケットの中にある',
      ko: '내일은 주머니에 있을 거예요',
    },
  },
  {
    emoji: '🔐',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU HAFTA',
        en: 'THIS WEEK',
        de: 'DIESE WOCHE',
        ar: 'هذا الأسبوع',
        fr: 'CETTE SEMAINE',
        es: 'ESTA SEMANA',
        ja: '今週',
        ko: '이번 주',
      },
      big: {
        tr: '9',
        en: '9',
        de: '9',
        ar: '9',
        fr: '9',
        es: '9',
        ja: '9',
        ko: '9',
      },
      text: {
        tr: 'kez “şifremi unuttum”a bastın',
        en: 'times you tapped “forgot password”',
        de: 'Mal auf „Passwort vergessen“ getippt',
        ar: 'مرات ضغطت على «نسيت كلمة المرور»',
        fr: 'fois où tu as appuyé sur « mot de passe oublié »',
        es: 'veces tocaste “olvidé mi contraseña”',
        ja: '回「パスワードを忘れた」を押した',
        ko: '번 “비밀번호 찾기”를 눌렀어요',
      },
    },
    caption: {
      tr: 'Yenisini de unuttun bile',
      en: 'And you already forgot the new one',
      de: 'Das neue ist auch schon vergessen',
      ar: 'ونسيت الجديدة أيضًا',
      fr: "T'as déjà oublié le nouveau",
      es: 'Ya olvidaste la nueva también',
      ja: '新しいのももう忘れた',
      ko: '새 비밀번호도 벌써 잊었죠',
    },
  },
  {
    emoji: '🔇',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '8',
        en: '8',
        de: '8',
        ar: '8',
        fr: '8',
        es: '8',
        ja: '8',
        ko: '8',
      },
      text: {
        tr: 'kez mikrofon kapalıyken koca bir sunum yaptın',
        en: 'times you gave a whole presentation on mute',
        de: 'Mal einen ganzen Vortrag bei stummem Mikro gehalten',
        ar: 'مرات قدّمت عرضًا كاملًا والميكروفون مغلق',
        fr: 'fois où tu as fait tout un exposé micro coupé',
        es: 'veces diste toda una presentación con el micro apagado',
        ja: '回、ミュートのまま熱いプレゼンをした',
        ko: '번, 음소거 상태로 발표를 끝까지 했어요',
      },
    },
    caption: {
      tr: 'En iyi sunumun buydu',
      en: 'Your best one yet',
      de: 'Dein bester bisher',
      ar: 'كان أفضل عروضك',
      fr: 'Ton meilleur à ce jour',
      es: 'La mejor que has dado',
      ja: '過去最高のプレゼンだった',
      ko: '인생 최고의 발표였어요',
    },
  },
  {
    emoji: '🍿',
    user: ACCOUNTS.vlog,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '40',
        en: '40',
        de: '40',
        ar: '40',
        fr: '40',
        es: '40',
        ja: '40',
        ko: '40',
      },
      text: {
        tr: 'dakika ne izleyeceğini seçtin, sonra uyuyakaldın',
        en: 'minutes picking something to watch. Then you fell asleep.',
        de: 'Minuten nach einer Serie gesucht. Dann eingeschlafen.',
        ar: 'دقيقة تختار ما ستشاهده… ثم نمت',
        fr: 'minutes à choisir quoi regarder. Puis dodo.',
        es: 'minutos eligiendo qué ver. Luego te dormiste.',
        ja: '分かけて観るものを選び、そのまま寝落ち',
        ko: '분 동안 볼 걸 고르다가 잠들었어요',
      },
    },
    caption: {
      tr: 'Yarın kaldığın yerden: seçmeye',
      en: 'Tomorrow: back to picking',
      de: 'Morgen geht die Suche weiter',
      ar: 'غدًا تكمل من حيث توقفت: الاختيار',
      fr: 'Demain, on reprend le choix',
      es: 'Mañana sigues eligiendo',
      ja: '明日は続きから：選ぶところ',
      ko: '내일은 이어서: 고르기부터',
    },
  },
  {
    emoji: '🤳',
    user: ACCOUNTS.trends,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '300',
        en: '300',
        de: '300',
        ar: '300',
        fr: '300',
        es: '300',
        ja: '300',
        ko: '300',
      },
      text: {
        tr: 'fotoğraf çektin; paylaştığın yine ilk çekilendi',
        en: 'photos taken. You posted the very first one.',
        de: 'Fotos gemacht. Gepostet hast du das allererste.',
        ar: 'صورة التقطتها… ونشرت أول واحدة',
        fr: 'photos prises. Tu as posté la toute première.',
        es: 'fotos tomadas. Publicaste la primera.',
        ja: '枚写真を撮った。投稿したのは1枚目。',
        ko: '장 사진을 찍었어요. 올린 건 첫 번째 사진.',
      },
    },
    caption: {
      tr: 'İlk içgüdü hep haklıdır',
      en: 'Always trust your first instinct',
      de: 'Der erste Instinkt hat immer recht',
      ar: 'الإحساس الأول دائمًا على حق',
      fr: 'Le premier instinct a toujours raison',
      es: 'El primer instinto nunca falla',
      ja: '最初の直感はいつも正しい',
      ko: '첫 느낌은 언제나 옳아요',
    },
  },
  {
    emoji: '📞',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'BU AY',
        en: 'THIS MONTH',
        de: 'DIESEN MONAT',
        ar: 'هذا الشهر',
        fr: 'CE MOIS-CI',
        es: 'ESTE MES',
        ja: '今月',
        ko: '이번 달',
      },
      big: {
        tr: '21',
        en: '21',
        de: '21',
        ar: '21',
        fr: '21',
        es: '21',
        ja: '21',
        ko: '21',
      },
      text: {
        tr: 'kez annene “sonra ararım” dedin',
        en: "times you told Mom “I'll call you later”",
        de: 'Mal zu Mama gesagt: „Ich ruf später an“',
        ar: 'مرة قلت لأمك «سأتصل بك لاحقًا»',
        fr: 'fois où tu as dit à ta mère « je te rappelle »',
        es: 'veces le dijiste a tu mamá “luego te llamo”',
        ja: '回、母に「あとで電話する」と言った',
        ko: '번 엄마한테 “이따 전화할게”라고 했어요',
      },
    },
    caption: {
      tr: 'Annen bu postu gördü',
      en: 'Your mom saw this post',
      de: 'Mama hat diesen Post gesehen',
      ar: 'أمك رأت هذا المنشور',
      fr: 'Ta mère a vu ce post',
      es: 'Tu mamá vio este post',
      ja: 'お母さんがこの投稿を見ました',
      ko: '엄마가 이 게시물을 봤어요',
    },
  },
  {
    emoji: '🚪',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '5',
        en: '5',
        de: '5',
        ar: '5',
        fr: '5',
        es: '5',
        ja: '5',
        ko: '5',
      },
      text: {
        tr: 'kez bir odaya girip neden girdiğini unuttun',
        en: 'times you walked into a room and forgot why',
        de: 'Mal in einen Raum gegangen und vergessen, wozu',
        ar: 'مرات دخلت غرفة ونسيت لماذا',
        fr: 'fois où tu as oublié pourquoi tu entrais dans la pièce',
        es: 'veces entraste a una habitación y olvidaste para qué',
        ja: '回、部屋に入って何しに来たか忘れた',
        ko: '번 방에 들어가서 왜 왔는지 잊었어요',
      },
    },
    caption: {
      tr: 'Altıncıda hatırlarsın',
      en: "You'll remember on the sixth",
      de: 'Beim sechsten Mal fällt es dir ein',
      ar: 'ستتذكر في المرة السادسة',
      fr: 'Ça te reviendra à la sixième',
      es: 'A la sexta te acordarás',
      ja: '6回目で思い出す',
      ko: '여섯 번째엔 기억날 거예요',
    },
  },
  {
    emoji: '🎟️',
    user: ACCOUNTS.plain,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '4',
        en: '4',
        de: '4',
        ar: '4',
        fr: '4',
        es: '4',
        ja: '4',
        ko: '4',
      },
      text: {
        tr: 'kez “iyi seyirler” diyene “size de” dedin',
        en: 'times someone said “enjoy the movie” and you said “you too”',
        de: 'Mal auf „Viel Spaß beim Film“ mit „Ihnen auch“ geantwortet',
        ar: 'مرات قيل لك «مشاهدة ممتعة» فقلت «ولك أيضًا»',
        fr: 'fois où tu as répondu « vous aussi » à « bon film »',
        es: 'veces respondiste “tú también” a “que disfrutes la película”',
        ja: '回「いってらっしゃい」に「いってらっしゃい」と返した',
        ko: '번 “맛있게 드세요”에 “네, 맛있게 드세요”라고 했어요',
      },
    },
    caption: {
      tr: 'Hâlâ düşünüyorsun, biliyoruz',
      en: "You're still thinking about it. We know.",
      de: 'Du denkst immer noch daran. Wir wissen es.',
      ar: 'ما زلت تفكر في الأمر، نعلم ذلك',
      fr: 'Tu y penses encore, on le sait',
      es: 'Todavía lo piensas, lo sabemos',
      ja: '今でも思い出すよね。知ってる。',
      ko: '아직도 생각나죠? 다 알아요.',
    },
  },
  {
    emoji: '💻',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '15',
        en: '15',
        de: '15',
        ar: '15',
        fr: '15',
        es: '15',
        ja: '15',
        ko: '15',
      },
      text: {
        tr: 'sekme açık; müzik hangisinden geliyor, bilmiyorsun',
        en: "tabs open. You can't tell which one is playing music.",
        de: 'Tabs offen. Welcher spielt Musik? Keine Ahnung.',
        ar: 'تبويبًا مفتوحًا… ولا تعرف أيها يشغّل الموسيقى',
        fr: 'onglets ouverts. Lequel joue de la musique ? Mystère.',
        es: 'pestañas abiertas y no sabes cuál tiene música',
        ja: '個のタブが開いてる。音楽がどれから流れてるか不明。',
        ko: '개의 탭이 열려 있어요. 어디서 음악이 나오는지 몰라요.',
      },
    },
    caption: {
      tr: 'Tek tek kapatmaya başladın',
      en: 'Time to close them one by one',
      de: 'Also schließt du einen nach dem anderen',
      ar: 'بدأت تغلقها واحدًا تلو الآخر',
      fr: "C'est parti pour les fermer un par un",
      es: 'Toca cerrarlas una por una',
      ja: '1個ずつ閉じていく時間',
      ko: '하나씩 닫아 보는 중',
    },
  },
  {
    emoji: '🔋',
    user: ACCOUNTS.hacks,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '%12',
        en: '12%',
        de: '12 %',
        ar: '12%',
        fr: '12 %',
        es: '12 %',
        ja: '12%',
        ko: '12%',
      },
      text: {
        tr: 'şarjla evden çıktın; şarj aleti evde kaldı',
        en: 'battery when you left. The charger stayed home.',
        de: 'Akku beim Losgehen. Das Ladekabel blieb zu Hause.',
        ar: 'شحن عند خروجك… والشاحن بقي في البيت',
        fr: 'de batterie en partant. Le chargeur est resté chez toi.',
        es: 'de batería al salir. El cargador se quedó en casa.',
        ja: 'の充電で家を出た。充電器は家にある。',
        ko: '배터리로 외출했어요. 충전기는 집에 두고요.',
      },
    },
    caption: {
      tr: 'Bugünkü görev: priz bulmak',
      en: "Today's quest: find an outlet",
      de: 'Tagesquest: Steckdose finden',
      ar: 'مهمة اليوم: إيجاد مقبس كهرباء',
      fr: 'Quête du jour : trouver une prise',
      es: 'Misión del día: encontrar un enchufe',
      ja: '今日のクエスト：コンセントを探せ',
      ko: '오늘의 퀘스트: 콘센트 찾기',
    },
  },
  {
    emoji: '🛗',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '16',
        en: '16',
        de: '16',
        ar: '16',
        fr: '16',
        es: '16',
        ja: '16',
        ko: '16',
      },
      text: {
        tr: 'kez asansör düğmesine bastın; daha hızlı gelmedi',
        en: "times you pressed the elevator button. It didn't come faster.",
        de: 'Mal den Aufzugknopf gedrückt. Schneller kam er nicht.',
        ar: 'مرة ضغطت زر المصعد… ولم يأتِ أسرع',
        fr: "fois où tu as appuyé sur l'ascenseur. Il prend son temps.",
        es: 'veces presionaste el botón del ascensor. No llegó antes.',
        ja: '回エレベーターのボタンを押した。早くは来なかった。',
        ko: '번 엘리베이터 버튼을 눌렀어요. 더 빨리 오진 않았어요.',
      },
    },
    caption: {
      tr: 'Bir sonrakinde kesin gelir',
      en: 'One more press should do it',
      de: 'Noch einmal drücken, dann kommt er',
      ar: 'ضغطة أخرى وسيأتي حتمًا',
      fr: 'Encore un appui et il arrive',
      es: 'Una vez más y seguro que llega',
      ja: '次押せば絶対来る',
      ko: '한 번만 더 누르면 올 거예요',
    },
  },
  {
    emoji: '🎧',
    user: ACCOUNTS.vlog,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '90',
        en: '90',
        de: '90',
        ar: '90',
        fr: '90',
        es: '90',
        ja: '90',
        ko: '90',
      },
      text: {
        tr: 'dakikadır kulaklık takılı; müzik açık bile değil',
        en: 'minutes with headphones on. No music playing.',
        de: 'Minuten Kopfhörer auf. Musik läuft keine.',
        ar: 'دقيقة والسماعات في أذنيك… بلا أي موسيقى',
        fr: 'minutes avec tes écouteurs. Zéro musique.',
        es: 'minutos con auriculares puestos. Sin música.',
        ja: '分イヤホンをしてる。音楽は流れてない。',
        ko: '분째 이어폰을 끼고 있어요. 음악은 안 틀었어요.',
      },
    },
    caption: {
      tr: 'Sadece kimse konuşmasın diye',
      en: 'Just so nobody talks to you',
      de: 'Nur damit dich keiner anspricht',
      ar: 'فقط كي لا يكلمك أحد',
      fr: "Juste pour qu'on te laisse tranquille",
      es: 'Solo para que nadie te hable',
      ja: '話しかけられないためだけに',
      ko: '아무도 말 못 걸게 하려고요',
    },
  },
  {
    emoji: '🕒',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '10',
        en: '10',
        de: '10',
        ar: '10',
        fr: '10',
        es: '10',
        ja: '10',
        ko: '10',
      },
      text: {
        tr: 'kez saate bakmak için telefonu açtın; saat kaç, bilmiyorsun',
        en: 'times you checked your phone for the time. Still no idea.',
        de: 'Mal aufs Handy geschaut, wie spät es ist. Keine Ahnung.',
        ar: 'مرات فتحت هاتفك لتعرف الوقت… وما زلت لا تعرفه',
        fr: "fois où tu as regardé l'heure. Tu ne la connais toujours pas.",
        es: 'veces miraste la hora en el teléfono. Sigues sin saberla.',
        ja: '回、時間を見るためにスマホを開いた。今何時か知らない。',
        ko: '번 시간 보려고 휴대폰을 켰어요. 몇 시인지는 몰라요.',
      },
    },
    caption: {
      tr: 'Hadi, şimdi saat kaç?',
      en: 'Quick: what time is it?',
      de: 'Schnell: Wie spät ist es?',
      ar: 'بسرعة: كم الساعة الآن؟',
      fr: 'Vite : il est quelle heure ?',
      es: 'Rápido: ¿qué hora es?',
      ja: 'はい、今何時？',
      ko: '자, 지금 몇 시죠?',
    },
  },
  {
    emoji: '🥄',
    user: ACCOUNTS.food,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '17',
        en: '17',
        de: '17',
        ar: '17',
        fr: '17',
        es: '17',
        ja: '17',
        ko: '17',
      },
      text: {
        tr: 'kez “bir tadına bakayım” dedin; tencere yarılandı',
        en: "times you said “just a taste.” The pot's half empty.",
        de: 'Mal „nur kurz probieren“. Der Topf ist halb leer.',
        ar: 'مرة قلت «سأتذوّق فقط»… ونصف القِدر اختفى',
        fr: 'fois « juste pour goûter ». La casserole est à moitié vide.',
        es: 'veces dijiste “solo lo pruebo”. La olla va por la mitad.',
        ja: '回「味見だけ」と言った。鍋はもう半分。',
        ko: '번 “맛만 볼게”라고 했어요. 냄비가 반이 됐어요.',
      },
    },
    caption: {
      tr: 'Akşam yemeği: tadımlık',
      en: 'Dinner: tasting menu',
      de: 'Abendessen: Probierportion',
      ar: 'العشاء: حصة تذوّق',
      fr: 'Dîner : menu dégustation',
      es: 'Cena: menú degustación',
      ja: '夕食：試食コース',
      ko: '저녁 메뉴: 시식 코스',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.trends,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '3',
        en: '3',
        de: '3',
        ar: '3',
        fr: '3',
        es: '3',
        ja: '3',
        ko: '3',
      },
      text: {
        tr: 'beğeni: annen, teyzen ve yanlışlıkla sen',
        en: 'likes: your mom, your aunt, and you by accident',
        de: 'Likes: Mama, Tante und aus Versehen du selbst',
        ar: 'إعجابات: أمك، خالتك، وأنت بالخطأ',
        fr: 'likes : ta mère, ta tante et toi, par erreur',
        es: 'me gusta: tu mamá, tu tía y tú sin querer',
        ja: 'いいね：母、おば、うっかり押した自分',
        ko: '개의 좋아요: 엄마, 이모, 실수로 누른 나',
      },
    },
    caption: {
      tr: 'Viral olmaya ramak kaldı',
      en: 'Basically viral',
      de: 'Quasi viral',
      ar: 'على وشك أن يصبح ترندًا',
      fr: 'Quasiment viral',
      es: 'Prácticamente viral',
      ja: 'バズる寸前',
      ko: '거의 떡상 직전',
    },
  },
  {
    emoji: '🍕',
    user: ACCOUNTS.food,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '6',
        en: '6',
        de: '6',
        ar: '6',
        fr: '6',
        es: '6',
        ja: '6',
        ko: '6',
      },
      text: {
        tr: 'dilim pizzanı “aç değilim” diyenler yedi',
        en: "slices of your pizza, eaten by people who “weren't hungry”",
        de: 'Stück deiner Pizza – gegessen von Leuten „ohne Hunger“',
        ar: 'شرائح من بيتزاك أكلها من قالوا «لست جائعًا»',
        fr: "parts de ta pizza, mangées par ceux qui « n'avaient pas faim »",
        es: 'porciones de tu pizza se comieron los que “no tenían hambre”',
        ja: '切れのピザを「お腹すいてない」人たちが食べた',
        ko: '조각의 피자를 “배 안 고프다”던 사람들이 먹었어요',
      },
    },
    caption: {
      tr: 'Bir dahaki sefere büyük boy',
      en: 'Order a large next time',
      de: 'Nächstes Mal die große',
      ar: 'في المرة القادمة: الحجم الكبير',
      fr: 'La prochaine fois, prends la grande',
      es: 'La próxima, pide la grande',
      ja: '次はLサイズで',
      ko: '다음엔 라지로 시켜요',
    },
  },
  {
    emoji: '🦶',
    user: ACCOUNTS.facts,
    body: {
      format: 'fact',
      eyebrow: {
        tr: 'ARAŞTIRMALARA GÖRE',
        en: 'STUDIES SHOW',
        de: 'STUDIEN ZEIGEN',
        ar: 'تقول الدراسات',
        fr: 'SELON LES ÉTUDES',
        es: 'SEGÚN LOS ESTUDIOS',
        ja: '研究によると',
        ko: '연구 결과에 따르면',
      },
      big: {
        tr: '1',
        en: '1',
        de: '1',
        ar: '1',
        fr: '1',
        es: '1',
        ja: '1',
        ko: '1',
      },
      text: {
        tr: 'ayak yorganın dışında: kusursuz uyku sıcaklığı',
        en: 'foot out of the blanket: the perfect sleep temperature',
        de: 'Fuß raus aus der Decke: perfekte Schlaftemperatur',
        ar: 'قدم خارج البطانية: حرارة النوم المثالية',
        fr: 'pied hors de la couette : la température parfaite',
        es: 'pie fuera de la manta: la temperatura perfecta',
        ja: '本の足を布団から出す。それが理想の寝る温度。',
        ko: '쪽 발만 이불 밖에: 완벽한 수면 온도',
      },
    },
    caption: {
      tr: 'Bilim bunu hâlâ açıklayamıyor',
      en: "Science still can't explain it",
      de: 'Die Wissenschaft rätselt noch',
      ar: 'ولا يزال العلم عاجزًا عن تفسير ذلك',
      fr: "La science ne l'explique toujours pas",
      es: 'La ciencia aún no lo explica',
      ja: '科学でもまだ説明できない',
      ko: '과학도 아직 설명 못 해요',
    },
  },
  {
    emoji: '⏲️',
    user: ACCOUNTS.hacks,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '23',
        en: '23',
        de: '23',
        ar: '23',
        fr: '23',
        es: '23',
        ja: '23',
        ko: '23',
      },
      text: {
        tr: 'kez mikrodalgayı bip sesinden hemen önce durdurdun',
        en: 'times you stopped the microwave right before the beep',
        de: 'Mal die Mikrowelle kurz vor dem Piepen gestoppt',
        ar: 'مرة أوقفت الميكروويف قبل الصفارة بلحظة',
        fr: 'fois où tu as arrêté le micro-ondes juste avant le bip',
        es: 'veces paraste el microondas justo antes del pitido',
        ja: '回、電子レンジを「チン」の直前で止めた',
        ko: '번 전자레인지를 “띵” 소리 직전에 멈췄어요',
      },
    },
    caption: {
      tr: 'Gizli ajan modu: açık',
      en: 'Secret agent mode: on',
      de: 'Geheimagenten-Modus: an',
      ar: 'وضع العميل السري: مفعَّل',
      fr: 'Mode agent secret : activé',
      es: 'Modo agente secreto: activado',
      ja: 'スパイモード：オン',
      ko: '비밀 요원 모드: 켜짐',
    },
  },
  {
    emoji: '📶',
    user: ACCOUNTS.home,
    body: {
      format: 'fact',
      eyebrow: null,
      big: {
        tr: '11',
        en: '11',
        de: '11',
        ar: '11',
        fr: '11',
        es: '11',
        ja: '11',
        ko: '11',
      },
      text: {
        tr: 'denemede arkadaşının wifi şifresini girebildin',
        en: "tries to get your friend's Wi-Fi password right",
        de: 'Versuche, bis das WLAN-Passwort bei Freunden stimmte',
        ar: 'محاولة حتى أدخلت كلمة سر الواي فاي عند صديقك',
        fr: 'essais pour taper le code wifi chez tes potes',
        es: 'intentos para escribir bien la contraseña del wifi',
        ja: '回目で友だちのWi-Fiパスワードを入力できた',
        ko: '번 만에 친구 와이파이 비밀번호를 맞혔어요',
      },
    },
    caption: {
      tr: 'Büyük I mı, küçük l mi?',
      en: 'Capital I or lowercase l?',
      de: 'Großes I oder kleines l?',
      ar: 'حرف كبير أم صغير؟',
      fr: 'I majuscule ou l minuscule ?',
      es: '¿I mayúscula o l minúscula?',
      ja: '大文字のI？小文字のl？',
      ko: '대문자 I야, 소문자 l이야?',
    },
  },
];
