import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are polls (`poll`). Append only: a published post keeps its place. */
export const SKIP_POLL: readonly Draft[] = [
  {
    emoji: '🛗',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Asansörde biriyle baş başasın. Sen:',
        en: 'Alone in an elevator with someone. You:',
        de: 'Allein im Aufzug mit jemandem. Du:',
        ar: 'وحدك مع شخص في المصعد. ماذا تفعل؟',
        fr: 'Ascenseur, toi et un inconnu. Tu fais quoi ?',
        es: 'A solas en el ascensor con alguien. Tú:',
      },
      options: [
        {
          tr: 'Sohbet ederim',
          en: 'Make small talk',
          de: 'Smalltalk machen',
          ar: 'أبدأ حديثًا',
          fr: 'Je fais la causette',
          es: 'Hago conversación',
        },
        {
          tr: 'Telefona bakarım',
          en: 'Stare at my phone',
          de: 'Aufs Handy starren',
          ar: 'أحدّق في هاتفي',
          fr: 'Je fixe mon téléphone',
          es: 'Miro el teléfono',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Çekmiyor ama bakıyorum',
      en: 'No signal. Still staring.',
      de: 'Kein Empfang. Ich starre trotzdem.',
      ar: 'لا توجد تغطية، لكنني أحدّق رغم ذلك',
      fr: 'Pas de réseau. Je fixe quand même.',
      es: 'Sin señal. Igual lo miro.',
    },
  },
  {
    emoji: '🚪',
    user: ACCOUNTS.plain,
    body: {
      format: 'poll',
      question: {
        tr: 'Kapıda “İTİNİZ” yazıyor. Sen:',
        en: 'The door says “PUSH.” You:',
        de: 'An der Tür steht „DRÜCKEN“. Du:',
        ar: 'مكتوب على الباب «ادفع». أنت:',
        fr: 'La porte dit « POUSSEZ ». Toi :',
        es: 'La puerta dice “EMPUJE”. Tú:',
      },
      options: [
        { tr: 'İttim', en: 'Pushed', de: 'Gedrückt', ar: 'دفعت', fr: "J'ai poussé", es: 'Empujé' },
        { tr: 'Çektim', en: 'Pulled', de: 'Gezogen', ar: 'سحبت', fr: "J'ai tiré", es: 'Hice lo contrario' },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Her. Seferinde.',
      en: 'Every. Single. Time.',
      de: 'Jedes. Einzelne. Mal.',
      ar: 'في كل مرة، بلا استثناء',
      fr: 'À chaque fois. Sans exception.',
      es: 'Siempre. Sin excepción.',
    },
  },
  {
    emoji: '🔊',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Otobüste video açtın. Kulaklık bağlı mı?',
        en: 'You play a video on the bus. Earbuds on?',
        de: 'Du startest im Bus ein Video. Kopfhörer an?',
        ar: 'شغّلت فيديو في الحافلة. هل السماعات متصلة؟',
        fr: 'Tu lances une vidéo dans le bus. Écouteurs ?',
        es: 'Pones un video en el bus. ¿Y los auriculares?',
      },
      options: [
        { tr: 'Bağlı tabii', en: 'Of course', de: 'Klar', ar: 'بالطبع', fr: 'Bien sûr', es: 'Claro' },
        {
          tr: 'Değilmiş, herkes duydu',
          en: 'Nope. Everyone heard.',
          de: 'Nein, alle hören mit',
          ar: 'لا، وسمع الجميع',
          fr: 'Oups, pas connectés',
          es: 'No. Todos oyeron.',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Otobüs artık her şeyi biliyor',
      en: 'The whole bus knows now',
      de: 'Jetzt weiß es der ganze Bus',
      ar: 'الآن تعرف الحافلة كلها',
      fr: 'Maintenant, tout le bus sait',
      es: 'Ahora todo el bus lo sabe',
    },
  },
  {
    emoji: '🙈',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Biri el salladı, sen de. Kime sallamış?',
        en: 'Someone waves. You wave back. It was for:',
        de: 'Jemand winkt, du winkst zurück. Es galt:',
        ar: 'لوّح لك أحدهم فلوّحت له. لمن كان يلوّح؟',
        fr: "On te fait coucou, tu réponds. C'était pour qui ?",
        es: 'Alguien saluda y respondes. ¿A quién saludaba?',
      },
      options: [
        {
          tr: 'Arkamdakine',
          en: 'The person behind me',
          de: 'Dem hinter mir',
          ar: 'لمن يقف خلفي',
          fr: 'La personne derrière',
          es: 'Al de atrás',
        },
        { tr: 'Bana', en: 'Me', de: 'Mir', ar: 'لي', fr: 'Moi', es: 'A mí' },
      ],
      winner: 0,
    },
    caption: {
      tr: 'Saçımı düzeltiyormuş gibi yaptım',
      en: 'I pretended to fix my hair',
      de: 'Tat so, als würde ich mein Haar richten',
      ar: 'فتظاهرت بأنني أرتّب شعري',
      fr: "J'ai fait semblant de me recoiffer",
      es: 'Fingí que me arreglaba el pelo',
    },
  },
  {
    emoji: '🧭',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Telefondan harita takip ediyorsun. Sen:',
        en: "You're following the map on your phone. You:",
        de: 'Du folgst der Karte auf dem Handy. Du:',
        ar: 'تتبع الخريطة على هاتفك. ماذا تفعل؟',
        fr: 'Tu suis la carte sur ton téléphone. Et là ?',
        es: 'Sigues el mapa en el teléfono. Tú:',
      },
      options: [
        {
          tr: 'Telefonla dönerim',
          en: 'Spin around with it',
          de: 'Mich mit ihm drehen',
          ar: 'أدور مع الهاتف',
          fr: 'Je tourne avec',
          es: 'Giro con él',
        },
        {
          tr: 'Direkt yürürüm',
          en: 'Just walk',
          de: 'Einfach losgehen',
          ar: 'أمشي مباشرة',
          fr: 'Je marche',
          es: 'Camino y ya',
        },
      ],
      winner: 0,
    },
    caption: {
      tr: '3 tur döndüm, hâlâ yanlış yön',
      en: 'Three spins later, still wrong way',
      de: 'Drei Drehungen später: falsche Richtung',
      ar: 'بعد 3 دورات، ما زلت في الاتجاه الخطأ',
      fr: 'Trois tours plus tard : mauvais sens',
      es: 'Tres vueltas después, sigo mal',
    },
  },
  {
    emoji: '💡',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Işığı kapattın. Yatağa nasıl gidersin?',
        en: 'Lights off. How do you get to bed?',
        de: 'Licht aus. Wie kommst du ins Bett?',
        ar: 'أطفأت النور. كيف تصل إلى سريرك؟',
        fr: 'Lumière éteinte. Tu vas au lit comment ?',
        es: 'Apagaste la luz. ¿Cómo llegas a la cama?',
      },
      options: [
        { tr: 'Yürüyerek', en: 'Walk', de: 'Gehen', ar: 'مشيًا', fr: 'En marchant', es: 'Caminando' },
        {
          tr: 'Koşup atlayarak',
          en: 'Sprint and jump',
          de: 'Rennen und springen',
          ar: 'ركضًا ثم قفزًا',
          fr: 'En sprint, puis saut',
          es: 'Corriendo y saltando',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Karanlıkta yeni hız rekoru',
      en: 'New speed record in the dark',
      de: 'Neuer Geschwindigkeitsrekord im Dunkeln',
      ar: 'رقم قياسي جديد في السرعة، في الظلام',
      fr: 'Nouveau record de vitesse dans le noir',
      es: 'Nuevo récord de velocidad a oscuras',
    },
  },
  {
    emoji: '🗑️',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Çöp kovası doldu. Plan ne?',
        en: "The trash is full. What's the plan?",
        de: 'Der Mülleimer ist voll. Der Plan?',
        ar: 'امتلأت سلة المهملات. ما الخطة؟',
        fr: 'La poubelle déborde. Le plan ?',
        es: 'La basura está llena. ¿Cuál es el plan?',
      },
      options: [
        { tr: 'Çıkarıyoruz', en: 'Take it out', de: 'Rausbringen', ar: 'نُخرجها', fr: 'On la sort', es: 'Sacarla' },
        {
          tr: 'Bastırıp sığdırıyoruz',
          en: 'Push it down more',
          de: 'Fester reindrücken',
          ar: 'نضغطها أكثر',
          fr: 'On tasse encore',
          es: 'Apretarla más',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Mühendislik harikası',
      en: 'Engineering at its finest',
      de: 'Ingenieurskunst vom Feinsten',
      ar: 'عبقرية هندسية حقيقية',
      fr: "Un chef-d'œuvre d'ingénierie",
      es: 'Ingeniería de primer nivel',
    },
  },
  {
    emoji: '🎶',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Şarkının sözlerini biliyor musun?',
        en: 'Do you actually know the lyrics?',
        de: 'Kennst du den Songtext wirklich?',
        ar: 'هل تحفظ كلمات الأغنية فعلًا؟',
        fr: 'Tu connais vraiment les paroles ?',
        es: '¿De verdad te sabes la letra?',
      },
      options: [
        { tr: 'Hepsini', en: 'Every word', de: 'Jedes Wort', ar: 'كل كلمة', fr: 'Par cœur', es: 'Toda' },
        {
          tr: 'Sadece nakaratı',
          en: 'Just the chorus',
          de: 'Nur den Refrain',
          ar: 'المقطع المتكرر فقط',
          fr: 'Juste le refrain',
          es: 'Solo el coro',
        },
        {
          tr: 'Uyduruyorum',
          en: 'I make them up',
          de: 'Ich erfinde ihn',
          ar: 'أؤلفها بنفسي',
          fr: "J'invente",
          es: 'Me la invento',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Yüksek sesle, emin ve yanlış',
      en: 'Loud, confident and wrong',
      de: 'Laut, selbstbewusst und falsch',
      ar: 'بصوت عالٍ، بثقة، وبشكل خاطئ',
      fr: 'Fort, avec aplomb, et faux',
      es: 'A todo volumen, con seguridad y mal',
    },
  },
  {
    emoji: '🛒',
    user: ACCOUNTS.trends,
    body: {
      format: 'poll',
      question: {
        tr: 'Sepete ekledin. Sonra ne oldu?',
        en: 'You added it to your cart. Then what?',
        de: 'In den Warenkorb gelegt. Und dann?',
        ar: 'أضفته إلى السلة. ثم ماذا؟',
        fr: 'Ajouté au panier. Et ensuite ?',
        es: 'Lo pusiste en el carrito. ¿Y luego?',
      },
      options: [
        { tr: 'Satın aldım', en: 'Bought it', de: 'Gekauft', ar: 'اشتريته', fr: 'Acheté', es: 'Lo compré' },
        {
          tr: 'Sepette yaşıyor',
          en: 'It lives there now',
          de: 'Wohnt jetzt dort',
          ar: 'يعيش هناك الآن',
          fr: 'Il y vit toujours',
          es: 'Ahora vive ahí',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Sepetim artık bir müze',
      en: 'My cart is basically a museum',
      de: 'Mein Warenkorb ist ein Museum',
      ar: 'سلة مشترياتي أصبحت متحفًا',
      fr: 'Mon panier est devenu un musée',
      es: 'Mi carrito ya es un museo',
    },
  },
  {
    emoji: '🤔',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Birinin adını unuttun. Ne yaparsın?',
        en: "You forgot someone's name. You:",
        de: 'Du hast jemandes Namen vergessen. Du:',
        ar: 'نسيت اسم أحدهم. ماذا تفعل؟',
        fr: "Tu as oublié le prénom de quelqu'un. Alors ?",
        es: 'Olvidaste el nombre de alguien. ¿Qué haces?',
      },
      options: [
        {
          tr: 'Tekrar sorarım',
          en: 'Ask again',
          de: 'Nochmal fragen',
          ar: 'أسأله مجددًا',
          fr: 'Je redemande',
          es: 'Preguntar otra vez',
        },
        {
          tr: 'Adsız idare ederim',
          en: 'Wing it forever',
          de: 'Ewig drumherum reden',
          ar: 'أتجنب ذكر اسمه للأبد',
          fr: "J'improvise à vie",
          es: 'Evitarlo para siempre',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: '3 yıldır idare ediyorum',
      en: 'Going on 3 years now',
      de: 'Klappt seit 3 Jahren',
      ar: 'وهكذا منذ 3 سنوات',
      fr: 'Ça fait 3 ans que ça dure',
      es: 'Ya van 3 años así',
    },
  },
  {
    emoji: '🍽️',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Bulaşıklar ne zaman yıkanacak?',
        en: 'When are the dishes getting done?',
        de: 'Wann wird endlich abgewaschen?',
        ar: 'متى ستُغسل الأطباق؟',
        fr: 'La vaisselle, on la fait quand ?',
        es: '¿Cuándo se lavan los platos?',
      },
      options: [
        {
          tr: 'Suda bekliyorlar',
          en: "They're soaking",
          de: 'Die weichen noch ein',
          ar: 'إنها منقوعة في الماء',
          fr: 'Elle trempe',
          es: 'Están en remojo',
        },
        { tr: 'Hemen', en: 'Right now', de: 'Sofort', ar: 'الآن', fr: 'Tout de suite', es: 'Ahora mismo' },
      ],
      winner: 0,
    },
    caption: {
      tr: 'Islatmak da yıkamaktan sayılır',
      en: 'Soaking counts as washing, right?',
      de: 'Einweichen zählt doch als Spülen',
      ar: 'النقع نصف الغسيل، أليس كذلك؟',
      fr: "Tremper, c'est déjà laver, non ?",
      es: 'Remojar ya es medio lavar',
    },
  },
  {
    emoji: '💃',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Karşıdan biri geliyor. Sen:',
        en: "Someone's walking straight at you. You:",
        de: 'Jemand kommt dir entgegen. Du:',
        ar: 'شخص قادم نحوك مباشرة. أنت:',
        fr: "Quelqu'un arrive en face. Tu fais quoi ?",
        es: 'Alguien viene de frente. Tú:',
      },
      options: [
        {
          tr: 'Kenara çekilirim',
          en: 'Step aside',
          de: 'Ich weiche aus',
          ar: 'أتنحّى جانبًا',
          fr: "Je m'écarte",
          es: 'Me hago a un lado',
        },
        {
          tr: 'Aynı tarafa, 3 kez',
          en: 'Same side, 3 times',
          de: 'Dreimal dieselbe Seite',
          ar: 'الجهة نفسها 3 مرات',
          fr: 'Même côté, 3 fois',
          es: 'El mismo lado, 3 veces',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kaldırım dansı, 3. tur',
      en: 'The sidewalk dance, round 3',
      de: 'Gehweg-Tanz, Runde 3',
      ar: 'رقصة الرصيف، الجولة الثالثة',
      fr: 'La danse du trottoir, round 3',
      es: 'El baile de la acera, ronda 3',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Bu evin patronu kim?',
        en: "Who's the boss in this house?",
        de: 'Wer ist bei dir zu Hause der Chef?',
        ar: 'من صاحب القرار في هذا البيت؟',
        fr: 'Qui commande dans cette maison ?',
        es: '¿Quién manda en esta casa?',
      },
      options: [
        { tr: 'Kedi', en: 'The cat', de: 'Die Katze', ar: 'القطة', fr: 'Le chat', es: 'El gato' },
        { tr: 'Ben', en: 'Me', de: 'Ich', ar: 'أنا', fr: 'Moi', es: 'Yo' },
      ],
      winner: 0,
    },
    caption: {
      tr: 'Kedi oy bile kullanmadı',
      en: "The cat didn't even vote",
      de: 'Die Katze hat nicht mal abgestimmt',
      ar: 'والقطة لم تصوّت أصلًا',
      fr: "Le chat n'a même pas voté",
      es: 'Y el gato ni siquiera votó',
    },
  },
  {
    emoji: '📜',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Kullanım koşullarını okudun mu?',
        en: 'Did you read the terms and conditions?',
        de: 'Hast du die AGB gelesen?',
        ar: 'هل قرأت الشروط والأحكام؟',
        fr: "Tu as lu les conditions d'utilisation ?",
        es: '¿Leíste los términos y condiciones?',
      },
      options: [
        { tr: 'Okudum', en: 'Yes', de: 'Ja', ar: 'نعم', fr: 'Oui', es: 'Sí' },
        { tr: 'Kabul ediyorum', en: 'I agree', de: 'Akzeptieren', ar: 'أوافق', fr: "J'accepte", es: 'Acepto' },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Kimse okumadı, herkes kabul etti',
      en: 'Nobody read them. Everyone agreed.',
      de: 'Keiner liest sie, alle stimmen zu',
      ar: 'لم يقرأها أحد، ووافق عليها الجميع',
      fr: 'Personne ne lit, tout le monde accepte',
      es: 'Nadie los leyó, todos aceptaron',
    },
  },
  {
    emoji: '🚗',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: '10 dakika erken çıktın. Ne zaman vardın?',
        en: 'You left 10 minutes early. You got there:',
        de: '10 Minuten früher los. Wann warst du da?',
        ar: 'خرجت مبكرًا 10 دقائق. متى وصلت؟',
        fr: 'Tu pars 10 min plus tôt. Tu arrives quand ?',
        es: 'Saliste 10 minutos antes. ¿Cuándo llegaste?',
      },
      options: [
        {
          tr: '10 dk erken',
          en: '10 minutes early',
          de: '10 Minuten zu früh',
          ar: 'مبكرًا 10 دقائق',
          fr: '10 min en avance',
          es: '10 minutos antes',
        },
        {
          tr: 'Yine 5 dk geç',
          en: '5 minutes late anyway',
          de: 'Doch 5 Minuten zu spät',
          ar: 'متأخرًا 5 دقائق',
          fr: 'En retard quand même',
          es: '5 minutos tarde igual',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Trafik haber almış',
      en: 'Traffic got the memo',
      de: 'Der Stau wusste Bescheid',
      ar: 'يبدو أن الزحام علم بالأمر',
      fr: 'Les bouchons étaient au courant',
      es: 'El tráfico se enteró',
    },
  },
  {
    emoji: '🔄',
    user: ACCOUNTS.hacks,
    body: {
      format: 'poll',
      question: {
        tr: 'Bir şey bozuldu. İlk hamlen?',
        en: 'Something stopped working. First move?',
        de: 'Irgendwas geht nicht. Erster Schritt?',
        ar: 'توقف شيء عن العمل. ما أول خطوة؟',
        fr: 'Un truc ne marche plus. Premier réflexe ?',
        es: 'Algo dejó de funcionar. ¿Primer paso?',
      },
      options: [
        {
          tr: 'Kapatıp açarım',
          en: 'Turn it off and on',
          de: 'Aus- und wieder an',
          ar: 'أطفئه وأعيد تشغيله',
          fr: 'Éteindre, rallumer',
          es: 'Apagar y encender',
        },
        {
          tr: 'Kılavuzu okurum',
          en: 'Read the manual',
          de: 'Anleitung lesen',
          ar: 'أقرأ الدليل',
          fr: 'Lire la notice',
          es: 'Leer el manual',
        },
      ],
      winner: 0,
    },
    caption: {
      tr: '%90 işe yarıyor',
      en: 'Works 90% of the time',
      de: 'Klappt in 90 % der Fälle',
      ar: 'ينجح في 90% من المرات',
      fr: 'Ça marche dans 90 % des cas',
      es: 'Funciona el 90 % de las veces',
    },
  },
  {
    emoji: '🚿',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: '“Yoldayım” dediğinde neredesin?',
        en: "You text “on my way.” You're actually:",
        de: 'Du schreibst „Bin unterwegs“. Wo bist du?',
        ar: 'تكتب «في الطريق». أين أنت فعلًا؟',
        fr: "Tu écris « J'arrive ». T'es où en vrai ?",
        es: 'Escribes “ya voy”. ¿Dónde estás en realidad?',
      },
      options: [
        { tr: 'Kapıda', en: 'At the door', de: 'An der Tür', ar: 'عند الباب', fr: 'Devant la porte', es: 'En la puerta' },
        { tr: 'Otobüste', en: 'On the bus', de: 'Im Bus', ar: 'في الحافلة', fr: 'Dans le bus', es: 'En el bus' },
        { tr: 'Duşta', en: 'In the shower', de: 'Unter der Dusche', ar: 'أستحمّ', fr: 'Sous la douche', es: 'En la ducha' },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Duş da yolun bir parçası',
      en: 'The shower is part of the journey',
      de: 'Die Dusche gehört zum Weg dazu',
      ar: 'الاستحمام جزء من الطريق',
      fr: 'La douche, ça fait partie du trajet',
      es: 'La ducha también es parte del camino',
    },
  },
  {
    emoji: '📝',
    user: ACCOUNTS.plain,
    body: {
      format: 'poll',
      question: {
        tr: 'Uzun bir cevap yazıyorsun. Sonra?',
        en: "You're typing a long reply. Then:",
        de: 'Du tippst eine lange Antwort. Dann?',
        ar: 'تكتب ردًا طويلًا. ثم ماذا؟',
        fr: 'Tu tapes une longue réponse. Et ensuite ?',
        es: 'Escribes una respuesta larga. ¿Y luego?',
      },
      options: [
        { tr: 'Gönderirim', en: 'I send it', de: 'Abschicken', ar: 'أرسله', fr: "J'envoie", es: 'La envío' },
        {
          tr: 'Yaz, sil, tekrarla',
          en: 'Type, delete, repeat',
          de: 'Tippen und löschen',
          ar: 'أكتب، أمسح، أكرر',
          fr: "J'écris, j'efface…",
          es: 'Escribo, borro, repito',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: '20 dakika sonra gönderilen: 👍',
      en: '20 minutes later, sent: 👍',
      de: '20 Minuten später gesendet: 👍',
      ar: 'بعد 20 دقيقة، أرسلت: 👍',
      fr: '20 minutes plus tard, envoyé : 👍',
      es: '20 minutos después, envié: 👍',
    },
  },
  {
    emoji: '👋',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Misafirler “kalkalım artık” dedi. Sonra?',
        en: 'Guests say “we should get going.” Then:',
        de: 'Besuch sagt: „Wir müssen dann mal.“ Und?',
        ar: 'قال الضيوف «علينا أن نذهب». ثم ماذا؟',
        fr: 'Les invités disent « on y va ». Et ?',
        es: 'Las visitas dicen “ya nos vamos”. ¿Y?',
      },
      options: [
        { tr: 'Gittiler', en: 'They leave', de: 'Sie gehen', ar: 'غادروا', fr: 'Ils partent', es: 'Se van' },
        {
          tr: 'Kapıda 1 saat daha',
          en: 'An hour at the door',
          de: '1 Stunde an der Tür',
          ar: 'ساعة أخرى عند الباب',
          fr: '1 h de plus à la porte',
          es: 'Otra hora en la puerta',
        },
      ],
      winner: 1,
    },
    caption: {
      tr: 'Asıl sohbet kapıda başlar',
      en: 'The real talk starts at the door',
      de: 'Die besten Gespräche gibt es an der Tür',
      ar: 'الحديث الحقيقي يبدأ عند الباب',
      fr: 'La vraie discussion commence à la porte',
      es: 'La charla de verdad empieza en la puerta',
    },
  },
  {
    emoji: '🧳',
    user: ACCOUNTS.vlog,
    body: {
      format: 'poll',
      question: {
        tr: 'Tatil için kaç kıyafet aldın?',
        en: 'Packing for a trip. How many outfits?',
        de: 'Urlaub! Wie viele Outfits packst du?',
        ar: 'كم طقمًا تأخذ معك في السفر؟',
        fr: 'Tu pars en vacances. Combien de tenues ?',
        es: 'Te vas de viaje. ¿Cuánta ropa llevas?',
      },
      options: [
        { tr: 'Yetecek kadar', en: 'Just enough', de: 'Genau genug', ar: 'ما يكفي فقط', fr: 'Juste assez', es: 'Lo justo' },
        { tr: 'Biraz fazla', en: 'A few extra', de: 'Ein paar mehr', ar: 'أكثر بقليل', fr: 'Un peu trop', es: 'Un poco de más' },
        {
          tr: 'Üç katı',
          en: '3 times too many',
          de: 'Dreimal zu viele',
          ar: '3 أضعاف حاجتي',
          fr: '3 fois trop',
          es: 'El triple',
        },
      ],
      winner: 2,
    },
    caption: {
      tr: 'Yarısını giymedim bile',
      en: "Didn't even wear half",
      de: 'Die Hälfte nie getragen',
      ar: 'لم ألبس نصفها أصلًا',
      fr: 'La moitié jamais portée',
      es: 'La mitad ni la usé',
    },
  },
  {
    emoji: '💤',
    user: ACCOUNTS.home,
    body: {
      format: 'poll',
      question: {
        tr: 'Kısa bir şekerleme. Ne kadar sürdü?',
        en: 'Just a quick nap. How long was it?',
        de: 'Nur ein kurzes Nickerchen. Wie lang?',
        ar: 'قيلولة قصيرة فقط. كم استمرت؟',
        fr: 'Juste une petite sieste. Ça a duré combien ?',
        es: 'Solo una siesta cortita. ¿Cuánto duró?',
      },
      options: [
        { tr: '3 saat', en: '3 hours', de: '3 Stunden', ar: '3 ساعات', fr: '3 heures', es: '3 horas' },
        { tr: '20 dakika', en: '20 minutes', de: '20 Minuten', ar: '20 دقيقة', fr: '20 minutes', es: '20 minutos' },
      ],
      winner: 0,
    },
    caption: {
      tr: 'Uyandım. Hangi yıldayız?',
      en: 'Woke up. What year is it?',
      de: 'Aufgewacht. Welches Jahr haben wir?',
      ar: 'استيقظت… في أي عام نحن؟',
      fr: 'Réveil : on est en quelle année ?',
      es: 'Desperté. ¿En qué año estamos?',
    },
  },
  {
    emoji: '🔍',
    user: ACCOUNTS.polls,
    body: {
      format: 'poll',
      question: {
        tr: 'Kumanda nerede?',
        en: "Where's the remote?",
        de: 'Wo ist die Fernbedienung?',
        ar: 'أين جهاز التحكم؟',
        fr: 'Elle est où, la télécommande ?',
        es: '¿Dónde está el control remoto?',
      },
      options: [
        {
          tr: 'Koltuğun içinde',
          en: 'Deep in the couch',
          de: 'Tief im Sofa',
          ar: 'في أعماق الأريكة',
          fr: 'Au fond du canapé',
          es: 'Dentro del sofá',
        },
        { tr: 'Masada', en: 'On the table', de: 'Auf dem Tisch', ar: 'على الطاولة', fr: 'Sur la table', es: 'En la mesa' },
      ],
      winner: 0,
    },
    caption: {
      tr: 'Koltuk her şeyi yutar',
      en: 'The couch eats everything',
      de: 'Das Sofa verschluckt alles',
      ar: 'الأريكة تبتلع كل شيء',
      fr: 'Le canapé avale tout',
      es: 'El sofá se lo traga todo',
    },
  },
];
