import { ACCOUNTS } from '../accounts';
import type { Draft } from '../types';

/** Ordinary posts that are line charts (`chart`). Append only: a published post keeps its place. */
export const SKIP_CHART: readonly Draft[] = [
  {
    emoji: '📱',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'EKRAN SÜREM',
        en: 'MY SCREEN TIME',
        de: 'MEINE BILDSCHIRMZEIT',
        ar: 'وقتي أمام الشاشة',
        fr: "MON TEMPS D'ÉCRAN",
        es: 'MI TIEMPO DE PANTALLA',
        ja: 'スクリーンタイム',
        ko: '내 스크린 타임',
      },
      value: {
        tr: '+%38',
        en: '+38%',
        de: '+38 %',
        ar: '+38%',
        fr: '+38 %',
        es: '+38 %',
        ja: '+38%',
        ko: '+38%',
      },
      shape: 'rise',
      axis: 'days',
    },
    caption: {
      tr: 'Haftalık rapor geldi, onu da kaydırdım',
      en: 'Got my weekly report. Swiped it away.',
      de: 'Wochenbericht kam. Weggewischt.',
      ar: 'وصل التقرير الأسبوعي، فتجاوزته هو أيضًا',
      fr: 'Bilan de la semaine reçu. Zappé.',
      es: 'Llegó el informe semanal: lo deslicé',
      ja: '週間レポートが来た。それもスワイプした。',
      ko: '주간 리포트 왔길래 그것도 넘겼음',
    },
  },
  {
    emoji: '🦉',
    user: ACCOUNTS.plain,
    body: {
      format: 'chart',
      title: {
        tr: '“SON BİR VİDEO”',
        en: '“ONE LAST VIDEO”',
        de: '„NUR NOCH EIN VIDEO“',
        ar: '«فيديو أخير فقط»',
        fr: '« UNE DERNIÈRE VIDÉO »',
        es: '“UN ÚLTIMO VIDEO”',
        ja: '「あと1本だけ」',
        ko: '“딱 하나만 더”',
      },
      value: {
        tr: '×37',
        en: '×37',
        de: '×37',
        ar: '×37',
        fr: '×37',
        es: '×37',
        ja: '×37',
        ko: '×37',
      },
      shape: 'rise',
      axis: 'hours',
    },
    caption: {
      tr: 'Bu sonuncuydu. Bu da.',
      en: 'That was the last one. So was this.',
      de: 'Das war das letzte. Das auch.',
      ar: 'كان هذا الأخير. وهذا أيضًا.',
      fr: "C'était la dernière. Celle-là aussi.",
      es: 'Ese era el último. Este también.',
      ja: 'これで最後。これも最後。',
      ko: '이게 마지막이었음. 이것도.',
    },
  },
  {
    emoji: '🥘',
    user: ACCOUNTS.food,
    body: {
      format: 'chart',
      title: {
        tr: 'KAYDETTİĞİM TARİFLER',
        en: 'SAVED RECIPES',
        de: 'GESPEICHERTE REZEPTE',
        ar: 'الوصفات التي حفظتها',
        fr: 'RECETTES ENREGISTRÉES',
        es: 'RECETAS GUARDADAS',
        ja: '保存したレシピ',
        ko: '저장한 레시피',
      },
      value: {
        tr: '312',
        en: '312',
        de: '312',
        ar: '312',
        fr: '312',
        es: '312',
        ja: '312',
        ko: '312',
      },
      shape: 'rise',
      axis: 'months',
    },
    caption: {
      tr: 'Pişirdiğim tarif sayısı: 0',
      en: "Recipes I've actually made: 0",
      de: 'Davon nachgekocht: 0',
      ar: 'ما طبخته منها: 0',
      fr: 'Recettes testées : 0',
      es: 'Recetas que cociné: 0',
      ja: '実際に作ったレシピ：0',
      ko: '실제로 만든 레시피: 0',
    },
  },
  {
    emoji: '🌵',
    user: ACCOUNTS.home,
    body: {
      format: 'chart',
      title: {
        tr: 'KAKTÜSÜMÜN MORALİ',
        en: "MY CACTUS'S MOOD",
        de: 'LAUNE MEINES KAKTUS',
        ar: 'معنويات الصبّار',
        fr: 'LE MORAL DE MON CACTUS',
        es: 'EL ÁNIMO DE MI CACTUS',
        ja: 'サボテンの元気',
        ko: '선인장의 기분',
      },
      value: null,
      shape: 'fall',
      axis: 'months',
    },
    caption: {
      tr: 'Kaktüs bile benden vazgeçti',
      en: 'Even my cactus gave up on me',
      de: 'Sogar mein Kaktus hat aufgegeben',
      ar: 'حتى الصبّار يئس مني',
      fr: 'Même mon cactus me lâche',
      es: 'Hasta mi cactus se rindió conmigo',
      ja: 'サボテンにまで見放された',
      ko: '선인장마저 날 포기함',
    },
  },
  {
    emoji: '🍪',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'ATIŞTIRMALIK STOĞUM',
        en: 'MY SNACK STASH',
        de: 'MEIN SNACKVORRAT',
        ar: 'مخزون الوجبات الخفيفة',
        fr: 'MA RÉSERVE DE BISCUITS',
        es: 'MI RESERVA DE GALLETAS',
        ja: 'お菓子のストック',
        ko: '내 간식 재고',
      },
      value: null,
      shape: 'crash',
      axis: 'days',
    },
    caption: {
      tr: '“Bütün hafta yeter” demiştim',
      en: "“This'll last all week,” I said",
      de: '„Reicht für die ganze Woche“, dachte ich',
      ar: 'قلتُ: «تكفي الأسبوع كله»',
      fr: 'Censée tenir toute la semaine',
      es: '“Me duran toda la semana”, dije',
      ja: '「1週間はもつ」と言っていた',
      ko: '“일주일은 가겠지”라고 했었지',
    },
  },
  {
    emoji: '📸',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'BOŞ DEPOLAMA ALANI',
        en: 'FREE STORAGE',
        de: 'FREIER SPEICHER',
        ar: 'مساحة التخزين المتبقية',
        fr: 'STOCKAGE DISPONIBLE',
        es: 'ESPACIO LIBRE',
        ja: '空き容量',
        ko: '남은 저장 공간',
      },
      value: {
        tr: '%2',
        en: '2%',
        de: '2 %',
        ar: '2%',
        fr: '2 %',
        es: '2 %',
        ja: '2%',
        ko: '2%',
      },
      shape: 'fall',
      axis: 'months',
    },
    caption: {
      tr: '847 ekran görüntüsü, hepsi “lazım olur”',
      en: '847 screenshots, all “might need it”',
      de: '847 Screenshots, alle „brauch ich noch“',
      ar: '847 لقطة شاشة… كلها «قد أحتاجها»',
      fr: '847 captures, toutes « au cas où »',
      es: '847 capturas, todas “por si acaso”',
      ja: 'スクショ847枚、全部「いつか使う」',
      ko: '스크린샷 847장, 전부 “나중에 필요함”',
    },
  },
  {
    emoji: '🎯',
    user: ACCOUNTS.motivation,
    body: {
      format: 'chart',
      title: {
        tr: 'KONSANTRASYONUM',
        en: 'MY FOCUS',
        de: 'MEINE KONZENTRATION',
        ar: 'تركيزي',
        fr: 'MA CONCENTRATION',
        es: 'MI CONCENTRACIÓN',
        ja: '集中力',
        ko: '내 집중력',
      },
      value: null,
      shape: 'crash',
      axis: 'hours',
    },
    caption: {
      tr: 'Sonra bir bildirim geldi',
      en: 'Then one notification came in',
      de: 'Dann kam eine Benachrichtigung',
      ar: 'ثم وصل إشعار واحد',
      fr: 'Puis une notif est arrivée',
      es: 'Luego llegó una notificación',
      ja: 'そこへ通知が1件',
      ko: '그때 알림이 하나 왔다',
    },
  },
  {
    emoji: '🗓️',
    user: ACCOUNTS.motivation,
    body: {
      format: 'chart',
      title: {
        tr: 'YENİ YIL KARARLARIM',
        en: "NEW YEAR'S RESOLUTIONS",
        de: 'MEINE NEUJAHRSVORSÄTZE',
        ar: 'قرارات العام الجديد',
        fr: 'MES BONNES RÉSOLUTIONS',
        es: 'PROPÓSITOS DE AÑO NUEVO',
        ja: '新年の抱負',
        ko: '새해 목표',
      },
      value: null,
      shape: 'crash',
      axis: 'months',
    },
    caption: {
      tr: 'Ocak’ta çok iddialıydım',
      en: 'January me had big plans',
      de: 'Im Januar hatte ich große Pläne',
      ar: 'كانت لديّ خطط كبيرة في يناير',
      fr: "En janvier, j'avais de grands projets",
      es: 'En enero tenía grandes planes',
      ja: '1月の私はやる気満々だった',
      ko: '1월의 나는 야심만만했다',
    },
  },
  {
    emoji: '🚿',
    user: ACCOUNTS.plain,
    body: {
      format: 'chart',
      title: {
        tr: 'EFSANE CEVAPLARIM',
        en: 'MY PERFECT COMEBACKS',
        de: 'MEINE SCHLAGFERTIGKEIT',
        ar: 'ردودي المُفحِمة',
        fr: 'MES RÉPARTIES',
        es: 'MIS RESPUESTAS ÉPICAS',
        ja: '完璧な言い返し',
        ko: '완벽한 반박',
      },
      value: null,
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Hepsi tartışmadan 3 saat sonra, duşta',
      en: 'All of them 3 hours late, in the shower',
      de: 'Alle 3 Stunden zu spät, unter der Dusche',
      ar: 'كلها تخطر لي بعد النقاش بثلاث ساعات، تحت الدش',
      fr: 'Toutes avec 3 h de retard, sous la douche',
      es: 'Todas llegan 3 horas tarde, en la ducha',
      ja: '全部、ケンカの3時間後にシャワー中',
      ko: '전부 말싸움 3시간 뒤 샤워하다 떠오름',
    },
  },
  {
    emoji: '🐈',
    user: ACCOUNTS.vlog,
    body: {
      format: 'chart',
      title: {
        tr: 'KEDİMİN SEVGİSİ',
        en: "MY CAT'S LOVE FOR ME",
        de: 'LIEBE MEINER KATZE',
        ar: 'حبّ قطتي لي',
        fr: "L'AMOUR DE MON CHAT",
        es: 'EL CARIÑO DE MI GATO',
        ja: '猫からの愛',
        ko: '고양이의 사랑',
      },
      value: null,
      shape: 'spike',
      axis: 'hours',
    },
    caption: {
      tr: 'Sadece mama saatinde seviliyorum',
      en: "I'm only loved at feeding time",
      de: 'Geliebt werde ich nur zur Fütterungszeit',
      ar: 'لا تحبني إلا وقت الطعام',
      fr: "On ne m'aime qu'à l'heure des croquettes",
      es: 'Solo me quiere a la hora de comer',
      ja: '愛されるのはごはんの時間だけ',
      ko: '밥 시간에만 사랑받음',
    },
  },
  {
    emoji: '🔨',
    user: ACCOUNTS.home,
    body: {
      format: 'chart',
      title: {
        tr: 'KOMŞUNUN MATKABI',
        en: "THE NEIGHBOR'S DRILL",
        de: 'NACHBARS BOHRMASCHINE',
        ar: 'مثقاب الجيران',
        fr: 'LA PERCEUSE DU VOISIN',
        es: 'EL TALADRO DEL VECINO',
        ja: '隣のドリル',
        ko: '옆집 드릴',
      },
      value: {
        tr: '95 dB',
        en: '95 dB',
        de: '95 dB',
        ar: '95 ديسيبل',
        fr: '95 dB',
        es: '95 dB',
        ja: '95 dB',
        ko: '95 dB',
      },
      shape: 'spike',
      axis: 'days',
    },
    caption: {
      tr: 'Her pazar, sabah 8’de. Şaşmaz.',
      en: 'Every Sunday, 8 a.m. sharp',
      de: 'Jeden Sonntag, pünktlich um 8',
      ar: 'كل يوم عطلة، الثامنة صباحًا بالضبط',
      fr: 'Chaque dimanche, 8 h pile',
      es: 'Cada domingo, a las 8 en punto',
      ja: '毎週日曜の朝8時。きっかり。',
      ko: '매주 일요일 아침 8시. 정확히.',
    },
  },
  {
    emoji: '🎈',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'BANA YAZANLAR',
        en: 'PEOPLE TEXTING ME',
        de: 'NACHRICHTEN AN MICH',
        ar: 'من يراسلني',
        fr: "LES GENS QUI M'ÉCRIVENT",
        es: 'QUIENES ME ESCRIBEN',
        ja: '連絡してくる人',
        ko: '연락 오는 사람',
      },
      value: {
        tr: '+%900',
        en: '+900%',
        de: '+900 %',
        ar: '+900%',
        fr: '+900 %',
        es: '+900 %',
        ja: '+900%',
        ko: '+900%',
      },
      shape: 'spike',
      axis: 'months',
    },
    caption: {
      tr: 'Yılda bir gün ünlüyüm: doğum günüm',
      en: 'Famous one day a year: my birthday',
      de: 'Einmal im Jahr berühmt: am Geburtstag',
      ar: 'مشهور يومًا واحدًا في السنة: يوم ميلادي',
      fr: 'Célèbre un jour par an : mon anniversaire',
      es: 'Famoso un día al año: mi cumpleaños',
      ja: '年に1日だけ人気者：誕生日',
      ko: '1년에 하루만 인기인: 내 생일',
    },
  },
  {
    emoji: '🔂',
    user: ACCOUNTS.trends,
    body: {
      format: 'chart',
      title: {
        tr: 'AYNI ŞARKIYI DİNLEME',
        en: 'SAME SONG ON REPEAT',
        de: 'SONG IN DAUERSCHLEIFE',
        ar: 'الأغنية نفسها مرارًا',
        fr: 'MÊME CHANSON EN BOUCLE',
        es: 'UNA CANCIÓN EN BUCLE',
        ja: '同じ曲をリピート',
        ko: '같은 노래 반복',
      },
      value: {
        tr: '×84',
        en: '×84',
        de: '×84',
        ar: '×84',
        fr: '×84',
        es: '×84',
        ja: '×84',
        ko: '×84',
      },
      shape: 'flat',
      axis: 'days',
    },
    caption: {
      tr: 'Tutarlılık diye buna derim',
      en: "Now that's consistency",
      de: 'Das nenn ich Beständigkeit',
      ar: 'هذا ما أسمّيه الثبات',
      fr: "Ça, c'est de la constance",
      es: 'Eso sí es constancia',
      ja: 'これぞ一途',
      ko: '이게 바로 한결같음',
    },
  },
  {
    emoji: '🔄',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'GÜNCELLEME İLERLEMESİ',
        en: 'UPDATE PROGRESS',
        de: 'UPDATE-FORTSCHRITT',
        ar: 'تقدّم التحديث',
        fr: 'MISE À JOUR',
        es: 'ACTUALIZACIÓN',
        ja: 'アップデート進行度',
        ko: '업데이트 진행률',
      },
      value: {
        tr: '%99',
        en: '99%',
        de: '99 %',
        ar: '99%',
        fr: '99 %',
        es: '99 %',
        ja: '99%',
        ko: '99%',
      },
      shape: 'flat',
      axis: 'hours',
    },
    caption: {
      tr: 'Üç saattir “neredeyse bitti”',
      en: '“Almost done” for three hours now',
      de: 'Seit drei Stunden „fast fertig“',
      ar: '«على وشك الانتهاء» منذ ثلاث ساعات',
      fr: '« Presque fini » depuis trois heures',
      es: '“Casi listo” desde hace tres horas',
      ja: '3時間ずっと「もうすぐ完了」',
      ko: '3시간째 “거의 다 됐어요”',
    },
  },
  {
    emoji: '💐',
    user: ACCOUNTS.charts,
    body: {
      format: 'chart',
      title: {
        tr: 'AİLE GRUBU MESAJLARI',
        en: 'FAMILY GROUP CHAT',
        de: 'FAMILIENCHAT',
        ar: 'رسائل مجموعة العائلة',
        fr: 'LE GROUPE FAMILLE',
        es: 'EL GRUPO DE LA FAMILIA',
        ja: '家族グループ',
        ko: '가족 단톡방',
      },
      value: null,
      shape: 'zigzag',
      axis: 'hours',
    },
    caption: {
      tr: 'Sabah 7’de 14 çiçekli “günaydın”',
      en: '7 a.m.: 14 flowery “good mornings”',
      de: '7 Uhr: 14-mal „Guten Morgen“ mit Blumen',
      ar: 'السابعة صباحًا: 14 «صباح الخير» بالورود',
      fr: '7 h : 14 « bonjour » fleuris',
      es: 'A las 7: 14 “buenos días” con flores',
      ja: '朝7時、花付き「おはよう」14件',
      ko: '아침 7시, 꽃 사진 “좋은 아침” 14개',
    },
  },
  {
    emoji: '✂️',
    user: ACCOUNTS.trends,
    body: {
      format: 'chart',
      title: {
        tr: 'SAÇ UZUNLUĞUM',
        en: 'MY HAIR LENGTH',
        de: 'MEINE HAARLÄNGE',
        ar: 'طول شعري',
        fr: 'LONGUEUR DE MES CHEVEUX',
        es: 'EL LARGO DE MI PELO',
        ja: '髪の長さ',
        ko: '내 머리 길이',
      },
      value: null,
      shape: 'zigzag',
      axis: 'months',
    },
    caption: {
      tr: 'Uzat, kestir, pişman ol, tekrarla',
      en: 'Grow it, cut it, regret it, repeat',
      de: 'Wachsen lassen, abschneiden, bereuen, von vorn',
      ar: 'أطيله، أقصّه، أندم… ثم أعيد',
      fr: 'Laisser pousser, couper, regretter, recommencer',
      es: 'Dejar crecer, cortar, arrepentirse, repetir',
      ja: '伸ばす、切る、後悔する、繰り返す',
      ko: '기르고, 자르고, 후회하고, 반복',
    },
  },
];
