import type { Localized } from './types';

/**
 * Who posts. An account keeps its handle in every post it makes, so each
 * language's feed has its regulars; the Turkish handles are the originals.
 */
export const ACCOUNTS = {
  vlog: {
    tr: '@gunluk.vlog',
    en: '@daily.vlog',
    de: '@alltags.vlog',
    ar: '@yawmiyat.vlog',
    fr: '@vlog.quotidien',
    es: '@vlog.diario',
  },
  food: {
    tr: '@yemek.defteri',
    en: '@food.diary',
    de: '@essens.tagebuch',
    ar: '@daftar.tabkh',
    fr: '@carnet.bouffe',
    es: '@diario.comida',
  },
  home: {
    tr: '@evden.notlar',
    en: '@notes.from.home',
    de: '@zuhause.notizen',
    ar: '@min.albait',
    fr: '@notes.de.chez.moi',
    es: '@notas.desde.casa',
  },
  plain: {
    tr: '@siradan.hesap',
    en: '@just.an.account',
    de: '@nur.ein.konto',
    ar: '@hisab.aadi',
    fr: '@compte.banal',
    es: '@cuenta.normal',
  },
  hacks: {
    tr: '@hayat.hilesi',
    en: '@life.hacks',
    de: '@lifehack.profi',
    ar: '@hiyal.hayat',
    fr: '@astuce.du.jour',
    es: '@trucos.de.vida',
  },
  trends: {
    tr: '@trend.avcisi',
    en: '@trend.hunter',
    de: '@trend.jaeger',
    ar: '@qannas.trend',
    fr: '@chasseur.de.trends',
    es: '@caza.tendencias',
  },
  facts: {
    tr: '@bilgi.kutusu',
    en: '@did.you.know',
    de: '@wusstest.du.schon',
    ar: '@hal.ta3lam',
    fr: '@le.saviez.vous',
    es: '@sabias.que',
  },
  motivation: {
    tr: '@motivasyon.34',
    en: '@motivation.247',
    de: '@motivation.030',
    ar: '@tahfeez.yawmi',
    fr: '@motivation.75',
    es: '@motivacion.365',
  },
  asmr: {
    tr: '@sessiz.asmr',
    en: '@quiet.asmr',
    de: '@leise.asmr',
    ar: '@asmr.hudoo',
    fr: '@asmr.chuchote',
    es: '@asmr.silencioso',
  },
  zeynep: {
    tr: '@zeynep.k',
    en: '@emma.k',
    de: '@lena.k',
    ar: '@noor.k',
    fr: '@chloe.k',
    es: '@lucia.k',
  },
  ali: {
    tr: '@kanka.ali',
    en: '@bro.jake',
    de: '@digga.max',
    ar: '@sahbi.ali',
    fr: '@frerot.theo',
    es: '@bro.pablo',
  },
  elif: {
    tr: '@elif.ay',
    en: '@olivia.moon',
    de: '@mia.mond',
    ar: '@layla.qamar',
    fr: '@lea.lune',
    es: '@sofia.luna',
  },
  ece: {
    tr: '@ece.su',
    en: '@ava.rose',
    de: '@sophie.lu',
    ar: '@salma.r',
    fr: '@jade.ln',
    es: '@carla.mar',
  },
  burak: {
    tr: '@burak.07',
    en: '@tyler.02',
    de: '@jonas.089',
    ar: '@yousef.07',
    fr: '@lucas.13',
    es: '@diego.07',
  },
  deniz: {
    tr: '@deniz*m',
    en: '@kayla*j',
    de: '@nele*k',
    ar: '@rana*m',
    fr: '@manon*b',
    es: '@paula*g',
  },
  can: {
    tr: '@can.can',
    en: '@alex.alex',
    de: '@finn.finn',
    ar: '@karim.karim',
    fr: '@hugo.hugo',
    es: '@dani.dani',
  },
  mert: {
    tr: '@mert*34',
    en: '@ryan*nyc',
    de: '@leon*030',
    ar: '@hamza*99',
    fr: '@enzo*75',
    es: '@javi*10',
  },
  rare: {
    tr: '@nadir.icerik',
    en: '@rare.content',
    de: '@seltener.content',
    ar: '@muhtawa.nadir',
    fr: '@contenu.rare',
    es: '@contenido.unico',
  },
  gold: {
    tr: '@altin.reel',
    en: '@gold.post',
    de: '@goldener.post',
    ar: '@manshour.dhahabi',
    fr: '@post.dore',
    es: '@post.dorado',
  },
  treasure: {
    tr: '@hazine*avcisi',
    en: '@treasure*hunter',
    de: '@schatz*jaeger',
    ar: '@sayyad*kunuz',
    fr: '@chasse*au*tresor',
    es: '@caza*tesoros',
  },
  live: {
    tr: '@canli.yayin',
    en: '@live.now',
    de: '@jetzt.live',
    ar: '@bath.mubasher',
    fr: '@en.direct',
    es: '@en.vivo',
  },
  // Friends — their posts are pink: double-tap.
  emre: {
    tr: '@emre.kaya',
    en: '@ethan.cole',
    de: '@noah.berg',
    ar: '@omar.saeed',
    fr: '@louis.b',
    es: '@mateo.ruiz',
  },
  selin: {
    tr: '@selin.yildiz',
    en: '@grace.star',
    de: '@hanna.stern',
    ar: '@mariam.najm',
    fr: '@ines.etoile',
    es: '@valeria.sol',
  },
  kaan: {
    tr: '@kaan.94',
    en: '@mason.94',
    de: '@paul.94',
    ar: '@tariq.94',
    fr: '@nathan.94',
    es: '@marcos.94',
  },
  ayse: {
    tr: '@ayse.bal',
    en: '@lily.honey',
    de: '@emilia.honig',
    ar: '@huda.asal',
    fr: '@camille.miel',
    es: '@carmen.miel',
  },
  bora: {
    tr: '@bora.gezgin',
    en: '@owen.travels',
    de: '@elias.reist',
    ar: '@ziad.rahhal',
    fr: '@arthur.voyage',
    es: '@alvaro.viajes',
  },
  ipek: {
    tr: '@ipek.cizer',
    en: '@zoe.draws',
    de: '@clara.malt',
    ar: '@dana.tarsum',
    fr: '@lou.dessine',
    es: '@martina.dibuja',
  },
  // Pages — each format has a few regulars.
  polls: {
    tr: '@anket.saati',
    en: '@poll.time',
    de: '@umfrage.zeit',
    ar: '@istitlaa.alyawm',
    fr: '@sondage.du.jour',
    es: '@encuesta.diaria',
  },
  screens: {
    tr: '@ss.arsivi',
    en: '@screenshot.vault',
    de: '@screenshot.archiv',
    ar: '@luqtat.shasha',
    fr: '@captures.cultes',
    es: '@capturas.top',
  },
  charts: {
    tr: '@grafik.gunlugu',
    en: '@chart.diary',
    de: '@diagramm.tagebuch',
    ar: '@rasm.bayani',
    fr: '@graphique.du.jour',
    es: '@grafico.diario',
  },
  receipts: {
    tr: '@fis.koleksiyonu',
    en: '@receipt.collector',
    de: '@kassenbon.sammler',
    ar: '@fawateer.albaqala',
    fr: '@tickets.de.caisse',
    es: '@tickets.del.super',
  },
  tiers: {
    tr: '@tier.listesi',
    en: '@tier.lists',
    de: '@tier.listen',
    ar: '@tier.qawaem',
    fr: '@tier.listes',
    es: '@tier.listas',
  },
  quotes: {
    tr: '@guzel.sozler',
    en: '@deep.quotes',
    de: '@weise.worte',
    ar: '@aqwal.hakeema',
    fr: '@citations.du.jour',
    es: '@frases.celebres',
  },
  notifs: {
    tr: '@bildirim.yagmuru',
    en: '@notification.storm',
    de: '@push.gewitter',
    ar: '@isharat.kathira',
    fr: '@notifs.en.pagaille',
    es: '@lluvia.de.avisos',
  },
  jackpot: {
    tr: '@buyuk.ikramiye',
    en: '@jackpot.hour',
    de: '@jackpot.stunde',
    ar: '@aljaeza.alkubra',
    fr: '@gros.lot',
    es: '@premio.gordo',
  },
  cctv: {
    tr: '@kamera.kayitta',
    en: '@caught.on.cam',
    de: '@kamera.laeuft',
    ar: '@kamera.tusajjil',
    fr: '@camera.cachee',
    es: '@camara.oculta',
  },
  signs: {
    tr: '@uyari.levhasi',
    en: '@warning.signs',
    de: '@warnschilder',
    ar: '@lafitat.tahdheer',
    fr: '@panneaux.danger',
    es: '@senales.peligro',
  },
  // The feed at a thousand posts: more friends and a page for every corner of the day.
  cemre: {
    tr: '@cemre.nur',
    en: '@hannah.b',
    de: '@marie.b',
    ar: '@reem.n',
    fr: '@alice.n',
    es: '@elena.n',
  },
  berk: {
    tr: '@berk.t',
    en: '@nathan.t',
    de: '@felix.t',
    ar: '@khaled.t',
    fr: '@jules.t',
    es: '@adrian.t',
  },
  naz: {
    tr: '@naz.ay',
    en: '@ruby.ay',
    de: '@frieda.m',
    ar: '@lina.m',
    fr: '@louise.m',
    es: '@noa.m',
  },
  onur: {
    tr: '@onur.k',
    en: '@jack.k',
    de: '@moritz.k',
    ar: '@samir.k',
    fr: '@leo.k',
    es: '@sergio.k',
  },
  melis: {
    tr: '@melis.d',
    en: '@madison.d',
    de: '@johanna.d',
    ar: '@yasmin.d',
    fr: '@clara.d',
    es: '@daniela.d',
  },
  arda: {
    tr: '@arda.y',
    en: '@caleb.y',
    de: '@luis.y',
    ar: '@hadi.y',
    fr: '@ethan.y',
    es: '@ivan.y',
  },
  defne: {
    tr: '@defne.s',
    en: '@stella.s',
    de: '@ella.s',
    ar: '@farah.s',
    fr: '@zoe.s',
    es: '@alba.s',
  },
  baris: {
    tr: '@baris.o',
    en: '@dylan.o',
    de: '@ben.o',
    ar: '@rami.o',
    fr: '@gabriel.o',
    es: '@hector.o',
  },
  irem: {
    tr: '@irem.k',
    en: '@nora.k',
    de: '@paula.k',
    ar: '@dima.k',
    fr: '@eva.k',
    es: '@irene.k',
  },
  tolga: {
    tr: '@tolga.b',
    en: '@logan.b',
    de: '@anton.b',
    ar: '@bassem.b',
    fr: '@tom.b',
    es: '@raul.b',
  },
  yagmur: {
    tr: '@yagmur.e',
    en: '@summer.e',
    de: '@luisa.e',
    ar: '@mayar.e',
    fr: '@margot.e',
    es: '@lluvia.e',
  },
  efe: {
    tr: '@efe.c',
    en: '@ryder.c',
    de: '@tim.c',
    ar: '@adam.c',
    fr: '@noah.c',
    es: '@marco.c',
  },
  kitchen: {
    tr: '@mutfak.kazasi',
    en: '@kitchen.fails',
    de: '@kuechen.chaos',
    ar: '@kawareth.almatbakh',
    fr: '@cuisine.ratee',
    es: '@cocina.desastre',
  },
  school: {
    tr: '@okul.gunlugu',
    en: '@school.diary',
    de: '@schul.tagebuch',
    ar: '@yawmiyat.almadrasa',
    fr: '@journal.de.classe',
    es: '@diario.escolar',
  },
  office: {
    tr: '@ofis.hayati',
    en: '@office.life',
    de: '@buero.alltag',
    ar: '@hayat.almaktab',
    fr: '@vie.de.bureau',
    es: '@vida.de.oficina',
  },
  city: {
    tr: '@sehir.halleri',
    en: '@city.moments',
    de: '@stadt.momente',
    ar: '@lahazat.almadina',
    fr: '@scenes.de.ville',
    es: '@momentos.urbanos',
  },
  weather: {
    tr: '@hava.nasil',
    en: '@weather.mood',
    de: '@wetter.laune',
    ar: '@mazaj.altaqs',
    fr: '@meteo.du.jour',
    es: '@clima.del.dia',
  },
  sport: {
    tr: '@spor.bahane',
    en: '@gym.excuses',
    de: '@sport.ausreden',
    ar: '@aadhar.riyadiya',
    fr: '@excuses.sport',
    es: '@excusas.gym',
  },
  games: {
    tr: '@oyun.gecesi',
    en: '@game.night',
    de: '@spieleabend',
    ar: '@laylat.alaab',
    fr: '@soiree.jeux',
    es: '@noche.de.juegos',
  },
  sleep: {
    tr: '@uyku.modu',
    en: '@sleep.mode',
    de: '@schlafmodus',
    ar: '@wadh.alnawm',
    fr: '@mode.dodo',
    es: '@modo.sueno',
  },
  shopping: {
    tr: '@sepet.dolu',
    en: '@cart.is.full',
    de: '@warenkorb.voll',
    ar: '@alsalla.mumtalia',
    fr: '@panier.plein',
    es: '@carrito.lleno',
  },
  pets: {
    tr: '@pati.dunyasi',
    en: '@paw.world',
    de: '@pfoten.welt',
    ar: '@alam.alhayawanat',
    fr: '@monde.des.pattes',
    es: '@mundo.patitas',
  },
  family: {
    tr: '@aile.halleri',
    en: '@family.chat',
    de: '@familien.chat',
    ar: '@jalsat.aailiya',
    fr: '@chat.de.famille',
    es: '@chat.familiar',
  },
  mornings: {
    tr: '@sabah.rutini',
    en: '@morning.routine',
    de: '@morgen.routine',
    ar: '@rotin.alsabah',
    fr: '@routine.du.matin',
    es: '@rutina.matutina',
  },
  alert: {
    tr: '@alarm.durumu',
    en: '@alert.mode',
    de: '@alarmstufe',
    ar: '@halat.inthar',
    fr: '@mode.alerte',
    es: '@modo.alerta',
  },
  lucky: {
    tr: '@sansli.gun',
    en: '@lucky.day',
    de: '@glueckstag',
    ar: '@yawm.alhazz',
    fr: '@jour.de.chance',
    es: '@dia.de.suerte',
  },
} satisfies Record<string, Localized>;
