import type { Localized, Notice } from './types';

/**
 * The parts a format borrows so that one post rarely looks the same twice:
 * the ordinary lines of a receipt, the notifications piled under a lock
 * screen's punchline, a chat contact's face, a corner sticker. The app picks
 * them from the seed and the reel's place (`apps/mobile/src/game/dress.ts`),
 * so a run always wears the same ones. They never reach the API, so a pool
 * may grow, shrink or be reworded at any time — but every entry is written in
 * all six languages, and what a player reads is as clean as a caption.
 */

/**
 * What else ends up in the basket: a receipt's ordinary lines, in capitals
 * as a till prints them (Turkish İ, German SS, accents kept; Arabic has no
 * capitals). Short — a line holds about 18 letters.
 */
export const RECEIPT_ITEMS: readonly Localized[] = [
  { tr: 'ÇİKOLATA', en: 'CHOCOLATE', de: 'SCHOKOLADE', ar: 'شوكولاتة', fr: 'CHOCOLAT', es: 'CHOCOLATE' },
  { tr: 'CİPS', en: 'CHIPS', de: 'CHIPS', ar: 'رقائق بطاطس', fr: 'CHIPS', es: 'PATATAS FRITAS' },
  { tr: 'EKMEK', en: 'BREAD', de: 'BROT', ar: 'خبز', fr: 'PAIN', es: 'PAN' },
  { tr: 'SÜT', en: 'MILK', de: 'MILCH', ar: 'حليب', fr: 'LAIT', es: 'LECHE' },
  { tr: 'YUMURTA', en: 'EGGS', de: 'EIER', ar: 'بيض', fr: 'OEUFS', es: 'HUEVOS' },
  { tr: 'PEYNİR', en: 'CHEESE', de: 'KÄSE', ar: 'جبنة', fr: 'FROMAGE', es: 'QUESO' },
  { tr: 'YOĞURT', en: 'YOGURT', de: 'JOGHURT', ar: 'زبادي', fr: 'YAOURT', es: 'YOGUR' },
  { tr: 'TEREYAĞI', en: 'BUTTER', de: 'BUTTER', ar: 'زبدة', fr: 'BEURRE', es: 'MANTEQUILLA' },
  { tr: 'ÇAY', en: 'TEA', de: 'TEE', ar: 'شاي', fr: 'THÉ', es: 'TÉ' },
  {
    tr: 'FİLTRE KAHVE',
    en: 'GROUND COFFEE',
    de: 'KAFFEE GEMAHLEN',
    ar: 'بن مطحون',
    fr: 'CAFÉ MOULU',
    es: 'CAFÉ MOLIDO',
  },
  { tr: 'MAKARNA', en: 'PASTA', de: 'NUDELN', ar: 'معكرونة', fr: 'PÂTES', es: 'PASTA' },
  { tr: 'PİRİNÇ', en: 'RICE', de: 'REIS', ar: 'أرز', fr: 'RIZ', es: 'ARROZ' },
  { tr: 'UN', en: 'FLOUR', de: 'MEHL', ar: 'طحين', fr: 'FARINE', es: 'HARINA' },
  { tr: 'BAL', en: 'HONEY', de: 'HONIG', ar: 'عسل', fr: 'MIEL', es: 'MIEL' },
  {
    tr: 'ÇİLEK REÇELİ',
    en: 'STRAWBERRY JAM',
    de: 'ERDBEERMARMELADE',
    ar: 'مربى الفراولة',
    fr: 'CONFITURE FRAISE',
    es: 'MERMELADA DE FRESA',
  },
  { tr: 'ZEYTİN', en: 'OLIVES', de: 'OLIVEN', ar: 'زيتون', fr: 'OLIVES', es: 'ACEITUNAS' },
  { tr: 'DOMATES', en: 'TOMATOES', de: 'TOMATEN', ar: 'طماطم', fr: 'TOMATES', es: 'TOMATES' },
  { tr: 'SALATALIK', en: 'CUCUMBERS', de: 'GURKEN', ar: 'خيار', fr: 'CONCOMBRES', es: 'PEPINOS' },
  { tr: 'SOĞAN', en: 'ONIONS', de: 'ZWIEBELN', ar: 'بصل', fr: 'OIGNONS', es: 'CEBOLLAS' },
  { tr: 'LİMON', en: 'LEMONS', de: 'ZITRONEN', ar: 'ليمون', fr: 'CITRONS', es: 'LIMONES' },
  { tr: 'ELMA', en: 'APPLES', de: 'ÄPFEL', ar: 'تفاح', fr: 'POMMES', es: 'MANZANAS' },
  { tr: 'MUZ', en: 'BANANAS', de: 'BANANEN', ar: 'موز', fr: 'BANANES', es: 'PLÁTANOS' },
  { tr: 'SAKIZ', en: 'GUM', de: 'KAUGUMMI', ar: 'علكة', fr: 'CHEWING-GUM', es: 'CHICLE' },
  { tr: 'BİSKÜVİ', en: 'COOKIES', de: 'KEKSE', ar: 'بسكويت', fr: 'BISCUITS', es: 'GALLETAS' },
  {
    tr: 'KRAKER',
    en: 'CRACKERS',
    de: 'SALZCRACKER',
    ar: 'بسكويت مالح',
    fr: 'CRACKERS',
    es: 'GALLETAS SALADAS',
  },
  {
    tr: 'AY ÇEKİRDEĞİ',
    en: 'SUNFLOWER SEEDS',
    de: 'SONNENBLUMENKERNE',
    ar: 'بذور عباد الشمس',
    fr: 'GRAINES TOURNESOL',
    es: 'SEMILLAS GIRASOL',
  },
  { tr: 'DONDURMA', en: 'ICE CREAM', de: 'EISCREME', ar: 'آيس كريم', fr: 'GLACE', es: 'HELADO' },
  { tr: 'LİMONATA', en: 'LEMONADE', de: 'LIMONADE', ar: 'عصير ليمون', fr: 'LIMONADE', es: 'LIMONADA' },
  {
    tr: 'MADEN SUYU',
    en: 'SPARKLING WATER',
    de: 'MINERALWASSER',
    ar: 'مياه معدنية',
    fr: 'EAU GAZEUSE',
    es: 'AGUA MINERAL',
  },
  {
    tr: 'ALÜMİNYUM FOLYO',
    en: 'ALUMINUM FOIL',
    de: 'ALUFOLIE',
    ar: 'ورق ألمنيوم',
    fr: 'PAPIER ALU',
    es: 'PAPEL DE ALUMINIO',
  },
  {
    tr: 'PEÇETE',
    en: 'NAPKINS',
    de: 'SERVIETTEN',
    ar: 'مناديل مائدة',
    fr: 'SERVIETTES PAPIER',
    es: 'SERVILLETAS',
  },
  {
    tr: 'ISLAK MENDİL',
    en: 'WET WIPES',
    de: 'FEUCHTTÜCHER',
    ar: 'مناديل مبللة',
    fr: 'LINGETTES',
    es: 'TOALLITAS HÚMEDAS',
  },
  {
    tr: 'KAĞIT HAVLU',
    en: 'PAPER TOWELS',
    de: 'KÜCHENROLLE',
    ar: 'مناديل مطبخ',
    fr: 'ESSUIE-TOUT',
    es: 'PAPEL DE COCINA',
  },
  {
    tr: 'TUVALET KAĞIDI',
    en: 'TOILET PAPER',
    de: 'TOILETTENPAPIER',
    ar: 'ورق تواليت',
    fr: 'PAPIER TOILETTE',
    es: 'PAPEL HIGIÉNICO',
  },
  {
    tr: 'BULAŞIK DETERJANI',
    en: 'DISH SOAP',
    de: 'SPÜLMITTEL',
    ar: 'سائل غسيل الصحون',
    fr: 'LIQUIDE VAISSELLE',
    es: 'JABÓN PARA PLATOS',
  },
  { tr: 'SÜNGER', en: 'SPONGES', de: 'SCHWÄMME', ar: 'إسفنج', fr: 'ÉPONGES', es: 'ESPONJAS' },
  {
    tr: 'DİŞ MACUNU',
    en: 'TOOTHPASTE',
    de: 'ZAHNPASTA',
    ar: 'معجون أسنان',
    fr: 'DENTIFRICE',
    es: 'PASTA DE DIENTES',
  },
  {
    tr: 'KOKULU MUM',
    en: 'SCENTED CANDLE',
    de: 'DUFTKERZE',
    ar: 'شمعة معطرة',
    fr: 'BOUGIE PARFUMÉE',
    es: 'VELA AROMÁTICA',
  },
  {
    tr: 'KEDİ MAMASI',
    en: 'CAT FOOD',
    de: 'KATZENFUTTER',
    ar: 'طعام قطط',
    fr: 'CROQUETTES CHAT',
    es: 'COMIDA PARA GATO',
  },
  {
    tr: 'DOĞUM GÜNÜ BALONU',
    en: 'BIRTHDAY BALLOON',
    de: 'GEBURTSTAGSBALLON',
    ar: 'بالون عيد ميلاد',
    fr: "BALLON D'ANNIV",
    es: 'GLOBO CUMPLEAÑOS',
  },
  { tr: 'PORTAKAL', en: 'ORANGES', de: 'ORANGEN', ar: 'برتقال', fr: 'ORANGES', es: 'NARANJAS' },
  { tr: 'HAVUÇ', en: 'CARROTS', de: 'KAROTTEN', ar: 'جزر', fr: 'CAROTTES', es: 'ZANAHORIAS' },
  { tr: 'MARUL', en: 'LETTUCE', de: 'KOPFSALAT', ar: 'خس', fr: 'LAITUE', es: 'LECHUGA' },
  { tr: 'MERCİMEK', en: 'LENTILS', de: 'LINSEN', ar: 'عدس', fr: 'LENTILLES', es: 'LENTEJAS' },
  { tr: 'NOHUT', en: 'CHICKPEAS', de: 'KICHERERBSEN', ar: 'حمص', fr: 'POIS CHICHES', es: 'GARBANZOS' },
  { tr: 'ŞEKER', en: 'SUGAR', de: 'ZUCKER', ar: 'سكر', fr: 'SUCRE', es: 'AZÚCAR' },
  { tr: 'TUZ', en: 'SALT', de: 'SALZ', ar: 'ملح', fr: 'SEL', es: 'SAL' },
  { tr: 'KARABİBER', en: 'BLACK PEPPER', de: 'SCHWARZER PFEFFER', ar: 'فلفل أسود', fr: 'POIVRE NOIR', es: 'PIMIENTA NEGRA' },
  { tr: 'ZEYTİNYAĞI', en: 'OLIVE OIL', de: 'OLIVENÖL', ar: 'زيت زيتون', fr: "HUILE D'OLIVE", es: 'ACEITE DE OLIVA' },
  { tr: 'MISIR GEVREĞİ', en: 'CEREAL', de: 'FRÜHSTÜCKSFLOCKEN', ar: 'رقائق الذرة', fr: 'CÉRÉALES', es: 'CEREALES' },
  { tr: 'YULAF EZMESİ', en: 'OATMEAL', de: 'HAFERFLOCKEN', ar: 'شوفان', fr: "FLOCONS D'AVOINE", es: 'AVENA' },
  { tr: 'KURU ÜZÜM', en: 'RAISINS', de: 'ROSINEN', ar: 'زبيب', fr: 'RAISINS SECS', es: 'PASAS' },
  { tr: 'FINDIK', en: 'HAZELNUTS', de: 'HASELNÜSSE', ar: 'بندق', fr: 'NOISETTES', es: 'AVELLANAS' },
  { tr: 'CEVİZ', en: 'WALNUTS', de: 'WALNÜSSE', ar: 'جوز', fr: 'NOIX', es: 'NUECES' },
  { tr: 'KEK', en: 'SNACK CAKE', de: 'RÜHRKUCHEN', ar: 'كعكة', fr: 'GÂTEAU', es: 'BIZCOCHO' },
  { tr: 'KARPUZ', en: 'WATERMELON', de: 'WASSERMELONE', ar: 'بطيخ', fr: 'PASTÈQUE', es: 'SANDÍA' },
  { tr: 'ARMUT', en: 'PEARS', de: 'BIRNEN', ar: 'كمثرى', fr: 'POIRES', es: 'PERAS' },
  { tr: 'KİVİ', en: 'KIWIS', de: 'KIWIS', ar: 'كيوي', fr: 'KIWIS', es: 'KIWIS' },
  { tr: 'MANTAR', en: 'MUSHROOMS', de: 'PILZE', ar: 'فطر', fr: 'CHAMPIGNONS', es: 'CHAMPIÑONES' },
  { tr: 'BİBER', en: 'BELL PEPPERS', de: 'PAPRIKA', ar: 'فلفل رومي', fr: 'POIVRONS', es: 'PIMIENTOS' },
  { tr: 'KİRAZ', en: 'CHERRIES', de: 'KIRSCHEN', ar: 'كرز', fr: 'CERISES', es: 'CEREZAS' },
  { tr: 'ŞAMPUAN', en: 'SHAMPOO', de: 'SHAMPOO', ar: 'شامبو', fr: 'SHAMPOING', es: 'CHAMPÚ' },
  { tr: 'SABUN', en: 'SOAP', de: 'SEIFE', ar: 'صابون', fr: 'SAVON', es: 'JABÓN' },
  { tr: 'DİŞ FIRÇASI', en: 'TOOTHBRUSH', de: 'ZAHNBÜRSTE', ar: 'فرشاة أسنان', fr: 'BROSSE À DENTS', es: 'CEPILLO DE DIENTES' },
  { tr: 'ÇAMAŞIR DETERJANI', en: 'LAUNDRY DETERGENT', de: 'WASCHMITTEL', ar: 'مسحوق غسيل', fr: 'LESSIVE', es: 'DETERGENTE' },
  { tr: 'ÇÖP TORBASI', en: 'TRASH BAGS', de: 'MÜLLBEUTEL', ar: 'أكياس قمامة', fr: 'SACS POUBELLE', es: 'BOLSAS DE BASURA' },
  { tr: 'BANT', en: 'TAPE', de: 'KLEBEBAND', ar: 'شريط لاصق', fr: 'RUBAN ADHÉSIF', es: 'CINTA ADHESIVA' },
  { tr: 'DEFTER', en: 'NOTEBOOK', de: 'NOTIZBUCH', ar: 'دفتر', fr: 'CAHIER', es: 'CUADERNO' },
  { tr: 'HAZIR ÇORBA', en: 'INSTANT SOUP', de: 'TÜTENSUPPE', ar: 'حساء سريع', fr: 'SOUPE INSTANTANÉE', es: 'SOPA INSTANTÁNEA' },
  { tr: 'PUDİNG', en: 'PUDDING CUPS', de: 'PUDDING', ar: 'مهلبية', fr: 'CRÈME DESSERT', es: 'PUDÍN' },
];

/**
 * The ordinary notifications of a lock screen, under the post's own
 * punchline: an app or a person, and one line. Nothing alarming, nothing
 * about the player's real phone — just the everyday pile.
 */
export const NOTICES: readonly Notice[] = [
  {
    icon: '🔋',
    app: { tr: 'Pil', en: 'Battery', de: 'Akku', ar: 'البطارية', fr: 'Batterie', es: 'Batería' },
    text: {
      tr: '%3 kaldı',
      en: '3% left',
      de: 'Noch 3 %',
      ar: 'متبقٍ 3%',
      fr: 'Plus que 3 %',
      es: 'Queda un 3 %',
    },
  },
  {
    icon: '☀️',
    app: {
      tr: 'Hava durumu',
      en: 'Weather',
      de: 'Wetter',
      ar: 'الطقس',
      fr: 'Météo',
      es: 'Pronóstico',
    },
    text: {
      tr: 'Bugün güneşli, en yüksek 24°',
      en: 'Sunny today, high of 75°',
      de: 'Heute sonnig, bis zu 24°',
      ar: 'مشمس اليوم، والعظمى 24°',
      fr: "Soleil aujourd'hui, jusqu'à 24°",
      es: 'Soleado hoy, máxima de 24°',
    },
  },
  {
    icon: '📅',
    app: {
      tr: 'Takvim',
      en: 'Calendar',
      de: 'Kalender',
      ar: 'التقويم',
      fr: 'Agenda',
      es: 'Calendario',
    },
    text: {
      tr: 'Yarın 10.00 · Kuaför',
      en: 'Tomorrow 10 AM · Haircut',
      de: 'Morgen 10:00 · Friseur',
      ar: 'غدًا 10:00 · موعد الحلاق',
      fr: 'Demain 10 h · Coiffeur',
      es: 'Mañana 10:00 · Peluquería',
    },
  },
  {
    icon: '📦',
    app: {
      tr: 'Kargo',
      en: 'Deliveries',
      de: 'Paketdienst',
      ar: 'الشحن',
      fr: 'Colis',
      es: 'Envíos',
    },
    text: {
      tr: 'Paketin yola çıktı, yarın kapında',
      en: 'Your package is on its way',
      de: 'Dein Paket ist unterwegs',
      ar: 'طردك في الطريق إليك',
      fr: 'Ton colis est en route',
      es: 'Tu paquete va en camino',
    },
  },
  {
    icon: '⏰',
    app: { tr: 'Alarm', en: 'Alarm', de: 'Wecker', ar: 'المنبه', fr: 'Réveil', es: 'Alarma' },
    text: {
      tr: 'Günaydın! Saat 07.30',
      en: "Good morning! It's 7:30",
      de: 'Guten Morgen! Es ist 7:30',
      ar: 'صباح الخير! الساعة 7:30',
      fr: 'Bonjour ! Il est 7 h 30',
      es: '¡Buenos días! Son las 7:30',
    },
  },
  {
    icon: '🖼️',
    app: { tr: 'Fotoğraflar', en: 'Photos', de: 'Fotos', ar: 'الصور', fr: 'Photos', es: 'Fotos' },
    text: {
      tr: 'Anılar: 3 yıl önce bugün',
      en: 'Memories: 3 years ago today',
      de: 'Erinnerungen: heute vor 3 Jahren',
      ar: 'ذكريات: في مثل هذا اليوم قبل 3 سنوات',
      fr: 'Souvenirs : il y a 3 ans jour pour jour',
      es: 'Recuerdos: hace 3 años, un día como hoy',
    },
  },
  {
    icon: '👣',
    app: {
      tr: 'Adım sayar',
      en: 'Step counter',
      de: 'Schrittzähler',
      ar: 'عداد الخطوات',
      fr: 'Podomètre',
      es: 'Podómetro',
    },
    text: {
      tr: 'Günlük hedefinin yarısındasın!',
      en: "You're halfway to your daily goal!",
      de: 'Halbes Tagesziel geschafft!',
      ar: 'وصلت إلى نصف هدفك اليومي!',
      fr: 'Tu es à mi-chemin de ton objectif !',
      es: '¡Vas a la mitad de tu meta diaria!',
    },
  },
  {
    icon: '💾',
    app: {
      tr: 'Ayarlar',
      en: 'Settings',
      de: 'Einstellungen',
      ar: 'الإعدادات',
      fr: 'Réglages',
      es: 'Ajustes',
    },
    text: {
      tr: 'Depolama alanı neredeyse dolu',
      en: 'Storage almost full',
      de: 'Speicher fast voll',
      ar: 'مساحة التخزين شبه ممتلئة',
      fr: 'Stockage presque plein',
      es: 'Almacenamiento casi lleno',
    },
  },
  {
    icon: '⚙️',
    app: {
      tr: 'Güncelleme',
      en: 'Software update',
      de: 'Softwareupdate',
      ar: 'تحديث النظام',
      fr: 'Mise à jour',
      es: 'Actualización',
    },
    text: {
      tr: 'Bu gece otomatik yüklenecek',
      en: 'Will install automatically tonight',
      de: 'Wird heute Nacht automatisch installiert',
      ar: 'سيُثبَّت تلقائيًا الليلة',
      fr: 'Installation automatique cette nuit',
      es: 'Se instalará sola esta noche',
    },
  },
  {
    icon: '🎙️',
    app: {
      tr: 'Podcast',
      en: 'Podcasts',
      de: 'Podcasts',
      ar: 'بودكاست',
      fr: 'Podcasts',
      es: 'Podcasts',
    },
    text: {
      tr: 'Kaldığın yerden devam edelim mi?',
      en: 'Pick up where you left off?',
      de: 'Weiterhören, wo du aufgehört hast?',
      ar: 'هل تتابع من حيث توقفت؟',
      fr: "Reprendre là où tu t'es arrêté ?",
      es: '¿Seguir donde te quedaste?',
    },
  },
  {
    icon: '💧',
    app: {
      tr: 'Su takibi',
      en: 'Water tracker',
      de: 'Trink-Erinnerung',
      ar: 'تذكير الماء',
      fr: 'Hydratation',
      es: 'Hidratación',
    },
    text: {
      tr: 'Bir bardak su içme vakti',
      en: 'Time for a glass of water',
      de: 'Zeit für ein Glas Wasser',
      ar: 'حان وقت شرب كوب ماء',
      fr: "C'est l'heure d'un verre d'eau",
      es: 'Hora de tomar un vaso de agua',
    },
  },
  {
    icon: '💬',
    app: {
      tr: 'Kanka',
      en: 'Bestie',
      de: 'Bester Kumpel',
      ar: 'صديقي',
      fr: 'Mon pote',
      es: 'Mi mejor amigo',
    },
    text: { tr: '😂😂', en: '😂😂', de: '😂😂', ar: '😂😂', fr: '😂😂', es: '😂😂' },
  },
  {
    icon: '👪',
    app: {
      tr: 'Aile grubu',
      en: 'Family group',
      de: 'Familiengruppe',
      ar: 'مجموعة العائلة',
      fr: 'Groupe famille',
      es: 'Grupo familiar',
    },
    text: {
      tr: '12 yeni mesaj',
      en: '12 new messages',
      de: '12 neue Nachrichten',
      ar: '12 رسالة جديدة',
      fr: '12 nouveaux messages',
      es: '12 mensajes nuevos',
    },
  },
  {
    icon: '🎂',
    app: {
      tr: 'Doğum günleri',
      en: 'Birthdays',
      de: 'Geburtstage',
      ar: 'أعياد الميلاد',
      fr: 'Anniversaires',
      es: 'Cumpleaños',
    },
    text: {
      tr: 'Yarın bir arkadaşının doğum günü',
      en: "A friend's birthday is tomorrow",
      de: 'Morgen hat ein Freund Geburtstag',
      ar: 'غدًا عيد ميلاد أحد أصدقائك',
      fr: "Demain, c'est l'anniv d'un ami",
      es: 'Mañana cumple años un amigo',
    },
  },
  {
    icon: '🌙',
    app: { tr: 'Uyku', en: 'Sleep', de: 'Schlaf', ar: 'النوم', fr: 'Sommeil', es: 'Sueño' },
    text: {
      tr: 'Yatma saatine 30 dakika var',
      en: 'Bedtime in 30 minutes',
      de: 'In 30 Minuten ist Schlafenszeit',
      ar: 'بقيت 30 دقيقة على موعد النوم',
      fr: 'Au lit dans 30 minutes',
      es: 'Faltan 30 minutos para dormir',
    },
  },
  {
    icon: '🎵',
    app: { tr: 'Müzik', en: 'Music', de: 'Musik', ar: 'الموسيقى', fr: 'Musique', es: 'Música' },
    text: {
      tr: 'Haftalık karışık listen hazır',
      en: 'Your weekly mix is ready',
      de: 'Dein Wochenmix ist da',
      ar: 'قائمة أغانيك الأسبوعية جاهزة',
      fr: 'Ton mix de la semaine est prêt',
      es: 'Tu mix semanal está listo',
    },
  },
  {
    icon: '📝',
    app: {
      tr: 'Alışveriş listesi',
      en: 'Shopping list',
      de: 'Einkaufsliste',
      ar: 'قائمة المشتريات',
      fr: 'Liste de courses',
      es: 'Lista de compras',
    },
    text: {
      tr: 'Domates, peynir, deterjan',
      en: 'Tomatoes, cheese, dish soap',
      de: 'Tomaten, Käse, Spülmittel',
      ar: 'طماطم، جبن، سائل جلي',
      fr: 'Tomates, fromage, liquide vaisselle',
      es: 'Tomates, queso y detergente',
    },
  },
  {
    icon: '🧺',
    app: {
      tr: 'Çamaşır makinesi',
      en: 'Washer',
      de: 'Waschmaschine',
      ar: 'الغسالة',
      fr: 'Lave-linge',
      es: 'Lavadora',
    },
    text: {
      tr: 'Yıkama bitti, asmayı unutma',
      en: "Laundry's done!",
      de: 'Die Wäsche ist fertig',
      ar: 'انتهى الغسيل، لا تنسَ نشره',
      fr: "Lessive terminée, pense à l'étendre",
      es: 'Terminó el lavado',
    },
  },
  {
    icon: '🚏',
    app: {
      tr: 'Toplu taşıma',
      en: 'Transit',
      de: 'Nahverkehr',
      ar: 'النقل العام',
      fr: 'Transports',
      es: 'Transporte',
    },
    text: {
      tr: 'Otobüsün 4 dakika sonra durakta',
      en: 'Your bus arrives in 4 min',
      de: 'Dein Bus kommt in 4 Min.',
      ar: 'حافلتك تصل بعد 4 دقائق',
      fr: 'Ton bus arrive dans 4 min',
      es: 'Tu bus llega en 4 min',
    },
  },
  {
    icon: '📚',
    app: {
      tr: 'Kütüphane',
      en: 'Library',
      de: 'Bibliothek',
      ar: 'المكتبة',
      fr: 'Bibliothèque',
      es: 'Biblioteca',
    },
    text: {
      tr: 'Kitabının iade tarihi yarın',
      en: 'Your book is due back tomorrow',
      de: 'Dein Buch muss morgen zurück',
      ar: 'موعد إعادة كتابك غدًا',
      fr: 'Ton livre est à rendre demain',
      es: 'Mañana vence el préstamo de tu libro',
    },
  },
  {
    icon: '🥡',
    app: {
      tr: 'Yemek siparişi',
      en: 'Food delivery',
      de: 'Essenslieferung',
      ar: 'توصيل الطعام',
      fr: 'Livraison repas',
      es: 'Comida a domicilio',
    },
    text: {
      tr: 'Siparişin hazırlanıyor',
      en: 'Your order is being prepared',
      de: 'Deine Bestellung wird zubereitet',
      ar: 'طلبك قيد التحضير',
      fr: 'Ta commande est en préparation',
      es: 'Tu pedido se está preparando',
    },
  },
  {
    icon: '🌷',
    app: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá' },
    text: {
      tr: 'Akşam yemeğe gelir misin?',
      en: 'Coming over for dinner tonight?',
      de: 'Kommst du heute zum Abendessen?',
      ar: 'هل ستأتي على العشاء الليلة؟',
      fr: 'Tu viens dîner ce soir ?',
      es: '¿Vienes a cenar esta noche?',
    },
  },
  {
    icon: '🧘',
    app: {
      tr: 'Mola',
      en: 'Mindfulness',
      de: 'Achtsamkeit',
      ar: 'استراحة',
      fr: 'Pause',
      es: 'Pausa',
    },
    text: {
      tr: '1 dakikalık nefes molasına ne dersin?',
      en: 'How about a 1-minute breather?',
      de: "Wie wär's mit einer Atempause?",
      ar: 'ما رأيك في استراحة تنفّس لدقيقة؟',
      fr: "Une pause respiration d'une minute ?",
      es: '¿Una pausa de un minuto para respirar?',
    },
  },
  {
    icon: '✉️',
    app: { tr: 'E-posta', en: 'Mail', de: 'E-Mail', ar: 'البريد', fr: 'E-mail', es: 'Correo' },
    text: {
      tr: '3 yeni e-posta',
      en: '3 new emails',
      de: '3 neue E-Mails',
      ar: '3 رسائل بريد جديدة',
      fr: '3 nouveaux e-mails',
      es: '3 correos nuevos',
    },
  },
  {
    icon: '🌱',
    app: {
      tr: 'Bitki bakımı',
      en: 'Plant care',
      de: 'Pflanzenpflege',
      ar: 'رعاية النباتات',
      fr: 'Mes plantes',
      es: 'Mis plantas',
    },
    text: {
      tr: 'Bitkileri sulama günü',
      en: 'Time to water your plants',
      de: 'Zeit, die Pflanzen zu gießen',
      ar: 'حان وقت سقي النباتات',
      fr: "C'est le jour d'arroser les plantes",
      es: 'Hora de regar las plantas',
    },
  },
  {
    icon: '💪',
    app: { tr: 'Spor', en: 'Fitness', de: 'Fitness', ar: 'اللياقة', fr: 'Sport', es: 'Ejercicio' },
    text: {
      tr: 'Bu hafta 2 antrenman, süpersin!',
      en: '2 workouts this week, nice work!',
      de: '2 Workouts diese Woche, stark!',
      ar: 'تمرينان هذا الأسبوع، أحسنت!',
      fr: '2 séances cette semaine, bravo !',
      es: '¡Bien! 2 entrenamientos esta semana',
    },
  },
  {
    icon: '🚪',
    app: {
      tr: 'Komşu',
      en: 'Neighbor',
      de: 'Nachbarin',
      ar: 'الجارة',
      fr: 'Voisine',
      es: 'Vecina',
    },
    text: {
      tr: 'Kargonu ben teslim aldım',
      en: 'I picked up your package for you',
      de: 'Hab dein Paket angenommen',
      ar: 'استلمتُ طردك نيابةً عنك',
      fr: "J'ai récupéré ton colis",
      es: 'Recibí tu paquete, lo tengo yo',
    },
  },
  {
    icon: '📺',
    app: {
      tr: 'Diziler',
      en: 'TV shows',
      de: 'Serien',
      ar: 'المسلسلات',
      fr: 'Séries',
      es: 'Series',
    },
    text: {
      tr: 'Yeni bölüm yayında!',
      en: 'New episode out now!',
      de: 'Neue Folge ist online!',
      ar: 'حلقة جديدة متاحة الآن!',
      fr: 'Nouvel épisode dispo !',
      es: '¡Ya salió el nuevo episodio!',
    },
  },
  {
    icon: '🗺️',
    app: {
      tr: 'Navigasyon',
      en: 'Navigation',
      de: 'Navi',
      ar: 'الملاحة',
      fr: 'Itinéraire',
      es: 'Navegación',
    },
    text: {
      tr: 'Eve 12 dakika, yollar açık',
      en: '12 min to home, roads are clear',
      de: '12 Min. bis nach Hause, freie Fahrt',
      ar: '12 دقيقة إلى المنزل، الطريق سالك',
      fr: 'Maison à 12 min, ça roule',
      es: '12 min a casa, tráfico fluido',
    },
  },
  {
    icon: '❤️',
    app: {
      tr: 'Sosyal medya',
      en: 'Social media',
      de: 'Social Media',
      ar: 'التواصل الاجتماعي',
      fr: 'Réseaux sociaux',
      es: 'Redes sociales',
    },
    text: {
      tr: '3 arkadaşın yeni gönderi paylaştı',
      en: '3 friends shared new posts',
      de: '3 Freunde haben was Neues gepostet',
      ar: '3 من أصدقائك نشروا منشورات جديدة',
      fr: '3 amis ont publié de nouveaux posts',
      es: '3 amigos publicaron algo nuevo',
    },
  },
  {
    icon: '✈️',
    app: {
      tr: 'Geri sayım',
      en: 'Countdown',
      de: 'Countdown',
      ar: 'العد التنازلي',
      fr: 'Compte à rebours',
      es: 'Cuenta regresiva',
    },
    text: {
      tr: 'Tatile 23 gün kaldı!',
      en: '23 days until vacation!',
      de: 'Noch 23 Tage bis zum Urlaub!',
      ar: 'بقي 23 يومًا على الإجازة!',
      fr: 'Plus que 23 jours avant les vacances !',
      es: '¡Faltan 23 días para las vacaciones!',
    },
  },
  {
    icon: '🐾',
    app: {
      tr: 'Evcil hayvan',
      en: 'Pet care',
      de: 'Haustier',
      ar: 'الحيوان الأليف',
      fr: 'Mon animal',
      es: 'Mascota',
    },
    text: {
      tr: 'Kedinin mama saati geldi',
      en: 'Time to feed the cat',
      de: 'Zeit, die Katze zu füttern',
      ar: 'حان موعد إطعام القطة',
      fr: "C'est l'heure de nourrir le chat",
      es: 'Hora de darle de comer al gato',
    },
  },
  {
    icon: '🧹',
    app: {
      tr: 'Robot süpürge',
      en: 'Robot vacuum',
      de: 'Saugroboter',
      ar: 'المكنسة الذكية',
      fr: 'Robot aspirateur',
      es: 'Robot aspiradora',
    },
    text: {
      tr: 'Salon temizliği tamamlandı',
      en: 'Living room cleaned',
      de: 'Wohnzimmer ist sauber',
      ar: 'اكتمل تنظيف غرفة المعيشة',
      fr: 'Salon nettoyé',
      es: 'Limpieza de la sala terminada',
    },
  },
  {
    icon: '🥕',
    app: {
      tr: 'Tarifler',
      en: 'Recipes',
      de: 'Rezepte',
      ar: 'وصفات',
      fr: 'Recettes',
      es: 'Recetas',
    },
    text: {
      tr: 'Günün tarifi: Fırında sebze',
      en: 'Recipe of the day: roasted veggies',
      de: 'Rezept des Tages: Ofengemüse',
      ar: 'وصفة اليوم: خضار في الفرن',
      fr: 'Recette du jour : légumes rôtis',
      es: 'Receta del día: verduras al horno',
    },
  },
  {
    icon: '🏖️',
    app: { tr: 'Kuzenim', en: 'Cousin', de: 'Cousine', ar: 'ابنة عمي', fr: 'Cousine', es: 'Prima' },
    text: {
      tr: 'Tatil fotoğraflarını attım',
      en: 'Sent you the vacation pics',
      de: 'Hab dir die Urlaubsfotos geschickt',
      ar: 'أرسلت لك صور الإجازة',
      fr: "Je t'ai envoyé les photos de vacances",
      es: 'Te mandé las fotos del viaje',
    },
  },
  {
    icon: '🗑️',
    app: {
      tr: 'Hatırlatıcı',
      en: 'Reminders',
      de: 'Erinnerungen',
      ar: 'التذكيرات',
      fr: 'Rappels',
      es: 'Recordatorios',
    },
    text: {
      tr: 'Çöpü çıkarmayı unutma',
      en: "Don't forget to take out the trash",
      de: 'Müll rausbringen nicht vergessen',
      ar: 'لا تنسَ إخراج القمامة',
      fr: 'Pense à sortir les poubelles',
      es: 'No olvides sacar la basura',
    },
  },
  {
    icon: '🎧',
    app: {
      tr: 'Kulaklık',
      en: 'Earbuds',
      de: 'Kopfhörer',
      ar: 'السماعات',
      fr: 'Écouteurs',
      es: 'Auriculares',
    },
    text: {
      tr: 'Kulaklık bağlandı',
      en: 'Earbuds connected',
      de: 'Kopfhörer verbunden',
      ar: 'تم توصيل السماعات',
      fr: 'Écouteurs connectés',
      es: 'Auriculares conectados',
    },
  },
  {
    icon: '☕️',
    app: { tr: 'Kafe', en: 'Coffee shop', de: 'Café', ar: 'المقهى', fr: 'Café', es: 'Cafetería' },
    text: {
      tr: 'Kahven hazır, tezgâhta seni bekliyor',
      en: 'Your coffee is ready at the counter',
      de: 'Dein Kaffee wartet an der Theke',
      ar: 'قهوتك جاهزة عند المنضدة',
      fr: "Ton café t'attend au comptoir",
      es: 'Tu café está listo en la barra',
    },
  },
  {
    icon: '🍿',
    app: { tr: 'Sinema', en: 'Movies', de: 'Kino', ar: 'السينما', fr: 'Cinéma', es: 'Cine' },
    text: {
      tr: 'Biletin hazır: Salon 3, koltuk 7',
      en: 'Your ticket: Theater 3, seat 7',
      de: 'Dein Ticket: Saal 3, Platz 7',
      ar: 'تذكرتك جاهزة: القاعة 3، المقعد 7',
      fr: 'Ton billet : salle 3, siège 7',
      es: 'Tu entrada: sala 3, asiento 7',
    },
  },
  {
    icon: '📖',
    app: {
      tr: 'E-kitap',
      en: 'E-books',
      de: 'E-Books',
      ar: 'الكتب الإلكترونية',
      fr: 'Liseuse',
      es: 'Libros',
    },
    text: {
      tr: 'Bugün 10 sayfa okudun, harika!',
      en: 'You read 10 pages today. Nice!',
      de: 'Heute 10 Seiten gelesen. Stark!',
      ar: 'قرأت 10 صفحات اليوم، رائع!',
      fr: "10 pages lues aujourd'hui, bravo !",
      es: '¡Hoy leíste 10 páginas, genial!',
    },
  },
  {
    icon: '🏃',
    app: { tr: 'Koşu', en: 'Running', de: 'Laufen', ar: 'الجري', fr: 'Course', es: 'Carrera' },
    text: {
      tr: '3 km’lik koşun kaydedildi',
      en: 'Your 2-mile run is saved',
      de: 'Dein 3-km-Lauf ist gespeichert',
      ar: 'تم حفظ جريك لمسافة 3 كم',
      fr: 'Ta course de 3 km est enregistrée',
      es: 'Tu carrera de 3 km quedó guardada',
    },
  },
  {
    icon: '🎮',
    app: { tr: 'Oyun', en: 'Games', de: 'Spiele', ar: 'الألعاب', fr: 'Jeux', es: 'Juegos' },
    text: {
      tr: 'Günlük görevler yenilendi',
      en: 'Daily quests have been refreshed',
      de: 'Neue Tagesaufgaben sind da',
      ar: 'تم تجديد المهام اليومية',
      fr: 'Nouvelles quêtes du jour dispo',
      es: 'Se renovaron las misiones diarias',
    },
  },
  {
    icon: '🍕',
    app: {
      tr: 'Ev arkadaşı',
      en: 'Roommate',
      de: 'Mitbewohner',
      ar: 'زميل السكن',
      fr: 'Coloc',
      es: 'Compañero de casa',
    },
    text: {
      tr: 'Pizza söylüyorum, ister misin?',
      en: 'Ordering pizza, want some?',
      de: 'Ich bestell Pizza, willst du auch?',
      ar: 'سأطلب بيتزا، هل تريد؟',
      fr: "Je commande une pizza, t'en veux ?",
      es: 'Voy a pedir pizza, ¿quieres?',
    },
  },
  {
    icon: '🚗',
    app: {
      tr: 'Otopark',
      en: 'Parking',
      de: 'Parkhaus',
      ar: 'موقف السيارات',
      fr: 'Parking',
      es: 'Estacionamiento',
    },
    text: {
      tr: 'Aracın 2. katta, B bölümünde',
      en: 'Your car is on level 2, section B',
      de: 'Dein Auto steht auf Ebene 2, Bereich B',
      ar: 'سيارتك في الطابق الثاني',
      fr: 'Ta voiture est au niveau 2, zone B',
      es: 'Tu vehículo está en el nivel 2, zona B',
    },
  },
  {
    icon: '🌡️',
    app: {
      tr: 'Termostat',
      en: 'Thermostat',
      de: 'Thermostat',
      ar: 'منظم الحرارة',
      fr: 'Thermostat',
      es: 'Termostato',
    },
    text: {
      tr: 'Ev 22 dereceye ısındı',
      en: 'Home warmed up to 72°',
      de: 'Die Wohnung hat jetzt 22 Grad',
      ar: 'وصلت حرارة البيت إلى 22 درجة',
      fr: 'La maison est à 22 degrés',
      es: 'La casa ya está a 22 grados',
    },
  },
  {
    icon: '🎈',
    app: {
      tr: 'Hatırlatıcı',
      en: 'Reminders',
      de: 'Erinnerungen',
      ar: 'التذكيرات',
      fr: 'Rappels',
      es: 'Recordatorios',
    },
    text: {
      tr: 'Parti için balon almayı unutma',
      en: "Don't forget balloons for the party",
      de: 'Luftballons für die Party kaufen',
      ar: 'لا تنسَ شراء البالونات للحفلة',
      fr: 'Pense aux ballons pour la fête',
      es: 'No olvides los globos para la fiesta',
    },
  },
  {
    icon: '🐶',
    app: {
      tr: 'Köpek bakıcısı',
      en: 'Dog walker',
      de: 'Hundesitter',
      ar: 'جليسة الكلب',
      fr: 'Promeneur de chien',
      es: 'Paseador de perros',
    },
    text: {
      tr: 'Köpeğin parkta çok eğlendi!',
      en: 'Your pup had a blast at the park!',
      de: 'Dein Hund hatte Spaß im Park!',
      ar: 'استمتع كلبك كثيرًا في الحديقة!',
      fr: 'Ton chien a adoré le parc !',
      es: '¡Tu perro disfrutó mucho del parque!',
    },
  },
  {
    icon: '📻',
    app: { tr: 'Radyo', en: 'Radio', de: 'Radio', ar: 'الراديو', fr: 'Radio', es: 'Radio' },
    text: {
      tr: 'En sevdiğin program başladı',
      en: 'Your favorite show just started',
      de: 'Deine Lieblingssendung läuft',
      ar: 'بدأ برنامجك المفضل',
      fr: 'Ton émission préférée commence',
      es: 'Empezó tu programa favorito',
    },
  },
  {
    icon: '🧩',
    app: {
      tr: 'Bulmaca',
      en: 'Puzzles',
      de: 'Rätsel',
      ar: 'الألغاز',
      fr: 'Casse-tête',
      es: 'Crucigrama',
    },
    text: {
      tr: 'Günün bulmacası hazır',
      en: "Today's puzzle is ready",
      de: 'Das Rätsel des Tages ist da',
      ar: 'لغز اليوم جاهز',
      fr: 'Le casse-tête du jour est prêt',
      es: 'El crucigrama del día está listo',
    },
  },
  {
    icon: '💡',
    app: {
      tr: 'Akıllı ev',
      en: 'Smart home',
      de: 'Smart Home',
      ar: 'المنزل الذكي',
      fr: 'Maison connectée',
      es: 'Casa inteligente',
    },
    text: {
      tr: 'Balkon ışıkları 19.00’da yandı',
      en: 'Porch lights came on at 7 PM',
      de: 'Balkonlicht ging um 19 Uhr an',
      ar: 'أُضيئت أنوار الشرفة في السابعة مساءً',
      fr: 'Lumières du balcon allumées à 19 h',
      es: 'Luces del balcón encendidas a las 19:00',
    },
  },
  {
    icon: '⚽️',
    app: { tr: 'Maç', en: 'Soccer', de: 'Fußball', ar: 'المباراة', fr: 'Match', es: 'Partido' },
    text: {
      tr: 'Maç 20.00’de başlıyor',
      en: 'Kickoff at 8 PM',
      de: 'Anpfiff um 20 Uhr',
      ar: 'تبدأ المباراة في الثامنة مساءً',
      fr: "Coup d'envoi à 20 h",
      es: 'El partido empieza a las 20:00',
    },
  },
  {
    icon: '🎨',
    app: {
      tr: 'Resim kursu',
      en: 'Art class',
      de: 'Malkurs',
      ar: 'دورة الرسم',
      fr: 'Cours de dessin',
      es: 'Clase de pintura',
    },
    text: {
      tr: 'Ders yarın 18.00’de, fırçanı unutma',
      en: 'Class tomorrow at 6 PM, bring a brush',
      de: 'Morgen 18 Uhr, Pinsel nicht vergessen',
      ar: 'الدرس غدًا في السادسة، لا تنسَ فرشاتك',
      fr: 'Cours demain à 18 h, pense au pinceau',
      es: 'Clase mañana a las 18:00, trae tu pincel',
    },
  },
  {
    icon: '🧶',
    app: { tr: 'Anneannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela' },
    text: {
      tr: 'Sana yeni bir atkı örüyorum',
      en: "I'm knitting you a new scarf",
      de: 'Ich stricke dir einen neuen Schal',
      ar: 'أحيك لك وشاحًا جديدًا',
      fr: 'Je te tricote une nouvelle écharpe',
      es: 'Te estoy tejiendo una bufanda nueva',
    },
  },
  {
    icon: '🌻',
    app: { tr: 'Teyzem', en: 'Auntie', de: 'Tante', ar: 'خالتي', fr: 'Tatie', es: 'Tía' },
    text: {
      tr: 'Bahçeden domates gönderdim',
      en: 'Sent you tomatoes from the garden',
      de: 'Hab dir Tomaten aus dem Garten geschickt',
      ar: 'أرسلت لك طماطم من الحديقة',
      fr: "Je t'ai envoyé des tomates du jardin",
      es: 'Te mandé tomates de la huerta',
    },
  },
  {
    icon: '🚕',
    app: { tr: 'Taksi', en: 'Taxi', de: 'Taxi', ar: 'سيارة الأجرة', fr: 'Taxi', es: 'Taxi' },
    text: {
      tr: 'Taksin kapıda',
      en: 'Your taxi is outside',
      de: 'Dein Taxi ist da',
      ar: 'سيارة الأجرة عند الباب',
      fr: 'Ton taxi est devant la porte',
      es: 'Tu taxi está en la puerta',
    },
  },
  {
    icon: '🖨️',
    app: {
      tr: 'Yazıcı',
      en: 'Printer',
      de: 'Drucker',
      ar: 'الطابعة',
      fr: 'Imprimante',
      es: 'Impresora',
    },
    text: {
      tr: 'Belgen yazdırıldı (3 sayfa)',
      en: 'Your document printed (3 pages)',
      de: 'Dokument gedruckt (3 Seiten)',
      ar: 'تمت طباعة مستندك (3 صفحات)',
      fr: 'Document imprimé (3 pages)',
      es: 'Documento impreso (3 páginas)',
    },
  },
  {
    icon: '🍽️',
    app: {
      tr: 'Bulaşık makinesi',
      en: 'Dishwasher',
      de: 'Spülmaschine',
      ar: 'غسالة الصحون',
      fr: 'Lave-vaisselle',
      es: 'Lavavajillas',
    },
    text: {
      tr: 'Yıkama bitti, tabaklar pırıl pırıl',
      en: 'Cycle done, the dishes are sparkling',
      de: 'Fertig, das Geschirr glänzt',
      ar: 'انتهى الغسيل، والصحون تلمع',
      fr: 'Lavage terminé, tout brille',
      es: 'Lavado listo, los platos relucen',
    },
  },
  {
    icon: '🎉',
    app: {
      tr: 'Arkadaş grubu',
      en: 'Friends group',
      de: 'Freundesgruppe',
      ar: 'مجموعة الأصدقاء',
      fr: 'Groupe des potes',
      es: 'Grupo de amigos',
    },
    text: {
      tr: 'Cuma akşamı herkes bizde!',
      en: 'Friday night, everyone at our place!',
      de: 'Freitagabend sind alle bei uns!',
      ar: 'مساء الجمعة، الجميع عندنا!',
      fr: 'Vendredi soir, tous chez nous !',
      es: '¡El viernes, todos a mi casa!',
    },
  },
  {
    icon: '🦉',
    app: {
      tr: 'Kitap kulübü',
      en: 'Book club',
      de: 'Buchclub',
      ar: 'نادي الكتاب',
      fr: 'Club de lecture',
      es: 'Club de lectura',
    },
    text: {
      tr: 'Bu ayın kitabı seçildi',
      en: "This month's book has been picked",
      de: 'Das Buch des Monats steht fest',
      ar: 'تم اختيار كتاب هذا الشهر',
      fr: 'Le livre du mois est choisi',
      es: 'Ya se eligió el libro del mes',
    },
  },
  {
    icon: '🌈',
    app: {
      tr: 'Hava durumu',
      en: 'Weather',
      de: 'Wetter',
      ar: 'الطقس',
      fr: 'Météo',
      es: 'Pronóstico',
    },
    text: {
      tr: 'Akşama gökkuşağı çıkabilir',
      en: 'Rainbow possible this evening',
      de: 'Heute Abend vielleicht ein Regenbogen',
      ar: 'قد يظهر قوس قزح مساءً',
      fr: 'Arc-en-ciel possible ce soir',
      es: 'Posible arcoíris esta tarde',
    },
  },
];

/** The face at the top of a chat screenshot. */
export const AVATARS: readonly string[] = ['🙂', '😎', '🤓', '😺', '🐻', '🦊', '🐼', '🐸', '🌻', '⚽️', '🎧', '🍕'];

/** What a post may wear in a corner, like a sticker on a story. */
export const STICKERS: readonly string[] = [
  '✨',
  '🔥',
  '💯',
  '👀',
  '😂',
  '😅',
  '🙃',
  '🤯',
  '😴',
  '👍',
  '🎉',
  '⭐️',
  '💥',
  '🌈',
  '💫',
  '🤌',
];
