import type { Localized, Notice } from './types';

/**
 * The parts a format borrows so that one post rarely looks the same twice:
 * the ordinary lines of a receipt, the notifications piled under a lock
 * screen's punchline, a chat contact's face, a corner sticker. The app picks
 * them from the seed and the reel's place (`apps/mobile/src/game/dress.ts`),
 * so a run always wears the same ones. They never reach the API, so a pool
 * may grow, shrink or be reworded at any time — but every entry is written in
 * all six languages, and what a player reads is as clean as a caption.
 */

/**
 * What else ends up in the basket: a receipt's ordinary lines, in capitals
 * as a till prints them (Turkish İ, German SS, accents kept; Arabic has no
 * capitals). Short — a line holds about 18 letters.
 */
export const RECEIPT_ITEMS: readonly Localized[] = [
  { tr: 'ÇİKOLATA', en: 'CHOCOLATE', de: 'SCHOKOLADE', ar: 'شوكولاتة', fr: 'CHOCOLAT', es: 'CHOCOLATE', ja: 'チョコレート', ko: '초콜릿' },
  { tr: 'CİPS', en: 'CHIPS', de: 'CHIPS', ar: 'رقائق بطاطس', fr: 'CHIPS', es: 'PATATAS FRITAS', ja: 'ポテトチップス', ko: '감자칩' },
  { tr: 'EKMEK', en: 'BREAD', de: 'BROT', ar: 'خبز', fr: 'PAIN', es: 'PAN', ja: '食パン', ko: '식빵' },
  { tr: 'SÜT', en: 'MILK', de: 'MILCH', ar: 'حليب', fr: 'LAIT', es: 'LECHE', ja: '牛乳', ko: '우유' },
  { tr: 'YUMURTA', en: 'EGGS', de: 'EIER', ar: 'بيض', fr: 'OEUFS', es: 'HUEVOS', ja: '卵', ko: '달걀' },
  { tr: 'PEYNİR', en: 'CHEESE', de: 'KÄSE', ar: 'جبنة', fr: 'FROMAGE', es: 'QUESO', ja: 'チーズ', ko: '치즈' },
  { tr: 'YOĞURT', en: 'YOGURT', de: 'JOGHURT', ar: 'زبادي', fr: 'YAOURT', es: 'YOGUR', ja: 'ヨーグルト', ko: '요거트' },
  { tr: 'TEREYAĞI', en: 'BUTTER', de: 'BUTTER', ar: 'زبدة', fr: 'BEURRE', es: 'MANTEQUILLA', ja: 'バター', ko: '버터' },
  { tr: 'ÇAY', en: 'TEA', de: 'TEE', ar: 'شاي', fr: 'THÉ', es: 'TÉ', ja: '紅茶', ko: '홍차' },
  {
    tr: 'FİLTRE KAHVE',
    en: 'GROUND COFFEE',
    de: 'KAFFEE GEMAHLEN',
    ar: 'بن مطحون',
    fr: 'CAFÉ MOULU',
    es: 'CAFÉ MOLIDO',
    ja: 'レギュラーコーヒー',
    ko: '분쇄 커피',
  },
  { tr: 'MAKARNA', en: 'PASTA', de: 'NUDELN', ar: 'معكرونة', fr: 'PÂTES', es: 'PASTA', ja: 'パスタ', ko: '파스타' },
  { tr: 'PİRİNÇ', en: 'RICE', de: 'REIS', ar: 'أرز', fr: 'RIZ', es: 'ARROZ', ja: 'お米', ko: '쌀' },
  { tr: 'UN', en: 'FLOUR', de: 'MEHL', ar: 'طحين', fr: 'FARINE', es: 'HARINA', ja: '小麦粉', ko: '밀가루' },
  { tr: 'BAL', en: 'HONEY', de: 'HONIG', ar: 'عسل', fr: 'MIEL', es: 'MIEL', ja: 'はちみつ', ko: '꿀' },
  {
    tr: 'ÇİLEK REÇELİ',
    en: 'STRAWBERRY JAM',
    de: 'ERDBEERMARMELADE',
    ar: 'مربى الفراولة',
    fr: 'CONFITURE FRAISE',
    es: 'MERMELADA DE FRESA',
    ja: 'いちごジャム',
    ko: '딸기잼',
  },
  { tr: 'ZEYTİN', en: 'OLIVES', de: 'OLIVEN', ar: 'زيتون', fr: 'OLIVES', es: 'ACEITUNAS', ja: 'オリーブ', ko: '올리브' },
  { tr: 'DOMATES', en: 'TOMATOES', de: 'TOMATEN', ar: 'طماطم', fr: 'TOMATES', es: 'TOMATES', ja: 'トマト', ko: '토마토' },
  { tr: 'SALATALIK', en: 'CUCUMBERS', de: 'GURKEN', ar: 'خيار', fr: 'CONCOMBRES', es: 'PEPINOS', ja: 'きゅうり', ko: '오이' },
  { tr: 'SOĞAN', en: 'ONIONS', de: 'ZWIEBELN', ar: 'بصل', fr: 'OIGNONS', es: 'CEBOLLAS', ja: '玉ねぎ', ko: '양파' },
  { tr: 'LİMON', en: 'LEMONS', de: 'ZITRONEN', ar: 'ليمون', fr: 'CITRONS', es: 'LIMONES', ja: 'レモン', ko: '레몬' },
  { tr: 'ELMA', en: 'APPLES', de: 'ÄPFEL', ar: 'تفاح', fr: 'POMMES', es: 'MANZANAS', ja: 'りんご', ko: '사과' },
  { tr: 'MUZ', en: 'BANANAS', de: 'BANANEN', ar: 'موز', fr: 'BANANES', es: 'PLÁTANOS', ja: 'バナナ', ko: '바나나' },
  { tr: 'SAKIZ', en: 'GUM', de: 'KAUGUMMI', ar: 'علكة', fr: 'CHEWING-GUM', es: 'CHICLE', ja: 'ガム', ko: '껌' },
  { tr: 'BİSKÜVİ', en: 'COOKIES', de: 'KEKSE', ar: 'بسكويت', fr: 'BISCUITS', es: 'GALLETAS', ja: 'クッキー', ko: '쿠키' },
  {
    tr: 'KRAKER',
    en: 'CRACKERS',
    de: 'SALZCRACKER',
    ar: 'بسكويت مالح',
    fr: 'CRACKERS',
    es: 'GALLETAS SALADAS',
    ja: 'クラッカー',
    ko: '크래커',
  },
  {
    tr: 'AY ÇEKİRDEĞİ',
    en: 'SUNFLOWER SEEDS',
    de: 'SONNENBLUMENKERNE',
    ar: 'بذور عباد الشمس',
    fr: 'GRAINES TOURNESOL',
    es: 'SEMILLAS GIRASOL',
    ja: 'ひまわりの種',
    ko: '해바라기씨',
  },
  { tr: 'DONDURMA', en: 'ICE CREAM', de: 'EISCREME', ar: 'آيس كريم', fr: 'GLACE', es: 'HELADO', ja: 'アイスクリーム', ko: '아이스크림' },
  { tr: 'LİMONATA', en: 'LEMONADE', de: 'LIMONADE', ar: 'عصير ليمون', fr: 'LIMONADE', es: 'LIMONADA', ja: 'レモネード', ko: '레모네이드' },
  {
    tr: 'MADEN SUYU',
    en: 'SPARKLING WATER',
    de: 'MINERALWASSER',
    ar: 'مياه معدنية',
    fr: 'EAU GAZEUSE',
    es: 'AGUA MINERAL',
    ja: '炭酸水',
    ko: '탄산수',
  },
  {
    tr: 'ALÜMİNYUM FOLYO',
    en: 'ALUMINUM FOIL',
    de: 'ALUFOLIE',
    ar: 'ورق ألمنيوم',
    fr: 'PAPIER ALU',
    es: 'PAPEL DE ALUMINIO',
    ja: 'アルミホイル',
    ko: '쿠킹포일',
  },
  {
    tr: 'PEÇETE',
    en: 'NAPKINS',
    de: 'SERVIETTEN',
    ar: 'مناديل مائدة',
    fr: 'SERVIETTES PAPIER',
    es: 'SERVILLETAS',
    ja: '紙ナプキン',
    ko: '냅킨',
  },
  {
    tr: 'ISLAK MENDİL',
    en: 'WET WIPES',
    de: 'FEUCHTTÜCHER',
    ar: 'مناديل مبللة',
    fr: 'LINGETTES',
    es: 'TOALLITAS HÚMEDAS',
    ja: 'ウェットティッシュ',
    ko: '물티슈',
  },
  {
    tr: 'KAĞIT HAVLU',
    en: 'PAPER TOWELS',
    de: 'KÜCHENROLLE',
    ar: 'مناديل مطبخ',
    fr: 'ESSUIE-TOUT',
    es: 'PAPEL DE COCINA',
    ja: 'キッチンペーパー',
    ko: '키친타월',
  },
  {
    tr: 'TUVALET KAĞIDI',
    en: 'TOILET PAPER',
    de: 'TOILETTENPAPIER',
    ar: 'ورق تواليت',
    fr: 'PAPIER TOILETTE',
    es: 'PAPEL HIGIÉNICO',
    ja: 'トイレットペーパー',
    ko: '화장지',
  },
  {
    tr: 'BULAŞIK DETERJANI',
    en: 'DISH SOAP',
    de: 'SPÜLMITTEL',
    ar: 'سائل غسيل الصحون',
    fr: 'LIQUIDE VAISSELLE',
    es: 'JABÓN PARA PLATOS',
    ja: '食器用洗剤',
    ko: '주방세제',
  },
  { tr: 'SÜNGER', en: 'SPONGES', de: 'SCHWÄMME', ar: 'إسفنج', fr: 'ÉPONGES', es: 'ESPONJAS', ja: 'スポンジ', ko: '수세미' },
  {
    tr: 'DİŞ MACUNU',
    en: 'TOOTHPASTE',
    de: 'ZAHNPASTA',
    ar: 'معجون أسنان',
    fr: 'DENTIFRICE',
    es: 'PASTA DE DIENTES',
    ja: '歯みがき粉',
    ko: '치약',
  },
  {
    tr: 'KOKULU MUM',
    en: 'SCENTED CANDLE',
    de: 'DUFTKERZE',
    ar: 'شمعة معطرة',
    fr: 'BOUGIE PARFUMÉE',
    es: 'VELA AROMÁTICA',
    ja: 'アロマキャンドル',
    ko: '향초',
  },
  {
    tr: 'KEDİ MAMASI',
    en: 'CAT FOOD',
    de: 'KATZENFUTTER',
    ar: 'طعام قطط',
    fr: 'CROQUETTES CHAT',
    es: 'COMIDA PARA GATO',
    ja: 'キャットフード',
    ko: '고양이 사료',
  },
  {
    tr: 'DOĞUM GÜNÜ BALONU',
    en: 'BIRTHDAY BALLOON',
    de: 'GEBURTSTAGSBALLON',
    ar: 'بالون عيد ميلاد',
    fr: "BALLON D'ANNIV",
    es: 'GLOBO CUMPLEAÑOS',
    ja: '誕生日の風船',
    ko: '생일 풍선',
  },
  { tr: 'PORTAKAL', en: 'ORANGES', de: 'ORANGEN', ar: 'برتقال', fr: 'ORANGES', es: 'NARANJAS', ja: 'オレンジ', ko: '오렌지' },
  { tr: 'HAVUÇ', en: 'CARROTS', de: 'KAROTTEN', ar: 'جزر', fr: 'CAROTTES', es: 'ZANAHORIAS', ja: 'にんじん', ko: '당근' },
  { tr: 'MARUL', en: 'LETTUCE', de: 'KOPFSALAT', ar: 'خس', fr: 'LAITUE', es: 'LECHUGA', ja: 'レタス', ko: '양상추' },
  { tr: 'MERCİMEK', en: 'LENTILS', de: 'LINSEN', ar: 'عدس', fr: 'LENTILLES', es: 'LENTEJAS', ja: 'レンズ豆', ko: '렌틸콩' },
  { tr: 'NOHUT', en: 'CHICKPEAS', de: 'KICHERERBSEN', ar: 'حمص', fr: 'POIS CHICHES', es: 'GARBANZOS', ja: 'ひよこ豆', ko: '병아리콩' },
  { tr: 'ŞEKER', en: 'SUGAR', de: 'ZUCKER', ar: 'سكر', fr: 'SUCRE', es: 'AZÚCAR', ja: '砂糖', ko: '설탕' },
  { tr: 'TUZ', en: 'SALT', de: 'SALZ', ar: 'ملح', fr: 'SEL', es: 'SAL', ja: '塩', ko: '소금' },
  { tr: 'KARABİBER', en: 'BLACK PEPPER', de: 'SCHWARZER PFEFFER', ar: 'فلفل أسود', fr: 'POIVRE NOIR', es: 'PIMIENTA NEGRA', ja: '黒こしょう', ko: '후추' },
  { tr: 'ZEYTİNYAĞI', en: 'OLIVE OIL', de: 'OLIVENÖL', ar: 'زيت زيتون', fr: "HUILE D'OLIVE", es: 'ACEITE DE OLIVA', ja: 'オリーブオイル', ko: '올리브유' },
  { tr: 'MISIR GEVREĞİ', en: 'CEREAL', de: 'FRÜHSTÜCKSFLOCKEN', ar: 'رقائق الذرة', fr: 'CÉRÉALES', es: 'CEREALES', ja: 'シリアル', ko: '시리얼' },
  { tr: 'YULAF EZMESİ', en: 'OATMEAL', de: 'HAFERFLOCKEN', ar: 'شوفان', fr: "FLOCONS D'AVOINE", es: 'AVENA', ja: 'オートミール', ko: '오트밀' },
  { tr: 'KURU ÜZÜM', en: 'RAISINS', de: 'ROSINEN', ar: 'زبيب', fr: 'RAISINS SECS', es: 'PASAS', ja: 'レーズン', ko: '건포도' },
  { tr: 'FINDIK', en: 'HAZELNUTS', de: 'HASELNÜSSE', ar: 'بندق', fr: 'NOISETTES', es: 'AVELLANAS', ja: 'ヘーゼルナッツ', ko: '헤이즐넛' },
  { tr: 'CEVİZ', en: 'WALNUTS', de: 'WALNÜSSE', ar: 'جوز', fr: 'NOIX', es: 'NUECES', ja: 'くるみ', ko: '호두' },
  { tr: 'KEK', en: 'SNACK CAKE', de: 'RÜHRKUCHEN', ar: 'كعكة', fr: 'GÂTEAU', es: 'BIZCOCHO', ja: 'パウンドケーキ', ko: '카스텔라' },
  { tr: 'KARPUZ', en: 'WATERMELON', de: 'WASSERMELONE', ar: 'بطيخ', fr: 'PASTÈQUE', es: 'SANDÍA', ja: 'スイカ', ko: '수박' },
  { tr: 'ARMUT', en: 'PEARS', de: 'BIRNEN', ar: 'كمثرى', fr: 'POIRES', es: 'PERAS', ja: '梨', ko: '배' },
  { tr: 'KİVİ', en: 'KIWIS', de: 'KIWIS', ar: 'كيوي', fr: 'KIWIS', es: 'KIWIS', ja: 'キウイ', ko: '키위' },
  { tr: 'MANTAR', en: 'MUSHROOMS', de: 'PILZE', ar: 'فطر', fr: 'CHAMPIGNONS', es: 'CHAMPIÑONES', ja: 'きのこ', ko: '버섯' },
  { tr: 'BİBER', en: 'BELL PEPPERS', de: 'PAPRIKA', ar: 'فلفل رومي', fr: 'POIVRONS', es: 'PIMIENTOS', ja: 'ピーマン', ko: '파프리카' },
  { tr: 'KİRAZ', en: 'CHERRIES', de: 'KIRSCHEN', ar: 'كرز', fr: 'CERISES', es: 'CEREZAS', ja: 'さくらんぼ', ko: '체리' },
  { tr: 'ŞAMPUAN', en: 'SHAMPOO', de: 'SHAMPOO', ar: 'شامبو', fr: 'SHAMPOING', es: 'CHAMPÚ', ja: 'シャンプー', ko: '샴푸' },
  { tr: 'SABUN', en: 'SOAP', de: 'SEIFE', ar: 'صابون', fr: 'SAVON', es: 'JABÓN', ja: 'せっけん', ko: '비누' },
  { tr: 'DİŞ FIRÇASI', en: 'TOOTHBRUSH', de: 'ZAHNBÜRSTE', ar: 'فرشاة أسنان', fr: 'BROSSE À DENTS', es: 'CEPILLO DE DIENTES', ja: '歯ブラシ', ko: '칫솔' },
  { tr: 'ÇAMAŞIR DETERJANI', en: 'LAUNDRY DETERGENT', de: 'WASCHMITTEL', ar: 'مسحوق غسيل', fr: 'LESSIVE', es: 'DETERGENTE', ja: '洗濯洗剤', ko: '세탁세제' },
  { tr: 'ÇÖP TORBASI', en: 'TRASH BAGS', de: 'MÜLLBEUTEL', ar: 'أكياس قمامة', fr: 'SACS POUBELLE', es: 'BOLSAS DE BASURA', ja: 'ゴミ袋', ko: '쓰레기봉투' },
  { tr: 'BANT', en: 'TAPE', de: 'KLEBEBAND', ar: 'شريط لاصق', fr: 'RUBAN ADHÉSIF', es: 'CINTA ADHESIVA', ja: 'セロハンテープ', ko: '테이프' },
  { tr: 'DEFTER', en: 'NOTEBOOK', de: 'NOTIZBUCH', ar: 'دفتر', fr: 'CAHIER', es: 'CUADERNO', ja: 'ノート', ko: '공책' },
  { tr: 'HAZIR ÇORBA', en: 'INSTANT SOUP', de: 'TÜTENSUPPE', ar: 'حساء سريع', fr: 'SOUPE INSTANTANÉE', es: 'SOPA INSTANTÁNEA', ja: 'インスタントスープ', ko: '즉석 수프' },
  { tr: 'PUDİNG', en: 'PUDDING CUPS', de: 'PUDDING', ar: 'مهلبية', fr: 'CRÈME DESSERT', es: 'PUDÍN', ja: 'プリン', ko: '푸딩' },
];

/**
 * The ordinary notifications of a lock screen, under the post's own
 * punchline: an app or a person, and one line. Nothing alarming, nothing
 * about the player's real phone — just the everyday pile.
 */
export const NOTICES: readonly Notice[] = [
  {
    icon: '🔋',
    app: { tr: 'Pil', en: 'Battery', de: 'Akku', ar: 'البطارية', fr: 'Batterie', es: 'Batería', ja: 'バッテリー', ko: '배터리' },
    text: {
      tr: '%3 kaldı',
      en: '3% left',
      de: 'Noch 3 %',
      ar: 'متبقٍ 3%',
      fr: 'Plus que 3 %',
      es: 'Queda un 3 %',
      ja: '残り3%',
      ko: '3% 남음',
    },
  },
  {
    icon: '☀️',
    app: {
      tr: 'Hava durumu',
      en: 'Weather',
      de: 'Wetter',
      ar: 'الطقس',
      fr: 'Météo',
      es: 'Pronóstico',
      ja: '天気',
      ko: '날씨',
    },
    text: {
      tr: 'Bugün güneşli, en yüksek 24°',
      en: 'Sunny today, high of 75°',
      de: 'Heute sonnig, bis zu 24°',
      ar: 'مشمس اليوم، والعظمى 24°',
      fr: "Soleil aujourd'hui, jusqu'à 24°",
      es: 'Soleado hoy, máxima de 24°',
      ja: '今日は晴れ、最高気温24°',
      ko: '오늘은 맑음, 최고 기온 24°',
    },
  },
  {
    icon: '📅',
    app: {
      tr: 'Takvim',
      en: 'Calendar',
      de: 'Kalender',
      ar: 'التقويم',
      fr: 'Agenda',
      es: 'Calendario',
      ja: 'カレンダー',
      ko: '캘린더',
    },
    text: {
      tr: 'Yarın 10.00 · Kuaför',
      en: 'Tomorrow 10 AM · Haircut',
      de: 'Morgen 10:00 · Friseur',
      ar: 'غدًا 10:00 · موعد الحلاق',
      fr: 'Demain 10 h · Coiffeur',
      es: 'Mañana 10:00 · Peluquería',
      ja: '明日10:00・美容院',
      ko: '내일 10:00 · 미용실',
    },
  },
  {
    icon: '📦',
    app: {
      tr: 'Kargo',
      en: 'Deliveries',
      de: 'Paketdienst',
      ar: 'الشحن',
      fr: 'Colis',
      es: 'Envíos',
      ja: '宅配便',
      ko: '택배',
    },
    text: {
      tr: 'Paketin yola çıktı, yarın kapında',
      en: 'Your package is on its way',
      de: 'Dein Paket ist unterwegs',
      ar: 'طردك في الطريق إليك',
      fr: 'Ton colis est en route',
      es: 'Tu paquete va en camino',
      ja: '荷物を発送しました。明日お届け予定',
      ko: '택배가 출발했어요. 내일 도착 예정',
    },
  },
  {
    icon: '⏰',
    app: { tr: 'Alarm', en: 'Alarm', de: 'Wecker', ar: 'المنبه', fr: 'Réveil', es: 'Alarma', ja: 'アラーム', ko: '알람' },
    text: {
      tr: 'Günaydın! Saat 07.30',
      en: "Good morning! It's 7:30",
      de: 'Guten Morgen! Es ist 7:30',
      ar: 'صباح الخير! الساعة 7:30',
      fr: 'Bonjour ! Il est 7 h 30',
      es: '¡Buenos días! Son las 7:30',
      ja: 'おはよう！7:30です',
      ko: '좋은 아침이에요! 7:30이에요',
    },
  },
  {
    icon: '🖼️',
    app: { tr: 'Fotoğraflar', en: 'Photos', de: 'Fotos', ar: 'الصور', fr: 'Photos', es: 'Fotos', ja: '写真', ko: '사진' },
    text: {
      tr: 'Anılar: 3 yıl önce bugün',
      en: 'Memories: 3 years ago today',
      de: 'Erinnerungen: heute vor 3 Jahren',
      ar: 'ذكريات: في مثل هذا اليوم قبل 3 سنوات',
      fr: 'Souvenirs : il y a 3 ans jour pour jour',
      es: 'Recuerdos: hace 3 años, un día como hoy',
      ja: '思い出：3年前の今日',
      ko: '추억: 3년 전 오늘',
    },
  },
  {
    icon: '👣',
    app: {
      tr: 'Adım sayar',
      en: 'Step counter',
      de: 'Schrittzähler',
      ar: 'عداد الخطوات',
      fr: 'Podomètre',
      es: 'Podómetro',
      ja: '歩数計',
      ko: '만보기',
    },
    text: {
      tr: 'Günlük hedefinin yarısındasın!',
      en: "You're halfway to your daily goal!",
      de: 'Halbes Tagesziel geschafft!',
      ar: 'وصلت إلى نصف هدفك اليومي!',
      fr: 'Tu es à mi-chemin de ton objectif !',
      es: '¡Vas a la mitad de tu meta diaria!',
      ja: '今日の目標まであと半分！',
      ko: '오늘 목표의 절반을 달성했어요!',
    },
  },
  {
    icon: '💾',
    app: {
      tr: 'Ayarlar',
      en: 'Settings',
      de: 'Einstellungen',
      ar: 'الإعدادات',
      fr: 'Réglages',
      es: 'Ajustes',
      ja: '設定',
      ko: '설정',
    },
    text: {
      tr: 'Depolama alanı neredeyse dolu',
      en: 'Storage almost full',
      de: 'Speicher fast voll',
      ar: 'مساحة التخزين شبه ممتلئة',
      fr: 'Stockage presque plein',
      es: 'Almacenamiento casi lleno',
      ja: 'ストレージがほぼいっぱいです',
      ko: '저장 공간이 거의 가득 찼어요',
    },
  },
  {
    icon: '⚙️',
    app: {
      tr: 'Güncelleme',
      en: 'Software update',
      de: 'Softwareupdate',
      ar: 'تحديث النظام',
      fr: 'Mise à jour',
      es: 'Actualización',
      ja: 'ソフトウェア更新',
      ko: '시스템 업데이트',
    },
    text: {
      tr: 'Bu gece otomatik yüklenecek',
      en: 'Will install automatically tonight',
      de: 'Wird heute Nacht automatisch installiert',
      ar: 'سيُثبَّت تلقائيًا الليلة',
      fr: 'Installation automatique cette nuit',
      es: 'Se instalará sola esta noche',
      ja: '今夜、自動でインストールされます',
      ko: '오늘 밤 자동으로 설치돼요',
    },
  },
  {
    icon: '🎙️',
    app: {
      tr: 'Podcast',
      en: 'Podcasts',
      de: 'Podcasts',
      ar: 'بودكاست',
      fr: 'Podcasts',
      es: 'Podcasts',
      ja: 'ポッドキャスト',
      ko: '팟캐스트',
    },
    text: {
      tr: 'Kaldığın yerden devam edelim mi?',
      en: 'Pick up where you left off?',
      de: 'Weiterhören, wo du aufgehört hast?',
      ar: 'هل تتابع من حيث توقفت؟',
      fr: "Reprendre là où tu t'es arrêté ?",
      es: '¿Seguir donde te quedaste?',
      ja: '続きから再生しますか？',
      ko: '이어서 들을까요?',
    },
  },
  {
    icon: '💧',
    app: {
      tr: 'Su takibi',
      en: 'Water tracker',
      de: 'Trink-Erinnerung',
      ar: 'تذكير الماء',
      fr: 'Hydratation',
      es: 'Hidratación',
      ja: '水分補給',
      ko: '물 마시기',
    },
    text: {
      tr: 'Bir bardak su içme vakti',
      en: 'Time for a glass of water',
      de: 'Zeit für ein Glas Wasser',
      ar: 'حان وقت شرب كوب ماء',
      fr: "C'est l'heure d'un verre d'eau",
      es: 'Hora de tomar un vaso de agua',
      ja: 'コップ1杯の水を飲む時間です',
      ko: '물 한 잔 마실 시간이에요',
    },
  },
  {
    icon: '💬',
    app: {
      tr: 'Kanka',
      en: 'Bestie',
      de: 'Bester Kumpel',
      ar: 'صديقي',
      fr: 'Mon pote',
      es: 'Mi mejor amigo',
      ja: '親友',
      ko: '절친',
    },
    text: { tr: '😂😂', en: '😂😂', de: '😂😂', ar: '😂😂', fr: '😂😂', es: '😂😂', ja: '😂😂', ko: '😂😂' },
  },
  {
    icon: '👪',
    app: {
      tr: 'Aile grubu',
      en: 'Family group',
      de: 'Familiengruppe',
      ar: 'مجموعة العائلة',
      fr: 'Groupe famille',
      es: 'Grupo familiar',
      ja: '家族グループ',
      ko: '가족 단톡방',
    },
    text: {
      tr: '12 yeni mesaj',
      en: '12 new messages',
      de: '12 neue Nachrichten',
      ar: '12 رسالة جديدة',
      fr: '12 nouveaux messages',
      es: '12 mensajes nuevos',
      ja: '新着メッセージ12件',
      ko: '새 메시지 12개',
    },
  },
  {
    icon: '🎂',
    app: {
      tr: 'Doğum günleri',
      en: 'Birthdays',
      de: 'Geburtstage',
      ar: 'أعياد الميلاد',
      fr: 'Anniversaires',
      es: 'Cumpleaños',
      ja: '誕生日',
      ko: '생일',
    },
    text: {
      tr: 'Yarın bir arkadaşının doğum günü',
      en: "A friend's birthday is tomorrow",
      de: 'Morgen hat ein Freund Geburtstag',
      ar: 'غدًا عيد ميلاد أحد أصدقائك',
      fr: "Demain, c'est l'anniv d'un ami",
      es: 'Mañana cumple años un amigo',
      ja: '明日は友だちの誕生日です',
      ko: '내일은 친구 생일이에요',
    },
  },
  {
    icon: '🌙',
    app: { tr: 'Uyku', en: 'Sleep', de: 'Schlaf', ar: 'النوم', fr: 'Sommeil', es: 'Sueño', ja: '睡眠', ko: '수면' },
    text: {
      tr: 'Yatma saatine 30 dakika var',
      en: 'Bedtime in 30 minutes',
      de: 'In 30 Minuten ist Schlafenszeit',
      ar: 'بقيت 30 دقيقة على موعد النوم',
      fr: 'Au lit dans 30 minutes',
      es: 'Faltan 30 minutos para dormir',
      ja: '就寝時刻まであと30分',
      ko: '취침 시간까지 30분 남았어요',
    },
  },
  {
    icon: '🎵',
    app: { tr: 'Müzik', en: 'Music', de: 'Musik', ar: 'الموسيقى', fr: 'Musique', es: 'Música', ja: 'ミュージック', ko: '음악' },
    text: {
      tr: 'Haftalık karışık listen hazır',
      en: 'Your weekly mix is ready',
      de: 'Dein Wochenmix ist da',
      ar: 'قائمة أغانيك الأسبوعية جاهزة',
      fr: 'Ton mix de la semaine est prêt',
      es: 'Tu mix semanal está listo',
      ja: '今週のミックスができました',
      ko: '이번 주 믹스가 준비됐어요',
    },
  },
  {
    icon: '📝',
    app: {
      tr: 'Alışveriş listesi',
      en: 'Shopping list',
      de: 'Einkaufsliste',
      ar: 'قائمة المشتريات',
      fr: 'Liste de courses',
      es: 'Lista de compras',
      ja: '買い物リスト',
      ko: '장보기 목록',
    },
    text: {
      tr: 'Domates, peynir, deterjan',
      en: 'Tomatoes, cheese, dish soap',
      de: 'Tomaten, Käse, Spülmittel',
      ar: 'طماطم، جبن، سائل جلي',
      fr: 'Tomates, fromage, liquide vaisselle',
      es: 'Tomates, queso y detergente',
      ja: 'トマト、チーズ、食器用洗剤',
      ko: '토마토, 치즈, 주방세제',
    },
  },
  {
    icon: '🧺',
    app: {
      tr: 'Çamaşır makinesi',
      en: 'Washer',
      de: 'Waschmaschine',
      ar: 'الغسالة',
      fr: 'Lave-linge',
      es: 'Lavadora',
      ja: '洗濯機',
      ko: '세탁기',
    },
    text: {
      tr: 'Yıkama bitti, asmayı unutma',
      en: "Laundry's done!",
      de: 'Die Wäsche ist fertig',
      ar: 'انتهى الغسيل، لا تنسَ نشره',
      fr: "Lessive terminée, pense à l'étendre",
      es: 'Terminó el lavado',
      ja: '洗濯が終わりました。干すのを忘れずに',
      ko: '세탁이 끝났어요. 잊지 말고 널어 주세요',
    },
  },
  {
    icon: '🚏',
    app: {
      tr: 'Toplu taşıma',
      en: 'Transit',
      de: 'Nahverkehr',
      ar: 'النقل العام',
      fr: 'Transports',
      es: 'Transporte',
      ja: '交通情報',
      ko: '대중교통',
    },
    text: {
      tr: 'Otobüsün 4 dakika sonra durakta',
      en: 'Your bus arrives in 4 min',
      de: 'Dein Bus kommt in 4 Min.',
      ar: 'حافلتك تصل بعد 4 دقائق',
      fr: 'Ton bus arrive dans 4 min',
      es: 'Tu bus llega en 4 min',
      ja: 'バスがあと4分で到着します',
      ko: '버스가 4분 후에 도착해요',
    },
  },
  {
    icon: '📚',
    app: {
      tr: 'Kütüphane',
      en: 'Library',
      de: 'Bibliothek',
      ar: 'المكتبة',
      fr: 'Bibliothèque',
      es: 'Biblioteca',
      ja: '図書館',
      ko: '도서관',
    },
    text: {
      tr: 'Kitabının iade tarihi yarın',
      en: 'Your book is due back tomorrow',
      de: 'Dein Buch muss morgen zurück',
      ar: 'موعد إعادة كتابك غدًا',
      fr: 'Ton livre est à rendre demain',
      es: 'Mañana vence el préstamo de tu libro',
      ja: '本の返却期限は明日です',
      ko: '책 반납일이 내일이에요',
    },
  },
  {
    icon: '🥡',
    app: {
      tr: 'Yemek siparişi',
      en: 'Food delivery',
      de: 'Essenslieferung',
      ar: 'توصيل الطعام',
      fr: 'Livraison repas',
      es: 'Comida a domicilio',
      ja: 'フードデリバリー',
      ko: '음식 배달',
    },
    text: {
      tr: 'Siparişin hazırlanıyor',
      en: 'Your order is being prepared',
      de: 'Deine Bestellung wird zubereitet',
      ar: 'طلبك قيد التحضير',
      fr: 'Ta commande est en préparation',
      es: 'Tu pedido se está preparando',
      ja: 'ご注文の料理を準備中です',
      ko: '주문하신 음식을 준비 중이에요',
    },
  },
  {
    icon: '🌷',
    app: { tr: 'Annem', en: 'Mom', de: 'Mama', ar: 'أمي', fr: 'Maman', es: 'Mamá', ja: 'お母さん', ko: '엄마' },
    text: {
      tr: 'Akşam yemeğe gelir misin?',
      en: 'Coming over for dinner tonight?',
      de: 'Kommst du heute zum Abendessen?',
      ar: 'هل ستأتي على العشاء الليلة؟',
      fr: 'Tu viens dîner ce soir ?',
      es: '¿Vienes a cenar esta noche?',
      ja: '今夜ごはん食べに来る？',
      ko: '오늘 저녁 먹으러 올래?',
    },
  },
  {
    icon: '🧘',
    app: {
      tr: 'Mola',
      en: 'Mindfulness',
      de: 'Achtsamkeit',
      ar: 'استراحة',
      fr: 'Pause',
      es: 'Pausa',
      ja: 'マインドフルネス',
      ko: '마음챙김',
    },
    text: {
      tr: '1 dakikalık nefes molasına ne dersin?',
      en: 'How about a 1-minute breather?',
      de: "Wie wär's mit einer Atempause?",
      ar: 'ما رأيك في استراحة تنفّس لدقيقة؟',
      fr: "Une pause respiration d'une minute ?",
      es: '¿Una pausa de un minuto para respirar?',
      ja: '1分だけ深呼吸しませんか？',
      ko: '1분 호흡 휴식 어때요?',
    },
  },
  {
    icon: '✉️',
    app: { tr: 'E-posta', en: 'Mail', de: 'E-Mail', ar: 'البريد', fr: 'E-mail', es: 'Correo', ja: 'メール', ko: '메일' },
    text: {
      tr: '3 yeni e-posta',
      en: '3 new emails',
      de: '3 neue E-Mails',
      ar: '3 رسائل بريد جديدة',
      fr: '3 nouveaux e-mails',
      es: '3 correos nuevos',
      ja: '新着メール3件',
      ko: '새 메일 3개',
    },
  },
  {
    icon: '🌱',
    app: {
      tr: 'Bitki bakımı',
      en: 'Plant care',
      de: 'Pflanzenpflege',
      ar: 'رعاية النباتات',
      fr: 'Mes plantes',
      es: 'Mis plantas',
      ja: '植物のお世話',
      ko: '식물 관리',
    },
    text: {
      tr: 'Bitkileri sulama günü',
      en: 'Time to water your plants',
      de: 'Zeit, die Pflanzen zu gießen',
      ar: 'حان وقت سقي النباتات',
      fr: "C'est le jour d'arroser les plantes",
      es: 'Hora de regar las plantas',
      ja: '植物に水をあげる日です',
      ko: '식물에 물 주는 날이에요',
    },
  },
  {
    icon: '💪',
    app: { tr: 'Spor', en: 'Fitness', de: 'Fitness', ar: 'اللياقة', fr: 'Sport', es: 'Ejercicio', ja: 'フィットネス', ko: '운동' },
    text: {
      tr: 'Bu hafta 2 antrenman, süpersin!',
      en: '2 workouts this week, nice work!',
      de: '2 Workouts diese Woche, stark!',
      ar: 'تمرينان هذا الأسبوع، أحسنت!',
      fr: '2 séances cette semaine, bravo !',
      es: '¡Bien! 2 entrenamientos esta semana',
      ja: '今週はトレーニング2回、すごい！',
      ko: '이번 주 운동 2회, 최고예요!',
    },
  },
  {
    icon: '🚪',
    app: {
      tr: 'Komşu',
      en: 'Neighbor',
      de: 'Nachbarin',
      ar: 'الجارة',
      fr: 'Voisine',
      es: 'Vecina',
      ja: 'お隣さん',
      ko: '이웃',
    },
    text: {
      tr: 'Kargonu ben teslim aldım',
      en: 'I picked up your package for you',
      de: 'Hab dein Paket angenommen',
      ar: 'استلمتُ طردك نيابةً عنك',
      fr: "J'ai récupéré ton colis",
      es: 'Recibí tu paquete, lo tengo yo',
      ja: '荷物、代わりに受け取っておいたよ',
      ko: '택배 제가 대신 받아 뒀어요',
    },
  },
  {
    icon: '📺',
    app: {
      tr: 'Diziler',
      en: 'TV shows',
      de: 'Serien',
      ar: 'المسلسلات',
      fr: 'Séries',
      es: 'Series',
      ja: 'ドラマ',
      ko: '드라마',
    },
    text: {
      tr: 'Yeni bölüm yayında!',
      en: 'New episode out now!',
      de: 'Neue Folge ist online!',
      ar: 'حلقة جديدة متاحة الآن!',
      fr: 'Nouvel épisode dispo !',
      es: '¡Ya salió el nuevo episodio!',
      ja: '最新話が配信されました！',
      ko: '새 에피소드가 공개됐어요!',
    },
  },
  {
    icon: '🗺️',
    app: {
      tr: 'Navigasyon',
      en: 'Navigation',
      de: 'Navi',
      ar: 'الملاحة',
      fr: 'Itinéraire',
      es: 'Navegación',
      ja: 'ナビ',
      ko: '내비게이션',
    },
    text: {
      tr: 'Eve 12 dakika, yollar açık',
      en: '12 min to home, roads are clear',
      de: '12 Min. bis nach Hause, freie Fahrt',
      ar: '12 دقيقة إلى المنزل، الطريق سالك',
      fr: 'Maison à 12 min, ça roule',
      es: '12 min a casa, tráfico fluido',
      ja: '自宅まで12分、道路は空いています',
      ko: '집까지 12분, 교통 원활',
    },
  },
  {
    icon: '❤️',
    app: {
      tr: 'Sosyal medya',
      en: 'Social media',
      de: 'Social Media',
      ar: 'التواصل الاجتماعي',
      fr: 'Réseaux sociaux',
      es: 'Redes sociales',
      ja: 'SNS',
      ko: 'SNS',
    },
    text: {
      tr: '3 arkadaşın yeni gönderi paylaştı',
      en: '3 friends shared new posts',
      de: '3 Freunde haben was Neues gepostet',
      ar: '3 من أصدقائك نشروا منشورات جديدة',
      fr: '3 amis ont publié de nouveaux posts',
      es: '3 amigos publicaron algo nuevo',
      ja: '友だち3人が新しく投稿しました',
      ko: '친구 3명이 새 게시물을 올렸어요',
    },
  },
  {
    icon: '✈️',
    app: {
      tr: 'Geri sayım',
      en: 'Countdown',
      de: 'Countdown',
      ar: 'العد التنازلي',
      fr: 'Compte à rebours',
      es: 'Cuenta regresiva',
      ja: 'カウントダウン',
      ko: '카운트다운',
    },
    text: {
      tr: 'Tatile 23 gün kaldı!',
      en: '23 days until vacation!',
      de: 'Noch 23 Tage bis zum Urlaub!',
      ar: 'بقي 23 يومًا على الإجازة!',
      fr: 'Plus que 23 jours avant les vacances !',
      es: '¡Faltan 23 días para las vacaciones!',
      ja: '休みまであと23日！',
      ko: '휴가까지 23일 남았어요!',
    },
  },
  {
    icon: '🐾',
    app: {
      tr: 'Evcil hayvan',
      en: 'Pet care',
      de: 'Haustier',
      ar: 'الحيوان الأليف',
      fr: 'Mon animal',
      es: 'Mascota',
      ja: 'ペットケア',
      ko: '반려동물',
    },
    text: {
      tr: 'Kedinin mama saati geldi',
      en: 'Time to feed the cat',
      de: 'Zeit, die Katze zu füttern',
      ar: 'حان موعد إطعام القطة',
      fr: "C'est l'heure de nourrir le chat",
      es: 'Hora de darle de comer al gato',
      ja: '猫のごはんの時間です',
      ko: '고양이 밥 줄 시간이에요',
    },
  },
  {
    icon: '🧹',
    app: {
      tr: 'Robot süpürge',
      en: 'Robot vacuum',
      de: 'Saugroboter',
      ar: 'المكنسة الذكية',
      fr: 'Robot aspirateur',
      es: 'Robot aspiradora',
      ja: 'ロボット掃除機',
      ko: '로봇청소기',
    },
    text: {
      tr: 'Salon temizliği tamamlandı',
      en: 'Living room cleaned',
      de: 'Wohnzimmer ist sauber',
      ar: 'اكتمل تنظيف غرفة المعيشة',
      fr: 'Salon nettoyé',
      es: 'Limpieza de la sala terminada',
      ja: 'リビングの掃除が完了しました',
      ko: '거실 청소를 마쳤어요',
    },
  },
  {
    icon: '🥕',
    app: {
      tr: 'Tarifler',
      en: 'Recipes',
      de: 'Rezepte',
      ar: 'وصفات',
      fr: 'Recettes',
      es: 'Recetas',
      ja: 'レシピ',
      ko: '레시피',
    },
    text: {
      tr: 'Günün tarifi: Fırında sebze',
      en: 'Recipe of the day: roasted veggies',
      de: 'Rezept des Tages: Ofengemüse',
      ar: 'وصفة اليوم: خضار في الفرن',
      fr: 'Recette du jour : légumes rôtis',
      es: 'Receta del día: verduras al horno',
      ja: '今日のレシピ：焼き野菜',
      ko: '오늘의 레시피: 구운 채소',
    },
  },
  {
    icon: '🏖️',
    app: { tr: 'Kuzenim', en: 'Cousin', de: 'Cousine', ar: 'ابنة عمي', fr: 'Cousine', es: 'Prima', ja: 'いとこ', ko: '사촌' },
    text: {
      tr: 'Tatil fotoğraflarını attım',
      en: 'Sent you the vacation pics',
      de: 'Hab dir die Urlaubsfotos geschickt',
      ar: 'أرسلت لك صور الإجازة',
      fr: "Je t'ai envoyé les photos de vacances",
      es: 'Te mandé las fotos del viaje',
      ja: '旅行の写真、送ったよ',
      ko: '휴가 사진 보냈어',
    },
  },
  {
    icon: '🗑️',
    app: {
      tr: 'Hatırlatıcı',
      en: 'Reminders',
      de: 'Erinnerungen',
      ar: 'التذكيرات',
      fr: 'Rappels',
      es: 'Recordatorios',
      ja: 'リマインダー',
      ko: '미리 알림',
    },
    text: {
      tr: 'Çöpü çıkarmayı unutma',
      en: "Don't forget to take out the trash",
      de: 'Müll rausbringen nicht vergessen',
      ar: 'لا تنسَ إخراج القمامة',
      fr: 'Pense à sortir les poubelles',
      es: 'No olvides sacar la basura',
      ja: 'ゴミ出しを忘れずに',
      ko: '쓰레기 버리는 거 잊지 마세요',
    },
  },
  {
    icon: '🎧',
    app: {
      tr: 'Kulaklık',
      en: 'Earbuds',
      de: 'Kopfhörer',
      ar: 'السماعات',
      fr: 'Écouteurs',
      es: 'Auriculares',
      ja: 'イヤホン',
      ko: '이어폰',
    },
    text: {
      tr: 'Kulaklık bağlandı',
      en: 'Earbuds connected',
      de: 'Kopfhörer verbunden',
      ar: 'تم توصيل السماعات',
      fr: 'Écouteurs connectés',
      es: 'Auriculares conectados',
      ja: 'イヤホンが接続されました',
      ko: '이어폰이 연결됐어요',
    },
  },
  {
    icon: '☕️',
    app: { tr: 'Kafe', en: 'Coffee shop', de: 'Café', ar: 'المقهى', fr: 'Café', es: 'Cafetería', ja: 'カフェ', ko: '카페' },
    text: {
      tr: 'Kahven hazır, tezgâhta seni bekliyor',
      en: 'Your coffee is ready at the counter',
      de: 'Dein Kaffee wartet an der Theke',
      ar: 'قهوتك جاهزة عند المنضدة',
      fr: "Ton café t'attend au comptoir",
      es: 'Tu café está listo en la barra',
      ja: 'コーヒーができました。カウンターへどうぞ',
      ko: '커피가 나왔어요. 카운터로 와 주세요',
    },
  },
  {
    icon: '🍿',
    app: { tr: 'Sinema', en: 'Movies', de: 'Kino', ar: 'السينما', fr: 'Cinéma', es: 'Cine', ja: '映画', ko: '영화' },
    text: {
      tr: 'Biletin hazır: Salon 3, koltuk 7',
      en: 'Your ticket: Theater 3, seat 7',
      de: 'Dein Ticket: Saal 3, Platz 7',
      ar: 'تذكرتك جاهزة: القاعة 3، المقعد 7',
      fr: 'Ton billet : salle 3, siège 7',
      es: 'Tu entrada: sala 3, asiento 7',
      ja: 'チケット：スクリーン3、7番席',
      ko: '티켓: 3관, 7번 좌석',
    },
  },
  {
    icon: '📖',
    app: {
      tr: 'E-kitap',
      en: 'E-books',
      de: 'E-Books',
      ar: 'الكتب الإلكترونية',
      fr: 'Liseuse',
      es: 'Libros',
      ja: '電子書籍',
      ko: '전자책',
    },
    text: {
      tr: 'Bugün 10 sayfa okudun, harika!',
      en: 'You read 10 pages today. Nice!',
      de: 'Heute 10 Seiten gelesen. Stark!',
      ar: 'قرأت 10 صفحات اليوم، رائع!',
      fr: "10 pages lues aujourd'hui, bravo !",
      es: '¡Hoy leíste 10 páginas, genial!',
      ja: '今日は10ページ読みました。すごい！',
      ko: '오늘 10페이지 읽었어요. 멋져요!',
    },
  },
  {
    icon: '🏃',
    app: { tr: 'Koşu', en: 'Running', de: 'Laufen', ar: 'الجري', fr: 'Course', es: 'Carrera', ja: 'ランニング', ko: '러닝' },
    text: {
      tr: '3 km’lik koşun kaydedildi',
      en: 'Your 2-mile run is saved',
      de: 'Dein 3-km-Lauf ist gespeichert',
      ar: 'تم حفظ جريك لمسافة 3 كم',
      fr: 'Ta course de 3 km est enregistrée',
      es: 'Tu carrera de 3 km quedó guardada',
      ja: '3kmのランを記録しました',
      ko: '3km 러닝이 기록됐어요',
    },
  },
  {
    icon: '🎮',
    app: { tr: 'Oyun', en: 'Games', de: 'Spiele', ar: 'الألعاب', fr: 'Jeux', es: 'Juegos', ja: 'ゲーム', ko: '게임' },
    text: {
      tr: 'Günlük görevler yenilendi',
      en: 'Daily quests have been refreshed',
      de: 'Neue Tagesaufgaben sind da',
      ar: 'تم تجديد المهام اليومية',
      fr: 'Nouvelles quêtes du jour dispo',
      es: 'Se renovaron las misiones diarias',
      ja: 'デイリーミッションが更新されました',
      ko: '일일 퀘스트가 초기화됐어요',
    },
  },
  {
    icon: '🍕',
    app: {
      tr: 'Ev arkadaşı',
      en: 'Roommate',
      de: 'Mitbewohner',
      ar: 'زميل السكن',
      fr: 'Coloc',
      es: 'Compañero de casa',
      ja: 'ルームメイト',
      ko: '룸메이트',
    },
    text: {
      tr: 'Pizza söylüyorum, ister misin?',
      en: 'Ordering pizza, want some?',
      de: 'Ich bestell Pizza, willst du auch?',
      ar: 'سأطلب بيتزا، هل تريد؟',
      fr: "Je commande une pizza, t'en veux ?",
      es: 'Voy a pedir pizza, ¿quieres?',
      ja: 'ピザ頼むけど、いる？',
      ko: '피자 시킬 건데, 먹을래?',
    },
  },
  {
    icon: '🚗',
    app: {
      tr: 'Otopark',
      en: 'Parking',
      de: 'Parkhaus',
      ar: 'موقف السيارات',
      fr: 'Parking',
      es: 'Estacionamiento',
      ja: '駐車場',
      ko: '주차장',
    },
    text: {
      tr: 'Aracın 2. katta, B bölümünde',
      en: 'Your car is on level 2, section B',
      de: 'Dein Auto steht auf Ebene 2, Bereich B',
      ar: 'سيارتك في الطابق الثاني',
      fr: 'Ta voiture est au niveau 2, zone B',
      es: 'Tu vehículo está en el nivel 2, zona B',
      ja: 'お車は2階のBエリアです',
      ko: '차량 위치: 2층 B구역',
    },
  },
  {
    icon: '🌡️',
    app: {
      tr: 'Termostat',
      en: 'Thermostat',
      de: 'Thermostat',
      ar: 'منظم الحرارة',
      fr: 'Thermostat',
      es: 'Termostato',
      ja: 'エアコン',
      ko: '보일러',
    },
    text: {
      tr: 'Ev 22 dereceye ısındı',
      en: 'Home warmed up to 72°',
      de: 'Die Wohnung hat jetzt 22 Grad',
      ar: 'وصلت حرارة البيت إلى 22 درجة',
      fr: 'La maison est à 22 degrés',
      es: 'La casa ya está a 22 grados',
      ja: '室温が22°になりました',
      ko: '집이 22도로 따뜻해졌어요',
    },
  },
  {
    icon: '🎈',
    app: {
      tr: 'Hatırlatıcı',
      en: 'Reminders',
      de: 'Erinnerungen',
      ar: 'التذكيرات',
      fr: 'Rappels',
      es: 'Recordatorios',
      ja: 'リマインダー',
      ko: '미리 알림',
    },
    text: {
      tr: 'Parti için balon almayı unutma',
      en: "Don't forget balloons for the party",
      de: 'Luftballons für die Party kaufen',
      ar: 'لا تنسَ شراء البالونات للحفلة',
      fr: 'Pense aux ballons pour la fête',
      es: 'No olvides los globos para la fiesta',
      ja: 'パーティー用の風船を忘れずに',
      ko: '파티용 풍선 사는 거 잊지 마세요',
    },
  },
  {
    icon: '🐶',
    app: {
      tr: 'Köpek bakıcısı',
      en: 'Dog walker',
      de: 'Hundesitter',
      ar: 'جليسة الكلب',
      fr: 'Promeneur de chien',
      es: 'Paseador de perros',
      ja: 'ドッグシッター',
      ko: '펫시터',
    },
    text: {
      tr: 'Köpeğin parkta çok eğlendi!',
      en: 'Your pup had a blast at the park!',
      de: 'Dein Hund hatte Spaß im Park!',
      ar: 'استمتع كلبك كثيرًا في الحديقة!',
      fr: 'Ton chien a adoré le parc !',
      es: '¡Tu perro disfrutó mucho del parque!',
      ja: 'ワンちゃん、公園で大はしゃぎでした！',
      ko: '강아지가 공원에서 신나게 놀았어요!',
    },
  },
  {
    icon: '📻',
    app: { tr: 'Radyo', en: 'Radio', de: 'Radio', ar: 'الراديو', fr: 'Radio', es: 'Radio', ja: 'ラジオ', ko: '라디오' },
    text: {
      tr: 'En sevdiğin program başladı',
      en: 'Your favorite show just started',
      de: 'Deine Lieblingssendung läuft',
      ar: 'بدأ برنامجك المفضل',
      fr: 'Ton émission préférée commence',
      es: 'Empezó tu programa favorito',
      ja: 'お気に入りの番組が始まりました',
      ko: '좋아하는 프로그램이 시작됐어요',
    },
  },
  {
    icon: '🧩',
    app: {
      tr: 'Bulmaca',
      en: 'Puzzles',
      de: 'Rätsel',
      ar: 'الألغاز',
      fr: 'Casse-tête',
      es: 'Crucigrama',
      ja: 'パズル',
      ko: '퍼즐',
    },
    text: {
      tr: 'Günün bulmacası hazır',
      en: "Today's puzzle is ready",
      de: 'Das Rätsel des Tages ist da',
      ar: 'لغز اليوم جاهز',
      fr: 'Le casse-tête du jour est prêt',
      es: 'El crucigrama del día está listo',
      ja: '今日のパズルが届きました',
      ko: '오늘의 퍼즐이 준비됐어요',
    },
  },
  {
    icon: '💡',
    app: {
      tr: 'Akıllı ev',
      en: 'Smart home',
      de: 'Smart Home',
      ar: 'المنزل الذكي',
      fr: 'Maison connectée',
      es: 'Casa inteligente',
      ja: 'スマートホーム',
      ko: '스마트홈',
    },
    text: {
      tr: 'Balkon ışıkları 19.00’da yandı',
      en: 'Porch lights came on at 7 PM',
      de: 'Balkonlicht ging um 19 Uhr an',
      ar: 'أُضيئت أنوار الشرفة في السابعة مساءً',
      fr: 'Lumières du balcon allumées à 19 h',
      es: 'Luces del balcón encendidas a las 19:00',
      ja: 'ベランダの照明が19:00に点灯しました',
      ko: '발코니 조명이 19:00에 켜졌어요',
    },
  },
  {
    icon: '⚽️',
    app: { tr: 'Maç', en: 'Soccer', de: 'Fußball', ar: 'المباراة', fr: 'Match', es: 'Partido', ja: 'サッカー', ko: '축구' },
    text: {
      tr: 'Maç 20.00’de başlıyor',
      en: 'Kickoff at 8 PM',
      de: 'Anpfiff um 20 Uhr',
      ar: 'تبدأ المباراة في الثامنة مساءً',
      fr: "Coup d'envoi à 20 h",
      es: 'El partido empieza a las 20:00',
      ja: '試合は20:00キックオフ',
      ko: '경기가 20:00에 시작해요',
    },
  },
  {
    icon: '🎨',
    app: {
      tr: 'Resim kursu',
      en: 'Art class',
      de: 'Malkurs',
      ar: 'دورة الرسم',
      fr: 'Cours de dessin',
      es: 'Clase de pintura',
      ja: '絵画教室',
      ko: '미술 학원',
    },
    text: {
      tr: 'Ders yarın 18.00’de, fırçanı unutma',
      en: 'Class tomorrow at 6 PM, bring a brush',
      de: 'Morgen 18 Uhr, Pinsel nicht vergessen',
      ar: 'الدرس غدًا في السادسة، لا تنسَ فرشاتك',
      fr: 'Cours demain à 18 h, pense au pinceau',
      es: 'Clase mañana a las 18:00, trae tu pincel',
      ja: '明日18:00から。筆を忘れずに',
      ko: '내일 18:00 수업, 붓 챙기세요',
    },
  },
  {
    icon: '🧶',
    app: { tr: 'Anneannem', en: 'Grandma', de: 'Oma', ar: 'جدتي', fr: 'Mamie', es: 'Abuela', ja: 'おばあちゃん', ko: '할머니' },
    text: {
      tr: 'Sana yeni bir atkı örüyorum',
      en: "I'm knitting you a new scarf",
      de: 'Ich stricke dir einen neuen Schal',
      ar: 'أحيك لك وشاحًا جديدًا',
      fr: 'Je te tricote une nouvelle écharpe',
      es: 'Te estoy tejiendo una bufanda nueva',
      ja: '新しいマフラー、編んでるからね',
      ko: '새 목도리 떠 주고 있단다',
    },
  },
  {
    icon: '🌻',
    app: { tr: 'Teyzem', en: 'Auntie', de: 'Tante', ar: 'خالتي', fr: 'Tatie', es: 'Tía', ja: 'おばさん', ko: '이모' },
    text: {
      tr: 'Bahçeden domates gönderdim',
      en: 'Sent you tomatoes from the garden',
      de: 'Hab dir Tomaten aus dem Garten geschickt',
      ar: 'أرسلت لك طماطم من الحديقة',
      fr: "Je t'ai envoyé des tomates du jardin",
      es: 'Te mandé tomates de la huerta',
      ja: '畑のトマト、送ったよ',
      ko: '텃밭에서 딴 토마토 보냈어',
    },
  },
  {
    icon: '🚕',
    app: { tr: 'Taksi', en: 'Taxi', de: 'Taxi', ar: 'سيارة الأجرة', fr: 'Taxi', es: 'Taxi', ja: 'タクシー', ko: '택시' },
    text: {
      tr: 'Taksin kapıda',
      en: 'Your taxi is outside',
      de: 'Dein Taxi ist da',
      ar: 'سيارة الأجرة عند الباب',
      fr: 'Ton taxi est devant la porte',
      es: 'Tu taxi está en la puerta',
      ja: 'タクシーが到着しました',
      ko: '택시가 도착했어요',
    },
  },
  {
    icon: '🖨️',
    app: {
      tr: 'Yazıcı',
      en: 'Printer',
      de: 'Drucker',
      ar: 'الطابعة',
      fr: 'Imprimante',
      es: 'Impresora',
      ja: 'プリンター',
      ko: '프린터',
    },
    text: {
      tr: 'Belgen yazdırıldı (3 sayfa)',
      en: 'Your document printed (3 pages)',
      de: 'Dokument gedruckt (3 Seiten)',
      ar: 'تمت طباعة مستندك (3 صفحات)',
      fr: 'Document imprimé (3 pages)',
      es: 'Documento impreso (3 páginas)',
      ja: '印刷が完了しました（3ページ）',
      ko: '문서 인쇄 완료 (3페이지)',
    },
  },
  {
    icon: '🍽️',
    app: {
      tr: 'Bulaşık makinesi',
      en: 'Dishwasher',
      de: 'Spülmaschine',
      ar: 'غسالة الصحون',
      fr: 'Lave-vaisselle',
      es: 'Lavavajillas',
      ja: '食洗機',
      ko: '식기세척기',
    },
    text: {
      tr: 'Yıkama bitti, tabaklar pırıl pırıl',
      en: 'Cycle done, the dishes are sparkling',
      de: 'Fertig, das Geschirr glänzt',
      ar: 'انتهى الغسيل، والصحون تلمع',
      fr: 'Lavage terminé, tout brille',
      es: 'Lavado listo, los platos relucen',
      ja: '洗浄完了、お皿がピカピカです',
      ko: '세척 완료, 그릇이 반짝반짝해요',
    },
  },
  {
    icon: '🎉',
    app: {
      tr: 'Arkadaş grubu',
      en: 'Friends group',
      de: 'Freundesgruppe',
      ar: 'مجموعة الأصدقاء',
      fr: 'Groupe des potes',
      es: 'Grupo de amigos',
      ja: '友だちグループ',
      ko: '친구 단톡방',
    },
    text: {
      tr: 'Cuma akşamı herkes bizde!',
      en: 'Friday night, everyone at our place!',
      de: 'Freitagabend sind alle bei uns!',
      ar: 'مساء الجمعة، الجميع عندنا!',
      fr: 'Vendredi soir, tous chez nous !',
      es: '¡El viernes, todos a mi casa!',
      ja: '金曜の夜はみんなうちに集合！',
      ko: '금요일 밤, 다들 우리 집으로!',
    },
  },
  {
    icon: '🦉',
    app: {
      tr: 'Kitap kulübü',
      en: 'Book club',
      de: 'Buchclub',
      ar: 'نادي الكتاب',
      fr: 'Club de lecture',
      es: 'Club de lectura',
      ja: '読書会',
      ko: '독서 모임',
    },
    text: {
      tr: 'Bu ayın kitabı seçildi',
      en: "This month's book has been picked",
      de: 'Das Buch des Monats steht fest',
      ar: 'تم اختيار كتاب هذا الشهر',
      fr: 'Le livre du mois est choisi',
      es: 'Ya se eligió el libro del mes',
      ja: '今月の本が決まりました',
      ko: '이번 달 책이 정해졌어요',
    },
  },
  {
    icon: '🌈',
    app: {
      tr: 'Hava durumu',
      en: 'Weather',
      de: 'Wetter',
      ar: 'الطقس',
      fr: 'Météo',
      es: 'Pronóstico',
      ja: '天気',
      ko: '날씨',
    },
    text: {
      tr: 'Akşama gökkuşağı çıkabilir',
      en: 'Rainbow possible this evening',
      de: 'Heute Abend vielleicht ein Regenbogen',
      ar: 'قد يظهر قوس قزح مساءً',
      fr: 'Arc-en-ciel possible ce soir',
      es: 'Posible arcoíris esta tarde',
      ja: '夕方、虹が見られるかも',
      ko: '저녁에 무지개가 뜰 수도 있어요',
    },
  },
];

/** The face at the top of a chat screenshot. */
export const AVATARS: readonly string[] = ['🙂', '😎', '🤓', '😺', '🐻', '🦊', '🐼', '🐸', '🌻', '⚽️', '🎧', '🍕'];

/** What a post may wear in a corner, like a sticker on a story. */
export const STICKERS: readonly string[] = [
  '✨',
  '🔥',
  '💯',
  '👀',
  '😂',
  '😅',
  '🙃',
  '🤯',
  '😴',
  '👍',
  '🎉',
  '⭐️',
  '💥',
  '🌈',
  '💫',
  '🤌',
];
